

data = [
	('修真世界 World of Cultivation Chaper Two Hundred and Fifty Eight “Bao Yi Explaining”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Fifty Five “New Sky Glass Wave”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Fifty Nine “Meteor Void Fire”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Fifty Seven “One Small Step”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Fifty Six “Variable”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Seventy Eight “The Insane Outer Hall”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Seventy Five “Circle Kill”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Seventy Four “You Eat Meat, We’ll Drink Soup”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Seventy Seven “Detection”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Seventy Six “An Unparalleled Good Bird”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Seventy Three “The Critical Sword Point”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Sixty Four “The Rudimentary Form”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Sixty One “Ambush!”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Sixty Three “Zuo Mo’s Determination”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Sixty Two “Unprofitable Business”', None, None, None, ''),
	('修真世界 World of Cultivation Chaper Two Hundred and Sixty “The Terrifying Female Xiu”', None, None, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Eight “The Scalping Zombie”', None, 88, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Five “Coming Up to The Door”', None, 85, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Four “For Jingshi”', None, 84, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Nine “Silly Yao”', None, 89, None, ''),
	('修真世界 World of Cultivation Chapter Eighty One “Ling Ying Sect”', None, 81, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Seven “Strong Attack Vs Strong Attack”', None, 87, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Six “Wen Fei”', None, 86, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Three “Brute Force”', None, 83, None, ''),
	('修真世界 World of Cultivation Chapter Eighty Two “If People Don’t Get Ill-gotten Gains, They Won’t Be Rich!”', None, 82, None, ''),
	('修真世界 World of Cultivation Chapter Eighty “A Transformation On The Gravestone”', None, 80, None, ''),
	('修真世界 World of Cultivation Chapter Eleven to Fifteen', None, 11, None, ''),
	('修真世界 World of Cultivation Chapter Ninety', None, 90, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Eight “Zuo Mo’s Fury and Heartache”', None, 98, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Five “A Method Forced Out”', None, 95, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Four “Why Do My Eyes Always Have Tears”', None, 94, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Nine “Seal Soldier”', None, 99, None, ''),
	('修真世界 World of Cultivation Chapter Ninety One “Merging Sword Essences”', None, 91, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Seven “Lin Yuan’s Plotting”', None, 97, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Six “A Cold Light”', None, 96, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Three “Stalagmite Fire”', None, 93, None, ''),
	('修真世界 World of Cultivation Chapter Ninety Two “Yin Fire Bead Chapter”', None, 92, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eight “Two Paths”', None, 108, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighteen “Between Happiness and Grief”', None, 118, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Eight “Entering The Formation”', None, 188, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Five “The Power of the Golden Crow Fire!”', None, 185, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Four “Mantis and Oriole”', None, 184, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Nine “Brewing”', None, 189, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty One “Familiar Guests”', None, 181, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Seven “Two Hours”', None, 187, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Six “Sword Formation”', None, 186, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Three “Black Wind Bandits”', None, 183, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty Two “Discovery!”', None, 182, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eighty “[Great Thousand Leaf Hands]”', None, 180, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Eleven “For Tasty Food”', None, 111, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifteen “Exploring the Sword Cave Again”', None, 115, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Eight “Seclusion”', None, 158, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Five “Collision”', None, 155, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Four “Moon Chime Sound Storm”', None, 154, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Nine “Gains”', None, 159, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty One “Comprehension”', None, 151, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Seven “Unexpected”', None, 157, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Six “Brothers in Difficulty”', None, 156, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Three “Soul-Tethered Talisman”', None, 153, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty Two “Stardust”', None, 152, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fifty “New Target”', None, 150, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Five “Mo Matrix and Yao Seed”', None, 105, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Eight “Seal Soldier”', None, 148, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Five “Nan Men Yang! A Real Man!”', None, 145, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Four “Strange”', None, 144, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Nine “Fire”', None, 149, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty One “Zong Ming Yan VS Zuo Mo”', None, 141, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Seven “Born to Battle”', None, 147, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Six “Zuo Mo’s Sorrowful Indignation”', None, 146, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Three “Heavyweight News”', None, 143, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Forty Two “Seven Plum Sword”', None, 142, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Four “Hesitation”', None, 104, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Fourteen “Sword Test Conference?”', None, 114, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Nine “Inky Black Lotus Seed”', None, 109, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Nineteen “Intelligence”', None, 119, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Eight “What Is The Situation?”', None, 198, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Five “Two Transactions”', None, 195, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Four “Golden Armor Guards”', None, 194, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Nine “Beast Service Card”', None, 199, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety One “The First Battle of the Yin Fire Bead”', None, 191, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Seven “Ningmai!”', None, 197, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Six “News”', None, 196, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Three “Bountiful Harvest”', None, 193, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety Two “Buddha Sound Hoop”', None, 192, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ninety “Going All In”', None, 190, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and One “All In!”', None, 101, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seven “Seeing Shixiong Again”', None, 107, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventeen “What Happened”', None, 117, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Eight “Void Pass”', None, 178, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Fire “Fire!”', None, 170, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Four “Macro Golden Crow Formation”', None, 174, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Nine “Gravestone”', None, 179, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy One “Micro Void Arrow”', None, 171, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Seven “Business”', None, 177, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Six “Brute Strength!”', None, 176, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Three “Pulling Into The Fold”', None, 173, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy Two “Pu Yao Awakening”', None, 172, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Seventy “Nan Ming Zi”', None, 170, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Six “The Half-Finished Product Processing Maniac”', None, 106, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixteen “Yin Splinter”', None, 116, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Eight “Desolate Wood Reef”', None, 168, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Five “Wu Kong Expansion”', None, 165, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Four “Sword Essence Formation”', None, 164, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Nine “Wealth Coming From the Sky”', None, 169, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty One “Forging The Sword Billet”', None, 161, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Seven “The Places Are The Same, The People Are Not”', None, 167, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Six “This Land Is Great”', None, 166, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Three “People Don’t Do This”', None, 163, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty Two “Reselling”', None, 162, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Sixty “Intense Fire Dan”', None, 160, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Ten “Four-Turn Fire Formation!”', None, 110, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirteen “Formation Disks”', None, 113, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Eight “Aggravation and Pleasure”', None, 138, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Five “Great Pine Pavilion”', None, 135, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Four “Before The Battle”', None, 134, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Nine “Formation-Defense-Style”', None, 139, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty One “The Wondrous Abilities of The Five Colored Pagoda”', None, 131, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Seven “Each Person’s Opponent”', None, 137, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Six “Heart Turn Sword Essence”', None, 136, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Three “Pei Yuan Ran’s Bad Mood”', None, 133, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty Two “Healing Wounds”', None, 132, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Thirty “Seeing Lin Qian Again”', None, 130, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Three “Inspiration”', None, 103, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twelve “Yin Fiends”', None, 112, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Eight “The Hundred Treasure Flying Pavilion”', None, 128, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Five “Final Kill”', None, 125, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Four “Multiple Shadows and Intense Fire”', None, 124, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Nine “Five Colored Pagoda”', None, 129, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty One “Wager”', None, 121, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Seven “Everyone Is Troubled”', None, 127, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Six “Cross-Examination”', None, 126, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Three “Battle Start”', None, 123, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty Two “Bet”', None, 122, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Twenty “An Irresistible Temptation!”', None, 120, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and Two “Couldn’t Understand”', None, 102, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred and and Forty “[Self Separation]”', None, 100, None, ''),
	('修真世界 World of Cultivation Chapter One Hundred “Bloody Chang Heng”', None, 100, None, ''),
	('修真世界 World of Cultivation Chapter One to Five', None, 1, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Eight “Making A Move”', None, 78, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Five “Haze”', None, 75, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Four “Nightmare”', None, 74, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Nine “Zuo Mo’s Decision”', None, 79, None, ''),
	('修真世界 World of Cultivation Chapter Seventy One “A New Experiment”', None, 71, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Seven “Plot”', None, 77, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Six “Body Cultivating Sword Formation”', None, 76, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Three “Inspiritation In An Emergency”', None, 73, None, ''),
	('修真世界 World of Cultivation Chapter Seventy Two “Seeing Guests”', None, 72, None, ''),
	('修真世界 World of Cultivation Chapter Seventy “The Yin Bead”', None, 70, None, ''),
	('修真世界 World of Cultivation Chapter Six to Ten', None, 6, None, ''),
	('修真世界 World of Cultivation Chapter Sixteen to Twenty', None, 16, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Eight “A Rare Leisure”', None, 68, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Five “Li Water Burning Heavens”', None, 65, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Four “Caught It!”', None, 64, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Nine “Zuo Mo Drooling”', None, 69, None, ''),
	('修真世界 World of Cultivation Chapter Sixty One “Planning”', None, 61, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Seven “Questions and Answers”', None, 67, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Six “Awakening”', None, 66, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Three “The Sect Assessment”', None, 63, None, ''),
	('修真世界 World of Cultivation Chapter Sixty Two “Lin Qian”', None, 62, None, ''),
	('修真世界 World of Cultivation Chapter Sixty “Comprehension”', None, 60, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Eight “Brute!”', None, 308, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Eighteen “Human Wrecking Ball”', None, 318, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Eleven “At The Door”', None, 311, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Five “Entrance to the Jie River”', None, 305, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Four “Great Day Mo Physique”', None, 304, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Fourteen “Successive Mo Kill”', None, 314, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Nine “The Greatest Gain”', None, 309, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Nineteen “If You Want a Fight, Fight!”', None, 319, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and One “Desperate Situation”', None, 301, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Seven “Bright Water City”', None, 307, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Seventeen “Clouds Gathering”', None, 317, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Six “Spells Entering Formation”', None, 306, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Sixteen “Enormous Change”', None, 316, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Ten “The Past Grievances”', None, 310, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Thirteen “Serpent Transformation”', None, 313, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Three “Leaving Little Mountain Jie”', None, 303, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twelve “Zuo Mo’s Fury”', None, 312, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Eight “Upheaval of Sword Cave”', None, 328, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Five “This Is … …”', None, 325, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Four “Ten Finger Prison”', None, 324, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Nine “The Name Of Tenth Grade”', None, 329, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty One “Ambush”', None, 321, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Seven “Twin Butterfly”', None, 327, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Six “Ten Thousand Year Old Ancient Battlefield”', None, 326, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Three “Core Formation”', None, 323, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty Two “Victory!”', None, 322, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Twenty “Move Out”', None, 320, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred and Two “A New Beginning”', None, 302, None, ''),
	('修真世界 World of Cultivation Chapter Three Hundred “Sacrifice”', None, 300, None, ''),
	('修真世界 World of Cultivation Chapter Twenty One to Twenty Five', None, 21, None, ''),
	('修真世界 World of Cultivation Chapter Twenty Six to Thirty', None, 26, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eight Six “Arrival!”', None, 214, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eight “Blood Void Movement”', None, 208, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighteen “Spoils of Victory”', None, 218, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Eight “Fight!”', None, 288, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Five “Comprehensions Gained From Forging”', None, 285, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Four “Great Formation!”', None, 284, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Nine “The Reappearance of the Sound Storm”', None, 289, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty One “Gradual Advance”', None, 281, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Seven “Cloud Formation Silk”', None, 287, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Three “Lil’ Fire”', None, 283, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty Two “Fire Sickle Rock”', None, 282, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eighty “Prelude”', None, 280, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Eleven “Trash and Poor Ghosts”', None, 211, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fifteen “Sustain Battle Through Battle”', None, 215, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fifty Four “The Metamorphosis of Jade Metal Head”', None, 254, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fifty One “Crazy Zuo Mo”', None, 251, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fifty Three “Golden Crow Walls”', None, 253, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fifty Two “Fire Paper Method”', None, 252, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fifty “Pu Yao’s Insane Suggestion”', None, 250, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Five “War Chess”', None, 205, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Eight “The Problem of Settlement”', None, 248, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Five “First Battle”', None, 245, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Four “Censensus”', None, 244, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Nine “A New Plan”', None, 249, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty One “City Construction”', None, 241, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Seven “Rainbow Mirage Light”', None, 247, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Six “Ambush”', None, 246, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Three “Jade Scroll”', None, 243, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty Two “Bao Yi”', None, 242, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Forty “What Was Going On?”', None, 240, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Four “Improvement”', None, 204, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Fourteen “A Mountain Of Problems”', None, 214, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Nine “Ma Fan”', None, 209, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Nineteen “Rewards Conference”', None, 219, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Eight “Insanity”', None, 298, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Five “Battle General!”', None, 295, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Four “The Return of Lil’ Miss”', None, 294, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Nine “The Great Formation and Sonic Lightning Walnut”', None, 299, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety One “Hong Jun Xuan”', None, 291, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Seven “Hardship Guard Armor”', None, 297, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Six “Silver”', None, 296, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Three “Great Unexpected Wealth”', None, 293, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety Two “Little Mo Kill”', None, 292, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ninety “The Guard Camp Steps Onto the Stage”', None, 290, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and One “Armed to the Teeth”', None, 201, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Seven “Moon Eye Blackwater Beast”', None, 207, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Seventeen “Killing Moves and Ma Fan”', None, 217, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Seventy Nine “Transaction”', None, 279, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Seventy One “Opportunity”', None, 271, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Seventy Two “Huang Zhuo Guang”', None, 272, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Seventy “Great Harvest!”', None, 270, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Six “What Was That?”', None, 206, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Sixteen “Gongsun Cha’s First Battle”', None, 216, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Sixty Eight “Nine Turn Sky Soil Disk”', None, 268, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Sixty Five “Silly Bird’s Shocking Change!”', None, 265, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Sixty Nine “Who The Mother F***ing Are You”', None, 269, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Sixty Seven “Ambush”', None, 267, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Sixty Six “A Little Harvest”', None, 266, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Ten “Collapse of Order”', None, 210, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirteen “Ma Fan Reaching Target”', None, 213, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty  “Sky Glass Wave”', None, 230, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Eight “Sonic Lightning Walnut”', None, 238, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Five “The Butcher’s Three Section Wave Killing Charge”', None, 235, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Four “Fury and Killing Intent”', None, 234, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Nine “Yao Visiting Wu Kong”', None, 239, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty One “Warning”', None, 231, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Seven “Reconstructing The Body”', None, 237, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Six “New Life?”', None, 236, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thirty Three “Bloody Horned Great Serpent”', None, 233, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Three “Date Seed Ship”', None, 203, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Thrity Two “Gongsun Cha’s Insane War Tactics”', None, 200, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Eight “Ma Fan’s Decisiveness”', None, 228, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Five “Breakthrough in Body Cultivation”', None, 225, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Four “Pu Yao’s Teaching”', None, 224, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Nine “Formation Breakthrough”', None, 229, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty One “What Is Pu Yao Doing?”', None, 221, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Seven “Internal Orders”', None, 227, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Six “The Stage of Two Mountains”', None, 226, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Three “Another Transaction”', None, 223, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty Two “Lil’ Pagoda’s Levelling Up”', None, 222, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twenty “The Fatal Rotten Metal Silver”', None, 220, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Twleve “Ge Is Pragmatic”', None, 200, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred and Two “Territory Intrusion”', None, 202, None, ''),
	('修真世界 World of Cultivation Chapter Two Hundred “Peddling”', None, 200, None, ''),
]

