

data = [
	('3 Chapters today', None, 3.0, None, ''),
	('3 Chapters~!', None, 3.0, None, ''),
	('3 Chapters~~~~', None, 3.0, None, ''),
	('3 DMCA’s received from Kadokawa', None, 3.0, None, ''),
	('3 Day break', None, 3.0, None, ''),
	('3 fast 5 me', None, 3.0, None, ''),
	('3 month anniversary! Plus Chapter 31 and 32!', None, 31.0, None, ''),
	('3 retpahC nrobnU – Why? Because I can.', None, 3.0, None, ''),
	('3 trap 4 lov drolrevO', None, 3.0, None, ''),
	('3,000,000 Site Views', None, 3.0, None, ''),
	('3-2 Is available!', None, 3.0, 2.0, ''),
	('3-4 Available', None, 3.0, 4.0, ''),
	('3-5 Available (A Larger update coming later this week)', None, 3.0, 5.0, ''),
	('3-6 Is Now Available!', None, 3.0, 6.0, ''),
	('3. Alternate World’s System', None, 3.0, None, ''),
	('3. Farming (for once) quickly', None, 3.0, None, ''),
	('3.- Battle against the Dark Worm', None, 3.0, None, ''),
	('3.01 – Tinnio {Clink}', None, 3.01, None, ''),
	('3.02 – Dulcis Sermo {Sweet Talk}', None, 3.02, None, ''),
	('3.03 – Finem Carrum {End of the Cart}', None, 3.03, None, ''),
	('3.04 – Somniculosus {Dreamy}', None, 3.04, None, ''),
	('3.1 – Rursum Obdormivit {Asleep Again}', None, 3.1, None, ''),
	('3.2 – Domesticam Vinculum {Familial Ties}', None, 3.2, None, ''),
	('3.3 – Sagitta Profectus Scopum {An Arrow to its Target}', None, 3.3, None, ''),
	('3.4 – Quietus Verba {Quiet Words}', None, 3.4, None, ''),
	('3.5 – Seditio {Rebellion}', None, 3.5, None, ''),
	('3.6 – Navis in Nimbosus Aquas {A Ship on Stormy Waters}', None, 3.6, None, ''),
	('3.7 – Artis et Pugna {Art and Combat}', None, 3.7, None, ''),
	('3/11 The Wave’s first crest', None, 3.0, None, ''),
	('3/11/11', None, None, None, ''),
	('34th Chapter Released!', None, 34.0, None, ''),
	('35th Chapter Released!', None, 35.0, None, ''),
	('36th Chapter Released!', None, 36.0, None, ''),
	('39—Legend of Sun Knight V1C1: In-Training, Part 1—Vice-Captain', 1.0, 1.0, 1.0, ''),
	('39—Legend of Sun Knight V1C1: In-Training, Part 2—Judgment Knight', 1.0, 1.0, 2.0, ''),
	('39—Legend of Sun Knight V1C1: In-Training, Part 3—Sun Knight', 1.0, 1.0, 3.0, ''),
	('39—Legend of Sun Knight V1C2: My… Part 2—Brother', 1.0, 2.0, 2.0, ''),
	('39—Legend of Sun Knight V1C2: My… Part 3—Companion', 1.0, 2.0, 3.0, ''),
	('39—Legend of Sun Knight V1C2: My…, Part 1—Father', 1.0, 2.0, 1.0, ''),
	('39—Legend of Sun Knight V1C3: Secret… Part 1—The Debt Owed by Whom', 1.0, 3.0, 1.0, ''),
	('39—Legend of Sun Knight V1C3: Secret… Part 2—What Kind of Fragrance', 1.0, 3.0, 2.0, ''),
	('39—Legend of Sun Knight V1C3: Secret… Part 3—The Demon King is… Shh!', 1.0, 3.0, 3.0, ''),
	('39—Legend of Sun Knight V1C4: Teacher’s… Part 1—True Love', 1.0, 4.0, 1.0, ''),
	('3Fast5Me', None, 3.0, None, ''),
	('3rd Month Recap', None, 3.0, None, ''),
	('3rd Story Choosing a Weapon', None, 3.0, None, ''),
]

