

data = [
	('[ ensemble stars ] lionheart (vol. 3 novel short story) part 1', 3.0, None, 1.0, ''),
	('[ ensemble stars ] lionheart (vol. 3 novel short story) part 2', 3.0, None, 2.0, ''),
	('[ ensemble stars ] scout! rainy season’s blossom chp. 1', None, 1.0, None, ''),
	('[ k-pop translation : 2pm private photobook sales notice ]', None, 2.0, None, ''),
	('[ k-pop translation : love planet: exo with you ] 160114 KAI’S BIRTHDAY SPECIAL', None, 160114.0, None, ''),
	('[ lyrics : burning with u by x.i.p for tokimeki restaurant ][ romaji lyrics + english translation ]', None, None, None, ''),
	('[ lyrics : line of derivation by love solfege feat. marie ][ romaji + english translation ]', None, None, None, ''),
	('[ lyrics : lorelei by monaca:factory (10日P) feat. IA ][ romaji + english translation ]', None, 10.0, None, ''),
	('[ lyrics : road of gold by mutsuki hijiri (cv. kenn) from scared rider xechs (romaji + english translation) ]', None, None, None, ''),
	('[ lyrics : vocaloid ] angelite (romaji + english translation)', None, None, None, ''),
	('[ lyrics ] kokia – kawaranai koto ~since 1976~ (english translation)', None, 1976.0, None, ''),
	('[ lyrics ] umetora, wotamin – call your name in the bad rain (romaji + english translation)', None, None, None, ''),
	('[ manga : shinmai maou no testament arashi! chp. 15 ]', None, 15.0, None, ''),
	('[ novel : fate/prototype sougin no fragments ] little lady act 1 part 1/4', None, 1.0, 1.0, ''),
	('[ novel : fate/prototype sougin no fragments ] little lady act 1 part 2/4', None, 1.0, 2.0, ''),
	('[ novel : fate/prototype sougin no fragments ] little lady act 2 part 1', None, 2.0, 1.0, ''),
	('[ novel : fate/prototype sougin no fragments ] little lady act 2 part 2', None, 2.0, 2.0, ''),
	('[ novel : fate/prototype sougin no fragments ] little lady act 2 part 3 (final)', None, 2.0, 3.0, ''),
	('[ novel : fate/prototype sougin no fragments ] little lady act 3 part 1', None, 3.0, 1.0, ''),
	('[ novel : fate/prototype sougin no fragments ] masterlist', None, None, None, ''),
	('[ novel : fate/prototype sougin no fragments ] vol. 1 bonus comic', 1.0, None, None, ''),
	('[ novel : shimai maou no testament ] chisato short story ( vol. 8 extra )', 8.0, None, None, 'extra )'),
	('[ novel : shimai maou no testament ] p. 267 – 273 (part of chp. 7 & 8)', None, 7, 267, ''),
	('[ novel : shimai maou no testament ] p. 278 – 283 (part of chp. 8)', None, 8, 278.0, ''),
	('[ novel : shimai maou no testament ] vol. 8 part 3 chp. 1 – 3', 8.0, 1.0, 3.0, ''),
	('[ novel : shimai maou no testament ] vol. 9 prologue chp. 6', 9.0, 6.0, None, 'prologue chp. 6'),
	('[ novel : shimai maou no testament ] vol. 9, part 3 chp 7', 9.0, 7.0, 3.0, ''),
	('[ shinmai maou no testament ] vol. 8 & 9 afterwords + vol. 10 preview', 8.0, 9.0, None, 'afterwords + vol. 10 preview'),
	('[18+ NSFW] Elf Tensei:  Chapter 2, Episode 9.2 (V2C9.2)', 2.0, 2.0, 9.2, ''),
	('[18+ NSWF] Elf Tensei:  Chapter 2, Episode 4.5 (V2C4.5)', 2.0, 2.0, 4.5, ''),
	('[1st Chapter Series] 世界微尘里 A Speck Amid the Dust of the World – 木浮生 Mu Fu Sheng', None, 1.0, None, ''),
	('[1st Chapter Series]《寻郎》Searching for Husband/Lover (In Search of Love) by Ming Yue Ting Feng 明月听风', None, 1.0, None, ''),
	('[ANNIVERSARY] – 9 FRAKIN YEARS!', None, 9.0, None, ''),
	('[ANNOUNCEMENT] Officially in Hiatus; Strategist gets picked up!', None, None, None, ''),
	('[ANNOUNCEMENT] Otoko Aruji Picked up!', None, None, None, ''),
	('[ARKADIA (Takenaka Hideo)] The Evil One Exists', None, None, None, ''),
	('[Amahara Teikoku (Amahara)] World of Reversed Gender Roles', None, None, None, ''),
	('[Anime] Tenkyou no Alderamin – PV1', None, 1.0, None, ''),
	('[Announcement] About the theme.', None, None, None, ''),
	('[Announcement] Doll Dungeon Picked Up by Reitransblog~', None, None, None, ''),
	('[Announcement] Re-Uploads and Some Minor Changes', None, None, None, ''),
	('[BL NOVEL[ Kill the Lights (Chapter 10 Part 3)', None, 10.0, 3.0, ''),
	('[BL NOVEL] Amber Dream Summary', None, None, None, ''),
	("[BL NOVEL] B-shi's Repeating Day Summary", None, None, None, ''),
	('[BL NOVEL] Black Butterfly (Part 1)', None, None, 1.0, ''),
	('[BL NOVEL] Black Butterfly (Part 10)', None, None, 10.0, ''),
	('[BL NOVEL] Black Butterfly (Part 11)', None, None, 11.0, ''),
	('[BL NOVEL] Black Butterfly (Part 12)', None, None, 12.0, ''),
	('[BL NOVEL] Black Butterfly (Part 13)', None, None, 13.0, ''),
	('[BL NOVEL] Black Butterfly (Part 14)', None, None, 14.0, ''),
	('[BL NOVEL] Black Butterfly (Part 15)', None, None, 15.0, ''),
	('[BL NOVEL] Black Butterfly (Part 16)', None, None, 16.0, ''),
	('[BL NOVEL] Black Butterfly (Part 17)', None, None, 17.0, ''),
	('[BL NOVEL] Black Butterfly (Part 18)', None, None, 18.0, ''),
	('[BL NOVEL] Black Butterfly (Part 19)', None, None, 19.0, ''),
	('[BL NOVEL] Black Butterfly (Part 2)', None, None, 2.0, ''),
	('[BL NOVEL] Black Butterfly (Part 21)', None, None, 21.0, ''),
	('[BL NOVEL] Black Butterfly (Part 3)', None, None, 3.0, ''),
	('[BL NOVEL] Black Butterfly (Part 4)', None, None, 4.0, ''),
	('[BL NOVEL] Black Butterfly (Part 5)', None, None, 5.0, ''),
	('[BL NOVEL] Black Butterfly (Part 6)', None, None, 6.0, ''),
	('[BL NOVEL] Black Butterfly (Part 7)', None, None, 7.0, ''),
	('[BL NOVEL] Black Butterfly (Part 8)', None, None, 8.0, ''),
	('[BL NOVEL] Black Butterfly (Part 9)', None, None, 9.0, ''),
	('[BL NOVEL] Black Butterfly (Part. 20)', None, None, 20, ''),
	('[BL NOVEL] Black Butterfly, Where Does the Black Butterfly Go Drink Water Summary', None, None, None, ''),
	('[BL NOVEL] Kill the Lights (Chapter 10 Part 1)', None, 10.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 10 Part 2)', None, 10.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 11 Part 1)', None, 11.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 11 Part 2)', None, 11.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 11 Part 3)', None, 11.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 11 Parts 4)', None, 11.0, 4.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 12 Part 1)', None, 12.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 12 Part 3)', None, 12.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 12 Part 4)', None, 12.0, 4.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 12 Part 5)', None, 12.0, 5.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 12 Parts 2)', None, 12.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 13 Part 1)', None, 13.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 4 Part 2)', None, 4.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 4 Part 3)', None, 4.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 4 Part 4)', None, 4.0, 4.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 5 Part 1)', None, 5.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 5 Part 2)', None, 5.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 5 Part 3)', None, 5.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 5 Part 4)', None, 5.0, 4.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 6 Part 1)', None, 6.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 6 Part 2)', None, 6.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 6 Part 3)', None, 6.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 7 Part 1)', None, 7.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 7 Part 2)', None, 7.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 7 Part 3)', None, 7.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 7 Part 4)', None, 7.0, 4.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 7 Part 5)', None, 7.0, 5.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 7 Part 6)', None, 7.0, 6.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 8 Part 1)', None, 8.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 8 Part 2)', None, 8.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 8 Part 3)', None, 8.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 9 Part 1)', None, 9.0, 1.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 9 Part 2)', None, 9.0, 2.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 9 Part 3)', None, 9.0, 3.0, ''),
	('[BL NOVEL] Kill the Lights (Chapter 9 Part 4)', None, 9.0, 4.0, ''),
	('[BL NOVEL] Monsieur Park (Chapter 3 Part 1)', None, 3.0, 1.0, ''),
	('[BNM] Book 1', 1.0, None, None, ''),
	('[BNM] Boy and Girl', None, None, None, ''),
	('[BNM] Chapter 1', None, 1.0, None, ''),
	('[BNM] Chapter 10', None, 10.0, None, ''),
	('[BNM] Chapter 11', None, 11.0, None, ''),
	('[BNM] Chapter 12', None, 12.0, None, ''),
	('[BNM] Chapter 13', None, 13.0, None, ''),
	('[BNM] Chapter 14', None, 14.0, None, ''),
	('[BNM] Chapter 15', None, 15.0, None, ''),
	('[BNM] Chapter 16', None, 16.0, None, ''),
	('[BNM] Chapter 17', None, 17.0, None, ''),
	('[BNM] Chapter 18', None, 18.0, None, ''),
	('[BNM] Chapter 19', None, 19.0, None, ''),
	('[BNM] Chapter 19 Part 1', None, 19.0, 1.0, ''),
	('[BNM] Chapter 19 Part 2', None, 19.0, 2.0, ''),
	('[BNM] Chapter 2', None, 2.0, None, ''),
	('[BNM] Chapter 20', None, 20.0, None, ''),
	('[BNM] Chapter 21', None, 21.0, None, ''),
	('[BNM] Chapter 21 | [HCLS] Chapter 23', None, 21.0, None, ''),
	('[BNM] Chapter 3', None, 3.0, None, ''),
	('[BNM] Chapter 4', None, 4.0, None, ''),
	('[BNM] Chapter 5', None, 5.0, None, ''),
	('[BNM] Chapter 6', None, 6.0, None, ''),
	('[BNM] Chapter 7', None, 7.0, None, ''),
	('[BNM] Chapter 9', None, 9.0, None, ''),
	('[BNM] Prologue', None, None, None, 'Prologue'),
	('[BTS] Awkward teenage years (Ostrich 20-28)', None, 20.0, 28.0, ''),
	('[BTS] Probably needs editing (Ostrich 1-19)', None, 1.0, 19.0, ''),
	('[BenkyouKami 1.1] Finding the God', None, 1.1, None, ''),
	('[BenkyouKami 1.2] Bicycle and Destiny', None, 1.2, None, ''),
	('[BenkyouKami 1.3] Kamisama’s Treats', None, 1.3, None, ''),
	('[BenkyouKami 1.4] The Contract’s Establishment', None, 1.4, None, ''),
	('[BenkyouKami 1.5] Madoka’s Dream', None, 1.5, None, ''),
	('[BenkyouKami 1.6] Fellow Mothers', None, 1.6, None, ''),
	('[BenkyouKami 1.7] Confession To Parents', None, 1.7, None, ''),
	('[BenkyouKami 2.1] Strategic Meeting', None, 2.1, None, ''),
	('[BenkyouKami 2.2] Fake Trial', None, 2.2, None, ''),
	('[BenkyouKami 2.2] How to Receive Lessons Correctly', None, 2.2, None, ''),
	('[CCM] Perspiring Master ACTUALLY HAD A NAME', None, None, None, ''),
	('[Chang Sheng] BABY Chapter 11 – Out of control', None, 11.0, None, ''),
	('[Chang Sheng] BABY Chapter 12 – Doctor Nohman', None, 12.0, None, ''),
	('[Chang Sheng] BABY Chapter 13 – Darkness before dawn', None, 13.0, None, ''),
	('[Chang Sheng] BABY Chapter 14 – The Ultimate Weapon', None, 14.0, None, ''),
	('[Chang Sheng] BABY Chapter 15 – Decision', None, 15.0, None, ''),
	('[Chang Sheng] BABY Chapter 16 – Defective', None, 16.0, None, ''),
	('[Chang Sheng] BABY Chapter 17 – Lord of the Land', None, 17.0, None, ''),
	('[Chang Sheng] BABY Volume 2', 2.0, None, None, ''),
	('[Chang Sheng] BABY Volume 3', 3.0, None, None, ''),
	("[Clotaku Club! v2] 1. The Sangkam's Game - Part 2", 2, 1, 2, ''),
	('[Clotaku Club! v2] 2. The Melancholy of the Original Eun Yerin', 2, 2, None, ''),
	('[Clotaku Club! v2] 3. Winning Twelve - Part 1', 2, 3, 1, ''),
	('[Collaborative Project Announcement] Sword Art Online Alternative Gun Gale Online manga', None, None, None, ''),
	('[Corrupt-emon] Chapter 1', None, 1.0, None, ''),
	('[DATABASE] & [RELEASE] – SEED ASTRAY PROLOGUE', None, None, None, 'PROLOGUE'),
	('[DATABASE] &#8211; Manga Added', None, 8211.0, None, ''),
	('[DATABASE] &#8211; Manga Update', None, 8211.0, None, ''),
	('[DATABASE] – BLAZING SHADOW', None, None, None, ''),
	('[DATABASE] – MSV-R SHIN MATSUNAGA', None, None, None, ''),
	('[DBMV46] Interview with Kawahara Reki', None, 46.0, None, ''),
	('[DD] Chapter 10', None, 10.0, None, ''),
	('[DD] Chapter 7', None, 7.0, None, ''),
	('[DD] Chapter 8', None, 8.0, None, ''),
	('[DD] Chapter 9', None, 9.0, None, ''),
	('[Dark Mage]Chapter 1 Escape,  then New World. 1st', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. 2nd episode', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 10', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 11', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 12', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 13', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 14', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 15', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 16', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 17', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 18', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 19', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 20', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 21', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 22', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 23', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 24', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 25', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 26', None, 1.0, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 27 Part 1', None, 1.0, 1.0, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 27 Part 2', None, 1.0, 2.0, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 5', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 6', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 7', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 8', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. EP. 9', None, 1, None, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. Part 3', None, 1, 3, ''),
	('[Dark Mage]Chapter 1 Escape, then New World. Part 4', None, 1, 4, ''),
	('[DarkMage]Chapter 2 Series of Trial. Episode 30', None, 2.0, 30.0, ''),
	('[DarkMage]Chapter 2 Series of Trial. Episode 31', None, 2.0, 31.0, ''),
	('[DarkMage]Chapter 2 Series of Trial. Episode 32', None, 2.0, 32.0, ''),
	('[DarkMage]Chapter 2 Series of Trial. Episode 33', None, 2.0, 33.0, ''),
	('[DarkMage]Chapter 2 Series of Trial. Episode 34', None, 2.0, 34.0, ''),
	('[DarkMage]Chapter 2 Series of Trial. Episode 35', None, 2.0, 35.0, ''),
	('[Database] – Updated', None, None, None, ''),
	('[Dawnbringer v2] 01. Our Luxurious Vacation! - Part 1', 2, 1, 1, ''),
	('[Dawnbringer v2] 01. Our Luxurious Vacation! - Part 2', 2, 1, 2, ''),
	('[Dawnbringer v2] 01. Our Luxurious Vacation! - Part 3', 2, 1, 3, ''),
	('[Dawnbringer v2] 01. Our Luxurious Vacation! - Part 4', 2, 1, 4, ''),
	('[Dawnbringer v2] 02. Critik in the Storm - Part 1', 2, 2, 1, ''),
	('[Dawnbringer v2] 02. Critik in the Storm - Part 2', 2, 2, 2, ''),
	('[Dawnbringer v2] 02. Critik in the Storm - Part 3', 2, 2, 3, ''),
	('[Dawnbringer v2] 02. Critik in the Storm - Part 4', 2, 2, 4, ''),
	('[Dawnbringer v2] 02. Critik in the Storm - Part 5', 2.0, 2.0, 5.0, ''),
	('[Dawnbringer v2] 03. Dawnbringer VS Saika - Part 1', 2.0, 3.0, 1.0, ''),
	('[Dawnbringer v2] 03. Dawnbringer VS Saika - Part 2', 2.0, 3.0, 2.0, ''),
	('[Dawnbringer v2] 04. The End of the Vacation', 2.0, 4.0, None, ''),
	('[Deadline: 1-1-2017] Poll/Voting: Second Translation Project', None, None, None, ''),
	('[Digital] – Gundam Unicorn', None, None, None, ''),
	('[Disciple] Chapter 1', None, 1.0, None, ''),
	('[Disciple] Chapter 10', None, 10.0, None, ''),
	('[Disciple] Chapter 100', None, 100.0, None, ''),
	('[Disciple] Chapter 101', None, 101.0, None, ''),
	('[Disciple] Chapter 102', None, 102.0, None, ''),
	('[Disciple] Chapter 103', None, 103.0, None, ''),
	('[Disciple] Chapter 104', None, 104.0, None, ''),
	('[Disciple] Chapter 105', None, 105.0, None, ''),
	('[Disciple] Chapter 106', None, 106.0, None, ''),
	('[Disciple] Chapter 107', None, 107.0, None, ''),
	('[Disciple] Chapter 108', None, 108.0, None, ''),
	('[Disciple] Chapter 109', None, 109.0, None, ''),
	('[Disciple] Chapter 11', None, 11.0, None, ''),
	('[Disciple] Chapter 110', None, 110.0, None, ''),
	('[Disciple] Chapter 111', None, 111.0, None, ''),
	('[Disciple] Chapter 112', None, 112.0, None, ''),
	('[Disciple] Chapter 113', None, 113.0, None, ''),
	('[Disciple] Chapter 114', None, 114.0, None, ''),
	('[Disciple] Chapter 115', None, 115.0, None, ''),
	('[Disciple] Chapter 116', None, 116.0, None, ''),
	('[Disciple] Chapter 117', None, 117.0, None, ''),
	('[Disciple] Chapter 118', None, 118.0, None, ''),
	('[Disciple] Chapter 119', None, 119.0, None, ''),
	('[Disciple] Chapter 12', None, 12.0, None, ''),
	('[Disciple] Chapter 120', None, 120.0, None, ''),
	('[Disciple] Chapter 121', None, 121.0, None, ''),
	('[Disciple] Chapter 122', None, 122.0, None, ''),
	('[Disciple] Chapter 123', None, 123.0, None, ''),
	('[Disciple] Chapter 124', None, 124.0, None, ''),
	('[Disciple] Chapter 125', None, 125.0, None, ''),
	('[Disciple] Chapter 126', None, 126.0, None, ''),
	('[Disciple] Chapter 127', None, 127.0, None, ''),
	('[Disciple] Chapter 128', None, 128.0, None, ''),
	('[Disciple] Chapter 129', None, 129.0, None, ''),
	('[Disciple] Chapter 13', None, 13.0, None, ''),
	('[Disciple] Chapter 130', None, 130.0, None, ''),
	('[Disciple] Chapter 131', None, 131.0, None, ''),
	('[Disciple] Chapter 132', None, 132.0, None, ''),
	('[Disciple] Chapter 133', None, 133.0, None, ''),
	('[Disciple] Chapter 134', None, 134.0, None, ''),
	('[Disciple] Chapter 135', None, 135.0, None, ''),
	('[Disciple] Chapter 136', None, 136.0, None, ''),
	('[Disciple] Chapter 137', None, 137.0, None, ''),
	('[Disciple] Chapter 138', None, 138.0, None, ''),
	('[Disciple] Chapter 139', None, 139.0, None, ''),
	('[Disciple] Chapter 14', None, 14.0, None, ''),
	('[Disciple] Chapter 140', None, 140.0, None, ''),
	('[Disciple] Chapter 141', None, 141.0, None, ''),
	('[Disciple] Chapter 142', None, 142.0, None, ''),
	('[Disciple] Chapter 143', None, 143.0, None, ''),
	('[Disciple] Chapter 144', None, 144.0, None, ''),
	('[Disciple] Chapter 145', None, 145.0, None, ''),
	('[Disciple] Chapter 146', None, 146.0, None, ''),
	('[Disciple] Chapter 15', None, 15.0, None, ''),
	('[Disciple] Chapter 16', None, 16.0, None, ''),
	('[Disciple] Chapter 17', None, 17.0, None, ''),
	('[Disciple] Chapter 18', None, 18.0, None, ''),
	('[Disciple] Chapter 19', None, 19.0, None, ''),
	('[Disciple] Chapter 2', None, 2.0, None, ''),
	('[Disciple] Chapter 20', None, 20.0, None, ''),
	('[Disciple] Chapter 21', None, 21.0, None, ''),
	('[Disciple] Chapter 22', None, 22.0, None, ''),
	('[Disciple] Chapter 23', None, 23.0, None, ''),
	('[Disciple] Chapter 24', None, 24.0, None, ''),
	('[Disciple] Chapter 25', None, 25.0, None, ''),
	('[Disciple] Chapter 26', None, 26.0, None, ''),
	('[Disciple] Chapter 27', None, 27.0, None, ''),
	('[Disciple] Chapter 28', None, 28.0, None, ''),
	('[Disciple] Chapter 29', None, 29.0, None, ''),
	('[Disciple] Chapter 3', None, 3.0, None, ''),
	('[Disciple] Chapter 30', None, 30.0, None, ''),
	('[Disciple] Chapter 31', None, 31.0, None, ''),
	('[Disciple] Chapter 32', None, 32.0, None, ''),
	('[Disciple] Chapter 33', None, 33.0, None, ''),
	('[Disciple] Chapter 34', None, 34.0, None, ''),
	('[Disciple] Chapter 35', None, 35.0, None, ''),
	('[Disciple] Chapter 36', None, 36.0, None, ''),
	('[Disciple] Chapter 37', None, 37.0, None, ''),
	('[Disciple] Chapter 38', None, 38.0, None, ''),
	('[Disciple] Chapter 39', None, 39.0, None, ''),
	('[Disciple] Chapter 4', None, 4.0, None, ''),
	('[Disciple] Chapter 40', None, 40.0, None, ''),
	('[Disciple] Chapter 41', None, 41.0, None, ''),
	('[Disciple] Chapter 42', None, 42.0, None, ''),
	('[Disciple] Chapter 43', None, 43.0, None, ''),
	('[Disciple] Chapter 44', None, 44.0, None, ''),
	('[Disciple] Chapter 45', None, 45.0, None, ''),
	('[Disciple] Chapter 46', None, 46.0, None, ''),
	('[Disciple] Chapter 47', None, 47.0, None, ''),
	('[Disciple] Chapter 48', None, 48.0, None, ''),
	('[Disciple] Chapter 49', None, 49.0, None, ''),
	('[Disciple] Chapter 5', None, 5.0, None, ''),
	('[Disciple] Chapter 50', None, 50.0, None, ''),
	('[Disciple] Chapter 51', None, 51.0, None, ''),
	('[Disciple] Chapter 52', None, 52.0, None, ''),
	('[Disciple] Chapter 53', None, 53.0, None, ''),
	('[Disciple] Chapter 54', None, 54.0, None, ''),
	('[Disciple] Chapter 55', None, 55.0, None, ''),
	('[Disciple] Chapter 56', None, 56.0, None, ''),
	('[Disciple] Chapter 57', None, 57.0, None, ''),
	('[Disciple] Chapter 58', None, 58.0, None, ''),
	('[Disciple] Chapter 59', None, 59.0, None, ''),
	('[Disciple] Chapter 6', None, 6.0, None, ''),
	('[Disciple] Chapter 60', None, 60.0, None, ''),
	('[Disciple] Chapter 61', None, 61.0, None, ''),
	('[Disciple] Chapter 62', None, 62.0, None, ''),
	('[Disciple] Chapter 63', None, 63.0, None, ''),
	('[Disciple] Chapter 64', None, 64.0, None, ''),
	('[Disciple] Chapter 65', None, 65.0, None, ''),
	('[Disciple] Chapter 66', None, 66.0, None, ''),
	('[Disciple] Chapter 67', None, 67.0, None, ''),
	('[Disciple] Chapter 68', None, 68.0, None, ''),
	('[Disciple] Chapter 69', None, 69.0, None, ''),
	('[Disciple] Chapter 7', None, 7.0, None, ''),
	('[Disciple] Chapter 70', None, 70.0, None, ''),
	('[Disciple] Chapter 71', None, 71.0, None, ''),
	('[Disciple] Chapter 72', None, 72.0, None, ''),
	('[Disciple] Chapter 73', None, 73.0, None, ''),
	('[Disciple] Chapter 74', None, 74.0, None, ''),
	('[Disciple] Chapter 75', None, 75.0, None, ''),
	('[Disciple] Chapter 76', None, 76.0, None, ''),
	('[Disciple] Chapter 77', None, 77.0, None, ''),
	('[Disciple] Chapter 78', None, 78.0, None, ''),
	('[Disciple] Chapter 79', None, 79.0, None, ''),
	('[Disciple] Chapter 8', None, 8.0, None, ''),
	('[Disciple] Chapter 80', None, 80.0, None, ''),
	('[Disciple] Chapter 81', None, 81.0, None, ''),
	('[Disciple] Chapter 82', None, 82.0, None, ''),
	('[Disciple] Chapter 83', None, 83.0, None, ''),
	('[Disciple] Chapter 84', None, 84.0, None, ''),
	('[Disciple] Chapter 85', None, 85.0, None, ''),
	('[Disciple] Chapter 86', None, 86.0, None, ''),
	('[Disciple] Chapter 87', None, 87.0, None, ''),
	('[Disciple] Chapter 88', None, 88.0, None, ''),
	('[Disciple] Chapter 89', None, 89.0, None, ''),
	('[Disciple] Chapter 9', None, 9.0, None, ''),
	('[Disciple] Chapter 90', None, 90.0, None, ''),
	('[Disciple] Chapter 91', None, 91.0, None, ''),
	('[Disciple] Chapter 92', None, 92.0, None, ''),
	('[Disciple] Chapter 93', None, 93.0, None, ''),
	('[Disciple] Chapter 94', None, 94.0, None, ''),
	('[Disciple] Chapter 95', None, 95.0, None, ''),
	('[Disciple] Chapter 96', None, 96.0, None, ''),
	('[Disciple] Chapter 97', None, 97.0, None, ''),
	('[Disciple] Chapter 98', None, 98.0, None, ''),
	('[Disciple] Chapter 99', None, 99.0, None, ''),
	('[Down with Cold] – Please come back tomorrow.', None, None, None, ''),
	('[Dropped]', None, None, None, ''),
	('[Ebisumaru] Springtime in Full Bloom', None, None, None, ''),
	('[Edited] KTMHK – Chapter 1', None, 1.0, None, ''),
	('[Edited] KTMHK – Chapter 2', None, 2.0, None, ''),
	('[Edited] KTMHK – Prologue', None, None, None, 'Prologue'),
	('[Fanfic]Pervert Healer ch4 page1-2', None, 4.0, 1.0, ''),
	('[Four Lovers v01] 5. Sweet Days', 1, 5, None, ''),
	('[Four Lovers v01] 6. Tempest - Part 1', 1, 6, 1, ''),
	('[Four Lovers v01] 6. Tempest - Part 2', 1, 6, 2, ''),
	('[Four Lovers v01] 7. Bitter End - Part 1', 1.0, 7.0, 1.0, ''),
	('[Four Lovers v01] 7. Bitter End - Part 2', 1.0, 7.0, 2.0, ''),
	('[Four Lovers v01] Epilogue. Indecent Relationship', 1.0, None, None, 'Epilogue. Indecent Relationship'),
	('[GDN] 3 chaps total today', None, 3.0, None, ''),
	('[GDN] 30 day no-fap streak', None, 30.0, None, ''),
	('[GDN] Bad news for TT', None, None, None, ''),
	('[GDN] Bonus chap here', None, None, None, ''),
	('[GDN] Bonus chap todayyyyy', None, None, None, ''),
	('[GDN] Late regular', None, None, None, ''),
	('[GDN] Regular chap here homies', None, None, None, ''),
	('[GDN] Regular todayyyy', None, None, None, ''),
	('[GDN] Tofu got drank from visiting an aquarium', None, None, None, ''),
	('[GDN] When Black Bean Sauce’s email ended up in junkmail', None, None, None, ''),
	('[GDN] When Tofu exercises his freedom of speech', None, None, None, ''),
	('[GDN] Woah Black Bean Sauce is la back', None, None, None, ''),
	('[GDN] hopefully 1 more to go', None, 1.0, None, ''),
	('[GDN] “I’m going to explode”', None, None, None, ''),
	('[GDN][MGZ]', None, None, None, ''),
	('[GDW 330] Hardest Game EVAR!', None, 330.0, None, ''),
	('[GDW 331] Society is Dead!', None, 331.0, None, ''),
	('[GDW 332] Zippy The Rabid Gerbil', None, 332.0, None, ''),
	('[GDW 333] Will the real Yue Zhong Please Stand Up?', None, 333.0, None, ''),
	('[GDW 334] Ecclectic Art!', None, 334.0, None, ''),
	('[GDW 335] Suplexes for Everyone!', None, 335.0, None, ''),
	('[GDW 336] Hot and Fresh!', None, 336.0, None, ''),
	('[GDW 337] Nobody Knows What Pearl Fruit Does?', None, 337.0, None, ''),
	('[GDW 338] 27℃ and sunny all day…FTW!', None, 338.0, None, ''),
	('[GDW 339] Double release Friday! Happy July!', None, 339.0, None, ''),
	('[GDW 340] The Divine Ulamog Empire!', None, 340.0, None, ''),
	('[GDW 341] Parents in Town!', None, 341.0, None, ''),
	('[GDW 342] Holiday Early release!', None, 342.0, None, ''),
	('[GDW 343] Regularly Scheduled Chapter', None, 343.0, None, ''),
	('[GDW 344] Another Intense Battle Begins!', None, 344.0, None, ''),
	('[GDW 345] Sound Military Tactics?', None, 345.0, None, ''),
	('[GDW 346] I’m Baaaaaaack!', None, 346.0, None, ''),
	('[GDW 347] I See The Future….', None, 347.0, None, ''),
	('[GDW 348] BLINDSIDED!', None, 348.0, None, ''),
	('[GDW 349]  so sleepy…', None, 349.0, None, ''),
	('[GDW 350] All Who Dont Participate Will Be Cursed!', None, 350.0, None, ''),
	('[GDW 351] Oh The Horror!', None, 351.0, None, ''),
	('[GDW 352] Carthago Delenda Est!', None, 352.0, None, ''),
	('[GDW 353]so sore!', None, 353.0, None, ''),
	('[GDW 354] Any Dark FolkTale Fans Here?', None, 354.0, None, ''),
	('[GDW 355] My restaurant job is The Wines of Colorado Gym?', None, 355.0, None, ''),
	('[GDW 356] Crash-Tastic! One of those “oooooh” moments…', None, 356.0, None, ''),
	('[GDW 357] Fine Chocolate is a Divine Cultivation Tool?', None, 357.0, None, ''),
	('[GDW 358] Dont Look Dooooown!!!', None, 358.0, None, ''),
	('[GDW 359] Late is better than tomorrow?', None, 359.0, None, ''),
	('[GDW 360] Chapter shmapter!', None, 360.0, None, ''),
	('[GDW 361]  Eh…. Poor form….', None, 361.0, None, ''),
	('[GDW 362] Begin the Drumroll!', None, 362.0, None, ''),
	('[GDW 363] Did you finish the first one yet?', None, 363.0, None, ''),
	('[GDW Team] New Novel???', None, None, None, ''),
	('[GDW]  Bedtime! I love it!', None, None, None, ''),
	('[GDW] 310 Free chapter, Sleepers be late!', None, 310.0, None, ''),
	('[GDW] 311 Grasshopper soup!', None, 311.0, None, ''),
	('[GDW] 313 This ones Gruesome!', None, 313.0, None, ''),
	('[GDW] 314 times i did push ups!', None, 314.0, None, ''),
	('[GDW] 319- Hack your Face! Read a Paper book!', None, 319.0, None, ''),
	('[GDW] 320 Did You Miss an Email?', None, 320.0, None, ''),
	('[GDW] 322 Fire In The Sky!', None, 322.0, None, ''),
	('[GDW] 328! Fired By a Customer!', None, 328.0, None, ''),
	('[GDW] Ancient Golden Runes Unearthed!', None, None, None, ''),
	('[GDW] Cadillac Spider-Hearse', None, None, None, ''),
	('[GDW] Delay in posting 312…', None, 312.0, None, ''),
	('[GDW] Delayed….', None, None, None, ''),
	('[GDW] Devil Flame Versatility?', None, None, None, ''),
	('[GDW] Early By Far!', None, None, None, ''),
	('[GDW] Ghost Zombies! 309 of them!', None, 309.0, None, ''),
	('[GDW] Late is better than Never!', None, None, None, ''),
	('[GDW] Mighty Morphin Forest Rangers', None, None, None, ''),
	('[GDW] Posting Buggy 308….', None, 308.0, None, ''),
	('[GDW] Sneaking into the Vault!', None, None, None, ''),
	('[GDW] Type 4 Heavenly Defying Rodent', None, 4.0, None, ''),
	('[GDW] nom nom 325', None, 325.0, None, ''),
	('[GDW] sponsored chapter!', None, None, None, ''),
	('[GDW] womp womp womp….', None, None, None, ''),
	('[GE]', None, None, None, ''),
	('[GE] 2 chapters woo', None, 2.0, None, ''),
	('[GE] 2/3', None, 2.0, None, ''),
	('[GE] I wanna be the very best', None, None, None, ''),
	('[GE] Jet Lag is hard on my booty', None, None, None, ''),
	('[GE] Third chapter of last week', None, None, None, ''),
	('[GE] x2', None, 2.0, None, ''),
	('[GGOM] LINK #001 - Prologue ①', None, 1.0, None, 'Prologue ①'),
	('[GGOV1] Afterword', None, 1.0, None, 'Afterword'),
	('[GGOV1] Prologue', None, 1.0, None, 'Prologue'),
	("[GGOV1] SECT.1 - Karen's Gloom", None, 1.0, None, ''),
	('[GGOV1] SECT.10 - LLENN and M', None, 1.0, None, ''),
	('[GGOV1] SECT.11 - Death Game', None, 1.0, None, ''),
	('[GGOV1] SECT.12 - This Last Battle of Mine', None, 1.0, None, ''),
	('[GGOV1] SECT.13 - Battle to the Death', None, 1.0, None, ''),
	('[GGOV1] SECT.14 - Later Developments', None, 1.0, None, ''),
	('[GGOV1] SECT.2 - LLENN and Pitohui', None, 1.0, None, ''),
	('[GGOV1] SECT.3 - Squad Jam', None, 1.0, None, ''),
	('[GGOV1] SECT.4 - A Man Named M', None, 1.0, None, ''),
	('[GGOV1] SECT.5 - The Beginning of the Tournament', None, 1.0, None, ''),
	('[GGOV1] SECT.6 - The Beginning of the Battle', None, 1.0, None, ''),
	('[GGOV1] SECT.7 - A Battle Against Pros', None, 1.0, None, ''),
	('[GGOV1] SECT.8 - Trap', None, 1.0, None, ''),
	("[GGOV1] SECT.9 - M's Battle", None, 1.0, None, ''),
	('[GGOV2] Prologue', None, 2.0, None, 'Prologue'),
	("[GGOV2] SECT.1 - Soldiers' Tea Party", None, 2.0, None, ''),
	('[GGOV2] SECT.2 - The Second Squad Jam', None, 2.0, None, ''),
	('[GGOV2] SECT.3 - SAO Loser', None, 2.0, None, ''),
	('[GGOV2] SECT.4 - SJ2 Preparations', None, 2.0, None, ''),
	('[GGOV2] SECT.5 - The Beginning of the Tournament', None, 2.0, None, ''),
	('[GGOV2] SECT.6 - Booby Trap', None, 2.0, None, ''),
	('[GGOV2] SECT.7 - Guilds-in-Action', None, 2.0, None, ''),
	('[GGOV2] SECT.8 - Their Respective Strategies', None, 2.0, None, ''),
	('[God & Devil Word] Chapter 173: Spiritual Cure', None, 173.0, None, ''),
	('[God & Devil World] Chapter 158: Mutant Rat King', None, 158.0, None, ''),
	('[God & Devil World] Chapter 159: Chasing the Rat King', None, 159.0, None, ''),
	('[God & Devil World] Chapter 160: The Battle against Mutant King Rat', None, 160.0, None, ''),
	('[God & Devil World] Chapter 161: Flowers among the camp.', None, 161.0, None, ''),
	('[God & Devil World] Chapter 162: A fierce battle', None, 162.0, None, ''),
	('[God & Devil World] Chapter 163: Tragic Victory', None, 163.0, None, ''),
	('[God & Devil World] Chapter 164: Saving Lives', None, 164.0, None, ''),
	('[God & Devil World] Chapter 165: Mass recruitment!', None, 165.0, None, ''),
	('[God & Devil World] Chapter 167: Dayun’s County [Or Big Cliff Village]', None, 167.0, None, ''),
	('[God & Devil World] Chapter 168: Little Greenie Show His Might!', None, 168.0, None, ''),
	('[God & Devil World] Chapter 169: [Title Withheld]', None, 169.0, None, ''),
	('[God & Devil World] Chapter 170: First battle for the Prisoners of War', None, 170.0, None, ''),
	('[God & Devil World] Chapter 171:  Attack on Big Cliff Village', None, 171.0, None, ''),
	('[God & Devil World] Chapter 172: Spirtual Attack', None, 172.0, None, ''),
	('[God & Devil World] Chapter 173: Strongman Gao [aka Gao Da Qiang]', None, 173.0, None, ''),
	('[God & Devil World] Chapter 175: Attack of the Zombies', None, 175.0, None, ''),
	('[God & Devil World] Chapter 176: [Title Withheld]', None, 176.0, None, ''),
	('[God & Devil World] Chapter 177: Entering the City', None, 177.0, None, ''),
	('[God & Devil World] Chapter 178: Investigation', None, 178.0, None, ''),
	('[God & Devil World] Chapter 179: Banquet', None, 179.0, None, ''),
	('[God & Devil World] Chapter 180: Fierce', None, 180.0, None, ''),
	('[God & Devil World] Chapter 181: Law after Apocalypse', None, 181.0, None, ''),
	('[God & Devil World] Chapter 182: Conference of the Three Big Powers', None, 182.0, None, ''),
	('[God & Devil World] Chapter 183: Arrival of the Zombies', None, 183.0, None, ''),
	('[God & Devil World] Chapter 187: Chaos!', None, 187.0, None, ''),
	('[God & Devil World] Chapter 189: The Sea of Zombies Temporary Retreats!', None, 189.0, None, ''),
	('[God & Devil World] Chapter 190: Lei Cheng fled!', None, 190.0, None, ''),
	('[God & Devil World] Chapter 191 A very difficult battle!', None, 191.0, None, ''),
	('[God & Devil World] Chapter 192: The mighty IFV', None, 192.0, None, ''),
	('[God and Devil World] Chapter 166: Little Greenie Evolved!', None, 166.0, None, ''),
	('[God and Devil World] Chapter 188: The Stage Turns', None, 188.0, None, ''),
	('[HCLS] Chapter 10', None, 10.0, None, ''),
	('[HCLS] Chapter 11', None, 11.0, None, ''),
	('[HCLS] Chapter 12', None, 12.0, None, ''),
	('[HCLS] Chapter 13', None, 13.0, None, ''),
	('[HCLS] Chapter 14', None, 14.0, None, ''),
	('[HCLS] Chapter 15', None, 15.0, None, ''),
	('[HCLS] Chapter 16', None, 16.0, None, ''),
	('[HCLS] Chapter 17', None, 17.0, None, ''),
	('[HCLS] Chapter 18', None, 18.0, None, ''),
	('[HCLS] Chapter 19', None, 19.0, None, ''),
	('[HCLS] Chapter 20', None, 20.0, None, ''),
	('[HCLS] Chapter 21', None, 21.0, None, ''),
	('[HCLS] Chapter 22', None, 22.0, None, ''),
	('[HCLS] Chapter 23', None, 23.0, None, ''),
	('[HCLS] Chapter 24', None, 24.0, None, ''),
	('[HCLS] Chapter 25', None, 25.0, None, ''),
	('[HCLS] Chapter 9', None, 9.0, None, ''),
	('[HLM] Chapter 2: Old Wang Went Crazy', None, 2.0, None, ''),
	('[HTK] 2nd regular chapter', None, 2.0, None, ''),
	('[HTK] Who are you people', None, None, None, ''),
	('[HTK] technically 1 chapter', None, 1.0, None, ''),
	('[HTSAS101] ARTWORK KITAAAAAA!!!', None, 101.0, None, ''),
	('[HTSAS101] Chapter 1', None, 1.0, None, ''),
	('[HTSAS101] Chapter 13 out!', None, 13.0, None, ''),
	('[HTSAS101] Chapter 2', None, 2.0, None, ''),
	('[HTSAS101] Chapter 3', None, 3.0, None, ''),
	('[HTSAS101] Chapter 4', None, 4.0, None, ''),
	('[HTSAS101] Chapter 6', None, 6.0, None, ''),
	('[HTSAS101] Chapter 7', None, 7.0, None, ''),
	('[HTSAS101] Chapter 8', None, 8.0, None, ''),
	('[HTSAS101] Prologue: Gods, Contracts and Frogs', None, 101.0, None, 'Prologue: Gods, Contracts and Frogs'),
	('[HTSAS101] Vote for what you love!', None, 101.0, None, ''),
	('[Hard to Escape] Chapter 1.1', None, 1.1, None, ''),
	('[Hard to Escape] Chapter 1.2', None, 1.2, None, ''),
	('[Hard to Escape] Chapter 1.3', None, 1.3, None, ''),
	('[Hard to Escape] Chapter 2.1', None, 2.1, None, ''),
	('[Hard to Escape] Chapter 2.2', None, 2.2, None, ''),
	('[Hasemi box (Hasemi Ryo)] UFO To Ore To Harem End', None, None, None, ''),
	('[Hell King] Book 1, Chapter 1', 1.0, 1.0, None, ''),
	('[Hell King] Book 1, Chapter 2', 1.0, 2.0, None, ''),
	('[Hell King] Book 1, Prologue', 1.0, None, None, 'Prologue'),
	('[ILLUSTRATION ARTIST] 伊吹五月: Ibuki Satsuki', None, None, None, ''),
	('[ILLUSTRATION ARTIST] 何何舞: ENO', None, None, None, ''),
	('[INFO] – Gundam: Iron-Blooded Orphans', None, None, None, ''),
	('[Incomplete 30% done] 026 – Three Of Them', None, 30.0, None, ''),
	('[Incomplete 90%] 025 – Things I Learned', None, 90.0, None, ''),
	('[Info] Mobile Suit Gundam: Missing Link Info', None, None, None, ''),
	('[Invisible Dragon] Chapters 1-50 (2002/07/25-2004/07/22)', None, 1, 50, ''),
	('[KC V5] Chapter 4 – An Opened Door Cannot Be Closed Again', 5.0, 4.0, None, ''),
	('[KC V5] Chapter 5 – And The Pentagon Dissolved', 5.0, 5.0, None, ''),
	('[KC V5] The Protagonist of this Story Is…', 5.0, None, None, ''),
	('[KR]Dragon Maken War Chapter 3', None, 3.0, None, ''),
	('[KYSnN] A Little About the Past 1', None, 1.0, None, ''),
	('[KYSnN] A Little About the Past 2', None, 2.0, None, ''),
	('[KYSnN] A Little About the Past 3', None, 3.0, None, ''),
	('[KYSnN] I Dun Want to Dance', None, None, None, ''),
	('[KYSnN] Life with My Mother', None, None, None, ''),
	('[Kashiwa-ya (Hiyo Hiyo)] Lily Lily Reapers Rererererelaxation', None, None, None, ''),
	('[Kimi no Na] C1 Dream', None, 1.0, None, ''),
	('[Kimi no Na] C2 Beginning', None, 2.0, None, ''),
	('[King Shura] Chapter 33', None, 33.0, None, ''),
	('[King Shura] Chapter 34', None, 34.0, None, ''),
	('[King Shura] Chapter 35', None, 35.0, None, ''),
	('[King Shura] Chapter 36', None, 36.0, None, ''),
	('[King Shura] Chapter 37', None, 37.0, None, ''),
	('[King Shura] Chapter 38', None, 38.0, None, ''),
	('[King Shura] Chapter 39', None, 39.0, None, ''),
	('[King Shura] Chapter 40', None, 40.0, None, ''),
	('[King Shura] Chapter 41', None, 41.0, None, ''),
	('[King Shura] Chapter 42', None, 42.0, None, ''),
	('[King Shura] Chapter 43', None, 43.0, None, ''),
	('[King Shura] Chapter 44', None, 44.0, None, ''),
	('[King Shura] Chapter 45', None, 45.0, None, ''),
	('[King Shura] Chapter 46', None, 46.0, None, ''),
	('[King Shura] Chapter 48', None, 48.0, None, ''),
	('[King Shura] Chapter 49', None, 49.0, None, ''),
	('[King Shura] Chapter 50', None, 50.0, None, ''),
	('[King Shura] Chapter 51', None, 51.0, None, ''),
	('[King Shura] Chapter 52', None, 52.0, None, ''),
	('[King Shura] Chapter 53', None, 53.0, None, ''),
	('[King Shura] Chapter 54', None, 54.0, None, ''),
	('[King Shura] Chapter 55', None, 55.0, None, ''),
	('[King Shura] Chapter 56', None, 56.0, None, ''),
	('[King Shura] Chapter 57', None, 57.0, None, ''),
	('[King Shura] Chapter 58', None, 58.0, None, ''),
	('[King Shura] Chapter 59', None, 59.0, None, ''),
	('[King Shura] Chapter 60', None, 60.0, None, ''),
	('[King Shura] Chapter 61', None, 61.0, None, ''),
	('[King Shura] Chapter 62', None, 62.0, None, ''),
	('[King Shura] Chapter 63', None, 63.0, None, ''),
	('[King Shura] Chapter 64', None, 64.0, None, ''),
	('[King Shura] Chapter 65', None, 65.0, None, ''),
	('[King Shura] Chapter 66', None, 66.0, None, ''),
	('[King Shura] Chapter 67', None, 67.0, None, ''),
	('[King Shura] Chapter 68', None, 68.0, None, ''),
	('[King Shura] Chapter 69', None, 69.0, None, ''),
	('[King Shura] Chapter 70', None, 70.0, None, ''),
	('[King Shura] Chapter 71', None, 71.0, None, ''),
	('[King Shura] Chapter 72', None, 72.0, None, ''),
	('[King Shura] Chapter 73', None, 73.0, None, ''),
	('[King Shura] Chapter 74', None, 74.0, None, ''),
	('[King Shura] Chapter 75', None, 75.0, None, ''),
	('[King Shura] Chapter 76', None, 76.0, None, ''),
	('[King Shura] Chapter 77', None, 77.0, None, ''),
	('[King Shura] Chapter 78', None, 78.0, None, ''),
	('[King Shura] Chapter 79', None, 79.0, None, ''),
	('[King Shura] Chapter 80', None, 80.0, None, ''),
	('[King Shura] Chapter 81', None, 81.0, None, ''),
	('[King Shura] Chapter 82', None, 82.0, None, ''),
	('[King Shura] Chapter 83', None, 83.0, None, ''),
	('[King Shura] Chapter 84', None, 84.0, None, ''),
	('[King Shura] Chapter 85', None, 85.0, None, ''),
	('[King Shura] Chapter 86', None, 86.0, None, ''),
	('[King Shura] Chapter 87', None, 87.0, None, ''),
	('[King Shura] Chapter 88', None, 88.0, None, ''),
	('[King Shura] Chapter 89', None, 89.0, None, ''),
	('[King Shura] Chapter 90', None, 90.0, None, ''),
	('[King Shura] Chapter 91', None, 91.0, None, ''),
	('[King Shura] Chapter 92', None, 92.0, None, ''),
	('[King Shura] Chapter 93', None, 93.0, None, ''),
	('[King Shura] Chapter 94', None, 94.0, None, ''),
	('[King Shura] Chapter 95', None, 95.0, None, ''),
	('[King Shura] Chapter 96', None, 96.0, None, ''),
	('[King Shura] Chapter 97', None, 97.0, None, ''),
	('[King Shura] Chapter 98', None, 98.0, None, ''),
	('[King Shura] Chapter 99', None, 99.0, None, ''),
	('[Kyomu no Uta (Satou Toshio)] Thanks for the Meal', None, None, None, ''),
	('[LBD&A] Chapter 36: Stirring Trouble', None, 36.0, None, ''),
	('[LBD&A] Chapter 37: Reminiscence 1', None, 37.0, None, ''),
	('[LBD&A] Chapter 38: Reminiscence 2', None, 38.0, None, ''),
	('[LBD&A] Chapter 39: An unexpected breakthrough!', None, 39.0, None, ''),
	('[LBD&A] Chapter 40: The Gamblers 1', None, 40.0, None, ''),
	('[LBD&A] Chapter 41: The gamblers II', None, 41.0, None, ''),
	('[LBD&A] Chapter 43: The Gamblers III (The Last Battle)', None, 43.0, None, ''),
	('[LBD&A] Chapter 43: The Raid', None, 43.0, None, ''),
	('[LBD&A] Chapter 44: Pay back in own coin', None, 44.0, None, ''),
	('[LBD&A] Chapter 45: The Vixen', None, 45.0, None, ''),
	('[LBD&A] Chapter 46: The Madness', None, 46.0, None, ''),
	('[LBD&A] Chapter 47: The Madness II – Seizing Power in South Ward', None, 47.0, None, ''),
	('[LBD&A] Chapter 48: Assassins in the night', None, 48.0, None, ''),
	('[LBD&A] Chapter 49: Even the best laid plans were no match for sheer power', None, 49.0, None, ''),
	('[LDM] Guild’s Receptionist-san Side Stories — Frequency', None, None, None, ''),
	('[LEWD] Great Demon King Chapter 30', None, 30.0, None, ''),
	('[LXM] Lily Ex Machina 61', None, 61.0, None, ''),
	('[LXM] Lily Ex Machina 64', None, 64.0, None, ''),
	('[LXM] Lily Ex Machina 65', None, 65.0, None, ''),
	('[LXM] Lily Ex Machina 66', None, 66.0, None, ''),
	('[LXM] Lily Ex Machina 67', None, 67.0, None, ''),
	('[LXM] Lily Ex Machina 68', None, 68.0, None, ''),
	('[LXM] Lily Ex Machina 69', None, 69.0, None, ''),
	('[LXM] Lily Ex Machina 70', None, 70.0, None, ''),
	('[LXM] Lily Ex Machina 71', None, 71.0, None, ''),
	('[LXM] Lily Ex Machina 72', None, 72.0, None, ''),
	('[LXM] Lily Ex Machina 73', None, 73.0, None, ''),
	('[LXM] Lily Ex Machina 74', None, 74.0, None, ''),
	('[LXM] Lily Ex Machina 75', None, 75.0, None, ''),
	('[LXM] Lily Ex Machina 76', None, 76.0, None, ''),
	('[LXM] Lily Ex Machina 77', None, 77.0, None, ''),
	('[LXM] Lily Ex Machina 78', None, 78.0, None, ''),
	('[LXM] Lily Ex Machina 79', None, 79.0, None, ''),
	('[LXM] Lily Ex Machina 83', None, 83.0, None, ''),
	('[LXM] Lily Ex Machina Chapter 60 + Character Info page', None, 60.0, None, ''),
	('[LXM] Lily Ex Machina Chapter 62', None, 62.0, None, ''),
	('[LXM] Lily Ex Machina Chapter 63', None, 63.0, None, ''),
	('[LXM] Lily Ex Machina Chapter 80', None, 80.0, None, ''),
	('[LXM] Lily Ex Machina Chapter 81', None, 81.0, None, ''),
	('[LXM] Lily Ex Machina Chapter 82', None, 82.0, None, ''),
	('[Little Phoenix] Chapter 1', None, 1.0, None, ''),
	('[Little Phoenix] Chapter 10', None, 10.0, None, ''),
	('[Little Phoenix] Chapter 11', None, 11.0, None, ''),
	('[Little Phoenix] Chapter 12', None, 12.0, None, ''),
	('[Little Phoenix] Chapter 13', None, 13.0, None, ''),
	('[Little Phoenix] Chapter 14', None, 14.0, None, ''),
	('[Little Phoenix] Chapter 15', None, 15.0, None, ''),
	('[Little Phoenix] Chapter 16', None, 16.0, None, ''),
	('[Little Phoenix] Chapter 17', None, 17.0, None, ''),
	('[Little Phoenix] Chapter 18', None, 18.0, None, ''),
	('[Little Phoenix] Chapter 2', None, 2.0, None, ''),
	('[Little Phoenix] Chapter 3', None, 3.0, None, ''),
	('[Little Phoenix] Chapter 4', None, 4.0, None, ''),
	('[Little Phoenix] Chapter 6', None, 6.0, None, ''),
	('[Little Phoenix] Chapter 7', None, 7.0, None, ''),
	('[Little Phoenix] Chapter 8', None, 8.0, None, ''),
	('[Little Phoenix] Chapter 9', None, 9.0, None, ''),
	('[MGZ]', None, None, None, ''),
	('[MGZ] Did you know Mcdonald is cooperating with Pokemon Go', None, None, None, ''),
	('[MGZ] Here u go', None, None, None, ''),
	('[MGZ] Regular', None, None, None, ''),
	('[MGZ] Woah so hardworking', None, None, None, ''),
	('[MGZ] Woahhh is that a sale??', None, None, None, ''),
	('[MISC] End of the server crashing issue', None, None, None, ''),
	('[MISC] Late Night Editing', None, None, None, ''),
	('[MISC] Staff and Changes', None, None, None, ''),
	('[MISC] Would Like Another Staff', None, None, None, ''),
	('[MZM] Chapter 3: Slime Counter-Attack', None, 3.0, None, ''),
	('[Makio] Peeping?', None, None, None, ''),
	('[Manga] 4-Koma Chapter 8', None, 8.0, None, ''),
	('[Manga] DanMachi 4 Koma Chapter 7', None, 7.0, None, ''),
	('[Manga] DanMachi 4-Koma Chapter 9', None, 9.0, None, ''),
	('[Manga] DanMachi 4Koma Chapter 10', None, 10.0, None, ''),
	('[Manga] Sword Oratoria Ch. 6', None, 6.0, None, ''),
	('[Mature] Koi no Kotoba c1', None, 1.0, None, ''),
	('[Me and the Tigress v01] 01. Starting Story', 1.0, 1.0, None, ''),
	('[Me and the Tigress v01] 02. Second Story', 1.0, 2.0, None, ''),
	('[Menea The Dog] Alas, Mako-chan got a Creampie', None, None, None, ''),
	('[Meta] Regarding Donations', None, None, None, ''),
	('[Monogatari Series] Nadeko Mirror', None, None, None, ''),
	('[Monogatari Series] Ougi Travel', None, None, None, ''),
	('[More Releases Here – Updated Perks]', None, None, None, ''),
	('[Mushi Uta ] Fan Art -- Anime Crossover Collection', None, None, None, ''),
	('[Mushi Uta v4 ] Chapter 1.00: Chiharu Part 1', 4.0, 1.0, 1.0, ''),
	('[Mushi Uta v4 ] Chapter 1.01: Chami Part 1', 4.0, 1.01, 1.0, ''),
	('[Mushi Uta v4 ] Chapter 1.02: The Others', 4.0, 1.02, None, ''),
	('[Mushi Uta v4 ] Chapter 1.03: The Others', 4.0, 1.03, None, ''),
	('[Mushi Uta v4 ] Chapter 1.04: Chiharu Part 2', 4.0, 1.04, 2.0, ''),
	('[Mushi Uta v4 ] Prologue 0.01: The Others', 4.0, 0.01, None, 'Prologue 0.01: The Others'),
	('[Mushi Uta] Fan art!', None, None, None, ''),
	('[NEWS] – GUNDAM ACE DETAILS', None, None, None, ''),
	('[NEWS] – STARTING MARCH 2013!', None, 2013.0, None, ''),
	('[NL NOVEL] Our House Pet (Chapter 5 Part 2)', None, 5.0, 2.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 5 Part 3)', None, 5.0, 3.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 6 Part 1)', None, 6.0, 1.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 6 Part 2)', None, 6.0, 2.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 7 Part 1)', None, 7.0, 1.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 7 Part 2)', None, 7.0, 2.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 8 Part 1)', None, 8.0, 1.0, ''),
	('[NL NOVEL] Our House Pet (Chapter 8 Part 2)', None, 8.0, 2.0, ''),
	('[NOT A TL] 206, little bug on the previous version, apologies', None, 206.0, None, ''),
	('[NOTICE][Not a Release] BAD NEWS! PC RIP!! :(', None, None, None, ''),
	('[NSFL] Xant & Minions Podcast #2', None, 2.0, None, ''),
	('[NSFW 18+] Immoral Holidays 背德假期 Chapter 1', None, 1.0, None, ''),
	('[NSFW 18+] Immoral Holidays 背德假期 Chapter 2', None, 2.0, None, ''),
	('[NSFW 18+] Immoral Holidays 背德假期 Chapter 3', None, 3.0, None, ''),
	('[NSFW 18+] Immoral Holidays 背德假期 Prologue', None, 18.0, None, 'Prologue'),
	('[NSFW] Great Demon King Chapter 11', None, 11.0, None, ''),
	('[Narise Konohara] Of Beauty / Of Love – Part 1', None, None, 1.0, ''),
	('[Narise Konohara] Of Beauty / Of Love – Part 2', None, None, 2.0, ''),
	('[Narise Konohara] Of Beauty / Of Love – Part 3', None, None, 3.0, ''),
	('[Narise Konohara] Of Beauty / Watch -chapter 2-', None, 2.0, None, ''),
	('[Narise Konohara] Of Beauty – Part 18', None, None, 18.0, ''),
	('[News] July Update', None, None, None, ''),
	('[News] July Update Number Two!', None, None, None, ''),
	('[News] No Chapters this Wednesday', None, None, None, ''),
	('[News] November Update', None, None, None, ''),
	('[News] Putting RPG World on Hiatus', None, None, None, ''),
	('[Not 1 TL] True hiatus..?', None, 1, None, ''),
	('[Not A Chapter] : Re-Edition', None, None, None, ''),
	('[Not A Chapter] OreDorei Page added!', None, None, None, ''),
	('[Not A Chapter] Status Update', None, None, None, ''),
	('[Not a Chapter] Japan Trip Journal', None, None, None, ''),
	('[Not a Chapter] New home for My Daoist Life', None, None, None, ''),
	('[Not a Chapter] Quick Announcement', None, None, None, ''),
	('[Not a Chapter] Random Update', None, None, None, ''),
	('[Not a Chapter] Schedule Change', None, None, None, ''),
	('[Not a Chapter] Status Update', None, None, None, ''),
	('[Not a Chapter] Status Update -Put the cart ahead of the horse', None, None, None, ''),
	('[Not a Chapter] Status Update – Ill', None, None, None, ''),
	('[Not a Chapter] Status Update – Thanksgiving, Black Friday, Winter Break and Zelda', None, None, None, ''),
	('[Not a Chapter] The End?', None, None, None, ''),
	('[Not a Chapter] This is not a chapter just as the tag says…..', None, None, None, ''),
	("[Not a Chapter] Translator's Introduction", None, None, None, ''),
	('[Not a Chapter] – Status Update: Hybrid, Magical Tournament, Chronicles, Experience and Teasers.', None, None, None, ''),
	('[Not a TL] Links page, but not only.', None, None, None, ''),
	('[Not a TL] Little hiatus, little new project, and you can ask me spoilers by mail.', None, None, None, ''),
	('[Not a TL] Website reworked (a little) and I will accept donations.', None, None, None, ''),
	('[Not a chapter]', None, None, None, ''),
	('[Not a chapter] Explanations in need', None, None, None, ''),
	('[Not a chapter] It’s one happy new if you’re curious', None, None, None, ''),
	('[Not a chapter] Reminder that this domain will expire soon', None, None, None, ''),
	('[Not a translation] 6 months later...', None, 6, None, ''),
	('[Not chapter] Clarification about last chapter', None, None, None, ''),
	('[Notice]Shikkaku (SK) on hiatus for some time. So some new info.', None, None, None, ''),
	('[Novel Review] 重生学霸当自强 – 萱草妖花', None, None, None, ''),
	('[Novel] Caught In My Own Trap 01', None, 1.0, None, ''),
	('[Novel] Caught In My Own Trap 02', None, 2.0, None, ''),
	('[Novel] Happy Little Mayor Chapter 1: Lord of Heart', None, 1.0, None, ''),
	('[Novel] My Mister Ostrich 016', None, 16.0, None, ''),
	('[Novel] My Mister Ostrich 017', None, 17.0, None, ''),
	('[Novel] My Mister Ostrich 018', None, 18.0, None, ''),
	('[Novel] My Mister Ostrich 019', None, 19.0, None, ''),
	('[Novel] My Mister Ostrich 020', None, 20.0, None, ''),
	('[Novel] My Mister Ostrich 021', None, 21.0, None, ''),
	('[Novel] My Mister Ostrich 022', None, 22.0, None, ''),
	('[Novel] My Mister Ostrich 023', None, 23.0, None, ''),
	('[Novel] My Mister Ostrich 024', None, 24.0, None, ''),
	('[Novel] My Mister Ostrich 025', None, 25.0, None, ''),
	('[Novel] My Mister Ostrich 026', None, 26.0, None, ''),
	('[Novel] My Mister Ostrich 027', None, 27.0, None, ''),
	('[Novel] My Mister Ostrich 028', None, 28.0, None, ''),
	('[Novel] My Mister Ostrich 029', None, 29.0, None, ''),
	('[Novel] My Mister Ostrich 030', None, 30.0, None, ''),
	('[Novel] My Mister Ostrich 031', None, 31.0, None, ''),
	('[Novel] My Mister Ostrich 032', None, 32.0, None, ''),
	('[Novel] My Mister Ostrich 033', None, 33.0, None, ''),
	('[Novel] My Mister Ostrich 034', None, 34.0, None, ''),
	('[Novel] My Mister Ostrich 035', None, 35.0, None, ''),
	('[Novel] My Mister Ostrich 036', None, 36.0, None, ''),
	('[Novel] My Mister Ostrich 037', None, 37.0, None, ''),
	('[Novel] My Mister Ostrich 038', None, 38.0, None, ''),
	('[Novel] My Mister Ostrich 039', None, 39.0, None, ''),
	('[Novel] My Mister Ostrich 040', None, 40.0, None, ''),
	('[Novel] My Mister Ostrich Prologue', None, None, None, 'Prologue'),
	('[Novel] The Left Ear 01 (1/3)', None, 1.0, None, ''),
	('[Novel] The Left Ear 01 (2/3)', None, 1.0, None, ''),
	('[Novel] The Left Ear 01 (3/3)', None, 1.0, None, ''),
	('[Nuwa] Prologue', None, None, None, 'Prologue'),
	('[Off Topic:] Christmas for Orphans', None, None, None, ''),
	('[Off Topic] : Reader Accusation and Comments', None, None, None, ''),
	('[Overlord Drama CD Vol. 1] Tracks 05 & 06', 1, 5, None, ''),
	('[Overlord Drama CD Vol. 1] Tracks 07 & 08', 1.0, 7.0, None, ''),
	('[Overlord Drama CD Vol. 1] Tracks 09 & 10', 1.0, 9.0, None, ''),
	('[Overlord v01] Chapter 1 | The end and the beginning - Part 1', 1, 1, 1, ''),
	('[Overlord v01] Chapter 1 | The end and the beginning - Part 2', 1, 1, 2, ''),
	('[Overlord v01] Prologue', 1, None, None, 'Prologue'),
	('[Owarimonogatari 3] Hitagi Rendezvous 001', None, 3.0, None, ''),
	('[Owarimonogatari 3] Hitagi Rendezvous 002', None, 3.0, None, ''),
	('[Owarimonogatari 3] Hitagi Rendezvous 003', None, 3.0, None, ''),
	('[Owarimonogatari 3] Hitagi Rendezvous 004', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 001', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 002', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 003', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 004', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 005', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 006', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 007', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 008', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 009', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 010', None, 3.0, None, ''),
	('[Owarimonogatari 3] Mayoi Hell 011', None, 3.0, None, ''),
	('[Owarimonogatari] Mayoi Hell 012', None, 12.0, None, ''),
	('[P.J] – Chapter 4', None, 4.0, None, ''),
	('[PE] Chapter 2: The Goddess and Sister Combo', None, 2.0, None, ''),
	('[POLL] Vote for the character naming order!', None, None, None, ''),
	('[Pinned] Mark is Dropped for now', None, None, None, ''),
	('[Pit] Chapter 1', None, 1.0, None, ''),
	('[Pit] Chapter 2', None, 2.0, None, ''),
	('[Pit] Chapter 3', None, 3.0, None, ''),
	('[Poll] What non-mainstream light novels should I translate?', None, None, None, ''),
	('[Project Announcement] Sword Art Online Alternative Gun Gale Online II -2nd Squad Jam- (I)', None, 2.0, None, ''),
	("[Project Announcement] Sword Art Online Alternative: Clover's Regret", None, None, None, ''),
	('[Project Announcement] Sword Art Online Comic Anthology Volume 1', 1.0, None, None, ''),
	('[RAMBLING] – A Presentation on Translation', None, None, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (1)', None, 1.0, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (2)', None, 1.0, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (3)', None, 1.0, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (4)', None, 1.0, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (5)', None, 1.0, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (6)', None, 1.0, None, ''),
	('[RATH!] Chapter 1. I didn’t know back then. (7)', None, 1.0, None, ''),
	('[RATH!] Chapter 2. Uhh… Mm… What’s that? Scary… (1)', None, 2.0, None, ''),
	('[RATH!] Chapter 2. Uhh… Mm… What’s that? Scary… (2)', None, 2.0, None, ''),
	('[RATH!] Chapter 2. Uhh… Mm… What’s that? Scary… (3)', None, 2.0, None, ''),
	('[RATH!] Chapter 2. Uhh… Mm… What’s that? Scary… (4)', None, 2.0, None, ''),
	('[RATH!] Chapter 2. Uhh… Mm… What’s that? Scary… (5)', None, 2.0, None, ''),
	('[RATH!] Prologue', None, None, None, 'Prologue'),
	('[RAW] Betsucomi Issue 12, 2015 and Hana to Yume Isssue 24, 2015', None, 12.0, None, ''),
	('[RAW] Furachi na Megane', None, None, None, ''),
	('[RAW] Hana to Yume - 2015-11-05', None, None, None, ''),
	('[RAW] Hana to Yume - Issue 09, 2016 (2016-04-05)', None, 9.0, None, ''),
	('[RAW] Hana to Yume - Issue 1, 2016 (2015-12-05)', None, 1.0, None, ''),
	('[RAW] Hana to Yume - Mega Release', None, None, None, ''),
	('[RAW] Hana to Yume Issue #10 (2016-04-20)', None, 10.0, None, ''),
	('[RAW] Hana to Yume Issue #11, 2016 (2016-05-05)', None, 11.0, None, ''),
	('[RAW] Kurotsuta Yashiki no Himegoto', None, None, None, ''),
	('[RAW] Lala - Issue # 1, 2016 (2015-11-24)', None, 1.0, None, ''),
	('[RAW] Lala DX - Issue 1, 2016 (2015-12-10)', None, 1.0, None, ''),
	('[RAW] Lala Issue #12, 2015 (2015-10-24)', None, 12.0, None, ''),
	('[RAW] Love So Life Volumes 15, 16 and 17 [END]', None, 15.0, None, ''),
	('[RAW] Nodoka no Niwa - Volume 1', 1.0, None, None, ''),
	('[RAW] Nodoka no Niwa - Volume 2', 2.0, None, None, ''),
	('[RAW] Petit Comic - Issue #12, 2015 (2015-11-08)', None, 12.0, None, ''),
	('[RAW] Petit Comic Issue #03, 2016 (2016-02-08)', None, 3.0, None, ''),
	('[RAW] Petit Comic Issue #04, 2016 (2016-03-08)', None, 4.0, None, ''),
	('[RAW] Petit Comic Issue #05 (2015-04-08)', None, 5.0, None, ''),
	('[RAW] Petit Comic Issue #11, 2015 (2015-10-08)', None, 11.0, None, ''),
	('[RAW] QQ Sweeper', None, None, None, ''),
	("[RAW] Queen's Quality - Volume 1", 1.0, None, None, ''),
	('[RAW] S Kei Megane Danshi 2', None, 2.0, None, ''),
	('[RAW] Shuriken to Pleats', None, None, None, ''),
	('[RAW] The Hana to Yume - December 2015 Issue', None, 2015.0, None, ''),
	('[RAW] Thunderbolt Fantasy Chapter 3', None, 3.0, None, ''),
	('[RAW] Two Months of Lala', None, None, None, ''),
	('[RAW] Two Months of Petit Comic', None, None, None, ''),
	('[RAW] Vampire Knight Side Story - Inochi to Owari to Tengoku no Aida (The Space Between Life, Death, and Heaven)', None, None, None, 'Side Story - Inochi to Owari to Tengoku no Aida (The Space Between Life, Death, and Heaven)'),
	('[RAW] Youchien de Aimashou', None, None, None, ''),
	('[RAW] Yume no Shizuku, Ougon no Torikago', None, None, None, ''),
	('[RELEASE] &#8211; GUNDAM 0083 VOL.05', 5, 8211, None, ''),
	('[RELEASE] Lily Ex Machina Chapter 1-59', None, 1, 59, ''),
	('[RELEASE] – NOVEMBER GUNDAM ACE TITLES', None, None, None, ''),
	('[RELEASE] – THE BLUE DESTINY (Stage 1)', None, 1.0, None, ''),
	('[RENEWAL] – Server Costs', None, None, None, ''),
	('[RPG&Disciple] PDFs and ePubs', None, None, None, ''),
	('[RPG] Chapter 5', None, 5.0, None, ''),
	('[RPG] Chapter 7', None, 7.0, None, ''),
	('[RPG] Vol. 5 Chapter 37', 5.0, 37.0, None, ''),
	('[RPG] Vol. 5 Chapter 38', 5.0, 38.0, None, ''),
	('[RPG] Vol. 5 Chapter 39', 5.0, 39.0, None, ''),
	('[RPG] Vol. 5 Chapter 40', 5.0, 40.0, None, ''),
	('[RPG] Vol. 5 Chapter 41', 5.0, 41.0, None, ''),
	('[RPG] Vol. 5 Chapter 5', 5.0, 5.0, None, ''),
	('[RPG] Vol. 6 Chapter 1', 6.0, 1.0, None, ''),
	('[RPG] Vol. 6 Chapter 10', 6.0, 10.0, None, ''),
	('[RPG] Vol. 6 Chapter 11', 6.0, 11.0, None, ''),
	('[RPG] Vol. 6 Chapter 12', 6.0, 12.0, None, ''),
	('[RPG] Vol. 6 Chapter 13', 6.0, 13.0, None, ''),
	('[RPG] Vol. 6 Chapter 14', 6.0, 14.0, None, ''),
	('[RPG] Vol. 6 Chapter 15', 6.0, 15.0, None, ''),
	('[RPG] Vol. 6 Chapter 16', 6.0, 16.0, None, ''),
	('[RPG] Vol. 6 Chapter 17', 6.0, 17.0, None, ''),
	('[RPG] Vol. 6 Chapter 18', 6.0, 18.0, None, ''),
	('[RPG] Vol. 6 Chapter 19', 6.0, 19.0, None, ''),
	('[RPG] Vol. 6 Chapter 2', 6.0, 2.0, None, ''),
	('[RPG] Vol. 6 Chapter 20', 6.0, 20.0, None, ''),
	('[RPG] Vol. 6 Chapter 21', 6.0, 21.0, None, ''),
	('[RPG] Vol. 6 Chapter 22', 6.0, 22.0, None, ''),
	('[RPG] Vol. 6 Chapter 23', 6.0, 23.0, None, ''),
	('[RPG] Vol. 6 Chapter 24', 6.0, 24.0, None, ''),
	('[RPG] Vol. 6 Chapter 25', 6.0, 25.0, None, ''),
	('[RPG] Vol. 6 Chapter 26', 6.0, 26.0, None, ''),
	('[RPG] Vol. 6 Chapter 27', 6.0, 27.0, None, ''),
	('[RPG] Vol. 6 Chapter 28', 6.0, 28.0, None, ''),
	('[RPG] Vol. 6 Chapter 29', 6.0, 29.0, None, ''),
	('[RPG] Vol. 6 Chapter 3', 6.0, 3.0, None, ''),
	('[RPG] Vol. 6 Chapter 30', 6.0, 30.0, None, ''),
	('[RPG] Vol. 6 Chapter 31', 6.0, 31.0, None, ''),
	('[RPG] Vol. 6 Chapter 32', 6.0, 32.0, None, ''),
	('[RPG] Vol. 6 Chapter 33', 6.0, 33.0, None, ''),
	('[RPG] Vol. 6 Chapter 34', 6.0, 34.0, None, ''),
	('[RPG] Vol. 6 Chapter 35', 6.0, 35.0, None, ''),
	('[RPG] Vol. 6 Chapter 36', 6.0, 36.0, None, ''),
	('[RPG] Vol. 6 Chapter 37', 6.0, 37.0, None, ''),
	('[RPG] Vol. 6 Chapter 38', 6.0, 38.0, None, ''),
	('[RPG] Vol. 6 Chapter 39', 6.0, 39.0, None, ''),
	('[RPG] Vol. 6 Chapter 4', 6.0, 4.0, None, ''),
	('[RPG] Vol. 6 Chapter 40', 6.0, 40.0, None, ''),
	('[RPG] Vol. 6 Chapter 41', 6.0, 41.0, None, ''),
	('[RPG] Vol. 6 Chapter 42', 6.0, 42.0, None, ''),
	('[RPG] Vol. 6 Chapter 43', 6.0, 43.0, None, ''),
	('[RPG] Vol. 6 Chapter 44', 6.0, 44.0, None, ''),
	('[RPG] Vol. 6 Chapter 45', 6.0, 45.0, None, ''),
	('[RPG] Vol. 6 Chapter 46', 6.0, 46.0, None, ''),
	('[RPG] Vol. 6 Chapter 47', 6.0, 47.0, None, ''),
	('[RPG] Vol. 6 Chapter 48', 6.0, 48.0, None, ''),
	('[RPG] Vol. 6 Chapter 49', 6.0, 49.0, None, ''),
	('[RPG] Vol. 6 Chapter 50', 6.0, 50.0, None, ''),
	('[RPG] Vol. 6 Chapter 51', 6.0, 51.0, None, ''),
	('[RPG] Vol. 6 Chapter 52', 6.0, 52.0, None, ''),
	('[RPG] Vol. 6 Chapter 6', 6.0, 6.0, None, ''),
	('[RPG] Vol. 6 Chapter 8', 6.0, 8.0, None, ''),
	('[RPG] Vol. 6 Chapter 9', 6.0, 9.0, None, ''),
	('[RPG] Vol. 6 Prologue', 6.0, None, None, 'Prologue'),
	('[RPG] Vol. 7 Chapter 1', 7.0, 1.0, None, ''),
	('[RPG] Vol. 7 Chapter 10', 7.0, 10.0, None, ''),
	('[RPG] Vol. 7 Chapter 11', 7.0, 11.0, None, ''),
	('[RPG] Vol. 7 Chapter 12', 7.0, 12.0, None, ''),
	('[RPG] Vol. 7 Chapter 13', 7.0, 13.0, None, ''),
	('[RPG] Vol. 7 Chapter 14', 7.0, 14.0, None, ''),
	('[RPG] Vol. 7 Chapter 15', 7.0, 15.0, None, ''),
	('[RPG] Vol. 7 Chapter 16', 7.0, 16.0, None, ''),
	('[RPG] Vol. 7 Chapter 17', 7.0, 17.0, None, ''),
	('[RPG] Vol. 7 Chapter 18', 7.0, 18.0, None, ''),
	('[RPG] Vol. 7 Chapter 19', 7.0, 19.0, None, ''),
	('[RPG] Vol. 7 Chapter 2', 7.0, 2.0, None, ''),
	('[RPG] Vol. 7 Chapter 20', 7.0, 20.0, None, ''),
	('[RPG] Vol. 7 Chapter 21', 7.0, 21.0, None, ''),
	('[RPG] Vol. 7 Chapter 22', 7.0, 22.0, None, ''),
	('[RPG] Vol. 7 Chapter 23', 7.0, 23.0, None, ''),
	('[RPG] Vol. 7 Chapter 24', 7.0, 24.0, None, ''),
	('[RPG] Vol. 7 Chapter 25', 7.0, 25.0, None, ''),
	('[RPG] Vol. 7 Chapter 26', 7.0, 26.0, None, ''),
	('[RPG] Vol. 7 Chapter 27', 7.0, 27.0, None, ''),
	('[RPG] Vol. 7 Chapter 28', 7.0, 28.0, None, ''),
	('[RPG] Vol. 7 Chapter 29', 7.0, 29.0, None, ''),
	('[RPG] Vol. 7 Chapter 3', 7.0, 3.0, None, ''),
	('[RPG] Vol. 7 Chapter 30', 7.0, 30.0, None, ''),
	('[RPG] Vol. 7 Chapter 31', 7.0, 31.0, None, ''),
	('[RPG] Vol. 7 Chapter 32', 7.0, 32.0, None, ''),
	('[RPG] Vol. 7 Chapter 4', 7.0, 4.0, None, ''),
	('[RPG] Vol. 7 Chapter 5', 7.0, 5.0, None, ''),
	('[RPG] Vol. 7 Chapter 6', 7.0, 6.0, None, ''),
	('[RPG] Vol. 7 Chapter 7', 7.0, 7.0, None, ''),
	('[RPG] Vol. 7 Chapter 8', 7.0, 8.0, None, ''),
	('[RPG] Vol. 7 Chapter 9', 7.0, 9.0, None, ''),
	('[RPG] Vol. 7 Prologue', 7.0, None, None, 'Prologue'),
	('[RPG] Vol. 8 Chapter 1', 8.0, 1.0, None, ''),
	('[RPG] Vol. 8 Chapter 10', 8.0, 10.0, None, ''),
	('[RPG] Vol. 8 Chapter 11', 8.0, 11.0, None, ''),
	('[RPG] Vol. 8 Chapter 12', 8.0, 12.0, None, ''),
	('[RPG] Vol. 8 Chapter 13', 8.0, 13.0, None, ''),
	('[RPG] Vol. 8 Chapter 14', 8.0, 14.0, None, ''),
	('[RPG] Vol. 8 Chapter 15', 8.0, 15.0, None, ''),
	('[RPG] Vol. 8 Chapter 16', 8.0, 16.0, None, ''),
	('[RPG] Vol. 8 Chapter 17', 8.0, 17.0, None, ''),
	('[RPG] Vol. 8 Chapter 18', 8.0, 18.0, None, ''),
	('[RPG] Vol. 8 Chapter 19', 8.0, 19.0, None, ''),
	('[RPG] Vol. 8 Chapter 2', 8.0, 2.0, None, ''),
	('[RPG] Vol. 8 Chapter 20', 8.0, 20.0, None, ''),
	('[RPG] Vol. 8 Chapter 21', 8.0, 21.0, None, ''),
	('[RPG] Vol. 8 Chapter 22', 8.0, 22.0, None, ''),
	('[RPG] Vol. 8 Chapter 23', 8.0, 23.0, None, ''),
	('[RPG] Vol. 8 Chapter 24', 8.0, 24.0, None, ''),
	('[RPG] Vol. 8 Chapter 3', 8.0, 3.0, None, ''),
	('[RPG] Vol. 8 Chapter 4', 8.0, 4.0, None, ''),
	('[RPG] Vol. 8 Chapter 5', 8.0, 5.0, None, ''),
	('[RPG] Vol. 8 Chapter 6', 8.0, 6.0, None, ''),
	('[RPG] Vol. 8 Chapter 7', 8.0, 7.0, None, ''),
	('[RPG] Vol. 8 Chapter 8', 8.0, 8.0, None, ''),
	('[RPG] Vol. 8 Chapter 9', 8.0, 9.0, None, ''),
	('[RPG] Vol. 8 Prologue', 8.0, None, None, 'Prologue'),
	('[RPG] Vol. 9 Chapter 1', 9.0, 1.0, None, ''),
	('[RPG] Vol. 9 Chapter 10', 9.0, 10.0, None, ''),
	('[RPG] Vol. 9 Chapter 2', 9.0, 2.0, None, ''),
	('[RPG] Vol. 9 Chapter 3', 9.0, 3.0, None, ''),
	('[RPG] Vol. 9 Chapter 4', 9.0, 4.0, None, ''),
	('[RPG] Vol. 9 Chapter 6', 9.0, 6.0, None, ''),
	('[RPG] Vol. 9 Chapter 7', 9.0, 7.0, None, ''),
	('[RPG] Vol. 9 Chapter 8', 9.0, 8.0, None, ''),
	('[RPG] Vol. 9 Chapter 9', 9.0, 9.0, None, ''),
	('[RPG] Vol. 9 Prologue', 9.0, None, None, 'Prologue'),
	('[Random]: Mars Insight Mission Name Entry', None, None, None, ''),
	('[RoTHD] Book 1, Prologue', 1.0, None, None, 'Prologue'),
	('[RoTL] Chapter 1', None, 1.0, None, ''),
	('[RoTL] Chapter 10. Salamander Creation (1)', None, 10.0, None, ''),
	('[RoTL] Chapter 2. Self-Defense(1)', None, 2.0, None, ''),
	('[RoTL] Chapter 3. Self-Defense(2)', None, 3.0, None, ''),
	('[RoTL] Chapter 4', None, 4.0, None, ''),
	('[RoTL] Chapter 5. Goblin Habitat (2)', None, 5.0, None, ''),
	('[RoTL] Chapter 6. Necromancer Class Advancement (1)', None, 6.0, None, ''),
	('[RoTL] Chapter 7. Necromancer Class Advancement (2)', None, 7.0, None, ''),
	('[RoTL] Chapter 8. Shard of Strength (1)', None, 8.0, None, ''),
	('[RoTL] Chapter 9. Shard of Strength (2)', None, 9.0, None, ''),
	('[Rumor & News] – Gundam Thunderbolt Anime Incoming?', None, None, None, ''),
	('[SAO Anthro] Nekoneko Quest Online', None, None, None, ''),
	("[SAO Comic Anthology] Asuna's SECRET", None, None, None, ''),
	('[SAO Comic Anthology] MAID iN AINCRAD', None, None, None, ''),
	('[SAO Comic Anthology] The Secret in the Depths of the Forest', None, None, None, ''),
	('[SAO V15] Chapter 17 – Dark Territory (25% completion)', 15.0, 17.0, None, ''),
	('[SAO V15] Chapter 17, Afterword, Illustrations complete! Volume complete!', 15.0, 17.0, None, 'Afterword, Illustrations complete! Volume complete!'),
	('[SAO V16] Chapter 19 and Afterword complete.', 16.0, 19.0, None, 'Afterword complete.'),
	('[SAO V16] Chapter 19 – The Radiant Medium (72% completion)', 16.0, 19.0, None, ''),
	('[SAO v17] Chapter 20 – Each of their Battles (70% completion)', 17.0, 20.0, None, ''),
	('[SAO] Chromatic Colors', None, None, None, ''),
	('[SAO] Ordinal Scale – Special Interview with Tomohiko Itou', None, None, None, ''),
	('[SAO] The Beginning – Prologue', None, None, None, 'Prologue'),
	('[SD] Chapter 10: Mysterious Power', None, 10.0, None, ''),
	('[SD] Chapter 11: Grey Matter', None, 11.0, None, ''),
	('[SD] Chapter 12: Unexpected Event', None, 12.0, None, ''),
	('[SD] Chapter 13: Evolution', None, 13.0, None, ''),
	('[SD] Chapter 14: Explosive Penguin', None, 14.0, None, ''),
	('[SD] Chapter 15: The Grand Chase Prequel', None, 15.0, None, ''),
	('[SD] Chapter 16: The Grand Chase', None, 16.0, None, ''),
	('[SD] Chapter 5: The Traumatic Bath', None, 5.0, None, ''),
	('[SD] Chapter 6: Birth of Untouchable Queen?', None, 6.0, None, ''),
	('[SD] Chapter 7: Standard Classes', None, 7.0, None, ''),
	('[SD] Chapter 8: The Transfer Students', None, 8.0, None, ''),
	('[SD] Chapter 9: Commoner & Aristocrat', None, 9.0, None, ''),
	('[SL] Chapter 09: Surrounded', None, 9.0, None, ''),
	('[SL] Chapter 10: Car Race', None, 10.0, None, ''),
	('[SS] 90-92', None, 90.0, None, ''),
	('[SS] Chapter 100!!!!!!', None, 100.0, None, ''),
	('[SS] Chapter 102', None, 102.0, None, ''),
	('[SS] Chapter 103', None, 103.0, None, ''),
	('[SS] Chapter 104', None, 104.0, None, ''),
	('[SS] Chapter 105', None, 105.0, None, ''),
	('[SS] Chapter 106', None, 106.0, None, ''),
	('[SS] Chapter 2: A Chance', None, 2.0, None, ''),
	('[SS] Chapter 3: A Second Name', None, 3.0, None, ''),
	('[SS] Chapter 4: It Was Luck', None, 4.0, None, ''),
	('[SS] Chapter 77', None, 77.0, None, ''),
	('[SS] Chapter 78: You Truly Are The Best!', None, 78.0, None, ''),
	('[SS] Chapter 84~', None, 84.0, None, ''),
	('[SS] Chapter 86', None, 86.0, None, ''),
	('[SS] Chapter 88', None, 88.0, None, ''),
	('[SS] Chapter 89', None, 89.0, None, ''),
	('[SS] Chapter 93', None, 93.0, None, ''),
	('[SS] Chapter 94', None, 94.0, None, ''),
	('[SS] Chapter 95', None, 95.0, None, ''),
	('[SS] Chapter 96', None, 96.0, None, ''),
	('[SS] Chapter 97', None, 97.0, None, ''),
	('[SS] Chapter 98', None, 98.0, None, ''),
	('[SS] Chapter 99', None, 99.0, None, ''),
	('[SS] Chapters 21-40', None, 21, 40, ''),
	('[SS] Chapters 82+83', None, 82.0, None, ''),
	('[SS] V6 Chapter 101', 6.0, 101.0, None, ''),
	('[SS] Volume 1 Chapter 1: I’ll Get Stronger!', 1.0, 1.0, None, ''),
	('[SS] chapter 85', None, 85.0, None, ''),
	('[SS] chapter 87', None, 87.0, None, ''),
	('[SS] v5 Chapter 81', 5.0, 81.0, None, ''),
	('[STR] Cleaning up some terms and names', None, None, None, ''),
	('[SWYZ] Chapter 10 part 1', None, 10, 1, ''),
	('[SWYZ] Chapter 6 : Mysterious new instructor(II)', None, 6, None, ''),
	('[SYWZ] 200!', None, 200.0, None, ''),
	('[SYWZ] 240', None, 240.0, None, ''),
	('[SYWZ] 241', None, 241.0, None, ''),
	('[SYWZ] 242', None, 242.0, None, ''),
	('[SYWZ] 243', None, 243.0, None, ''),
	('[SYWZ] 245', None, 245.0, None, ''),
	('[SYWZ] 246', None, 246.0, None, ''),
	('[SYWZ] 247', None, 247.0, None, ''),
	('[SYWZ] 248', None, 248.0, None, ''),
	('[SYWZ] 249', None, 249.0, None, ''),
	('[SYWZ] 261 –  Donation button: language fixed', None, 261.0, None, ''),
	('[SYWZ] 262', None, 262.0, None, ''),
	('[SYWZ] 263', None, 263.0, None, ''),
	('[SYWZ] 264', None, 264.0, None, ''),
	('[SYWZ] 265', None, 265.0, None, ''),
	('[SYWZ] 266', None, 266.0, None, ''),
	('[SYWZ] 267', None, 267.0, None, ''),
	('[SYWZ] 270', None, 270.0, None, ''),
	('[SYWZ] 271', None, 271.0, None, ''),
	('[SYWZ] 272', None, 272.0, None, ''),
	('[SYWZ] 273', None, 273.0, None, ''),
	('[SYWZ] 274 (and some thanks and news)', None, 274.0, None, ''),
	('[SYWZ] 275', None, 275.0, None, ''),
	('[SYWZ] 277', None, 277.0, None, ''),
	('[SYWZ] 278', None, 278.0, None, ''),
	('[SYWZ] 279', None, 279.0, None, ''),
	('[SYWZ] 280', None, 280.0, None, ''),
	('[SYWZ] 281', None, 281.0, None, ''),
	('[SYWZ] 282', None, 282.0, None, ''),
	('[SYWZ] 283 and 284 – Sorry and Thanks', None, 283.0, None, ''),
	('[SYWZ] 285', None, 285.0, None, ''),
	('[SYWZ] 286', None, 286.0, None, ''),
	('[SYWZ] 287', None, 287.0, None, ''),
	('[SYWZ] 288', None, 288.0, None, ''),
	('[SYWZ] 289', None, 289.0, None, ''),
	('[SYWZ] 290', None, 290.0, None, ''),
	('[SYWZ] 291', None, 291.0, None, ''),
	('[SYWZ] 292', None, 292.0, None, ''),
	('[SYWZ] 293', None, 293.0, None, ''),
	('[SYWZ] 294', None, 294.0, None, ''),
	('[SYWZ] 295', None, 295.0, None, ''),
	('[SYWZ] 296', None, 296.0, None, ''),
	('[SYWZ] 297', None, 297.0, None, ''),
	('[SYWZ] 298', None, 298.0, None, ''),
	('[SYWZ] 299', None, 299.0, None, ''),
	('[SYWZ] 300', None, 300.0, None, ''),
	('[SYWZ] 301', None, 301.0, None, ''),
	('[SYWZ] 302', None, 302.0, None, ''),
	('[SYWZ] 303', None, 303.0, None, ''),
	('[SYWZ] 304', None, 304.0, None, ''),
	('[SYWZ] 305', None, 305.0, None, ''),
	('[SYWZ] 306', None, 306.0, None, ''),
	('[SYWZ] 307', None, 307.0, None, ''),
	('[SYWZ] 308', None, 308.0, None, ''),
	('[SYWZ] 309', None, 309.0, None, ''),
	('[SYWZ] 310', None, 310.0, None, ''),
	('[SYWZ] 311', None, 311.0, None, ''),
	('[SYWZ] 312', None, 312.0, None, ''),
	('[SYWZ] 313', None, 313.0, None, ''),
	('[SYWZ] 314', None, 314.0, None, ''),
	('[SYWZ] 315', None, 315.0, None, ''),
	('[SYWZ] 316', None, 316.0, None, ''),
	('[SYWZ] 317', None, 317.0, None, ''),
	('[SYWZ] 318', None, 318.0, None, ''),
	('[SYWZ] 319', None, 319.0, None, ''),
	('[SYWZ] 320', None, 320.0, None, ''),
	('[SYWZ] 321', None, 321.0, None, ''),
	('[SYWZ] 322', None, 322.0, None, ''),
	('[SYWZ] 323', None, 323.0, None, ''),
	('[SYWZ] 324', None, 324.0, None, ''),
	('[SYWZ] 325', None, 325.0, None, ''),
	('[SYWZ] 326', None, 326.0, None, ''),
	('[SYWZ] 327', None, 327.0, None, ''),
	('[SYWZ] 328', None, 328.0, None, ''),
	('[SYWZ] 329', None, 329.0, None, ''),
	('[SYWZ] 330', None, 330.0, None, ''),
	('[SYWZ] 331', None, 331.0, None, ''),
	('[SYWZ] 332', None, 332.0, None, ''),
	('[SYWZ] 333', None, 333.0, None, ''),
	('[SYWZ] 334', None, 334.0, None, ''),
	('[SYWZ] 335', None, 335.0, None, ''),
	('[SYWZ] 336', None, 336.0, None, ''),
	('[SYWZ] 337', None, 337.0, None, ''),
	('[SYWZ] 338', None, 338.0, None, ''),
	('[SYWZ] 339', None, 339.0, None, ''),
	('[SYWZ] 340', None, 340.0, None, ''),
	('[SYWZ] 341', None, 341.0, None, ''),
	('[SYWZ] 342', None, 342.0, None, ''),
	('[SYWZ] 343 – 344 (and little thumbs up, please consider disabling adblocks and supporting us through the ads btw)', None, 343.0, None, ''),
	('[SYWZ] 345', None, 345.0, None, ''),
	('[SYWZ] 346', None, 346.0, None, ''),
	('[SYWZ] 347', None, 347.0, None, ''),
	('[SYWZ] 348', None, 348.0, None, ''),
	('[SYWZ] 349', None, 349.0, None, ''),
	('[SYWZ] 350', None, 350.0, None, ''),
	('[SYWZ] 351', None, 351.0, None, ''),
	('[SYWZ] 352', None, 352.0, None, ''),
	('[SYWZ] 353', None, 353.0, None, ''),
	('[SYWZ] 354', None, 354.0, None, ''),
	('[SYWZ] 355', None, 355.0, None, ''),
	('[SYWZ] 356', None, 356.0, None, ''),
	('[SYWZ] 357', None, 357.0, None, ''),
	('[SYWZ] 358', None, 358.0, None, ''),
	('[SYWZ] 359', None, 359.0, None, ''),
	('[SYWZ] 360', None, 360.0, None, ''),
	('[SYWZ] 361', None, 361.0, None, ''),
	('[SYWZ] 362', None, 362.0, None, ''),
	('[SYWZ] 363', None, 363.0, None, ''),
	('[SYWZ] 364', None, 364.0, None, ''),
	('[SYWZ] 365', None, 365.0, None, ''),
	('[SYWZ] 366', None, 366.0, None, ''),
	('[SYWZ] 367', None, 367.0, None, ''),
	('[SYWZ] 368', None, 368.0, None, ''),
	('[SYWZ] 369', None, 369.0, None, ''),
	('[SYWZ] 370', None, 370.0, None, ''),
	('[SYWZ] 371', None, 371.0, None, ''),
	('[SYWZ] 372', None, 372.0, None, ''),
	('[SYWZ] 373', None, 373.0, None, ''),
	('[SYWZ] 374', None, 374.0, None, ''),
	('[SYWZ] 375', None, 375.0, None, ''),
	('[SYWZ] 376', None, 376.0, None, ''),
	('[SYWZ] 377', None, 377.0, None, ''),
	('[SYWZ] 378', None, 378.0, None, ''),
	('[SYWZ] 379', None, 379.0, None, ''),
	('[SYWZ] 380', None, 380.0, None, ''),
	('[SYWZ] 381', None, 381.0, None, ''),
	('[SYWZ] 382 – may reneed to disable mail notifications', None, 382.0, None, ''),
	('[SYWZ] 383; good and bad news', None, 383.0, None, ''),
	('[SYWZ] 384', None, 384.0, None, ''),
	('[SYWZ] 385', None, 385.0, None, ''),
	('[SYWZ] 386', None, 386.0, None, ''),
	('[SYWZ] 387', None, 387.0, None, ''),
	('[SYWZ] 388', None, 388.0, None, ''),
	('[SYWZ] BACK HOME and Chapter 143', None, 143.0, None, ''),
	('[SYWZ] Chapter 10 part 2', None, 10, 2, ''),
	('[SYWZ] Chapter 11 (& Part 1 chapter 12 after edit Saturday 10:22 PM)', None, 11, 1, ''),
	('[SYWZ] Chapter 139', None, 139.0, None, ''),
	('[SYWZ] Chapter 140', None, 140.0, None, ''),
	('[SYWZ] Chapter 141', None, 141.0, None, ''),
	('[SYWZ] Chapter 141 – Sorry about the bug', None, 141.0, None, ''),
	('[SYWZ] Chapter 142', None, 142.0, None, ''),
	('[SYWZ] Chapter 144', None, 144.0, None, ''),
	('[SYWZ] Chapter 145', None, 145.0, None, ''),
	('[SYWZ] Chapter 146', None, 146.0, None, ''),
	('[SYWZ] Chapter 147', None, 147.0, None, ''),
	('[SYWZ] Chapter 148', None, 148.0, None, ''),
	('[SYWZ] Chapter 149', None, 149.0, None, ''),
	('[SYWZ] Chapter 150', None, 150.0, None, ''),
	('[SYWZ] Chapter 151', None, 151.0, None, ''),
	('[SYWZ] Chapter 152', None, 152.0, None, ''),
	('[SYWZ] Chapter 153', None, 153.0, None, ''),
	('[SYWZ] Chapter 154', None, 154.0, None, ''),
	('[SYWZ] Chapter 155', None, 155.0, None, ''),
	('[SYWZ] Chapter 156', None, 156.0, None, ''),
	('[SYWZ] Chapter 157', None, 157.0, None, ''),
	('[SYWZ] Chapter 158', None, 158.0, None, ''),
	('[SYWZ] Chapter 159', None, 159.0, None, ''),
	('[SYWZ] Chapter 16 and other updates', None, 16, None, ''),
	('[SYWZ] Chapter 16 and other updates + WE MOVE OUT', None, 16.0, None, ''),
	('[SYWZ] Chapter 160', None, 160.0, None, ''),
	('[SYWZ] Chapter 161', None, 161.0, None, ''),
	('[SYWZ] Chapter 162', None, 162.0, None, ''),
	('[SYWZ] Chapter 163', None, 163.0, None, ''),
	('[SYWZ] Chapter 164', None, 164.0, None, ''),
	('[SYWZ] Chapter 165', None, 165.0, None, ''),
	('[SYWZ] Chapter 166', None, 166.0, None, ''),
	('[SYWZ] Chapter 167', None, 167.0, None, ''),
	('[SYWZ] Chapter 169', None, 169.0, None, ''),
	('[SYWZ] Chapter 170', None, 170.0, None, ''),
	('[SYWZ] Chapter 171', None, 171.0, None, ''),
	('[SYWZ] Chapter 172', None, 172.0, None, ''),
	('[SYWZ] Chapter 173', None, 173.0, None, ''),
	('[SYWZ] Chapter 174', None, 174.0, None, ''),
	('[SYWZ] Chapter 175', None, 175.0, None, ''),
	('[SYWZ] Chapter 176', None, 176.0, None, ''),
	('[SYWZ] Chapter 177', None, 177.0, None, ''),
	('[SYWZ] Chapter 178', None, 178.0, None, ''),
	('[SYWZ] Chapter 179', None, 179.0, None, ''),
	('[SYWZ] Chapter 180', None, 180.0, None, ''),
	('[SYWZ] Chapter 181', None, 181.0, None, ''),
	('[SYWZ] Chapter 182', None, 182.0, None, ''),
	('[SYWZ] Chapter 183', None, 183.0, None, ''),
	('[SYWZ] Chapter 184', None, 184.0, None, ''),
	('[SYWZ] Chapter 185', None, 185.0, None, ''),
	('[SYWZ] Chapter 186', None, 186.0, None, ''),
	('[SYWZ] Chapter 187', None, 187.0, None, ''),
	('[SYWZ] Chapter 188', None, 188.0, None, ''),
	('[SYWZ] Chapter 189', None, 189.0, None, ''),
	('[SYWZ] Chapter 190', None, 190.0, None, ''),
	('[SYWZ] Chapter 191', None, 191.0, None, ''),
	('[SYWZ] Chapter 192', None, 192.0, None, ''),
	('[SYWZ] Chapter 193', None, 193.0, None, ''),
	('[SYWZ] Chapter 194', None, 194.0, None, ''),
	('[SYWZ] Chapter 195', None, 195.0, None, ''),
	('[SYWZ] Chapter 196', None, 196.0, None, ''),
	('[SYWZ] Chapter 197', None, 197.0, None, ''),
	('[SYWZ] Chapter 198', None, 198.0, None, ''),
	('[SYWZ] Chapter 199', None, 199.0, None, ''),
	('[SYWZ] Chapter 20', None, 20, None, ''),
	('[SYWZ] Chapter 201', None, 201.0, None, ''),
	('[SYWZ] Chapter 202', None, 202.0, None, ''),
	('[SYWZ] Chapter 203', None, 203.0, None, ''),
	('[SYWZ] Chapter 204', None, 204.0, None, ''),
	('[SYWZ] Chapter 205', None, 205.0, None, ''),
	('[SYWZ] Chapter 206', None, 206.0, None, ''),
	('[SYWZ] Chapter 207', None, 207.0, None, ''),
	('[SYWZ] Chapter 208', None, 208.0, None, ''),
	('[SYWZ] Chapter 209', None, 209.0, None, ''),
	('[SYWZ] Chapter 21', None, 21, None, ''),
	('[SYWZ] Chapter 210', None, 210.0, None, ''),
	('[SYWZ] Chapter 211', None, 211.0, None, ''),
	('[SYWZ] Chapter 212', None, 212.0, None, ''),
	('[SYWZ] Chapter 213', None, 213.0, None, ''),
	('[SYWZ] Chapter 214', None, 214.0, None, ''),
	('[SYWZ] Chapter 215', None, 215.0, None, ''),
	('[SYWZ] Chapter 217', None, 217.0, None, ''),
	('[SYWZ] Chapter 218', None, 218.0, None, ''),
	('[SYWZ] Chapter 219', None, 219.0, None, ''),
	('[SYWZ] Chapter 22 out', None, 22, None, ''),
	("[SYWZ] Chapter 220 – :'( :'(", None, 220.0, None, ''),
	('[SYWZ] Chapter 221', None, 221.0, None, ''),
	('[SYWZ] Chapter 222', None, 222.0, None, ''),
	('[SYWZ] Chapter 223', None, 223.0, None, ''),
	('[SYWZ] Chapter 224', None, 224.0, None, ''),
	('[SYWZ] Chapter 225', None, 225.0, None, ''),
	('[SYWZ] Chapter 226', None, 226.0, None, ''),
	('[SYWZ] Chapter 227', None, 227.0, None, ''),
	('[SYWZ] Chapter 228', None, 228.0, None, ''),
	('[SYWZ] Chapter 229', None, 229.0, None, ''),
	('[SYWZ] Chapter 23', None, 23, None, ''),
	('[SYWZ] Chapter 230', None, 230.0, None, ''),
	('[SYWZ] Chapter 231', None, 231.0, None, ''),
	('[SYWZ] Chapter 232', None, 232.0, None, ''),
	('[SYWZ] Chapter 233', None, 233.0, None, ''),
	('[SYWZ] Chapter 234', None, 234.0, None, ''),
	('[SYWZ] Chapter 235', None, 235.0, None, ''),
	('[SYWZ] Chapter 236', None, 236.0, None, ''),
	('[SYWZ] Chapter 237', None, 237.0, None, ''),
	('[SYWZ] Chapter 238', None, 238.0, None, ''),
	('[SYWZ] Chapter 239', None, 239.0, None, ''),
	('[SYWZ] Chapter 24', None, 24, None, ''),
	('[SYWZ] Chapter 244', None, 244.0, None, ''),
	('[SYWZ] Chapter 25 & I’m better now', None, 25, None, ''),
	('[SYWZ] Chapter 250', None, 250.0, None, ''),
	('[SYWZ] Chapter 251', None, 251.0, None, ''),
	('[SYWZ] Chapter 252', None, 252.0, None, ''),
	('[SYWZ] Chapter 253', None, 253.0, None, ''),
	('[SYWZ] Chapter 254', None, 254.0, None, ''),
	('[SYWZ] Chapter 255', None, 255.0, None, ''),
	('[SYWZ] Chapter 256', None, 256.0, None, ''),
	('[SYWZ] Chapter 257', None, 257.0, None, ''),
	('[SYWZ] Chapter 258', None, 258.0, None, ''),
	('[SYWZ] Chapter 259', None, 259.0, None, ''),
	('[SYWZ] Chapter 26', None, 26, None, ''),
	('[SYWZ] Chapter 260', None, 260.0, None, ''),
	('[SYWZ] Chapter 268', None, 268.0, None, ''),
	('[SYWZ] Chapter 27', None, 27, None, ''),
	('[SYWZ] Chapter 28 & Idea', None, 28, None, ''),
	('[SYWZ] Chapter 29', None, 29, None, ''),
	('[SYWZ] Chapter 30 & little stuff', None, 30, None, ''),
	('[SYWZ] Chapter 31 & Chapter 32; Donations', None, 31, None, ''),
	('[SYWZ] Chapter 33', None, 33, None, ''),
	('[SYWZ] Chapter 34', None, 34, None, ''),
	('[SYWZ] Chapter 35', None, 35, None, ''),
	('[SYWZ] Chapter 36', None, 36, None, ''),
	('[SYWZ] Chapter 37', None, 37, None, ''),
	('[SYWZ] Chapter 38', None, 38, None, ''),
	('[SYWZ] Chapter 39', None, 39, None, ''),
	('[SYWZ] Chapter 40; little question: ‘him’ or ‘it’?; interested in helping?', None, 40, None, ''),
	('[SYWZ] Chapter 41', None, 41, None, ''),
	('[SYWZ] Chapter 42; My opinion on Ye Hua.', None, 42, None, ''),
	('[SYWZ] Chapter 43', None, 43, None, ''),
	('[SYWZ] Chapter 44', None, 44, None, ''),
	('[SYWZ] Chapter 45', None, 45, None, ''),
	('[SYWZ] Chapter 46', None, 46, None, ''),
	('[SYWZ] Chapter 47', None, 47, None, ''),
	('[SYWZ] Chapter 48', None, 48, None, ''),
	('[SYWZ] Chapter 49; Important reminder, no spoilers in comment pls.', None, 49, None, ''),
	('[SYWZ] Chapter 50', None, 50, None, ''),
	('[SYWZ] Chapter 51', None, 51, None, ''),
	('[SYWZ] Chapter 52', None, 52, None, ''),
	('[SYWZ] Chapter 53', None, 53, None, ''),
	('[SYWZ] Chapter 54', None, 54, None, ''),
	('[SYWZ] Chapter 55 & 56, various updates, a solution about the confusing names?', None, 55, None, ''),
	('[SYWZ] Chapter 57 – just joking.', None, 57, None, ''),
	('[SYWZ] Chapter 58', None, 58, None, ''),
	('[SYWZ] Chapter 59', None, 59, None, ''),
	('[SYWZ] Chapter 60 – Title 16 done', None, 60, None, ''),
	('[SYWZ] Chapter 61', None, 61, None, ''),
	('[SYWZ] Chapter 62', None, 62, None, ''),
	('[SYWZ] Chapter 63', None, 63, None, ''),
	('[SYWZ] Chapter 64', None, 64, None, ''),
	('[SYWZ] Chapter 65', None, 65, None, ''),
	('[SYWZ] Chapter 66', None, 66, None, ''),
	('[SYWZ] Chapter 67', None, 67, None, ''),
	('[SYWZ] Chapter 68', None, 68, None, ''),
	('[SYWZ] Chapter 69', None, 69, None, ''),
	('[SYWZ] Chapter 7 2/2 & Chapter 8 1/2', None, 7, None, ''),
	('[SYWZ] Chapter 7 part 1/2', None, 7, 1, ''),
	('[SYWZ] Chapter 70', None, 70, None, ''),
	('[SYWZ] Chapter 71, and surprise upgrade', None, 71, None, ''),
	('[SYWZ] Chapter 72', None, 72, None, ''),
	('[SYWZ] Chapter 8 part 2/2 & Chapter 9 part 1/2', None, 8, 2, ''),
	('[SYWZ] Chapter 9 part 2/2', None, 9, 2, ''),
	('[SYWZ]Chapter 12 (& Chapter 13 part 1 after the edit of Monday 4:30 PM)', None, 12, 1, ''),
	('[Saki Aida] Deadlock – Chapter 2', None, 2.0, None, ''),
	('[Saki Aida] Deadlock – Chapter 3', None, 3.0, None, ''),
	('[Saki Aida] Deadlock – Chapter 4', None, 4.0, None, ''),
	('[Saki Aida] Deadlock – Prologue + Chapter 1', None, 1.0, None, 'Prologue + Chapter 1'),
	('[Second Saga]', None, None, None, ''),
	('[Second Saga] 41-60', None, 41.0, None, ''),
	('[Second Saga] Ch 1-20', None, 1, 20, ''),
	('[Second Saga] Chapter 62', None, 62.0, None, ''),
	('[Second Saga] Chapter 63', None, 63.0, None, ''),
	('[Second Saga] Chapter 64', None, 64.0, None, ''),
	('[Second Saga] Chapter 65: Shall I Wash Your Back?', None, 65.0, None, ''),
	('[Second Saga] Chapter 66', None, 66.0, None, ''),
	('[Second Saga] Chapter 67', None, 67.0, None, ''),
	('[Second Saga] Chapter 68', None, 68.0, None, ''),
	('[Second Saga] Chapter 69', None, 69.0, None, ''),
	('[Second Saga] Chapter 70', None, 70.0, None, ''),
	('[Second Saga] Chapter 71: Do You Like Me?', None, 71.0, None, ''),
	('[Second Saga] Chapter 73', None, 73.0, None, ''),
	('[Second Saga] Chapter 74: Enter The [White Winged Tree]', None, 74.0, None, ''),
	('[Second Saga] Chapter 75: The First Trial', None, 75.0, None, ''),
	('[Second Saga] Chapter 76', None, 76.0, None, ''),
	('[Second Saga] End of Volume 4', 4.0, None, None, ''),
	('[Second Saga] Fixing of Chapter 43', None, 43.0, None, ''),
	('[Second Saga] Volume 4 Chapter 61', 4.0, 61.0, None, ''),
	('[Second saga] Chapter 72', None, 72.0, None, ''),
	('[Seirei Gensouki] Episode 1 - Past Life', None, 1.0, None, ''),
	('[Seirei Gensouki] Episode 2 - Awakening', None, 2.0, None, ''),
	('[Seirei Gensouki] Episode 3 - Kidnapping', None, 3.0, None, ''),
	('[Seirei Gensouki] Episode 4 - Interrogation', None, 4.0, None, ''),
	('[Sekaimo v2] Ⅱ. Baekryeon :: Psychopath - /002', 2, 2, None, ''),
	('[Sekaimo v2] Ⅱ. Baekryeon :: Psychopath - /003a', 2, 3, None, ''),
	('[Sekaimo v2] Ⅱ. Baekryeon :: Psychopath - /003b', 2.0, 3.0, None, ''),
	('[Shimimaru] Queen Series – Ch. 5', None, 5.0, None, ''),
	('[Shinonome v1] Chapter 8', 1.0, 8.0, None, ''),
	('[Short Story] Esoril’s Dragon', None, None, None, ''),
	('[Shuumatsu] V1 C1 Before This World Ends – A', 1.0, 1.0, None, ''),
	('[Shuumatsu] V1 C2 In This Twilight World P1', 1.0, 2.0, 1.0, ''),
	('[Shuumatsu] V1 C3 The Forest in the Sky P2', 1.0, 3.0, 2.0, ''),
	('[Shuumatsu] V1 C3 The Forest in the Sky P3', 1.0, 3.0, 3.0, ''),
	('[Shuumatsu] V1 C3 The Forest in the Sky P4', 1.0, 3.0, 4.0, ''),
	('[Shuumatsu] V1 C3 The Forest in the Sky P5', 1.0, 3.0, 5.0, ''),
	('[Shuumatsu] V1 C4 When This Battle Ends P1', 1.0, 4.0, 1.0, ''),
	('[Shuumatsu] V1 C4 When This Battle Ends P2', 1.0, 4.0, 2.0, ''),
	('[Shuumatsu] V1 C4 When This Battle Ends P3', 1.0, 4.0, 3.0, ''),
	('[Shuumatsu] V1 C4 When This Battle Ends P4', 1.0, 4.0, 4.0, ''),
	('[Shuumatsu] V1 C4 When This Battle Ends P5', 1.0, 4.0, 5.0, ''),
	('[Shuumatsu] V1 C5 Before This World Ends – B', 1.0, 5.0, None, ''),
	('[Shuumatsu] V1 Chapter 1:Before This World Ends – A', 1.0, 1.0, None, ''),
	('[Shuumatsu] V2 C1 A Now Distant Dream – A', 2.0, 1.0, None, ''),
	('[Shuumatsu] V2 C2 Those Who Have yet to Come Home and Those Who Continue to Wait P1', 2.0, 2.0, 1.0, ''),
	('[Shuumatsu] V2 C2 Those Who Have yet to Come Home and Those Who Continue to Wait P2', 2.0, 2.0, 2.0, ''),
	('[Shuumatsu] V2 C2 Those Who Have yet to Come Home and Those Who Continue to Wait P3', 2.0, 2.0, 3.0, ''),
	('[Status] March 21st, 2016', None, 21.0, None, ''),
	('[TBS] Chapter 1-1. Beautiful Crossdresser', None, 1, 1, ''),
	('[TBS] Chapter 1-2. Hidden Story of Birth', None, 1, 2, ''),
	('[TBS] Chapter 1-3. Fiancee', None, 1, 3, ''),
	('[TL] A New Project?', None, None, None, ''),
	('[TL] Update Post!', None, None, None, ''),
	('[TPWY] Chapter 01', None, 1.0, None, ''),
	('[TPWY] Chapter 02', None, 2.0, None, ''),
	('[TPWY] Chapter 03', None, 3.0, None, ''),
	('[TPWY] Chapter 04', None, 4.0, None, ''),
	('[TPWY] Chapter 05', None, 5.0, None, ''),
	('[TPWY] Chapter 06', None, 6.0, None, ''),
	('[TPWY] Chapter 07', None, 7.0, None, ''),
	('[TPWY] Chapter 08', None, 8.0, None, ''),
	('[TPWY] Chapter 09', None, 9.0, None, ''),
	('[TPWY] Chapter 10', None, 10.0, None, ''),
	('[TPWY] Chapter 11', None, 11.0, None, ''),
	('[TPWY] Chapter 12', None, 12.0, None, ''),
	('[TPWY] Chapter 13', None, 13.0, None, ''),
	('[TPWY] Chapter 14', None, 14.0, None, ''),
	('[TPWY] Forewords', None, None, None, 'Forewords'),
	('[TT] How can Onion be sick', None, None, None, ''),
	('[TT] Regular for todayyyy', None, None, None, ''),
	('[TT] Waw two regular chaps', None, None, None, ''),
	('[TT] When Tofu came back in one piece', None, None, None, ''),
	('[TT] When Tofu is bad at driving', None, None, None, ''),
	('[TT] [MGZ Sale] I think your fish came true', None, None, None, ''),
	('[TT]Oh sht almost forgot', None, None, None, ''),
	('[Teaser/Recruitment] Overlord Drama CD Vol. 1 - Encoder WANTED', 1, None, None, ''),
	('[Teaser] Synopsis for “When I Returned Home, what I Found is Fantasy!?”', None, None, None, ''),
	('[Teaser] Synopsis of In a Different World with a Smartphone', None, None, None, ''),
	('[Teaser] 私、能力は平均値でって言ったよね！ Chapter 1 : Reincarnation 1', None, 1.0, None, ''),
	('[The Manual of Duke’s Daughter] Chapter 1', None, 1.0, None, ''),
	('[The Manual of Duke’s Daughter] Chapter 2', None, 2.0, None, ''),
	('[UNEDITED] Chapter 06 – Entrance Ceremony', None, 6.0, None, ''),
	('[UPDATE] – GUNDAM THUNDERBOLT', None, None, None, ''),
	('[URGENT] looking for a typesetter', None, None, None, ''),
	('[Unedited] Chapter 3 Unrest at Katjvarna’s Northern Boundaries Part 1', None, 3.0, 1.0, ''),
	('[Unedited] Chapter 3 Unrest at Katjvarna’s Northern Boundaries Part 2', None, 3.0, 2.0, ''),
	('[Unedited] Chapter 3 Unrest at Katjvarna’s Northern Boundaries Part 3', None, 3.0, 3.0, ''),
	('[Unedited] Chapter 4 Leaving with a Modest Reputation Part 1', None, 4.0, 1.0, ''),
	('[Unedited] Chapter 56: A Maou’s Night', None, 56.0, None, ''),
	('[Unedited] Christmas Special', None, None, None, ''),
	('[Until I do my best to make a harem as a Loner] Chapter 1: Loner’s way to school', None, 1.0, None, ''),
	('[Update]', None, None, None, ''),
	('[Update]  :3 Teehee :3', None, 3.0, None, ''),
	('[Update]  Hehe!~* ^_^', None, None, None, ''),
	('[Update]  …………      ^^”', None, None, None, ''),
	('[Update] (Not katahane though…)', None, None, None, ''),
	('[Update] -.-', None, None, None, ''),
	('[Update] Back :DDDDDDDDDD', None, None, None, ''),
	('[Update] Comment', None, None, None, ''),
	('[Update] Finally ;-;', None, None, None, ''),
	('[Update] Finally back -.-', None, None, None, ''),
	('[Update] Finally!!:D', None, None, None, ''),
	('[Update] Hohohohoho~* ‘ 3’', None, 3.0, None, ''),
	('[Update] I´m innocent ¬¬', None, None, None, ''),
	('[Update] Late… Nothing unusual…', None, None, None, ''),
	('[Update] Lolibaba', None, None, None, ''),
	('[Update] MY FIRST DONATION 0.00000000000000000000', None, 0.0, None, ''),
	('[Update] Meh', None, None, None, ''),
	('[Update] More chapters!', None, None, None, ''),
	('[Update] More… Chapters…', None, None, None, ''),
	('[Update] O.O', None, None, None, ''),
	('[Update] Sleepy… :c', None, None, None, ''),
	('[Update] Slowly…. Zzzzz…', None, None, None, ''),
	('[Update] Update?', None, None, None, ''),
	('[Update] zzzzz', None, None, None, ''),
	('[Update] ‘ 3’', None, 3.0, None, ''),
	('[Update] ….', None, None, None, ''),
	('[Updated] Drama ：《神雕侠侣》The Romance of the Condor Heroes + Trailer and Episodes', None, None, None, ''),
	('[Updates & Notices]', None, None, None, ''),
	('[VOL2] CHAPTER 5', 2.0, 5.0, None, ''),
	('[VW: Conquer the World] Chapter 10: Golden Slime King', None, 10.0, None, ''),
	('[VW: Conquer the World] Chapter 11: Purple Rhyme', None, 11.0, None, ''),
	('[VW: Conquer the World] Chapter 1: Dear God, Please give me a beautiful woman!', None, 1.0, None, ''),
	('[VW: Conquer the World] Chapter 5: Entering the Game', None, 5.0, None, ''),
	('[VW: Conquer the World] Chapter 6: Goblin Axe', None, 6.0, None, ''),
	('[VW: Conquer the World] Chapter 9: The Fated Ones', None, 9.0, None, ''),
	('[VW: Conquer the world] Chapter 4: A Fee for Staying', None, 4.0, None, ''),
	('[VW: Conquest of the War] Chapter 3: Spirit of Grief', None, 3.0, None, ''),
	('[Volume One] Chapter 1: Getting another chance', 1, 1, None, ''),
	('[WARNING] Dropped series!', None, None, None, ''),
	('[WIP] GGxrd Elphet', None, None, None, ''),
	('[WN] Doll Dungeon 1-14.', None, 1.0, None, ''),
	('[WN] Doll Dungeon 4-1. Character Profile', None, 4.0, None, ''),
	('[WN] Doll Dungeon 4-2. Chat Thread', None, 4.0, None, ''),
	('[WN] Doll Dungeon Part 1-10', None, 10.0, 1.0, ''),
	('[WN] Doll Dungeon Part 1-11.', None, 11.0, 1.0, ''),
	('[WN] Doll Dungeon Part 1-12.', None, 12.0, 1.0, ''),
	('[WN] Doll Dungeon Part 1-13.', None, 13.0, 1.0, ''),
	('[WN] Doll Dungeon Part 1-7.', None, 7.0, 1.0, ''),
	('[WN] Doll Dungeon Part 1-8.', None, 8.0, 1.0, ''),
	('[WN] Doll Dungeon Part 1-9.', None, 9.0, 1.0, ''),
	('[WN] Impregnable Dreadnought Prologues (1) and (2)', None, 1.0, None, 'Prologues (1) and (2)'),
	('[WN] Insolent Knight and Prince of Mask 00. Thunder roars, then comes a sudden shower.', None, 0.0, None, ''),
	('[WN] Insolent Knight and Prince of Mask 01. What business do you have with a mere pharmacist?', None, 1.0, None, ''),
	('[WN] Otoko Aruji 1-3. It’s not Earth, either.', None, 1.0, None, ''),
	('[WN] Sword Saint’s Disciple 2-1. History of the Country’s Founding and the First Destination', None, 2.0, None, ''),
	('[WN] Sword Saint’s Disciple 2-2. Raza Town and Soldier Guild', None, 2.0, None, ''),
	('[WN] Sword Saint’s Disciple 2-3. Rank and Commission', None, 2.0, None, ''),
	('[WN] Sword Saint’s Disciple 2-4. Old Soldier’s Advice', None, 2.0, None, ''),
	('[WN] Sword Saint’s Disciple 2-5. Lord Raza’s Mansion', None, 2.0, None, ''),
	('[WN] Sword Saint’s Disciple Interlude. Reincarnation Eve ~ Small Fame ~', None, None, None, 'Interlude. Reincarnation Eve ~ Small Fame ~'),
	('[WN] The Strategist Knows Everything Chapters 1-2', None, 1, 2, ''),
	('[WN] Third Prince Elmer 5-6. One day, the Prince-sama… (1)', None, 5.0, None, ''),
	('[WN] Third Prince Elmer 5-7. One day, the Prince-sama… (2)', None, 5.0, None, ''),
	('[WN] Third Prince Elmer 5-8. Occupational Experience Learning (1)', None, 5.0, None, ''),
	('[WN] Third Prince Elmer 5-9. Occupational Experience Learning (2)', None, 5.0, None, ''),
	('[When They Cry] The First and Last Gift', None, None, None, ''),
	('[World of Immortals] Author’s Note', None, None, None, ''),
	('[not a chapter whatsoever] the reddits commenter', None, None, None, ''),
	('[obligatory new year post]', None, None, None, ''),
]

