

data = [
	('HAPPY NEW YEAR 2016!', None, 2016.0, None, ''),
	('HAPPY NEW YEAR!', None, None, None, ''),
	('HATHAWAY&#8217;S FLASH &#8211; CHAPTER.02 LOUNGE', None, 2, None, ''),
	('HATHAWAY&#8217;S FLASH &#8211; CHAPTER.04 HIJACK', None, 4, None, ''),
	('HATHAWAY&#8217;S FLASH &#8211; CHAPTER.06 LANDING GROUND', None, 6, None, ''),
	('HATHAWAY&#8217;S FLASH &#8211; CHAPTER.07 WITH GIGI', None, 7, None, ''),
	('HATHAWAY&#8217;S FLASH &#8211; CHAPTER.1 GIGI', None, 1, None, ''),
	('HATHAWAY&#8217;S FLASH &#8211; PROLOGUE', None, 8217.0, None, 'PROLOGUE'),
	('HATHAWAY’S FLASH – CHAPTER.03 KENNETH', None, 3, None, ''),
	('HATHAWAY’S FLASH – CHAPTER.05 HATHAWAY', None, 5, None, ''),
	('HBMJTT 狩猎美男之古旅—Chapter 10: I’d rather die than enter the Jianghu Community', None, 10.0, None, ''),
	('HCLS – Chapter 5', None, 5.0, None, ''),
	('HCLS – Chapter 6', None, 6.0, None, ''),
	('HCLS – Chapter 7', None, 7.0, None, ''),
	('HCLS – Chapter 8', None, 8.0, None, ''),
	('HCOP Book 2, Chapter 76: Helping Out Some Old Friends', 2.0, 76.0, None, ''),
	('HCOP Book 2, Chapter 77: Another Draw', 2.0, 77.0, None, ''),
	('HCOP Chapter 74: The Guardians', None, 74.0, None, ''),
	('HCOP Chapter 75: The Chaotic Three-Way… Battle', None, 75.0, None, ''),
	('HCOP Prologue and Edited Chapter 1', None, 1.0, None, 'Prologue and Edited Chapter 1'),
	('HDUH – Chapter 19', None, 19.0, None, ''),
	('HDUH – Chapter 20', None, 20.0, None, ''),
	('HDUH – Chapter 21', None, 21.0, None, ''),
	('HDUH – Chapter 22', None, 22.0, None, ''),
	('HDUH – Chapter 23', None, 23.0, None, ''),
	('HDUH – Chapter 24', None, 24.0, None, ''),
	('HEAVENLY JEWEL CHANGE (Indonesia)', None, None, None, ''),
	('HEAVY OBJECT', None, None, None, ''),
	('HEAVY OBJECT (Indonesia):Halaman Pendaftaran', None, None, None, ''),
	('HEAVY OBJECT:Volume 1 Epilog', 1.0, None, None, ''),
	('HEAVY OBJECT:Volume 1 Ilustrasi', 1.0, None, None, ''),
	('HEAVY OBJECT:Volume 1 Penutup', 1.0, None, None, ''),
	('HEAVY OBJECT:Volume 1 Prolog', 1.0, None, None, ''),
	('HEAVY OBJECT:Volume 10 Ilustrasi', 10.0, None, None, ''),
	('HEAVY OBJECT:Volume 11 Ilustrasi', 11.0, None, None, ''),
	('HEAVY OBJECT:Volume 2 Bagian 2', 2.0, 2.0, None, ''),
	('HEAVY OBJECT:Volume 2 Ilustrasi', 2.0, None, None, ''),
	('HEAVY OBJECT:Volume 2 Prolog', 2.0, None, None, ''),
	('HEAVY OBJECT:Volume 3 Illustrasi', 3.0, None, None, ''),
	('HEAVY OBJECT:Volume 3 Prolog', 3.0, None, None, ''),
	('HEAVY OBJECT:Volume 4 Illustrasi', 4.0, None, None, ''),
	('HEAVY OBJECT:Volume 5 Illustrasi', 5.0, None, None, ''),
	('HEAVY OBJECT:Volume 6 Illustrasi', 6.0, None, None, ''),
	('HEAVY OBJECT:Volume 6 Ilustrasi', 6.0, None, None, ''),
	('HEAVY OBJECT:Volume 7 Ilustrasi', 7.0, None, None, ''),
	('HEAVY OBJECT:Volume 9 Ilustrasi', 9.0, None, None, ''),
	('HEAVY OBJECT:Volume8 Ilustrasi', 8.0, None, None, ''),
	('HELLLAND; Smoke', None, None, None, ''),
	('HEY ALL it’s been forever since I updated&hellip; anything. I’ve been on a huge hiatus. That said,...', None, None, None, ''),
	('HIATUS ANNOUCEMENT', None, None, None, ''),
	('HIATUS CONCLUDED! SERVICE RESUMED!', None, None, None, ''),
	('HJC Glossary', None, None, None, ''),
	('HJC Glossary Update + Error Fixing (31.3)', None, 31.3, None, ''),
	('HJC Mini Hiatus', None, None, None, ''),
	('HJC Vol 10 Chapter 83 Part 2 Release', 10.0, 83.0, 2.0, ''),
	('HJC Vol 10 Chapter 83 Part 3 Release', 10.0, 83.0, 3.0, ''),
	('HJC Vol 10 Chapter 84 Part 1 Release', 10.0, 84.0, 1.0, ''),
	('HJC Vol 10 Chapter 84 Part 2 Release', 10.0, 84.0, 2.0, ''),
	('HJC Vol 10 Chapter 85 Part 1 Release', 10.0, 85.0, 1.0, ''),
	('HJC Vol 10 Chapter 85 Part 2 Release', 10.0, 85.0, 2.0, ''),
	('HJC Vol 10 Chapter 85 Part 3 Release', 10.0, 85.0, 3.0, ''),
	('HJC Vol 10 Chapter 86 Part 1 Release', 10.0, 86.0, 1.0, ''),
	('HJC Vol 11 Chapter 86 Part 2 Release', 11.0, 86.0, 2.0, ''),
	('HJC Vol 11 Chapter 86 Part 3 Release', 11.0, 86.0, 3.0, ''),
	('HJC Vol 11 Chapter 87 Part 1 Release', 11.0, 87.0, 1.0, ''),
	('HJC Vol 11 Chapter 87 Part 2 Release', 11.0, 87.0, 2.0, ''),
	('HJC Vol 11 Chapter 87 Part 3 Release', 11.0, 87.0, 3.0, ''),
	('HJC Vol 11 Chapter 88 Part 1 Release', 11.0, 88.0, 1.0, ''),
	('HJC Vol 11 Chapter 88 Part 2 Release', 11.0, 88.0, 2.0, ''),
	('HJC Vol 11 Chapter 88 Part 3 Release', 11.0, 88.0, 3.0, ''),
	('HJC Vol 11 Chapter 89 Part 1 Release', 11.0, 89.0, 1.0, ''),
	('HJC Vol 11 Chapter 89 Part 2 Release', 11.0, 89.0, 2.0, ''),
	('HJC Vol 11 Chapter 89 Part 3 Release', 11.0, 89.0, 3.0, ''),
	('HJC Vol 11 Chapter 90 Part 1 Release', 11.0, 90.0, 1.0, ''),
	('HJC Vol 11 Chapter 90 Part 2 Release', 11.0, 90.0, 2.0, ''),
	('HJC Vol 11 Chapter 90 Part 3 Release', 11.0, 90.0, 3.0, ''),
	('HJC Vol 11 Chapter 91 Release', 11.0, 91.0, None, ''),
	('HJC Vol 12 Chapter 92 Part 1 Release', 12.0, 92.0, 1.0, ''),
	('HJC Vol 12 Chapter 92 Part 2 Release', 12.0, 92.0, 2.0, ''),
	('HJC Vol 12 Chapter 92 Part 3 Release', 12.0, 92.0, 3.0, ''),
	('HJC Vol 12 Chapter 93 Part 1 Release', 12.0, 93.0, 1.0, ''),
	('HJC Vol 12 Chapter 93 Part 2 Release', 12.0, 93.0, 2.0, ''),
	('HJC Vol 12 Chapter 93 Part 3 Release', 12.0, 93.0, 3.0, ''),
	('HJC Vol 12 Chapter 94 Part 1 Release', 12.0, 94.0, 1.0, ''),
	('HJC Vol 12 Chapter 94 Part 2 Release', 12.0, 94.0, 2.0, ''),
	('HJC Vol 3 Chapter 17 Part 3 Release', 3.0, 17.0, 3.0, ''),
	('HJC Vol 3 Chapter 17 Part 4 Release', 3.0, 17.0, 4.0, ''),
	('HJC Vol 3 Chapter 18 Part 1-2 Release', 3.0, 18.0, 1.0, ''),
	('HJC Vol 3 Chapter 18 Part 3 Release', 3.0, 18.0, 3.0, ''),
	('HJC Vol 3 Chapter 18 Part 4 Release', 3.0, 18.0, 4.0, ''),
	('HJC Vol 3 Chapter 19 Part 1 Release', 3.0, 19.0, 1.0, ''),
	('HJC Vol 3 Chapter 19 Part 2 Release', 3.0, 19.0, 2.0, ''),
	('HJC Vol 3 Chapter 19 Part 3 Release', 3.0, 19.0, 3.0, ''),
	('HJC Vol 3 Chapter 19 Part 4 Release', 3.0, 19.0, 4.0, ''),
	('HJC Vol 3 Chapter 20 Part 1 Release', 3.0, 20.0, 1.0, ''),
	('HJC Vol 3 Chapter 20 Part 2 Release', 3.0, 20.0, 2.0, ''),
	('HJC Vol 3 Chapter 20 Part 3 Release', 3.0, 20.0, 3.0, ''),
	('HJC Vol 3 Chapter 20 Part 4 Release', 3.0, 20.0, 4.0, ''),
	('HJC Vol 3 Chapter 21 Part 1 Release', 3.0, 21.0, 1.0, ''),
	('HJC Vol 3 Chapter 21 Part 2 Release', 3.0, 21.0, 2.0, ''),
	('HJC Vol 3 Chapter 21 Part 3 Release', 3.0, 21.0, 3.0, ''),
	('HJC Vol 3 Chapter 21 Part 4 Release', 3.0, 21.0, 4.0, ''),
	('HJC Vol 4 Chapter 22 Part 1 Release', 4.0, 22.0, 1.0, ''),
	('HJC Vol 4 Chapter 22 Part 2 Release', 4.0, 22.0, 2.0, ''),
	('HJC Vol 5 Chapter 25 Part 1 Release', 5.0, 25.0, 1.0, ''),
	('HJC Vol 5 Chapter 25 Part 2 Release', 5.0, 25.0, 2.0, ''),
	('HJC Vol 5 Chapter 25 Part 3 Release', 5.0, 25.0, 3.0, ''),
	('HJC Vol 5 Chapter 26 Part 1 Release', 5.0, 26.0, 1.0, ''),
	('HJC Vol 5 Chapter 26 Part 2 Release', 5.0, 26.0, 2.0, ''),
	('HJC Vol 5 Chapter 26 Part 3 Release', 5.0, 26.0, 3.0, ''),
	('HJC Vol 5 Chapter 27 Part 1 Release', 5.0, 27.0, 1.0, ''),
	('HJC Vol 5 Chapter 27 Part 2 Release', 5.0, 27.0, 2.0, ''),
	('HJC Vol 5 Chapter 27 Part 3 Release', 5.0, 27.0, 3.0, ''),
	('HJC Vol 5 Chapter 28 Part 1 Release', 5.0, 28.0, 1.0, ''),
	('HJC Vol 5 Chapter 28 Part 2 Release', 5.0, 28.0, 2.0, ''),
	('HJC Vol 5 Chapter 29 Part 1 Release', 5.0, 29.0, 1.0, ''),
	('HJC Vol 5 Chapter 29 Part 2 Release', 5.0, 29.0, 2.0, ''),
	('HJC Vol 5 Chapter 29 Part 3 Release', 5.0, 29.0, 3.0, ''),
	('HJC Vol 5 Chapter 30 Part 1 Release', 5.0, 30.0, 1.0, ''),
	('HJC Vol 5 Chapter 30 Part 2 Release', 5.0, 30.0, 2.0, ''),
	('HJC Vol 5 Chapter 30 Part 3 Release', 5.0, 30.0, 3.0, ''),
	('HJC Vol 5 Chapter 31 Part 1 Release', 5.0, 31.0, 1.0, ''),
	('HJC Vol 5 Chapter 31 Part 2 Release', 5.0, 31.0, 2.0, ''),
	('HJC Vol 5 Chapter 31 Part 3 Release', 5.0, 31.0, 3.0, ''),
	('HJC Vol 5 Chapter 32 Part 1 Release', 5.0, 32.0, 1.0, ''),
	('HJC Vol 5 Chapter 32 Part 2 Release', 5.0, 32.0, 2.0, ''),
	('HJC Vol 5 Chapter 32 Part 3 Release', 5.0, 32.0, 3.0, ''),
	('HJC Vol 5 Chapter 33 Part 1 Release', 5.0, 33.0, 1.0, ''),
	('HJC Vol 5 Chapter 33 Part 2 Release', 5.0, 33.0, 2.0, ''),
	('HJC Vol 5 Chapter 33 Part 3 Release', 5.0, 33.0, 3.0, ''),
	('HJC Vol 5 Chapter 34 Part 1', 5.0, 34.0, 1.0, ''),
	('HJC Vol 5 Chapter 34 Part 2 Release', 5.0, 34.0, 2.0, ''),
	('HJC Vol 5 Chapter 34 Part 3 Release', 5.0, 34.0, 3.0, ''),
	('HJC Vol 5 Chapter 35 Part 1 Release', 5.0, 35.0, 1.0, ''),
	('HJC Vol 5 Chapter 35 Part 2 Release', 5.0, 35.0, 2.0, ''),
	('HJC Vol 6 Chapter 36 Part 1 Release', 6.0, 36.0, 1.0, ''),
	('HJC Vol 6 Chapter 36 Part 2 Release', 6.0, 36.0, 2.0, ''),
	('HJC Vol 6 Chapter 36 Part 3 Release', 6.0, 36.0, 3.0, ''),
	('HJC Vol 6 Chapter 37 Part 1 Release', 6.0, 37.0, 1.0, ''),
	('HJC Vol 6 Chapter 37 Part 2 Release', 6.0, 37.0, 2.0, ''),
	('HJC Vol 6 Chapter 37 Part 3 Release', 6.0, 37.0, 3.0, ''),
	('HJC Vol 6 Chapter 38 Part 1 Release', 6.0, 38.0, 1.0, ''),
	('HJC Vol 6 Chapter 38 Part 2 Release', 6.0, 38.0, 2.0, ''),
	('HJC Vol 6 Chapter 38 Part 3 Release', 6.0, 38.0, 3.0, ''),
	('HJC Vol 6 Chapter 39 Part 1 Release', 6.0, 39.0, 1.0, ''),
	('HJC Vol 6 Chapter 39 Part 2 Release', 6.0, 39.0, 2.0, ''),
	('HJC Vol 6 Chapter 39 Part 3 Release', 6.0, 39.0, 3.0, ''),
	('HJC Vol 6 Chapter 40 Part 1 Release', 6.0, 40.0, 1.0, ''),
	('HJC Vol 6 Chapter 40 Part 2 Release', 6.0, 40.0, 2.0, ''),
	('HJC Vol 6 Chapter 40 Part 3 Release', 6.0, 40.0, 3.0, ''),
	('HJC Vol 6 Chapter 41 Part 1 Release', 6.0, 41.0, 1.0, ''),
	('HJC Vol 6 Chapter 41 Part 2 Release', 6.0, 41.0, 2.0, ''),
	('HJC Vol 6 Chapter 41 Part 3 Release', 6.0, 41.0, 3.0, ''),
	('HJC Vol 6 Chapter 42 Part 1 Release', 6.0, 42.0, 1.0, ''),
	('HJC Vol 6 Chapter 42 Part 2 Release', 6.0, 42.0, 2.0, ''),
	('HJC Vol 6 Chapter 43 Part 1 Release', 6.0, 43.0, 1.0, ''),
	('HJC Vol 6 Chapter 43 Part 2 Release', 6.0, 43.0, 2.0, ''),
	('HJC Vol 6 Chapter 43 Part 3 Release', 6.0, 43.0, 3.0, ''),
	('HJC Vol 6 Chapter 44 Part 1 Release', 6.0, 44.0, 1.0, ''),
	('HJC Vol 6 Chapter 44 Part 2 Release', 6.0, 44.0, 2.0, ''),
	('HJC Vol 6 Chapter 44 Part 3 Release', 6.0, 44.0, 3.0, ''),
	('HJC Vol 6 Chapter 45 Part 1 Release', 6.0, 45.0, 1.0, ''),
	('HJC Vol 6 Chapter 45 Part 2 Release', 6.0, 45.0, 2.0, ''),
	('HJC Vol 6 Chapter 45 Part 3 Release', 6.0, 45.0, 3.0, ''),
	('HJC Vol 6 Chapter 46 Part 1 Release', 6.0, 46.0, 1.0, ''),
	('HJC Vol 6 Chapter 46 Part 2 Release', 6.0, 46.0, 2.0, ''),
	('HJC Vol 6 Chapter 46 Part 3 Release', 6.0, 46.0, 3.0, ''),
	('HJC Vol 6 Chapter 47 Part 1 Release', 6.0, 47.0, 1.0, ''),
	('HJC Vol 6 Chapter 47 Part 2 Release', 6.0, 47.0, 2.0, ''),
	('HJC Vol 6 Chapter 47 Part 3 Release', 6.0, 47.0, 3.0, ''),
	('HJC Vol 6 Chapter 48 Part 1 Release', 6.0, 48.0, 1.0, ''),
	('HJC Vol 6 Chapter 48 Part 2 Release', 6.0, 48.0, 2.0, ''),
	('HJC Vol 6 Chapter 48 Part 3 Release', 6.0, 48.0, 3.0, ''),
	('HJC Vol 6 Chapter 49 Part 1 Release', 6.0, 49.0, 1.0, ''),
	('HJC Vol 6 Chapter 49 Part 2 Release', 6.0, 49.0, 2.0, ''),
	('HJC Vol 6 Chapter 50 Part 1 Release', 6.0, 50.0, 1.0, ''),
	('HJC Vol 6 Chapter 50 Part 2 Release', 6.0, 50.0, 2.0, ''),
	('HJC Vol 6 Chapter 50 Part 3 Release', 6.0, 50.0, 3.0, ''),
	('HJC Vol 6 Chapter 51 Part 1 Release', 6.0, 51.0, 1.0, ''),
	('HJC Vol 6 Chapter 51 Part 2 Release', 6.0, 51.0, 2.0, ''),
	('HJC Vol 6 Chapter 51 Part 3 Release', 6.0, 51.0, 3.0, ''),
	('HJC Vol 6 Chapter 52 Part 1 Release', 6.0, 52.0, 1.0, ''),
	('HJC Vol 6 Chapter 52 Part 2 Release', 6.0, 52.0, 2.0, ''),
	('HJC Vol 6 Chapter 52 Part 3 Release', 6.0, 52.0, 3.0, ''),
	('HJC Vol 6 Chapter 53 Part 1 Release', 6.0, 53.0, 1.0, ''),
	('HJC Vol 6 Chapter 53 Part 2 Release', 6.0, 53.0, 2.0, ''),
	('HJC Vol 6 Chapter 53 Part 3 Release', 6.0, 53.0, 3.0, ''),
	('HJC Vol 6 Chapter 54 Part 1 Release', 6.0, 54.0, 1.0, ''),
	('HJC Vol 6 Chapter 54 Part 2 Release', 6.0, 54.0, 2.0, ''),
	('HJC Vol 6 Chapter 54 Part 3 Release', 6.0, 54.0, 3.0, ''),
	('HJC Vol 7 Chapter 55 Part 2 Release', 7.0, 55.0, 2.0, ''),
	('HJC Vol 7 Chapter 55 Part 3 Release', 7.0, 55.0, 3.0, ''),
	('HJC Vol 7 Chapter 56 Part 1 Release', 7.0, 56.0, 1.0, ''),
	('HJC Vol 7 Chapter 56 Part 2 Release', 7.0, 56.0, 2.0, ''),
	('HJC Vol 7 Chapter 57 Part 1 Release', 7.0, 57.0, 1.0, ''),
	('HJC Vol 7 Chapter 57 Part 2 Release', 7.0, 57.0, 2.0, ''),
	('HJC Vol 7 Chapter 57 Part 3 Release', 7.0, 57.0, 3.0, ''),
	('HJC Vol 7 Chapter 58 Part 1 Release', 7.0, 58.0, 1.0, ''),
	('HJC Vol 7 Chapter 58 Part 2 Release', 7.0, 58.0, 2.0, ''),
	('HJC Vol 7 Chapter 58 Part 3 Release', 7.0, 58.0, 3.0, ''),
	('HJC Vol 7 Chapter 59 Part 1 Release', 7.0, 59.0, 1.0, ''),
	('HJC Vol 7 Chapter 59 Part 2 Release', 7.0, 59.0, 2.0, ''),
	('HJC Vol 7 Chapter 59 Part 3 Release', 7.0, 59.0, 3.0, ''),
	('HJC Vol 7 Chapter 60 Part 1 and 2 Release', 7.0, 60.0, 1.0, ''),
	('HJC Vol 7 Chapter 60 Part 3 Release', 7.0, 60.0, 3.0, ''),
	('HJC Vol 7 Chapter 61 Part 1 Release', 7.0, 61.0, 1.0, ''),
	('HJC Vol 7 Chapter 61 Part 2 and 3 Release', 7.0, 61.0, 2.0, ''),
	('HJC Vol 8 Chapter 62 Part 1 Release', 8.0, 62.0, 1.0, ''),
	('HJC Vol 8 Chapter 62 Part 2 Release', 8.0, 62.0, 2.0, ''),
	('HJC Vol 8 Chapter 62 Part 3 Release', 8.0, 62.0, 3.0, ''),
	('HJC Vol 8 Chapter 63 Part 1 Release', 8.0, 63.0, 1.0, ''),
	('HJC Vol 8 Chapter 63 Part 2 Release', 8.0, 63.0, 2.0, ''),
	('HJC Vol 8 Chapter 64 Part 1 Release', 8.0, 64.0, 1.0, ''),
	('HJC Vol 8 Chapter 64 Part 2 Release', 8.0, 64.0, 2.0, ''),
	('HJC Vol 8 Chapter 64 Part 3 Release', 8.0, 64.0, 3.0, ''),
	('HJC Vol 8 Chapter 65 Part 1 Release', 8.0, 65.0, 1.0, ''),
	('HJC Vol 8 Chapter 65 Part 2 Release', 8.0, 65.0, 2.0, ''),
	('HJC Vol 8 Chapter 65 Part 3 Release', 8.0, 65.0, 3.0, ''),
	('HJC Vol 8 Chapter 66 Part 1 Release', 8.0, 66.0, 1.0, ''),
	('HJC Vol 8 Chapter 66 Part 2 Release', 8.0, 66.0, 2.0, ''),
	('HJC Vol 8 Chapter 66 Part 3 Release', 8.0, 66.0, 3.0, ''),
	('HJC Vol 8 Chapter 67 Part 1 Release', 8.0, 67.0, 1.0, ''),
	('HJC Vol 8 Chapter 67 Part 2 Release', 8.0, 67.0, 2.0, ''),
	('HJC Vol 8 Chapter 67 Part 3 Release', 8.0, 67.0, 3.0, ''),
	('HJC Vol 8 Chapter 68 Part 1 Release', 8.0, 68.0, 1.0, ''),
	('HJC Vol 8 Chapter 68 Part 2 Release', 8.0, 68.0, 2.0, ''),
	('HJC Vol 8 Chapter 68 Part 3 Release', 8.0, 68.0, 3.0, ''),
	('HJC Vol 8 Chapter 69 Part 1 Release', 8.0, 69.0, 1.0, ''),
	('HJC Vol 8 Chapter 69 Part 2 Release', 8.0, 69.0, 2.0, ''),
	('HJC Vol 8 Chapter 69 Part 3 Release', 8.0, 69.0, 3.0, ''),
	('HJC Vol 8 Chapter 70 Part 1 Release', 8.0, 70.0, 1.0, ''),
	('HJC Vol 8 Chapter 70 Part 2 Release', 8.0, 70.0, 2.0, ''),
	('HJC Vol 9 Chapter 71 Part 1 Release', 9.0, 71.0, 1.0, ''),
	('HJC Vol 9 Chapter 71 Part 2 Release', 9.0, 71.0, 2.0, ''),
	('HJC Vol 9 Chapter 71 Part 3 Release', 9.0, 71.0, 3.0, ''),
	('HJC Vol 9 Chapter 72 Part 1 Release', 9.0, 72.0, 1.0, ''),
	('HJC Vol 9 Chapter 72 Part 2 Release', 9.0, 72.0, 2.0, ''),
	('HJC Vol 9 Chapter 72 Part 3 Release', 9.0, 72.0, 3.0, ''),
	('HJC Vol 9 Chapter 73 Part 1 Release', 9.0, 73.0, 1.0, ''),
	('HJC Vol 9 Chapter 73 Part 2 Release', 9.0, 73.0, 2.0, ''),
	('HJC Vol 9 Chapter 73 Part 3 Release', 9.0, 73.0, 3.0, ''),
	('HJC Vol 9 Chapter 74 Part 1 Release', 9.0, 74.0, 1.0, ''),
	('HJC Vol 9 Chapter 74 Part 2 Release', 9.0, 74.0, 2.0, ''),
	('HJC Vol 9 Chapter 74 Part 3 Release', 9.0, 74.0, 3.0, ''),
	('HJC Vol 9 Chapter 75 Part 1 Release', 9.0, 75.0, 1.0, ''),
	('HJC Vol 9 Chapter 75 Part 2 Release', 9.0, 75.0, 2.0, ''),
	('HJC Vol 9 Chapter 75 Part 3 Release', 9.0, 75.0, 3.0, ''),
	('HJC Vol 9 Chapter 76 Part 2 Release', 9.0, 76.0, 2.0, ''),
	('HJC Vol 9 Chapter 76 Part 3 Release', 9.0, 76.0, 3.0, ''),
	('HJC Vol 9 Chapter 77 Part 1 Release', 9.0, 77.0, 1.0, ''),
	('HJC Vol 9 Chapter 77 Part 2 Release', 9.0, 77.0, 2.0, ''),
	('HJC Vol 9 Chapter 78 Part 1 Release', 9.0, 78.0, 1.0, ''),
	('HJC Vol 9 Chapter 78 Part 2 Release', 9.0, 78.0, 2.0, ''),
	('HJC Vol 9 Chapter 78 Part 3 Release', 9.0, 78.0, 3.0, ''),
	('HJC Vol 9 Chapter 79 Part 1 Release', 9.0, 79.0, 1.0, ''),
	('HJC Vol 9 Chapter 79 Part 2 Release', 9.0, 79.0, 2.0, ''),
	('HJC Vol 9 Chapter 79 Part 3 Release', 9.0, 79.0, 3.0, ''),
	('HJC Vol 9 Chapter 80 Part 1 Release', 9.0, 80.0, 1.0, ''),
	('HJC Vol 9 Chapter 80 Part 2 Release', 9.0, 80.0, 2.0, ''),
	('HJC Vol 9 Chapter 80 Part 3 Release', 9.0, 80.0, 3.0, ''),
	('HJC Vol 9 Chapter 81 Part 1 Release', 9.0, 81.0, 1.0, ''),
	('HJC Vol 9 Chapter 81 Part 2 Release', 9.0, 81.0, 2.0, ''),
	('HJC Vol 9 Chapter 81 Part 3 Release', 9.0, 81.0, 3.0, ''),
	('HJC Vol 9 Chapter 82 Part 1 Release', 9.0, 82.0, 1.0, ''),
	('HJC Vol 9 Chapter 82 Part 2 Release', 9.0, 82.0, 2.0, ''),
	('HJC Vol 9 Chapter 82 Part 3 Release', 9.0, 82.0, 3.0, ''),
	('HJC Vol 9 Chapter 83 Part 1 Release', 9.0, 83.0, 1.0, ''),
	('HJC Volume 3 Chapter 17 Part 2 Release', 3.0, 17.0, 2.0, ''),
	('HJC Volume 3 Chapter 17 Part 3 Release', 3.0, 17.0, 3.0, ''),
	('HJC – Mini Hiatus, Sick', None, None, None, ''),
	('HJC – New Synopsis', None, None, None, ''),
	('HN Fans & Followers', None, None, None, ''),
	('HN1F Chapter 10: The Second Lottery Chance', None, 10.0, None, ''),
	('HN1F Chapter 11: Master Must Strive to Strengthen Himself', None, 11.0, None, ''),
	('HN1F Chapter 12: Encountering a Disciple Stealer', None, 12.0, None, ''),
	('HN1F Chapter 13: The Fallen Prodigy', None, 13.0, None, ''),
	('HN1F Chapter 14: 2 Rings', None, 14.0, None, ''),
	('HN1F Chapter 15: It’s Not Easy Being A Milk Dad', None, 15.0, None, ''),
	('HN1F Chapter 16: Fighting for the Post of Old Grandpa', None, 16.0, None, ''),
	('HN1F Chapter 17: Old Grandma…', None, 17.0, None, ''),
	('HN1F Chapter 18: So What if it’s the Number 1 Holy Land', None, 18.0, None, ''),
	('HN1F Chapter 1: The Cheating System', None, 1.0, None, ''),
	('HN1F Chapter 20: Lots of Surprises', None, 20.0, None, ''),
	('HN1F Chapter 21: Enemy, Aurous Core Stage Cultivator', None, 21.0, None, ''),
	('HN1F Chapter 22: Start Up: New System Tool!', None, 22.0, None, ''),
	('HN1F Chapter 23: Kid, Have You Messed Around Enough Yet?', None, 23.0, None, ''),
	('HN1F Chapter 24: You’re Overthinking', None, 24.0, None, ''),
	('HN1F Chapter 25: Second! Third?', None, 25.0, None, ''),
	('HN1F Chapter 26: The Tragic Holy Maiden', None, 26.0, None, ''),
	('HN1F Chapter 27: Hidden Benefit', None, 27.0, None, ''),
	('HN1F Chapter 28: Senior and Junior', None, 28.0, None, ''),
	('HN1F Chapter 29: Farewell', None, 29.0, None, ''),
	('HN1F Chapter 2: Being the Old Grandpa for People', None, 2.0, None, ''),
	('HN1F Chapter 30: Marquis Bastard, Awe-Inspiring Righteousness', None, 30.0, None, ''),
	('HN1F Chapter 31: The Power of Max Luck', None, 31.0, None, ''),
	('HN1F Chapter 32: The Master that Cheats the Disciple', None, 32.0, None, ''),
	('HN1F Chapter 35: The Pursuers Arrive', None, 35.0, None, ''),
	('HN1F Chapter 36: Fierce Monk, 24 Heaven Arhat Formation', None, 36.0, None, ''),
	('HN1F Chapter 3: Enemy Attack!', None, 3.0, None, ''),
	('HN1F Chapter 41: Random Side Quest', None, 41.0, None, ''),
	('HN1F Chapter 43: Mt. Shu Sword Cultivator', None, 43.0, None, ''),
	('HN1F Chapter 44: Relentlessly Beating the Dog in the Water', None, 44.0, None, ''),
	('HN1F Chapter 45: I was Waiting for You, Baldy!', None, 45.0, None, ''),
	('HN1F Chapter 46: The Source of the Blood River', None, 46.0, None, ''),
	('HN1F Chapter 47: Watching How You Die!', None, 47.0, None, ''),
	('HN1F Chapter 48: You’re a Good Person', None, 48.0, None, ''),
	('HN1F Chapter 49: We Are From the Yu Clan', None, 49.0, None, ''),
	('HN1F Chapter 50: Keep Silent', None, 50.0, None, ''),
	('HN1F Chapter 52: 3 in 1 Big Gift', None, 52.0, None, ''),
	('HN1F Chapter 53: None of Them are Fools', None, 53.0, None, ''),
	('HN1F Chapter 54: All Sides Take Action', None, 54.0, None, ''),
	('HN1F Chapter 55: One Step Late!', None, 55.0, None, ''),
	('HN1F Chapter 56: Sudden Surprise', None, 56.0, None, ''),
	('HN1F Chapter 57: Qi Disciple Great Circle of Perfection', None, 57.0, None, ''),
	('HN1F Chapter 58: Little girl, Uncle Will Take You to See Goldfishes', None, 58.0, None, ''),
	('HN1F Chapter 59: The Exchange Competition that was Brought Forward', None, 59.0, None, ''),
	('HN1F Chapter 5: The First Lottery Chance', None, 5.0, None, ''),
	('HN1F Chapter 60: Not Just One Person has Their Mind on Him', None, 60.0, None, ''),
	('HN1F Chapter 61: Business Snatcher', None, 61.0, None, ''),
	('HN1F Chapter 62: The Script isn’t Right!', None, 62.0, None, ''),
	('HN1F Chapter 63: Get Away From My Disciple!', None, 63.0, None, ''),
	('HN1F Chapter 65: Master Isn’t Home: The First Bullet', None, 65.0, None, ''),
	('HN1F Chapter 66: Master Isn’t Home: Trouble Comes Knocking', None, 66.0, None, ''),
	('HN1F Chapter 67: True Netherworld Water', None, 67.0, None, ''),
	('HN1F Chapter 68: Within the Netherworld Bead', None, 68.0, None, ''),
	('HN1F Chapter 6: You’re Going to Get Screwed', None, 6.0, None, ''),
	('HN1F Chapter 70: Master Isn’t Home: No Place to Run', None, 70.0, None, ''),
	('HN1F Chapter 71: Head Supporting the Heavens, Feet Trampling the Netherworld', None, 71.0, None, ''),
	('HN1F Chapter 72: First Main Quest, Complete!', None, 72.0, None, ''),
	('HN1F Chapter 73: Master Isn’t Home: Surrounded by Enemies', None, 73.0, None, ''),
	('HN1F Chapter 74: Master Isn’t Home: Won’t Submit!', None, 74.0, None, ''),
	('HN1F Chapter 75: Beat Everyone Down!', None, 75.0, None, ''),
	('HN1F Chapter 76: Nobody’s Leaving!', None, 76.0, None, ''),
	('HN1F Chapter 77: New Main Quest Issued!', None, 77.0, None, ''),
	('HN1F Chapter 78: Flowing Wind Sigil, Wind & Thunder Genesis Sigil Formation', None, 78.0, None, ''),
	('HN1F Chapter 79: Tricking the Hell out of People', None, 79.0, None, ''),
	('HN1F Chapter 7: Celeritas vs Peach Blossom', None, 7.0, None, ''),
	('HN1F Chapter 80: Amazing Luck', None, 80.0, None, ''),
	('HN1F Chapter 81: Test You Guys', None, 81.0, None, ''),
	('HN1F Chapter 82: When the Master has Something to do, the Disciple does the Work', None, 82.0, None, ''),
	('HN1F Chapter 83: Ancient World Marsh', None, 83.0, None, ''),
	('HN1F Chapter 84: If the Snake does not Die', None, 84.0, None, ''),
	('HN1F Chapter 85 Don’t Want to Bully Kids', None, 85.0, None, ''),
	('HN1F Chapter 86: If I Use Aurous Core Stage Strength, Consider it Me Bullying You Guys', None, 86.0, None, ''),
	('HN1F Chapter 87: Fiery Beauty', None, 87.0, None, ''),
	('HN1F Chapter 88: General Wicked', None, 88.0, None, ''),
	('HN1F Chapter 89: Snowgale Survivors', None, 89.0, None, ''),
	('HN1F Chapter 8: I’ve Remembered You', None, 8.0, None, ''),
	('HN1F Chapter 90: Strange Person Underground', None, 90.0, None, ''),
	('HN1F Chapter 91: A Promise Made is a Promise Kept for Life!', None, 91.0, None, ''),
	('HN1F Chapter 92: Stone Flute Secret Area', None, 92.0, None, ''),
	('HN1F Chapter 9: Hurry Up and Come Into Master’s Bowl', None, 9.0, None, ''),
	('HN1F: Chapter 4: There’s Something Wrong With That Old Tree!', None, 4.0, None, ''),
	('HN1F: Chapter 51: Bullying With Numbers', None, 51.0, None, ''),
	('HPC chapter 17: Deceiving gentleness', None, 17.0, None, ''),
	('HPC chapter 18: Deceiving gentleness', None, 18.0, None, ''),
	('HPC chapter 19: Ben Wang is very busy, has no time', None, 19.0, None, ''),
	('HPC chapter 20: Ben Wang is very busy, has no time', None, 20.0, None, ''),
	('HPC chapter 21-22: Counter soldiers with arms, water with an earth weir', None, 21, 22, ''),
	('HPC chapter 23-24: Counter soldiers with arms, water with an earth weir', None, 23, 24, ''),
	('HS Chapter 1', None, 1.0, None, ''),
	('HS Chapter 15', None, 15.0, None, ''),
	('HS Chapter 16', None, 16.0, None, ''),
	('HS Chapter 17 and some news', None, 17.0, None, ''),
	('HS Chapter 18', None, 18.0, None, ''),
	('HS Chapter 19', None, 19.0, None, ''),
	('HS Chapter 20', None, 20.0, None, ''),
	('HS Chapter 21', None, 21.0, None, ''),
	('HS Chapter 22-23', None, 22, 23, ''),
	('HS – Chapter 24', None, 24.0, None, ''),
	('HS-Chapter 25', None, 25.0, None, ''),
	('HS-Chapter 26-27', None, 26.0, None, ''),
	('HS-Chapter 28', None, 28.0, None, ''),
	('HS-Chapter 29', None, 29.0, None, ''),
	('HS-Chapter 30', None, 30.0, None, ''),
	('HS-Chapter 31', None, 31.0, None, ''),
	('HS-Chapter 32', None, 32.0, None, ''),
	('HS-Chapter 33', None, 33.0, None, ''),
	('HS-Chapter 34', None, 34.0, None, ''),
	('HS-Chapter 35&36', None, 35.0, None, ''),
	('HS-Chapter 37-39', None, 37.0, None, ''),
	('HS-Chapter 41', None, 41.0, None, ''),
	('HS-Chapter 42', None, 42.0, None, ''),
	('HS-Chapter 43', None, 43.0, None, ''),
	('HS-Chapter 44', None, 44.0, None, ''),
	('HS-Chapter 45', None, 45.0, None, ''),
	('HS-Chapter 46-47', None, 46.0, None, ''),
	('HS-Quick status update', None, None, None, ''),
	('HTG : ch 1(prologue) – The God has an idea.', None, 1, None, '1(prologue) – The God has an idea.'),
	('HTG : ch 2 Girl Reincarnation', None, 2, None, ''),
	('HTG: CH 5 – A Rival Appears', None, 5.0, None, ''),
	('HTG: CH 6 – The First Victim', None, 6.0, None, ''),
	('HTG: ch 3 HikiNEET Vs Thief Couple', None, 3, None, ''),
	('HTG: ch 4 The Guardian is the great swordswoman.', None, 4, None, ''),
	('HTK: When Udon’s about to get fired', None, None, None, ''),
	('HTSAS Chapter 20 is up and waiting.', None, 20.0, None, ''),
	('HTSAS101 Cover Art! whoohoo!', None, 101.0, None, ''),
	('HUDH – Chapter 11', None, 11.0, None, ''),
	('HUDH – Chapter 12', None, 12.0, None, ''),
	('HUDH – Chapter 13', None, 13.0, None, ''),
	('HUDH – Chapter 14', None, 14.0, None, ''),
	('HUDH – Chapter 15', None, 15.0, None, ''),
	('HUDH – Chapter 16', None, 16.0, None, ''),
	('HUDH – Chapter 17', None, 17.0, None, ''),
	('HUGE Skyfire Avenue Release – Chapters 89-92', None, 89, 92, ''),
	('Hachi-nan Chapter 26 Draft', None, 26.0, None, ''),
	('Hachi-nan Chapter 27 Draft', None, 27.0, None, ''),
	('Hachi-nan Chapter 28 Draft', None, 28.0, None, ''),
	('Hachi-nan Chapter 29', None, 29.0, None, ''),
	('Hachi-nan Chapter 31', None, 31.0, None, ''),
	('Hachi-nan chapter 30 part 2', None, 30.0, 2.0, ''),
	('Hachi-nan chapter 30 part 3.', None, 30.0, 3.0, ''),
	('Hachi-nan part 2 TEASER', None, None, 2.0, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 30: Erich-nii-san’s marriage', None, 30.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 31: Circumstances of the Helmut Kingdom Aristrocacy', None, 31.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 32: Royal Head Magician, Klimt Christoph von Armstrong', None, 32.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 33: A brief holiday', None, 33.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 34: Compulsory army order: Old dragon subjugation', None, 34.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 36: My fiance is nicknamed Saint', None, 36.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 37: The Saint’s First Date', None, 37.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 38: Studying at the Royal Capital', None, 38.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 39: Story about increasing the masters', None, 39.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 40: Turning 15 years old', None, 40.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 41: Adventurer registration', None, 41.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 42: The dangerous adventurer debut fight', None, 42.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 43: The Loot from the Underground Ruin', None, 43.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 44: The overwhelming reward', None, 44.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 45: The started adventurer life and a new request – part 1', None, 45.0, 1.0, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 45: The started adventurer live and a new request – part 2', None, 45.0, 2.0, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 46: Coming home after a long while – Part 1', None, 46.0, 1.0, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 46: Coming home after a long while – part 2', None, 46.0, 2.0, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 47: Once again Klaus', None, 47.0, None, ''),
	('Hachinan tte, sore wa nai deshou! – Chapter 47: Once again Klaus – Part 1', None, 47.0, 1.0, ''),
	('Hachinan tte, sore wa nai deshou! – Interlude 10: Pink Hippo-san', None, 10.0, None, 'Interlude 10: Pink Hippo-san'),
	('Hachinan tte, sore wa nai deshou! – Interlude 11: The Saint’s confession', None, 11.0, None, 'Interlude 11: The Saint’s confession'),
	('Hachinan tte, sore wa nai deshou! – Interlude 12: The Lord’s weird instruction', None, 12.0, None, 'Interlude 12: The Lord’s weird instruction'),
	('Hachinan tte, sore wa nai deshou! – Interlude 13 – A shady realtor', None, 13.0, None, 'Interlude 13 – A shady realtor'),
	('Hachinan tte, sore wa nai deshou! – Interlude 14: Duel Uproar', None, 14.0, None, 'Interlude 14: Duel Uproar'),
	('Hachinan tte, sore wa nai deshou! – Interlude 15: Helmut-nii-san’s adoption into the family of his bride', None, 15.0, None, 'Interlude 15: Helmut-nii-san’s adoption into the family of his bride'),
	('Hachinan tte, sore wa nai deshou! – Interlude 16: Night before the Martial Arts Tournament', None, 16.0, None, 'Interlude 16: Night before the Martial Arts Tournament'),
	('Hachinan tte, sore wa nai deshou! – Interlude 17: Performance at the Martial Arts Tournament', None, 17.0, None, 'Interlude 17: Performance at the Martial Arts Tournament'),
	('Hachinan tte, sore wa nai deshou! – Interlude 6: A strong-willed Loli girl', None, 6.0, None, 'Interlude 6: A strong-willed Loli girl'),
	('Hachinan tte, sore wa nai deshou! – Interlude 7: Circumstances surrounding the composition of the Associate Baron Baumeister’s feudal troops', None, 7.0, None, 'Interlude 7: Circumstances surrounding the composition of the Associate Baron Baumeister’s feudal troops'),
	('Hachinan tte, sore wa nai deshou! – Interlude 8: Behind the scenes of the Fiancée Selection', None, 8.0, None, 'Interlude 8: Behind the scenes of the Fiancée Selection'),
	('Hachinan tte, sore wa nai deshou! – Interlude 9: At the Baumeister knight peerage after the dragon subjugation', None, 9.0, None, 'Interlude 9: At the Baumeister knight peerage after the dragon subjugation'),
	('Hachinan tte, sore wa nai desshou! – Chapter 35: Fiance', None, 35.0, None, ''),
	('Hackjob: Part 10', None, None, 10.0, ''),
	('Hackjob: Part 11', None, None, 11.0, ''),
	('Hackjob: Part 5', None, None, 5.0, ''),
	('Hackjob: Part 6', None, None, 6.0, ''),
	('Hackjob: Part 7', None, None, 7.0, ''),
	('Hackjob: Part 8', None, None, 8.0, ''),
	('Hackjob: Part 9', None, None, 9.0, ''),
	('Haganai Announcement', None, None, None, ''),
	('Haganai Volume 10 Chapter 2 released!', 10, 2, None, ''),
	('Haganai Volume 10 Chapter 3 released!', 10, 3, None, ''),
	('Haganai Volume 10 Chapter 4 released!', 10.0, 4.0, None, ''),
	('Haganai Volume 10 Chapter 5 preview!', 10.0, 5.0, None, ''),
	('Haganai Volume 10 Chapter 5 released!', 10.0, 5.0, None, ''),
	('Haganai Volume 10 Chapter 6 preview!', 10.0, 6.0, None, ''),
	('Haganai Volume 10 Chapter 6 released!', 10.0, 6.0, None, ''),
	('Haganai Volume 10 Chapter 7 preview!', 10.0, 7.0, None, ''),
	('Haganai Volume 10 Chapter 7 released!', 10.0, 7.0, None, ''),
	('Haganai Volume 10 Chapter 8 released!', 10.0, 8.0, None, ''),
	('Hagure Yuusha no Aesthetica', None, None, None, ''),
	('Hagure Yuusha no Aesthetica:Registration Page', None, None, None, ''),
	('Hagure Yuusha no Aesthetica:Volume 9 Chapter 1', 9.0, 1.0, None, ''),
	('Hagure Yuusha no Aesthetica:Volume 9 Prologue', 9.0, None, None, 'Prologue'),
	('Hai to Gensou no Grimgal’s sister story. TEASER.', None, None, None, ''),
	('Hai to Gensou no Grimgar', None, None, None, ''),
	('Hai to Gensou no Grimgar (Indonesia)', None, None, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 0', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 1', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 10', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 11', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 12', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 13', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 14', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 15', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 16', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 17', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 18', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 19', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 2', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 20', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 21', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 22', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 23', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 3', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 4', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 5', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 6', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 7', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 8', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab 9', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Bab Tambahan', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Kata Penutup', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 1 Lampiran', None, 1.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 1', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 10', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 2', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 3', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 4', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 5', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 6', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 7', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 8', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Bab 9', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia): Jilid 2 Ilustrasi', None, 2.0, None, ''),
	('Hai to Gensou no Grimgar (Indonesia):Halaman Pendaftaran', None, None, None, ''),
	('Haitus', None, None, None, ''),
	('Haitus over – Self reflection and me.', None, None, None, ''),
	('Hajiko please :’D', None, None, None, ''),
	('Hakai Me no Yuuri – Ch 5', None, 5.0, None, ''),
	('Hakai Me no Yuuri – Ch 6', None, 6.0, None, ''),
	('Hakai Me no Yuuri – Ch 7', None, 7.0, None, ''),
	('Hakai Me no Yuuri – Ch 8', None, 8.0, None, ''),
	('Hakai Me no Yuuri – Chapter 1', None, 1.0, None, ''),
	('Haken no Kouki Altina', None, None, None, ''),
	('Haken no Kouki Altina (Indonesia)', None, None, None, ''),
	('Haken no Kouki Altina (Indonesia): Jilid 1 Bab 1', None, 1.0, None, ''),
	('Haken no Kouki Altina (Indonesia): Jilid 1 Bab 2', None, 1.0, None, ''),
	('Haken no Kouki Altina (Indonesia): Jilid 1 Bab 3', None, 1.0, None, ''),
	('Haken no Kouki Altina (Indonesia):Halaman Pendaftaran', None, None, None, ''),
	('Haken no Kouki Altina PL', None, None, None, ''),
	('Haken no Kouki Altina PL: Tom 3 Rozdział 1', None, 3.0, None, ''),
	('Haken no Kouki Altina PT-BR', None, None, None, ''),
	('Haken no Kouki Altina Registration Page pt-br', None, None, None, ''),
	('Haken no Kouki Altina ~Brazilian Portuguese~', None, None, None, ''),
	('Hakomari (Indonesia)', None, None, None, ''),
	('Hakomari (Indonesia):Halaman Pendaftaran', None, None, None, ''),
	('Hakomari (Indonesia):Jilid 2 1 Mei', None, 2.0, None, ''),
	('Hakomari (Indonesia):Jilid 4 Bab 1', None, 4.0, None, ''),
	('Hakomari (Indonesia):Jilid 4 Bab 2', None, 4.0, None, ''),
	('Hakomari (Indonesia):Jilid 4 Bab 3', None, 4.0, None, ''),
	('Hakomari (Indonesia):Jilid 4 Bab 4', None, 4.0, None, ''),
	('Hakomari (Indonesia):Jilid 4 Bab 5', None, 4.0, None, ''),
	('Hakomari (Indonesia):Jilid 5 Bab 1', None, 5.0, None, ''),
	('Hakomari (Indonesia):Jilid 5 Bab 2', None, 5.0, None, ''),
	('Hakomari (Indonesia):Jilid 6 Ilustrasi', None, 6.0, None, ''),
	('Hakomari (Indonesia):Jilid 7 Ilustrasi', None, 7.0, None, ''),
	('Hakomari (Indonesia):Jilid 7 Prolog', None, 7.0, None, ''),
	('Half Kuang Shen Chapter', None, None, None, ''),
	('Half-Dragon Slave Life- Chapter 1', None, 1.0, None, ''),
	('Half-Dragon Slave Life- Chapter 2', None, 2.0, None, ''),
	('Half-Dragon Slave Life- Chapter 3', None, 3.0, None, ''),
	('Half-Dragon Slave Life- Chapter 4', None, 4.0, None, ''),
	('Half-Dragon Slave Life- Chapter 5', None, 5.0, None, ''),
	('Half-Dragon Slave Life- Chapter 6', None, 6.0, None, ''),
	('Half-Dragon Slave Life- Prologue 1', None, 1.0, None, 'Prologue 1'),
	('Half-Dragon Slave Life- Prologue 3', None, 3.0, None, 'Prologue 3'),
	('Halloween', None, None, None, ''),
	('Halloween 2015 Story Writing Contest', None, 2015.0, None, ''),
	('Halloween :3', None, 3.0, None, ''),
	('Halloween story writing contest 2013', None, 2013.0, None, ''),
	('HanTsuki:Volume 2 Chapter 1', 2.0, 1.0, None, ''),
	('HanTsuki:Volume 4 Chapter 1', 4.0, 1.0, None, ''),
	('Hanayome to Futsuma no Kishi (The Bride and the Exorcist Knight) is finally here!', None, None, None, ''),
	("Handyboy's New Customer by realoldbill", None, None, None, ''),
	('Happy 1st Anniversay re:translations~', None, 1.0, None, ''),
	('Happy 2016!', None, 2016.0, None, ''),
	('Happy Anniversary', None, None, None, ''),
	('Happy Anniversay, Stud', None, None, None, ''),
	('Happy April Fools', None, None, None, ''),
	('Happy April Fool’s 2016', None, 2016.0, None, ''),
	('Happy April Fool’s Day!', None, None, None, ''),
	('Happy August, have some updates', None, None, None, ''),
	('Happy Birthday', None, None, None, ''),
	('Happy Birthday RTD!', None, None, None, ''),
	('Happy Birthday to Kidyeon!!', None, None, None, ''),
	('Happy Birthday to Me', None, None, None, ''),
	('Happy Birthday to Yoni + Ninja Chapter', None, None, None, ''),
	('Happy Birthday to myself.', None, None, None, ''),
	('Happy Birthday, Gravitytales!', None, None, None, ''),
	('Happy CNY and TFI chap8', None, 8.0, None, ''),
	('Happy Canada Day~', None, None, None, ''),
	('Happy Easter', None, None, None, ''),
	('Happy Easter~', None, None, None, ''),
	('Happy Eid Fitri', None, None, None, ''),
	('Happy Father’s day!', None, None, None, ''),
	('Happy First Birthday!!!', None, None, None, ''),
	('Happy Friday the 13th!', None, 13.0, None, ''),
	('Happy Hari Raya~ Chapter 4 is out!', None, 4.0, None, ''),
	('Happy Holiday Season!', None, None, None, ''),
	('Happy Holidays', None, None, None, ''),
	('Happy Holidays Release!', None, None, None, ''),
	('Happy Holidays!', None, None, None, ''),
	('Happy Ied', None, None, None, ''),
	('Happy Independence Day Weekend!', None, None, None, ''),
	('Happy Juice', None, None, None, ''),
	('Happy Life picked up!', None, None, None, ''),
	('Happy Lunar New Year 2016!!!', None, 2016.0, None, ''),
	('Happy Lunar New Year!', None, None, None, ''),
	('Happy Monday!', None, None, None, ''),
	('Happy Mother’s Day~  Chapter 74 is Out!', None, 74.0, None, ''),
	('Happy New Year', None, None, None, ''),
	('Happy New Year 2015', None, 2015.0, None, ''),
	('Happy New Year 2015!', None, 2015.0, None, ''),
	('Happy New Year 2016!', None, 2016.0, None, ''),
	('Happy New Year 2016!!', None, 2016.0, None, ''),
	('Happy New Year 2016!!!', None, 2016.0, None, ''),
	('Happy New Year and SOPA/PIPA Protest', None, None, None, ''),
	('Happy New Year!', None, None, None, ''),
	('Happy New Year! Final Announcement', None, None, None, ''),
	('Happy New Year!!!!', None, None, None, ''),
	('Happy New Year, Bitches! Suck on Chapter 23: Spreading the Flames of Justice', None, 23.0, None, ''),
	('Happy New Year. The Last Guild book 2- chapter 10.', 2.0, 10.0, None, ''),
	('Happy New Years! Editing Team~', None, None, None, ''),
	('Happy New Year~', None, None, None, ''),
	('Happy Peach — Chapter 4', None, 4.0, None, ''),
	('Happy Peach — Chapter 5', None, 5.0, None, ''),
	('Happy Peach — Chapter 6', None, 6.0, None, ''),
	("Happy Valentine's Day 2016, Everyone!", None, 2016.0, None, ''),
	('Happy Valentines Day', None, None, None, ''),
	('Happy Valentine’s Day!', None, None, None, ''),
	('Happy Valentine’s Day!!!', None, None, None, ''),
	('Happy Victoria Day!!!!!!!', None, None, None, ''),
	('Happy anniversary Reddycreations', None, None, None, ''),
	('Happy birthday to Yu Wo!', None, None, None, ''),
	('Happy day after New years!', None, None, None, ''),
	('Happy en... NOPE, not happening.', None, None, None, ''),
	('Happy lunar new year!', None, None, None, ''),
	('Happy π Day!', None, None, None, ''),
	('Harassing Thief Girl Ch 7 Booby Trap', None, 7.0, None, ''),
	('Hardcore Info-Dump', None, None, None, ''),
	('Hardcore OP-ness', None, None, None, ''),
	('Hardcore OP-ness Art', None, None, None, ''),
	('Hardcore OP-ness Volume 2: Chaotic Companionship', 2.0, None, None, ''),
	('Harem Castle: Chapter 1 - Farewell, My Distant Days', None, 1.0, None, ''),
	('Harem Castle: Chapter 2 - Devilishness of the Holy Mother', None, 2.0, None, ''),
	('Harem Castle: Chapter 3 - New Life', None, 3.0, None, ''),
	('Harem Castle: Chapter 4 - Rebellion', None, 4.0, None, ''),
	('Harem Castle: Chapter 5 - Forest and Lake', None, 5.0, None, ''),
	('Harem Castle: Chapter 6 - The Great Bath', None, 6.0, None, ''),
	('Harem Pirates: Chapter 1 - The White Lady', None, 1.0, None, ''),
	('Harem Pirates: Chapter 2 - The Red-Haired Pirate', None, 2.0, None, ''),
	('Harem Pirates: Chapter 3 - Rough Life on the Ship', None, 3.0, None, ''),
	('Harem Pirates: Chapter 4 - Defeat', None, 4.0, None, ''),
	('Harem Pirates: Chapter 5 - Pirate Stronghold', None, 5.0, None, ''),
	('Harem Pirates: Chapter 6 - Dreaming of Ruling the South Sea', None, 6.0, None, ''),
	('Harem Sister: Chapter 1 - Holy Bath', None, 1.0, None, ''),
	('Harem Sister: Chapter 2 - Service', None, 2.0, None, ''),
	('Harem Sister: Chapter 3 - Holy Warrior', None, 3.0, None, ''),
	('Harem Sister: Chapter 4 - Sinful Nun', None, 4.0, None, ''),
	('Harem Slave Master Chapter 3', None, 3.0, None, ''),
	('Harem Slave Master Chapter 4', None, 4.0, None, ''),
	('Harem Slave Master Chapter 5', None, 5.0, None, ''),
	('Haris and Orsino', None, None, None, ''),
	('Hariyama-san, Center of the World, volume 1: Afterwords', 1.0, None, None, 'Afterwords'),
	('Hariyama-san, Center of the World, volume 1: Center of the Miracles [1/3]', 1.0, 1.0, None, ''),
	('Hariyama-san, Center of the World, volume 1: Center of the Miracles [2/3]', 1.0, 2.0, None, ''),
	('Hariyama-san, Center of the World, volume 1: Center of the Miracles [3/3]', 1.0, 3.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person', None, None, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 1', None, 1.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 10', None, 10.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 11', None, 11.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 12', None, 12.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 13', None, 13.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 14', None, 14.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 15', None, 15.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 16', None, 16.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 17', None, 17.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 18', None, 18.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 2', None, 2.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 20', None, 20.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 21', None, 21.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 22', None, 22.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 23', None, 23.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 24', None, 24.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 25', None, 25.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 26', None, 26.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 27', None, 27.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 28', None, 28.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 29', None, 29.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 30', None, 30.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 31', None, 31.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 32', None, 32.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 33', None, 33.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 34', None, 34.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 35', None, 35.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 37', None, 37.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 38', None, 38.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 39', None, 39.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 4', None, 4.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 5', None, 5.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 6', None, 6.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 7', None, 7.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 8', None, 8.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person Chapter 9', None, 9.0, None, ''),
	('Harry Potter and the Rise of the Ordinary Person has been updated to the latest chapter!', None, None, None, ''),
	('HaruPARTY Scans is up and running', None, None, None, ''),
	('Has the popularity poll ended? If so, what are the results?', None, None, None, ''),
	('Hataraku Maou-Sama! Actualizaciones', None, None, None, ''),
	('Hataraku Maou-Sama!: Página de registro', None, None, None, ''),
	('Hataraku Maou-sama update', None, None, None, ''),
	('Hatoful Boyfriend on Steam!', None, None, None, ''),
	('Haunted House', None, None, None, ''),
	('Haunting Spectre Road 冤鬼路—Chapter 2: Ghost Girl', None, 2.0, None, ''),
	('Have You Ever Seen The Rain? GDW 289', None, 289.0, None, ''),
	('Have you considered learning Chinese?', None, None, None, ''),
	('Haven’t given up!', None, None, None, ''),
	('He Has Come, Please Close Your Eyes (他来了，请闭眼) by Ding Mo (丁墨) - Review: 4.5 stars (HE) & Chapter Translation', None, 4.5, None, ''),
	("He Is The King Of Gods(for coolbadgirl's The Challenge 2013)", None, 2013.0, None, ''),
	('He wants my blood (PICS!!!)', None, None, None, ''),
	('Head Coach’s Tail', None, None, None, ''),
	('Head to the New Site!', None, None, None, ''),
	('Headache :/', None, None, None, ''),
	('Header…', None, None, None, ''),
	('Heads up', None, None, None, ''),
	('Heads up Part II', None, None, None, ''),
	('Heads up on a teaser', None, None, None, ''),
	('Healing Semen Chapter 0', None, 0.0, None, ''),
	('Healing Semen Chapter 1', None, 1.0, None, ''),
	('Healing Semen Chapter 10', None, 10.0, None, ''),
	('Healing Semen Chapter 11', None, 11.0, None, ''),
	('Healing Semen Chapter 12', None, 12.0, None, ''),
	('Healing Semen Chapter 2', None, 2.0, None, ''),
	('Healing Semen Chapter 3', None, 3.0, None, ''),
	('Healing Semen Chapter 4', None, 4.0, None, ''),
	('Healing Semen Chapter 5', None, 5.0, None, ''),
	('Healing Semen Chapter 6', None, 6.0, None, ''),
	('Healing Semen Chapter 7', None, 7.0, None, ''),
	('Healing Semen Chapter 8', None, 8.0, None, ''),
	('Healing Semen Chapter 9', None, 9.0, None, ''),
	('Health issues causing delays !!', None, None, None, ''),
	('Heart Attack Characters', None, None, None, ''),
	('Heart Break Detective Momose, and この恋と、その未来', None, None, None, ''),
	('Heart Broken Poems (?)', None, None, None, ''),
	('Heat Death of the Universe', None, None, None, ''),
	('Heaven & Hell', None, None, None, ''),
	('Heaven Awakening Path Ch-1,2,3', None, 1.0, None, ''),
	('Heaven Awakening Path Ch-10,11', None, 10.0, None, ''),
	('Heaven Awakening Path Ch-12', None, 12.0, None, ''),
	('Heaven Awakening Path Ch-13', None, 13.0, None, ''),
	('Heaven Awakening Path Ch-14', None, 14.0, None, ''),
	('Heaven Awakening Path Ch-15', None, 15.0, None, ''),
	('Heaven Awakening Path Ch-16', None, 16.0, None, ''),
	('Heaven Awakening Path Ch-17', None, 17.0, None, ''),
	('Heaven Awakening Path Ch-18 And a bit of sad news…', None, 18.0, None, ''),
	('Heaven Awakening Path Ch-19', None, 19.0, None, ''),
	('Heaven Awakening Path Ch-20', None, 20.0, None, ''),
	('Heaven Awakening Path Ch-21', None, 21.0, None, ''),
	('Heaven Awakening Path Ch-22', None, 22.0, None, ''),
	('Heaven Awakening Path Ch-23', None, 23.0, None, ''),
	('Heaven Awakening Path Ch-24', None, 24.0, None, ''),
	('Heaven Awakening Path Ch-25', None, 25.0, None, ''),
	('Heaven Awakening Path Ch-26+27', None, 26.0, None, ''),
	('Heaven Awakening Path Ch-28-30', None, 28.0, None, ''),
	('Heaven Awakening Path Ch-31-33', None, 31.0, None, ''),
	('Heaven Awakening Path Ch-34', None, 34.0, None, ''),
	('Heaven Awakening Path Ch-35', None, 35.0, None, ''),
	('Heaven Awakening Path Ch-36', None, 36.0, None, ''),
	('Heaven Awakening Path Ch-37', None, 37.0, None, ''),
	('Heaven Awakening Path Ch-38', None, 38.0, None, ''),
	('Heaven Awakening Path Ch-39', None, 39.0, None, ''),
	('Heaven Awakening Path Ch-4', None, 4.0, None, ''),
	('Heaven Awakening Path Ch-40', None, 40.0, None, ''),
	('Heaven Awakening Path Ch-41', None, 41.0, None, ''),
	('Heaven Awakening Path Ch-42', None, 42.0, None, ''),
	('Heaven Awakening Path Ch-43', None, 43.0, None, ''),
	('Heaven Awakening Path Ch-44', None, 44.0, None, ''),
	('Heaven Awakening Path Ch-45', None, 45.0, None, ''),
	('Heaven Awakening Path Ch-46', None, 46.0, None, ''),
	('Heaven Awakening Path Ch-47', None, 47.0, None, ''),
	('Heaven Awakening Path Ch-48', None, 48.0, None, ''),
	('Heaven Awakening Path Ch-49', None, 49.0, None, ''),
	('Heaven Awakening Path Ch-5', None, 5.0, None, ''),
	('Heaven Awakening Path Ch-50+51', None, 50.0, None, ''),
	('Heaven Awakening Path Ch-52+53', None, 52.0, None, ''),
	('Heaven Awakening Path Ch-54', None, 54.0, None, ''),
	('Heaven Awakening Path Ch-56', None, 56.0, None, ''),
	('Heaven Awakening Path Ch-57', None, 57.0, None, ''),
	('Heaven Awakening Path Ch-6', None, 6.0, None, ''),
	('Heaven Awakening Path Ch-7', None, 7.0, None, ''),
	('Heaven Awakening Path Ch-8', None, 8.0, None, ''),
	('Heaven Awakening Path Ch-9', None, 9.0, None, ''),
	('Heavenly Calamity Status Update', None, None, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 10', 1.0, 10.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 11', 1.0, 11.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 12', 1.0, 12.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 13', 1.0, 13.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 14', 1.0, 14.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 15', 1.0, 15.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 16', 1.0, 16.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 17', 1.0, 17.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 19', 1.0, 19.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 2', 1.0, 2.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 20', 1.0, 20.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 21', 1.0, 21.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 22', 1.0, 22.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 23', 1.0, 23.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 3', 1.0, 3.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 4', 1.0, 4.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 5', 1.0, 5.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 6', 1.0, 6.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 7', 1.0, 7.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 8', 1.0, 8.0, None, ''),
	('Heavenly Calamity – Volume 1: Chapter 9', 1.0, 9.0, None, ''),
	('Heavenly Jewel Change (HJC) moving away!', None, None, None, ''),
	('Heavenly Star Chapter 2', None, 2.0, None, ''),
	('Heavenly Star – Translated by Est', None, None, None, ''),
	('Heavenly Tribulation – Volume 1 Chapter 1', 1.0, 1.0, None, ''),
	('Heavenly Tribulation – Volume 1 Chapter 2', 1.0, 2.0, None, ''),
	('Heavenly Tribulation – Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('Heavenly Tribulation – Volume 1 Chapter 4', 1.0, 4.0, None, ''),
	('Heavenly Tribulation – Volume 1 Chapter 5', 1.0, 5.0, None, ''),
	('Heavenly evil – lets talk about the love of angels and demons Chapter 1', None, 1.0, None, ''),
	('Heavenward on Golden Wings', None, None, None, ''),
	('Heavll\nChapter 1: Town 1\nPart 2: RL&Heavll', None, 1.0, None, ''),
	('Heavll Chapter 0: Guideline Part 1: Info', None, 0.0, 1.0, ''),
	('Heavll Chapter 0: Guideline Part 2: Job, Make, Understand', None, 0.0, 2.0, ''),
	('Heavll Chapter 1: Town 1 Part 1: AKA Nickname Town, Hunt, Equipment', None, 1.0, 1.0, ''),
	('Heavy Object (Indonesia)', None, None, None, ''),
	('Heavy Object ED', None, None, None, ''),
	('Heavy Object ~ (Spanish)', None, None, None, ''),
	('Heavy Object:Volumen 5 Capítulo 2', None, 5.0, None, ''),
	('Heavy Object:Volumen 5 Capítulo 3', None, 5.0, None, ''),
	('Heavy Sweetness Ash-Like Frost : Translation (Epilogue 1: When Jin Mi was a Book Boy (Part 1))', None, 1.0, 1.0, '(Epilogue 1: When Jin Mi was a Book Boy (Part 1))'),
	('Heavy Sweetness Ash-Like Frost : Translation (Epilogue 2: Dragon Boat Festival/ When Jin Mi was a Book Boy (Part 2))', None, 2.0, 2.0, '(Epilogue 2: Dragon Boat Festival/ When Jin Mi was a Book Boy (Part 2))'),
	('Heavy Sweetness Ash-Like Frost : Translation (Epilogue 3: Testing Pills)', None, 3.0, None, '(Epilogue 3: Testing Pills)'),
	('Heavy Sweetness Ash-Like Frost : Translation (Epilogue 4: Tang Yue)', None, 4.0, None, '(Epilogue 4: Tang Yue)'),
	('Heavy Sweetness Ash-Like Frost: Translation (Chapter 22.4: Love and Hate Changes in an Instant)', None, 22.4, None, ''),
	('Heavy Sweetness Ash-Like Frost: Translation (Chapter 23.1: No Door For Redemption)', None, 23.1, None, ''),
	('Heavy Sweetness Ash-Like Frost: Translation (Chapter 23.2: No Door For Redemption)', None, 23.2, None, ''),
	('Heavy Sweetness Ash-Like Frost: Translation (Chapter 23.3: No Door For Redemption)', None, 23.3, None, ''),
	('Heavy Sweetness Ash-Like Frost: Translation (Chapter 23.4: No Door For Redemption & Chapter 24.1: Tears of the Deep Blue Sea)', None, 23.4, None, ''),
	('Heavy Sweetness Ash-Like Frost: Translation (Chapter 24.2: The Tears of the Deep Blue Sea & Final Chapter) *COMPLETED*', None, 24.2, None, ''),
	('Heeey guiss', None, None, None, ''),
	('Heibon ch 8', None, 8.0, None, ''),
	('Heibon – 1', None, 1, None, ''),
	('Heibon – 2', None, 2, None, ''),
	('Hell Week', None, None, None, ''),
	('Hello', None, None, None, ''),
	('Hello Everybody', None, None, None, ''),
	('Hello From God of Thunder and New Chapter!', None, None, None, ''),
	('Hello Monster', None, None, None, ''),
	('Hello Readers!', None, None, None, ''),
	('Hello To All My Readers', None, None, None, ''),
	('Hello Work Chapter 26', None, 26.0, None, ''),
	('Hello Work Chapter 27', None, 27.0, None, ''),
	('Hello Work Volume 2 Chapter 11-13', 2, 11, 13, ''),
	('Hello Work Volume 2 Chapter 8', 2.0, 8.0, None, ''),
	('Hello Work Volume 2 Chapter 9-10', 2, 9, 10, ''),
	('Hello Work – V2Ch10', 2.0, 10.0, None, ''),
	('Hello Work – V2Ch11', 2.0, 11.0, None, ''),
	('Hello Work – V2Ch12', 2.0, 12.0, None, ''),
	('Hello Work – V2Ch13', 2.0, 13.0, None, ''),
	('Hello Work – V2Ch14', 2.0, 14.0, None, ''),
	('Hello Work – V2Ch15', 2.0, 15.0, None, ''),
	('Hello Work – V2Ch16', 2.0, 16.0, None, ''),
	('Hello Work – V2Ch17', 2.0, 17.0, None, ''),
	('Hello Work – V2Ch3', 2.0, 3.0, None, ''),
	('Hello Work – V2Ch4', 2.0, 4.0, None, ''),
	('Hello Work – V2Ch5', 2.0, 5.0, None, ''),
	('Hello Work – V2Ch6', 2.0, 6.0, None, ''),
	('Hello Work – V2Ch7', 2.0, 7.0, None, ''),
	('Hello Work – V2Ch8', 2.0, 8.0, None, ''),
	('Hello Work – V2Ch9', 2.0, 9.0, None, ''),
	('Hello Work – Volume 2 Chapter 2', 2.0, 2.0, None, ''),
	('Hello World', None, None, None, ''),
	('Hello World! Ensj here, bringing you “An Incomplete Life.”', None, None, None, ''),
	('Hello World! and “Death March” 1-Prologue', None, 1, None, '1-Prologue'),
	('Hello World.', None, None, None, ''),
	('Hello Wuxiaworld!', None, None, None, ''),
	('Hello again!', None, None, None, ''),
	('Hello and sorry', None, None, None, ''),
	('Hello everyone, just wanted to share something neat i found on youtube', None, None, None, ''),
	('Hello there and chapter 1 of Unlimited Anime Works', None, 1.0, None, ''),
	('Hello there everyone!', None, None, None, ''),
	('Hello world!', None, None, None, ''),
	('Hello world! is the default greeting so I’m sticking with it!', None, None, None, ''),
	('Hello world?', None, None, None, ''),
	('Hello!', None, None, None, ''),
	('Hello!!!', None, None, None, ''),
	('Hello, everyone~', None, None, None, ''),
	('Hello, it’s nice to see you all again :D (これからもよろしく)', None, None, None, ''),
	('Help', None, None, None, ''),
	('Help me and my friends out a bit', None, None, None, ''),
	('Help me out!', None, None, None, ''),
	('Help me! Life Struggles', None, None, None, ''),
	('Help talk:Administration Contact Page', None, None, None, ''),
	('Help us!', None, None, None, ''),
	('Help:Wiki Basics', None, None, None, ''),
	('Helping out Rumanshi!', None, None, None, ''),
	('Helping the Homeless: Happy Feet', None, None, None, ''),
	('Henneko Translation Un-release Complete!', None, None, None, ''),
	('Her First Women', None, None, None, ''),
	('Her Life Saver', None, None, None, ''),
	('Here comes the 3 days mania!', None, 3.0, None, ''),
	('Here go GM prologue', None, None, None, 'prologue'),
	('Here in the dark', None, None, None, ''),
	('Here is Chapter 18', None, 18.0, None, ''),
	('Here the 1st regular chapter of the week and a little bit of an announcement', None, 1.0, None, ''),
	('Here we go before these expire…', None, None, None, ''),
	("Here's Chapter 9", None, 9.0, None, ''),
	("Here's a new pic for Shinka no Mi", None, None, None, ''),
	("Here's chapter 105", None, 105.0, None, ''),
	("Here's some more", None, None, None, ''),
	('Here’s a magic trick', None, None, None, ''),
	('Here’s an early regular for GDN oh ho ho', None, None, None, ''),
	('Here’s the GDN boner chap and GE regular', None, None, None, ''),
	('Here’s the chapter!', None, None, None, ''),
	('Here’s the extra chapter!', None, None, None, 'extra chapter!'),
	('Here’s the first chapter of the the new series', None, None, None, ''),
	('Hero Chapter 1', None, 1.0, None, ''),
	('Hero Chapter 10', None, 10.0, None, ''),
	('Hero Chapter 11', None, 11.0, None, ''),
	('Hero Chapter 12', None, 12.0, None, ''),
	('Hero Chapter 13', None, 13.0, None, ''),
	('Hero Chapter 14', None, 14.0, None, ''),
	('Hero Chapter 15', None, 15.0, None, ''),
	('Hero Chapter 16', None, 16.0, None, ''),
	('Hero Chapter 17', None, 17.0, None, ''),
	('Hero Chapter 2', None, 2.0, None, ''),
	('Hero Chapter 3', None, 3.0, None, ''),
	('Hero Chapter 4', None, 4.0, None, ''),
	('Hero Chapter 5', None, 5.0, None, ''),
	('Hero Chapter 6', None, 6.0, None, ''),
	('Hero Chapter 7', None, 7.0, None, ''),
	('Hero Chapter 8', None, 8.0, None, ''),
	('Hero Chapter 9', None, 9.0, None, ''),
	('Hero Pandemic chapter 1 and 2 &Monster Musume Update', None, 1.0, None, ''),
	('Hero Pandemic chapter 3', None, 3.0, None, ''),
	('Heroes Shed No Tears 2/2 PLUS Dragon King', None, 2, None, ''),
	('Heroes Shed No Tears – Part 1/2', None, None, 1, ''),
	('Heroine Imouto – 001', None, 1.0, None, ''),
	('Heroine Imouto – 002', None, 2.0, None, ''),
	('Hey Hey Hey - ATG - Chapter 176', None, 176.0, None, ''),
	('Hey Y’all!', None, None, None, ''),
	('Hey do you have the raws for plus alpha no tachiitachi?? Or do you know where i coul get it?? Cause this manga is so interesting but i cant wait to know what will happen and even though i cant read japanesse atleast i can see the pictures :( <---- very desprate. THANK YOUUU SO MUCHHH <3', None, 3.0, None, ''),
	('Hey guy its Digital with a status update!', None, None, None, ''),
	('Hey guys', None, None, None, ''),
	('Hey guys, It’s a poll regarding Son Goku', None, None, None, ''),
	('Hey loyal reads I have a question?', None, None, None, ''),
	('Hey!', None, None, None, ''),
	('Hey, Just Another Sunday :)', None, None, None, ''),
	('Hey.', None, None, None, ''),
	('Heya guys', None, None, None, ''),
	('He’s gonna be fine ^.^', None, None, None, ''),
	('Hi', None, None, None, ''),
	('Hi Binh/Announcement', None, None, None, ''),
	('Hi Hi~', None, None, None, ''),
	('Hi ^^', None, None, None, ''),
	('Hi guys!', None, None, None, ''),
	('Hi guys….', None, None, None, ''),
	('Hi it’s snow', None, None, None, ''),
	('Hi there!', None, None, None, ''),
	('Hi ‘-‘', None, None, None, ''),
	('Hi!', None, None, None, ''),
	('Hi! Alice here.', None, None, None, ''),
	('Hi! Alice here~', None, None, None, ''),
	("Hi! Um, what do you think happened to black demon that they're trapped inside the cursed weapons? It's not like Mahiru had forced Ashuramaru and bound him down, right? She was just a child when her demon appeared, right? So they came naturally, just like that? Or it's because of the experiment placed upon them (Mahiru, and maybe Shinoa at some point)? I would be happy if you could answer my question :) Thank you very much!", None, None, None, ''),
	('Hi, and Thank You', None, None, None, ''),
	('Hi, everyone~', None, None, None, ''),
	('Hi. I’m new to this, I just wanted to translate and share.', None, None, None, ''),
	('Hia', None, None, None, ''),
	('Hiatus', None, None, None, ''),
	('Hiatus :(', None, None, None, ''),
	('Hiatus End', None, None, None, ''),
	('Hiatus Notice', None, None, None, ''),
	('Hiatus Over', None, None, None, ''),
	('Hiatus Until Exam Ends', None, None, None, ''),
	('Hiatus announcement', None, None, None, ''),
	('Hiatus for Chapter 8', None, 8.0, None, ''),
	('Hiatus for GoT', None, None, None, ''),
	('Hiatus for some members of the team~', None, None, None, ''),
	('Hiatus notice', None, None, None, ''),
	('Hiatus until the 21st', None, 21.0, None, ''),
	('Hiatus — Monkoto’s Translations', None, None, None, ''),
	('Hiatus!', None, None, None, ''),
	('Hibernation', None, None, None, ''),
	('Hidan no Aria', None, None, None, ''),
	('Hidan no Aria Light Novel EPUB and PDF Download', None, None, None, ''),
	('Hidari Kiki Dattakara Isekai ni Tsurete Ikareta', None, None, None, ''),
	('Hidden GM: Extra Chapter Survey', None, None, None, 'Extra Chapter Survey'),
	('Hidden GMs Destiny Bonus Chapter: B-Side ⧫ Chicken Talk', None, None, None, ''),
	('Hidden GMs Destiny chapter 6 part 1', None, 6.0, 1.0, ''),
	('Hidden GMs Destiny chapter 6 part 2', None, 6.0, 2.0, ''),
	('Hidden GMs Destiny chapter 6 part 3', None, 6.0, 3.0, ''),
	('Hidden GMs Destiny chapter 6 part 4+Donations', None, 6.0, 4.0, ''),
	('Hidden GMs Destiny chapter 7 part 1', None, 7.0, 1.0, ''),
	('Hidden GMs Destiny chapter 7 part 2', None, 7.0, 2.0, ''),
	('Hidden GMs Destiny chapter 7 part 3', None, 7.0, 3.0, ''),
	('Hidden GMs Destiny chapter 8 part 1', None, 8.0, 1.0, ''),
	('Hidden GMs Destiny chapter 8 part 2', None, 8.0, 2.0, ''),
	('Hidden GMs Destiny chapter 8 part 3', None, 8.0, 3.0, ''),
	('Hidden GMs Destiny chapter 9 part 1', None, 9.0, 1.0, ''),
	('Hidden Lives by blackrandl1958', None, 1958.0, None, ''),
	('Higawari Teni Chapter 1 Release', None, 1.0, None, ''),
	('Higawari Teni Chapter 2 Release', None, 2.0, None, ''),
	('Higawari Teni Chapter 3 Release', None, 3.0, None, ''),
	('Higawari Teni Chapter 4 Release', None, 4.0, None, ''),
	('Higawari Teni Chapter 5 Release', None, 5.0, None, ''),
	('Higawari Teni Chapter 6 Release', None, 6.0, None, ''),
	('Higawari Teni Chapter 7 Release', None, 7.0, None, ''),
	('High Comprehension Low Strength – Chapter 1', None, 1.0, None, ''),
	('High Comprehension Low Strength – Chapter 2', None, 2.0, None, ''),
	('High Comprehension Low Strength – Chapter 3', None, 3.0, None, ''),
	('High Comprehension Low Strength – Chapter 4', None, 4.0, None, ''),
	('High Profile Delhi Escorts Service - Models or Housewife ?', None, None, None, ''),
	('High School DxD', None, None, None, ''),
	('High School DxD (Bahasa Indonesia):Dragon Magazine 2013-01', None, 2013.0, None, ''),
	('High School DxD (Bahasa Indonesia):EX Bab 1', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):EX Bab 2', None, 2.0, None, ''),
	('High School DxD (Bahasa Indonesia):EX Bab 3', None, 3.0, None, ''),
	('High School DxD (Bahasa Indonesia):EX Ilustrasi', None, None, None, ''),
	('High School DxD (Bahasa Indonesia):Harta Asia', None, None, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Last Life Keadilan Puitis', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Life.0', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Life.1 Kegelisahan Konsultasi Karir', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Life.2 Kebenaran Kompetisi', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Life.3 Hyodou Issei', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Makhluk 666', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Orang Tua', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Pemalsu', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Pencegahan', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Penutup', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid 20 Sangat Marah', None, 20.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Extra Life', None, 1.0, None, 'Extra Life'),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Ilustrasi', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Life 1', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Life 2', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Life 3', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Life 4', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Life 5', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX1 Penutup', None, 1.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX2 Ilustrasi', None, 2.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX2 Life.1', None, 2.0, None, ''),
	('High School DxD (Bahasa Indonesia):Jilid DX2 Life.2', None, 2.0, None, ''),
	('High School DxD (Bahasa Indonesia):Registration Page', None, None, None, ''),
	('High School DxD (Bahasa Indonesia):Rias di Negeri Ajaib', None, None, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 17 Ilustrasi', 17.0, None, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 18 Ilustrasi', 18.0, None, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 19 Ilustrasi', 19.0, None, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 19 Life.0', 19.0, 0.0, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 19 Rudra', 19.0, None, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 20 Ilustrasi', 20.0, None, None, ''),
	('High School DxD (Bahasa Indonesia):Volume 21 Ilustrasi', 21.0, None, None, ''),
	('High School DxD (Deutsch)', None, None, None, ''),
	('High School DxD (Indonesia)', None, None, None, ''),
	('High School DxD (Polski)', None, None, None, ''),
	('High School DxD (Polski):Tom DX1', None, 1.0, None, ''),
	('High School DxD (Polski):Tom DX2 Żywot 1', None, 2.0, None, ''),
	('High School DxD (Polski):Tom EX Rozdział 1', None, 1.0, None, ''),
	('High School DxD (Polski):Tom EX Rozdział 2', None, 2.0, None, ''),
	('High School DxD (Polski):Tom EX Rozdział 3', None, 3.0, None, ''),
	('High School DxD (Polski):Tom EX Rozdział 4', None, 4.0, None, ''),
	('High School DxD (Polski):Tom EX Rozdział 5', None, 5.0, None, ''),
	('High School DxD (Polski):Tom EX Rozdział 6', None, 6.0, None, ''),
	('High School DxD (Turkish)', None, None, None, ''),
	('High School DxD - Français', None, None, None, ''),
	('High School DxD PL: Rias w Krainie Czarów', None, None, None, ''),
	('High School DxD Volume 14 Illustrationen', 14.0, None, None, ''),
	('High School DxD Volume 21', 21.0, None, None, ''),
	('High School DxD ~Brazilian Portuguese~', None, None, None, ''),
	('High School DxD: Deutsch Dragon Magazine 2013-0!', None, 2013.0, None, ''),
	('High School DxD: Deutsch Volume 2 Der letzte Kuss', 2.0, None, None, ''),
	('High School DxD: Deutsch Volume 2 Endspiel', 2.0, None, None, ''),
	('High School DxD: Deutsch Volume 2 Leben 0', 2.0, 0.0, None, ''),
	('High School DxD: Deutsch Volume 2 Leben 1', 2.0, 1.0, None, ''),
	('High School DxD: Deutsch Volume 2 Leben 2', 2.0, 2.0, None, ''),
	('High School DxD: Deutsch Volume 2 Leben 3', 2.0, 3.0, None, ''),
	('High School DxD: Deutsch Volume 2 Leben 4', 2.0, 4.0, None, ''),
	('High School DxD: Deutsch Volume 2 Leben 5', 2.0, 5.0, None, ''),
	('High School DxD: Deutsch Volume 2 Nachwort', 2.0, None, None, ''),
	('High School DxD: Deutsch Volume 2 Neues Leben', 2.0, None, None, ''),
	('High School DxD: Deutsch Volume 2 Schachmatt!', 2.0, None, None, ''),
	('High School DxD: Deutsch Volume 2 Vater trifft auf Vater', 2.0, None, None, ''),
	('High School DxD: Deutsch Volume 3 Neuer Ritter, neuer Rivale', 3.0, None, None, ''),
	('High School DxD: Deutsch Volume 8 Leben 3', 8.0, 3.0, None, ''),
	('High School DxD: Deutsch Volume 8 Leben 6', 8.0, 6.0, None, ''),
	('High School DxD: Deutsch Volume 9 Leben 0', 9.0, 0.0, None, ''),
	('High School DxD: Deutsch Volume 9 Leben 1', 9.0, 1.0, None, ''),
	('High School DxD: Deutsche Updates', None, None, None, ''),
	('High School DxD: Registrierungsseite', None, None, None, ''),
	('High School DxD: Volume 13 Illustrationen', 13.0, None, None, ''),
	('High School DxD:Registration Page', None, None, None, ''),
	('High School DxD:Tome 1 Life 2', None, 1.0, None, ''),
	('High School DxD:Volume 1 Vida 1', 1.0, 1.0, None, ''),
	('High School DxD:Volume 15 Illustrationen', 15.0, None, None, ''),
	('High School DxD:Volume 16 Illustrationen', 16.0, None, None, ''),
	('High School DxD:Volume 17 Illustrationen', 17.0, None, None, ''),
	('High School DxD:Volume 18 Illustrationen', 18.0, None, None, ''),
	('High School DxD:Volume 20 Ilustrasi', 20.0, None, None, ''),
	('High School DxD:Volume 6 Life 2', 6.0, 2.0, None, ''),
	('High School DxD:Volume 6 Life 3', 6.0, 3.0, None, ''),
	('High School DxD:Volume DX1 Afterword', None, 1.0, None, 'Afterword'),
	('High School DxD:Volume DX1 Ilustrasi', None, 1.0, None, ''),
	('High School DxD:Volume DX1 Life 1', None, 1.0, None, ''),
	('High School DxD:Volume DX2 Ilustracje', None, 2.0, None, ''),
	('High School DxD:Volume DX2 Life.1', None, 2.0, None, ''),
	('High School DxD:Volume DX2 Life.2', None, 2.0, None, ''),
	('High School DxD:Volume DX2 Life.3', None, 2.0, None, ''),
	('High School DxD:Volume DX2 Life.4', None, 2.0, None, ''),
	('High School DxD:Volume DX2 Life.5', None, 2.0, None, ''),
	('High Speed! 2: Afterword', None, 2.0, None, 'Afterword'),
	('High Speed! 2: Chapter 10 – Feel', None, 10.0, None, ''),
	('High Speed! 2: Chapter 11 – Believe', None, 11.0, None, ''),
	('High Speed! 2: Chapter 12 – Accelerate', None, 12.0, None, ''),
	('High Speed! 2: Chapter 13 – Hope', None, 13.0, None, ''),
	('High Speed! 2: Chapter 6 – Splash', None, 6.0, None, ''),
	('High Speed! 2: Chapter 7 – Limit', None, 7.0, None, ''),
	('High Speed! 2: Chapter 8 – Light', None, 8.0, None, ''),
	('High Speed! 2: Chapter 9 – Road', None, 9.0, None, ''),
	('High school DxD Tom 21 Determinacja', None, 21.0, None, ''),
	('High school DxD Tom 21 Żywot 2: Drużyna DxD Atakuje!', None, 21.0, None, ''),
	('High school DxD Tom 21 Żywot: Jutrzenka Porannej Gwiazdy Lucyfera ~Pojedynek', None, 21.0, None, ''),
	('Himegami no Miko (姫神の巫女) Part I, Chapter 10', None, 10.0, None, ''),
	('Himegami no Miko (姫神の巫女) Part I, Chapter 7', None, 7.0, None, ''),
	('Himegami no Miko (姫神の巫女) Part I, Chapter 8', None, 8.0, None, ''),
	('Himegami no Miko (姫神の巫女) Part I, Chapter 9', None, 9.0, None, ''),
	('Himegami no Miko (姫神の巫女): Character Biographies and Terms', None, None, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 10', 1.0, 10.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 11', 1.0, 11.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 12', 1.0, 12.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 13', 1.0, 13.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 14', 1.0, 14.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 15', 1.0, 15.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 16', 1.0, 16.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 17', 1.0, 17.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 18', 1.0, 18.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 19', 1.0, 19.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 20', 1.0, 20.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 21', 1.0, 21.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 4', 1.0, 4.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 5', 1.0, 5.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 6', 1.0, 6.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 7', 1.0, 7.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 8', 1.0, 8.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Chapter 9', 1.0, 9.0, None, ''),
	('Himekishi Ga Classmate! Volume 1 Extra Scene', 1.0, None, None, 'Extra Scene'),
	('Himekishi Ga Classmate! Volume 2 Chapter 22', 2.0, 22.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 23', 2.0, 23.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 24', 2.0, 24.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 25', 2.0, 25.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 26', 2.0, 26.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 27', 2.0, 27.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 28', 2.0, 28.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 29', 2.0, 29.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 30', 2.0, 30.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 31', 2.0, 31.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 32', 2.0, 32.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 33', 2.0, 33.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 34', 2.0, 34.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Chapter 35', 2.0, 35.0, None, ''),
	('Himekishi Ga Classmate! Volume 2 Extra Scene Part 1', 2.0, None, 1.0, 'Extra Scene Part 1'),
	('Himekishi Ga Classmate! Volume 2 Extra Scene Part 2', 2.0, None, 2.0, 'Extra Scene Part 2'),
	('Himekishi ch4 NSFW', None, 4.0, None, ''),
	('Himekishi ga Classmate vol 1 ch 2', 1.0, 2.0, None, ''),
	('Himekishi ga Classmate vol 1 ch 3', 1.0, 3.0, None, ''),
	('Himekishi poll 1', None, 1.0, None, ''),
	('Himekishi to Camping Car - Arc 1 Chapter 3', 1.0, 3.0, None, ''),
	('Himekishi to Camping Car ?', None, None, None, ''),
	('Himekishi to Camping Car Chapter 1 - Teaser', None, 1.0, None, ''),
	('Himekishi to Camping car Chapter 2', None, 2.0, None, ''),
	('Himouto Umaru-chan’S – Adverstiment', None, None, None, ''),
	('Himouto! Umaru-chan’S 01 – Net Call', None, 1.0, None, ''),
	('Himouto! Umaru-chan’S 02 – Idols', None, 2.0, None, ''),
	('Himouto! Umaru-chan’S 03 – Short titles', None, 3.0, None, ''),
	('Himouto! Umaru-chan’S 04 – Game', None, 4.0, None, ''),
	('Himouto! Umaruchan’S 05 – Game②', None, 5.0, None, ''),
	('Hint for our next project opening.', None, None, None, ''),
	('Hint on that ??? page :D', None, None, None, ''),
	('Hira hira hirara, Doll Chapter', None, None, None, ''),
	('His', None, None, None, ''),
	('His Little Obsession- Character Pics', None, None, None, ''),
	('His Virgin Love Slave', None, None, None, ''),
	('Hiscore', None, None, None, ''),
	('Hisshou Dungeon Unei Houhou Prologue Part 1', None, None, 1, 'Prologue Part 1'),
	('Hisshou Dungeon Unei Houhou Prologue Part 2', None, None, 2, 'Prologue Part 2'),
	('History of Archia', None, None, None, ''),
	('History of DWGMSFF', None, None, None, ''),
	('History of cars', None, None, None, ''),
	('History’s Strongest Senior Brother Chapter 1', None, 1.0, None, ''),
	('History’s Strongest Senior Brother Chapter 10', None, 10.0, None, ''),
	('History’s Strongest Senior Brother Chapter 11', None, 11.0, None, ''),
	('History’s Strongest Senior Brother Chapter 2', None, 2.0, None, ''),
	('History’s Strongest Senior Brother Chapter 3', None, 3.0, None, ''),
	('History’s Strongest Senior Brother Chapter 4', None, 4.0, None, ''),
	('History’s Strongest Senior Brother Chapter 5', None, 5.0, None, ''),
	('History’s Strongest Senior Brother Chapter 6', None, 6.0, None, ''),
	('History’s Strongest Senior Brother Chapter 7', None, 7.0, None, ''),
	('History’s Strongest Senior Brother Chapters 8-9', None, 8, 9, ''),
	('Hit a roadblock', None, None, None, ''),
	('Hit the reset button', None, None, None, ''),
	('Hitomishiri Onna 9-11', None, 9.0, None, ''),
	('Hitsugi no Chaika', None, None, None, ''),
	('Hiya! (lot of English errors, too tired to bother right now)', None, None, None, ''),
	('Hi~ Forum is up beta version', None, None, None, ''),
	('Hi…', None, None, None, ''),
	('Hmm. I don’t appreciate the changes made in Vermillion’s LN version vol 2', 2.0, None, None, ''),
	('Hmmmm… Yes, no title today.', None, None, None, ''),
	('Hmmm….', None, None, None, ''),
	('Hm… thoughts?', None, None, None, ''),
	('HoGW Chapter 17: … Of Guile and Force', None, 17.0, None, ''),
	('HoGW Chapter 18: Setting Out', None, 18.0, None, ''),
	('HoGW Chapter 19: Hunting with Grandma', None, 19.0, None, ''),
	('HoGW Chapter 20: Hunting with Grandma II', None, 20.0, None, ''),
	('HoGW Chapter 21: Innocence Lost', None, 21.0, None, ''),
	('HoGW Chapter 22', None, 22.0, None, ''),
	('HoGW Chapter Eight', None, 8, None, ''),
	('HoGW Chapter Eleven', None, 11, None, ''),
	('HoGW Chapter Fifteen', None, 15, None, ''),
	('HoGW Chapter Five', None, 5, None, ''),
	('HoGW Chapter Four', None, 4, None, ''),
	('HoGW Chapter Fourteen', None, 14, None, ''),
	('HoGW Chapter Nine', None, 9, None, ''),
	('HoGW Chapter One', None, 1, None, ''),
	('HoGW Chapter Seven', None, 7, None, ''),
	('HoGW Chapter Six', None, 6, None, ''),
	('HoGW Chapter Sixteen', None, 16, None, ''),
	('HoGW Chapter Ten', None, 10, None, ''),
	('HoGW Chapter Thirteen', None, 13, None, ''),
	('HoGW Chapter Three', None, 3, None, ''),
	('HoGW Chapter Twelve', None, 12, None, ''),
	('HoGW Chapter Two', None, 2, None, ''),
	('Hohohohoho', None, None, None, ''),
	('Hokuou Kizoku to Moukinzuma no Karigurashi', None, None, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 02', None, 2.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 03', None, 3.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 04', None, 4.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 05', None, 5.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 07', None, 7.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 08', None, 8.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 09', None, 9.0, None, ''),
	('Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi: Chapter 6', None, 6.0, None, ''),
	('Hola~', None, None, None, ''),
	('Hold it!', None, None, None, ''),
	('Holiday Announcement Pt.1', None, None, 1.0, ''),
	('Holiday Announcements Pt. 2', None, None, 2.0, ''),
	('Holiday Break', None, None, None, ''),
	('Holy Anri Nation', None, None, None, ''),
	('Homage to the first honorary Bathrobe Knight- Zectas volume 3', 3.0, None, None, ''),
	('Home Sweet Home', None, None, None, ''),
	('Homecoming – Breadcrumbs', None, None, None, ''),
	('Homecoming – Calcified', None, None, None, ''),
	('Homecoming – Diffusion I', None, None, None, ''),
	('Homecoming – Diffusion II', None, None, None, ''),
	('Homecoming – Fallout', None, None, None, ''),
	('Homecoming – Hand of God', None, None, None, ''),
	('Homecoming – Hunter', None, None, None, ''),
	('Homecoming – Needle in a Haystack', None, None, None, ''),
	('Homecoming – Truth', None, None, None, ''),
	('Homeschooled', None, None, None, ''),
	('Hone no aru Yatsu – Chapter 1', None, 1.0, None, ''),
	('Hone no aru Yatsu – Chapter 2', None, 2.0, None, ''),
	('Hone no aru Yatsu – Chapter 3', None, 3.0, None, ''),
	('Hone no aru Yatsu – Chapter 4', None, 4.0, None, ''),
	('Hone no aru Yatsu – Chapter 5', None, 5.0, None, ''),
	('Hone no aru Yatsu – Chapter 6', None, 6.0, None, ''),
	('Hone no aru Yatsu – Chapter 7', None, 7.0, None, ''),
	('Hone no aru Yatsu – Chapter 8', None, 8.0, None, ''),
	('Hone no aru Yatsu – Chapter 9', None, 9.0, None, ''),
	('Honey', None, None, None, ''),
	('Honey Let’s Go Glossaries', None, None, None, ''),
	('Honey Stewed Squid by Mo Bao Fei Bao', None, None, None, ''),
	('Honey Stewed Squid ~ Chapter 2', None, 2.0, None, ''),
	('Honey Stewed Squid ~ Chapter 3', None, 3.0, None, ''),
	('Honey Stewed Squid ~ Chapter 4', None, 4.0, None, ''),
	('Honey Stewed Squid ~ Chapter 5', None, 5.0, None, ''),
	('Honey Stewed Squid ~ Chapter 6', None, 6.0, None, ''),
	('Honey Stewed Squid ~ Chapter 7', None, 7.0, None, ''),
	('Honey Stewed Squid ~ Chapter 8', None, 8.0, None, ''),
	('Honey Stewed Squid ~ Chapter 9', None, 9.0, None, ''),
	('Honey, Let’s Go – Chapter 2', None, 2.0, None, ''),
	('Honeymooners', None, None, None, ''),
	('Hooked', None, None, None, ''),
	('Hookers Are Just My Type', None, None, None, ''),
	('Hope you all had a great weekend!', None, None, None, ''),
	('Horizon:Kimitoasamade 2A Chapter 10', None, 10.0, None, ''),
	('Horizon:Kimitoasamade 2A Chapter 11', None, 11.0, None, ''),
	('Horizon:Kimitoasamade 2A Chapter 12', None, 12.0, None, ''),
	('Horizon:Kimitoasamade 2A Chapter 13', None, 13.0, None, ''),
	('Horizon:Volume 4B', 4.0, None, None, ''),
	('Horizon:Volume 4B Afterword', 4.0, None, None, 'Afterword'),
	('Horizon:Volume 4B Chapter 48', 4.0, 48.0, None, ''),
	('Horizon:Volume 4B Chapter 49', 4.0, 49.0, None, ''),
	('Horizon:Volume 4B Chapter 50', 4.0, 50.0, None, ''),
	('Horizon:Volume 4B Chapter 51', 4.0, 51.0, None, ''),
	('Horizon:Volume 4B Chapter 52', 4.0, 52.0, None, ''),
	('Horizon:Volume 4B Chapter 53', 4.0, 53.0, None, ''),
	('Horizon:Volume 4B Chapter 55', 4.0, 55.0, None, ''),
	('Horizon:Volume 4B Chapter 56', 4.0, 56.0, None, ''),
	('Horizon:Volume 4B Chapter 57', 4.0, 57.0, None, ''),
	('Horizon:Volume 4B Chapter 58', 4.0, 58.0, None, ''),
	('Horizon:Volume 4B Chapter 59', 4.0, 59.0, None, ''),
	('Horizon:Volume 4B Chapter 60', 4.0, 60.0, None, ''),
	('Horizon:Volume 4B Chapter 61', 4.0, 61.0, None, ''),
	('Horizon:Volume 4B Table of Contents', 4.0, None, None, ''),
	('Horizon:Volume 4C Chapter 62', 4.0, 62.0, None, ''),
	('Horizon:Volume 4C Chapter 63', 4.0, 63.0, None, ''),
	('Horizon:Volume 4C Chapter 65', 4.0, 65.0, None, ''),
	('Horizon:Volume 4C Chapter 66', 4.0, 66.0, None, ''),
	('Horizon:Volume 4C Character Introduction', 4.0, None, None, ''),
	('Horizon:Volume 4C Glossary', 4.0, None, None, ''),
	('Horizon:Volume 4C Preface', 4.0, None, None, ''),
	('Horizon:Volume 4C School Rules', 4.0, None, None, ''),
	('Horizon:Volume 4C World', 4.0, None, None, ''),
	('Horror Story time', None, None, None, ''),
	('Horror announcement', None, None, None, ''),
	('Hospital', None, None, None, ''),
	('Hostel Main Ragging', None, None, None, ''),
	('Hourou Yuusha wa Kinka to Odoru – Teaser', None, None, None, ''),
	('House of Pleasure', None, None, None, ''),
	('How Do You Stay - In this Madness?', None, None, None, ''),
	('How I Lost Him...', None, None, None, ''),
	('How I Translate', None, None, None, ''),
	('How I will handle GAKUSEN', None, None, None, ''),
	('How Many Chapters Per Day?', None, None, None, ''),
	('How Sex Starts...', None, None, None, ''),
	('How about picking up a new project? :)', None, None, None, ''),
	('How desperate are you?', None, None, None, ''),
	('How joyful can it be, to find one manga better han the one you thought was the best?', None, None, None, ''),
	('How much should a 13 year old weigh?', None, 13.0, None, ''),
	("How my Daddy's Cock changed me in one night.", None, None, None, ''),
	('How the heck I translate something you ask?', None, None, None, ''),
	('How to Be a Gardener', None, None, None, ''),
	('How to Blow Your Mind.', None, None, None, ''),
	('How to Interrupt Like a President', None, None, None, ''),
	('How to Propose to a Mop', None, None, None, ''),
	('How to Raise a Pet Mummy', None, None, None, ''),
	('How to Raise a Pet Mummy 2, Above the Cloud Sea 20.1-20.3', None, 2.0, None, ''),
	('How to do a superhero conflict right', None, None, None, ''),
	('How to escape the Friendzone', None, None, None, ''),
	('How to get super early dementia', None, None, None, ''),
	('How to migrate your WordPress website to Cloudways for Free?', None, None, None, ''),
	('How to read Chinese', None, None, None, ''),
	('How to survive an alien invasion', None, None, None, ''),
	('How to?!', None, None, None, ''),
	('How writing changed my life? (Read this please)', None, None, None, ''),
	('Hua Xu Yin 6 (2) 13 Yue', None, 6.0, None, ''),
	('Hua Xu Yin Chapter 6 (1) 13 Yue', None, 6.0, None, ''),
	('Hua Xu Yin Chapter 6 (3) 13 Yue', None, 6.0, None, ''),
	('Hua Xu Yin Update Post 2', None, 2.0, None, ''),
	('Hua Xu Yin Update Status', None, None, None, ''),
	('Huffelscruff', None, None, None, ''),
	('Huge Post Wall Incoming', None, None, None, ''),
	('Huge Update about CSR, SR, BTTH and DD', None, None, None, ''),
	('Huge news!!', None, None, None, ''),
	('Human Doll Contract Manhua Chapter 1', None, 1.0, None, ''),
	('Human Doll Contract Manhua Chapter 2: Twins', None, 2.0, None, ''),
	('Human Doll Contract Manhua Chapter 3: Those Things that Cannot be Seen', None, 3.0, None, ''),
	('Human Doll Contract Manhua Chapter 4: Jiu Ge', None, 4.0, None, ''),
	('Human Doll Contract Manhua Chapter 5: Fuel', None, 5.0, None, ''),
	('Human Doll Contract Manhua Chapter 6: Inferno', None, 6.0, None, ''),
	('Humans are the Strongest Chapter 1', None, 1.0, None, ''),
	('Humans are the Strongest Race Chapter 2', None, 2.0, None, ''),
	('Humans are the Strongest Race Chapter 3', None, 3.0, None, ''),
	('Humans are the Strongest Race Chapter 4', None, 4.0, None, ''),
	('Humans are the Strongest Race Chapter 5', None, 5.0, None, ''),
	('Humans are the Strongest Race Chapter 6', None, 6.0, None, ''),
	('Hundred Volume 1 final!', 1.0, None, None, ''),
	('Hundred – Volume 3 – Prologue (Teaser)', 3.0, None, None, 'Prologue (Teaser)'),
	('Hunter Club – Chapter 1', None, 1.0, None, ''),
	('Hunter Club – Chapter 2', None, 2.0, None, ''),
	('Hunter Club – Chapter 3', None, 3.0, None, ''),
	('Hunter Club – Chapter 4', None, 4.0, None, ''),
	('Hunter Club – Chapter 5', None, 5.0, None, ''),
	('Hunter Club – Chapter 6', None, 6.0, None, ''),
	('Hunter Club – Chapter 7', None, 7.0, None, ''),
	('Hunter Club – Chapter 8', None, 8.0, None, ''),
	('Hunter Club – Chapter 9', None, 9.0, None, ''),
	('Hunting Tigers and Chasing Eagles', None, None, None, ''),
	('Hurray! Hurray, Demenious is back….', None, None, None, ''),
	('Huts (1) – Blue 93', None, 1.0, None, ''),
	('Huts (2) – Blue 93', None, 2.0, None, ''),
	('Huts (3) – Blue 93', None, 3.0, None, ''),
	('Huts (4) – Blue 93', None, 4.0, None, ''),
	('HxH VOl 3 Ch 3 finished', 3.0, 3.0, None, ''),
	('HxH VOl 4 Complete', 4.0, None, None, ''),
	('HxH Vol 1 Ch 2 Finished', 1.0, 2.0, None, ''),
	('HxH Vol 1 Chapter 1 complete', 1.0, 1.0, None, ''),
	('HxH Vol 1 ch 3 finished', 1.0, 3.0, None, ''),
	('HxH Vol 1 prologue complete', 1.0, None, None, 'prologue complete'),
	('HxH Vol 2 Ch 1 Complete', 2.0, 1.0, None, ''),
	('HxH Vol 2 Ch 2', 2.0, 2.0, None, ''),
	('HxH Vol 2 Ch 3 complete', 2.0, 3.0, None, ''),
	('HxH Vol 2 Chapter 4 complete', 2.0, 4.0, None, ''),
	('HxH Vol 2 Prologue complete', 2.0, None, None, 'Prologue complete'),
	('HxH Vol 3 Ch 1 complete', 3.0, 1.0, None, ''),
	('HxH Vol 3 Ch 2 complete', 3.0, 2.0, None, ''),
	('HxH Vol 3 Ch 4 finished', 3.0, 4.0, None, ''),
	('HxH Vol 3 Complete', 3.0, None, None, ''),
	('HxH Vol 4 Ch 1 complete', 4.0, 1.0, None, ''),
	('HxH Vol 4 Ch 2 Complete', 4.0, 2.0, None, ''),
	('HxH Vol 4 Ch 3 complete', 4.0, 3.0, None, ''),
	('HxH Vol 4 Prologue complete', 4.0, None, None, 'Prologue complete'),
	('HxH Vol 6 Ch 1 Complete', 6.0, 1.0, None, ''),
	('HxH Vol 6 Ch 2 Complete', 6.0, 2.0, None, ''),
	('HxH Vol 6 Ch 3 Complete', 6.0, 3.0, None, ''),
	('HxH Vol 6 Prologue complete', 6.0, None, None, 'Prologue complete'),
	('HxH Vol 6 and Vol 7 Prologue Complete', 6.0, None, None, 'Prologue Complete'),
	('HxH Vol 7 Ch 2 Complete', 7.0, 2.0, None, ''),
	('HxH Vol 7 Ch 3 Complete', 7.0, 3.0, None, ''),
	('HxH Vol 7 Ch 4 finished', 7.0, 4.0, None, ''),
	('HxH Vol 7 Chapter 1 complete', 7.0, 1.0, None, ''),
	('HxH Vol 7 complete', 7.0, None, None, ''),
	('HxH Vol 8 Chapter 1 finished', 8.0, 1.0, None, ''),
	('HxH Vol 8 Chapter 2 complete', 8.0, 2.0, None, ''),
	('HxH Vol 8 Chapter 3 Complete', 8.0, 3.0, None, ''),
	('HxH Vol 8 Chapter 4 Complete', 8.0, 4.0, None, ''),
	('HxH Vol 8 Complete', 8.0, None, None, ''),
	('HxH Vol 8 Prologue Complete', 8.0, None, None, 'Prologue Complete'),
	('HxH Volume 2 + Vol 3 Prologue complete', 2.0, None, None, 'Prologue complete'),
	('HxH vol 1 complete', 1.0, None, None, ''),
	('Hxh VOl 8 Chapter 5 complete', 8.0, 5.0, None, ''),
	('Hyaku ma no Shu Ch 3-4 Updated!', None, 3, 4, ''),
	('Hyaku ma no Shu, Ch 1-2 Updated!', None, 1, 2, ''),
	('Hyakuren no Haou to Seiyaku no Valkyria Volume 1 Prologue', 1.0, None, None, 'Prologue'),
	('Hyouka PL', None, None, None, ''),
	('Hyouka PL: Tom 2 Rozdział 5', None, 2.0, None, ''),
	('Hyouketsu Kyoukai no Eden Volume 6 Afterword', 6.0, None, None, 'Afterword'),
	('Hyouketsu Kyoukai no Eden Volume 6 Epub', 6.0, None, None, ''),
	('Hyouketsu Kyoukai no Eden Volume 7 Prologue', 7.0, None, None, 'Prologue'),
	('Hyouketsu Kyoukai no Eden Volume 7 – Blank Baptism', 7.0, None, None, ''),
	('Hyouketsu Kyoukai no Eden Volume 7, Chapter 1 – The Separated', 7.0, 1.0, None, ''),
	('Hyouketsu Kyoukai no Eden Volume 7, Chapter 2 – Those Who Set Off. Those Who Wish. Those Who Continue to Pray', 7.0, 2.0, None, ''),
	('Hyouketsu Kyoukai no Eden Volume 7, Chapter 3 – Chance Meeting', 7.0, 3.0, None, ''),
	('Hyouketsu Kyoukai no Eden Volume 7, Intermission – Ultramarine', 7.0, None, None, 'Intermission – Ultramarine'),
	('Hyouketsu Kyoukai no Eden:Volume 4 Chapter1', 4, 1, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 4 Chapter2', 4, 2, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 4 Final Chapter', 4.0, None, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 5 Chapter1', 5, 1, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 5 Chapter2', 5, 2, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 5 Chapter3', 5, 3, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 5 Prologue', 5.0, None, None, 'Prologue'),
	('Hyouketsu Kyoukai no Eden:Volume 6 Chapter1', 6, 1, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 6 Chapter2', 6, 2, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 6 Chapter3', 6, 3, None, ''),
	('Hyouketsu Kyoukai no Eden:Volume 6 Epilogue', 6.0, None, None, 'Epilogue'),
	('Hyouketsu Kyoukai no Eden:Volume 6 Final Chapter', 6.0, None, None, ''),
	('Hyperion 7 Volume 1 Chapter 2', 1.0, 2.0, None, ''),
	('Hyperion 7 Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('Hyperion 7 Volume 1 Chapter 4', 1.0, 4.0, None, ''),
	('Hyperion 7 Volume 1 Chapter 5', 1.0, 5.0, None, ''),
	('Hyperion 7 Volume 1 Chapter 6', 1.0, 6.0, None, ''),
	('Hyuman, The Truth and an Encounter ~Rinon~', None, None, None, ''),
	('h5.17k.com ranking', None, 5, None, ''),
	('hangover', None, None, None, ''),
	('happy chinese new year', None, None, None, ''),
	('he is watching me', None, None, None, ''),
	('hey', None, None, None, ''),
	('hi', None, None, None, ''),
	('hi snow is here', None, None, None, ''),
	('hikadelay 2', None, 2.0, None, ''),
	('hikadelay? JK', None, None, None, ''),
	('history of archia', None, None, None, ''),
	('hohohohohohoho', None, None, None, ''),
	('how to be sexy when gay and being a lesbaein', None, None, None, ''),
	('http://www.wuxiaworld.com/pw-index/pw-chapter-110/', None, 110.0, None, ''),
]

