

data = [
	('K-Drama Review : Marriage Contract (결혼계약)', None, None, None, ''),
	('K-Drama Review : Noble, My Love (고결한 그대) – Part 1', None, None, 1.0, ''),
	('K-Drama Review : Noble, My Love (고결한 그대) – Part 2', None, None, 2.0, ''),
	('K-Drama Review : Noble, My Love (고결한 그대) – Part 3', None, None, 3.0, ''),
	('K-Drama Review : Page Turner (페이지 터너)', None, None, None, ''),
	('K-Drama Review : Splash Splash Love (퐁당퐁당 LOVE) – Part 1', None, None, 1.0, ''),
	('K-Drama Review : Splash Splash Love (퐁당퐁당 LOVE) – Part 2', None, None, 2.0, ''),
	('KENS Character Index', None, None, None, ''),
	("KFN A11C7 - The Dark Duke's trap", None, 7.0, None, ''),
	("KFN A11C8 - The Lion's Maiden", None, 8.0, None, ''),
	('KFN A12C1 - Company of pretty boy knights', None, 1.0, None, ''),
	('KFN A12C2 - We meet again, princess (Summary)', None, 2.0, None, ''),
	('KFN A12C5 - A lost amber necklace', None, 5.0, None, ''),
	('KFN Chapter 128 Raw', None, 128.0, None, ''),
	('KFN Chapter 129 Raws', None, 129.0, None, ''),
	('KFN Chapter 131 Raw', None, 131.0, None, ''),
	('KFN Manhua Chapter 130 Translations', None, 130.0, None, ''),
	('KFN Manhua Chapter 132', None, 132.0, None, ''),
	('KFN Raw Chapter 130', None, 130.0, None, ''),
	("KFN Special Chapter - The record of the knights' search for a life partner", None, None, None, ''),
	('KFN Special Chapter Teaser', None, None, None, ''),
	('KFNA11C10 - Duchess (Shitty Translation Ver)', None, 10.0, None, ''),
	('KFNA11C6 - Lost scabbard', None, 6.0, None, ''),
	('KFNA12C3 - Love is poison (Summary)', None, 3.0, None, ''),
	('KFNA12C4 - Strange fall into the lake', None, 4.0, None, ''),
	('KFNA2C4 - The language of flowers, Cosmos', None, 4.0, None, ''),
	('KFNA9C2 - The return of the knight brothers (Part 1)', None, 2.0, 1.0, ''),
	('KGGD Chapter 10!', None, 10.0, None, ''),
	('KGGD Chapter 100-101', None, 100, 101, ''),
	('KGGD Chapter 102!', None, 102.0, None, ''),
	('KGGD Chapter 103!', None, 103.0, None, ''),
	('KGGD Chapter 106 + Announcement!', None, 106.0, None, ''),
	('KGGD Chapter 107!', None, 107.0, None, ''),
	('KGGD Chapter 108!', None, 108.0, None, ''),
	('KGGD Chapter 109!', None, 109.0, None, ''),
	('KGGD Chapter 11!', None, 11.0, None, ''),
	('KGGD Chapter 110!', None, 110.0, None, ''),
	('KGGD Chapter 111!', None, 111.0, None, ''),
	('KGGD Chapter 112!', None, 112.0, None, ''),
	('KGGD Chapter 113!', None, 113.0, None, ''),
	('KGGD Chapter 114!', None, 114.0, None, ''),
	('KGGD Chapter 115!', None, 115.0, None, ''),
	('KGGD Chapter 116!', None, 116.0, None, ''),
	('KGGD Chapter 117!', None, 117.0, None, ''),
	('KGGD Chapter 118!', None, 118.0, None, ''),
	('KGGD Chapter 119!', None, 119.0, None, ''),
	('KGGD Chapter 12!', None, 12.0, None, ''),
	('KGGD Chapter 13!', None, 13.0, None, ''),
	('KGGD Chapter 14!', None, 14.0, None, ''),
	('KGGD Chapter 15!', None, 15.0, None, ''),
	('KGGD Chapter 16!', None, 16.0, None, ''),
	('KGGD Chapter 17!', None, 17.0, None, ''),
	('KGGD Chapter 18!', None, 18.0, None, ''),
	('KGGD Chapter 19!', None, 19.0, None, ''),
	('KGGD Chapter 20!', None, 20.0, None, ''),
	('KGGD Chapter 21', None, 21.0, None, ''),
	('KGGD Chapter 22!', None, 22.0, None, ''),
	('KGGD Chapter 23!', None, 23.0, None, ''),
	('KGGD Chapter 24!', None, 24.0, None, ''),
	('KGGD Chapter 25!', None, 25.0, None, ''),
	('KGGD Chapter 26!', None, 26.0, None, ''),
	('KGGD Chapter 27!', None, 27.0, None, ''),
	('KGGD Chapter 28!', None, 28.0, None, ''),
	('KGGD Chapter 29!', None, 29.0, None, ''),
	('KGGD Chapter 30!', None, 30.0, None, ''),
	('KGGD Chapter 31!', None, 31.0, None, ''),
	('KGGD Chapter 32!', None, 32.0, None, ''),
	('KGGD Chapter 33!', None, 33.0, None, ''),
	('KGGD Chapter 34!', None, 34.0, None, ''),
	('KGGD Chapter 35!', None, 35.0, None, ''),
	('KGGD Chapter 36!', None, 36.0, None, ''),
	('KGGD Chapter 37!', None, 37.0, None, ''),
	('KGGD Chapter 38!', None, 38.0, None, ''),
	('KGGD Chapter 39!', None, 39.0, None, ''),
	('KGGD Chapter 4!', None, 4.0, None, ''),
	('KGGD Chapter 40!', None, 40.0, None, ''),
	('KGGD Chapter 41!', None, 41.0, None, ''),
	('KGGD Chapter 42!', None, 42.0, None, ''),
	('KGGD Chapter 43!', None, 43.0, None, ''),
	('KGGD Chapter 44!', None, 44.0, None, ''),
	('KGGD Chapter 45!', None, 45.0, None, ''),
	('KGGD Chapter 46!', None, 46.0, None, ''),
	('KGGD Chapter 47!', None, 47.0, None, ''),
	('KGGD Chapter 48!', None, 48.0, None, ''),
	('KGGD Chapter 49!', None, 49.0, None, ''),
	('KGGD Chapter 5!', None, 5.0, None, ''),
	('KGGD Chapter 50!', None, 50.0, None, ''),
	('KGGD Chapter 51!', None, 51.0, None, ''),
	('KGGD Chapter 52!', None, 52.0, None, ''),
	('KGGD Chapter 53!', None, 53.0, None, ''),
	('KGGD Chapter 54!', None, 54.0, None, ''),
	('KGGD Chapter 55!', None, 55.0, None, ''),
	('KGGD Chapter 56!', None, 56.0, None, ''),
	('KGGD Chapter 57!', None, 57.0, None, ''),
	('KGGD Chapter 58!', None, 58.0, None, ''),
	('KGGD Chapter 59!', None, 59.0, None, ''),
	('KGGD Chapter 6!', None, 6.0, None, ''),
	('KGGD Chapter 60!', None, 60.0, None, ''),
	('KGGD Chapter 61!', None, 61.0, None, ''),
	('KGGD Chapter 62!', None, 62.0, None, ''),
	('KGGD Chapter 63!', None, 63.0, None, ''),
	('KGGD Chapter 64!', None, 64.0, None, ''),
	('KGGD Chapter 65!', None, 65.0, None, ''),
	('KGGD Chapter 66!', None, 66.0, None, ''),
	('KGGD Chapter 67!', None, 67.0, None, ''),
	('KGGD Chapter 68!', None, 68.0, None, ''),
	('KGGD Chapter 69!', None, 69.0, None, ''),
	('KGGD Chapter 7!', None, 7.0, None, ''),
	('KGGD Chapter 70!', None, 70.0, None, ''),
	('KGGD Chapter 71!', None, 71.0, None, ''),
	('KGGD Chapter 72!', None, 72.0, None, ''),
	('KGGD Chapter 73!', None, 73.0, None, ''),
	('KGGD Chapter 74!', None, 74.0, None, ''),
	('KGGD Chapter 75!', None, 75.0, None, ''),
	('KGGD Chapter 76!', None, 76.0, None, ''),
	('KGGD Chapter 77!', None, 77.0, None, ''),
	('KGGD Chapter 78!', None, 78.0, None, ''),
	('KGGD Chapter 79!', None, 79.0, None, ''),
	('KGGD Chapter 8!', None, 8.0, None, ''),
	('KGGD Chapter 80!', None, 80.0, None, ''),
	('KGGD Chapter 81!', None, 81.0, None, ''),
	('KGGD Chapter 82!', None, 82.0, None, ''),
	('KGGD Chapter 83!', None, 83.0, None, ''),
	('KGGD Chapter 84!', None, 84.0, None, ''),
	('KGGD Chapter 85!', None, 85.0, None, ''),
	('KGGD Chapter 86!', None, 86.0, None, ''),
	('KGGD Chapter 87!', None, 87.0, None, ''),
	('KGGD Chapter 88!', None, 88.0, None, ''),
	('KGGD Chapter 89!', None, 89.0, None, ''),
	('KGGD Chapter 9!', None, 9.0, None, ''),
	('KGGD Chapter 90!', None, 90.0, None, ''),
	('KGGD Chapter 91!', None, 91.0, None, ''),
	('KGGD Chapter 92!', None, 92.0, None, ''),
	('KGGD Chapter 93!', None, 93.0, None, ''),
	('KGGD Chapter 94!', None, 94.0, None, ''),
	('KGGD Chapter 95 + Announcement', None, 95.0, None, ''),
	('KGGD Chapter 96!', None, 96.0, None, ''),
	('KGGD Chapter 97!', None, 97.0, None, ''),
	('KGGD Chapters 104-105!', None, 104, 105, ''),
	('KGGD Chapters 98 and 99!', None, 98.0, None, ''),
	('KKDB Accessing Problems', None, None, None, ''),
	('KKDB Episode 1 Part 10', None, 1.0, 10.0, ''),
	('KKDB Episode 1 Part 6', None, 1.0, 6.0, ''),
	('KKDB Episode 1 Part 7', None, 1.0, 7.0, ''),
	('KKDB Episode 1 Part 8', None, 1.0, 8.0, ''),
	('KKDB Episode 1 Part 9', None, 1.0, 9.0, ''),
	('KKDB Episode 2 Part 1', None, 2.0, 1.0, ''),
	('KKDB Episode 2 Part 2', None, 2.0, 2.0, ''),
	('KKDB Episode 2 Part 3', None, 2.0, 3.0, ''),
	('KKDB Episode 2 Part 4', None, 2.0, 4.0, ''),
	('KKDB Episode 2 Part 5', None, 2.0, 5.0, ''),
	('KKDB Episode 2 Part 6', None, 2.0, 6.0, ''),
	('KKDB Episode 2 Part 7', None, 2.0, 7.0, ''),
	('KKDB Episode 2 Part 8', None, 2.0, 8.0, ''),
	('KKDB Episode 3 Part 1', None, 3.0, 1.0, ''),
	('KKDB Episode 3 Part 2', None, 3.0, 2.0, ''),
	('KKDB Episode 3 Part 3', None, 3.0, 3.0, ''),
	('KKDB Episode 3 Part 5', None, 3.0, 5.0, ''),
	('KKDB Episode 3 Part 6', None, 3.0, 6.0, ''),
	('KKDB Episode 4 Part 4', None, 4.0, 4.0, ''),
	('KNM: Volume 14 Chapter 1', 14.0, 1.0, None, ''),
	('KS chapters~!', None, None, None, ''),
	('KSGU:Volume 6 Chapter 1', 6.0, 1.0, None, ''),
	('KYNE Chapters to celebrate the reach of a new milestone!', None, None, None, ''),
	('KYNE – Chapter 1', None, 1.0, None, ''),
	('KYNE – Chapter 10', None, 10.0, None, ''),
	('KYNE – Chapter 11', None, 11.0, None, ''),
	('KYNE – Chapter 12', None, 12.0, None, ''),
	('KYNE – Chapter 13', None, 13.0, None, ''),
	('KYNE – Chapter 2', None, 2.0, None, ''),
	('KYNE – Chapter 3', None, 3.0, None, ''),
	('KYNE – Chapter 6', None, 6.0, None, ''),
	('KYNE – Chapter 7', None, 7.0, None, ''),
	('KYNE – Chapter 8', None, 8.0, None, ''),
	('KYNE – Chapter 9', None, 9.0, None, ''),
	('Kagayome.', None, None, None, ''),
	('Kahani Ek Model Ki', None, None, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 0: The day of the Sacred Flame Festival', None, 0.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 1: Listen up! Read the newspapers', None, 1.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 2: The hand of mine is small and frail', None, 2.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 3: The dearly missed atmosphere of kendo sounds', None, 3.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 4: The trick is the coordination of the wrist and the fingers', None, 4.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 5: It’s good if you talk obediently', None, 5.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 6: It’s the twisting of good and evil because of a strange coincidence', None, 6.0, None, ''),
	('Kakei Senki wo Kakageyo! – Chapter 7: Herbivores, carnivores, a shepherd and me', None, 7.0, None, ''),
	('Kami no Rhapsody Play Guide and Tips', None, None, None, ''),
	('Kamigoroshi no Eiyuu Chapter 15 [I’m (not) dead][PC still dead tho.]', None, 15.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 10', None, 10.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 11', None, 11.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 12', None, 12.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 13', None, 13.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 14', None, 14.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 15', None, 15.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 16', None, 16.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 16 [PC still Dead tho.:(]', None, 16.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 17', None, 17.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 17 [I’m back for good! \\m/]', None, 17.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 18', None, 18.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 19', None, 19.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 2', None, 2.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 20', None, 20.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 21', None, 21.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 22', None, 22.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 23', None, 23.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 24', None, 24.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 25', None, 25.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 26', None, 26.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 27', None, 27.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 27- 28', None, 27.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 28', None, 28.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 29', None, 29.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 3', None, 3.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 30', None, 30.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 31', None, 31.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 32', None, 32.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 33', None, 33.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 34', None, 34.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 35', None, 35.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 36', None, 36.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 37', None, 37.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 38', None, 38.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 39', None, 39.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 4', None, 4.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 40', None, 40.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 41 (Part 1)', None, 41.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 41 (Part 2/2)', None, 41.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 42 (Part 1)', None, 42.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 42 (Part 2/2)', None, 42.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 43 (Part 1)', None, 43.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 43 (Part 2/2)', None, 43.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 44', None, 44.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 45 (Part 2/2)', None, 45.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 45 (part 1)', None, 45.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 46 (Part 1)', None, 46.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 46 (Part 2/2)', None, 46.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 47', None, 47.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 48', None, 48.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 49', None, 49.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 5', None, 5.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 50 (Part 1)', None, 50.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 50 (Part 2/2)', None, 50.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 51', None, 51.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 52', None, 52.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 53', None, 53.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 54', None, 54.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 55', None, 55.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 56', None, 56.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 57 (Part 1)', None, 57.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 57 (Part 2/2)', None, 57.0, 2.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 58', None, 58.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 59 (Part 1)', None, 59.0, 1.0, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 6', None, 6.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 7', None, 7.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 8', None, 8.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Chapter 9', None, 9.0, None, ''),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 1', None, 1.0, None, 'Interlude 1'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 2', None, 2.0, None, 'Interlude 2'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 3', None, 3.0, None, 'Interlude 3'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 4', None, 4.0, None, 'Interlude 4'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 5', None, 5.0, None, 'Interlude 5'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 5 (Part 2/2)', None, 5.0, 2.0, 'Interlude 5 (Part 2/2)'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 6', None, 6.0, None, 'Interlude 6'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku Interlude 7', None, 7.0, None, 'Interlude 7'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku LN Volume 1 Illustrations', 1.0, None, None, 'Illustrations'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku LN Volume 2 Illustrations', 2.0, None, None, 'Illustrations'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku LN Volume 3 Illustrations [Spoilers]', 3.0, None, None, 'Illustrations [Spoilers]'),
	('Kamigoroshi no Eiyuu to Nanatsu no Seiyaku LN Volume 4 Illustrations [Spoilers]', 4.0, None, None, 'Illustrations [Spoilers]'),
	('Kamisama no Memochou:Volume 5 Chapter 1', 5.0, 1.0, None, ''),
	('Kamisama no Memochou:Volume 6 Chapter 1', 6.0, 1.0, None, ''),
	('Kamisama no Memochou:Volume 7 Chapter 1', 7.0, 1.0, None, ''),
	('Kamisama no Memochou:Volume 8 Chapter 1', 8.0, 1.0, None, ''),
	('Kamisama no Memochou:Volume 9 Chapter 1', 9.0, 1.0, None, ''),
	('Kamisama no Memochou:Volume 9 Chapter 7', 9.0, 7.0, None, ''),
	('Kamisama no Memochou:Volume 9 Chapter 8', 9.0, 8.0, None, ''),
	('Kamisu Reina:Volume 1 Epilogue', 1.0, None, None, 'Epilogue'),
	('Kamitachi ni Hirowareta Otoko ToC', None, None, None, ''),
	('Kansu 49 + ART!', None, 49.0, None, ''),
	('Kansu Art!!!', None, None, None, ''),
	('Kansu Ch48 The Girl That Didn’t Have It: Part 2', None, 48.0, 2.0, ''),
	('Kansutoppu  Chapter 45 Union part 4', None, 45.0, 4.0, ''),
	('Kansutoppu Ch 47 The Girl That Didn’t Have It part 1', None, 47.0, 1.0, ''),
	('Kansutoppu Chapter 45 Union part 4', None, 45.0, 4.0, ''),
	('Kansutoppu Chapter 46 Union End', None, 46.0, None, ''),
	('Kansutoppu! Chapter 30', None, 30, None, ''),
	('Kansutoppu! Chapter 31', None, 31, None, ''),
	('Kansutoppu! Chapter 32', None, 32, None, ''),
	('Kansutoppu! Chapter 33', None, 33, None, ''),
	('Kansutoppu! Chapter 34', None, 34, None, ''),
	('Kansutoppu! Chapter 35', None, 35, None, ''),
	('Kansutoppu! Chapter 36', None, 36, None, ''),
	('Kansutoppu! Chapter 37', None, 37, None, ''),
	('Kansutoppu! Chapter 38', None, 38, None, ''),
	('Kansutoppu! Chapter 39', None, 39, None, ''),
	('Kansutoppu! Chapter 40', None, 40, None, ''),
	('Kansutoppu! Chapter 41', None, 41, None, ''),
	('Kansutoppu! Chapter 42', None, 42, None, ''),
	('Kansutoppu! Chapter 43', None, 43.0, None, ''),
	('Kantai Collection E-5', None, 5.0, None, ''),
	('Kapitel 03 - Der rote Regenschirm', None, 3.0, None, ''),
	('Kara no Kyōkai translations', None, None, None, ''),
	("Kara's First Odd Insertion", None, None, None, ''),
	('Kauai', None, None, None, ''),
	('Kayoi Gahama-san.', None, None, None, ''),
	('Kaze no Stigma', None, None, None, ''),
	('Kaze no Stigma - Français', None, None, None, ''),
	('Kaze no Stigma - Français:Volume1 Chapitre1', 1.0, 1.0, None, ''),
	('Kaze no Stigma - Français:Volume1 Chapitre5', 1.0, 5.0, None, ''),
	('Kaze no Stigma - Français:Volume1 Chapitre6', 1.0, 6.0, None, ''),
	('Kaze no Stigma - Français:Volume1 Commentaire', 1.0, None, None, ''),
	('Kaze no Stigma - Français:Volume1 Postface', 1.0, None, None, ''),
	('Kaze no kishihime capitulo1 Karin', None, 1.0, None, ''),
	('Kaze no kishihime prologo', None, None, None, ''),
	('Ke Lake or Clark', None, None, None, ''),
	('Keep them a secret first~~', None, None, None, ''),
	('Kemono Chapter 1', None, 1.0, None, ''),
	('Kemono Chapter 2', None, 2.0, None, ''),
	('Kemono Chapter 3', None, 3.0, None, ''),
	('Kemono Chapter 4', None, 4.0, None, ''),
	('Kemono Chapter 5', None, 5.0, None, ''),
	('Kemono Chapter 6', None, 6.0, None, ''),
	('Kemono Chapter 7', None, 7.0, None, ''),
	('Kemono Chapter 8', None, 8.0, None, ''),
	('Kenja ni Natta (I Became a Sage) – Prologue', None, None, None, 'Prologue'),
	('Kenja ni Natta – Chapter 1-1', None, 1, 1, ''),
	('Kenja ni Natta – Chapter 1-10', None, 1, 10, ''),
	('Kenja ni Natta – Chapter 1-11', None, 1, 11, ''),
	('Kenja ni Natta – Chapter 1-2', None, 1, 2, ''),
	('Kenja ni Natta – Chapter 1-3', None, 1, 3, ''),
	('Kenja ni Natta – Chapter 1-4', None, 1, 4, ''),
	('Kenja ni Natta – Chapter 1-5', None, 1, 5, ''),
	('Kenja ni Natta – Chapter 1-6', None, 1, 6, ''),
	('Kenja ni Natta – Chapter 1-7', None, 1, 7, ''),
	('Kenja ni Natta – Chapter 1-8', None, 1, 8, ''),
	('Kenja ni Natta – Chapter 1-9', None, 1, 9, ''),
	('Kenja no Mago', None, None, None, ''),
	('Kenkoku no Jungfrau', None, None, None, ''),
	('Kenkoku no Jungfrau:Volume 1 Illustrations', 1.0, None, None, 'Illustrations'),
	('Kenkyo, kenjitsu o motto ni ikite orimasu! chapter 20', None, 20.0, None, ''),
	('Kenkyo, kenjitsu o motto ni ikite orimasu! chapter 21', None, 21.0, None, ''),
	('Kenshin no Keishousha', None, None, None, ''),
	('Kept you waiting huh?', None, None, None, ''),
	('Kerberos 06 and Shinmai 18', None, 6.0, None, ''),
	("Kiba's Long Day", None, None, None, ''),
	("Kiba's Surprise", None, None, None, ''),
	('Kicking Ass in the Rankings!', None, None, None, ''),
	('Kicking arses like a boss…', None, None, None, ''),
	('Kidnapped...', None, None, None, ''),
	('Kidnapping is Always an Option', None, None, None, ''),
	('Kikou Shoujo wa Kizutsukanai ~Brazilian Portuguese~', None, None, None, ''),
	('Kill No More VS 1/2 Prince V1C5: Chapter 5', 1.0, 5.0, None, ''),
	('Kill No More VS 1/2 Prince V1C6: Chapter 6', 1.0, 6.0, None, ''),
	('Kill No More VS 1/2 Prince V1C7: Chapter 7', 1.0, 7.0, None, ''),
	('Kill No More VS 1/2 Prince V1C8: Chapter 8', 1.0, 8.0, None, ''),
	('Kill No More VS 1/2 Prince V1C9: Chapter 9 (END)', 1.0, 9.0, None, ''),
	('Kill Run (1) – Blue 98', None, 1.0, None, ''),
	('Kill Switch Version A by Phoenixwriter', None, None, None, ''),
	('Kill Switch Version B by Phoenixwriter', None, None, None, ''),
	('Kill Switch Version C by Phoenixwriter', None, None, None, ''),
	('Kill the Lights', None, None, None, ''),
	('Kill the Lights Chapters', None, None, None, ''),
	('KimiNozo Project Update!', None, None, None, ''),
	('Kindhearted Bee Comments on MGA Publication!', None, None, None, ''),
	('Kindred – Chapter 1-3', None, 1, 3, ''),
	('Kindred – Chapter 1-5', None, 1, 5, ''),
	('Kindred – Chapter 10', None, 10.0, None, ''),
	('Kindred – Chapter 11', None, 11.0, None, ''),
	('Kindred – Chapter 12', None, 12.0, None, ''),
	('Kindred – Chapter 13', None, 13.0, None, ''),
	('Kindred – Chapter 14', None, 14.0, None, ''),
	('Kindred – Chapter 15', None, 15.0, None, ''),
	('Kindred – Chapter 16', None, 16.0, None, ''),
	('Kindred – Chapter 17', None, 17.0, None, ''),
	('Kindred – Chapter 18', None, 18.0, None, ''),
	('Kindred – Chapter 19', None, 19.0, None, ''),
	('Kindred – Chapter 20', None, 20.0, None, ''),
	('Kindred – Chapter 21', None, 21.0, None, ''),
	('Kindred – Chapter 22', None, 22.0, None, ''),
	('Kindred – Chapter 23', None, 23.0, None, ''),
	('Kindred – Chapter 24', None, 24.0, None, ''),
	('Kindred – Chapter 25', None, 25.0, None, ''),
	('Kindred – Chapter 26', None, 26.0, None, ''),
	('Kindred – Chapter 27', None, 27.0, None, ''),
	('Kindred – Chapter 28', None, 28.0, None, ''),
	('Kindred – Chapter 29', None, 29.0, None, ''),
	('Kindred – Chapter 30', None, 30.0, None, ''),
	('Kindred – Chapter 31', None, 31.0, None, ''),
	('Kindred – Chapter 32', None, 32.0, None, ''),
	('Kindred – Chapter 33', None, 33.0, None, ''),
	('Kindred – Chapter 34', None, 34.0, None, ''),
	('Kindred – Chapter 35', None, 35.0, None, ''),
	('Kindred – Chapter 4', None, 4.0, None, ''),
	('Kindred – Chapter 44', None, 44.0, None, ''),
	('Kindred – Chapter 45', None, 45.0, None, ''),
	('Kindred – Chapter 46', None, 46.0, None, ''),
	('Kindred – Chapter 47', None, 47.0, None, ''),
	('Kindred – Chapter 48', None, 48.0, None, ''),
	('Kindred – Chapter 49', None, 49.0, None, ''),
	('Kindred – Chapter 5', None, 5.0, None, ''),
	('Kindred – Chapter 50', None, 50.0, None, ''),
	('Kindred – Chapter 51', None, 51.0, None, ''),
	('Kindred – Chapter 52', None, 52.0, None, ''),
	('Kindred – Chapter 53', None, 53.0, None, ''),
	('Kindred – Chapter 54', None, 54.0, None, ''),
	('Kindred – Chapter 55', None, 55.0, None, ''),
	('Kindred – Chapter 56', None, 56.0, None, ''),
	('Kindred – Chapter 57', None, 57.0, None, ''),
	('Kindred – Chapter 58', None, 58.0, None, ''),
	('Kindred – Chapter 6', None, 6.0, None, ''),
	('Kindred – Chapter 7', None, 7.0, None, ''),
	('Kindred – Chapter 8', None, 8.0, None, ''),
	('Kindred – Chapter 9', None, 9.0, None, ''),
	('King Of Kings (KoK) – prologue, chapter 1 and chapter 2', None, 1.0, None, 'prologue, chapter 1 and chapter 2'),
	('King Shura, Chapter 101', None, 101.0, None, ''),
	('King Shura, Chapter 47', None, 47.0, None, ''),
	('King Shura, Chapter 62', None, 62.0, None, ''),
	('King Shura, Chapter 63', None, 63.0, None, ''),
	('King Shura, Chapter 64', None, 64.0, None, ''),
	('King Shura, Chapter 65', None, 65.0, None, ''),
	('King Shura, Chapter 66', None, 66.0, None, ''),
	('King Shura, Chapter 67', None, 67.0, None, ''),
	('King Shura, Chapter 68', None, 68.0, None, ''),
	('King Shura, Chapter 69', None, 69.0, None, ''),
	('King Shura, Chapter 70', None, 70.0, None, ''),
	('King Shura, Chapter 71', None, 71.0, None, ''),
	('King Shura, Chapter 72', None, 72.0, None, ''),
	('King Shura, Chapter 73', None, 73.0, None, ''),
	('King Shura, Chapter 74', None, 74.0, None, ''),
	('King Shura, Chapter 75', None, 75.0, None, ''),
	('King Shura, Chapter 76', None, 76.0, None, ''),
	('King Shura, Chapter 77', None, 77.0, None, ''),
	('King Shura, Chapter 78', None, 78.0, None, ''),
	('King Shura, Chapter 79', None, 79.0, None, ''),
	('King Shura, Chapter 80', None, 80.0, None, ''),
	('King Shura, Chapter 81', None, 81.0, None, ''),
	('King Shura, Chapter 82', None, 82.0, None, ''),
	('King Shura, Chapter 83', None, 83.0, None, ''),
	('King Shura, Chapter 84', None, 84.0, None, ''),
	('King Shura, Chapter 85', None, 85.0, None, ''),
	('King Shura, Chapter 86', None, 86.0, None, ''),
	('King Shura, Chapter 88', None, 88.0, None, ''),
	('King Shura, Chapter 89', None, 89.0, None, ''),
	('King Shura, Chapter 90', None, 90.0, None, ''),
	('King Shura, Chapter 91', None, 91.0, None, ''),
	('King Shura, Chapter 92', None, 92.0, None, ''),
	('King Shura, Chapter 93', None, 93.0, None, ''),
	('King Shura, Chapter 94', None, 94.0, None, ''),
	('King Shura, Chapter 95', None, 95.0, None, ''),
	('King Shura, Chapter 96', None, 96.0, None, ''),
	('King Shura, Chapter 97', None, 97.0, None, ''),
	('King Shura, Chapter 98', None, 98.0, None, ''),
	('King Shura, Chapter 99', None, 99.0, None, ''),
	('King of Kings (KoK) chapter 3 and 4', None, 3.0, None, ''),
	('King of the Eternal Night Chapter 6', None, 6.0, None, ''),
	('King of the Eternal Night Chapter 7', None, 7.0, None, ''),
	('King of the Eternal Night, Chapter 4: Welcome to hell', None, 4.0, None, ''),
	('King of the Eternal Night, Chapter 5: QianYe and LinMing', None, 5.0, None, ''),
	("King's feet", None, None, None, ''),
	('Kings and Conquerors by Maxicue', None, None, None, ''),
	('Kininaru Chapter 11', None, 11.0, None, ''),
	('Kininaru Chapter 12', None, 12.0, None, ''),
	('Kininaru Chapter 13', None, 13.0, None, ''),
	('Kininaru Chapter 14', None, 14.0, None, ''),
	('Kininaru Chapter 15', None, 15.0, None, ''),
	('Kininaru Chapter 16', None, 16.0, None, ''),
	('Kininaru Chapter 17', None, 17.0, None, ''),
	('Kininaru Chapter 18', None, 18.0, None, ''),
	('Kininaru Chapter 19', None, 19.0, None, ''),
	('Kininaru Chapter 20', None, 20.0, None, ''),
	('Kininaru Chapter 21', None, 21.0, None, ''),
	('Kininaru Chapter 22', None, 22.0, None, ''),
	('Kininaru Chapter 23', None, 23.0, None, ''),
	('Kininaru Chapter 24', None, 24.0, None, ''),
	('Kininaru Chapter 25', None, 25.0, None, ''),
	('Kininaru Chapter 26', None, 26.0, None, ''),
	('Kininaru Chapter 27', None, 27.0, None, ''),
	('Kininaru Chapter 28', None, 28.0, None, ''),
	('Kininaru Chapter 29', None, 29.0, None, ''),
	('Kininaru Chapter 30', None, 30.0, None, ''),
	('Kininaru Chapter 31', None, 31.0, None, ''),
	('Kininaru Chapter 32', None, 32.0, None, ''),
	('Kininaru Chapter 33', None, 33.0, None, ''),
	('Kininaru Chapter 34', None, 34.0, None, ''),
	('Kininaru Chapter 35', None, 35.0, None, ''),
	('Kininaru Chapter 36', None, 36.0, None, ''),
	('Kininaru Chapter 37', None, 37.0, None, ''),
	('Kininaru Chapter 38', None, 38.0, None, ''),
	('Kininaru Chapter 39', None, 39.0, None, ''),
	('Kininaru Chapter 40', None, 40.0, None, ''),
	('Kininaru Chapter 41', None, 41.0, None, ''),
	('Kininaru Chapter 42', None, 42.0, None, ''),
	('Kininaru Chapter 43', None, 43.0, None, ''),
	('Kininaru Chapter 44', None, 44.0, None, ''),
	('Kininaru Chapter 45', None, 45.0, None, ''),
	('Kininaru Chapter 46', None, 46.0, None, ''),
	('Kininaru Chapter 47', None, 47.0, None, ''),
	('Kininaru Chapter 48', None, 48.0, None, ''),
	('Kininaru Chapter 49', None, 49.0, None, ''),
	('Kininaru Chapter 50', None, 50.0, None, ''),
	('Kininaru Chapter 51', None, 51.0, None, ''),
	('Kininaru Chapter 52', None, 52.0, None, ''),
	('Kininaru Chapter 53', None, 53.0, None, ''),
	('Kininaru chapter 17', None, 17.0, None, ''),
	('Kinkington', None, None, None, ''),
	('Kinmou’s Corner', None, None, None, ''),
	('Kino no Tabi:Volume7', 7.0, None, None, ''),
	('Kiriko Epawsode 1 – A Whole New World….maybe.', None, 1.0, None, ''),
	('Kiriko Epawsode 10 – Encroaching Shadows', None, 10.0, None, ''),
	('Kiriko Epawsode 11 – Fleeting Faces', None, 11.0, None, ''),
	('Kiriko Epawsode 12 – Devouring Demons', None, 12.0, None, ''),
	('Kiriko Epawsode 13 – The Depraved Depths', None, 13.0, None, ''),
	('Kiriko Epawsode 2 – A Deceptive Demeanor', None, 2.0, None, ''),
	('Kiriko Epawsode 3 – A ‘Beta’ Character Appeared', None, 3.0, None, ''),
	('Kiriko Epawsode 4 – A Slimy Situation', None, 4.0, None, ''),
	('Kiriko Epawsode 5 – A Specious Smile', None, 5.0, None, ''),
	('Kiriko Epawsode 6 – An Infuriating Interjection', None, 6.0, None, ''),
	('Kiriko Epawsode 7 – An Ikemen Arrived!', None, 7.0, None, ''),
	('Kiriko Epawsode 8 – The Swindler’s Surprise', None, 8.0, None, ''),
	('Kiriko Epawsode 9 – The Cockroach’s Comeback', None, 9.0, None, ''),
	('Kiriko Interlude 1 – The Red Riddle', None, 1.0, None, 'Interlude 1 – The Red Riddle'),
	('Kiriko Interlude 2 – The Converging Cogs', None, 2.0, None, 'Interlude 2 – The Converging Cogs'),
	('Kiriko Interlude 3 – The Siblings of Sin', None, 3.0, None, 'Interlude 3 – The Siblings of Sin'),
	('Kiriko SS: The Story of a Certain Noble', None, None, None, ''),
	('Kisei Kanojo Sana', None, None, None, ''),
	('Kiss The Girl', None, None, None, ''),
	('Kitaseno Yunaki-sensei interviews Anri – Character Baton', None, None, None, ''),
	('Kitaseno-sensei’s comments on EGA Cover Illustration', None, None, None, ''),
	('Kitchen Fling', None, None, None, ''),
	('Kitsune 16: To become stronger', None, 16.0, None, ''),
	('Kitsune Chapter 15: A steady week', None, 15.0, None, ''),
	('Kitsune-sama 17: Training pattern', None, 17.0, None, ''),
	('Kitsune-sama chapter 14: Start line', None, 14.0, None, ''),
	('KmF: Arc-0, Chapter-1: Price of a mistake', 0.0, 1.0, None, ''),
	('KmF: Arc-1, Chapter-1: A Farce in broad daylight', 1.0, 1.0, None, ''),
	('KmF: Arc-1, Chapter-2: Escape, return, and……', 1.0, 2.0, None, ''),
	('KmF: Arc-1, Chapter-3: 2 years and 8 years', 1.0, 3.0, None, ''),
	('KmF: Arc-1, Chapter-4: Rejection', 1.0, 4.0, None, ''),
	('KmF: Arc-2, Chapter-1: Do not make fun of my mother!', 2.0, 1.0, None, ''),
	('Kmf: Arc-2, Chapter-2: Mistake', 2.0, 2.0, None, ''),
	('KnHG Chapter 1 Part 1', None, 1.0, 1.0, ''),
	('KnHG Prologue: Red Dawn', None, None, None, 'Prologue: Red Dawn'),
	('KnHG Volume 1 Chapter 1 Part 2', 1.0, 1.0, 2.0, ''),
	('KnHG Volume 1 Chapter 1 Part 3', 1.0, 1.0, 3.0, ''),
	('KnHG Volume 1 Chapter 1 Part 4', 1.0, 1.0, 4.0, ''),
	('KnHG Volume 1 Chapter 1 Part 5', 1.0, 1.0, 5.0, ''),
	('KnHG Volume 1 Chapter 2 Part 1', 1.0, 2.0, 1.0, ''),
	('KnHG Volume 1 Chapter 2 Part 2', 1.0, 2.0, 2.0, ''),
	('KnHG Volume 1 Chapter 2 Part 3', 1.0, 2.0, 3.0, ''),
	('KnHG Volume 1 Chapter 3 Part 1', 1.0, 3.0, 1.0, ''),
	('KnHG Volume 1 Chapter 3 Part 2', 1.0, 3.0, 2.0, ''),
	('KnHG Volume 1 Chapter 3 Part 3', 1.0, 3.0, 3.0, ''),
	('KnHG Volume 1 Illustrations', 1.0, None, None, 'Illustrations'),
	('KnK on .epub, and some news on Mahoyo', None, None, None, ''),
	('KnM Chapters Late', None, None, None, ''),
	('KnW Chapter 104: King Rudolf’s Motive', None, 104, None, ''),
	('KnW Chapter 107: The Heroes Who Came to Know of Reality', None, 107, None, ''),
	('KnW Chapter 111: Those Who are Alive', None, 111, None, ''),
	('KnW Chapter 118: Hiiro, at Holy Oldine', None, 118, None, ''),
	('KnW Chapter 119: The Top’s True Strength', None, 119, None, ''),
	('KnW Chapter 120: The Protagonist that Relieves His Stress', None, 120, None, ''),
	('KnW Chapter 136: Invitation to the Castle', None, 136.0, None, ''),
	('KnW Chapter 139: Hiiro’s Coming-Out', None, 139.0, None, ''),
	('KnW Chapter 140: The Two Heroes’ Treatment', None, 140.0, None, ''),
	('KnW Chapter 141: Real Food, Demon Capital Cuisine!', None, 141.0, None, ''),
	('KnW Chapter 158: It’s Definitely About Him!', None, 158.0, None, ''),
	('KnW Chapter 159: The Red Robe’s Identity ~Arnold’s Rampage~', None, 159.0, None, ''),
	('KnW Chapter 160: Coming to Like Hiiro', None, 160.0, None, ''),
	('KnW Chapter 164: The Doting Beast King', None, 164.0, None, ''),
	('KnW Chapter 167: Reunion', None, 167.0, None, ''),
	('KnW Chapter 170: The Outcome of the Clash between the Sun and the Earth', None, 170.0, None, ''),
	('KnW Chapter 173: Their Respective Abilities', None, 173.0, None, ''),
	('KnW Chapter 175: Two vs. Two', None, 175.0, None, ''),
	('KnW Chapter 96: The Conclusion, and a Tearful Parting', None, 96, None, ''),
	('KnW Terminologies', None, None, None, ''),
	('KnW | Chapter 154 : A conversation at the jail', None, 154.0, None, ''),
	('KnW | Chapter 75 : The Apologizing Maid', None, 75, None, ''),
	('KnW | Chapter 78 : The Servant’s Worries', None, 78, None, ''),
	('KnW | Chapter 83 : Battle in Raohrb Desert', None, 83, None, ''),
	('KnW | Chapter 88 : Camus’s True Power', None, 88, None, ''),
	("Knight's & Magic Light Novel Translation", None, None, None, ''),
	("Knight's & Magic Vol 2 Chapter 12", 2, 12, None, ''),
	("Knight's & Magic Vol 2 Chapter 13", 2, 13, None, ''),
	("Knight's & Magic Vol 2 Chapter 14", 2, 14, None, ''),
	("Knight's & Magic Vol 2 Chapter 15", 2, 15, None, ''),
	("Knight's & Magic Vol 2 Chapter 16", 2, 16, None, ''),
	("Knight's & Magic Vol 2 Chapter 17", 2, 17, None, ''),
	("Knight's & Magic Vol 2 Chapter 18", 2, 18, None, ''),
	("Knight's & Magic Volume 3 Chapter 19", 3.0, 19.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 20", 3.0, 20.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 21", 3.0, 21.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 22", 3.0, 22.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 23", 3.0, 23.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 24", 3.0, 24.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 25", 3.0, 25.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 26", 3.0, 26.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 27", 3.0, 27.0, None, ''),
	("Knight's & Magic Volume 3 Chapter 28", 3.0, 28.0, None, ''),
	("Knight's & Magic Volume 3 Prologue", 3.0, None, None, 'Prologue'),
	("Knight's & Magic Volume 4 Prologue Translation Part 1", 4.0, None, 1.0, 'Prologue Translation Part 1'),
	("Knight's & Magic manga begins serialization mid April", None, None, None, ''),
	('Knowledge, Attitude and practice of contraception in Tonk District of Rajasthan', None, None, None, ''),
	('Knw chp 191 Finale', None, 191.0, None, ''),
	('Kokoro no Minato – Monkey D. Garp', None, None, None, ''),
	('Kokugensou V1 CH.1Part 10', 1.0, 1.0, 10.0, ''),
	('Kokugensou V1 Ch.1 Part 11', 1.0, 1.0, 11.0, ''),
	('Kokugensou V1 Ch.1 Part 12', 1.0, 1.0, 12.0, ''),
	('Kokugensou Volume 1 Chapter 1 Part 11', 1.0, 1.0, 11.0, ''),
	('Kokugensou Volume 1 Chapter 1 part 10', 1.0, 1.0, 10.0, ''),
	('Kokugensou wo Item Cheat de Ikinuku (LN) – Volume 1 – Chapter 1 re-Translations rehost', 1.0, 1.0, None, ''),
	('Kokugensou wo Item Cheat de Ikinuku – Volume 1 – Prologue re-Translations rehost', 1.0, None, None, 'Prologue re-Translations rehost'),
	('Kokugensou: Volume 1 Chapter 1 part 9', 1.0, 1.0, 9.0, ''),
	('Kollider', None, None, None, ''),
	('Konjiki no Moji Tsukai - Chapter 108: Enter! Okamura Hiiro!', None, 108, None, ''),
	("Konjiki no Moji Tsukai - Chapter 109: Hiiro's True Ability", None, 109, None, ''),
	('Konjiki no Moji Tsukai - Chapter 124: Hiiro, once again to the Demon Country', None, 124.0, None, ''),
	('Konjiki no Moji Tsukai - Chapter 133: The Preaching Hiiro', None, 133.0, None, ''),
	('Konjiki no Moji Tsukai - Chapter 134: The Irritated Protagonist', None, 134.0, None, ''),
	('Konjiki no Moji Tsukai - Chapter 42: Another Conference in the Demon Country', None, 42, None, ''),
	("Konjiki no Moji Tsukai - Chapter 47: Arnold's Other Objective", None, 47, None, ''),
	("Konjiki no Moji Tsukai - Chapter 52: Arnold and Company's Suspicions", None, 52, None, ''),
	('Konjiki no Moji Tsukai - Chapter 55: That Bird, Again!', None, 55, None, ''),
	('Konjiki no Moji Tsukai - Chapter 58: Now, to the Evila Continent!', None, 58, None, ''),
	('Konjiki no Moji Tsukai - Chapter 63: Venom Mountain', None, 63, None, ''),
	('Konjiki no Moji Tsukai - Chapter 66: The Chaotic Trio', None, 66, None, ''),
	('Konjiki no Moji Tsukai - Chapter 67: The Devious Girl - Liliyn', None, 67, None, ''),
	('Konjiki no Moji Tsukai - Chapter 72: The Visiting Red Rain', None, 72, None, ''),
	('Konjiki no Moji Tsukai - Chapter 76: Contract with a Demon?', None, 76, None, ''),
	('Konjiki no Moji Tsukai - Chapter 79: And now, towards the Journey', None, 79, None, ''),
	('Konjiki no Moji Tsukai - Chapter 80: The Heroes One Month Later', None, 80, None, ''),
	('Konjiki no Moji Tsukai - Chapter 87: Unyielding Thoughts', None, 87, None, ''),
	('Konjiki no Moji Tsukai - Chapter 89: Hiiro vs Camus', None, 89, None, ''),
	('Konjiki no Moji Tsukai - Chapter 93: New Word Magic Ability...and Title', None, 93, None, ''),
	('Konjiki no Moji Tsukai - Chapter 96: The Conclusion, and Tearful Farewell', None, 96, None, ''),
	('Konjiki no Moji Tsukai: Chapter 138 - The Heroes and the Demon Lord, Face-to-Face', None, 138.0, None, ''),
	("Konjiki no Moji Tsukai: Chapter 144 - The Heroes and Teckil's Meeting", None, 144.0, None, ''),
	('Konjiki no Moji Tsukai: Chapter 161 - Arnold and Muir, Duel Participation Confirmed!', None, 161.0, None, ''),
	('Konjiki no Word Master - Chapter 64: The Fight with the Cactus Man', None, 64, None, ''),
	('Konjiki no Word Master Chapter 101: Prelude to the Meeting', None, 101, None, ''),
	('Konjiki no Word Master Chapter 92: United Front', None, 92, None, ''),
	('Konjiki no Word Master Chapter 97: Rebound of Word Magic', None, 97, None, ''),
	('Konjiki no Word Master Chapter 98: Food! Ashura Nabe!', None, 98, None, ''),
	('Konjiki no Word Master chapter 106 – Beginning of War', None, 106, None, ''),
	('Konjiki no Word Master chapter 106: Beginning of War', None, 106, None, ''),
	('Konjiki no Word Master chapter 128: How to deal with zombies', None, 128.0, None, ''),
	('Konjiki no Word Master ~ (Spanish)', None, None, None, ''),
	('Konjiki no Wordmaster (Indonesia)', None, None, None, ''),
	('Konjiki no Wordmaster Chapter 101: Prelude to the Conference', None, 101, None, ''),
	('Konjiki no Wordmaster Chapter 105: Beginning of Betrayal', None, 105, None, ''),
	('Konjiki no Wordmaster Chapter 110: The Imprisoned Ones', None, 110, None, ''),
	('Konjiki no Wordmaster Chapter 121: The Transformed King', None, 121.0, None, ''),
	('Konjiki no Wordmaster Chapter 142: Late Night Conversation', None, 142.0, None, ''),
	('Konjiki no Wordmaster Chapter 155', None, 155.0, None, ''),
	('Konjiki no Wordmaster Chapter 169', None, 169.0, None, ''),
	('Konjiki no Wordmaster Chapter 174: Muir’s Struggle', None, 174.0, None, ''),
	('Konjiki no Wordmaster Chapter 191 Finale.. part 1', None, 191.0, 1.0, ''),
	('Konjiki no Wordmaster Chapter 84: The Ashura Tribe', None, 84, None, ''),
	('Konjiki no Wordmaster Chapter 94', None, 94, None, ''),
	('Konjiki no Wordmaster: Character Analysis! For the sake of a Harem? Part 1', None, None, 1, ''),
	('Konjiki no Wordmaster: Popularity Ranking Announcement', None, None, None, ''),
	('Konjiki no Wordmaster: Web Chapter 100 – After Half a Year', None, 100, None, ''),
	('Konjiki no Wordmaster: Web Chapter 102 – The Demon Lord, to the Human World', None, 102, None, ''),
	('Konjiki no Wordmaster: Web Chapter 113 – Judom’s Countermeasures and a New Betrayal', None, 113, None, ''),
	('Konjiki no Wordmaster: Web Chapter 114 – Out of Place Hiiro', None, 114, None, ''),
	('Konjiki no Wordmaster: Web Chapter 115 – Meeting with the Demon Queen', None, 115, None, ''),
	('Konjiki no Wordmaster: Web Chapter 116 – Hiiro and Eveam', None, 116, None, ''),
	('Konjiki no Wordmaster: Web Chapter 117 – Request of the Demon Lor', None, 117, None, ''),
	('Konjiki no Wordmaster: Web Chapter 117 – Request of the Demon Lord', None, 117, None, ''),
	('Konjiki no Wordmaster: Web Chapter 152 – Eveam’s Decision', None, 152.0, None, ''),
	('Konjiki no Wordmaster: Web Chapter 153 – Unprecedented Demand', None, 153.0, None, ''),
	('Konjiki no Wordmaster: Web Chapter 86 – Ashura’s Tenacity', None, 86, None, ''),
	('Konjiki no Wordmaster: Web Chapter 86 – Devotion of the Ashura', None, 86, None, ''),
	('Konjiki no Wordmaster: Web Chapter 95 – Resolve', None, 95, None, ''),
	('Konjiki no Wordmaster: Web Chapter 99 – Intoxicated Companions', None, 99, None, ''),
	('Konjiki no Wordmaster:Web Chapter 614 – Eveam’s Wish', None, 614, None, ''),
	('Konjiki no Wordmaster~Brazilian Portuguese~', None, None, None, ''),
	('Kono Koi to, Sono Mirai clinched 9th in このライトノベルがすごい! 2015', None, 9.0, None, ''),
	('Kono Suba Vol 5 Prologue  [ Let’s & Go to Crimson Demon of Explosion!! ]', 5.0, None, None, 'Prologue  [ Let’s & Go to Crimson Demon of Explosion!! ]'),
	('Kono Subarashii Sekai ni Shukufuku o!', None, None, None, ''),
	('KonoSuba Season 2 confirmed', 2.0, None, None, ''),
	('Konosuba', None, None, None, ''),
	('Konosuba 5 Chapter 1 part 2 is done, updated', None, 1.0, 2.0, ''),
	('Konosuba picked up by Yen Press', None, None, None, ''),
	('Konyaki-haki sarete Me ga Samemashita', None, None, None, ''),
	('Kore wa Zombie desu ka?', None, None, None, ''),
	('KotB 26', None, 26.0, None, ''),
	('KotB Ch 28', None, 28.0, None, ''),
	('KotB Ch 37', None, 37.0, None, ''),
	('KotB Ch 39!', None, 39.0, None, ''),
	('KotB Ch 46', None, 46.0, None, ''),
	('KotB Ch. 43', None, 43.0, None, ''),
	('KotB Chapter 10!', None, 10.0, None, ''),
	('KotB Chapter 13', None, 13.0, None, ''),
	('KotB Chapter 23~', None, 23.0, None, ''),
	('KotB Chapter 25', None, 25.0, None, ''),
	('KotB Chapter 30', None, 30.0, None, ''),
	('KotB Chapter~', None, None, None, ''),
	('KotB! Chapter 33!', None, 33.0, None, ''),
	('KotB~', None, None, None, ''),
	('Kotobukiya Yukino &Yui', None, None, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Flor/002', None, 2.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Flor/003', None, 3.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Montanha/003', None, 3.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Montanha/004', None, 4.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Morto/001', None, 1.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Morto/004', None, 4.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Morto/005', None, 5.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Morto/006', None, 6.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Nada/001', None, 1.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Nada/002', None, 2.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Nada/003', None, 3.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Pedra/006', None, 6.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Semente/001', None, 1.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Semente/002', None, 2.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Semente/003', None, 3.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Semente/004', None, 4.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Semente/005', None, 5.0, None, ''),
	('Koyomimonogatari ~Brazilian Portuguese~/Koyomi Vento/005', None, 5.0, None, ''),
	("Kristin's Demotion", None, None, None, ''),
	('Kuang Shen Chapter Released', None, None, None, ''),
	('Kuang Shen Volume 4 Chapter 4 released!', 4.0, 4.0, None, ''),
	('Kuang Shen Volume 4 Chapter 5', 4.0, 5.0, None, ''),
	('Kuang Shen Volume 4 Chapter 5 Released~!', 4.0, 5.0, None, ''),
	('Kuang Shen Volume 4 Chapter 6 released!', 4.0, 6.0, None, ''),
	('Kuang Shen Volume 6 Chapter 1!', 6.0, 1.0, None, ''),
	('Kujibiji Tokushou : Musou Harem Ken Chapter 2', None, 2.0, None, ''),
	('Kujibiji Tokushou : Musou Harem Ken Chapter 3', None, 3.0, None, ''),
	('Kujibiki Tokushou : Mushou Harem Ken Chapter 17', None, 17.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 11', None, 11.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 12', None, 12.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 13', None, 13.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 14', None, 14.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 15', None, 15.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 16', None, 16.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 19', None, 19.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 20', None, 20.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 22', None, 22.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 23', None, 23.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 24', None, 24.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 28', None, 28.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 4', None, 4.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 5', None, 5.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 6', None, 6.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 7', None, 7.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Chapter 9', None, 9.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken Volume 3 Chapter 31', 3.0, 31.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken chapter 21', None, 21.0, None, ''),
	('Kujibiki Tokushou : Musou Harem Ken v2 Chapter 33', 2.0, 33.0, None, ''),
	('Kujibiki Tokushou Characters', None, None, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken Chapter 10', None, 10.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken Chapter 18', None, 18.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken Chapter 25', None, 25.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken Chapter 26', None, 26.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken Chapter 27', None, 27.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken V2 Chapter 30', 2.0, 30.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken Volume 3 Chapter 32', 3.0, 32.0, None, ''),
	('Kujibiki Tokushou: Musou Harem Ken v2 Chapter 29', 2.0, 29.0, None, ''),
	('Kujibiki Tokushou: Musou Hāremu ken chapter 1', None, 1.0, None, ''),
	('Kujibiki tokushou: musou hāremu ken Prologue', None, None, None, 'Prologue'),
	('Kujibiku Tokushou : Musou Harem Ken Chapter 8', None, 8.0, None, ''),
	('Kujou-san’s Extreme Sadist Consultation Room', None, None, None, ''),
	('Kuma Kuma Kuma Bear – Chapter 2', None, 2.0, None, ''),
	('Kuma Kuma Kuma Bear – Volume 1 Chapter 1', 1.0, 1.0, None, ''),
	('Kumo Desu Ga, Nani Ka? 213', None, 213.0, None, ''),
	('Kumo Desu Ga, Nani Ka? 214', None, 214.0, None, ''),
	('Kumo Desu Ga, Nani Ka? 215', None, 215.0, None, ''),
	('Kumo Desu Ga, Nani Ka? 216', None, 216.0, None, ''),
	('Kumo Desu Ga, Nani Ka? Oni VS Oni ⑥', None, None, None, ''),
	('Kumo Desu Ga, Nani Ka? Oni Vs Oni ④', None, None, None, ''),
	('Kumo Desu Ga, Nani Ka? Oni vs Oni ③', None, None, None, ''),
	('Kumo Desu Ga, Nani Ka? Oni vs Oni ⑤', None, None, None, ''),
	('Kumo Desu ga, Nani ga? Chapter 134', None, 134.0, None, ''),
	('Kumo Desu ga, Nani ka? Adventurers vs Ogre', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Because I am a teacher', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Before the war', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Blood 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 1-3', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 10', None, 10.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 11', None, 11.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 12', None, 12.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 12-14', None, 12.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 13', None, 13.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 14', None, 14.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 15', None, 15.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 15-16 + Oni 5', None, 15.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 16', None, 16.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 17', None, 17.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 17-18 + Chapter 211', None, 211.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 18', None, 18.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 19', None, 19.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 20', None, 20.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 20-21 + Regular Reports', None, 20.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 21', None, 21.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 22', None, 22.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 23', None, 23.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 23-26', None, 23.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 24', None, 24.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 25', None, 25.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 26', None, 26.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 4', None, 4.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 5', None, 5.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 6', None, 6.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 6-8', None, 6.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 7', None, 7.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 8', None, 8.0, None, ''),
	('Kumo Desu ga, Nani ka? Blood 9', None, 9.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 100', None, 100.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 101', None, 101.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 102', None, 102.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 103', None, 103.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 104', None, 104.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 105', None, 105.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 106', None, 106.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 107', None, 107.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 108', None, 108.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 109', None, 109.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 110', None, 110.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 111', None, 111.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 112', None, 112.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 113', None, 113.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 114', None, 114.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 115', None, 115.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 116', None, 116.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 117', None, 117.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 118', None, 118.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 119', None, 119.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 120', None, 120.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 121', None, 121.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 122', None, 122.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 123', None, 123.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 124', None, 124.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 125', None, 125.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 126', None, 126.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 127', None, 127.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 128', None, 128.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 129', None, 129.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 130', None, 130.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 131', None, 131.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 132', None, 132.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 133', None, 133.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 135', None, 135.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 136', None, 136.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 137', None, 137.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 138', None, 138.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 139', None, 139.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 140', None, 140.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 141', None, 141.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 142', None, 142.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 143', None, 143.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 144', None, 144.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 145', None, 145.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 146', None, 146.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 147', None, 147.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 148', None, 148.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 149', None, 149.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 150', None, 150.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 151', None, 151.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 152', None, 152.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 153', None, 153.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 154', None, 154.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 155', None, 155.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 156', None, 156.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 157', None, 157.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 158', None, 158.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 159', None, 159.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 160', None, 160.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 161', None, 161.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 162', None, 162.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 163', None, 163.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 164', None, 164.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 165', None, 165.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 166', None, 166.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 167', None, 167.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 168', None, 168.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 169', None, 169.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 170', None, 170.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 171', None, 171.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 172', None, 172.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 173', None, 173.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 174', None, 174.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 175', None, 175.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 176', None, 176.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 177', None, 177.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 178', None, 178.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 179', None, 179.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 180', None, 180.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 181', None, 181.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 182', None, 182.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 183', None, 183.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 184', None, 184.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 185', None, 185.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 186', None, 186.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 187', None, 187.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 188', None, 188.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 189', None, 189.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 190', None, 190.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 191', None, 191.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 192', None, 192.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 193', None, 193.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 194', None, 194.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 195', None, 195.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 196', None, 196.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 197', None, 197.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 198', None, 198.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 199', None, 199.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 200', None, 200.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 201', None, 201.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 201-203', None, 201, 203, ''),
	('Kumo Desu ga, Nani ka? Chapter 202', None, 202.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 203', None, 203.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 204', None, 204.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 204-205 + Oni 1 + Character Introduction', None, 204, 205, ''),
	('Kumo Desu ga, Nani ka? Chapter 205', None, 205.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 206', None, 206.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 206-207', None, 206, 207, ''),
	('Kumo Desu ga, Nani ka? Chapter 207', None, 207.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 208', None, 208.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 209', None, 209.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 210', None, 210.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 210 + Oni 4 + Blood 11', None, 210.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 211', None, 211.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 212', None, 212.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 212 + Oni 6 + Blood 19', None, 212.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 86', None, 86.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 87', None, 87.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 88', None, 88.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 89', None, 89.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 90', None, 90.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 91', None, 91.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 92', None, 92.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 93', None, 93.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 94', None, 94.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 95', None, 95.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 96', None, 96.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 97', None, 97.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 98', None, 98.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter 99', None, 99.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter B1', 1, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter B2', 2, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter K1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter K2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S13', 13, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S14', 14, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S15', 15, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S16', 16, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S17', 17, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S19', 19, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S20', 20, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S21', 21, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S22', 22, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S23', 23, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S24', 24, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S25', 25, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S26', 26, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S27', 27, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S28', 28, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter S29', 29, None, None, ''),
	('Kumo Desu ga, Nani ka? Chapter Y2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Character Introduction', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 10', None, 10.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 11', None, 11.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 2-4', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 4', None, 4.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 5', None, 5.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 5-8', None, 5.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 6', None, 6.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 7', None, 7.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 8', None, 8.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 9', None, 9.0, None, ''),
	('Kumo Desu ga, Nani ka? Elf Village Battle 9-11', None, 9.0, None, ''),
	('Kumo Desu ga, Nani ka? Elro Great Labyrinth Abnormality Investigation Team 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Elro Great Labyrinth Abnormality Investigation Team 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Elro Great Labyrinth Abnormality Investigation Team 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? Empire Knights vs Ogre', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Extra 3', None, 3.0, None, 'Extra 3'),
	('Kumo Desu ga, Nani ka? Human-Demon Great War 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Human-Demon Great War 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Human-Demon Great War 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? Human-Demon Great War 4', None, 4.0, None, ''),
	('Kumo Desu ga, Nani ka? Human-Demon Great War 5', None, 5.0, None, ''),
	('Kumo Desu ga, Nani ka? Human-Demon Great War Secret', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Magician, Apprenticeship', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Old Man×2 vs Ogre', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 10', None, 10.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 2 + Blood 4-5', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 3 + Blood 9-10 + Chapter 208-209', None, 208, 209, ''),
	('Kumo Desu ga, Nani ka? Oni 4', None, 4.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 5', None, 5.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 6', None, 6.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 7', None, 7.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 8', None, 8.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 8 + Revolving Lantern + Rumor', None, 8.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 9', None, 9.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni 9 + Sword King and Magician', None, 9.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni vs Oni 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? Oni vs Oni 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? Pope + Oni 7 + Blood 22', None, 7.0, None, ''),
	('Kumo Desu ga, Nani ka? Q&A 10', None, 10.0, None, ''),
	('Kumo Desu ga, Nani ka? Q&A 9', None, 9.0, None, ''),
	('Kumo Desu ga, Nani ka? S18', 18.0, None, None, ''),
	('Kumo Desu ga, Nani ka? SS Christmas', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Searching For Master', None, None, None, ''),
	('Kumo Desu ga, Nani ka? Sword Emperor + Sword God + Oni 10', None, 10.0, None, ''),
	('Kumo Desu ga, Nani ka? Sword God vs Ogre', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Divine Word Religion and the Goddess Religion', None, None, None, ''),
	("Kumo Desu ga, Nani ka? The Labyrinth's Nightmare 1", None, 1.0, None, ''),
	("Kumo Desu ga, Nani ka? The Labyrinth's Nightmare 2", None, 2.0, None, ''),
	("Kumo Desu ga, Nani ka? The Labyrinth's Nightmare 3", None, 3.0, None, ''),
	("Kumo Desu ga, Nani ka? The Labyrinth's Nightmare 4", None, 4.0, None, ''),
	('Kumo Desu ga, Nani ka? The Pope and the Administrator', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Pope and the Ninja', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Pope’s Deliberations', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Pope’s Torment', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Regular Reports of the Demon King and the Administrator', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Revolving Lantern of the Summoner', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Royal Capital Battle 1', None, 1.0, None, ''),
	('Kumo Desu ga, Nani ka? The Royal Capital Battle 2', None, 2.0, None, ''),
	('Kumo Desu ga, Nani ka? The Royal Capital Battle 3', None, 3.0, None, ''),
	('Kumo Desu ga, Nani ka? The Rumor of the Adventurer', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The Sword King and the Magician', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The country of the interstice', None, None, None, ''),
	('Kumo Desu ga, Nani ka? The previous Sword Emperor', None, None, None, ''),
	('Kumo Desu ga, Nani ka? VS Ogre', None, None, None, ''),
	('Kumo desu ga, Nani ka? 217', None, 217.0, None, ''),
	('Kumo desu ga, Nani ka? 218', None, 218.0, None, ''),
	('Kumo desu ga, Nani ka? 219', None, 219.0, None, ''),
	('Kumo desu ga, Nani ka? 220', None, 220.0, None, ''),
	('Kumo desu ga, Nani ka? 221', None, 221.0, None, ''),
	('Kumo desu ga, Nani ka? 222', None, 222.0, None, ''),
	('Kumo desu ga, Nani ka? 223', None, 223.0, None, ''),
	('Kumo desu ga, Nani ka? 224', None, 224.0, None, ''),
	('Kumo desu ga, Nani ka? 225', None, 225.0, None, ''),
	('Kumo desu ga, Nani ka? 226', None, 226.0, None, ''),
	('Kumo desu ga, Nani ka? 227', None, 227.0, None, ''),
	('Kumo desu ga, Nani ka? 228', None, 228.0, None, ''),
	('Kumo desu ga, Nani ka? 229', None, 229.0, None, ''),
	('Kumo desu ga, Nani ka? 230', None, 230.0, None, ''),
	('Kumo desu ga, Nani ka? 231', None, 231.0, None, ''),
	('Kumo desu ga, Nani ka? 232', None, 232.0, None, ''),
	('Kumo desu ga, Nani ka? 233', None, 233.0, None, ''),
	('Kumo desu ga, Nani ka? 234', None, 234.0, None, ''),
	('Kumo desu ga, Nani ka? 235', None, 235.0, None, ''),
	('Kumo desu ga, Nani ka? 236', None, 236.0, None, ''),
	('Kumo desu ga, Nani ka? 237', None, 237.0, None, ''),
	('Kumo desu ga, Nani ka? 238', None, 238.0, None, ''),
	('Kumo desu ga, Nani ka? 239', None, 239.0, None, ''),
	('Kumo desu ga, Nani ka? 240', None, 240.0, None, ''),
	('Kumo desu ga, Nani ka? 241', None, 241.0, None, ''),
	('Kumo desu ga, Nani ka? 242', None, 242.0, None, ''),
	('Kumo desu ga, Nani ka? 243', None, 243.0, None, ''),
	('Kumo desu ga, Nani ka? 244', None, 244.0, None, ''),
	('Kumo desu ga, Nani ka? 245', None, 245.0, None, ''),
	('Kumo desu ga, Nani ka? 246', None, 246.0, None, ''),
	('Kumo desu ga, Nani ka? 247', None, 247.0, None, ''),
	('Kumo desu ga, Nani ka? 248', None, 248.0, None, ''),
	('Kumo desu ga, Nani ka? 249', None, 249.0, None, ''),
	('Kumo desu ga, Nani ka? 250', None, 250.0, None, ''),
	('Kumo desu ga, Nani ka? 251', None, 251.0, None, ''),
	('Kumo desu ga, Nani ka? 252', None, 252.0, None, ''),
	('Kumo desu ga, Nani ka? 253', None, 253.0, None, ''),
	('Kumo desu ga, Nani ka? 254', None, 254.0, None, ''),
	('Kumo desu ga, Nani ka? 255', None, 255.0, None, ''),
	('Kumo desu ga, Nani ka? 256', None, 256.0, None, ''),
	('Kumo desu ga, Nani ka? 257', None, 257.0, None, ''),
	('Kumo desu ga, Nani ka? 258', None, 258.0, None, ''),
	('Kumo desu ga, Nani ka? 259', None, 259.0, None, ''),
	('Kumo desu ga, Nani ka? 260', None, 260.0, None, ''),
	('Kumo desu ga, Nani ka? 261', None, 261.0, None, ''),
	('Kumo desu ga, Nani ka? 262', None, 262.0, None, ''),
	('Kumo desu ga, Nani ka? 263', None, 263.0, None, ''),
	('Kumo desu ga, Nani ka? 264', None, 264.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 27', None, 27.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 28', None, 28.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 29', None, 29.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 30', None, 30.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 31', None, 31.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 32', None, 32.0, None, ''),
	('Kumo desu ga, Nani ka? Blood 33', None, 33.0, None, ''),
	('Kumo desu ga, Nani ka? Dropped', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference – hidden', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ①', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ②', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ③', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ④', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ⑤', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ⑥', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ⑦', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ⑧', None, None, None, ''),
	('Kumo desu ga, Nani ka? Informal Conference ⑨', None, None, None, ''),
	('Kumo desu ga, Nani ka? Oni 11', None, 11.0, None, ''),
	('Kumo desu ga, Nani ka? Oni 12', None, 12.0, None, ''),
	('Kumo desu ga, Nani ka? Oni 13', None, 13.0, None, ''),
	('Kumo desu ga, Nani ka? Oni 14', None, 14.0, None, ''),
	('Kumo desu ga, Nani ka? Oni 15', None, 15.0, None, ''),
	('Kumo desu ga, Nani ka? Oni 16', None, 16.0, None, ''),
	('Kumo desu ga, Nani ka? Oni 17', None, 17.0, None, ''),
	('Kumo desu ga, nani ka? – vampie vs ogre-kun 4', None, 4.0, None, ''),
	('Kumo desu ga, nani ka? – vampie vs ogre-kun vs dragon vs spider vs maou vs…', None, None, None, ''),
	('Kumo?', None, None, None, ''),
	('Kuro  no Maou Chapter 142', None, 142.0, None, ''),
	('Kuro no Hiera Glaphicos - Prelude - Red Dawn', None, None, None, ''),
	('Kuro no Hiera Glaphicos - Volume 1 - Chapter 1 Part 1', 1.0, 1.0, 1.0, ''),
	('Kuro no Maou Chapter 127', None, 127.0, None, ''),
	('Kuro no Maou Chapter 128', None, 128.0, None, ''),
	('Kuro no Maou Chapter 129', None, 129.0, None, ''),
	('Kuro no Maou Chapter 130', None, 130.0, None, ''),
	('Kuro no Maou Chapter 131', None, 131.0, None, ''),
	('Kuro no Maou Chapter 132', None, 132.0, None, ''),
	('Kuro no Maou Chapter 133', None, 133.0, None, ''),
	('Kuro no Maou Chapter 134', None, 134.0, None, ''),
	('Kuro no Maou Chapter 135', None, 135.0, None, ''),
	('Kuro no Maou Chapter 136', None, 136.0, None, ''),
	('Kuro no Maou Chapter 137', None, 137.0, None, ''),
	('Kuro no Maou Chapter 138', None, 138.0, None, ''),
	('Kuro no Maou Chapter 139', None, 139.0, None, ''),
	('Kuro no Maou Chapter 140', None, 140.0, None, ''),
	('Kuro no Maou Chapter 141', None, 141.0, None, ''),
	('Kuro no Maou Chapter 143', None, 143.0, None, ''),
	('Kuro no Maou Chapter 144', None, 144.0, None, ''),
	('Kuro no Maou Chapter 145', None, 145.0, None, ''),
	('Kuro no Maou Chapter 146', None, 146.0, None, ''),
	('Kuro no Maou Chapter 147', None, 147.0, None, ''),
	('Kuro no Maou Chapter 148', None, 148.0, None, ''),
	('Kuro no Maou Chapter 149', None, 149.0, None, ''),
	('Kuro no Maou Chapter 150', None, 150.0, None, ''),
	('Kuro no Maou Chapter 151', None, 151.0, None, ''),
	('Kuro no Maou Chapter 152', None, 152.0, None, ''),
	('Kuro no Maou Chapter 153', None, 153.0, None, ''),
	('Kuro no Maou Chapter 154', None, 154.0, None, ''),
	('Kuro no Maou Chapter 155', None, 155.0, None, ''),
	('Kuro no Maou Chapter 156', None, 156.0, None, ''),
	('Kuro no Maou Chapter 157', None, 157.0, None, ''),
	('Kuro no Maou Chapter 158', None, 158.0, None, ''),
	('Kuro no Maou Chapter 159', None, 159.0, None, ''),
	('Kuro no Maou Chapter 160', None, 160.0, None, ''),
	('Kuro no Maou Chapter 161', None, 161.0, None, ''),
	('Kuro no Maou Chapter 162', None, 162.0, None, ''),
	('Kuro no Maou Chapter 163', None, 163.0, None, ''),
	('Kuro no Maou Chapter 164', None, 164.0, None, ''),
	('Kuro no Maou Chapter 165', None, 165.0, None, ''),
	('Kuro no Maou Chapter 166', None, 166.0, None, ''),
	('Kuro no Maou Chapter 167', None, 167.0, None, ''),
	('Kuro no Maou Chapter 168', None, 168.0, None, ''),
	('Kuro no Maou Chapter 169', None, 169.0, None, ''),
	('Kuro no Maou Chapter 170', None, 170.0, None, ''),
	('Kuro no Maou Chapter 171', None, 171.0, None, ''),
	('Kuro no Maou Chapter 172', None, 172.0, None, ''),
	('Kuro no Maou Chapter 173', None, 173.0, None, ''),
	('Kuro no Maou Chapter 174', None, 174.0, None, ''),
	('Kuro no Maou Chapter 175', None, 175.0, None, ''),
	('Kuro no Maou Chapter 176', None, 176.0, None, ''),
	('Kuro no Maou Chapter 177', None, 177.0, None, ''),
	('Kuro no Maou Chapter 178', None, 178.0, None, ''),
	('Kuro no Maou Chapter 179', None, 179.0, None, ''),
	('Kuro no Maou Chapter 180', None, 180.0, None, ''),
	('Kuro no Maou Chapter 181', None, 181.0, None, ''),
	('Kuro no Maou Chapter 182', None, 182.0, None, ''),
	('Kuro no Maou Chapter 183', None, 183.0, None, ''),
	('Kuro no Maou Chapter 184', None, 184.0, None, ''),
	('Kuro no Maou Chapter 185', None, 185.0, None, ''),
	('Kuro no Maou Chapter 186', None, 186.0, None, ''),
	('Kuro no Maou Chapter 187', None, 187.0, None, ''),
	('Kuro no Maou Chapter 188', None, 188.0, None, ''),
	('Kuro no Maou Chapter 189', None, 189.0, None, ''),
	('Kuro no Maou Chapter 190', None, 190.0, None, ''),
	('Kuro no Maou Chapter 191', None, 191.0, None, ''),
	('Kuro no Maou Chapter 192', None, 192.0, None, ''),
	('Kuro no Maou Chapter 193', None, 193.0, None, ''),
	('Kuro no Maou Chapter 194', None, 194.0, None, ''),
	('Kuro no Maou Chapter 195', None, 195.0, None, ''),
	('Kuro no Maou Chapter 196', None, 196.0, None, ''),
	('Kuro no Maou Chapter 196 & 197', None, 196.0, None, ''),
	('Kuro no Maou Chapter 197', None, 197.0, None, ''),
	('Kuro no Maou Chapter 198', None, 198.0, None, ''),
	('Kuro no Maou Chapter 199', None, 199.0, None, ''),
	('Kuro no Maou Chapter 200', None, 200.0, None, ''),
	('Kuro no Maou Chapter 201', None, 201.0, None, ''),
	('Kuro no Maou Chapter 202', None, 202.0, None, ''),
	('Kuro no Maou Chapter 203', None, 203.0, None, ''),
	('Kuro no Maou Chapter 203 – 204', None, 203.0, None, ''),
	('Kuro no Maou Chapter 204', None, 204.0, None, ''),
	('Kuro no Maou Chapter 205', None, 205.0, None, ''),
	('Kuro no Maou Chapter 206', None, 206.0, None, ''),
	('Kuro no Maou Chapter 207', None, 207.0, None, ''),
	('Kuro no Maou Chapter 208', None, 208.0, None, ''),
	('Kuro no Maou Chapter 209', None, 209.0, None, ''),
	('Kuro no Maou Chapter 210', None, 210.0, None, ''),
	('Kuro no Maou Chapter 211', None, 211.0, None, ''),
	('Kuro no Maou Chapter 212', None, 212.0, None, ''),
	('Kuro no Maou Chapter 213', None, 213.0, None, ''),
	('Kuro no Maou Chapter 214', None, 214.0, None, ''),
	('Kuro no Maou Chapter 215', None, 215.0, None, ''),
	('Kuro no Maou Chapter 216', None, 216.0, None, ''),
	('Kuro no Maou Chapter 216-217', None, 216, 217, ''),
	('Kuro no Maou Chapter 217', None, 217.0, None, ''),
	('Kuro no Maou Chapter 218', None, 218.0, None, ''),
	('Kuro no Maou Chapter 219', None, 219.0, None, ''),
	('Kuro no Maou Chapter 220', None, 220.0, None, ''),
	('Kuro no Maou Chapter 221', None, 221.0, None, ''),
	('Kuro no Maou Chapter 222', None, 222.0, None, ''),
	('Kuro no Maou Chapter 223', None, 223.0, None, ''),
	('Kuro no Maou Chapter 224', None, 224.0, None, ''),
	('Kuro no Maou Chapter 225', None, 225.0, None, ''),
	('Kuro no Maou Chapter 226', None, 226.0, None, ''),
	('Kuro no Maou Chapter 227', None, 227.0, None, ''),
	('Kuro no Maou Chapter 228', None, 228.0, None, ''),
	('Kuro no Maou Chapter 229', None, 229.0, None, ''),
	('Kuro no Maou Chapter 230', None, 230.0, None, ''),
	('Kuro no Maou Chapter 231', None, 231.0, None, ''),
	('Kuro no Maou Chapter 232', None, 232.0, None, ''),
	('Kuro no Maou Chapter 233', None, 233.0, None, ''),
	('Kuro no Maou Chapter 234', None, 234.0, None, ''),
	('Kuro no Maou Chapter 235', None, 235.0, None, ''),
	('Kuro no Maou Chapter 237', None, 237.0, None, ''),
	('Kuro no Maou Chapter 238', None, 238.0, None, ''),
	('Kuro no Maou Chapter 239', None, 239.0, None, ''),
	('Kuro no Maou Chapter 240', None, 240.0, None, ''),
	('Kuro no Maou Chapter 241', None, 241.0, None, ''),
	('Kuro no Maou Chapter 242', None, 242.0, None, ''),
	('Kuro no Maou Chapter 243', None, 243.0, None, ''),
	('Kuro no Maou Chapter 244', None, 244.0, None, ''),
	('Kuro no Maou Chapter 245', None, 245.0, None, ''),
	('Kuro no Maou Chapter 246-247', None, 246, 247, ''),
	('Kuro no Maou Chapter 248', None, 248.0, None, ''),
	('Kuro no Maou Chapter 252', None, 252.0, None, ''),
	('Kuro no Maou Chapter 253', None, 253.0, None, ''),
	('Kuro no Maou Chapter 254 – 255', None, 254.0, None, ''),
	('Kuro no Maou Chapter 256', None, 256.0, None, ''),
	('Kuro no Maou Chapter 257-259', None, 257, 259, ''),
	('Kuro no Maou Chapter 260-262', None, 260, 262, ''),
	('Kuro no Maou Chapter 263 Part 1', None, 263.0, 1.0, ''),
	('Kuro no Maou Chapter 263. Complete chapter!', None, 263.0, None, ''),
	('Kuro no Maou Chapter 264', None, 264.0, None, ''),
	('Kuro no Maou Chapter 265', None, 265.0, None, ''),
	('Kuro no Maou Chapter 266', None, 266.0, None, ''),
	('Kuro no Maou Chapter 266 + Info', None, 266.0, None, ''),
	('Kuro no Maou Chapter 267', None, 267.0, None, ''),
	('Kuro no Maou Chapter 268', None, 268.0, None, ''),
	('Kuro no Maou Chapter 269', None, 269.0, None, ''),
	('Kuro no Maou Chapter 270-272', None, 270, 272, ''),
	('Kuro no Maou Chapter 273-275', None, 273, 275, ''),
	('Kuro no Maou Chapter 276-278', None, 276, 278, ''),
	('Kuro no Maou Chapter 279', None, 279.0, None, ''),
	('Kuro no Maou Chapter 280', None, 280.0, None, ''),
	('Kuro no Maou Chapter 283', None, 283.0, None, ''),
	('Kuro no Maou Chapter 284', None, 284.0, None, ''),
	('Kuro no Maou Chapter 285', None, 285.0, None, ''),
	('Kuro no Maou Chapter 286', None, 286.0, None, ''),
	('Kuro no Maou Chapter Chapter 236', None, 236.0, None, ''),
	('Kuro no Maou Chapters 249 – 251 + info', None, 249.0, None, ''),
	('Kuro no Maou Chapters 281-282', None, 281, 282, ''),
	('Kuro no Seiken Tsukai', None, None, None, ''),
	('Kuro no Shoukanshi – Chapter 12: Conclusion', None, 12.0, None, ''),
	('Kuro no senki Chapter 1 part 1', None, 1.0, 1.0, ''),
	('Kuroyukihime as Mercedes from “Princess Royale”', None, None, None, ''),
	('Kuroyukihime as Mercedes from “Princess Royale” – Collection #2', None, 2.0, None, ''),
	('Kuroyukihime as Mercedes from “Princess Royale” – Collection #3', None, 3.0, None, ''),
	('Kurt Cobain Alive?', None, None, None, ''),
	('Kuusen Madoushi Kouhosei no Kyoukan', None, None, None, ''),
	('Kyoukai Senjou no Horizon', None, None, None, ''),
	('Kyoukai Senjou no Horizon ~Brazilian Portuguese~', None, None, None, ''),
	('Kyoukai Senjou no Horizon:Registration Page', None, None, None, ''),
	('Kyoukai no Kanata PV translations', None, None, None, ''),
	('Kyoukai no Kanata translation', None, None, None, ''),
	('Kyoukai no Kanata volume 1 progress tracker', 1.0, None, None, ''),
	('Kyoukai no Kanata website translations', None, None, None, ''),
	('Kyuuketsu Hime Ch 1 Episode 10', None, 1, 10, ''),
	('Kyuuketsu Hime Ch 1 Episode 11', None, 1, 11, ''),
	('Kyuuketsu Hime Ch 1 Episode 12', None, 1, 12, ''),
	('Kyuuketsu Hime Ch 1 Episode 2', None, 1, 2, ''),
	('Kyuuketsu Hime Ch 1 Episode 3', None, 1, 3, ''),
	('Kyuuketsu Hime Ch 1 Episode 4', None, 1, 4, ''),
	('Kyuuketsu Hime Ch 1 Episode 5', None, 1, 5, ''),
	('Kyuuketsu Hime Ch 1 Episode 6', None, 1, 6, ''),
	('Kyuuketsu Hime Ch 1 Episode 7', None, 1, 7, ''),
	('Kyuuketsu Hime Ch 1 Episode 9', None, 1, 9, ''),
	('Kyuuketsu Hime Ch 1 Interlude 3', None, 1, None, 'Interlude 3'),
	('Kyuuketsu Hime Ch 2 Episode 10', None, 2.0, 10.0, ''),
	('Kyuuketsu Hime Ch 2 Episode 3', None, 2.0, 3.0, ''),
	('Kyuuketsu Hime Ch 2 Episode 4', None, 2.0, 4.0, ''),
	('Kyuuketsu Hime Ch 2 Episode 5', None, 2.0, 5.0, ''),
	('Kyuuketsu Hime Ch 2 Episode 8', None, 2.0, 8.0, ''),
	('Kyuuketsu Hime Ch 2 Interlude 3', None, 2.0, None, 'Interlude 3'),
	('Kyuuketsu Hime Ch 3 Episode 1', None, 3.0, 1.0, ''),
	('Kyuuketsu Hime Ch 3 Episode 5', None, 3.0, 5.0, ''),
	('Kyuuketsu Hime Ch 3 Episode 7', None, 3.0, 7.0, ''),
	('Kyuuketsu Hime Ch 3 Episode 8', None, 3.0, 8.0, ''),
	('Kyuuketsu Hime Ch 3 Episode 9', None, 3.0, 9.0, ''),
	('Kyuuketsu Hime Ch 3 Interlude 2', None, 3.0, None, 'Interlude 2'),
	('Kyuuketsu Hime Ch1 Episode 1', None, 1, 1, ''),
	('Kyuuketsu Hime Ch1 Episode 8', None, 1, 8, ''),
	('Kyuuketsu Hime Ch1 Interlude 1', None, 1, None, 'Interlude 1'),
	('Kyuuketsu Hime Ch1 Interlude 2', None, 1, None, 'Interlude 2'),
	('Kyuuketsu Hime Chapter 2 Episode 2', None, 2, 2, ''),
	('Kyuuketsu Hime Prologue 2', None, 2, None, 'Prologue 2'),
	('Kyuuketsu Hime Prologue 3', None, 3, None, 'Prologue 3'),
	('Kyuuketsu Hime Supplementary – Eternal Horizon Online', None, None, None, ''),
	('Kyuuketsu Hime ch 2 Interlude 1', None, 2.0, None, 'Interlude 1'),
	('Kyuuketsu Hime ch 2 Interlude 3', None, 2.0, None, 'Interlude 3'),
	('Kyuuketsu Hime ch 3 Episode 2', None, 3.0, 2.0, ''),
	('Kyuuketsu hime Ch 2 Episode 13', None, 2.0, 13.0, ''),
	('Kyuuketsuhime Ch 2 Episode 11', None, 2.0, 11.0, ''),
	('Kyuuketsuki Hajimeru Vol.1 – Chapter 1', 1.0, 1.0, None, ''),
	('Kyuuketsuki Hajimeru Vol.1 – Chapter 2', 1.0, 2.0, None, ''),
	('kats bored night', None, None, None, ''),
	('kudarajin', None, None, None, ''),
]

