

data = [
	('XJ Log 21 – XCrossJ and Bullet', None, 21.0, None, ''),
	('XJ Log 22 – XCrossJ and the Power to Kill', None, 22.0, None, ''),
	('XJ Log 23 – XCrossJ and the Power of the Copy Cat', None, 23.0, None, ''),
	('XJ Log 24 – The One Left Behind and the Blue Haired Youth', None, 24.0, None, ''),
	('XJ Log 25 – XCrossJ and the Marionette', None, 25.0, None, ''),
	('XJ Log 26 – XCrossJ and the Girl of Innocence', None, 26.0, None, ''),
	('XJ Log 27 – XCrossJ, Nobles, and the Red Cat', None, 27.0, None, ''),
	('XJ Log 28 – XCrossJ and his Weakness', None, 28.0, None, ''),
	('XJ Log 29 – XCrossJ, the kitty, and the Silver Saviour', None, 29.0, None, ''),
	('XJ Log 29.5 – Brewing Turmoil', None, 29.5, None, ''),
	('XJ Log 30 – XCrossJ and the Doctor', None, 30.0, None, ''),
	('XJ Log 31 – Pearl and Silvia', None, 31.0, None, ''),
	('XJ Log 32 – XCrossJ and the Extremely Innocent One', None, 32.0, None, ''),
	('XJ Log 33 – XCrossJ and the Power of Music', None, 33.0, None, ''),
	('XJ Log 34 – XCrossJ and the First Invader', None, 34.0, None, ''),
	('XJ Log 35 – Pearl, XCrossJ, and Lunch?', None, 35.0, None, ''),
	('XJ Log 36 – XCrossJ and the ones who are In The Dark', None, 36.0, None, ''),
	('XJ Log 37 – XCrossJ and the Disrupted Lull', None, 37.0, None, ''),
	('XJ Log 38 – XCrossJ and the Hunted', None, 38.0, None, ''),
	('XJ Log 39 – XCrossJ and those who are Wounded', None, 39.0, None, ''),
	('XJ Log 39.5 – Reasons and Responsibilities', None, 39.5, None, ''),
	('XJ Log 40 – XCrossJ and Negotiations', None, 40.0, None, ''),
	('XJ Log 41 – XCrossJ and the Undesirable Development', None, 41.0, None, ''),
	('XJ Log 42 – XCrossJ, Battle Gear, and the Wonders of Cosplay', None, 42.0, None, ''),
	('XJ Log 43 – XCrossJ’s Grind and Pearl’s Secret?', None, 43.0, None, ''),
	('XJ Log 43.5 – Convictions and Contradictions', None, 43.5, None, ''),
	('XJ Log 44 – XCrossJ and the Things That Can’t Be Taken Back', None, 44.0, None, ''),
	('XJ Log 44.5 – Truth Hidden Within Lies', None, 44.5, None, ''),
	('XJAM: Shirushi (Test)', None, None, None, ''),
	('XQW – Chapter Eight', None, 8, None, ''),
	('XQW – Chapter Five', None, 5, None, ''),
	('XQW – Chapter Four', None, 4, None, ''),
	('XQW – Chapter One', None, 1, None, ''),
	('XQW – Chapter Seven', None, 7, None, ''),
	('XQW – Chapter Six', None, 6, None, ''),
	('XQW – Chapter Three', None, 3, None, ''),
	('XQW – Chapter Two', None, 2, None, ''),
	('XQW – Side Story Six (Part 1)', None, None, 1.0, 'Side Story Six (Part 1)'),
	('XQW – Side Story Six (Part 2)', None, None, 2.0, 'Side Story Six (Part 2)'),
	('XWE Chapter 1', None, 1.0, None, ''),
	('XWE Chapter 2', None, 2.0, None, ''),
	('XWE Chapter 3', None, 3.0, None, ''),
	('XWE Chapter 4', None, 4.0, None, ''),
	('XWE Chapter 5', None, 5.0, None, ''),
	('Xant & Solistia – The Podcast', None, None, None, ''),
	('Xero Arc 3 Chapter 6 is up !', 3.0, 6.0, None, ''),
	('Xero’s current stats and skills', None, None, None, ''),
	('Xian NI Chapter 125 – Ji Realm Divine Consciousness', None, 125, None, ''),
	('Xian Ni 267 and 268', None, 267.0, None, ''),
	('Xian Ni Chaper 184 Release!', None, 184.0, None, ''),
	('Xian Ni Chapter 100 – Refining the Sheath', None, 100, None, ''),
	('Xian Ni Chapter 101 – Soul Jade Strip', None, 101, None, ''),
	('Xian Ni Chapter 104 – Calamity Mourn (Final)', None, 104, None, ''),
	('Xian Ni Chapter 106 – Rank', None, 106, None, ''),
	('Xian Ni Chapter 107 – Shining Grains', None, 107, None, ''),
	('Xian Ni Chapter 108 – Old Acquaintance', None, 108, None, ''),
	('Xian Ni Chapter 11-14 release!', None, 11, 14, ''),
	('Xian Ni Chapter 110 – Liu Mei', None, 110, None, ''),
	('Xian Ni Chapter 112', None, 112, None, ''),
	('Xian Ni Chapter 114', None, 114, None, ''),
	('Xian Ni Chapter 115', None, 115, None, ''),
	('Xian Ni Chapter 117 – Death of Wang Lin', None, 117, None, ''),
	('Xian Ni Chapter 118 – Foreign Battlefield', None, 118, None, ''),
	('Xian Ni Chapter 119 – Soul Awakens', None, 119, None, ''),
	('Xian Ni Chapter 120 – Return of Wang Lin', None, 120, None, ''),
	('Xian Ni Chapter 121 – Acting Recklessly', None, 121, None, ''),
	('Xian Ni Chapter 122 – Kill Him', None, 122, None, ''),
	('Xian Ni Chapter 123 – Devil', None, 123, None, ''),
	('Xian Ni Chapter 124 – Law of the World', None, 124, None, ''),
	('Xian Ni Chapter 126 – A Foreign Country', None, 126, None, ''),
	('Xian Ni Chapter 127 – Volcano Closed-Door Practise', None, 127, None, ''),
	('Xian Ni Chapter 128 – Burning Gold Mountain Range', None, 128, None, ''),
	('Xian Ni Chapter 129 – Homemade Devil', None, 129, None, ''),
	('Xian Ni Chapter 130 – Sudden Arrival of a YuanYing', None, 130, None, ''),
	('Xian Ni Chapter 132 – Upheaval in Huo Fen Country (1)', None, 132, None, ''),
	('Xian Ni Chapter 133 – Upheaval in Huo Fen Country (2)', None, 133, None, ''),
	('Xian Ni Chapter 134 – Nationwide Migration', None, 134, None, ''),
	('Xian Ni Chapter 135 – Drastic Changes', None, 135, None, ''),
	('Xian Ni Chapter 136 – Middle Aged Man', None, 136, None, ''),
	('Xian Ni Chapter 137 – Country Wide Sealing Formation', None, 137, None, ''),
	('Xian Ni Chapter 14 – Unusual Transformation', None, 14, None, ''),
	('Xian Ni Chapter 141-145', None, 141, 145, ''),
	('Xian Ni Chapter 15 – Suspicion', None, 15, None, ''),
	('Xian Ni Chapter 150 – Kill', None, 150.0, None, ''),
	('Xian Ni Chapter 151 – Ten Thousand Devils Hundred Days Killing Warrant', None, 151.0, None, ''),
	('Xian Ni Chapter 152 – Bloody Killing Expedition Trail', None, 152.0, None, ''),
	('Xian Ni Chapter 153 – NanDou Overwhelmed', None, 153.0, None, ''),
	('Xian Ni Chapter 154 – Battle Dragon Great Formation', None, 154.0, None, ''),
	('Xian Ni Chapter 155 – Sword Cultivation Afterimage', None, 155.0, None, ''),
	('Xian Ni Chapter 156 – His Struggle', None, 156.0, None, ''),
	('Xian Ni Chapter 157 – A Sad and Beautiful Complexion', None, 157.0, None, ''),
	('Xian Ni Chapter 158 – Sea of Mists', None, 158.0, None, ''),
	('Xian Ni Chapter 159 – Blue Robed Old Man', None, 159.0, None, ''),
	('Xian Ni Chapter 16 Release', None, 16.0, None, ''),
	('Xian Ni Chapter 16 – Disciple', None, 16, None, ''),
	('Xian Ni Chapter 160 – Cultivation Dan', None, 160.0, None, ''),
	('Xian Ni Chapter 161 – Octopus Divine Consciousness', None, 161.0, None, ''),
	('Xian Ni Chapter 162 – Reaching an Agreement', None, 162.0, None, ''),
	('Xian Ni Chapter 163 – Shen Dao Technique', None, 163.0, None, ''),
	('Xian Ni Chapter 164 – Mysterious Corpse', None, 164.0, None, ''),
	('Xian Ni Chapter 165 – Palpitating with Eagerness', None, 165.0, None, ''),
	('Xian Ni Chapter 166 – Ancient Transfer Formation', None, 166.0, None, ''),
	('Xian Ni Chapter 167 – Gathering of Devils', None, 167.0, None, ''),
	('Xian Ni Chapter 168 – Land of the Ancient God', None, 168.0, None, ''),
	('Xian Ni Chapter 169 – Obtaining the Marrow', None, 169.0, None, ''),
	('Xian Ni Chapter 17 release', None, 17.0, None, ''),
	('Xian Ni Chapter 17 – XiuXian', None, 17, None, ''),
	('Xian Ni Chapter 170 – Breaking off from the party', None, 170.0, None, ''),
	('Xian Ni Chapter 171 – The Jade Strip left behind by Li Mu Wan', None, 171.0, None, ''),
	('Xian Ni Chapter 172 – Earth Domain', None, 172.0, None, ''),
	('Xian Ni Chapter 173 – The Second Devil', None, 173.0, None, ''),
	('Xian Ni Chapter 174 – Devil Mutation', None, 174.0, None, ''),
	('Xian Ni Chapter 175 – Scrambling for Treasure', None, 175.0, None, ''),
	('Xian Ni Chapter 176 – Capturing the Group of Hurricanes', None, 176.0, None, ''),
	('Xian Ni Chapter 177 – Poison King Cauldron', None, 177.0, None, ''),
	('Xian Ni Chapter 178 – Mountain of Restrictions', None, 178.0, None, ''),
	('Xian Ni Chapter 179 – Studying the Restrictions', None, 179.0, None, ''),
	('Xian Ni Chapter 18 & 19 Release', None, 18.0, None, ''),
	('Xian Ni Chapter 18 – Bottle Gourd', None, 18, None, ''),
	('Xian Ni Chapter 183', None, 183.0, None, ''),
	('Xian Ni Chapter 185 & 186 Release', None, 185.0, None, ''),
	('Xian Ni Chapter 187 Release', None, 187.0, None, ''),
	('Xian Ni Chapter 188 Release', None, 188.0, None, ''),
	('Xian Ni Chapter 189 & 190 Release', None, 189.0, None, ''),
	('Xian Ni Chapter 19 – By the Door', None, 19, None, ''),
	('Xian Ni Chapter 191 Release', None, 191.0, None, ''),
	('Xian Ni Chapter 192 & 28 Release!', None, 192.0, None, ''),
	('Xian Ni Chapter 193 Release', None, 193.0, None, ''),
	('Xian Ni Chapter 194 Release', None, 194.0, None, ''),
	('Xian Ni Chapter 195 Release!', None, 195.0, None, ''),
	('Xian Ni Chapter 196 Release!', None, 196.0, None, ''),
	('Xian Ni Chapter 197 Release!', None, 197.0, None, ''),
	('Xian Ni Chapter 198 Release!', None, 198.0, None, ''),
	('Xian Ni Chapter 199 Release!', None, 199.0, None, ''),
	('Xian Ni Chapter 20 & 21 Release!', None, 20.0, None, ''),
	('Xian Ni Chapter 20 – Nine Clouds', None, 20, None, ''),
	('Xian Ni Chapter 200 & 201 Release', None, 200.0, None, ''),
	('Xian Ni Chapter 202 Release', None, 202.0, None, ''),
	('Xian Ni Chapter 203 Release!', None, 203.0, None, ''),
	('Xian Ni Chapter 204 & 205 Release!', None, 204.0, None, ''),
	('Xian Ni Chapter 206 Release!', None, 206.0, None, ''),
	('Xian Ni Chapter 207 First Half Release!', None, 207.0, None, ''),
	('Xian Ni Chapter 207 Second Half Release!', None, 207.0, None, ''),
	('Xian Ni Chapter 208 First Half Release!', None, 208.0, None, ''),
	('Xian Ni Chapter 208 Second Half Release!', None, 208.0, None, ''),
	('Xian Ni Chapter 209 Release!', None, 209.0, None, ''),
	('Xian Ni Chapter 21 – Gaining Pills', None, 21, None, ''),
	('Xian Ni Chapter 210 Release!', None, 210.0, None, ''),
	('Xian Ni Chapter 211 release!', None, 211.0, None, ''),
	('Xian Ni Chapter 212 Release!', None, 212.0, None, ''),
	('Xian Ni Chapter 213 First Half Release!', None, 213.0, None, ''),
	('Xian Ni Chapter 213 full release', None, 213.0, None, ''),
	('Xian Ni Chapter 214 Release', None, 214.0, None, ''),
	('Xian Ni Chapter 215 Release!', None, 215.0, None, ''),
	('Xian Ni Chapter 216 Release!', None, 216.0, None, ''),
	('Xian Ni Chapter 217 Release', None, 217.0, None, ''),
	('Xian Ni Chapter 218 Release', None, 218.0, None, ''),
	('Xian Ni Chapter 219 Release!', None, 219.0, None, ''),
	('Xian Ni Chapter 22 Release', None, 22.0, None, ''),
	('Xian Ni Chapter 22 – Scattered Power', None, 22, None, ''),
	('Xian Ni Chapter 220 Release', None, 220.0, None, ''),
	('Xian Ni Chapter 221 Release!', None, 221.0, None, ''),
	('Xian Ni Chapter 222 Release', None, 222.0, None, ''),
	('Xian Ni Chapter 223 Release', None, 223.0, None, ''),
	('Xian Ni Chapter 224 Release', None, 224.0, None, ''),
	('Xian Ni Chapter 225 Release', None, 225.0, None, ''),
	('Xian Ni Chapter 226 Second Half', None, 226.0, None, ''),
	('Xian Ni Chapter 227 Release', None, 227.0, None, ''),
	('Xian Ni Chapter 228 Release', None, 228.0, None, ''),
	('Xian Ni Chapter 229 Release!', None, 229.0, None, ''),
	('Xian Ni Chapter 23 Release', None, 23.0, None, ''),
	('Xian Ni Chapter 23 – Ten Clouds', None, 23, None, ''),
	('Xian Ni Chapter 230 First Half!', None, 230.0, None, ''),
	('Xian Ni Chapter 230 Fixed Release!', None, 230.0, None, ''),
	('Xian Ni Chapter 230 Part 2 Release!', None, 230.0, 2.0, ''),
	('Xian Ni Chapter 231 Release!', None, 231.0, None, ''),
	('Xian Ni Chapter 232 Release!', None, 232.0, None, ''),
	('Xian Ni Chapter 233 Release!', None, 233.0, None, ''),
	('Xian Ni Chapter 234', None, 234.0, None, ''),
	('Xian Ni Chapter 235 Release!', None, 235.0, None, ''),
	('Xian Ni Chapter 236 Release!', None, 236.0, None, ''),
	('Xian Ni Chapter 237 Part 1', None, 237.0, 1.0, ''),
	('Xian Ni Chapter 237 Part 2', None, 237.0, 2.0, ''),
	('Xian Ni Chapter 238 Release!', None, 238.0, None, ''),
	('Xian Ni Chapter 239 Release!', None, 239.0, None, ''),
	('Xian Ni Chapter 24 Release', None, 24.0, None, ''),
	('Xian Ni Chapter 24 – Practice', None, 24, None, ''),
	('Xian Ni Chapter 240 Release!', None, 240.0, None, ''),
	('Xian Ni Chapter 242 Release!', None, 242.0, None, ''),
	('Xian Ni Chapter 243 Release!', None, 243.0, None, ''),
	('Xian Ni Chapter 244 Release!', None, 244.0, None, ''),
	('Xian Ni Chapter 245 Release!', None, 245.0, None, ''),
	('Xian Ni Chapter 246&247 Release!', None, 246.0, None, ''),
	('Xian Ni Chapter 248 Release!', None, 248.0, None, ''),
	('Xian Ni Chapter 249 Release', None, 249.0, None, ''),
	('Xian Ni Chapter 25 – Concentrating Qi', None, 25, None, ''),
	('Xian Ni Chapter 25-27 Release', None, 25, 27, ''),
	('Xian Ni Chapter 251 Release!', None, 251.0, None, ''),
	('Xian Ni Chapter 252 Release', None, 252.0, None, ''),
	('Xian Ni Chapter 253 Release!', None, 253.0, None, ''),
	('Xian Ni Chapter 254 Release', None, 254.0, None, ''),
	('Xian Ni Chapter 255 Release', None, 255.0, None, ''),
	('Xian Ni Chapter 256 Release!', None, 256.0, None, ''),
	('Xian Ni Chapter 257 Release (Unedited)', None, 257.0, None, ''),
	('Xian Ni Chapter 258 Release (Unedited)', None, 258.0, None, ''),
	('Xian Ni Chapter 259&260 Release!', None, 259.0, None, ''),
	('Xian Ni Chapter 26 – Malice', None, 26, None, ''),
	('Xian Ni Chapter 261 Release!', None, 261.0, None, ''),
	('Xian Ni Chapter 262 Release!', None, 262.0, None, ''),
	('Xian Ni Chapter 263 Release!', None, 263.0, None, ''),
	('Xian Ni Chapter 264 (Unedited)', None, 264.0, None, ''),
	('Xian Ni Chapter 265 Release', None, 265.0, None, ''),
	('Xian Ni Chapter 266 Release (Unedited)', None, 266.0, None, ''),
	('Xian Ni Chapter 269', None, 269.0, None, ''),
	('Xian Ni Chapter 27 – A Visit', None, 27, None, ''),
	('Xian Ni Chapter 27 – Visit (Real)', None, 27, None, ''),
	('Xian Ni Chapter 270 Release!', None, 270.0, None, ''),
	('Xian Ni Chapter 271 Release!', None, 271.0, None, ''),
	('Xian Ni Chapter 28 – Chores', None, 28, None, ''),
	('Xian Ni Chapter 29 Release', None, 29.0, None, ''),
	('Xian Ni Chapter 29 – Locked Door', None, 29, None, ''),
	('Xian Ni Chapter 30 Release!', None, 30.0, None, ''),
	('Xian Ni Chapter 30 – Wang Hao', None, 30, None, ''),
	('Xian Ni Chapter 31', None, 31.0, None, ''),
	('Xian Ni Chapter 31 – Snow Water', None, 31, None, ''),
	('Xian Ni Chapter 32 – Trades', None, 32, None, ''),
	('Xian Ni Chapter 32-36 Release', None, 32, 36, ''),
	('Xian Ni Chapter 33 – Chants', None, 33, None, ''),
	('Xian Ni Chapter 34 – Training', None, 34, None, ''),
	('Xian Ni Chapter 35 – Back Side of the Mountain', None, 35, None, ''),
	('Xian Ni Chapter 36 – Quarrel', None, 36, None, ''),
	('Xian Ni Chapter 37 – Four Years', None, 37, None, ''),
	('Xian Ni Chapter 37-40 Release', None, 37, 40, ''),
	('Xian Ni Chapter 38 – Facula', None, 38, None, ''),
	('Xian Ni Chapter 39 – Wealthy', None, 39, None, ''),
	('Xian Ni Chapter 41-50 Release!', None, 41, 50, ''),
	('Xian Ni Chapter 42 – Centipede Poison', None, 42, None, ''),
	('Xian Ni Chapter 43 – Old Friends', None, 43, None, ''),
	('Xian Ni Chapter 48 – Exchange (2)', None, 48, None, ''),
	('Xian Ni Chapter 49 – Exchange (3)', None, 49, None, ''),
	('Xian Ni Chapter 50 – Exchange (4)', None, 50, None, ''),
	('Xian Ni Chapter 51 Release!', None, 51.0, None, ''),
	('Xian Ni Chapter 51 – Entering the Stage', None, 51, None, ''),
	('Xian Ni Chapter 52 Release', None, 52.0, None, ''),
	('Xian Ni Chapter 52 – Entering the Stage (2)', None, 52, None, ''),
	('Xian Ni Chapter 53 Release!', None, 53.0, None, ''),
	('Xian Ni Chapter 53 – Entering the Stage (3)', None, 53, None, ''),
	('Xian Ni Chapter 54 – Entering the Stage (4)', None, 54, None, ''),
	('Xian Ni Chapter 55 – Entering the Stage (5)', None, 55, None, ''),
	('Xian Ni Chapter 56 – Entering the Stage (6)', None, 56, None, ''),
	('Xian Ni Chapter 58 – Conclude', None, 58, None, ''),
	('Xian Ni Chapter 61 – Ancestors', None, 61, None, ''),
	('Xian Ni Chapter 63 – Powerful', None, 63, None, ''),
	('Xian Ni Chapter 66', None, 66, None, ''),
	('Xian Ni Chapter 67', None, 67, None, ''),
	('Xian Ni Chapter 68', None, 68, None, ''),
	('Xian Ni Chapter 69', None, 69, None, ''),
	('Xian Ni Chapter 71 – Four Years', None, 71, None, ''),
	('Xian Ni Chapter 72 – Seizing Foundation', None, 72, None, ''),
	('Xian Ni Chapter 73 – Tian Shui City', None, 73, None, ''),
	('Xian Ni Chapter 74 – Plague of Blood', None, 74, None, ''),
	('Xian Ni Chapter 75 – Meeting again an old friend', None, 75, None, ''),
	('Xian Ni Chapter 76 – Weird Flying Sword', None, 76, None, ''),
	('Xian Ni Chapter 77 – JiMo Old Man', None, 77, None, ''),
	('Xian Ni Chapter 81 – Seizing Foundation (1)', None, 81, None, ''),
	('Xian Ni Chapter 83 – Seizing Foundation (3)', None, 83, None, ''),
	('Xian Ni Chapter 86 – Forest Ruins', None, 86, None, ''),
	('Xian Ni Chapter 87 – Abyssal Cold Dan', None, 87, None, ''),
	('Xian Ni Chapter 88 – Blue Skinned Weird Person', None, 88, None, ''),
	('Xian Ni Chapter 89 – Intimidating Magic Weapon', None, 89, None, ''),
	('Xian Ni Chapter 9 & 10 double release!!!', None, 9.0, None, ''),
	('Xian Ni Chapter 90 – First Indications', None, 90, None, ''),
	('Xian Ni Chapter 91 – Ji Yin Spiritual Force', None, 91, None, ''),
	('Xian Ni Chapter 92 – Corpse Yin Sect (1)', None, 92, None, ''),
	('Xian Ni Chapter 94 – Corpse Yin Sect (3)', None, 94, None, ''),
	('Xian Ni Chapter 95 – Entering the Sect', None, 95, None, ''),
	('Xian Ni Chapter 97 – Great Changes', None, 97, None, ''),
	('Xian Ni Chapter 97 – Preface to Foreign Battlefield', None, 97, None, ''),
	('Xian Ni Chapter 99 -Stone Bead Changes', None, 99, None, ''),
	('Xian Ni Chatper 226 First Half Release', None, 226.0, None, ''),
	('Xian Ni chapter 250 Release!', None, 250.0, None, ''),
	('Xian ni Chapter 105 – Ji Realm of the Past Era', None, 105, None, ''),
	('Xian ni Chapter 109', None, 109, None, ''),
	('Xianxia’s Working Emperor', None, None, None, ''),
	('Xiu Luo Zhan Shen—Glossary', None, None, None, ''),
	('Xray Chapter', None, None, None, ''),
	('Xray Chapter 1', None, 1.0, None, ''),
	('Xray Chapter 10', None, 10.0, None, ''),
	('Xray Chapter 11', None, 11.0, None, ''),
	('Xray Chapter 12', None, 12.0, None, ''),
	('Xray Chapter 13', None, 13.0, None, ''),
	('Xray Chapter 14', None, 14.0, None, ''),
	('Xray Chapter 15', None, 15.0, None, ''),
	('Xray Chapter 16', None, 16.0, None, ''),
	('Xray Chapter 17', None, 17.0, None, ''),
	('Xray Chapter 18', None, 18.0, None, ''),
	('Xray Chapter 19', None, 19.0, None, ''),
	('Xray Chapter 2', None, 2.0, None, ''),
	('Xray Chapter 20', None, 20.0, None, ''),
	('Xray Chapter 21', None, 21.0, None, ''),
	('Xray Chapter 22', None, 22.0, None, ''),
	('Xray Chapter 23', None, 23.0, None, ''),
	('Xray Chapter 24', None, 24.0, None, ''),
	('Xray Chapter 25', None, 25.0, None, ''),
	('Xray Chapter 26', None, 26.0, None, ''),
	('Xray Chapter 27', None, 27.0, None, ''),
	('Xray Chapter 28', None, 28.0, None, ''),
	('Xray Chapter 29', None, 29.0, None, ''),
	('Xray Chapter 3', None, 3.0, None, ''),
	('Xray Chapter 30', None, 30.0, None, ''),
	('Xray Chapter 31', None, 31.0, None, ''),
	('Xray Chapter 32', None, 32.0, None, ''),
	('Xray Chapter 33', None, 33.0, None, ''),
	('Xray Chapter 34', None, 34.0, None, ''),
	('Xray Chapter 36', None, 36.0, None, ''),
	('Xray Chapter 37', None, 37.0, None, ''),
	('Xray Chapter 38', None, 38.0, None, ''),
	('Xray Chapter 39', None, 39.0, None, ''),
	('Xray Chapter 4', None, 4.0, None, ''),
	('Xray Chapter 40', None, 40.0, None, ''),
	('Xray Chapter 41', None, 41.0, None, ''),
	('Xray Chapter 42', None, 42.0, None, ''),
	('Xray Chapter 43', None, 43.0, None, ''),
	('Xray Chapter 5', None, 5.0, None, ''),
	('Xray Chapter 6', None, 6.0, None, ''),
	('Xray Chapter 7', None, 7.0, None, ''),
	('Xray Chapter 8', None, 8.0, None, ''),
	('Xray Chapter 9', None, 9.0, None, ''),
	('Xu Yun vs Cops', None, None, None, ''),
	('Xuan Yuan Sword 3: Rift of the Sky Review', None, 3.0, None, ''),
	('xXCONTESTXx', None, None, None, ''),
]

