

data = [
	('1 Chapter', None, 1.0, None, ''),
	('1 Chapter (JS)', None, 1.0, None, ''),
	('1 Chapter (KS)', None, 1.0, None, ''),
	('1 Chapter (KS, JS)', None, 1.0, None, ''),
	('1 Chapter (SSK)', None, 1.0, None, ''),
	('1 Chapter (SW)', None, 1.0, None, ''),
	('1 September is public holiday', None, 1.0, None, ''),
	('1 Year Anniversary', None, 1.0, None, ''),
	('1 Year Anniversary + Bonus Chapter', None, 1.0, None, ''),
	('1 day delay', None, 1.0, None, ''),
	('1 week hiatus', None, 1.0, None, ''),
	('1 year anniversary', None, 1.0, None, ''),
	('1 year anniversary!', None, 1.0, None, ''),
	('1). Sharing your Work with readers and 2). Fanfic On The Sphere?', None, 1.0, None, ''),
	('1+1/2+1/2 = 2 whole chapters…Right?', None, 1.0, None, ''),
	('1,000,000 Pageviews!', None, 1.0, None, ''),
	('1,000,000 Views Special', None, 1, None, ''),
	('1-0 w/ tln', None, 1.0, None, ''),
	('1-0 w/o tln', None, 1.0, None, ''),
	('1-1', None, 1.0, 1.0, ''),
	('1-2', None, 1.0, 2.0, ''),
	('1-Day Raincheck', None, 1.0, None, ''),
	('1. Chapter 1: Girl Trouble', None, 1.0, None, ''),
	('1. I wandered into a different world  labyrinth', None, 1.0, None, ''),
	('1.- The egg that walks.', None, 1.0, None, ''),
	('1.000.000 + rants', None, None, None, ''),
	('1.01 – Beatus… {Happy…}', None, 1.01, None, ''),
	('1.02 – Munera {Gifts}', None, 1.02, None, ''),
	('1.03 – Problems {Quaestio}', None, 1.03, None, ''),
	('1.04 – Loquitur Nocte {Discussions in the Night}', None, 1.04, None, ''),
	('1.05 – Extendentes Alas {Spreading Wings}', None, 1.05, None, ''),
	('1.3', None, 1.3, None, ''),
	('1.4', None, 1.4, None, ''),
	('1.5', None, 1.5, None, ''),
	('1.5 Chapters', None, 1.5, None, ''),
	('1.5 Chapters (SW, KS)', None, 1.5, None, ''),
	('1.5 chapters.', None, 1.5, None, ''),
	('1.6', None, 1.6, None, ''),
	('1.7', None, 1.7, None, ''),
	('1/2 Kuang Shen Chapter + 1 Jiu Shen Chapter + 1 Sheng Wang chapter!', None, 1.0, None, ''),
	('1/2 Year Review', None, 1.0, None, ''),
	('10', None, 10.0, None, ''),
	('10 Good Questions', None, 10.0, None, ''),
	('10 Years? Sweet Jesus… I need a life…', None, 10.0, None, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Bulletin Board Interlude 1', None, 10.0, None, 'Interlude 1'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Epilogue', None, 1.0, None, 'Epilogue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 5', None, 1.0, 5.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 6', None, 1.0, 6.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 7', None, 1.0, 7.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 8', None, 1.0, 8.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 9', None, 1.0, 9.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Epilogue', None, 2.0, None, 'Epilogue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 1', None, 2.0, 1.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 10', None, 2.0, 10.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 11', None, 2.0, 11.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 12', None, 2.0, 12.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 2', None, 2.0, 2.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 3', None, 2.0, 3.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 4', None, 2.0, 4.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 5', None, 2.0, 5.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 6', None, 2.0, 6.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 7', None, 2.0, 7.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 8', None, 2.0, 8.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 2 - Part 9', None, 2.0, 9.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Epilogue', None, 3.0, None, 'Epilogue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Part 1', None, 3.0, 1.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Part 2', None, 3.0, 2.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Part 3', None, 3.0, 3.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Part 4', None, 3.0, 4.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Part 5', None, 3.0, 5.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Part 6', None, 3.0, 6.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 3 - Prologue', None, 3.0, None, 'Prologue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Chapter 1', None, 4.0, None, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Chapter 2', None, 4.0, None, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Chapter 3', None, 4.0, None, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Chapter 4', None, 4.0, None, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Chapter 6', None, 4.0, None, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Epilogue', None, 4.0, None, 'Epilogue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Part 10', None, 4.0, 10.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Part 11', None, 4.0, 11.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Part 7', None, 4.0, 7.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Part 8', None, 4.0, 8.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Part 9', None, 4.0, 9.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 4 - Prologue', None, 4.0, None, 'Prologue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Epilogue', None, 5.0, None, 'Epilogue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 1', None, 5.0, 1.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 10', None, 5.0, 10.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 11', None, 5.0, 11.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 2', None, 5.0, 2.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 3', None, 5.0, 3.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 4', None, 5.0, 4.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 5', None, 5.0, 5.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 6', None, 5.0, 6.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 7', None, 5.0, 7.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 8', None, 5.0, 8.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Part 9', None, 5.0, 9.0, ''),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 5 Prologue', None, 5.0, None, 'Prologue'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Interlude 2-13', None, 10.0, None, 'Interlude 2-13'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Interlude 3-8', None, 10.0, None, 'Interlude 3-8'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Interlude 3-9', None, 10.0, None, 'Interlude 3-9'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Interlude 5-12', None, 10.0, None, 'Interlude 5-12'),
	('10 nen goshi no HikiNEET o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Interlude 5-13', None, 10.0, None, 'Interlude 5-13'),
	('10 nen goshi no HikiNiito o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 1.', None, 1.0, 1.0, ''),
	('10 nen goshi no HikiNiito o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 2.', None, 1.0, 2.0, ''),
	('10 nen goshi no HikiNiito o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 3', None, 1.0, 3.0, ''),
	('10 nen goshi no HikiNiito o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Chapter 1 - Part 4', None, 1.0, 4.0, ''),
	('10 nen goshi no HikiNiito o Yamete Gaishutsushitara Jitaku goto Isekai ni Ten’ishiteta. Prologue', None, 10.0, None, 'Prologue'),
	('10 | 4 : The Tranquil Village', None, 10.0, None, ''),
	('10 – Hungry Wolf Hunt', None, 10.0, None, ''),
	('10 – Measure of a Man', None, 10.0, None, ''),
	('10,000,000 total page views', None, 10.0, None, ''),
	('10.1 Resurgence', None, 10.1, None, ''),
	('10.10 Interlude (Gentleman)', None, 10.1, None, 'Interlude (Gentleman)'),
	('10.11 Interlude (Overdrive) – part 1', None, 10.11, 1.0, 'Interlude (Overdrive) – part 1'),
	('10.11 Interlude (Overdrive) – part 2', None, 10.11, 2.0, 'Interlude (Overdrive) – part 2'),
	('10.11 Interlude (Overdrive) – part 3', None, 10.11, 3.0, 'Interlude (Overdrive) – part 3'),
	('10.2 Resurgence', None, 10.2, None, ''),
	('10.3 Resurgence', None, 10.3, None, ''),
	('10.4 Resurgence', None, 10.4, None, ''),
	('10.5 Resurgence', None, 10.5, None, ''),
	('10.6 Resurgence', None, 10.6, None, ''),
	('10.7 Resurgence', None, 10.7, None, ''),
	('10.8 Resurgence', None, 10.8, None, ''),
	('10.9 Migration', None, 10.9, None, ''),
	('10.9 Resurgence', None, 10.9, None, ''),
	('10/01/2016', None, None, None, ''),
	('10/06/2015', None, None, None, ''),
	('10/11 – That which is left', None, 10.0, None, ''),
	('100 Chapter Milestone!', None, 100.0, None, ''),
	('100 Years Of Martial Arts. WN or LN?', None, 100, None, ''),
	('100 Years of Martial Arts – Chapter 2 Finished (╯°□°）╯︵ ┻━┻)', None, 2, None, ''),
	('100!', None, 100.0, None, ''),
	('100% Distracted', None, 100, None, ''),
	('100. Underground Labyrinth', None, 100.0, None, ''),
	('100. Underground Labyrinth (1/2)', None, 100.0, None, ''),
	('1000 Hugs chapter 35 And Paladin of the End book 1 chapter 2', 1.0, 35.0, None, ''),
	('1000 hugs chapter 28', None, 28.0, None, ''),
	('1000 hugs chapter 29', None, 29.0, None, ''),
	('1000 hugs chapter 30', None, 30.0, None, ''),
	('1000 hugs chapter 31', None, 31.0, None, ''),
	('1000 hugs chapter 32', None, 32.0, None, ''),
	('1000 hugs chapter 33 and new thing', None, 33.0, None, ''),
	('1000 hugs chapter 34', None, 34.0, None, ''),
	('1000 hugs chapter 36 and 37', None, 36.0, None, ''),
	('1000 hugs chapter 38', None, 38.0, None, ''),
	('1000 hugs chapter 39', None, 39.0, None, ''),
	('1000 nin no Homunkurusu no Shoujo tachi ni Kakomarete Isekai Kenkoku - Chapter 1', None, 1.0, None, ''),
	('1000 nin no Homunkurusu no Shoujo tachi ni Kakomarete Isekai Kenkoku - Chapter 2', None, 2.0, None, ''),
	('1000 nin no Homunkurusu no Shoujo tachi ni Kakomarete Isekai Kenkoku - Chapter 3', None, 3.0, None, ''),
	('100th release!', None, 100.0, None, ''),
	('101 Ways of Surviving a Cliffhanger', None, 101.0, None, ''),
	('101. Smooth Plan', None, 101.0, None, ''),
	('102. Audience with Monsters', None, 102.0, None, ''),
	('104. The Night Before', None, 104.0, None, ''),
	('104. The Night Before (50%)', None, 104.0, None, ''),
	('105. Preliminary Rous', None, 105.0, None, ''),
	('106. Tournament – Finals Part 1', None, 106.0, 1.0, ''),
	('107. Tournament – Finals Part 2', None, 107.0, 2.0, ''),
	('108 Maidens of Destiny Glossaries', None, 108.0, None, ''),
	('108 Maidens of Destiny – Chapter 12', None, 12.0, None, ''),
	('108 Maidens of Destiny: Chapter 10 – Running into a Demoness', None, 10.0, None, ''),
	('108 Maidens of Destiny: Chapter 11 – Chaotic Tail Escape Technique', None, 11.0, None, ''),
	('108 Maidens of Destiny: Chapter 13 – Xun Tian Daoist', None, 13.0, None, ''),
	('108 Maidens of Destiny: Chapter 14 – None of You Have The Qualification', None, 14.0, None, ''),
	('108 Maidens of Destiny: Chapter 4 – Shifting the tides with a lift of a Blade', None, 4.0, None, ''),
	('108 Maidens of Destiny: Chapter 5 – Relic Blade Legacy', None, 5.0, None, ''),
	('108 Maidens of Destiny: Chapter 6 – Spirit Engulfing Flood Dragons', None, 6.0, None, ''),
	('108 Maidens of Destiny: Chapter 7 – Solution to the Legacy’s Secret', None, 7.0, None, ''),
	('108 Maidens of Destiny: Chapter 8 – The Majestic Star’s Seal Symbol', None, 8.0, None, ''),
	('108 Maidens of Destiny: Chapter 9 – The Majestic Star’s Seal Symbol', None, 9.0, None, ''),
	('108. Tournament – Finals Part 3', None, 108.0, 3.0, ''),
	('109. Tournament – Finals Part 4', None, 109.0, 4.0, ''),
	('10th Chapter Milestone', None, 10.0, None, ''),
	('10th Chapter Milestone!', None, 10.0, None, ''),
	('11', None, 11.0, None, ''),
	('11 | 1 : Machine', None, 11.0, None, ''),
	('11 | 2 : Machine', None, 11.0, None, ''),
	('11 | 3 : Machine', None, 11.0, None, ''),
	('11 | 4 : Machine', None, 11.0, None, ''),
	('11 – On and Forever', None, 11.0, None, ''),
	('11.1 Migration', None, 11.1, None, ''),
	('11.10 Migration', None, 11.1, None, ''),
	('11.11 Migration', None, 11.11, None, ''),
	('11.12 Migration', None, 11.12, None, ''),
	('11.13 Migration', None, 11.13, None, ''),
	('11.14 Interlude (Snow)', None, 11.14, None, 'Interlude (Snow)'),
	('11.2 Migration', None, 11.2, None, ''),
	('11.3 Migration', None, 11.3, None, ''),
	('11.4 Migration', None, 11.4, None, ''),
	('11.5 Migration', None, 11.5, None, ''),
	('11.6 Migration', None, 11.6, None, ''),
	('11.7 Migration', None, 11.7, None, ''),
	('11.8 Migration', None, 11.8, None, ''),
	('11/11 The struggle has ended', None, 11.0, None, ''),
	('110. Tournament – Part 5', None, 110.0, 5.0, ''),
	('110. Tournament – Part 5 (70%)', None, 110.0, 5.0, ''),
	('111. Tournament – Finals Part 6', None, 111.0, 6.0, ''),
	('117. Smooth Sailing', None, 117.0, None, ''),
	('118. Labyrinth and Trust', None, 118.0, None, ''),
	('119. The way to a enjoy a dungeon', None, 119.0, None, ''),
	('12', None, 12.0, None, ''),
	('12 Days of Christmas release', None, 12.0, None, ''),
	('12 Hr Translation Marathon!', None, 12.0, None, ''),
	('12 is done', None, 12.0, None, ''),
	('12 | 1 : Memory Lane', None, 12.0, None, ''),
	('12 | 2 : Memory Lane', None, 12.0, None, ''),
	('12 – New Journey', None, 12.0, None, ''),
	('12.1 Precipice', None, 12.1, None, ''),
	('12.10 Precipice', None, 12.1, None, ''),
	('12.11 Precipice', None, 12.11, None, ''),
	('12.12 Precipice', None, 12.12, None, ''),
	('12.13 Precipice', None, 12.13, None, ''),
	('12.14 Precipice', None, 12.14, None, ''),
	('12.15 Precipice', None, 12.15, None, ''),
	('12.16 Precipice', None, 12.16, None, ''),
	('12.17 Precipice', None, 12.17, None, ''),
	('12.18 Precipice', None, 12.18, None, ''),
	('12.2 Precipice', None, 12.2, None, ''),
	('12.3 Precipice', None, 12.3, None, ''),
	('12.4 Precipice', None, 12.4, None, ''),
	('12.5 Precipice', None, 12.5, None, ''),
	('12.6 Precipice', None, 12.6, None, ''),
	('12.7 Precipice', None, 12.7, None, ''),
	('12.8 Precipice', None, 12.8, None, ''),
	('12.9 Precipice', None, 12.9, None, ''),
	('120. Setting off', None, 120.0, None, ''),
	('121. Hinata and the Kids', None, 121.0, None, ''),
	('122. Hinata and Yuuki', None, 122.0, None, ''),
	('123. Predestined Fate (Guro)', None, 123.0, None, ''),
	('124. Birth of a Hero', None, 124.0, None, ''),
	('125. The Memories of the Hero (Guro)', None, 125.0, None, ''),
	('126. The Rebellion’s Beginning', None, 126.0, None, ''),
	('127. Excuse and Reflection (Guro)', None, 127.0, None, ''),
	('128. Alliance of Three Kingdoms', None, 128.0, None, ''),
	('129. Yuuki Subjugation Raid', None, 129.0, None, ''),
	('13 is 100% done', None, 13.0, None, ''),
	('13.1 Devastation', None, 13.1, None, ''),
	('13.2 Devastation', None, 13.2, None, ''),
	('13.3 Devastation', None, 13.3, None, ''),
	('13.4 Devastation', None, 13.4, None, ''),
	('13.5 Devastation', None, 13.5, None, ''),
	('13.6 Devastation', None, 13.6, None, ''),
	('13.7 Devastation', None, 13.7, None, ''),
	('13.8 Devastation', None, 13.8, None, ''),
	('13/01/2016', None, None, None, ''),
	('130. A sudden invitation', None, 130.0, None, ''),
	('131. Demon Lord Leon', None, 131.0, None, ''),
	('132. Kagurazaka Yuuki (Guro)', None, 132.0, None, ''),
	('133. Leon vs Yuuki – Part 1', None, 133.0, 1.0, ''),
	('134. Leon vs Yuuki – Part 2 (Guro)', None, 134.0, 2.0, ''),
	('135. After the Incident', None, 135.0, None, ''),
	('136. Eastern Empire', None, 136.0, None, ''),
	('137. A year of Progress (Part 1)', None, 137.0, 1.0, ''),
	('137. A year of progress (Part 2)', None, 137.0, 2.0, ''),
	('138. A request from the council', None, 138.0, None, ''),
	('139. The Whole Story of the Assembly (Guro)', None, 139.0, None, ''),
	('13^2 – 10^2 =', None, 13.0, None, ''),
	('14/05/2015', None, None, None, ''),
	('140. Research Results (Guro)', None, 140.0, None, ''),
	('142. Military Affairs', None, 142.0, None, ''),
	('143 Kaoru’s Cake House – Chapter Eighteen', None, 18, None, ''),
	('143 Kaoru’s Cake House – Chapter Fifteen', None, 15, None, ''),
	('143 Kaoru’s Cake House – Chapter Seventeen', None, 17, None, ''),
	('143 Kaoru’s Cake House – Chapter Sixteen', None, 16, None, ''),
	('143. The Formidable Corps (Unedited)', None, 143.0, None, ''),
	('148. A Decision made too late', None, 148.0, None, ''),
	('15. Gardiyanlarla Pazarlık', None, 15.0, None, ''),
	('153. Great War Outbreak -The beginning of the trampling- (unedited)', None, 153.0, None, ''),
	('153. Great war outbreak –The beginning of the trampling- (Edited)', None, 153.0, None, ''),
	('157. Battle of the Dungeon.', None, 157.0, None, ''),
	('159. The Capital’s Defensive battle', None, 159.0, None, ''),
	('16', None, 16.0, None, ''),
	('17', None, 17.0, None, ''),
	('17.5 - Key points', None, 17.5, None, ''),
	('18', None, 18.0, None, ''),
	('18/05/2015', None, None, None, ''),
	('18/11 Upcoming', None, 18.0, None, ''),
	('19', None, 19.0, None, ''),
	('1985: Dracula’s Revenge', None, 1985.0, None, ''),
	('1M', None, 1.0, None, ''),
	('1YL: 7.15', None, 1.0, None, ''),
	('1st Construction: Dig there Doggy! Teaser!!', None, 1.0, None, ''),
	('1st Translation Chapter Post Mortem', None, 1.0, None, ''),
	('1st and 2nd Person', None, 1.0, None, ''),
	('1st regular chapter of the week!', None, 1.0, None, ''),
	('1st story [The Master of the Dark guild]', None, 1.0, None, ''),
]

