

data = [
	('', None, None, None, ''),
	('!!Chapter 42!! !!Happy times!!', None, 42.0, None, ''),
	('!172 WDG daeR esalP', None, 172.0, None, ''),
	('!Chapter 46!', None, 46.0, None, ''),
	('!Sneaky! Chapter 59 !Sneaky!', None, 59.0, None, ''),
	('#1 Sponsored Chapter!', None, 1.0, None, ''),
	('#2 Sponsored Chapter of the weekend!', None, 2.0, None, ''),
	('#BanYunForCheatingAtQuests', None, None, None, ''),
	('#ExcusesForInordinatelyLongBreak #GiveUsYourSympathy #Generic/ClichedWeThankYouForYourPatienceAndSupportPost', None, None, None, ''),
	('#talk 33: One million milestone!', None, 33.0, None, ''),
	('#talk 34: Writing & Friends', None, 34.0, None, ''),
	('#talk 35: Dreaming about my New Translation Project!', None, 35.0, None, ''),
	('#talk 37: my very warm hello to my readers, Once Promised project & life!', None, 37.0, None, ''),
	('*** SUPER IMPORTANT ANNOUNCEMENT***', None, None, None, ''),
	('***IMPORTANT ANNOUNCEMENT***', None, None, None, ''),
	('*Dust Trails*', None, None, None, ''),
	('*New* Half-Dragon Slave Life- Prologue 2', None, 2.0, None, 'Prologue 2'),
	('*Update*', None, None, None, ''),
	('*WDQK Update Post*', None, None, None, ''),
	('*sigh* meow has been fired.', None, None, None, ''),
	('*small gasp*', None, None, None, ''),
	('-Elqueeness’ Chapter- Supplemental story 2.', None, 2, None, ''),
	('-Elqueeness’ Chapter- Supplemental story 3-', None, 3.0, None, ''),
	('-SLASHDØG̙- (Indonesia) Bab 1', None, 1.0, None, ''),
	('-SLASHDØG̙- (Indonesia) Bab 2', None, 2.0, None, ''),
	('-SLASHDØG̙- (Indonesia) Prolog', None, None, None, ''),
	('-poke-', None, None, None, ''),
	('/second-life-1-10/', None, 1.0, 10.0, ''),
	('8 Hour Translation Marathon TMR!', None, 8.0, None, ''),
	('8 natori icons', None, 8.0, None, ''),
	('8. Flying baby', None, 8.0, None, ''),
	('8.-Little Rock Dragon', None, 8.0, None, ''),
	('8/11 – The last leg', None, 8.0, None, ''),
	('85 percent', None, 85.0, None, ''),
	(':3 Late chapter today :3', None, 3.0, None, ''),
	(':O Looks like many people are having problems', None, None, None, ''),
	(':^)', None, None, None, ''),
	(';-;', None, None, None, ''),
	(';_;', None, None, None, ''),
	('>_<', None, None, None, ''),
	('??? Page, further information', None, None, None, ''),
	('?????', None, None, None, ''),
	('^_^ Chapter 57 ^_^', None, 57.0, None, ''),
	('^———————-^', None, None, None, ''),
	('_Chapter 47_', None, 47.0, None, ''),
	('{:} Chapter 51 {:}', None, 51.0, None, ''),
	('{TRANSLATOR RECRUITMENT! This project needs a translator and/or is stuck in teaser status}', None, None, None, ''),
	('{xxx} is the ideal', None, None, None, ''),
	('{◕ ᵥ ◕} Chapter 50 {◕ ᵥ ◕}', None, 50.0, None, ''),
	('~Regarding Demon Lord’s Pet Release Schedule~', None, None, None, ''),
	('~Slow life in another world~', None, None, None, ''),
	('~Tempest of the Stellar War Update~', None, None, None, ''),
	('~The Side of The Last Boss~ C (Teaser)', None, None, None, ''),
	('~You asked for it~', None, None, None, ''),
	('¡El capítulo decimocuarto había tradujo!', None, None, None, ''),
	('½ Prince V2C6: The Truth, Revealed?', 2.0, 6.0, None, ''),
	('½ Prince V2Extra: Diary', 2, None, None, 'V2Extra: Diary'),
	('½ Prince V3C4: Jing and Yun', 3.0, 4.0, None, ''),
	('½ Prince V4C1: Infinite City Will Never\xa0Fall', 4.0, 1.0, None, ''),
	('½ Prince V4Extra: The Sun should Shine in the Fair Sky', 4, None, None, 'V4Extra: The Sun should Shine in the Fair Sky'),
	('½ Prince V5C1: The Title of Undefeatable King', 5.0, 1.0, None, ''),
	('½ Prince V8Extra: Epilogue (End)', 8, None, None, 'V8Extra: Epilogue (End)'),
	('½ Prince V9C1: Feng Long Ming, Part One', 9.0, 1.0, 1, ''),
	('½ Prince V9C2: Feng Long Ming, Part Two', 9.0, 2.0, 2, ''),
	('Żywot 1: Cycki w słońcu!', None, 1.0, None, ''),
	('Żywot 2: Rozporządzenie Samorządu Uczniowskiego', None, 2.0, None, ''),
	('Żywot 3: Jazda z tym treningiem', None, 3.0, None, ''),
	('Żywot 4: Kult☆Smoczej Bogini', None, 4.0, None, ''),
	('Żywot 5: Nekomaci☆Zwój Ninja', None, 5.0, None, ''),
	('Конец пролога / День, когда Хасэгава Кодака стал главным героем', None, None, None, ''),
	('Конец пролога\\День, когда Хасэгава Кодака стал главным героем', None, None, None, ''),
	('‘Agar Tu Hota Tho’ English Meaning and Lyrics', None, None, None, ''),
	('‘Meow’ and his posts…', None, None, None, ''),
	('‘Salamat’ English Meaning and Lyrics', None, None, None, ''),
	('‘Sapna Jahan’ From Brothers OST Lyrics and Meaning', None, None, None, ''),
	('‘Sup', None, None, None, ''),
	('‘Tere Bina Zindagi Se’ Song Meaning and Lyrics', None, None, None, ''),
	('….late.’ 3′', None, 3.0, None, ''),
	('…? What is this…?', None, None, None, ''),
	('…Chapter 224!', None, 224.0, None, ''),
	('…Good Stuff is Coming ^^', None, None, None, ''),
	('⋆Active again! Mass update!⋆', None, None, None, ''),
	('☼kyou wa watashi learnt persuasion☼', None, None, None, ''),
	('✓ Message seen', None, None, None, ''),
	('《三嫁未晚》', None, None, None, ''),
	('《琅琊榜》Nirvana in Fire : Chapter 04《路逢旧交》', None, 4.0, None, ''),
	('《琅琊榜》Nirvana in Fire : Chapter 05《途中惊变》', None, 5.0, None, ''),
	('《琅琊榜》Nirvana in Fire : Chapter 06《借兵》', None, 6.0, None, ''),
	('《琅琊榜》Nirvana in Fire : Chapter 07.5 《殊途》', None, 7.5, None, ''),
	('《琅琊榜》Nirvana in Fire : Episode 1', None, 1.0, None, ''),
	('ハーレム性召喚から婚約者を決めて! [Harem Seishoukan kara Konyakusha wo Kimete!]', None, None, None, ''),
	('不侍寝？砍了! – Refusing to Serve Me?  Then Off With Your Head!', None, None, None, ''),
	('不悟 Unrepentant: Book Review', None, None, None, ''),
	('不第后赋菊: Composing Chrysanthemum [Poem] After Failing The Imperial Examination (By 黄巢 Huang Chao)', None, None, None, ''),
	('与于中丞: Yu Yu Zhong Cheng （by 刘商 / Liu Shang）', None, None, None, ''),
	('东宫 Eastern Palace: Chapter 10', None, 10.0, None, ''),
	('东宫 Eastern Palace: Chapter 5', None, 5.0, None, ''),
	('东宫 Eastern Palace: Chapter 6', None, 6.0, None, ''),
	('东宫 Eastern Palace: Chapter 7', None, 7.0, None, ''),
	('东宫 Eastern Palace: Chapter 8', None, 8.0, None, ''),
	('东宫 Eastern Palace: Chapter 9', None, 9.0, None, ''),
	('乌衣巷: Wu Yi Alley (By 刘禹锡 Liu Yu Xi)', None, None, None, ''),
	('书中自有颜如玉 (Finding Glowing Beauty in Books) – 板栗子Ban Li Zi [Pilot Chapter 1]', None, 1.0, None, ''),
	('他知道风从哪里来 The Wind Goes, As He Knows: Book Review', None, None, None, ''),
	('仿如昨日 14-16', None, 14.0, None, ''),
	('仿如昨日 17-20', None, 17.0, None, ''),
	('仿如昨日 9-13', None, 9.0, None, ''),
	('公主贵性 What’s Your Gender, Princess?: Book Review', None, None, None, ''),
	('六花禁爱 Flowers of Love by 月落紫珊 Chapter 14', None, 14.0, None, ''),
	('六花禁爱 Flowers of Love by 月落紫珊 Chapter 15', None, 15.0, None, ''),
	('六花禁爱 Flowers of Love by 月落紫珊 Chapter 16', None, 16.0, None, ''),
	('六花禁爱 Flowers of Love by 月落紫珊 Chapter 17', None, 17.0, None, ''),
	('六花禁爱 Flowers of Love by 月落紫珊 Chapter 19', None, 19.0, None, ''),
	('六花禁爱 Flowers of Love by 月落紫珊 Chapter 21', None, 21.0, None, ''),
	('凤唳九天/The cry of the phoenix  which reached the Ninth Heaven', None, None, None, ''),
	('南歌子·万万千千恨: Song of the South · Thousands Upon Thousands of Hate (by 辛弃疾 Xin Ji Qi)', None, None, None, ''),
	('参加します (i used google translatu just for yall)', None, None, None, ''),
	('同居不同床- 舒格 SAME PLACE NOT SAME BED- SUGAR CHAPTER 1.2', None, 1.2, None, ''),
	('同居不同床- 舒格 SAME PLACE NOT SAME BED- SUGAR CHAPTER 3', None, 3.0, None, ''),
	('同居不同床- 舒格 SAME PLACE NOT SAME BED- SUGAR CHAPTER 4', None, 4.0, None, ''),
	('同居不同床- 舒格 Same Place Not Same Bed- Sugar Chapter 1.1', None, 1.1, None, ''),
	('塞鸿秋·山行警: Sai Hong Qiu·The Mountain Walk Alarm (by anonymous)', None, None, None, ''),
	('好感度が上がらない', None, None, None, ''),
	('婚約破棄……望むところです', None, None, None, ''),
	('宝贝宝贝 Baobei Baobei by 以墨/上黑下土- 1st Chapter Series', None, 1.0, None, ''),
	('宣州谢朓楼饯别校书叔云: A Farewell to Secretary Uncle Yun At the Xietiao Villa in Xuanzhou (by 李白 Li Bai)', None, None, None, ''),
	('少年的你，如此美丽 The Youthful You Who Was So Beautiful: Book Review', None, None, None, ''),
	('微微一笑很倾城 (Just One Smile Is Very Alluring)(Review)', None, None, None, ''),
	('微微一笑很倾城 One smile is very alluring drama', None, None, None, ''),
	('念奴娇·赤壁怀古: Nian Nu Jiao·Reminiscence of Red Cliffs (by 苏轼 / Su Shi)', None, None, None, ''),
	('护心 Heart Protection: Book Review', None, None, None, ''),
	('新時代のサガ Shinjidai no Saga – Donquiote Flamingo – Character Song', None, None, None, ''),
	('星月神话- 金莎', None, None, None, ''),
	('春江花月夜: Spring Blossoms On The Moonlit River (by 张若虚 Zhang Ruo Xu)', None, None, None, ''),
	('本王在此 The Prince is Here: Book Review', None, None, None, ''),
	('梅花引·荆溪阻雪:Plum Blossom Citing·Jing Xi Snow Barrier (by 蒋捷 Jiang Jie)', None, None, None, ''),
	('梓琴 (Ziqin) by 九鹭非香 (Jiu Lu Fei Xiang)', None, None, None, ''),
	('沈依莎 《時過境遷》~ Passage of Time by Shen Yi Sha', None, None, None, ''),
	('泪倾城·浅眸乱君颜 Tears all over the place: cold ruler’s only love', None, None, None, ''),
	('火刑戦旗を掲げよ！Prologue（Fanning the Flames of War）', None, None, None, '火刑戦旗を掲げよ！Prologue（Fanning the Flames of War）'),
	('爱莲说：On the Love of the Lotus (by 周敦颐 Zhou Dun Yi)', None, None, None, ''),
	('王笠人 – 如果我們再相遇 致,第三者 ~ Wang Li Ren, If We Meet Again (To the Dearest Intruder)', None, None, None, ''),
	('生于忧患，死于安乐: Suffering is living, happiness is death (from 孟子·告子下 Mencius · Gao Zi)', None, None, None, ''),
	('界 World of Cultivation Chapter Three Hundred and Fifteen “Flower Slaves”', None, 315, None, ''),
	('異世界食堂 Chapter 1 - Minced Cutlet', None, 1.0, None, ''),
	('目', None, None, None, ''),
	('短い話です', None, None, None, ''),
	('神達に拾われた男 Prologue-1', None, 1.0, None, 'Prologue-1'),
	('終南別業:Villa On Mount Zhong Nan (by 王維 Wang Wei)', None, None, None, ''),
	('美人为馅 Memory Lost – 丁墨 DING MO(HE)', None, None, None, ''),
	('翻译官 Les Interprètes (Chapter One+Two)', None, None, None, ''),
	('舌尖上的心跳 The Heartbeat At The Tip Of The Tongue: Book Review', None, None, None, ''),
	('蘇りの魔王(Yomigaeri no Maou) – Chapter 21', None, 21, None, ''),
	('跨过千年来爱你 Across A Millennium to Love You By 秋夜雨寒  Chap 1', None, 1.0, None, ''),
	('跨过千年来爱你 Across A Millennium to Love You- Snippet 1 (Chap 4)', None, 4.0, None, ''),
	('遇见你就烂漫了/等一个晴天Meeting You is Brightly Colored(Brilliant)/Waiting for a Sunny Day- 蝶之灵 Die Zhi Ling: Chapter 1.1.1', None, None, None, ''),
	('锦绣缘 ~ Cruel Romance ~ Chapter 6 (1)', None, 6.0, None, ''),
	('锦绣缘 ~ Cruel Romance ~ Chapter 6 (2)', None, 6.0, None, ''),
	('锦绣缘 ~ Cruel Romance ~ Chapter 6 (3)', None, 6.0, None, ''),
	('锦绣缘 ~ Cruel Romance ~ Chapter 6 (4)', None, 6.0, None, ''),
	('锦绣缘 ~ Cruel Romance ~ Chapter 6 (5)', None, 6.0, None, ''),
	('锦绣缘 ~ Cruel Romance ~ Chapter 6 (6)', None, 6.0, None, ''),
	('风行烈《云狂》Yun Kuang : Unbelievably OP Female Lead', None, None, None, ''),
	('／人◕ ‿‿ ◕人＼\ufeff', None, None, None, ''),
	('Ｔｅｓｔ\u3000ｆｏｒ\u3000ａ\u3000ｍｅｓｓ', None, None, None, ''),
	('😱 What happened to Buy.com?', None, None, None, ''),
]

