

data = [
	('( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)', None, None, None, ''),
	('(100 Luck) Chapter 26: Pertiko and the Paladins (Part 1)', None, 26.0, 1.0, ''),
	('(100 Luck) Chapter 27: An unexpected turn of events', None, 27.0, None, ''),
	('(100 Luck) Chapter 28: Trapped (Part 1)', None, 28.0, 1.0, ''),
	('(100 Luck) Chapter 28: Trapped (Part 2)', None, 28.0, 2.0, ''),
	('(100 Luck) Chapter 29: The final countdown (Part 1)', None, 29.0, 1.0, ''),
	('(100 Luck) Chapter 29: The final countdown (Part 2)', None, 29.0, 2.0, ''),
	('(100 Luck) Chapter 30: A battle between two heroes (Part 1)', None, 30.0, 1.0, ''),
	('(100 Luck) Chapter 30: A battle between two heroes (Part 2)', None, 30.0, 2.0, ''),
	('(100 Luck): Chapter 26: Pertiko and the Paladins (Part 2)', None, 26.0, 2.0, ''),
	('(75%) Chapter 13 : Job completed', None, 13.0, None, ''),
	('(Announcement) Grassland Law', None, None, None, ''),
	("(Announcement) and Chapter 21 - Zeshald's Request", None, 21.0, None, ''),
	('(BOOK 1) Tales of a Shifter - Broken Bonds', 1.0, None, None, ''),
	('(Belated) New Year’s Release – Part 4 (Final)', None, None, 4.0, ''),
	('(C76) [Chocomint Mashimaro (Uzu, Midou Riko)] Ranshama to Issho (Touhou Project)', None, 76.0, None, ''),
	('(C79) [Sakurai Energy] Densetsu no Kyoushi (Touhou Project)', None, 79.0, None, ''),
	('(C83) [Fuantei] Konno Katouseibutsu Gaa!!! (Touhou Project)', None, 83.0, None, ''),
	('(C85) [Ichikai (Ichi)] Aru Hitori no Senjou Kameraman no Saigo no Shashin (Touhou Project)', None, 85.0, None, ''),
	('(C85) [Rainbow Vanilla (Matsuriuta)] Junjou Eccentric Honey Face (Touhou Project)', None, 85.0, None, ''),
	('(C87) [Irori Sabou (tyatamaru)] MariAli ga Kosodate wo Suru Hanashi Sister (Touhou Project)', None, 87.0, None, ''),
	('(Dai 127 ki Bunbunmaru Shinbun Tomo no Kai) [Anzu no KI (Unyakichi)] ○○ Kakeru Hatate (Touhou Project)', None, 127.0, None, ''),
	('(ES) Chapter 4: A fake Yawn to say Good Night', None, 4.0, None, ''),
	('(FOE) Chapter 4: For I am Anwen!', None, 4.0, None, ''),
	('(Fanfic) Consulting with this Masked Devil! Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('(Fanfic) Consulting with this Masked Devil! Volume 1 Chapter 4', 1.0, 4.0, None, ''),
	('(Fanfic) Consulting with this Masked Devil! Volume 1 Chapter 5', 1.0, 5.0, None, ''),
	('(Fanfic) Consulting with this Masked Devil! Volume 1 Epilogue', 1.0, None, None, 'Epilogue'),
	('(Fanfic) Gifting the wonderful world with blessings! Volume 9 Chapter 1', 9.0, 1.0, None, ''),
	('(Fanfic) Gifting the wonderful world with blessings! Volume 9 Chapter 2', 9.0, 2.0, None, ''),
	('(Fanfic) Gifting the wonderful world with blessings! Volume 9 Chapter 3', 9.0, 3.0, None, ''),
	('(Fanfic) Gifting the wonderful world with blessings! Volume 9 Chapter 4', 9.0, 4.0, None, ''),
	('(Fanfic) Gifting the wonderful world with blessings! Volume 9 Prologue', 9.0, None, None, 'Prologue'),
	('(Fanfiction) Gifting the wonderful world with blessings!', None, None, None, ''),
	('(GDW) Chapter 2: A new day in my wife’s dungeon!', None, 2.0, None, ''),
	('(GDW) Chapter 3: Meeting the locals', None, 3.0, None, ''),
	('(Hakata Touhousai) [RUMP (Bon)] Eringe (Touhou Project)', None, None, None, ''),
	('(Impt. Notification)', None, None, None, ''),
	('(Kageki no Utage) [Fuantei (Furari, Kome Dorobou)] MIRACLE, LOVE, JET!! (Touhou Project)', None, None, None, ''),
	('(Konosuba OST) Drama CD 1', None, 1.0, None, ''),
	('(Kouroumu 10) [Fuantei (Furari, Kome Dorobou)] NATURAL BORN DARKNESS (Touhou Project)', None, 10.0, None, ''),
	('(Kouroumu 5) [KEMONOMICHI (Chihiro)] Jukai no Ito (Touhou Project)', None, 5.0, None, ''),
	('(Kouroumu 9) [Fuantei (Furari)] KOKOROSTEP (Touhou Project)', None, 9.0, None, ''),
	('(Kouroumu 9) [HECHOCHO (ABO, Kuromitsu)] Natsuiro Shangri-La! (Touhou Project)', None, 9.0, None, ''),
	('(MA) Chapter 60: Illsyore’s rage (Part 1)', None, 60.0, 1.0, ''),
	('(MA) Chapter 60: Illsyore’s rage (Part 2)', None, 60.0, 2.0, ''),
	('(MA) Chapter 61: Madness and destruction (Part 1)', None, 61.0, 1.0, ''),
	('(MA) Chapter 61: Madness and destruction (Part 2)', None, 61.0, 2.0, ''),
	('(MA) Chapter 62: The curse (Part 1)', None, 62.0, 1.0, ''),
	('(MA) Chapter 62: The curse (Part 2)', None, 62.0, 2.0, ''),
	('(MA) Chapter 63: Giving up on my el’doraw (Part 1)', None, 63.0, 1.0, ''),
	('(MA) Chapter 63: Giving up on my el’doraw (Part 2)', None, 63.0, 2.0, ''),
	('(MA) Chapter 63: Giving up on my el’doraw (Part 3)', None, 63.0, 3.0, ''),
	('(MA) Chapter 64: The stalker (Part 1)', None, 64.0, 1.0, ''),
	('(MA) Chapter 64: The stalker (Part 2)', None, 64.0, 2.0, ''),
	('(MA) Chapter 65: The battle in the forest (Part 1)', None, 65.0, 1.0, ''),
	('(MA) Chapter 65: The battle in the forest (Part 2)', None, 65.0, 2.0, ''),
	('(MA) Chapter 65: The battle in the forest (Part 3)', None, 65.0, 3.0, ''),
	('(MA) Chapter 66: A new party member (Part 1)', None, 66.0, 1.0, ''),
	('(MA) Chapter 66: A new party member (Part 2)', None, 66.0, 2.0, ''),
	('(MA) Chapter 67: The start of a new day', None, 67.0, None, ''),
	('(MA) Chapter 68: The secret plan', None, 68.0, None, ''),
	('(MA) Chapter 69: Nightmare', None, 69.0, None, ''),
	('(MA) Chapter 70: Memories and Turmoil (Part 1)', None, 70.0, 1.0, ''),
	('(MA) Chapter 70: Memories and Turmoil (Part 2)', None, 70.0, 2.0, ''),
	('(MA) Chapter 71: Zoreya’s turmoil', None, 71.0, None, ''),
	('(MA) Chapter 72: A history untold', None, 72.0, None, ''),
	('(Mecha Mushroom saved Jiang Ye) Jiang Ye Update', None, None, None, ''),
	('(NSFW) Eroge (P)Review: Anoko wa Ore kara Hanarenai', None, None, None, ''),
	('(NSFW) Nukige Review: Hoka no Onna no Ko to H o Shiteiru Ore o Mite Koufun Suru Kanojo', None, None, None, ''),
	('(Novel) An Earnest Unrequited Love, Wanting to Make it Bear a Little Happiness', None, None, None, ''),
	('(Novel) Apartments For Rent Chapter 11 Part III', None, 11.0, None, ''),
	('(Novel) Apartments For Rent Chapter 12 Part I', None, 12.0, None, ''),
	('(Novel) Purple River Chapter 07 Part 06', None, 7.0, 6.0, ''),
	('(Novel) Purple River Chapter 07 Part 07', None, 7.0, 7.0, ''),
	('(Novel) Purple River Chapter 07 Part 08', None, 7.0, 8.0, ''),
	('(Novel) Purple River Chapter 08 Part 01', None, 8.0, 1.0, ''),
	('(Novel) Purple River Chapter 08 Part 02', None, 8.0, 2.0, ''),
	('(Novel) Purple River Chapter 08 Part 03', None, 8.0, 3.0, ''),
	('(Novel) Purple River Chapter 08 Part 04', None, 8.0, 4.0, ''),
	('(Novel) Purple River Chapter 08 Part 05', None, 8.0, 5.0, ''),
	('(Novel) Purple River Chapter 08 Part 06', None, 8.0, 6.0, ''),
	('(Novel) Purple River Chapter 08 Part 07', None, 8.0, 7.0, ''),
	('(Novel) Purple River Chapter 08 Part 08', None, 8.0, 8.0, ''),
	('(Novel) Purple River Chapter 09 Part 01', None, 9.0, 1.0, ''),
	('(Part 2) An Earnest Unrequited Love, Wanting to Make it Bear a Little Happiness', None, None, 2.0, ''),
	('(Part 3) An Earnest Unrequited Love, Wanting to Make it Bear a Little Happiness', None, None, 3.0, ''),
	('(Part 4) An Earnest Unrequited Love, Wanting to Make it Bear a Little Happiness', None, None, 4.0, ''),
	('(Part 5) An Earnest Unrequited Love, Wanting to Make it Bear a Little Happiness', None, None, 5.0, ''),
	('(Potential) new series?', None, None, None, ''),
	('(R18) Frequenting Brothels 1', None, 1.0, None, ''),
	('(R18) Frequenting Brothels 10', None, 10.0, None, ''),
	('(R18) Frequenting Brothels 11', None, 11.0, None, ''),
	('(R18) Frequenting Brothels 12', None, 12.0, None, ''),
	('(R18) Frequenting Brothels 13', None, 13.0, None, ''),
	('(R18) Frequenting Brothels 14', None, 14.0, None, ''),
	('(R18) Frequenting Brothels 15', None, 15.0, None, ''),
	('(R18) Frequenting Brothels 16', None, 16.0, None, ''),
	('(R18) Frequenting Brothels 17', None, 17.0, None, ''),
	('(R18) Frequenting Brothels 18', None, 18.0, None, ''),
	('(R18) Frequenting Brothels 19', None, 19.0, None, ''),
	('(R18) Frequenting Brothels 2', None, 2.0, None, ''),
	('(R18) Frequenting Brothels 20', None, 20.0, None, ''),
	('(R18) Frequenting Brothels 21', None, 21.0, None, ''),
	('(R18) Frequenting Brothels 22', None, 22.0, None, ''),
	('(R18) Frequenting Brothels 23', None, 23.0, None, ''),
	('(R18) Frequenting Brothels 24', None, 24.0, None, ''),
	('(R18) Frequenting Brothels 25', None, 25.0, None, ''),
	('(R18) Frequenting Brothels 26', None, 26.0, None, ''),
	('(R18) Frequenting Brothels 27', None, 27.0, None, ''),
	('(R18) Frequenting Brothels 28', None, 28.0, None, ''),
	('(R18) Frequenting Brothels 3', None, 3.0, None, ''),
	('(R18) Frequenting Brothels 4', None, 4.0, None, ''),
	('(R18) Frequenting Brothels 5', None, 5.0, None, ''),
	('(R18) Frequenting Brothels 6', None, 6.0, None, ''),
	('(R18) Frequenting Brothels 7', None, 7.0, None, ''),
	('(R18) Frequenting Brothels 8', None, 8.0, None, ''),
	('(R18) Frequenting Brothels 9', None, 9.0, None, ''),
	('(R18) Frequenting Brothels Prologue', None, None, None, 'Prologue'),
	('(R18)Zhan Long 256 – Attack by Mei Guo', None, 256, None, ''),
	('(Reitaisai 10) [Gekidan Bunshichi] Grand Guignol (Touhou Project)', None, 10.0, None, ''),
	('(Reitaisai 10) [Irori Sabou (tyatamaru)] MariAri ga Kosodate wo Suru Hanashi -zero- (Touhou Project)', None, 10.0, None, ''),
	('(Reitaisai 11) [Fuantei (Furari, Kome Dorobou)] I do (Touhou Project)', None, 11.0, None, ''),
	('(Reitaisai 8) [Tamagooni Tappuri (Kanitama, kirusu)] Mushikui (Touhou Project)', None, 8.0, None, ''),
	('(Reitaisai 9) [Irori Sabou (tyatamaru)] MariAli ga Kosodate wo Suru Hanashi (Touhou Project)', None, 9.0, None, ''),
	('(The Prequel) Chapter 26: Confrontation', None, 26.0, None, ''),
	('(The Prequel) Chapter 27: Tears from the Past', None, 27.0, None, ''),
	('(The Truth) Behind Time Traveling穿越背后 by 无袖拢香 Wu Xiu Long Xiang Chapter/Part 1', None, None, 1.0, ''),
	('(This is not a Chapter) A Random Passing Thought', None, None, None, ''),
	('(This is not a Chapter) I did something: Gakumon! (ONA)', None, None, None, ''),
	('(This is not a Chapter) Information About Konjiki no Wordmaster', None, None, None, ''),
	('(This is not a chapter) Resuming', None, None, None, ''),
	('(UPDATE) Please Be More Serious | Chapter 32', None, 32.0, None, ''),
	('(Unedited) Magical Tournament Extra Edition: Plot Maker – Cast vs The Wall', None, None, None, 'Extra Edition: Plot Maker – Cast vs The Wall'),
	('(Unedited) Matou Vol 8 Chapter 1: Overture', 8.0, 1.0, None, ''),
	('(Unedited) Matou Vol 8 Chapter 2: Harsh Reality', 8.0, 2.0, None, ''),
	('(Unedited) Matou Vol 8 Chapter 3: Harsh Reality – Second Part', 8.0, 3.0, None, ''),
	('(ZerenMi) Editor introduction', None, None, None, ''),
	('(not chapter) just notice for chapter 13', None, 13.0, None, ''),
	('(o.O) shocked, happy, moved thanks Tim you are awesome (T_T)b', None, None, None, ''),
	('(o_O)!?', None, None, None, ''),
	('(o≧∇≦)o Our First Original Series!! o(≧∇≦o)', None, None, None, ''),
]

