

data = [
	('江湖路弯弯 Character List', None, None, None, ''),
	("江湖路弯弯 Jiang Hu Lu Wan Wan (Jiang Hu's road is curved) by 影照 Ying Zhao (HE)", None, None, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! (by 影照 Ying Zhao)', None, None, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 10', None, 10.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 12', None, 12.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 14', None, 14.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 15', None, 15.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 16', None, 16.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 17', None, 17.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 18', None, 18.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 19', None, 19.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 2', None, 2.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 20', None, 20.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 21', None, 21.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 22', None, 22.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 23', None, 23.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 24', None, 24.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 25', None, 25.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 26', None, 26.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 27', None, 27.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 28', None, 28.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 29', None, 29.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 3', None, 3.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 30', None, 30.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 31', None, 31.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 32', None, 32.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 33', None, 33.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 34', None, 34.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 35', None, 35.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 36', None, 36.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 37', None, 37.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 38', None, 38.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 39', None, 39.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 4', None, 4.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 40', None, 40.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 41', None, 41.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 42', None, 42.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 43', None, 43.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 44', None, 44.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 45', None, 45.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 46', None, 46.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 47', None, 47.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 48', None, 48.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 49', None, 49.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 50', None, 50.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 6', None, 6.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Chapter 8', None, 8.0, None, ''),
	('江湖路弯弯: Jianghu Road is Curved! Intro Chapter', None, None, None, ''),
	('江湖路弯弯:Jianghu Road is Curved! Chapter 11', None, 11.0, None, ''),
	('江湖路弯弯:Jianghu Road is Curved! Chapter 13', None, 13.0, None, ''),
	('江湖路弯弯:Jianghu Road is Curved! Chapter 5', None, 5.0, None, ''),
	('江湖路弯弯:Jianghu Road is Curved! Chapter 7', None, 7.0, None, ''),
	('江湖路弯弯:Jianghu Road is Curved! Chapter 9', None, 9.0, None, ''),
]

