

data = [
	('UHL - Ch 1', None, 1.0, None, ''),
	('UHL ch 2', None, 2.0, None, ''),
	('UL: Volume 5 Chapter 10', 5, 10, None, ''),
	('UL: Volume 5 Chapter 11', 5, 11, None, ''),
	('UL: Volume 5 Chapter 8', 5, 8, None, ''),
	('UL: Volume 5 Chapter 9', 5, 9, None, ''),
	('UL: Volume 6 Chapter 0', 6, 0, None, ''),
	('UL: Volume 6 Chapter 1', 6, 1, None, ''),
	('UL: Volume 6 Chapter 10', 6.0, 10.0, None, ''),
	('UL: Volume 6 Chapter 11', 6.0, 11.0, None, ''),
	('UL: Volume 6 Chapter 2', 6, 2, None, ''),
	('UL: Volume 6 Chapter 3', 6.0, 3.0, None, ''),
	('UL: Volume 6 Chapter 4', 6.0, 4.0, None, ''),
	('UL: Volume 6 Chapter 5', 6.0, 5.0, None, ''),
	('UL: Volume 6 Chapter 6', 6.0, 6.0, None, ''),
	('UL: Volume 6 Chapter 7', 6.0, 7.0, None, ''),
	('UL: Volume 6 Chapter 8', 6.0, 8.0, None, ''),
	('UL: Volume 6 Chapter 9', 6.0, 9.0, None, ''),
	('UNDER THE MOONLIGHT [VOLUME.03]', 3, None, None, ''),
	('UPDATE?!', None, None, None, ''),
	('URGENT ANNOUNCEMENT + Terror Paradise Chapter 19', None, 19.0, None, ''),
	('URL Change', None, None, None, ''),
	('US Site for the Rokka anime', None, None, None, ''),
	('USAW Chapter Release – Book 1, Chapter 81', 1.0, 81.0, None, ''),
	('USAW Chapter Release – Book 1, Chapter 82', 1.0, 82.0, None, ''),
	('USAW Chapter Release!  Book 1, Chapter 83', 1.0, 83.0, None, ''),
	('USAW Chapter Release!  Book 1, Chapter 84', 1.0, 84.0, None, ''),
	('USAW RELEASE BOOK 1 CHAPTER 69', 1.0, 69.0, None, ''),
	('USAW RELEASE – BOOK 1, CHAPTER 78', 1.0, 78.0, None, ''),
	('USAW RELEASE – Book 1, Chapter 80', 1.0, 80.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 66', 1.0, 66.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 67', 1.0, 67.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 68', 1.0, 68.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 70', 1.0, 70.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 73 & 74', 1.0, 73.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 75', 1.0, 75.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 76', 1.0, 76.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTER 77', 1.0, 77.0, None, ''),
	('USAW RELEASE — BOOK 1 CHAPTERS 71 + 72', 1.0, 71.0, None, ''),
	('USAW RELEASE: BOOK 1 CHAPTER 63', 1.0, 63.0, None, ''),
	('USAW RELEASE: BOOK 1 CHAPTER 64', 1.0, 64.0, None, ''),
	('USAW RELEASE: BOOK 1 CHAPTER 65', 1.0, 65.0, None, ''),
	('USAW RELEASE: Book 1 Chapter 61', 1.0, 61.0, None, ''),
	('USAW RELEASE: Book 1 Chapter 62', 1.0, 62.0, None, ''),
	('USAW Rease: Book 1 Chapter 5', 1.0, 5.0, None, ''),
	('USAW Release — Book 1 Chapter 45', 1.0, 45.0, None, ''),
	('USAW Release!  Book 1, Chapter 79', 1.0, 79.0, None, ''),
	('USAW Release: Boo1 Chapter 28', None, 28.0, None, ''),
	('USAW Release: Book 1 Chapter 10', 1.0, 10.0, None, ''),
	('USAW Release: Book 1 Chapter 11', 1.0, 11.0, None, ''),
	('USAW Release: Book 1 Chapter 12', 1.0, 12.0, None, ''),
	('USAW Release: Book 1 Chapter 13', 1.0, 13.0, None, ''),
	('USAW Release: Book 1 Chapter 14', 1.0, 14.0, None, ''),
	('USAW Release: Book 1 Chapter 15', 1.0, 15.0, None, ''),
	('USAW Release: Book 1 Chapter 16', 1.0, 16.0, None, ''),
	('USAW Release: Book 1 Chapter 17', 1.0, 17.0, None, ''),
	('USAW Release: Book 1 Chapter 18', 1.0, 18.0, None, ''),
	('USAW Release: Book 1 Chapter 19', 1.0, 19.0, None, ''),
	('USAW Release: Book 1 Chapter 20', 1.0, 20.0, None, ''),
	('USAW Release: Book 1 Chapter 21', 1.0, 21.0, None, ''),
	('USAW Release: Book 1 Chapter 22', 1.0, 22.0, None, ''),
	('USAW Release: Book 1 Chapter 23', 1.0, 23.0, None, ''),
	('USAW Release: Book 1 Chapter 24', 1.0, 24.0, None, ''),
	('USAW Release: Book 1 Chapter 25', 1.0, 25.0, None, ''),
	('USAW Release: Book 1 Chapter 26', 1.0, 26.0, None, ''),
	('USAW Release: Book 1 Chapter 27', 1.0, 27.0, None, ''),
	('USAW Release: Book 1 Chapter 29', 1.0, 29.0, None, ''),
	('USAW Release: Book 1 Chapter 30', 1.0, 30.0, None, ''),
	('USAW Release: Book 1 Chapter 31', 1.0, 31.0, None, ''),
	('USAW Release: Book 1 Chapter 32', 1.0, 32.0, None, ''),
	('USAW Release: Book 1 Chapter 33 + 34', 1.0, 33.0, None, ''),
	('USAW Release: Book 1 Chapter 35 + 36', 1.0, 35.0, None, ''),
	('USAW Release: Book 1 Chapter 37', 1.0, 37.0, None, ''),
	('USAW Release: Book 1 Chapter 38', 1.0, 38.0, None, ''),
	('USAW Release: Book 1 Chapter 39 + 40', 1.0, 39.0, None, ''),
	('USAW Release: Book 1 Chapter 41 + 42', 1.0, 41.0, None, ''),
	('USAW Release: Book 1 Chapter 43', 1.0, 43.0, None, ''),
	('USAW Release: Book 1 Chapter 44', 1.0, 44.0, None, ''),
	('USAW Release: Book 1 Chapter 46 + 47', 1.0, 46.0, None, ''),
	('USAW Release: Book 1 Chapter 48 + 49', 1.0, 48.0, None, ''),
	('USAW Release: Book 1 Chapter 52', 1.0, 52.0, None, ''),
	('USAW Release: Book 1 Chapter 53', 1.0, 53.0, None, ''),
	('USAW Release: Book 1 Chapter 54', 1.0, 54.0, None, ''),
	('USAW Release: Book 1 Chapter 55 + 56', 1.0, 55.0, None, ''),
	('USAW Release: Book 1 Chapter 57 + 58', 1.0, 57.0, None, ''),
	('USAW Release: Book 1 Chapter 6', 1.0, 6.0, None, ''),
	('USAW Release: Book 1 Chapter 60', 1.0, 60.0, None, ''),
	('USAW Release: Book 1 Chapter 7', 1.0, 7.0, None, ''),
	('USAW Release: Book 1 Chapter 8', 1.0, 8.0, None, ''),
	('USAW Release: Book 1 Chapter 9', 1.0, 9.0, None, ''),
	('USAW Release: Chapter 50 + 51', None, 50.0, None, ''),
	('USAW Release: book 1 chapter 59', 1.0, 59.0, None, ''),
	('UUTS Chapter 36 – Broken Spear', None, 36.0, None, ''),
	('UVB II – Introduction', None, None, None, ''),
	('UVB – Chapter 100', None, 100.0, None, ''),
	('UVB – Chapter 101', None, 101.0, None, ''),
	('UVB – Chapter 102', None, 102.0, None, ''),
	('UVB – Chapter 103', None, 103.0, None, ''),
	('UVB – Chapter 104', None, 104.0, None, ''),
	('UVB – Chapter 105', None, 105.0, None, ''),
	('UVB – Chapter 106', None, 106.0, None, ''),
	('UVB – Chapter 107', None, 107.0, None, ''),
	('UVB – Chapter 108', None, 108.0, None, ''),
	('UVB – Chapter 109', None, 109.0, None, ''),
	('UVB – Chapter 110', None, 110.0, None, ''),
	('UVB – Chapter 111', None, 111.0, None, ''),
	('UVB – Chapter 112', None, 112.0, None, ''),
	('UVB – Chapter 113', None, 113.0, None, ''),
	('UVB – Chapter 114', None, 114.0, None, ''),
	('UVB – Chapter 115', None, 115.0, None, ''),
	('UVB – Chapter 116', None, 116.0, None, ''),
	('UVB – Chapter 117', None, 117.0, None, ''),
	('UVB – Chapter 118', None, 118.0, None, ''),
	('UVB – Chapter 119', None, 119.0, None, ''),
	('UVB – Chapter 120', None, 120.0, None, ''),
	('UVB – Chapter 121', None, 121.0, None, ''),
	('UVB – Chapter 122', None, 122.0, None, ''),
	('UVB – Chapter 123', None, 123.0, None, ''),
	('UVB – Chapter 124', None, 124.0, None, ''),
	('UVB – Chapter 125', None, 125.0, None, ''),
	('UVB – Chapter 126 (Part 1)', None, 126.0, 1.0, ''),
	('UVB – Chapter Eight', None, 8, None, ''),
	('UVB – Chapter Eighty-Eight', None, 88, None, ''),
	('UVB – Chapter Eighty-Five', None, 85, None, ''),
	('UVB – Chapter Eighty-Four', None, 84, None, ''),
	('UVB – Chapter Eighty-Nine', None, 89, None, ''),
	('UVB – Chapter Eighty-One', None, 81, None, ''),
	('UVB – Chapter Eighty-Three', None, 83, None, ''),
	('UVB – Chapter Eighty-Two', None, 82, None, ''),
	('UVB – Chapter Fifteen', None, 15, None, ''),
	('UVB – Chapter Five', None, 5, None, ''),
	('UVB – Chapter Four', None, 4, None, ''),
	('UVB – Chapter Fourteen', None, 14, None, ''),
	('UVB – Chapter Ninety', None, 90, None, ''),
	('UVB – Chapter Ninety-Eight', None, 98, None, ''),
	('UVB – Chapter Ninety-Five', None, 95, None, ''),
	('UVB – Chapter Ninety-Four', None, 94, None, ''),
	('UVB – Chapter Ninety-Nine', None, 99, None, ''),
	('UVB – Chapter Ninety-One', None, 91, None, ''),
	('UVB – Chapter Ninety-Seven', None, 97, None, ''),
	('UVB – Chapter Ninety-Six', None, 96, None, ''),
	('UVB – Chapter Ninety-Three', None, 93, None, ''),
	('UVB – Chapter Ninety-Two', None, 92, None, ''),
	('UVB – Chapter One', None, 1, None, ''),
	('UVB – Chapter Seventy', None, 70, None, ''),
	('UVB – Chapter Seventy-One', None, 71, None, ''),
	('UVB – Chapter Seventy-Two', None, 72, None, ''),
	('UVB – Chapter Sixty-Nine', None, 69, None, ''),
	('UVB – Chapter Thirteen', None, 13, None, ''),
	('UVB – Chapter Thirty-Six', None, 36, None, ''),
	('UVB – Chapter Thirty-Three', None, 33, None, ''),
	('UVB – Chapter Three', None, 3, None, ''),
	('UVB – Chapter Twenty-Eight', None, 28, None, ''),
	('UVB – Chapter Two', None, 2, None, ''),
	('UVB – Chapters Eighteen to Nineteen', None, 18, None, ''),
	('UVB – Chapters Eighty-Six to Eighty-Seven', None, 86, None, ''),
	('UVB – Chapters Eleven to Twelve', None, 11, None, ''),
	('UVB – Chapters Fifty-Five to Fifty-Six', None, 55, None, ''),
	('UVB – Chapters Fifty-Nine to Sixty', None, 59, None, ''),
	('UVB – Chapters Fifty-One to Fifty-Two', None, 51, None, ''),
	('UVB – Chapters Fifty-Three to Fifty-Four', None, 53, None, ''),
	('UVB – Chapters Forty-Five to Forty-Six', None, 45, None, ''),
	('UVB – Chapters Forty-Nine to Fifty', None, 49, None, ''),
	('UVB – Chapters Forty-One to Forty-Two', None, 41, None, ''),
	('UVB – Chapters Forty-Seven to Forty-Eight', None, 47, None, ''),
	('UVB – Chapters Forty-Three to Forty-Four', None, 43, None, ''),
	('UVB – Chapters Nine to Ten', None, 9, None, ''),
	('UVB – Chapters Seventy-Five to Seventy-Six', None, 75, None, ''),
	('UVB – Chapters Seventy-Nine to Eighty', None, 79, None, ''),
	('UVB – Chapters Seventy-Seven to Seventy-Eight', None, 77, None, ''),
	('UVB – Chapters Seventy-Three to Seventy-Four', None, 73, None, ''),
	('UVB – Chapters Six to Seven', None, 6, None, ''),
	('UVB – Chapters Sixteen to Seventeen', None, 16, None, ''),
	('UVB – Chapters Sixty-Five to Sixty-Six', None, 65, None, ''),
	('UVB – Chapters Sixty-One to Sixty-Two', None, 61, None, ''),
	('UVB – Chapters Sixty-Seven to Sixty-Eight', None, 67, None, ''),
	('UVB – Chapters Sixty-Three to Sixty-Four', None, 63, None, ''),
	('UVB – Chapters Thirty-Four to Thirty-Five', None, 34, None, ''),
	('UVB – Chapters Thirty-Nine to Forty', None, 39, None, ''),
	('UVB – Chapters Thirty-One to Thirty-Two', None, 31, None, ''),
	('UVB – Chapters Thirty-Seven to Thirty-Eight', None, 37, None, ''),
	('UVB – Chapters Twenty to Twenty-One', None, 20, None, ''),
	('UVB – Chapters Twenty-Four to Twenty-Five', None, 24, None, ''),
	('UVB – Chapters Twenty-Nine to Thirty', None, 29, None, ''),
	('UVB – Chapters Twenty-Six to Twenty-Seven', None, 26, None, ''),
	('UVB – Chapters Twenty-Two to Twenty-Three', None, 22, None, ''),
	('UVB- Chapters Fifty-Seven to Fifty-Eight', None, 57, None, ''),
	('UchiMusume Manga – Chapter 01', None, 1.0, None, ''),
	('UchiMusume – Chapter 07', None, 7.0, None, ''),
	('UchiMusume – Chapter 08', None, 8.0, None, ''),
	('UchiMusume – Chapter 09', None, 9.0, None, ''),
	('UchiMusume – Chapter 10', None, 10.0, None, ''),
	('UchiMusume – Chapter 11', None, 11.0, None, ''),
	('UchiMusume – Chapter 12', None, 12.0, None, ''),
	('UchiMusume – Chapter 13', None, 13.0, None, ''),
	('UchiMusume – Chapter 14', None, 14.0, None, ''),
	('UchiMusume – Chapter 15', None, 15.0, None, ''),
	('UchiMusume – Chapter 16', None, 16.0, None, ''),
	('UchiMusume – Chapter 17', None, 17.0, None, ''),
	('UchiMusume – Chapter 18', None, 18.0, None, ''),
	('UchiMusume – Chapter 19', None, 19.0, None, ''),
	('UchiMusume – Chapter 20', None, 20.0, None, ''),
	('UchiMusume – Chapter 21', None, 21.0, None, ''),
	('UchiMusume – Chapter 22', None, 22.0, None, ''),
	('UchiMusume – Chapter 23', None, 23.0, None, ''),
	('UchiMusume – Chapter 24', None, 24.0, None, ''),
	('UchiMusume – Chapter 25', None, 25.0, None, ''),
	('UchiMusume – Chapter 26', None, 26.0, None, ''),
	('UchiMusume – Chapter 27', None, 27.0, None, ''),
	('UchiMusume – Chapter 28', None, 28.0, None, ''),
	('UchiMusume – Chapter 29', None, 29.0, None, ''),
	('UchiMusume – Chapter 30', None, 30.0, None, ''),
	('UchiMusume – Chapter 31', None, 31.0, None, ''),
	('UchiMusume – Chapter 32', None, 32.0, None, ''),
	('UchiMusume – Chapter 33', None, 33.0, None, ''),
	('UchiMusume – Chapter 34', None, 34.0, None, ''),
	('UchiMusume – Chapter 35', None, 35.0, None, ''),
	('UchiMusume – Chapter 36', None, 36.0, None, ''),
	('UchiMusume – Chapter 37', None, 37.0, None, ''),
	('UchiMusume – Chapter 38', None, 38.0, None, ''),
	('UchiMusume – Chapter 39', None, 39.0, None, ''),
	('UchiMusume – Chapter 40', None, 40.0, None, ''),
	('UchiMusume – Chapter 42', None, 42.0, None, ''),
	('UchiMusume – Chapter 43', None, 43.0, None, ''),
	('UchiMusume – Chapter 44', None, 44.0, None, ''),
	('UchiMusume – Chapter 45', None, 45.0, None, ''),
	('UchiMusume – Chapter 46', None, 46.0, None, ''),
	('UchiNara Volume 1 Introduction + Chapter 1', 1.0, 1.0, None, ''),
	('Uchimusume – Chapter 41', None, 41.0, None, ''),
	('Ugh', None, None, None, ''),
	('Uhh… Hi?', None, None, None, ''),
	('Ultimate Antihero', None, None, None, ''),
	('Ultimate Antihero:Registration Page', None, None, None, ''),
	('Ultimate Antihero:Volume 1 Chapter 1', 1.0, 1.0, None, ''),
	('Ultimate Antihero:Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('Ultimate Antihero:Volume 1 Illustrations', 1.0, None, None, 'Illustrations'),
	('Ultimate Antihero:Volume 2 Illustrations', 2.0, None, None, 'Illustrations'),
	('Ultimate Antihero:Volume 3 Illustrations', 3.0, None, None, 'Illustrations'),
	('Ultimate Antihero:Volume 4', 4.0, None, None, ''),
	('Ultimate Antihero:Volume 4 Afterword', 4.0, None, None, 'Afterword'),
	('Ultimate Antihero:Volume 4 Chapter 1', 4.0, 1.0, None, ''),
	('Ultimate Antihero:Volume 4 Chapter 2', 4.0, 2.0, None, ''),
	('Ultimate Antihero:Volume 4 Chapter 4', 4.0, 4.0, None, ''),
	('Ultimate Antihero:Volume 4 Chapter 5', 4.0, 5.0, None, ''),
	('Ultimate Antihero:Volume 4 Epilogue', 4.0, None, None, 'Epilogue'),
	('Ultimate Antihero:Volume 4 Illustrations', 4.0, None, None, 'Illustrations'),
	('Ultimate Antihero:Volume 4 Prologue', 4.0, None, None, 'Prologue'),
	('Ultimate Assassin System – Chapter 1', None, 1.0, None, ''),
	('Ultimate Assassin System – Chapter 2', None, 2.0, None, ''),
	('Ultimate Assassin System – Chapter 3', None, 3.0, None, ''),
	('Ultimate Assassin System – Chapter 4', None, 4.0, None, ''),
	('Ultimate Assassin System – Index', None, None, None, ''),
	('Ultimate Assassin System: Chapter 5  – The First System Mission', None, 5.0, None, ''),
	('Ultimate Assassin System: Chapter 6 – Spying on Father York', None, 6.0, None, ''),
	('Ultimate Assassin System: Chapter 7 – For Whom Was The Bell Rung?', None, 7.0, None, ''),
	('Ultimate Assassin System: Chapter 8 – The Annihilation of Little Stone Village', None, 8.0, None, ''),
	('Ultimate Assassin System: Chapter 9 -Tang En’s Fury', None, 9.0, None, ''),
	('Ultimate sadness; an unrelated side-note', None, None, None, ''),
	('Unadon here', None, None, None, ''),
	('Unborn – Chapter 1', None, 1, None, ''),
	('Unborn – Chapter 2', None, 2, None, ''),
	('Unborn – Prologue', None, None, None, 'Prologue'),
	('Unbreakable (Being Revised)', None, None, None, ''),
	('Uncharted Regrets Online', None, None, None, ''),
	('Uncharted Territory', None, None, None, ''),
	('Undead Life(?) V1C5 is out!', 1.0, 5.0, None, ''),
	('Undead Life(?) V1C6: Not everything is convenient, y’know?', 1.0, 6.0, None, ''),
	('Undead Life(?) V1C7 is here! The start of a battle!', 1.0, 7.0, None, ''),
	('Undead Life(?) V1C8 is here — only 36 minutes late!', 1.0, 8.0, None, ''),
	('Undead Life(?) VⅠC4 has arrived!', None, 4.0, None, ''),
	('Undead Seeks Warmth – Chapter 1-2', None, 1, 2, ''),
	('Undead Seeks Warmth – Chapter 1-4', None, 1, 4, ''),
	('Undead Seeks Warmth – Chapter 10', None, 10.0, None, ''),
	('Undead Seeks Warmth – Chapter 11', None, 11.0, None, ''),
	('Undead Seeks Warmth – Chapter 12', None, 12.0, None, ''),
	('Undead Seeks Warmth – Chapter 13', None, 13.0, None, ''),
	('Undead Seeks Warmth – Chapter 14', None, 14.0, None, ''),
	('Undead Seeks Warmth – Chapter 15', None, 15.0, None, ''),
	('Undead Seeks Warmth – Chapter 16', None, 16.0, None, ''),
	('Undead Seeks Warmth – Chapter 17', None, 17.0, None, ''),
	('Undead Seeks Warmth – Chapter 18', None, 18.0, None, ''),
	('Undead Seeks Warmth – Chapter 19', None, 19.0, None, ''),
	('Undead Seeks Warmth – Chapter 20', None, 20.0, None, ''),
	('Undead Seeks Warmth – Chapter 21', None, 21.0, None, ''),
	('Undead Seeks Warmth – Chapter 22', None, 22.0, None, ''),
	('Undead Seeks Warmth – Chapter 23', None, 23.0, None, ''),
	('Undead Seeks Warmth – Chapter 24', None, 24.0, None, ''),
	('Undead Seeks Warmth – Chapter 25', None, 25.0, None, ''),
	('Undead Seeks Warmth – Chapter 26', None, 26.0, None, ''),
	('Undead Seeks Warmth – Chapter 27', None, 27.0, None, ''),
	('Undead Seeks Warmth – Chapter 28', None, 28.0, None, ''),
	('Undead Seeks Warmth – Chapter 29', None, 29.0, None, ''),
	('Undead Seeks Warmth – Chapter 3', None, 3.0, None, ''),
	('Undead Seeks Warmth – Chapter 30', None, 30.0, None, ''),
	('Undead Seeks Warmth – Chapter 31', None, 31.0, None, ''),
	('Undead Seeks Warmth – Chapter 32', None, 32.0, None, ''),
	('Undead Seeks Warmth – Chapter 34', None, 34.0, None, ''),
	('Undead Seeks Warmth – Chapter 4', None, 4.0, None, ''),
	('Undead Seeks Warmth – Chapter 5', None, 5.0, None, ''),
	('Undead Seeks Warmth – Chapter 5-8', None, 5, 8, ''),
	('Undead Seeks Warmth – Chapter 6', None, 6.0, None, ''),
	('Undead Seeks Warmth – Chapter 7', None, 7.0, None, ''),
	('Undead Seeks Warmth – Chapter 8', None, 8.0, None, ''),
	('Undead Seeks Warmth – Chapter 9', None, 9.0, None, ''),
	('Undead Seeks Warmth – Idle Talk 1', None, 1.0, None, ''),
	('Undead Seeks Warmth – Idle talk 2', None, 2.0, None, ''),
	('Undead Seeks Warmth – Idle talk 3', None, 3.0, None, ''),
	('Undead Seeks Warmth – The Angel Vows in Front of the Raven’s Grave', None, None, None, ''),
	('Undefeated Bahamut Chronicle Light Novel Series Gets TV Anime', None, None, None, ''),
	('Undefeated God of War Chapter 1', None, 1.0, None, ''),
	('Undefeated God of War Chapter 10', None, 10.0, None, ''),
	('Undefeated God of War Chapter 100', None, 100.0, None, ''),
	('Undefeated God of War Chapter 101', None, 101.0, None, ''),
	('Undefeated God of War Chapter 102', None, 102.0, None, ''),
	('Undefeated God of War Chapter 103', None, 103.0, None, ''),
	('Undefeated God of War Chapter 104', None, 104.0, None, ''),
	('Undefeated God of War Chapter 105', None, 105.0, None, ''),
	('Undefeated God of War Chapter 106', None, 106.0, None, ''),
	('Undefeated God of War Chapter 107', None, 107.0, None, ''),
	('Undefeated God of War Chapter 108', None, 108.0, None, ''),
	('Undefeated God of War Chapter 109', None, 109.0, None, ''),
	('Undefeated God of War Chapter 11', None, 11.0, None, ''),
	('Undefeated God of War Chapter 110', None, 110.0, None, ''),
	('Undefeated God of War Chapter 111', None, 111.0, None, ''),
	('Undefeated God of War Chapter 112', None, 112.0, None, ''),
	('Undefeated God of War Chapter 113', None, 113.0, None, ''),
	('Undefeated God of War Chapter 114', None, 114.0, None, ''),
	('Undefeated God of War Chapter 115', None, 115.0, None, ''),
	('Undefeated God of War Chapter 116', None, 116.0, None, ''),
	('Undefeated God of War Chapter 117', None, 117.0, None, ''),
	('Undefeated God of War Chapter 118', None, 118.0, None, ''),
	('Undefeated God of War Chapter 119', None, 119.0, None, ''),
	('Undefeated God of War Chapter 12', None, 12.0, None, ''),
	('Undefeated God of War Chapter 120', None, 120.0, None, ''),
	('Undefeated God of War Chapter 121', None, 121.0, None, ''),
	('Undefeated God of War Chapter 122', None, 122.0, None, ''),
	('Undefeated God of War Chapter 123', None, 123.0, None, ''),
	('Undefeated God of War Chapter 124', None, 124.0, None, ''),
	('Undefeated God of War Chapter 125', None, 125.0, None, ''),
	('Undefeated God of War Chapter 126', None, 126.0, None, ''),
	('Undefeated God of War Chapter 127', None, 127.0, None, ''),
	('Undefeated God of War Chapter 128', None, 128.0, None, ''),
	('Undefeated God of War Chapter 129', None, 129.0, None, ''),
	('Undefeated God of War Chapter 13', None, 13.0, None, ''),
	('Undefeated God of War Chapter 130', None, 130.0, None, ''),
	('Undefeated God of War Chapter 131', None, 131.0, None, ''),
	('Undefeated God of War Chapter 132', None, 132.0, None, ''),
	('Undefeated God of War Chapter 133', None, 133.0, None, ''),
	('Undefeated God of War Chapter 134', None, 134.0, None, ''),
	('Undefeated God of War Chapter 135', None, 135.0, None, ''),
	('Undefeated God of War Chapter 136', None, 136.0, None, ''),
	('Undefeated God of War Chapter 137', None, 137.0, None, ''),
	('Undefeated God of War Chapter 138', None, 138.0, None, ''),
	('Undefeated God of War Chapter 139', None, 139.0, None, ''),
	('Undefeated God of War Chapter 14', None, 14.0, None, ''),
	('Undefeated God of War Chapter 140', None, 140.0, None, ''),
	('Undefeated God of War Chapter 141', None, 141.0, None, ''),
	('Undefeated God of War Chapter 142', None, 142.0, None, ''),
	('Undefeated God of War Chapter 143', None, 143.0, None, ''),
	('Undefeated God of War Chapter 144', None, 144.0, None, ''),
	('Undefeated God of War Chapter 145', None, 145.0, None, ''),
	('Undefeated God of War Chapter 146', None, 146.0, None, ''),
	('Undefeated God of War Chapter 15', None, 15.0, None, ''),
	('Undefeated God of War Chapter 16', None, 16.0, None, ''),
	('Undefeated God of War Chapter 17', None, 17.0, None, ''),
	('Undefeated God of War Chapter 18', None, 18.0, None, ''),
	('Undefeated God of War Chapter 19', None, 19.0, None, ''),
	('Undefeated God of War Chapter 2', None, 2.0, None, ''),
	('Undefeated God of War Chapter 20', None, 20.0, None, ''),
	('Undefeated God of War Chapter 21', None, 21.0, None, ''),
	('Undefeated God of War Chapter 22', None, 22.0, None, ''),
	('Undefeated God of War Chapter 23', None, 23.0, None, ''),
	('Undefeated God of War Chapter 24', None, 24.0, None, ''),
	('Undefeated God of War Chapter 25', None, 25.0, None, ''),
	('Undefeated God of War Chapter 26', None, 26.0, None, ''),
	('Undefeated God of War Chapter 27', None, 27.0, None, ''),
	('Undefeated God of War Chapter 28', None, 28.0, None, ''),
	('Undefeated God of War Chapter 29', None, 29.0, None, ''),
	('Undefeated God of War Chapter 3', None, 3.0, None, ''),
	('Undefeated God of War Chapter 30', None, 30.0, None, ''),
	('Undefeated God of War Chapter 31', None, 31.0, None, ''),
	('Undefeated God of War Chapter 32', None, 32.0, None, ''),
	('Undefeated God of War Chapter 33', None, 33.0, None, ''),
	('Undefeated God of War Chapter 34', None, 34.0, None, ''),
	('Undefeated God of War Chapter 35', None, 35.0, None, ''),
	('Undefeated God of War Chapter 36', None, 36.0, None, ''),
	('Undefeated God of War Chapter 37', None, 37.0, None, ''),
	('Undefeated God of War Chapter 38', None, 38.0, None, ''),
	('Undefeated God of War Chapter 39', None, 39.0, None, ''),
	('Undefeated God of War Chapter 4-5-6', None, None, None, ''),
	('Undefeated God of War Chapter 40', None, 40.0, None, ''),
	('Undefeated God of War Chapter 41', None, 41.0, None, ''),
	('Undefeated God of War Chapter 42', None, 42.0, None, ''),
	('Undefeated God of War Chapter 43', None, 43.0, None, ''),
	('Undefeated God of War Chapter 44', None, 44.0, None, ''),
	('Undefeated God of War Chapter 45', None, 45.0, None, ''),
	('Undefeated God of War Chapter 46', None, 46.0, None, ''),
	('Undefeated God of War Chapter 47', None, 47.0, None, ''),
	('Undefeated God of War Chapter 48', None, 48.0, None, ''),
	('Undefeated God of War Chapter 49', None, 49.0, None, ''),
	('Undefeated God of War Chapter 50', None, 50.0, None, ''),
	('Undefeated God of War Chapter 51', None, 51.0, None, ''),
	('Undefeated God of War Chapter 52', None, 52.0, None, ''),
	('Undefeated God of War Chapter 53', None, 53.0, None, ''),
	('Undefeated God of War Chapter 54', None, 54.0, None, ''),
	('Undefeated God of War Chapter 55', None, 55.0, None, ''),
	('Undefeated God of War Chapter 56', None, 56.0, None, ''),
	('Undefeated God of War Chapter 57', None, 57.0, None, ''),
	('Undefeated God of War Chapter 58', None, 58.0, None, ''),
	('Undefeated God of War Chapter 59', None, 59.0, None, ''),
	('Undefeated God of War Chapter 60', None, 60.0, None, ''),
	('Undefeated God of War Chapter 61', None, 61.0, None, ''),
	('Undefeated God of War Chapter 62', None, 62.0, None, ''),
	('Undefeated God of War Chapter 63', None, 63.0, None, ''),
	('Undefeated God of War Chapter 64', None, 64.0, None, ''),
	('Undefeated God of War Chapter 65', None, 65.0, None, ''),
	('Undefeated God of War Chapter 66', None, 66.0, None, ''),
	('Undefeated God of War Chapter 67', None, 67.0, None, ''),
	('Undefeated God of War Chapter 68', None, 68.0, None, ''),
	('Undefeated God of War Chapter 69', None, 69.0, None, ''),
	('Undefeated God of War Chapter 7', None, 7.0, None, ''),
	('Undefeated God of War Chapter 70', None, 70.0, None, ''),
	('Undefeated God of War Chapter 71', None, 71.0, None, ''),
	('Undefeated God of War Chapter 72', None, 72.0, None, ''),
	('Undefeated God of War Chapter 73', None, 73.0, None, ''),
	('Undefeated God of War Chapter 74', None, 74.0, None, ''),
	('Undefeated God of War Chapter 75', None, 75.0, None, ''),
	('Undefeated God of War Chapter 76', None, 76.0, None, ''),
	('Undefeated God of War Chapter 76- Update', None, 76.0, None, ''),
	('Undefeated God of War Chapter 77', None, 77.0, None, ''),
	('Undefeated God of War Chapter 78', None, 78.0, None, ''),
	('Undefeated God of War Chapter 79', None, 79.0, None, ''),
	('Undefeated God of War Chapter 8', None, 8.0, None, ''),
	('Undefeated God of War Chapter 80', None, 80.0, None, ''),
	('Undefeated God of War Chapter 81', None, 81.0, None, ''),
	('Undefeated God of War Chapter 82', None, 82.0, None, ''),
	('Undefeated God of War Chapter 83', None, 83.0, None, ''),
	('Undefeated God of War Chapter 84', None, 84.0, None, ''),
	('Undefeated God of War Chapter 85', None, 85.0, None, ''),
	('Undefeated God of War Chapter 86', None, 86.0, None, ''),
	('Undefeated God of War Chapter 87', None, 87.0, None, ''),
	('Undefeated God of War Chapter 88', None, 88.0, None, ''),
	('Undefeated God of War Chapter 89', None, 89.0, None, ''),
	('Undefeated God of War Chapter 9', None, 9.0, None, ''),
	('Undefeated God of War Chapter 90', None, 90.0, None, ''),
	('Undefeated God of War Chapter 91', None, 91.0, None, ''),
	('Undefeated God of War Chapter 92', None, 92.0, None, ''),
	('Undefeated God of War Chapter 93', None, 93.0, None, ''),
	('Undefeated God of War Chapter 94', None, 94.0, None, ''),
	('Undefeated God of War Chapter 95', None, 95.0, None, ''),
	('Undefeated God of War Chapter 96', None, 96.0, None, ''),
	('Undefeated God of War Chapter 97', None, 97.0, None, ''),
	('Undefeated God of War Chapter 98', None, 98.0, None, ''),
	('Undefeated God of War Chapter 99', None, 99.0, None, ''),
	('Undeniable Attraction', None, None, None, ''),
	('Underground Doctor — Chapter 1: Waking Up in Another World — Part 2', None, 1.0, 2.0, ''),
	('Underground Doctor — Chapter 1: Waking up in another world — Part 1', None, 1.0, 1.0, ''),
	('Underground Doctor — Chapter 2: In Order To Earn Quick Money I’ll Preform a Surgery For a Bit — Part 1', None, 2.0, 1.0, ''),
	('Underground Doctor — Chapter 2: In Order To Earn Quick Money I’ll Preform a Surgery For a Bit — Part 2', None, 2.0, 2.0, ''),
	('Underground Doctor — Prologue', None, None, None, 'Prologue'),
	('Undeserving not even rant (but gets a little personal… hmm)', None, None, None, ''),
	('Undying Assassins May 2016', None, 2016.0, None, ''),
	('Unedited Poll', None, None, None, ''),
	('Unedited version', None, None, None, ''),
	('Unemploymented Hero\nSoul Collector\nChapter 1: Episode 1 His own knack\n~Part ½~', None, 1.0, None, ''),
	('Unexpected', None, None, None, ''),
	('Unexplored Summon://Blood-Sign (Indonesia):Volume 1', 1.0, None, None, ''),
	('Unforgettable Weeks by Jay Cantrell', None, None, None, ''),
	('Unfortunate delay', None, None, None, ''),
	('Unintended Desires', None, None, None, ''),
	('Union in Crisis (Book 1, Union Trilogy) by Reluctant_Sir', 1.0, None, None, ''),
	('Unique Cantonese Word: “漏齙”', None, None, None, ''),
	('Universal Sword God Chapter 3: Heaven’s Divine Manual', None, 3.0, None, ''),
	('Universal Sword God Chapter 4: A Bad Performance', None, 4.0, None, ''),
	('Universal Sword God Chapter 9: Frightening Judgement', None, 9.0, None, ''),
	('Unknown', None, None, None, ''),
	('Unknown Love', None, None, None, ''),
	('Unknown Love part 2', None, None, 2.0, ''),
	('Unleashing The Inner Godzilla', None, None, None, ''),
	('Unlikely Good', None, None, None, ''),
	('Unlimited Fafnir', None, None, None, ''),
	('Unlimited Fafnir:Updates', None, None, None, ''),
	('Unlimited Fafnir:Volume 12 Illustrations', 12.0, None, None, 'Illustrations'),
	('Unlimited Fafnir:Volume 12 Prologue', 12.0, None, None, 'Prologue'),
	('Unlimited Fafnir:Volume 3 Chapter 1', 3.0, 1.0, None, ''),
	('Unplanned Surprise!', None, None, None, ''),
	('Unreal, please watch his video to help the poor guy out!!', None, None, None, ''),
	('Unrelated with Slime and Homuculus', None, None, None, ''),
	('Unrelease Schedule', None, None, None, ''),
	('Unspoken Love', None, None, None, ''),
	('Unsung Heros', None, None, None, ''),
	('Untamed Desires', None, None, None, ''),
	('Upcoming Chapters Vote', None, None, None, ''),
	('Upcoming Gundam Titles', None, None, None, ''),
	('Upcoming Projects', None, None, None, ''),
	('Upcoming The Song of Swords Schedule Announcement + Streaming', None, None, None, ''),
	('Upcoming changes to already translated chapters and some other stuff', None, None, None, ''),
	('Update', None, None, None, ''),
	('Update #2.', None, 2.0, None, ''),
	('Update #3', None, 3.0, None, ''),
	('Update & Poll', None, None, None, ''),
	('Update -29/02/16', None, None, None, ''),
	('Update 02/06/2016', None, None, None, ''),
	('Update 04/08/15', None, None, None, ''),
	('Update 07/07/2016', None, None, None, ''),
	('Update 07/09/15', None, None, None, ''),
	('Update 10/5', None, 10.0, None, ''),
	('Update 12/3', None, 12.0, None, ''),
	('Update 12/6/15', None, None, None, ''),
	('Update 15/02/2016', None, None, None, ''),
	('Update 16/04/15', None, None, None, ''),
	('Update 17/07/2016', None, None, None, ''),
	('Update 17/8/15', None, None, None, ''),
	('Update 20/5/15', None, None, None, ''),
	('Update 23/08/15', None, None, None, ''),
	('Update 5/13/2016', None, None, None, ''),
	('Update 5/24/2016 *Please vote on poll!*', None, None, None, ''),
	('Update :>', None, None, None, ''),
	('Update CC 10.5 part 4 side A', None, 10.5, 4.0, ''),
	('Update CC Ch 10.5 Part 4 side B', None, 10.5, 4.0, ''),
	('Update CC side D', None, None, None, ''),
	('Update Four | (IMPORTANT TO KNOW) I Tried to Contact Bishoujo’s Author', None, None, None, ''),
	('Update II', None, None, None, ''),
	('Update Log', None, None, None, ''),
	('Update One | New Look', None, None, None, ''),
	('Update Parthios', None, None, None, ''),
	('Update Post: August 14th', None, 14.0, None, ''),
	('Update Projection', None, None, None, ''),
	('Update Schedule', None, None, None, ''),
	('Update Three | Poll and Editor/Translator Recruitment', None, None, None, ''),
	('Update Time! 2-8 is now available', None, 2.0, None, ''),
	('Update Two | School, Motivation, and Hiring', None, None, None, ''),
	('Update YGDA Ch 37', None, 37.0, None, ''),
	('Update YGDA Ch 38', None, 38.0, None, ''),
	('Update YGDA Ch 38 Part A', None, 38.0, None, ''),
	('Update YGDA Ch 40. At Last haha', None, 40.0, None, ''),
	('Update YGDA ch 41', None, 41.0, None, ''),
	('Update [BNM]', None, None, None, ''),
	('Update about Soap!', None, None, None, ''),
	('Update about me', None, None, None, ''),
	('Update again at last... but not the story...', None, None, None, ''),
	('Update and welcome monday!', None, None, None, ''),
	('Update announcement', None, None, None, ''),
	('Update by Forsaken Hero’s Author, Yuuto Ran', None, None, None, ''),
	('Update for KnW Translation', None, None, None, ''),
	('Update for all :)', None, None, None, ''),
	('Update from Pumpkin + New Project Announcement', None, None, None, ''),
	('Update of the update', None, None, None, ''),
	('Update on Current Status', None, None, None, ''),
	('Update on Demon’s Diary!', None, None, None, ''),
	('Update on Donations and schedule', None, None, None, ''),
	('Update on Hardcore OP-ness', None, None, None, ''),
	('Update on Loiterous', None, None, None, ''),
	('Update on Record of A Thousand Lives', None, None, None, ''),
	('Update on Renegade Immortal', None, None, None, ''),
	('Update on Revision & Glossary Progress', None, None, None, ''),
	('Update on SOTR Chapter 182', None, 182.0, None, ''),
	('Update on Schedule Right Now', None, None, None, ''),
	('Update on Schedule: More Stories', None, None, None, ''),
	('Update on The Nine Godheads', None, None, None, ''),
	('Update on Zhan Long', None, None, None, ''),
	('Update on donations (new donation)', None, None, None, ''),
	('Update on my health and stuff…', None, None, None, ''),
	('Update on progress (May 1st) and…call for editor apps! (NOW CLOSED)', None, 1.0, None, ''),
	('Update on progress (by Options)', None, None, None, ''),
	('Update on real life', None, None, None, ''),
	('Update on schedule', None, None, None, ''),
	('Update on status?', None, None, None, ''),
	('Update on stuff', None, None, None, ''),
	('Update on the PDF/EPub', None, None, None, ''),
	('Update on the third Book of The Divine Elements', None, None, None, ''),
	('Update on things and clarifications', None, None, None, ''),
	('Update on this weekend', None, None, None, ''),
	('Update on tonight chapter', None, None, None, ''),
	('Update only', None, None, None, ''),
	('Update progress', None, None, None, ''),
	('Update regarding the team', None, None, None, ''),
	('Update regarding the translations', None, None, None, ''),
	('Update to Editor Selection.', None, None, None, ''),
	('Update to Monster Musume', None, None, None, ''),
	('Update v.2', 2.0, None, None, ''),
	('Update will be at around 12PM today', None, 12.0, None, ''),
	('Update will be at around 12pm', None, 12.0, None, ''),
	('Update – 04/02/2016', None, None, None, ''),
	('Update – 06/08/2016', None, None, None, ''),
	('Update – 18 March 2014', None, 18.0, None, ''),
	('Update – 19 October 2014', None, 19.0, None, ''),
	('Update – 25 July 2014', None, 25.0, None, ''),
	('Update – 27 May 2014', None, 27.0, None, ''),
	('Update – 28 June 2014', None, 28.0, None, ''),
	('Update – 28/04/16', None, None, None, ''),
	('Update – Shit Happened', None, None, None, ''),
	('Update – Temporary Pause', None, None, None, ''),
	('Update!', None, None, None, ''),
	('Update! YGDA ch 39', None, 39.0, None, ''),
	('Update! YGDA ch 45', None, 45.0, None, ''),
	('Update!!', None, None, None, ''),
	('Update!!!!!', None, None, None, ''),
	('Update(This is not a Chapter)', None, None, None, ''),
	('Update(after a long time)', None, None, None, ''),
	('Update, Announcement, and Recruitment', None, None, None, ''),
	("Update, and controversy! Let's discuss gender roles and feminism.", None, None, None, ''),
	('Update...', None, None, None, ''),
	('Update/ Book info + Possible Contest?', None, None, None, ''),
	('Update: About Isekai, and the future', None, None, None, ''),
	("Update: About this week's translation...", None, None, None, ''),
	('Update: April 2016', None, 2016.0, None, ''),
	('Update: August 2015', None, 2015.0, None, ''),
	('Update: August 2016', None, 2016.0, None, ''),
	('Update: Busy', None, None, None, ''),
	('Update: Changes', None, None, None, ''),
	('Update: Chapters starting again', None, None, None, ''),
	('Update: December 2015', None, 2015.0, None, ''),
	('Update: February 2016', None, 2016.0, None, ''),
	('Update: Hey I’m alive', None, None, None, ''),
	('Update: How should I say this?', None, None, None, ''),
	('Update: In response to haters?', None, None, None, ''),
	('Update: January 2016', None, 2016.0, None, ''),
	('Update: Jiang Ye and Ze Tian Ji Tomorrow', None, None, None, ''),
	('Update: July 2015', None, 2015.0, None, ''),
	('Update: July 2016', None, 2016.0, None, ''),
	('Update: June 2016', None, 2016.0, None, ''),
	('Update: Just got my internet back!', None, None, None, ''),
	('Update: Long Overdue', None, None, None, ''),
	('Update: March 2016', None, 2016.0, None, ''),
	('Update: May 2016', None, 2016.0, None, ''),
	('Update: More Novels!! & Recruiting', None, None, None, ''),
	('Update: Near Disaster', None, None, None, ''),
	('Update: New Project', None, None, None, ''),
	('Update: New Series?', None, None, None, ''),
	('Update: New Site is BACK!', None, None, None, ''),
	('Update: Next Chapter Coming This Week', None, None, None, ''),
	('Update: November 2015', None, 2015.0, None, ''),
	('Update: October 2015', None, 2015.0, None, ''),
	('Update: September 2015', None, 2015.0, None, ''),
	('Update: Site Changes & Paypal', None, None, None, ''),
	("Update: So...I'm back", None, None, None, ''),
	('Update: Some novels have moved', None, None, None, ''),
	('Update: There’ll be delays.', None, None, None, ''),
	('Update: XCrossJ Logs', None, None, None, ''),
	('Update: hospital status', None, None, None, ''),
	('Update: \xa0 Next releases', None, None, None, ''),
	('Updated LDM Chapter List', None, None, None, ''),
	('Updated Links & Novel Suggestions', None, None, None, ''),
	('Updated Web Novel Rankings November 2015', None, 2015.0, None, ''),
	('Updated about page', None, None, None, ''),
	('Updates', None, None, None, ''),
	('Updates #1', None, 1.0, None, ''),
	('Updates 23/6/16', None, None, None, ''),
	('Updates Etc.', None, None, None, ''),
	('Updates Poi?', None, None, None, ''),
	('Updates and Announcements', None, None, None, ''),
	('Updates and Delays', None, None, None, ''),
	('Updates and New Page', None, None, None, ''),
	('Updates and Other Things', None, None, None, ''),
	('Updates for Gifting', None, None, None, ''),
	('Updates for series', None, None, None, ''),
	('Updates on Donations and Schedule', None, None, None, ''),
	('Updates on High Speed!', None, None, None, ''),
	('Updates on Menu', None, None, None, ''),
	('Updates updates updates.. No your eyes isn’t deceiving you..', None, None, None, ''),
	('Updates – 18/11/2015', None, None, None, ''),
	('Updates – THWAFG', None, None, None, ''),
	('Updates!', None, None, None, ''),
	('Updates, cuz I can’t go on without being bugged by people.', None, None, None, ''),
	('Updates- tondemo c11', None, 11.0, None, ''),
	('Updates:  2016 Edition #1!', None, 2016.0, None, ''),
	('Updates:  Din No Monshou', None, None, None, ''),
	('Updates:  March', None, None, None, ''),
	('Updates: New Chapters & Finals Stuff', None, None, None, ''),
	('Updates… and no this is not a prank.', None, None, None, ''),
	('Update~', None, None, None, ''),
	('Updating Hosting', None, None, None, ''),
	('Updating The Blog Mobile version', None, None, None, ''),
	('Updating You on the Latest in Korean Entertainment', None, None, None, ''),
	('Upgrading site…', None, None, None, ''),
	('Upgrading the Website!', None, None, None, ''),
	('Upgrading the site, donations and dead projects.', None, None, None, ''),
	('Upload!', None, None, None, ''),
	('Upper World Notice', None, None, None, ''),
	('Upper World – Chapter 10', None, 10.0, None, ''),
	('Upper World – Chapter 15', None, 15.0, None, ''),
	('Upper world – Chapter 11', None, 11.0, None, ''),
	('Upper world – Chapter 16', None, 16.0, None, ''),
	('Upper world – Chapter 9', None, 9.0, None, ''),
	('Ups? Me sorry? More or less', None, None, None, ''),
	('Upstairoids', None, None, None, ''),
	('Urgent! (Lookism)', None, None, None, ''),
	('Urgh', None, None, None, ''),
	('Urinal Rules', None, None, None, ''),
	('User Stats', None, None, None, ''),
	('User talk:127.0.0.1', None, None, None, ''),
	('User talk:Akhdi', None, None, None, ''),
	('User talk:Akishima', None, None, None, ''),
	('User talk:Alaxxis Sade', None, None, None, ''),
	('User talk:Apelmerah', None, None, None, ''),
	('User talk:Araoz', None, None, None, ''),
	('User talk:Atiri', None, None, None, ''),
	('User talk:Baka-Tsuki Update Indonesia', None, None, None, ''),
	('User talk:Bakapervert', None, None, None, ''),
	('User talk:BankaiGoku', None, None, None, ''),
	('User talk:BionicMeerkat', None, None, None, ''),
	('User talk:BloodyKitty', None, None, None, ''),
	('User talk:C.I.U', None, None, None, ''),
	('User talk:Chaos', None, None, None, ''),
	('User talk:Chepot', None, None, None, ''),
	('User talk:Chonan Odayakana', None, None, None, ''),
	('User talk:Cloudii', None, None, None, ''),
	('User talk:Cthaeh', None, None, None, ''),
	('User talk:Darkdraig', None, None, None, ''),
	('User talk:Darkoneko', None, None, None, ''),
	('User talk:Djidji', None, None, None, ''),
	('User talk:DothThouHoist', None, None, None, ''),
	('User talk:Dreamer2908', None, 2908, None, ''),
	('User talk:DreamlessWindow', None, None, None, ''),
	('User talk:Dreyakis', None, None, None, ''),
	('User talk:Ecchi-sama', None, None, None, ''),
	('User talk:EnTruce', None, None, None, ''),
	('User talk:Enderwor', None, None, None, ''),
	('User talk:Enn are', None, None, None, ''),
	('User talk:EusthEnoptEron', None, None, None, ''),
	('User talk:Héresse', None, None, None, ''),
	('User talk:Isko', None, None, None, ''),
	('User talk:Jasonjapi123', None, 123.0, None, ''),
	('User talk:Joegargery', None, None, None, ''),
	('User talk:Kazugaya', None, None, None, ''),
	('User talk:Labestia1', None, 1.0, None, ''),
	('User talk:Libertariot', None, None, None, ''),
	('User talk:Lukuchi1303', None, 1303.0, None, ''),
	('User talk:LunaLupus', None, None, None, ''),
	('User talk:Lunar Vitae', None, None, None, ''),
	('User talk:Maou', None, None, None, ''),
	('User talk:Mic0609', None, 609.0, None, ''),
	('User talk:Nameless angel', None, None, None, ''),
	('User talk:Nura rihan', None, None, None, ''),
	('User talk:Pie', None, None, None, ''),
	('User talk:Renuac', None, None, None, ''),
	('User talk:RikiNutcase', None, None, None, ''),
	('User talk:Robin997', None, 997.0, None, ''),
	('User talk:Rosenmond', None, None, None, ''),
	('User talk:RozenMaiden', None, None, None, ''),
	('User talk:Rumberkren', None, None, None, ''),
	('User talk:Rydenius', None, None, None, ''),
	('User talk:Sakamiyo', None, None, None, ''),
	('User talk:Setia', None, None, None, ''),
	('User talk:Silverhunter', None, None, None, ''),
	('User talk:Sisyfo9', None, 9.0, None, ''),
	('User talk:SteinKun', None, None, None, ''),
	('User talk:Stuck-in-time', None, None, None, ''),
	('User talk:Teh Ping', None, None, None, ''),
	('User talk:Tony Yon', None, None, None, ''),
	('User talk:Toshiya', None, None, None, ''),
	('User talk:Translatebear', None, None, None, ''),
	('User talk:Translucent', None, None, None, ''),
	('User talk:Trustno1', None, 1.0, None, ''),
	('User talk:Valkyrious', None, None, None, ''),
	('User talk:Velocity7', None, 7.0, None, ''),
	('User talk:Vonfossen', None, None, None, ''),
	('User talk:Warnis', None, None, None, ''),
	('User talk:Ways', None, None, None, ''),
	('User talk:Wolfpup', None, None, None, ''),
	('User talk:Xdtiagonzhar', None, None, None, ''),
	('User talk:Xerox012', None, 12.0, None, ''),
	('User talk:Yascob99', None, 99.0, None, ''),
	('User talk:YoakeNoHikari', None, None, None, ''),
	('User talk:Yoraikun', None, None, None, ''),
	('User talk:ZeeGee', None, None, None, ''),
	('User talk:Zzhk', None, None, None, ''),
	('User talk:変幻出没', None, None, None, ''),
	('Using Tim', None, None, None, ''),
	('Using “volunteer work” as an excuse for non-translations is spitting on the face of the community', None, None, None, ''),
	('UtaPri Anniversary Comic', None, None, None, ''),
	('Utawarerumono Itsuwari no Kamen', None, None, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 0. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 0. Defa (2)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 1. Defa (2)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 10,876. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 10000. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 2601. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 2602. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27753. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27753. Defa (2)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27754. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27754. Defa(2)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27755. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27755. Defa (3)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27755. Defa (4)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27755. Defa(2)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27755. Defa(5)', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 27756. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 3087. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt 9999. Defa', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt Ara', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt Kapanış', None, 1.0, None, ''),
	('Utsuro no Hako - Türkçe:1. Cilt Yazarın Notları', None, 1.0, None, ''),
	('Utsuro no Hako TR:Registration Page', None, None, None, ''),
	('Utsuro no Hako to Zero no Maria', None, None, None, ''),
	('Utsuro no Hako to Zero no Maria (Italian):Volume 3 - 2° Turno', 3.0, 2.0, None, ''),
	('Utsuro no Hako to Zero no Maria (Italian):Volume 5 - Prima che lo spettacolo cominci', 5.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria (Türkçe)', None, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 1', 1.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 2', 2.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 3', 3.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 4', 4.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 5', 5.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 6', 6.0, None, None, ''),
	('Utsuro no Hako to Zero no Maria Volume 7', 7.0, None, None, ''),
	('Utsuro no Hako:Güncellemeler', None, None, None, ''),
	('Utsuro no Hako:Volume 7 Epilogue', 7.0, None, None, 'Epilogue'),
	('Utsuro no Hako:Volume 7 Prologue', 7.0, None, None, 'Prologue'),
	('Utsuro no Hako:Volume1 27756th time', 1.0, 27756.0, None, ''),
	('Utsuro no Hako:Volume2 May 18', 2.0, 18.0, None, ''),
	('Utsuro no Hako:Volume2 May 2', 2.0, 2.0, None, ''),
	('Utsuro no Hako:Volume2 May 4', 2.0, 4.0, None, ''),
	('Utsuro no Hako:Volume3 Beginning', 3.0, None, None, ''),
	('Utsuro no Hako:Volume4 Prologue', 4.0, None, None, 'Prologue'),
	('u should reconsider', None, None, None, ''),
	('unconditional love of a woman', None, None, None, ''),
	('update frequency and new editor!', None, None, None, ''),
	('update on TSOS for the future', None, None, None, ''),
	('updated ill live my 2nd life c1120', None, 1120.0, None, ''),
	('updated ill live my 2nd life c2130', None, 2130.0, None, ''),
	('updated ill live my 2nd life c3140', None, 3140.0, None, ''),
	('updated ill live my 2nd life c4150', None, 4150.0, None, ''),
	('updated ill live my 2nd life c51~60', None, 51.0, None, ''),
	('updated ill live my 2nd life c61~70', None, 61.0, None, ''),
	('updates..', None, None, None, ''),
]

