

data = [
	('JMG CHAPTERS INDEX', None, None, None, ''),
	('JMG Chapters Delay', None, None, None, ''),
	('JMG – Chapter 57', None, 57.0, None, ''),
	('JMG – Chapter 58', None, 58.0, None, ''),
	('JMG – Chapter 59', None, 59.0, None, ''),
	('JMG – Chapter 60', None, 60.0, None, ''),
	('JMG – Chapter 61', None, 61.0, None, ''),
	('JMG – Chapter 62', None, 62.0, None, ''),
	('JMG – Chapter 63', None, 63.0, None, ''),
	('JMG – Chapter 64', None, 64.0, None, ''),
	('JTSPR Prologue', None, None, None, 'Prologue'),
	('JTSPR V1 Chapter 1 Part 2', 1.0, 1.0, 2.0, ''),
	('JTSPR V1: Chapter 1 Part 1', 1.0, 1.0, 1.0, ''),
	('JTSPR V1: Chapter 1 Part 3', 1.0, 1.0, 3.0, ''),
	('JTSPR V1: Chapter 1 Part 4', 1.0, 1.0, 4.0, ''),
	('JTSPR V1: Chapter 2 Part 1', 1.0, 2.0, 1.0, ''),
	('JTSPR V1: Chapter 2 Part 2', 1.0, 2.0, 2.0, ''),
	('JTSPR V1: Chapter 3 Part 1', 1.0, 3.0, 1.0, ''),
	('JTSPR V1: Chapter 3 Part 2', 1.0, 3.0, 2.0, ''),
	('JTSPR V1: Chapter 4 Part 1', 1.0, 4.0, 1.0, ''),
	('JTSPR V1: Chapter 4 Part 2', 1.0, 4.0, 2.0, ''),
	('JTSPR V1: Chapter 4 Part 3', 1.0, 4.0, 3.0, ''),
	('JTSPR V1: Chapter 5 Part 1', 1.0, 5.0, 1.0, ''),
	('JTSPR V1: Chapter 5 Part 2', 1.0, 5.0, 2.0, ''),
	('JTSPR V1: Chapter 6 Part 1', 1.0, 6.0, 1.0, ''),
	('JTSPR V1: Chapter 6 Part 2', 1.0, 6.0, 2.0, ''),
	('JTSPR V1: Chapter 6 Part 3', 1.0, 6.0, 3.0, ''),
	('JTSPR V2: Chapter 1 Part 1', 2.0, 1.0, 1.0, ''),
	('JTSPR V2: Chapter 1 Part 2', 2.0, 1.0, 2.0, ''),
	('JTSPR V2: Chapter 2 Part 1', 2.0, 2.0, 1.0, ''),
	('JTSPR V2: Chapter 2 Part 2', 2.0, 2.0, 2.0, ''),
	('JTSPR V2: Chapter 3 Part 1', 2.0, 3.0, 1.0, ''),
	('JTSPR V2: Chapter 3 Part 2', 2.0, 3.0, 2.0, ''),
	('JTSPR V2: Chapter 4', 2.0, 4.0, None, ''),
	('JTSPR V2: Chapter 5', 2.0, 5.0, None, ''),
	('Jack and Lida', None, None, None, ''),
	("Jack's First Week by Stegro88", None, 88.0, None, ''),
	('Jake and Amelia', None, None, None, ''),
	('January 2016 Announcements', None, 2016.0, None, ''),
	('January 2016 News', None, 2016.0, None, ''),
	('Japan Tragedies Aftermath and Some Moral Lessons', None, None, None, ''),
	('Japanese Language Manga: Vol 12 - 17', 12.0, 17.0, None, ''),
	('Japtem Reader App Downtime', None, None, None, ''),
	('Japtem author beats George RR for 1 ranking period!', None, 1.0, None, ''),
	('Japtem is now translating manhua.', None, None, None, ''),
	('Jashin Average Side Story 01', None, 1, None, 'Side Story 01'),
	('Jashin Average Side Story 02', None, 2, None, 'Side Story 02'),
	('Jashin Average Side Story 03', None, 3, None, 'Side Story 03'),
	('Jashin Average Side Story 03 translated by Vidar', None, 3, None, 'Side Story 03 translated by Vidar'),
	('Jashin Average Side Story 04 translated by Vidar', None, 4, None, 'Side Story 04 translated by Vidar'),
	('Jashin Average – 1', None, 1, None, ''),
	('Jashin Average – 10', None, 10, None, ''),
	('Jashin Average – 11', None, 11, None, ''),
	('Jashin Average – 12', None, 12, None, ''),
	('Jashin Average – 13', None, 13, None, ''),
	('Jashin Average – 14', None, 14, None, ''),
	('Jashin Average – 15', None, 15, None, ''),
	('Jashin Average – 16', None, 16, None, ''),
	('Jashin Average – 17', None, 17, None, ''),
	('Jashin Average – 2', None, 2, None, ''),
	('Jashin Average – 3', None, 3, None, ''),
	('Jashin Average – 4', None, 4, None, ''),
	('Jashin Average – 5', None, 5, None, ''),
	('Jashin Average – 6', None, 6, None, ''),
	('Jashin Average – 7', None, 7, None, ''),
	('Jashin Average – 8', None, 8, None, ''),
	('Jashin Average – 9', None, 9, None, ''),
	('Jashin Sidestory 4', None, 4, None, 'Sidestory 4'),
	('Jashin sidestory 5', None, 5, None, 'sidestory 5'),
	('Jasmin', None, None, None, ''),
	('Jazzed.', None, None, None, ''),
	('Je suis very sorry today', None, None, None, ''),
	('Jealousy-chapter 1', None, 1.0, None, ''),
	("Jessica's Choice", None, None, None, ''),
	('Jet lag', None, None, None, ''),
	('Jiang Hu Lu Wan Wan chapter 1', None, 1.0, None, ''),
	('Jiang Ye (Before Night)  Chapter 38 is out ^.^', None, 38, None, ''),
	('Jiang Ye (Before Night) Chapter 37 is finally out sorry guys', None, 37, None, ''),
	('Jiang Ye (Before Night) Chapter 39', None, 39, None, ''),
	('Jiang Ye Chapter 52', None, 52.0, None, ''),
	('Jiang Ye Chapter 53', None, 53.0, None, ''),
	('Jiang Ye Chapter 54', None, 54.0, None, ''),
	('Jiang Ye Chapter 55', None, 55.0, None, ''),
	('Jiang Ye Chapter 56', None, 56.0, None, ''),
	('Jiang Ye Chapter 57', None, 57.0, None, ''),
	('Jiang Ye Chapter 58', None, 58.0, None, ''),
	('Jiang Ye Chapter 59', None, 59.0, None, ''),
	('Jiang Ye Chapter 60', None, 60.0, None, ''),
	('Jiang Ye Chapter 61', None, 61.0, None, ''),
	('Jiang Ye Chapter 62', None, 62.0, None, ''),
	('Jiang Ye Chapter 63', None, 63.0, None, ''),
	('Jiang Ye Chapter 64', None, 64.0, None, ''),
	('Jiang Ye Chapter 65', None, 65.0, None, ''),
	('Jiang Ye Chapter 66', None, 66.0, None, ''),
	('Jiang Ye Chapter 67', None, 67.0, None, ''),
	('Jiang Ye Chapter 68', None, 68.0, None, ''),
	('Jiang Ye Chapter 69', None, 69.0, None, ''),
	('Jiang Ye Chapter 70', None, 70.0, None, ''),
	('Jiang Ye Chapter 71', None, 71.0, None, ''),
	('Jiang Ye Chapter 72', None, 72.0, None, ''),
	('Jiang Ye Chapter 73', None, 73.0, None, ''),
	('Jiang Ye Chapter 74', None, 74.0, None, ''),
	('Jiang Ye Major Announcement + Chapter 75', None, 75.0, None, ''),
	('Jiang Ye final updates before winter vacation', None, None, None, ''),
	('Jikuu Mahou chaper 163', None, 163.0, None, ''),
	('Jikuu Mahou chapter 100', None, 100.0, None, ''),
	('Jikuu Mahou chapter 101', None, 101.0, None, ''),
	('Jikuu Mahou chapter 102', None, 102.0, None, ''),
	('Jikuu Mahou chapter 103', None, 103.0, None, ''),
	('Jikuu Mahou chapter 104', None, 104.0, None, ''),
	('Jikuu Mahou chapter 105', None, 105.0, None, ''),
	('Jikuu Mahou chapter 108', None, 108.0, None, ''),
	('Jikuu Mahou chapter 109', None, 109.0, None, ''),
	('Jikuu Mahou chapter 110', None, 110.0, None, ''),
	('Jikuu Mahou chapter 111', None, 111.0, None, ''),
	('Jikuu Mahou chapter 112', None, 112.0, None, ''),
	('Jikuu Mahou chapter 113', None, 113.0, None, ''),
	('Jikuu Mahou chapter 114', None, 114.0, None, ''),
	('Jikuu Mahou chapter 115', None, 115.0, None, ''),
	('Jikuu Mahou chapter 116', None, 116.0, None, ''),
	('Jikuu Mahou chapter 117', None, 117.0, None, ''),
	('Jikuu Mahou chapter 118', None, 118.0, None, ''),
	('Jikuu Mahou chapter 119', None, 119.0, None, ''),
	('Jikuu Mahou chapter 120', None, 120.0, None, ''),
	('Jikuu Mahou chapter 121', None, 121.0, None, ''),
	('Jikuu Mahou chapter 122', None, 122.0, None, ''),
	('Jikuu Mahou chapter 123', None, 123.0, None, ''),
	('Jikuu Mahou chapter 126', None, 126.0, None, ''),
	('Jikuu Mahou chapter 127', None, 127.0, None, ''),
	('Jikuu Mahou chapter 128', None, 128.0, None, ''),
	('Jikuu Mahou chapter 129', None, 129.0, None, ''),
	('Jikuu Mahou chapter 132', None, 132.0, None, ''),
	('Jikuu Mahou chapter 135', None, 135.0, None, ''),
	('Jikuu Mahou chapter 136', None, 136.0, None, ''),
	('Jikuu Mahou chapter 137', None, 137.0, None, ''),
	('Jikuu Mahou chapter 138', None, 138.0, None, ''),
	('Jikuu Mahou chapter 139', None, 139.0, None, ''),
	('Jikuu Mahou chapter 145', None, 145.0, None, ''),
	('Jikuu Mahou chapter 146', None, 146.0, None, ''),
	('Jikuu Mahou chapter 147', None, 147.0, None, ''),
	('Jikuu Mahou chapter 154', None, 154.0, None, ''),
	('Jikuu Mahou chapter 155', None, 155.0, None, ''),
	('Jikuu Mahou chapter 156', None, 156.0, None, ''),
	('Jikuu Mahou chapter 162', None, 162.0, None, ''),
	('Jikuu Mahou chapter 164', None, 164.0, None, ''),
	('Jikuu Mahou chapter 165', None, 165.0, None, ''),
	('Jikuu Mahou chapter 168', None, 168.0, None, ''),
	('Jikuu Mahou chapter 169', None, 169.0, None, ''),
	('Jikuu Mahou chapter 170', None, 170.0, None, ''),
	('Jikuu Mahou chapter 171', None, 171.0, None, ''),
	('Jikuu Mahou chapter 172', None, 172.0, None, ''),
	('Jikuu Mahou chapter 175', None, 175.0, None, ''),
	('Jikuu Mahou chapter 178', None, 178.0, None, ''),
	('Jikuu Mahou chapter 179', None, 179.0, None, ''),
	('Jikuu Mahou chapter 180', None, 180.0, None, ''),
	('Jikuu Mahou chapter 182', None, 182.0, None, ''),
	('Jikuu Mahou chapter 183', None, 183.0, None, ''),
	('Jikuu Mahou chapter 184', None, 184.0, None, ''),
	('Jikuu Mahou chapter 185', None, 185.0, None, ''),
	('Jikuu Mahou chapter 186', None, 186.0, None, ''),
	('Jikuu Mahou chapter 187', None, 187.0, None, ''),
	('Jikuu Mahou chapter 188', None, 188.0, None, ''),
	('Jikuu Mahou chapter 190', None, 190.0, None, ''),
	('Jikuu Mahou chapter 191', None, 191.0, None, ''),
	('Jikuu Mahou chapter 196 + side story', None, 196.0, None, 'side story'),
	('Jikuu Mahou chapter 197', None, 197.0, None, ''),
	('Jikuu Mahou chapter 200', None, 200.0, None, ''),
	('Jikuu Mahou chapter 209', None, 209.0, None, ''),
	('Jikuu Mahou chapter 212', None, 212.0, None, ''),
	('Jikuu Mahou chapter 213', None, 213.0, None, ''),
	('Jikuu Mahou chapter 214', None, 214.0, None, ''),
	('Jikuu Mahou chapter 215', None, 215.0, None, ''),
	('Jikuu Mahou chapter 216', None, 216.0, None, ''),
	('Jikuu Mahou chapter 217', None, 217.0, None, ''),
	('Jikuu Mahou chapter 218', None, 218.0, None, ''),
	('Jikuu Mahou chapter 219', None, 219.0, None, ''),
	('Jikuu Mahou chapter 222', None, 222.0, None, ''),
	('Jikuu Mahou chapter 223', None, 223.0, None, ''),
	('Jikuu Mahou chapter 224', None, 224.0, None, ''),
	('Jikuu Mahou chapter 225', None, 225.0, None, ''),
	('Jikuu Mahou chapter 232', None, 232.0, None, ''),
	('Jikuu Mahou chapter 235', None, 235.0, None, ''),
	('Jikuu Mahou chapter 236', None, 236.0, None, ''),
	('Jikuu Mahou chapter 237', None, 237.0, None, ''),
	('Jikuu Mahou chapter 238', None, 238.0, None, ''),
	('Jikuu Mahou chapter 239', None, 239.0, None, ''),
	('Jikuu Mahou chapter 240', None, 240.0, None, ''),
	('Jikuu Mahou chapter 36', None, 36.0, None, ''),
	('Jikuu Mahou chapter 37', None, 37.0, None, ''),
	('Jikuu Mahou chapter 41 release', None, 41.0, None, ''),
	('Jikuu Mahou chapter 42', None, 42.0, None, ''),
	('Jikuu Mahou chapter 43', None, 43.0, None, ''),
	('Jikuu Mahou chapter 44', None, 44.0, None, ''),
	('Jikuu Mahou chapter 45', None, 45.0, None, ''),
	('Jikuu Mahou chapter 46', None, 46.0, None, ''),
	('Jikuu Mahou chapter 47', None, 47.0, None, ''),
	('Jikuu Mahou chapter 48', None, 48.0, None, ''),
	('Jikuu Mahou chapter 49', None, 49.0, None, ''),
	('Jikuu Mahou chapter 50', None, 50.0, None, ''),
	('Jikuu Mahou chapter 51', None, 51.0, None, ''),
	('Jikuu Mahou chapter 52', None, 52.0, None, ''),
	('Jikuu Mahou chapter 53', None, 53.0, None, ''),
	('Jikuu Mahou chapter 54', None, 54.0, None, ''),
	('Jikuu Mahou chapter 55', None, 55.0, None, ''),
	('Jikuu Mahou chapter 56', None, 56.0, None, ''),
	('Jikuu Mahou chapter 58', None, 58.0, None, ''),
	('Jikuu Mahou chapter 59', None, 59.0, None, ''),
	('Jikuu Mahou chapter 60', None, 60.0, None, ''),
	('Jikuu Mahou chapter 61', None, 61.0, None, ''),
	('Jikuu Mahou chapter 62', None, 62.0, None, ''),
	('Jikuu Mahou chapter 63', None, 63.0, None, ''),
	('Jikuu Mahou chapter 64', None, 64.0, None, ''),
	('Jikuu Mahou chapter 65', None, 65.0, None, ''),
	('Jikuu Mahou chapter 66', None, 66.0, None, ''),
	('Jikuu Mahou chapter 67', None, 67.0, None, ''),
	('Jikuu Mahou chapter 68', None, 68.0, None, ''),
	('Jikuu Mahou chapter 69', None, 69.0, None, ''),
	('Jikuu Mahou chapter 70', None, 70.0, None, ''),
	('Jikuu Mahou chapter 75', None, 75.0, None, ''),
	('Jikuu Mahou chapter 76', None, 76.0, None, ''),
	('Jikuu Mahou chapter 77', None, 77.0, None, ''),
	('Jikuu Mahou chapter 78', None, 78.0, None, ''),
	('Jikuu Mahou chapter 79', None, 79.0, None, ''),
	('Jikuu Mahou chapter 82', None, 82.0, None, ''),
	('Jikuu Mahou chapter 83', None, 83.0, None, ''),
	('Jikuu Mahou chapter 84', None, 84.0, None, ''),
	('Jikuu Mahou chapter 85', None, 85.0, None, ''),
	('Jikuu Mahou chapter 86', None, 86.0, None, ''),
	('Jikuu Mahou chapter 87', None, 87.0, None, ''),
	('Jikuu Mahou chapter 88', None, 88.0, None, ''),
	('Jikuu Mahou chapter 89', None, 89.0, None, ''),
	('Jikuu Mahou chapter 92', None, 92.0, None, ''),
	('Jikuu Mahou chapter 93', None, 93.0, None, ''),
	('Jikuu Mahou chapter 94', None, 94.0, None, ''),
	('Jikuu Mahou chapter 95', None, 95.0, None, ''),
	('Jikuu Mahou chapter 96', None, 96.0, None, ''),
	('Jikuu Mahou chapter 97', None, 97.0, None, ''),
	('Jikuu Mahou chapter 98', None, 98.0, None, ''),
	('Jikuu Mahou chapter 99', None, 99.0, None, ''),
	('Jikuu Mahou chapters 106 – 107', None, 106.0, None, ''),
	('Jikuu Mahou chapters 124 – 125', None, 124.0, None, ''),
	('Jikuu Mahou chapters 130-131', None, 130, 131, ''),
	('Jikuu Mahou chapters 133-134', None, 133, 134, ''),
	('Jikuu Mahou chapters 140-141', None, 140, 141, ''),
	('Jikuu Mahou chapters 142 – 144', None, 142.0, None, ''),
	('Jikuu Mahou chapters 148 – 151', None, 148.0, None, ''),
	('Jikuu Mahou chapters 152-153(eu)', None, 152, 153, ''),
	('Jikuu Mahou chapters 157-160', None, 157, 160, ''),
	('Jikuu Mahou chapters 166 – 167', None, 166.0, None, ''),
	('Jikuu Mahou chapters 173-174', None, 173, 174, ''),
	('Jikuu Mahou chapters 176 & 177', None, 176.0, None, ''),
	('Jikuu Mahou chapters 192-193', None, 192, 193, ''),
	('Jikuu Mahou chapters 194-195', None, 194, 195, ''),
	('Jikuu Mahou chapters 198-199', None, 198, 199, ''),
	('Jikuu Mahou chapters 201-202', None, 201, 202, ''),
	('Jikuu Mahou chapters 203-204', None, 203, 204, ''),
	('Jikuu Mahou chapters 205-206', None, 205, 206, ''),
	('Jikuu Mahou chapters 207-208', None, 207, 208, ''),
	('Jikuu Mahou chapters 210-211', None, 210, 211, ''),
	('Jikuu Mahou chapters 220-221', None, 220, 221, ''),
	('Jikuu Mahou chapters 226-228', None, 226, 228, ''),
	('Jikuu Mahou chapters 229-231', None, 229, 231, ''),
	('Jikuu Mahou chapters 23-35 release', None, 23, 35, ''),
	('Jikuu Mahou chapters 233-234', None, 233, 234, ''),
	('Jikuu Mahou chapters 38 – 40', None, 38.0, None, ''),
	('Jikuu Mahou chapters 56.5 and 57', None, 56.5, None, ''),
	('Jikuu Mahou chapters 71 – 74', None, 71.0, None, ''),
	('Jikuu Mahou chapters 80 – 81', None, 80.0, None, ''),
	('Jikuu Mahou chapters 90 – 91', None, 90.0, None, ''),
	('Jikuu Mahou chapters release', None, None, None, ''),
	('Jikuu Mahou chater 189', None, 189.0, None, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 0-1', None, 0, 1, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 11', None, 11.0, None, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 12-13', None, 12, 13, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 14-22', None, 14, 22, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 2-4', None, 2, 4, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 5', None, 5.0, None, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 6', None, 6.0, None, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 7', None, 7.0, None, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 8', None, 8.0, None, ''),
	('Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari Chapter 9-10', None, 9, 10, ''),
	('Jikuu Mahuo chapter 181', None, 181.0, None, ''),
	('Jiu Shen Chapter 2 is released', None, 2.0, None, ''),
	('JnH Chapter 14', None, 14.0, None, ''),
	('JnH Chapter 15', None, 15.0, None, ''),
	('JnH Chapter 16', None, 16.0, None, ''),
	('JnH Chapter 17', None, 17.0, None, ''),
	('JnH Chapter 18', None, 18.0, None, ''),
	('JnH Chapter 19', None, 19.0, None, ''),
	('JnH Chapter 20', None, 20.0, None, ''),
	('JnH Chapter 21', None, 21.0, None, ''),
	('JnH Chapter 22', None, 22.0, None, ''),
	('JnH Chapter 23', None, 23.0, None, ''),
	('JnH Chapter 24', None, 24.0, None, ''),
	('JnH Chapter 25', None, 25.0, None, ''),
	('JnH Chapter 27', None, 27.0, None, ''),
	('JnH Chapter 28', None, 28.0, None, ''),
	('JnH Chapter 29', None, 29.0, None, ''),
	('JnH Chapter 30', None, 30.0, None, ''),
	('JnH Chapter 31', None, 31.0, None, ''),
	('JnH Chapter 32', None, 32.0, None, ''),
	('JnH Chapter 33', None, 33.0, None, ''),
	('JnH Chapter 34', None, 34.0, None, ''),
	('JnH Chapter 35', None, 35.0, None, ''),
	('JnH Chapter 37', None, 37.0, None, ''),
	('JnH Chapter 38', None, 38.0, None, ''),
	('JnH Chapter 39', None, 39.0, None, ''),
	('JnH Chapter 40', None, 40.0, None, ''),
	('JnH Chapter Bonus', None, None, None, ''),
	('JnH chapter 36', None, 36.0, None, ''),
	('JoBlEsS – Chapter 21', None, 21.0, None, ''),
	('Job interviews are exhausting', None, None, None, ''),
	('Job – Chapter 1', None, 1, None, ''),
	('Jobless Oblige Chapter 2', None, 2.0, None, ''),
	('Jobless Oblige Chapter 3', None, 3.0, None, ''),
	('Jobless – Chapter 10', None, 10.0, None, ''),
	('Jobless – Chapter 12', None, 12.0, None, ''),
	('Jobless – Chapter 13', None, 13.0, None, ''),
	('Jobless – Chapter 14', None, 14.0, None, ''),
	('Jobless – Chapter 15', None, 15.0, None, ''),
	('Jobless – Chapter 16', None, 16.0, None, ''),
	('Jobless – Chapter 17', None, 17.0, None, ''),
	('Jobless – Chapter 18', None, 18.0, None, ''),
	('Jobless – Chapter 19', None, 19.0, None, ''),
	('Jobless – Chapter 20', None, 20.0, None, ''),
	('Jobless – Chapter 23', None, 23.0, None, ''),
	('Jobless – Chapter 24', None, 24.0, None, ''),
	('Jobless – Chapter 25', None, 25.0, None, ''),
	('Jobless – Chapter 26', None, 26.0, None, ''),
	('Jobless – Chapter 27', None, 27.0, None, ''),
	('Jobless – Chapter 28', None, 28.0, None, ''),
	('Jobless – Chapter 29', None, 29.0, None, ''),
	('Jobless – Chapter 30', None, 30.0, None, ''),
	('Jobless – Chapter 31', None, 31.0, None, ''),
	('Jobless – Chapter 32', None, 32.0, None, ''),
	('Jobless – Chapter 33', None, 33.0, None, ''),
	('Jobless – Chapter 5', None, 5.0, None, ''),
	('Jobless – Chapter 7', None, 7.0, None, ''),
	('Jobless – Chapter 8', None, 8.0, None, ''),
	('Jobless – Chapter 9', None, 9.0, None, ''),
	('Jog (1) – Blue 98', None, 1.0, None, ''),
	('Jog (2) – Blue 98', None, 2.0, None, ''),
	("John's Remembrances", None, None, None, ''),
	('Joker Script', None, None, None, ''),
	("Jokes I've Aquired Over Time. You WILL Giggle :) enjoy!", None, None, None, ''),
	('Jokes and Giggles by Jack Spratt', None, None, None, ''),
	('Journal Entry: Crystals and Mutations', None, None, None, ''),
	('Journal Entry: Harpies', None, None, None, ''),
	('Journey to Seek Past Reincarnations Synopsis', None, None, None, ''),
	('Journey — Chapter 1', None, 1.0, None, ''),
	('Journey — Chapter 2', None, 2.0, None, ''),
	('JuJoku Chapter 2 Part 3', None, 2.0, 3.0, ''),
	('Judgment 16.13', None, 16.13, None, ''),
	('Jui-san no Oshigoto in Isekai - Prologue - Teaser', None, None, None, 'Prologue - Teaser'),
	('July 11th – Status update', None, 11.0, None, ''),
	('July 2014 KLNs', None, 2014, None, ''),
	('July 2015 Announcements', None, 2015.0, None, ''),
	('July 2016 Announcements', None, 2016.0, None, ''),
	('July 23rd – Status Update', None, 23.0, None, ''),
	('July 30th – Status Update', None, 30.0, None, ''),
	('July already…', None, None, None, ''),
	('July is coming to an end…', None, None, None, ''),
	('June (er July) Surprise Teasers! And General status of series', None, None, None, ''),
	('June 2014 KLNs', None, 2014, None, ''),
	('June 2015 Announcements', None, 2015.0, None, ''),
	('June 2016 Announcements', None, 2016.0, None, ''),
	('Jungle Soap - The Beginning', None, None, None, ''),
	('Junior Medical God Chapter 68(Regular)', None, 68.0, None, ''),
	('Junior Medical God Chapter 69 (Preview)', None, 69.0, None, ''),
	('Junior Medical God Chapter 70: Favour of three beauties (Preview)', None, 70.0, None, ''),
	('Jury Duty', None, None, None, ''),
	('Just A Kiss', None, None, None, ''),
	('Just A Straight Road (Part 11)', None, None, 11.0, ''),
	('Just A Straight Road (Part 12)', None, None, 12.0, ''),
	('Just A Straight Road (Part 13)', None, None, 13.0, ''),
	('Just A Straight Road (Part 14)', None, None, 14.0, ''),
	('Just A Straight Road (Part 15)', None, None, 15.0, ''),
	('Just A Straight Road (Part 16)', None, None, 16.0, ''),
	('Just A Straight Road (Part 17)', None, None, 17.0, ''),
	('Just A Straight Road (Part 18)', None, None, 18.0, ''),
	('Just Another Randomness', None, None, None, ''),
	('Just As I Remembered It', None, None, None, ''),
	('Just Dessert', None, None, None, ''),
	('Just Dreaming a Wet Dream', None, None, None, ''),
	('Just Erotic Romance Reviews', None, None, None, ''),
	('Just Fucking Take Me (Being Revised)', None, None, None, ''),
	('Just Get Used To These Things. Plus Rant About Licensing.', None, None, None, ''),
	('Just Kidding, HERE A LITTLE RELEASE. ENJOY~!', None, None, None, ''),
	('Just One Smile filming', None, None, None, ''),
	('Just One Smile is Very Alluring Feature: The Drama', None, None, None, ''),
	('Just One Smile is Very Alluring Feature: The Movie', None, None, None, ''),
	('Just Passing Through by Levi Charon', None, None, None, ''),
	('Just Putting This Out There', None, None, None, ''),
	('Just Some Updates', None, None, None, ''),
	('Just Something Random', None, None, None, ''),
	('Just Starting Up', None, None, None, ''),
	('Just a Little More.', None, None, None, ''),
	('Just a Notice', None, None, None, ''),
	('Just a Straight Road (Part 10)', None, None, 10.0, ''),
	('Just a Straight Road (Part 19)', None, None, 19.0, ''),
	('Just a Straight Road (Part 2)', None, None, 2.0, ''),
	('Just a Straight Road (Part 20)', None, None, 20.0, ''),
	('Just a Straight Road (Part 3)', None, None, 3.0, ''),
	('Just a Straight Road (Part 4)', None, None, 4.0, ''),
	('Just a Straight Road (Part 5)', None, None, 5.0, ''),
	('Just a Straight Road (Part 6)', None, None, 6.0, ''),
	('Just a Straight Road (Part 7)', None, None, 7.0, ''),
	('Just a Straight Road (Part 8)', None, None, 8.0, ''),
	('Just a Straight Road (Part 9)', None, None, 9.0, ''),
	('Just a little announcement', None, None, None, ''),
	('Just a little update', None, None, None, ''),
	('Just a notice; no EGA translations tonight', None, None, None, ''),
	('Just a quick info!', None, None, None, ''),
	('Just a slight delay', None, None, None, ''),
	('Just a small update', None, None, None, ''),
	('Just a thought…', None, None, None, ''),
	('Just an Announcement for Future Works', None, None, None, ''),
	('Just an FYI', None, None, None, ''),
	('Just an FYI for Elqueeness', None, None, None, ''),
	('Just an update', None, None, None, ''),
	('Just an update...', None, None, None, ''),
	('Just announcement', None, None, None, ''),
	('Just for the Time it Takes - Daddy Love Me!', None, None, None, ''),
	('Just friends?! Synopsis + Snippet', None, None, None, ''),
	('Just one day remaining for the Rampage Week!', None, None, None, ''),
	('Just posted this through the wordpress.com linked to the site.', None, None, None, ''),
	('Just read the last 5 chapters of Mushoku Tensei', None, 5, None, ''),
	('Just some announcements', None, None, None, ''),
	('Just some info', None, None, None, ''),
	('Just some news', None, None, None, ''),
	('Just some original short.', None, None, None, ''),
	('Just started a Joint project', None, None, None, ''),
	('Just the usual.', None, None, None, ''),
	('Just to Clarify/State of Affairs', None, None, None, ''),
	('Just to be Clear', None, None, None, ''),
	('Just to clarify', None, None, None, ''),
	('Just visited the doctor..', None, None, None, ''),
	('Just wanna say that I’m still alive', None, None, None, ''),
	('Just wonderin’ (serious)', None, None, None, ''),
	('Just your random post XD', None, None, None, ''),
	('Juvenile Medical God Announcement', None, None, None, ''),
	('Juvenile Medical God Chapter 100', None, 100.0, None, ''),
	('Juvenile Medical God Chapter 101', None, 101.0, None, ''),
	('Juvenile Medical God Chapter 102', None, 102.0, None, ''),
	('Juvenile Medical God Chapter 103', None, 103.0, None, ''),
	('Juvenile Medical God Chapter 104', None, 104.0, None, ''),
	('Juvenile Medical God Chapter 105', None, 105.0, None, ''),
	('Juvenile Medical God Chapter 106', None, 106.0, None, ''),
	('Juvenile Medical God Chapter 107', None, 107.0, None, ''),
	('Juvenile Medical God Chapter 108', None, 108.0, None, ''),
	('Juvenile Medical God Chapter 109', None, 109.0, None, ''),
	('Juvenile Medical God Chapter 43', None, 43.0, None, ''),
	('Juvenile Medical God Chapter 44', None, 44.0, None, ''),
	('Juvenile Medical God Chapter 45', None, 45.0, None, ''),
	('Juvenile Medical God Chapter 46', None, 46.0, None, ''),
	('Juvenile Medical God Chapter 47', None, 47.0, None, ''),
	('Juvenile Medical God Chapter 48', None, 48.0, None, ''),
	('Juvenile Medical God Chapter 49', None, 49.0, None, ''),
	('Juvenile Medical God Chapter 50', None, 50.0, None, ''),
	('Juvenile Medical God Chapter 51', None, 51.0, None, ''),
	('Juvenile Medical God Chapter 52', None, 52.0, None, ''),
	('Juvenile Medical God Chapter 53', None, 53.0, None, ''),
	('Juvenile Medical God Chapter 54', None, 54.0, None, ''),
	('Juvenile Medical God Chapter 55', None, 55.0, None, ''),
	('Juvenile Medical God Chapter 69', None, 69.0, None, ''),
	('Juvenile Medical God Chapter 70', None, 70.0, None, ''),
	('Juvenile Medical God Chapter 71', None, 71.0, None, ''),
	('Juvenile Medical God Chapter 72', None, 72.0, None, ''),
	('Juvenile Medical God Chapter 73', None, 73.0, None, ''),
	('Juvenile Medical God Chapter 74', None, 74.0, None, ''),
	('Juvenile Medical God Chapter 75', None, 75.0, None, ''),
	('Juvenile Medical God Chapter 76', None, 76.0, None, ''),
	('Juvenile Medical God Chapter 77', None, 77.0, None, ''),
	('Juvenile Medical God Chapter 78', None, 78.0, None, ''),
	('Juvenile Medical God Chapter 79', None, 79.0, None, ''),
	('Juvenile Medical God Chapter 80', None, 80.0, None, ''),
	('Juvenile Medical God Chapter 81', None, 81.0, None, ''),
	('Juvenile Medical God Chapter 82', None, 82.0, None, ''),
	('Juvenile Medical God Chapter 83', None, 83.0, None, ''),
	('Juvenile Medical God Chapter 84', None, 84.0, None, ''),
	('Juvenile Medical God Chapter 85', None, 85.0, None, ''),
	('Juvenile Medical God Chapter 86', None, 86.0, None, ''),
	('Juvenile Medical God Chapter 87', None, 87.0, None, ''),
	('Juvenile Medical God Chapter 88', None, 88.0, None, ''),
	('Juvenile Medical God Chapter 89', None, 89.0, None, ''),
	('Juvenile Medical God Chapter 90', None, 90.0, None, ''),
	('Juvenile Medical God Chapter 91', None, 91.0, None, ''),
	('Juvenile Medical God Chapter 92', None, 92.0, None, ''),
	('Juvenile Medical God Chapter 93', None, 93.0, None, ''),
	('Juvenile Medical God Chapter 94', None, 94.0, None, ''),
	('Juvenile Medical God Chapter 95', None, 95.0, None, ''),
	('Juvenile Medical God Chapter 96', None, 96.0, None, ''),
	('Juvenile Medical God Chapter 97', None, 97.0, None, ''),
	('Juvenile Medical God Chapter 98', None, 98.0, None, ''),
	('Juvenile Medical God Chapter 99', None, 99.0, None, ''),
	('jk not dead + news', None, None, None, ''),
	('jokes that are stupid', None, None, None, ''),
	('just an update NO CHAPTER YET', None, None, None, ''),
	('just an update not a chapter yet…', None, None, None, ''),
	('just edited chapter 11', None, 11.0, None, ''),
	("just read this it's funny! XD", None, None, None, ''),
	('just to prompt everyone’s email about update ~!', None, None, None, ''),
]

