

data = [
	('F*ck', None, None, None, ''),
	('F/A Material, Ha, Ma and Ya Sections complete!', None, None, None, ''),
	('F/A Material, Ka Section complete!', None, None, None, ''),
	('F/A Material, Ra Section complete! Glossary Complete!!!', None, None, None, ''),
	('F/A Material, Sa Section complete!', None, None, None, ''),
	('F/A Material, Ta and Na Sections complete!', None, None, None, ''),
	('FAQ', None, None, None, ''),
	('FAQ, corrections, and other stuff', None, None, None, ''),
	('FE Awakening, Drama CD 2: 9. Now, End the Chain of Sorrow', None, 2.0, None, ''),
	('FE Awakening, Drama CD 4: 1. Just... Who Are You?', None, 4.0, None, ''),
	("FE Awakening, Drama CD 4: 10. Let's Meet Up Again Someday", None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 11. Come Back ver. [M]', None, 4.0, None, ''),
	("FE Awakening, Drama CD 4: 2. She... Really Doesn't Want to Give Up", None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 3. Royal Crown Search Mission (die Tiara Suche Mission)', None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 4. Prepare Yourself, Mountain Creature', None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 5. I Really Think That Hair Ornament Won’t Do', None, 4.0, None, ''),
	("FE Awakening, Drama CD 4: 6. We're a Shameful, Unarmed Militia", None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 7. I Don’t Know What’s In This Bag, But Eat This Anyway', None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 8. What a Fascinating Phenomenon', None, 4.0, None, ''),
	('FE Awakening, Drama CD 4: 9. An Even More Amazing Treasure', None, 4.0, None, ''),
	('FEEL MY SORROW [It’s not READ OR DIE, it’s READ AND DIE]', None, None, None, ''),
	('FF to find Heman!', None, None, None, ''),
	('FFW prologue is revised', None, None, None, 'prologue is revised'),
	('FIIIIIII! COVERRRRRRR!! LIGHT NOVEL COVERRR!!!', None, None, None, ''),
	('FIRST SPONSORED CHAPTER IS OUT B3, C7!', 3.0, 7.0, None, ''),
	('FIT Chapter 1', None, 1.0, None, ''),
	('FIT Chapter 2', None, 2.0, None, ''),
	('FIT Chapter 3', None, 3.0, None, ''),
	('FIT Chapter 34', None, 34.0, None, ''),
	('FIT Chapter 35', None, 35.0, None, ''),
	('FIT Chapter 36', None, 36.0, None, ''),
	('FIT Chapter 37', None, 37.0, None, ''),
	('FIT Chapter 38', None, 38.0, None, ''),
	('FIT Chapter 39', None, 39.0, None, ''),
	('FIT Chapter 4', None, 4.0, None, ''),
	('FIT Chapter 40', None, 40.0, None, ''),
	('FIT Chapter 41', None, 41.0, None, ''),
	('FIT Chapter 42', None, 42.0, None, ''),
	('FIT Chapter 43', None, 43.0, None, ''),
	('FIT Chapter 44', None, 44.0, None, ''),
	('FIT Chapter 45', None, 45.0, None, ''),
	('FIT Chapter 46', None, 46.0, None, ''),
	('FIT Chapter 47', None, 47.0, None, ''),
	('FIT Chapter 48', None, 48.0, None, ''),
	('FIT Chapter 49', None, 49.0, None, ''),
	('FIT Chapter 51', None, 51.0, None, ''),
	('FIT Chapter 52', None, 52.0, None, ''),
	('FIT Chapter 53', None, 53.0, None, ''),
	('FIT Chapter 54', None, 54.0, None, ''),
	('FIT Chapter 55', None, 55.0, None, ''),
	('FIT Chapter 56', None, 56.0, None, ''),
	('FIT Chapter 57', None, 57.0, None, ''),
	('FIT Chapter 58', None, 58.0, None, ''),
	('FIT Chapter 59', None, 59.0, None, ''),
	('FIT Chapter 60', None, 60.0, None, ''),
	('FIT Chapter 61', None, 61.0, None, ''),
	('FIT Chapter 62', None, 62.0, None, ''),
	('FIT Chapter 63', None, 63.0, None, ''),
	('FIT Chapter 64', None, 64.0, None, ''),
	('FIT Chapter 65', None, 65.0, None, ''),
	('FIT Chatper 50', None, 50.0, None, ''),
	('FIrst Principle Schedule', None, None, None, ''),
	('FK COLLEGE FK LIFE', None, None, None, ''),
	('FLASH MARRIAGE -15.1', None, 15.1, None, ''),
	('FLASH MARRIAGE -16.2', None, 16.2, None, ''),
	('FLASH MARRIAGE 16.1', None, 16.1, None, ''),
	('FLASH MARRIAGE-10.1', None, 10.1, None, ''),
	('FLASH MARRIAGE-10.2', None, 10.2, None, ''),
	('FLASH MARRIAGE-13.1', None, 13.1, None, ''),
	('FLASH MARRIAGE-13.2', None, 13.2, None, ''),
	('FLASH MARRIAGE-14.1', None, 14.1, None, ''),
	('FLASH MARRIAGE-15.2', None, 15.2, None, ''),
	('FLASH MARRIAGE-17.1', None, 17.1, None, ''),
	('FLASH MARRIAGE-17.3', None, 17.3, None, ''),
	('FLASH MARRIAGE-18.1', None, 18.1, None, ''),
	('FLASH MARRIAGE-18.2', None, 18.2, None, ''),
	('FLASH MARRIAGE-19.1', None, 19.1, None, ''),
	('FLASH MARRIAGE-19.2', None, 19.2, None, ''),
	('FLASH MARRIAGE-20.1', None, 20.1, None, ''),
	('FLASH MARRIAGE-20.2', None, 20.2, None, ''),
	('FLASH MARRIAGE-21.1 (INCOMPLETE)', None, 21.1, None, ''),
	('FLASH MARRIAGE-21.2', None, 21.2, None, ''),
	('FLASH MARRIAGE-22.1', None, 22.1, None, ''),
	('FLASH MARRIAGE-22.3', None, 22.3, None, ''),
	('FLASH MARRIAGE-23.1', None, 23.1, None, ''),
	('FLASH MARRIAGE-23.2', None, 23.2, None, ''),
	('FLASH MARRIAGE-24.1', None, 24.1, None, ''),
	('FLASH MARRIAGE-24.2', None, 24.2, None, ''),
	('FLASH MARRIAGE-25.1', None, 25.1, None, ''),
	('FLASH MARRIAGE-25.2', None, 25.2, None, ''),
	('FLASH MARRIAGE-26.2', None, 26.2, None, ''),
	('FLASH MARRIAGE-27.1', None, 27.1, None, ''),
	('FLASH MARRIAGE-27.2', None, 27.2, None, ''),
	('FLASH MARRIAGE-28.1', None, 28.1, None, ''),
	('FLASH MARRIAGE-28.2', None, 28.2, None, ''),
	('FLASH MARRIAGE-28.3', None, 28.3, None, ''),
	('FML', None, None, None, ''),
	('FMP! is back!', None, None, None, ''),
	('FMTL – Chapter 038', None, 38.0, None, ''),
	('FMTL – Chapter 039', None, 39.0, None, ''),
	('FMTL – Chapter 040', None, 40.0, None, ''),
	('FMTL – Chapter 041', None, 41.0, None, ''),
	('FMTL – Chapter 042', None, 42.0, None, ''),
	('FMTL – Chapter 043', None, 43.0, None, ''),
	('FMTL – Chapter 044', None, 44.0, None, ''),
	('FMTL – Chapter 045', None, 45.0, None, ''),
	('FMTL – Chapter 046', None, 46.0, None, ''),
	('FMTL – Chapter 047', None, 47.0, None, ''),
	('FMTL – Chapter 048', None, 48.0, None, ''),
	('FMTL – Chapter 049', None, 49.0, None, ''),
	('FMTL – Chapter 050', None, 50.0, None, ''),
	('FMTL – Chapter 051', None, 51.0, None, ''),
	('FMTL – Chapter 052', None, 52.0, None, ''),
	('FMTL – Chapter 053', None, 53.0, None, ''),
	('FMTL – Chapter 056', None, 56.0, None, ''),
	('FMTL – Chapter 54', None, 54.0, None, ''),
	('FMTL – Chapter 55', None, 55.0, None, ''),
	('FMTL – Chapter 57', None, 57.0, None, ''),
	('FMTL – Chapter 58', None, 58.0, None, ''),
	('FMTL – Chapter 59', None, 59.0, None, ''),
	('FMTL – Chapter 60', None, 60.0, None, ''),
	('FMTL – Chapter 61', None, 61.0, None, ''),
	('FMTL – Chapter 62', None, 62.0, None, ''),
	('FMTL – Chapter 63', None, 63.0, None, ''),
	('FMTL – Chapter 64', None, 64.0, None, ''),
	('FMTL – Chapter 65', None, 65.0, None, ''),
	('FMTL – Chapter 66', None, 66.0, None, ''),
	('FMTL – Chapter 67', None, 67.0, None, ''),
	('FMTL – Chapter 68', None, 68.0, None, ''),
	('FMTL – Chapter 69 Part 1', None, 69.0, 1.0, ''),
	('FOE Continent Manga Chapter 2 is out!', None, 2.0, None, ''),
	('FOR . M x', None, None, None, ''),
	('FPS prologue', None, None, None, 'prologue'),
	('FRESH Skyfire Avenue Release -Chapter 217', None, 217.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 101', None, 101.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 102', None, 102.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 103', None, 103.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 106', None, 106.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 107', None, 107.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 108', None, 108.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 109', None, 109.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 110', None, 110.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 111', None, 111.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 113', None, 113.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 118', None, 118.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 119', None, 119.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 120', None, 120.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 121', None, 121.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 123', None, 123.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 125', None, 125.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 126', None, 126.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 140', None, 140.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 141', None, 141.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 143', None, 143.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 145', None, 145.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 146', None, 146.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 148', None, 148.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 149', None, 149.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 150', None, 150.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 151', None, 151.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 152', None, 152.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 153', None, 153.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 154', None, 154.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 155', None, 155.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 157', None, 157.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 158', None, 158.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 159', None, 159.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 160', None, 160.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 161', None, 161.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 162', None, 162.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 164', None, 164.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 165', None, 165.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 166', None, 166.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 167', None, 167.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 168', None, 168.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 169', None, 169.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 170', None, 170.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 171', None, 171.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 172', None, 172.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 173', None, 173.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 175', None, 175.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 176', None, 176.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 177', None, 177.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 178', None, 178.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 179', None, 179.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 180', None, 180.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 181', None, 181.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 182', None, 182.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 183', None, 183.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 185', None, 185.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 186', None, 186.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 187', None, 187.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 189', None, 189.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 190', None, 190.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 191', None, 191.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 192', None, 192.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 193', None, 193.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 194', None, 194.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 195', None, 195.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 196', None, 196.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 197', None, 197.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 198', None, 198.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 199', None, 199.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 200!', None, 200.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 202', None, 202.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 203', None, 203.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 204', None, 204.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 205', None, 205.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 206', None, 206.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 207', None, 207.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 208', None, 208.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 209', None, 209.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 210', None, 210.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 211', None, 211.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 212', None, 212.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 213', None, 213.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 214', None, 214.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 215', None, 215.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 216', None, 216.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 218', None, 218.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 219', None, 219.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 220', None, 220.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 221', None, 221.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 222', None, 222.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 224', None, 224.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 225', None, 225.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 226', None, 226.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 227', None, 227.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 228', None, 228.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 230', None, 230.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 232', None, 232.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 233', None, 233.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 234', None, 234.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 235', None, 235.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 237', None, 237.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 238', None, 238.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 239', None, 239.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 240', None, 240.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 241', None, 241.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 55', None, 55.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 57', None, 57.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 58', None, 58.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 59', None, 59.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 60', None, 60.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 61', None, 61.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 62', None, 62.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 65', None, 65.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 66', None, 66.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 68', None, 68.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 69', None, 69.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 70', None, 70.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 71', None, 71.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 72', None, 72.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 73', None, 73.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 74 + Correction', None, 74.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 75', None, 75.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 76', None, 76.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 77', None, 77.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 78', None, 78.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 79', None, 79.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 80', None, 80.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 81', None, 81.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 82', None, 82.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 83', None, 83.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 85', None, 85.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 86', None, 86.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 87', None, 87.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 88', None, 88.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 9', None, 9, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 93', None, 93.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 94', None, 94.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 95', None, 95.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 96', None, 96.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 97', None, 97.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 98', None, 98.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapter 99', None, 99.0, None, ''),
	('FRESH Skyfire Avenue Release – Chapters 114-115', None, 114, 115, ''),
	('FRESH Skyfire Avenue Releases – Chapters 128-129', None, 128, 129, ''),
	('FRESH Skyfire Avenue release – Chapter 67', None, 67.0, None, ''),
	('FRESH Skyfire Avenue – Chapter 100!', None, 100.0, None, ''),
	('FRESH Skyfire Release – Chapter 56', None, 56.0, None, ''),
	('FROM ON SCREEN TO OFF SCREEN PART 01', None, None, 1.0, ''),
	('FS: Natsume Yuujincho Kuji Strap, Nyanko-sensei Sweets, Izakaya, Gold Omikuji, Copper Mascot Straps', None, None, None, ''),
	('FSL is climbing!', None, None, None, ''),
	('FYI – Fourth Sponsored  Chapter…', None, None, None, ''),
	('FYI – Server Work Going On 7:30 AM – 9:30 AM (EST)', None, 7, None, ''),
	('FYJT Vol 4: The Vicissitudes – Chapter 2 Part B', 4.0, 2.0, None, ''),
	('Facebook Page', None, None, None, ''),
	('Faerieland: 37', None, 37.0, None, ''),
	('Faerieland: Part 10', None, None, 10.0, ''),
	('Faerieland: Part 11', None, None, 11.0, ''),
	('Faerieland: Part 12', None, None, 12.0, ''),
	('Faerieland: Part 13', None, None, 13.0, ''),
	('Faerieland: Part 14', None, None, 14.0, ''),
	('Faerieland: Part 15', None, None, 15.0, ''),
	('Faerieland: Part 16', None, None, 16.0, ''),
	('Faerieland: Part 17', None, None, 17.0, ''),
	('Faerieland: Part 18', None, None, 18.0, ''),
	('Faerieland: Part 19', None, None, 19.0, ''),
	('Faerieland: Part 20', None, None, 20.0, ''),
	('Faerieland: Part 21', None, None, 21.0, ''),
	('Faerieland: Part 22', None, None, 22.0, ''),
	('Faerieland: Part 23', None, None, 23.0, ''),
	('Faerieland: Part 24', None, None, 24.0, ''),
	('Faerieland: Part 25', None, None, 25.0, ''),
	('Faerieland: Part 26', None, None, 26.0, ''),
	('Faerieland: Part 27', None, None, 27.0, ''),
	('Faerieland: Part 28', None, None, 28.0, ''),
	('Faerieland: Part 29', None, None, 29.0, ''),
	('Faerieland: Part 30', None, None, 30.0, ''),
	('Faerieland: Part 31', None, None, 31.0, ''),
	('Faerieland: Part 32', None, None, 32.0, ''),
	('Faerieland: Part 33', None, None, 33.0, ''),
	('Faerieland: Part 34', None, None, 34.0, ''),
	('Faerieland: Part 35', None, None, 35.0, ''),
	('Faerieland: Part 36', None, None, 36.0, ''),
	('Faerieland: Part 38', None, None, 38.0, ''),
	('Faerieland: Part 39', None, None, 39.0, ''),
	('Faerieland: Part 40', None, None, 40.0, ''),
	('Faerieland: Part 8', None, None, 8.0, ''),
	('Faerieland: Part 9', None, None, 9.0, ''),
	('Fairy tale for the nephilim. Chapter 6: the honourable knight', None, 6.0, None, ''),
	('Faithful to Buddha, Faithful to You', None, None, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 1 and 2', None, 1.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 10', None, 10.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 11', None, 11.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 12', None, 12.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 13', None, 13.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 14', None, 14.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 15-16', None, 15, 16, ''),
	('Faithful to Buddha, Faithful to You — Chapter 17', None, 17.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 18', None, 18.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 19', None, 19.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 20', None, 20.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 3', None, 3.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 4', None, 4.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 5', None, 5.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 6', None, 6.0, None, ''),
	('Faithful to Buddha, Faithful to You — Chapter 7-8', None, 7, 8, ''),
	('Faithful to Buddha, Faithful to You — Chapter 9', None, 9.0, None, ''),
	('Fallen Angel', None, None, None, ''),
	('Falling Dreams of Fang Hua Chapter 37', None, 37.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 38', None, 38.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 39', None, 39.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 40', None, 40.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 41', None, 41.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 42', None, 42.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 43', None, 43.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 44', None, 44.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 45', None, 45.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 46', None, 46.0, None, ''),
	('Falling Dreams of Fang Hua Chapter 47 (Part 1)', None, 47.0, 1.0, ''),
	('Falling Dreams of Fang Hua Chapter 47 (Part 2)', None, 47.0, 2.0, ''),
	('Falling Dreams of Fang Hua Chapter 48 (Part 1)', None, 48.0, 1.0, ''),
	('Falling Dreams of Fang Hua Chapter 48 (Part 2)', None, 48.0, 2.0, ''),
	('Falling Dreams of Fang Hua Chapter 49 (Part 1)', None, 49.0, 1.0, ''),
	('Falling Dreams of Fang Hua Chapter 49 (Part 2)', None, 49.0, 2.0, ''),
	('Falling Dreams of Fang Hua Chapters 25 – 30', None, 25.0, None, ''),
	('Falling Dreams of Fang Hua Chapters 31-33', None, 31, 33, ''),
	('Falling Dreams of Fang Hua Chapters 34-36', None, 34, 36, ''),
	('False Pretenses', None, None, None, ''),
	('Family Camping Trip by BigMan7307', None, 7307.0, None, ''),
	('Family Reunion by TheWatcher58', None, 58, None, ''),
	('Family Values', None, None, None, ''),
	('Family of Mine', None, None, None, ''),
	('Family-Hen Chapter 1', None, 1.0, None, ''),
	('Family-Hen Chapter 2', None, 2.0, None, ''),
	('Family-Hen Chapter 3', None, 3.0, None, ''),
	('Family-Hen Chapter 4', None, 4.0, None, ''),
	('Family-Hen Chapter 5', None, 5.0, None, ''),
	('Family-Hen Chapter 6', None, 6.0, None, ''),
	('Family-Hen Chapter 7', None, 7.0, None, ''),
	('Family-Hen Chapter 8', None, 8.0, None, ''),
	('Family-Hen Chapter 9', None, 9.0, None, ''),
	('Fan Tong’s Foreword', None, None, None, 'Foreword'),
	('Fan art page update', None, None, None, ''),
	('FanArt #1 by Deamonvic', None, 1, None, ''),
	('FanArt #2 by Pedro Musacchio', None, 2.0, None, ''),
	('Fanart?', None, None, None, ''),
	('Fandoms: The Good, The Bad and The Downright Crazy!', None, None, None, ''),
	('Fanfic server issue', None, None, None, ''),
	('Fanfic: The Frozen Future, Ch. 9', None, 9.0, None, ''),
	('Fanny & Lillian', None, None, None, ''),
	('Fans are magical', None, None, None, ''),
	('Fantasy Man', None, None, None, ''),
	('Fanwork of Claudia', None, None, None, ''),
	('Farewell at the Bottom of the Hill', None, None, None, ''),
	('Farewell!', None, None, None, ''),
	('Farm Village Arc ② – My name', None, None, None, ''),
	('Farm Village Arc ③ – My first river debut', None, None, None, ''),
	('Farm Village Arc ④ – Anti-Hunger Plan', None, None, None, ''),
	('Farm Village Arc ⑤ – It was a new village!', None, None, None, ''),
	('Fat is beautiful novel introduction and mini translation', None, None, None, ''),
	('Fate Leads to Pork Cutlets', None, None, None, ''),
	('Fate/Apocrypha', None, None, None, ''),
	('Fate/Apocrypha 3 – Chapter 1 (Part 1)', None, 1.0, 1.0, ''),
	('Fate/Apocrypha 3 – Chapter 1 (Part 2)', None, 1.0, 2.0, ''),
	('Fate/Apocrypha 3 – Chapter 1 (Part 3)', None, 1.0, 3.0, ''),
	('Fate/Apocrypha 3 – Chapter 1 (Part 4)', None, 1.0, 4.0, ''),
	('Fate/Apocrypha 3 – Chapter 2 (Part 1)', None, 2.0, 1.0, ''),
	('Fate/Apocrypha 3 – Chapter 2 (Part 2)', None, 2.0, 2.0, ''),
	('Fate/Apocrypha 3 – Chapter 2 (Part 3)', None, 2.0, 3.0, ''),
	('Fate/Apocrypha 3 – Chapter 2 (Part 4)', None, 2.0, 4.0, ''),
	('Fate/Apocrypha 3 – Chapter 3 (Part 1)', None, 3.0, 1.0, ''),
	('Fate/Apocrypha 3 – Chapter 3 (Part 2)', None, 3.0, 2.0, ''),
	('Fate/Apocrypha 3 – Chapter 3 (Part 3)', None, 3.0, 3.0, ''),
	('Fate/Apocrypha Vol. 2 + 3', 2.0, 3.0, None, ''),
	('Fate/Apocrypha Volume 3 – Prologue', 3.0, None, None, 'Prologue'),
	('Fate/Apocrypha ~ (Italiano)', None, None, None, ''),
	('Fate/Apocrypha: Act 1 Unbirth', None, 1.0, None, ''),
	('Fate/Apocrypha: Act 1 Unbirth complete', None, 1.0, None, ''),
	('Fate/Apocrypha: Act 1 Unbirth2', None, 1.0, None, ''),
	('Fate/Apocrypha: Act 1 Unbirth3', None, 1.0, None, ''),
	('Fate/Apocrypha:Convenzioni Traduzione', None, None, None, ''),
	('Fate/Apocrypha:Pagina Progressi Traduzione', None, None, None, ''),
	('Fate/Apocrypha:Pagina Registrazione', None, None, None, ''),
	('Fate/Apocrypha:Volume1', 1.0, None, None, ''),
	('Fate/Apocrypha:Volume1 Capitolo 1 parte 1', 1.0, 1.0, None, ''),
	('Fate/Apocrypha:Volume1 Capitolo 1 parte 3', 1.0, 1.0, None, ''),
	('Fate/Apocrypha:Volume1 Prologo', 1.0, None, None, ''),
	('Fate/Apocrypha:Volume2', 2.0, None, None, ''),
	('Fate/Apocrypha:Volume3', 3.0, None, None, ''),
	('Fate/Apocrypha:Volume4', 4.0, None, None, ''),
	('Fate/Apocrypha:Volume5', 5.0, None, None, ''),
	('Fate/Strange Fake ~ (Brazilian Portuguese)', None, None, None, ''),
	('Fate/Zero:Act 10 Part 4', None, 10.0, 4.0, ''),
	('Fate/hollow ataraxia Chapter 1', None, 1.0, None, ''),
	('Fate/strange fake', None, None, None, ''),
	('Fate/strange fake plans', None, None, None, ''),
	('Fates of Change', None, None, None, ''),
	('Favicon Battle Result!!', None, None, None, ''),
	('Favorite Girl Poll', None, None, None, ''),
	('Favorite actors', None, None, None, ''),
	('Fear the Assassin, read ALBT Chapter 0012', None, 12.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0013', None, 13.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0014', None, 14.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0015', None, 15.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0016', None, 16.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0017', None, 17.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0018', None, 18.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0019', None, 19.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0020', None, 20.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0021', None, 21.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0022', None, 22.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0023', None, 23.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0024', None, 24.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0025', None, 25.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0026', None, 26.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0027', None, 27.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0028', None, 28.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0029', None, 29.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0030', None, 30.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0031', None, 31.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0032', None, 32.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0034', None, 34.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0035', None, 35.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0036', None, 36.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0037', None, 37.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0038', None, 38.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0039', None, 39.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0040', None, 40.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0041', None, 41.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0042', None, 42.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0043', None, 43.0, None, ''),
	('Fear the Assassin, read ALBT Chapter 0044', None, 44.0, None, ''),
	('Fearless Phil by realoldbill', None, None, None, ''),
	('Feast Your Eyes on the… Um, Prologue', None, None, None, 'Prologue'),
	('Feb Contest update', None, None, None, ''),
	('February 2015 Announcement', None, 2015.0, None, ''),
	('February 2016 Announcements', None, 2016.0, None, ''),
	('February 2016 Recap', None, 2016.0, None, ''),
	('Febuary 2016 Web Novel Ranking', None, 2016.0, None, ''),
	('Feedback', None, None, None, ''),
	('Feedback Thread', None, None, None, ''),
	('Feedback help for serious question: How Stupid is Too Stupid?', None, None, None, ''),
	('Feeling Really Generous', None, None, None, ''),
	('Feeling under the weather', None, None, None, ''),
	("Felicia's Second Life Chapter 8 Part 1", None, 8.0, 1.0, ''),
	("Felicia's Second Life Chapter 8 Part 2", None, 8.0, 2.0, ''),
	("Felicia's Second Life Chapter 8 Part 3", None, 8.0, 3.0, ''),
	("Felicia's Second Life Chapter 9", None, 9.0, None, ''),
	("Felicia's Second Life Epilogue: The Souvenir From Lytis", None, None, None, 'Epilogue: The Souvenir From Lytis'),
	("Felicia's Second Life Prologue Book 2", 2.0, None, None, 'Prologue Book 2'),
	("Felicia's Second Life: End of volume 1 and a short pause before the next volume.", 1.0, None, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 117!', 2.0, 117.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 119!!', 2.0, 119.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 121!!', 2.0, 121.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 141!!', 2.0, 141.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 143!!', 2.0, 143.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 145!!', 2.0, 145.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 147, 148!!', 2.0, 147.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 150, 151!', 2.0, 150.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 153!!!', 2.0, 153.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 155!!', 2.0, 155.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 158!!', 2.0, 158.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 161!!', 2.0, 161.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 162!!', 2.0, 162.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 164!!', 2.0, 164.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 166!!', 2.0, 166.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 168!!', 2.0, 168.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 170!!!', 2.0, 170.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 172!', 2.0, 172.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 174, 175!', 2.0, 174.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 177!!', 2.0, 177.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 178!!', 2.0, 178.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 180!!', 2.0, 180.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 181!!!', 2.0, 181.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 182!', 2.0, 182.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 183!', 2.0, 183.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 185!!', 2.0, 185.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 186!!', 2.0, 186.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 192, 193!!', 2.0, 192.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 194!', 2.0, 194.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 196!!', 2.0, 196.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 198!!', 2.0, 198.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 200!!!', 2.0, 200.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 202!', 2.0, 202.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapter 204!', 2.0, 204.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 112, 113!!', 2.0, 112.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 115!', 2.0, 115.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 123!!', 2.0, 123.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 126!!', 2.0, 126.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 128!!', 2.0, 128.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 133-135!!', 2, 133, 135, ''),
	('Fellow Daoists, please enjoy ISSTH Book 2, Chapters 138, 139!!', 2.0, 138.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 204!', 3.0, 204.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 208!', 3.0, 208.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 210!', 3.0, 210.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 212!', 3.0, 212.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 214!', 3.0, 214.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 216!', 3.0, 216.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 218!', 3.0, 218.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 220!', 3.0, 220.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 222!', 3.0, 222.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 224!', 3.0, 224.0, None, ''),
	('Fellow Daoists, please enjoy ISSTH Book 3, Chapter 226!', 3.0, 226.0, None, ''),
	('Female Warrior Prologue V1C6: Light and Shadow Part 6', 1.0, 6.0, 6.0, 'Prologue V1C6: Light and Shadow Part 6'),
	('Female Warrior Prologue V1C7: Intertwined', 1.0, 7.0, None, 'Prologue V1C7: Intertwined'),
	('Female Warrior Prologue V1Prologue: In a Flash', 1.0, None, None, 'Prologue V1Prologue: In a Flash'),
	('Female Warrior Prologue V2C10: Number, 10, Revenge', 2.0, 10.0, None, 'Prologue V2C10: Number, 10, Revenge'),
	('Female Warrior Prologue V2C11: Number, 11, Judgment', 2.0, 11.0, None, 'Prologue V2C11: Number, 11, Judgment'),
	('Female Warrior Prologue V2C12: Number, 12, Twelve (END)', 2.0, 12.0, None, 'Prologue V2C12: Number, 12, Twelve (END)'),
	('Female Warrior Prologue V2C1: Number, 1, Prologue', 2.0, 1.0, None, 'Prologue V2C1: Number, 1, Prologue'),
	('Female Warrior Prologue V2C2: Number, 2, Divergence', 2.0, 2.0, None, 'Prologue V2C2: Number, 2, Divergence'),
	('Female Warrior Prologue V2C3: Number, 3, The Third One', 2.0, 3.0, None, 'Prologue V2C3: Number, 3, The Third One'),
	('Female Warrior Prologue V2C4: Number, 4, Cale', 2.0, 4.0, None, 'Prologue V2C4: Number, 4, Cale'),
	('Female Warrior Prologue V2C5: Number, 5, Good Guy? Bad Guy?', 2.0, 5.0, None, 'Prologue V2C5: Number, 5, Good Guy? Bad Guy?'),
	('Female Warrior Prologue V2C6: Number, 6, …The Fourth One?', 2.0, 6.0, None, 'Prologue V2C6: Number, 6, …The Fourth One?'),
	('Female Warrior Prologue V2C7: Number, 7, Halfleaf', 2.0, 7.0, None, 'Prologue V2C7: Number, 7, Halfleaf'),
	('Female Warrior Prologue V2C8: Number, 8, Stalemate', 2.0, 8.0, None, 'Prologue V2C8: Number, 8, Stalemate'),
	('Female Warrior Prologue V2C9: Number, 9, Younger Brother', 2.0, 9.0, None, 'Prologue V2C9: Number, 9, Younger Brother'),
	('Female Warrior Prologue V2Extra: Artbook', 2.0, None, None, 'Prologue V2Extra: Artbook'),
	('FiLI Chapter 1 Release', None, 1.0, None, ''),
	('FiLI Chapter 2 Release', None, 2.0, None, ''),
	('FiLI Chapter 3 Release', None, 3.0, None, ''),
	('FiLI Chapter 5 Release', None, 5.0, None, ''),
	('FiLi Chapter 4 Release', None, 4.0, None, ''),
	('Fiance-Hen Chapter 4', None, 4.0, None, ''),
	('Fiance-Hen Chapter 5', None, 5.0, None, ''),
	('Fiance-Hen Chapter 6', None, 6.0, None, ''),
	('Fiance-Hen Chapter 7', None, 7.0, None, ''),
	('Fiance-Hen Chapter 8', None, 8.0, None, ''),
	('Fiction: Little Ode to the Boss! (One Shot - Completed)', None, None, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 10)', None, 10.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 11)', None, 11.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 12)', None, 12.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 13)', None, 13.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 14)', None, 14.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 5)', None, 5.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 6)', None, 6.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 7)', None, 7.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 8)', None, 8.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Chapter 9)', None, 9.0, None, ''),
	('Fiction: The Princess Who Cannot Marry (Synopsis/Character Chart/Casting)', None, None, None, ''),
	('Fifth Regular Chapter Of The Week! B4 C9!', 4.0, 9.0, None, ''),
	('Fifty Shades of 999', None, 999.0, None, ''),
	('Fifty Shades of Grey - How has it become so popular?', None, None, None, ''),
	('Fighting For Peace', None, None, None, ''),
	('Fii Character Sketch', None, None, None, ''),
	('Fiiru and Lynette sketches', None, None, None, ''),
	('Fiiru-sama’s New Years Special Performance', None, None, None, ''),
	('File:A01.jpg', None, 1.0, None, ''),
	('File:A02.jpg', None, 2.0, None, ''),
	('File:A03.jpg', None, 3.0, None, ''),
	('File:A04.jpg', None, 4.0, None, ''),
	('File:A05.png', None, 5.0, None, ''),
	('File:A06.jpg', None, 6.0, None, ''),
	('File:A07.jpg', None, 7.0, None, ''),
	('File:A08.jpg', None, 8.0, None, ''),
	('File:A09.jpg', None, 9.0, None, ''),
	('File:A10.jpg', None, 10.0, None, ''),
	('File:A11.jpg', None, 11.0, None, ''),
	('File:A12.jpg', None, 12.0, None, ''),
	('File:A13.jpg', None, 13.0, None, ''),
	('File:A14.png', None, 14.0, None, ''),
	('File:Act1-Unbirth.jpg', None, 1.0, None, ''),
	('File:Ageha v2.jpg', 2.0, None, None, ''),
	('File:Altine Cross Overlord Cover.jpg', None, None, None, ''),
	('File:Amaryllis033.jpg', None, 33.0, None, ''),
	('File:AmaryllisCover.jpeg', None, None, None, ''),
	('File:Apo01.png', None, 1.0, None, ''),
	('File:Arashi Hug.jpg', None, None, None, ''),
	('File:Ayaka Sajyou.png', None, None, None, ''),
	('File:BA Volume 3 Cover.jpeg', 3.0, None, None, ''),
	('File:BTS vol 01 000c cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000d cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000e cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000f cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000g cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000h cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000i cz.jpg', 1.0, 0.0, None, ''),
	('File:BTS vol 01 000j cz.jpg', 1.0, 0.0, None, ''),
	('File:Bake HitagiCrab czEdit.jpg', None, None, None, ''),
	('File:Bake MayoiSnail czEdit.jpg', None, None, None, ''),
	('File:Bakemonogatari ebook 1.jpg', None, 1.0, None, ''),
	('File:Beans602.jpg', None, 602.0, None, ''),
	('File:Boku wa Isekai de Fuyo Mahou to Shoukan Mahou wo Tenbin ni Kakeru Cover vol01.jpg', 1.0, None, None, ''),
	('File:Bokurano alternative Cover.jpeg', None, None, None, ''),
	('File:BooBoo v01 001.png', 1.0, 1.0, None, ''),
	('File:BooBoo v01 002.png', 1.0, 2.0, None, ''),
	('File:BooBoo v01 009.png', 1.0, 9.0, None, ''),
	('File:BooBoo v01 023.png', 1.0, 23.0, None, ''),
	('File:BooBoo v01 061.png', 1.0, 61.0, None, ''),
	('File:BooBoo v01 072.png', 1.0, 72.0, None, ''),
	('File:BooBoo v01 087.png', 1.0, 87.0, None, ''),
	('File:BooBoo v01 100.png', 1.0, 100.0, None, ''),
	('File:BooBoo v01 150.png', 1.0, 150.0, None, ''),
	('File:BooBoo v01 199.png', 1.0, 199.0, None, ''),
	('File:BooBoo v01 234.png', 1.0, 234.0, None, ''),
	('File:BooBoo v01 295.png', 1.0, 295.0, None, ''),
	('File:CSR 23 002-003.jpg', None, 23.0, None, ''),
	('File:CSR v22 cover2.jpg', 22.0, 2, None, ''),
	('File:CSR v22 cover3.jpg', 22.0, 3, None, ''),
	('File:CSR v22 cover4.jpg', 22.0, 4, None, ''),
	('File:CSR v24 0.jpg', 24.0, 0.0, None, ''),
	('File:CSR v24 2.jpg', 24.0, 2.0, None, ''),
	('File:CSR v24 3.jpg', 24.0, 3.0, None, ''),
	('File:CSR v24 4.jpg', 24.0, 4.0, None, ''),
	('File:CSR v24 5.jpg', 24.0, 5.0, None, ''),
	('File:CSR vol01 001.jpg', 1.0, 1.0, None, ''),
	('File:CSR vol01 002-003.jpg', 1.0, 2.0, None, ''),
	('File:CSR vol01 004.jpg', 1.0, 4.0, None, ''),
	('File:CSR vol15 000b.jpg', 15.0, 0.0, None, ''),
	('File:CSR vol15 000cd.jpg', 15.0, 0.0, None, ''),
	('File:CSR vol15 000e.jpg', 15.0, 0.0, None, ''),
	('File:CSR vol17 000b.jpg', 17.0, 0.0, None, ''),
	('File:CSR vol17 000cd.jpg', 17.0, 0.0, None, ''),
	('File:Chronicle Legion 01 000.jpg', None, 1.0, None, ''),
	('File:Chronicle Legion 01 001.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW02.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW03.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW04.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW05.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW06.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW07.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW08.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW09.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW1.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW10.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW11.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW12.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW13.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 BW14.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Color1.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Color2.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Color3.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Color4.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Map1 english.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Map1.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Map2 english.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Map2.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 01 Map3.jpg', None, 1.0, None, ''),
	('File:ChronicleLegion 02 000.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 001.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW01.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW02.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW03.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW04.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW05.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW06.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW07.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW08.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW09.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 BW10.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 Color1.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 Color2.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 Color3.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 Map1.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 02 Map2.jpg', None, 2.0, None, ''),
	('File:ChronicleLegion 03 000.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 001.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW01.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW02.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW03.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW04.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW05.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW06.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW07.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 BW08.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 Color1.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 Color2.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 Color3.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 03 Color4.jpg', None, 3.0, None, ''),
	('File:ChronicleLegion 04 000.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 001.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW01.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW02.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW03.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW04.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW05.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW06.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW07.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW08.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW09.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 BW10.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 Color1.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 Color2.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 Map1.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 Map2.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 04 Map3.jpg', None, 4.0, None, ''),
	('File:ChronicleLegion 05 000.jpg', None, 5.0, None, ''),
	('File:Complaint File N1 Gwendal.jpg', None, 1.0, None, ''),
	('File:Complaint File N2 Conrart.jpg', None, 2.0, None, ''),
	('File:Complaint File N4 Josak.jpg', None, 4.0, None, ''),
	('File:Cover High School DxD Volume Dx2.jpg', None, 2.0, None, ''),
	('File:Cover Limited High School DxD Volume Dx2.jpg', None, 2.0, None, ''),
	('File:Cover Normal High School DxD Volume Dx2.jpg', None, 2.0, None, ''),
	('File:Csr v25 000c.jpg', 25.0, 0.0, None, ''),
	('File:Datboi.jpg', None, None, None, ''),
	('File:Do you want an exorcism002.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 01.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 02.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 03.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 04.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 05.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 06.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 07.jpg', None, 2.0, None, ''),
	('File:DxD Dx2 08.jpg', None, 2.0, None, ''),
	('File:FateApocrypha vol04.jpg', 4.0, None, None, ''),
	('File:FateApocrypha vol05.jpg', 5.0, None, None, ''),
	('File:Flat Escardos.png', None, None, None, ''),
	('File:Galactic Dark Net Cover.jpg', None, None, None, ''),
	('File:HEAVENLY JEWEL CHANGE Cover.png', None, None, None, ''),
	('File:HO v11 001.jpg', 11.0, 1.0, None, ''),
	('File:HO v11 002.jpg', 11.0, 2.0, None, ''),
	('File:HO v11 003-005.jpg', 11.0, 3.0, None, ''),
	('File:HO v11 006-008.jpg', 11.0, 6.0, None, ''),
	('File:HO v11 009.jpg', 11.0, 9.0, None, ''),
	('File:HO v11 025.jpg', 11.0, 25.0, None, ''),
	('File:HO v11 044.jpg', 11.0, 44.0, None, ''),
	('File:HO v11 084.jpg', 11.0, 84.0, None, ''),
	('File:HO v11 099.jpg', 11.0, 99.0, None, ''),
	('File:HO v11 105.jpg', 11.0, 105.0, None, ''),
	('File:HO v11 112.jpg', 11.0, 112.0, None, ''),
	('File:HO v11 133.jpg', 11.0, 133.0, None, ''),
	('File:HO v11 154.jpg', 11.0, 154.0, None, ''),
	('File:HO v11 195.jpg', 11.0, 195.0, None, ''),
	('File:HO v11 209.jpg', 11.0, 209.0, None, ''),
	('File:HO v11 223.jpg', 11.0, 223.0, None, ''),
	('File:HO v11 267.jpg', 11.0, 267.0, None, ''),
	('File:HO v11 277.jpg', 11.0, 277.0, None, ''),
	('File:HO v11 320-321.jpg', 11.0, 320.0, None, ''),
	('File:Hexennacht v02 001.jpg', 2.0, 1.0, None, ''),
	('File:Hexennacht v02 008.jpg', 2.0, 8.0, None, ''),
	('File:Hexennacht v02 021.png', 2.0, 21.0, None, ''),
	('File:Hexennacht v02 085.png', 2.0, 85.0, None, ''),
	('File:Hexennacht v02 107.png', 2.0, 107.0, None, ''),
	('File:Hexennacht v02 145.png', 2.0, 145.0, None, ''),
	('File:Hexennacht v02 167.png', 2.0, 167.0, None, ''),
	('File:Hexennacht v02 327.png', 2.0, 327.0, None, ''),
	('File:Hexennacht v02 353.png', 2.0, 353.0, None, ''),
	('File:Hgn Vol8 chp11 img1', 8.0, 11.0, None, ''),
	('File:Hgn Vol8 chp11 img1.png', 8.0, 11.0, None, ''),
	('File:Hgn Vol8 chp11 img2', 8.0, 11.0, None, ''),
	('File:Hgn Vol8 chp11 img2.jpeg', 8.0, 11.0, None, ''),
	('File:Hidan no Aria Volume 1 Cover.jpg', 1.0, None, None, ''),
	('File:Hidan no Aria Volume 10 Cover.jpg', 10.0, None, None, ''),
	('File:Hidan no Aria Volume 11 Cover.jpg', 11.0, None, None, ''),
	('File:Hidan no Aria Volume 12 Cover.jpg', 12.0, None, None, ''),
	('File:Hidan no Aria Volume 13 Cover.jpg', 13.0, None, None, ''),
	('File:Hidan no Aria Volume 15 Cover.jpg', 15.0, None, None, ''),
	('File:Hidan no Aria Volume 7 Cover.jpg', 7.0, None, None, ''),
	('File:Horizon Kimi2A 045.jpg', None, 2.0, None, ''),
	('File:Horizon9B.jpg', None, 9.0, None, ''),
	('File:Jester Karture.png', None, None, None, ''),
	('File:Kenkoku no Jungfrau Volume 1 - Color Image 1.jpg', 1.0, 1.0, None, ''),
	('File:Kenkoku no YungFrau V1 cl01.jpg', 1.0, 1.0, None, ''),
	('File:Kenkoku no YungFrau V1 cl02.jpg', 1.0, 2.0, None, ''),
	('File:Kenkoku no YungFrau V1 cl03.jpg', 1.0, 3.0, None, ''),
	('File:Kenkoku no YungFrau V1 p121.jpg', 1.0, None, 121.0, ''),
	('File:Kenkoku no YungFrau V1 p165.jpg', 1.0, None, 165.0, ''),
	('File:Kenkoku no YungFrau V1 p199.jpg', 1.0, None, 199.0, ''),
	('File:Kenkoku no YungFrau V1 p23.jpg', 1.0, None, 23.0, ''),
	('File:Kenkoku no YungFrau V1 p271.jpg', 1.0, None, 271.0, ''),
	('File:Kenkoku no YungFrau V1 p307.jpg', 1.0, None, 307.0, ''),
	('File:Kenkoku no YungFrau V1 p309.jpg', 1.0, None, 309.0, ''),
	('File:Kenkoku no YungFrau V1 p53.jpg', 1.0, None, 53.0, ''),
	('File:Kenkoku no YungFrau V1 p63.jpg', 1.0, None, 63.0, ''),
	('File:Kuruoka Tsubaki.png', None, None, None, ''),
	('File:Leviathan 05 266.jpg', None, 5.0, None, ''),
	('File:Leviathan 06 022.jpg', None, 6.0, None, ''),
	('File:Leviathan 06 095.jpg', None, 6.0, None, ''),
	('File:Leviathan 06 114.jpg', None, 6.0, None, ''),
	('File:Leviathan 06 217.jpg', None, 6.0, None, ''),
	('File:Leviathan 06 236.jpg', None, 6.0, None, ''),
	('File:LoR Vol3 Cover.jpg', 3.0, None, None, ''),
	('File:LoR v01 color 1.jpg', 1.0, 1.0, None, ''),
	('File:LoR v01 color 2.jpg', 1.0, 2.0, None, ''),
	('File:LoR v01 color 3.jpg', 1.0, 3.0, None, ''),
	('File:LoR v01.jpg', 1.0, None, None, ''),
	('File:LoR v02 color 1.jpg', 2.0, 1.0, None, ''),
	('File:LoR v02 color 2.jpg', 2.0, 2.0, None, ''),
	('File:LoR v02 color 3.jpg', 2.0, 3.0, None, ''),
	('File:LoR v02.jpg', 2.0, None, None, ''),
	('File:LoR v03 color 1.jpg', 3.0, 1.0, None, ''),
	('File:LoR v03 color 2.jpg', 3.0, 2.0, None, ''),
	('File:MKnR Indo Colour 01.jpg', None, 1.0, None, ''),
	('File:MKnR Indo Colour 02.jpg', None, 2.0, None, ''),
	('File:MKnR Indo Colour 03.jpg', None, 3.0, None, ''),
	('File:MKnR Indo Colour 04.jpg', None, 4.0, None, ''),
	('File:MKnR Indo Colour 05.jpg', None, 5.0, None, ''),
	('File:MM v15 085.jpg', 15.0, 85.0, None, ''),
	('File:MM v15 133.jpg', 15.0, 133.0, None, ''),
	('File:MM v15 207.jpg', 15.0, 207.0, None, ''),
	('File:MM v16 025.jpg', 16.0, 25.0, None, ''),
	('File:MM v16 047.jpg', 16.0, 47.0, None, ''),
	('File:MM v16 057.jpg', 16.0, 57.0, None, ''),
	('File:MM v16 069.jpg', 16.0, 69.0, None, ''),
	('File:MM v16 085.jpg', 16.0, 85.0, None, ''),
	('File:MM v16 097.jpg', 16.0, 97.0, None, ''),
	('File:MM v16 109.jpg', 16.0, 109.0, None, ''),
	('File:MM v16 115.jpg', 16.0, 115.0, None, ''),
	('File:MM v16 127.jpg', 16.0, 127.0, None, ''),
	('File:MM v16 175.jpg', 16.0, 175.0, None, ''),
	('File:MM v18 p017.jpg', 18.0, None, 17.0, ''),
	('File:MM v18 p053.jpg', 18.0, None, 53.0, ''),
	('File:MM v18 p089.jpg', 18.0, None, 89.0, ''),
	('File:MM v18 p131.jpg', 18.0, None, 131.0, ''),
	('File:MM v18 p189.jpg', 18.0, None, 189.0, ''),
	('File:MM v35 000.jpg', 35.0, 0.0, None, ''),
	('File:MM v35 019.png', 35.0, 19.0, None, ''),
	('File:MM v35 037.png', 35.0, 37.0, None, ''),
	('File:MM v35 051.png', 35.0, 51.0, None, ''),
	('File:MM v35 121.png', 35.0, 121.0, None, ''),
	('File:MM v36 000a.jpg', 36.0, 0.0, None, ''),
	('File:MM v36 000b.jpg', 36.0, 0.0, None, ''),
	('File:MM v36 035.png', 36.0, 35.0, None, ''),
	('File:MM v36 083.png', 36.0, 83.0, None, ''),
	('File:MM v37 000.jpg', 37.0, 0.0, None, ''),
	('File:MM v37 004.png', 37.0, 4.0, None, ''),
	('File:MM v37 097.png', 37.0, 97.0, None, ''),
	('File:MM v37 189.png', 37.0, 189.0, None, ''),
	('File:MagdalaV03Cover.jpg', None, 3.0, None, ''),
	('File:MagdalaV04Cover.jpg', None, 4.0, None, ''),
	('File:MagdalaV05Cover.jpg', None, 5.0, None, ''),
	('File:MagdalaV06Cover.jpg', None, 6.0, None, ''),
	('File:MagdalaV07Cover.jpg', None, 7.0, None, ''),
	('File:MagdalaV08Cover.jpg', None, 8.0, None, ''),
	('File:MagdalaV1Cover.jpg', None, 1.0, None, ''),
	('File:MagdalaV2Cover.jpg', None, 2.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.09 000.jpg', 9.0, 0.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 000.jpg', 12.0, 0.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 001.jpg', 12.0, 1.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 002-003.jpg', 12.0, 2.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 004-005.jpg', 12.0, 4.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 006-007.jpg', 12.0, 6.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 021.jpg', 12.0, 21.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 027.jpg', 12.0, 27.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 055.jpg', 12.0, 55.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 083.jpg', 12.0, 83.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 101.jpg', 12.0, 101.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 167.jpg', 12.0, 167.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 173.jpg', 12.0, 173.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 197.jpg', 12.0, 197.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 261.jpg', 12.0, 261.0, None, ''),
	('File:Magika No Kenshi To Shoukan Maou Vol.12 322-323.jpg', 12.0, 322.0, None, ''),
	('File:Mahouka Koukou no Rettousei S1.png', 1.0, None, None, ''),
	('File:Maoyyu Maou Yuusha Volume 2 Image 2.jpg', 2.0, 2.0, None, ''),
	('File:Maoyyu Maou Yuusha Volume 2 Image 3.jpg', 2.0, 3.0, None, ''),
	('File:Map1.jpg', None, 1.0, None, ''),
	('File:Map2.jpg', None, 2.0, None, ''),
	('File:Map3.jpg', None, 3.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 02.jpg', 7.0, 2.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 03.jpg', 7.0, 3.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 04.jpg', 7.0, 4.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 05.jpg', 7.0, 5.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 06.jpg', 7.0, 6.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 07.jpg', 7.0, 7.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 08.jpg', 7.0, 8.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 09.jpg', 7.0, 9.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 10.jpg', 7.0, 10.0, None, ''),
	('File:Masou Gakuen HxH V07 BW 11.jpg', 7.0, 11.0, None, ''),
	('File:Masou Gakuen HxH V07 CD Drama Cover Edition.jpg', 7.0, None, None, ''),
	('File:Masou Gakuen HxH V07 Color 01.jpg', 7.0, 1.0, None, ''),
	('File:Masou Gakuen HxH V07 Color 02.jpg', 7.0, 2.0, None, ''),
	('File:Masou Gakuen HxH V07 Color 03.jpg', 7.0, 3.0, None, ''),
	('File:Masou Gakuen HxH V07 Color 04.jpg', 7.0, 4.0, None, ''),
	('File:Masou Gakuen HxH V07 Color 05.jpg', 7.0, 5.0, None, ''),
	('File:Masou Gakuen HxH V07 Color 06.jpg', 7.0, 6.0, None, ''),
	('File:Masou Gakuen HxH V08 001.jpg', 8.0, 1.0, None, ''),
	('File:Masou Gakuen HxH V08 002-003.jpg', 8.0, 2.0, None, ''),
	('File:Masou Gakuen HxH V08 004-005.jpg', 8.0, 4.0, None, ''),
	('File:Masou Gakuen HxH V08 006-007.jpg', 8.0, 6.0, None, ''),
	('File:Masou Gakuen HxH V08 008.jpg', 8.0, 8.0, None, ''),
	('File:Masou Gakuen HxH V08 017.jpg', 8.0, 17.0, None, ''),
	('File:Masou Gakuen HxH V08 049.jpg', 8.0, 49.0, None, ''),
	('File:Masou Gakuen HxH V08 145.jpg', 8.0, 145.0, None, ''),
	('File:Masou Gakuen HxH V08 182-183.jpg', 8.0, 182.0, None, ''),
	('File:Masou Gakuen HxH V08 187.jpg', 8.0, 187.0, None, ''),
	('File:Masou Gakuen HxH V08 195.jpg', 8.0, 195.0, None, ''),
	('File:Masou Gakuen HxH V08 225.jpg', 8.0, 225.0, None, ''),
	('File:Masou Gakuen HxH V08 245.jpg', 8.0, 245.0, None, ''),
	('File:Masou Gakuen HxH V08 265.jpg', 8.0, 265.0, None, ''),
	('File:Masou Gakuen HxH V08 273.jpg', 8.0, 273.0, None, ''),
	('File:Masou Gakuen HxH V08 293.jpg', 8.0, 293.0, None, ''),
	('File:Masou Gakuen HxH V08 313.jpg', 8.0, 313.0, None, ''),
	('File:Masou Gakuen HxH V08 314-315.jpg', 8.0, 314.0, None, ''),
	('File:Masou Gakuen HxH V08 Cover.jpg', 8.0, None, None, ''),
	('File:Masou Gakuen HxH V09 Cover.jpg', 9.0, None, None, ''),
	('File:Mushoku11 08.jpg', None, 11.0, None, ''),
	('File:Mushoku11 09.jpg', None, 11.0, None, ''),
	('File:Mushoku11 10.jpg', None, 11.0, None, ''),
	('File:Mushoku11 11.jpg', None, 11.0, None, ''),
	('File:NGNL V01 004.jpg', 1.0, 4.0, None, ''),
	('File:NGNL V03 005.jpg', 3.0, 5.0, None, ''),
	('File:NGNL V03 006.jpg', 3.0, 6.0, None, ''),
	('File:NGNL V07 - REF1.jpeg', 7.0, 1.0, None, ''),
	('File:NGNL V08 - 05.jpg', 8.0, 5.0, None, ''),
	('File:NGNL V08 - 07.jpg', 8.0, 7.0, None, ''),
	('File:NGNL V08 - 09.jpg', 8.0, 9.0, None, ''),
	('File:NGNL V08 - P029.jpg', 8.0, None, 29.0, ''),
	('File:NGNL V08 - P057.jpg', 8.0, None, 57.0, ''),
	('File:NGNL V08 - P131.jpg', 8.0, None, 131.0, ''),
	('File:NGNL V08 - P168.jpg', 8.0, None, 168.0, ''),
	('File:NGNL V08 - P175.jpg', 8.0, None, 175.0, ''),
	('File:NGNL V08 - P219.jpg', 8.0, None, 219.0, ''),
	('File:NGNL V08 - P283.jpg', 8.0, None, 283.0, ''),
	('File:NGNL V08 - P294.jpg', 8.0, None, 294.0, ''),
	('File:NGNL V08 - P324.jpg', 8.0, None, 324.0, ''),
	('File:NGNL V08 - Sommaire.jpg', 8.0, None, None, ''),
	('File:NGNL V08 Cover.jpg', 8.0, None, None, ''),
	('File:NGNL V2 004.jpg', 2.0, 4.0, None, ''),
	('File:NT Index v16 023.jpg', 16.0, 23.0, None, ''),
	('File:NT Index v16 042.jpg', 16.0, 42.0, None, ''),
	('File:NT vol 16.jpg', 16.0, None, None, ''),
	('File:Naga03 002.jpg', None, 3.0, None, ''),
	('File:Naga03 003.jpg', None, 3.0, None, ''),
	('File:Naga03 004.jpg', None, 3.0, None, ''),
	('File:Naga03 005.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-01.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-02.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-03.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-04.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-05.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-06.jpg', None, 3.0, None, ''),
	('File:Naga03 Illus-07.jpg', None, 3.0, None, ''),
	('File:Naga03 Kay-intro.jpg', None, 3.0, None, ''),
	('File:Naga03 cover.jpg', None, 3.0, None, ''),
	('File:Naga03 world-map.jpg', None, 3.0, None, ''),
	('File:Naga04 002.jpg', None, 4.0, None, ''),
	('File:Naga04 003.jpg', None, 4.0, None, ''),
	('File:Naga04 004.jpg', None, 4.0, None, ''),
	('File:Naga04 005.jpg', None, 4.0, None, ''),
	('File:Naga04 Illus-01.jpg', None, 4.0, None, ''),
	('File:Naga04 Illus-02.jpg', None, 4.0, None, ''),
	('File:Naga04 character-page.jpg', None, 4.0, None, ''),
	('File:Naga04 cover.jpg', None, 4.0, None, ''),
	('File:Ngnl T1 4.jpg', None, 1.0, None, ''),
	('File:Ngnl T1 5.jpg', None, 1.0, None, ''),
	('File:Ngnl T1 6.jpg', None, 1.0, None, ''),
	('File:Ngnl T2 2.jpg', None, 2.0, None, ''),
	('File:Ngnl T2 3.jpg', None, 2.0, None, ''),
	('File:Ngnl T2 4.jpg', None, 2.0, None, ''),
	('File:Ngnl T2 5.jpg', None, 2.0, None, ''),
	('File:Oda Vol 11 003.png', 11.0, 3.0, None, ''),
	('File:Oda Vol 11 004.png', 11.0, 4.0, None, ''),
	('File:Oda Vol 11 014.png', 11.0, 14.0, None, ''),
	('File:Oda Vol 11 060.png', 11.0, 60.0, None, ''),
	('File:Oda Vol 11 228.png', 11.0, 228.0, None, ''),
	('File:Oda Vol 11 244.png', 11.0, 244.0, None, ''),
	('File:Oda Vol 11 316.png', 11.0, 316.0, None, ''),
	('File:Oda Vol 11 318.png', 11.0, 318.0, None, ''),
	('File:Oda Vol 11 Cover 2.png', 11.0, 2.0, None, ''),
	('File:Orlando Reeve.png', None, None, None, ''),
	('File:ProfileArcherOfBlack.jpg', None, None, None, ''),
	('File:ProfileArcherOfRed.jpg', None, None, None, ''),
	('File:ProfileAssassinOfBlack.jpg', None, None, None, ''),
	('File:ProfileAssassinOfBlack.png', None, None, None, ''),
	('File:ProfileAssassinOfRed.png', None, None, None, ''),
	('File:ProfileBerserkerOfBlack.png', None, None, None, ''),
	('File:ProfileBerserkerOfRed.jpg', None, None, None, ''),
	('File:ProfileCasterOfBlack.jpg', None, None, None, ''),
	('File:ProfileCasterOfRed.jpg', None, None, None, ''),
	('File:ProfileCaules.png', None, None, None, ''),
	('File:ProfileCelenike.jpg', None, None, None, ''),
	('File:ProfileDarnic.png', None, None, None, ''),
	('File:ProfileFiore.jpg', None, None, None, ''),
	('File:ProfileGordes.jpg', None, None, None, ''),
	('File:ProfileKairi.png', None, None, None, ''),
	('File:ProfileLancerBlack.png', None, None, None, ''),
	('File:ProfileLancerOfBlack.png', None, None, None, ''),
	('File:ProfileLancerOfRed.jpg', None, None, None, ''),
	('File:ProfileReika.jpg', None, None, None, ''),
	('File:ProfileRiderOfBlack.jpg', None, None, None, ''),
	('File:ProfileRiderOfRed.jpg', None, None, None, ''),
	('File:ProfileRoche.jpg', None, None, None, ''),
	('File:ProfileRuler.png', None, None, None, ''),
	('File:ProfileSaberOfBlack.png', None, None, None, ''),
	('File:ProfileSaberOfRed.png', None, None, None, ''),
	('File:ProfileSaberOfRed02.jpg', None, 2.0, None, ''),
	('File:ProfileShiro.png', None, None, None, ''),
	('File:ProfileSieg.png', None, None, None, ''),
	('File:RPG World Vol 2 Cover.jpg', 2.0, None, None, ''),
	('File:Rakudai V10 002.jpg', 10.0, 2.0, None, ''),
	('File:Rakudai V10 003.jpg', 10.0, 3.0, None, ''),
	('File:Rakudai V10 004.jpg', 10.0, 4.0, None, ''),
	('File:Rakudai V10 005.jpg', 10.0, 5.0, None, ''),
	('File:Rakudai V10 Cover.jpg', 10.0, None, None, ''),
	('File:Rakudai V10 Illus001.jpg', 10.0, 1.0, None, ''),
	('File:Rakudai V10 Illus002.jpg', 10.0, 2.0, None, ''),
	('File:Rakudai V10 Illus003.jpg', 10.0, 3.0, None, ''),
	('File:Rakudai V10 Illus004.jpg', 10.0, 4.0, None, ''),
	('File:Rakudai V10 Illus005.jpg', 10.0, 5.0, None, ''),
	('File:Rakudai V10 Illus006.jpg', 10.0, 6.0, None, ''),
	('File:Rakudai V10 Illus007.jpg', 10.0, 7.0, None, ''),
	('File:Rakudai V10 Illus008.jpg', 10.0, 8.0, None, ''),
	('File:Rakudai V10 Illus009.jpg', 10.0, 9.0, None, ''),
	('File:Rakudai V10 Illus010.jpg', 10.0, 10.0, None, ''),
	('File:Regi18 000d.jpg', None, 18.0, None, ''),
	('File:Regi18 000ef.jpg', None, 18.0, None, ''),
	('File:Regi18 000g.jpg', None, 18.0, None, ''),
	('File:Regi19 00001.jpg', None, 19.0, None, ''),
	('File:Regi20 000c.jpg', None, 20.0, None, ''),
	('File:Regi20 000e.jpg', None, 20.0, None, ''),
	('File:Regi21 000a.jpg', None, 21.0, None, ''),
	('File:Regi21 000b.jpg', None, 21.0, None, ''),
	('File:Regi21 000fg.jpg', None, 21.0, None, ''),
	('File:Regios Crusade v1 color 1.jpg', 1.0, 1.0, None, ''),
	('File:Regios Crusade v1 color 2.jpg', 1.0, 2.0, None, ''),
	('File:Regios Crusade v1.jpg', 1.0, None, None, ''),
	('File:Regios Crusade v2 color 1.jpg', 2.0, 1.0, None, ''),
	('File:Regios Crusade v2 color 2.jpg', 2.0, 2.0, None, ''),
	('File:Regios Crusade v2.jpg', 2.0, None, None, ''),
	('File:Regios Crusade v3 color 1.jpg', 3.0, 1.0, None, ''),
	('File:Regios Crusade v3 color 2.jpg', 3.0, 2.0, None, ''),
	('File:Regios Crusade v3.jpg', 3.0, None, None, ''),
	('File:Regios18.jpg', None, 18.0, None, ''),
	('File:Regios25.jpg', None, 25.0, None, ''),
	('File:Rokujouma No Shinryakusha V14 Extra 4.jpg', 14.0, 4.0, None, 'Extra 4.jpg'),
	('File:Rokujouma No Shinryakusha V14 Illustration 11.jpg', 14.0, 11.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 017.jpg', 15.0, 17.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 045.jpg', 15.0, 45.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 073.jpg', 15.0, 73.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 115.jpg', 15.0, 115.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 143.jpg', 15.0, 143.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 149.jpg', 15.0, 149.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 191.jpg', 15.0, 191.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 217.jpg', 15.0, 217.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 231.jpg', 15.0, 231.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 247.jpg', 15.0, 247.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 250.jpg', 15.0, 250.0, None, ''),
	('File:Rokujouma No Shinryakusha V15 Extra 1.jpg', 15.0, 1.0, None, 'Extra 1.jpg'),
	('File:Rokujouma No Shinryakusha V15 Extra 2.jpg', 15.0, 2.0, None, 'Extra 2.jpg'),
	('File:Rokujouma No Shinryakusha V15 Extra 3.jpg', 15.0, 3.0, None, 'Extra 3.jpg'),
	('File:SCN 0001 b.jpg', None, 1.0, None, ''),
	('File:SCN 0017 b.jpg', None, 17.0, None, ''),
	('File:SaijakuBahamut v10 Cover.jpg', 10.0, None, None, ''),
	('File:SaijakuBahamut v8 01.jpg', 8.0, 1.0, None, ''),
	('File:SaijakuBahamut v8 02.jpg', 8.0, 2.0, None, ''),
	('File:SaijakuBahamut v8 03.jpg', 8.0, 3.0, None, ''),
	('File:SaijakuBahamut v8 04.jpg', 8.0, 4.0, None, ''),
	('File:SaijakuBahamut v8 05.jpg', 8.0, 5.0, None, ''),
	('File:SaijakuBahamut v8 06.jpg', 8.0, 6.0, None, ''),
	('File:SaijakuBahamut v8 07.jpg', 8.0, 7.0, None, ''),
	('File:SaijakuBahamut v8 08.jpg', 8.0, 8.0, None, ''),
	('File:SaijakuBahamut v8 09.jpg', 8.0, 9.0, None, ''),
	('File:SaijakuBahamut v8 10.jpg', 8.0, 10.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 007.jpg', 1.0, 7.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 043.jpg', 1.0, 43.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 057.jpg', 1.0, 57.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 093.jpg', 1.0, 93.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 135.jpg', 1.0, 135.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 175.jpg', 1.0, 175.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 199.jpg', 1.0, 199.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v01 Cover.jpg', 1.0, None, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 003.jpg', 2.0, 3.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 004.jpg', 2.0, 4.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 005.jpg', 2.0, 5.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 007.jpg', 2.0, 7.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 037.jpg', 2.0, 37.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 069.jpg', 2.0, 69.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 103.jpg', 2.0, 103.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 119.jpg', 2.0, 119.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 141.jpg', 2.0, 141.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 161.jpg', 2.0, 161.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 187.jpg', 2.0, 187.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 229.jpg', 2.0, 229.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v02 Cover.jpg', 2.0, None, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 003.png', 3.0, 3.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 004.png', 3.0, 4.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 005.png', 3.0, 5.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 006.png', 3.0, 6.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 007.png', 3.0, 7.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 035.png', 3.0, 35.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 071.png', 3.0, 71.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 095.png', 3.0, 95.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 135.png', 3.0, 135.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 181.png', 3.0, 181.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 185.jpg', 3.0, 185.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 227.png', 3.0, 227.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v03 Cover.jpg', 3.0, None, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 003.png', 4.0, 3.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 004.png', 4.0, 4.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 005.png', 4.0, 5.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 007.png', 4.0, 7.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 031.png', 4.0, 31.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 081.png', 4.0, 81.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 131.png', 4.0, 131.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 159.png', 4.0, 159.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 207.png', 4.0, 207.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 291.png', 4.0, 291.0, None, ''),
	('File:Saiunkoku Monogatari Gaiden v04 Cover.jpg', 4.0, None, None, ''),
	('File:Shimoneta EX cover.jpg.jpg', None, None, None, ''),
	('File:Shimoneta v02 cover.jpg', 2.0, None, None, ''),
	('File:Shimoneta v03 cover.jpg', 3.0, None, None, ''),
	('File:Shimoneta v04 cover.jpg', 4.0, None, None, ''),
	('File:Shimoneta v05 cover.jpg', 5.0, None, None, ''),
	('File:Shimoneta v07 cover.jpg', 7.0, None, None, ''),
	('File:Shimoneta v08 cover.jpg', 8.0, None, None, ''),
	('File:Shimoneta v09 cover.jpg', 9.0, None, None, ''),
	('File:Shimoneta v10 cover.jpg', 10.0, None, None, ''),
	('File:Shimoneta v11 cover.jpg', 11.0, None, None, ''),
	('File:So What If It’s an RPG World?.jpg', None, None, None, ''),
	('File:Strangled Afterword 1 English.jpg', None, 1.0, None, 'Afterword 1 English.jpg'),
	('File:Strangled Afterword 2 English.jpg', None, 2.0, None, 'Afterword 2 English.jpg'),
	('File:TOKYO 013.jpg', None, 13.0, None, ''),
	('File:TOKYO 015.jpg', None, 15.0, None, ''),
	('File:TOKYO 019.jpg', None, 19.0, None, ''),
	('File:TOKYO 023.jpg', None, 23.0, None, ''),
	('File:TOKYO 024-025.jpg', None, 24.0, None, ''),
	('File:TOKYO 027.jpg', None, 27.0, None, ''),
	('File:TOKYO 029.jpg', None, 29.0, None, ''),
	('File:Tate no Yuusha vol2 01.jpg', 2.0, 1.0, None, ''),
	('File:Tate no Yuusha vol2 05.jpg', 2.0, 5.0, None, ''),
	('File:Tate no Yuusha vol3 01.jpg', 3.0, 1.0, None, ''),
	('File:Tiné Chelc.png', None, None, None, ''),
	('File:Toolong2001.jpg', None, 2001.0, None, ''),
	('File:Toolong2003.jpg', None, 2003.0, None, ''),
	('File:Toolong2005.jpg', None, 2005.0, None, ''),
	('File:Toolong2006.jpeg', None, 2006.0, None, ''),
	('File:Toolong2009.jpg', None, 2009.0, None, ''),
	('File:Toolong2010.jpg', None, 2010.0, None, ''),
	('File:Toolong2021.jpg', None, 2021.0, None, ''),
	('File:Toolong2091.jpg', None, 2091.0, None, ''),
	('File:Toolong2139.jpg', None, 2139.0, None, ''),
	('File:Toolong2197.jpg', None, 2197.0, None, ''),
	('File:Toolong2226.jpg', None, 2226.0, None, ''),
	('File:Toolong2242.jpg', None, 2242.0, None, ''),
	('File:Toolong2286.jpg', None, 2286.0, None, ''),
	('File:Toolong2299.jpg', None, 2299.0, None, ''),
	('File:Toolong2324.jpg', None, 2324.0, None, ''),
	('File:Toolong2ch5.jpg', None, 5.0, None, ''),
	('File:Toolong2ch6.jpg', None, 6.0, None, ''),
	('File:Toolong2ch7.jpg', None, 7.0, None, ''),
	('File:Toolong2ch8.jpg', None, 8.0, None, ''),
	('File:Trap V2.jpg', 2.0, None, None, ''),
	('File:Tumblr o3a20fLHOI1t16h1fo1 540.jpg', None, 3.0, None, ''),
	('File:Ukikumo vol2.jpg', 2.0, None, None, ''),
	('File:Ultimate Antihero 04 Cover.jpg', None, 4.0, None, ''),
	('File:Ultimate Antihero V1 ToC.jpg', 1.0, None, None, ''),
	('File:Ultimate Antihero V2 003.jpg', 2.0, 3.0, None, ''),
	('File:Ultimate Antihero V2 004.jpg', 2.0, 4.0, None, ''),
	('File:Ultimate Antihero V2 005.jpg', 2.0, 5.0, None, ''),
	('File:Ultimate Antihero V2 006.jpg', 2.0, 6.0, None, ''),
	('File:Ultimate Antihero V2 ToC.jpg', 2.0, None, None, ''),
	('File:Ultimate Antihero V3 p008.jpg', 3.0, None, 8.0, ''),
	('File:Ultimate Antihero V4 001.jpg', 4.0, 1.0, None, ''),
	('File:Ultimate Antihero V4 002-003.jpg', 4.0, 2.0, None, ''),
	('File:Ultimate Antihero V4 004-005.jpg', 4.0, 4.0, None, ''),
	('File:Ultimate Antihero V4 006-007.jpg', 4.0, 6.0, None, ''),
	('File:Ultimate Antihero V4 008.jpg', 4.0, 8.0, None, ''),
	('File:Ultimate Antihero V4 027.jpg', 4.0, 27.0, None, ''),
	('File:Ultimate Antihero V4 033.jpg', 4.0, 33.0, None, ''),
	('File:Ultimate Antihero V4 039.jpg', 4.0, 39.0, None, ''),
	('File:Ultimate Antihero V4 053.jpg', 4.0, 53.0, None, ''),
	('File:Ultimate Antihero V4 069.jpg', 4.0, 69.0, None, ''),
	('File:Ultimate Antihero V4 169.jpg', 4.0, 169.0, None, ''),
	('File:Ultimate Antihero V4 179.jpg', 4.0, 179.0, None, ''),
	('File:Ultimate Antihero V4 196.jpg', 4.0, 196.0, None, ''),
	('File:Ultimate Antihero V4 257.jpg', 4.0, 257.0, None, ''),
	('File:Ultimate Antihero V4 288.jpg', 4.0, 288.0, None, ''),
	('File:UnlimitedFafnir v11 008&clean.jpg', 11.0, 8.0, None, ''),
	('File:UnlimitedFafnir v12 000.jpg', 12.0, 0.0, None, ''),
	('File:UnlimitedFafnir v12 001.jpg', 12.0, 1.0, None, ''),
	('File:UnlimitedFafnir v12 002-003.jpg', 12.0, 2.0, None, ''),
	('File:UnlimitedFafnir v12 004-005.jpg', 12.0, 4.0, None, ''),
	('File:UnlimitedFafnir v12 006-007.jpg', 12.0, 6.0, None, ''),
	('File:UnlimitedFafnir v12 008.jpg', 12.0, 8.0, None, ''),
	('File:Valhalla no Ban Gohan V1 001.jpg', 1.0, 1.0, None, ''),
	('File:Valhalla no Ban Gohan V1 008.jpg', 1.0, 8.0, None, ''),
	('File:Valhalla no Ban Gohan V1 009.jpg', 1.0, 9.0, None, ''),
	('File:Valhalla no Ban Gohan V1 01.jpg', 1.0, 1.0, None, ''),
	('File:Valhalla no Ban Gohan V1 02.jpg', 1.0, 2.0, None, ''),
	('File:Valhalla no Ban Gohan V1 03.jpg', 1.0, 3.0, None, ''),
	('File:Valhalla no Ban Gohan V1 04.jpg', 1.0, 4.0, None, ''),
	('File:Valhalla no Ban Gohan V1 05.jpg', 1.0, 5.0, None, ''),
	('File:Valhalla no Ban Gohan V1 06.jpg', 1.0, 6.0, None, ''),
	('File:Valhalla no Ban Gohan V1 062.jpg', 1.0, 62.0, None, ''),
	('File:Valhalla no Ban Gohan V1 07.jpg', 1.0, 7.0, None, ''),
	('File:Valhalla no Ban Gohan V1 083.jpg', 1.0, 83.0, None, ''),
	('File:Valhalla no Ban Gohan V1 0837.jpg', 1.0, 837.0, None, ''),
	('File:Valhalla no Ban Gohan V1 128.jpg', 1.0, 128.0, None, ''),
	('File:Valhalla no Ban Gohan V1 157.jpg', 1.0, 157.0, None, ''),
	('File:Valhalla no Ban Gohan V1 191.jpg', 1.0, 191.0, None, ''),
	('File:Valhalla no Ban Gohan V1 239.jpg', 1.0, 239.0, None, ''),
	('File:Valhalla no Ban Gohan V1 252.jpg', 1.0, 252.0, None, ''),
	('File:Valhalla no Ban Gohan V1 cover.jpg', 1.0, None, None, ''),
	('File:Wicked Soldier King Cover.jpg', None, None, None, ''),
	('File:Yahari 4 4-8.png', None, 4.0, None, ''),
	('File:Yahari 5-1.png', None, 5.0, None, ''),
	('File:Yahari 5-3.png', None, 5.0, None, ''),
	('File:Youjo senki vol1 cover.jpg', 1.0, None, None, ''),
	('File:Zashiki Bonus Track.png', None, None, None, ''),
	('File:Zashiki Bonus Track2.png', None, 2.0, None, ''),
	('File:Zashiki Bonus Track3.png', None, 3.0, None, ''),
	('File:Zashiki Bonus Track4.png', None, 4.0, None, ''),
	('Fill in the Bubbles Contest Voting', None, None, None, ''),
	('Fill in the Bubbles Contest Winners', None, None, None, ''),
	('Final Announcement', None, None, None, ''),
	('Final Call for Original Story Submissions!', None, None, None, ''),
	('Final Chapter : Afterlife', None, None, None, ''),
	('Final Chapter and Epilogue', None, None, None, 'Epilogue'),
	('Final Chapter: The Sunset, Shiron, and Colio – Part 2', None, None, 2.0, ''),
	('Final Chapter: The Swamp of Souls, the Memory of a Smile – Part 1', None, None, 1.0, ''),
	('Final Chapter: The Swamp of Souls, the Memory of a Smile – Part 2', None, None, 2.0, ''),
	('Final Exam', None, None, None, ''),
	('Final Post! Goodbye Itranslateln~!', None, None, None, ''),
	('Final chapter of Volume 3 starts!', 3.0, None, None, ''),
	('Final chapter of book 5 is OUT!', 5.0, None, None, ''),
	('Final project thing', None, None, None, ''),
	('Finally Finished Conti New: Track 11 “an”', None, 11.0, None, ''),
	('Finally Finished it!', None, None, None, ''),
	('Finally Finished!', None, None, None, ''),
	('Finally Found Who Is “Kongkong”', None, None, None, ''),
	('Finally Home', None, None, None, ''),
	('Finally a hope', None, None, None, ''),
	('Finally an update! Parts 3-6.', None, 6.0, 3.0, ''),
	('Finally back', None, None, None, ''),
	('Finally bonus chapter! B5 C2!', 5.0, 2.0, None, ''),
	('Finally done Black Knight', None, None, None, ''),
	('Finally done. Yay. The torment is over.', None, None, None, ''),
	('Finally! New Release: V.4, Ch.79', 4.0, 79.0, None, ''),
	('Finally, Century!', None, None, None, ''),
	('Finally, Strategist!', None, None, None, ''),
	('Finally, a decision…', None, None, None, ''),
	('Finally, a man who understands politics!', None, None, None, ''),
	('Finally. Chapter 10', None, 10.0, None, ''),
	('Finally~ Chapter 27 – part 2 + pics', None, 27.0, 2.0, ''),
	('Finally…..!', None, None, None, ''),
	('Finals', None, None, None, ''),
	('Finals Finished!', None, None, None, ''),
	('Finals T_T', None, None, None, ''),
	('Finals done', None, None, None, ''),
	('Finals ~Complete~', None, None, None, ''),
	('Financial : Money, Don’t let it worries you too much', None, None, None, ''),
	('Finding Glowing Beauty in Books (书中自有颜如玉)', None, None, None, ''),
	('Finding Glowing Beauty in Books (书中自有颜如玉) – Chapter 1.1', None, 1.1, None, ''),
	('Finding Glowing Beauty in Books 书中自有颜如玉: Book Review', None, None, None, ''),
	('Finding help', None, None, None, ''),
	('Finestories has moved!', None, None, None, ''),
	('Fingering Renae Publically by LiteroCat', None, None, None, ''),
	('Finishing Touch~', None, None, None, ''),
	('Finishing Up Vol. 2 Chapter 2 – Yay', 2.0, 2.0, None, ''),
	('Finnaly Done', None, None, None, ''),
	('Fire-Mage Drawing', None, None, None, ''),
	('Firs Book “waking from a dream”', None, None, None, ''),
	('First 1000 Visitors in 6 days!!', None, 1000.0, None, ''),
	('First Battle.', None, None, None, ''),
	('First Bonus Chapter Is OUT B3, C7', 3.0, 7.0, None, ''),
	('First Chapter Of The Week B4 C5!', 4.0, 5.0, None, ''),
	('First Chapter of the Week!', None, None, None, ''),
	('First Chapter of the week!', None, None, None, ''),
	('First Encounter With An Incubus', None, None, None, ''),
	('First Grave – Everything is out to kill me….again', None, None, None, ''),
	('First Information', None, None, None, ''),
	('First Kiss', None, None, None, ''),
	('First KotB chapter of the week!', None, None, None, ''),
	('First Month Recap', None, None, None, ''),
	('First Post', None, None, None, ''),
	('First Post! : Story Synopsis : I Was a Sword When I Reincarnated', None, None, None, ''),
	('First Principle', None, None, None, ''),
	('First Principle Chapters', None, None, None, ''),
	('First Principle first & second', None, None, None, ''),
	('First Regular Chapter of the Week', None, None, None, ''),
	('First Sponsor chapter of SoJ! Ch. 6!', None, 6.0, None, ''),
	('First Try Translations: Kuro Kishi Chapter 20', None, 20.0, None, ''),
	('First Year Second Semester – Chapter 11', None, 11, None, ''),
	('First Year Second Semester – Chapter 12', None, 12, None, ''),
	('First Year Second Semester – Chapter 13', None, 13, None, ''),
	('First Year Second Semester – Chapter 14', None, 14, None, ''),
	('First Year Second Semester – Chapter 15', None, 15, None, ''),
	('First Year Second Semester – Chapter 16', None, 16, None, ''),
	('First blog post', None, None, None, ''),
	('First chapter of Doctor of the Demon World is out!', None, None, None, ''),
	('First chapter of the week', None, None, None, ''),
	('First chapter today coming late', None, None, None, ''),
	('First fan-art submission!', None, None, None, ''),
	('First generation translated chapters…', None, None, None, ''),
	('First half of V8 Prologue posted', 8.0, None, None, 'Prologue posted'),
	('First poll in Roxism[And it’s not about which goddess is the highest one(cough*Ai*cough*sha)', None, None, None, ''),
	('First principle chapter is ready', None, None, None, ''),
	('First regular chapter of the week B4, C2', 4.0, 2.0, None, ''),
	('First release of Doctor of the Demon World!', None, None, None, ''),
	('First victory and the enemy main forces (unedited)', None, None, None, ''),
	('Fish Ball’s jam', None, None, None, ''),
	('Fishballs got turned on by Cucumber strips', None, None, None, ''),
	('Fishballs is butthole', None, None, None, ''),
	('Five Way Heaven 10', None, 10.0, None, ''),
	('Five Way Heaven 11', None, 11.0, None, ''),
	('Five Way Heaven 12', None, 12.0, None, ''),
	('Five Way Heaven 13', None, 13.0, None, ''),
	('Five Way Heaven 14', None, 14.0, None, ''),
	('Five Way Heaven 15', None, 15.0, None, ''),
	('Five Way Heaven 16', None, 16.0, None, ''),
	('Five Way Heaven 17', None, 17.0, None, ''),
	('Five Way Heaven 18', None, 18.0, None, ''),
	('Five Way Heaven 19', None, 19.0, None, ''),
	('Five Way Heaven 20', None, 20.0, None, ''),
	('Five Way Heaven 21', None, 21.0, None, ''),
	('Five Way Heaven 22', None, 22.0, None, ''),
	('Five Way Heaven 23', None, 23.0, None, ''),
	('Five Way Heaven 24', None, 24.0, None, ''),
	('Five Way Heaven 25', None, 25.0, None, ''),
	('Five Way Heaven 26', None, 26.0, None, ''),
	('Five Way Heaven 27', None, 27.0, None, ''),
	('Five Way Heaven 29', None, 29.0, None, ''),
	('Five Way Heaven 3', None, 3.0, None, ''),
	('Five Way Heaven 31', None, 31.0, None, ''),
	('Five Way Heaven 32', None, 32.0, None, ''),
	('Five Way Heaven 33', None, 33.0, None, ''),
	('Five Way Heaven 6', None, 6.0, None, ''),
	('Five Way Heaven 8', None, 8.0, None, ''),
	('Five Way Heaven 9', None, 9.0, None, ''),
	('Five Way Heaven Chapter 2', None, 2.0, None, ''),
	('Five Way Heaven Chapter 30', None, 30.0, None, ''),
	('Five Way Heaven Chapter 4', None, 4.0, None, ''),
	('Five Way Heaven Chapter 5', None, 5.0, None, ''),
	('Five Way Heaven Chapter 7', None, 7.0, None, ''),
	('Fixed Link HTSAS CH8', None, 8.0, None, ''),
	('Fixed Missing Links', None, None, None, ''),
	('Fixed..', None, None, None, ''),
	('Fixes and updates – February 2016', None, 2016.0, None, ''),
	('Fixing The Stats', None, None, None, ''),
	('Fixing Things…. Q.Q', None, None, None, ''),
	('Flame Of The Highlands', None, None, None, ''),
	('Flash Marriage -11.1', None, 11.1, None, ''),
	('Flash Marriage-11.2', None, 11.2, None, ''),
	('Flash Marriage-12.1', None, 12.1, None, ''),
	('Flash Marriage-12.2', None, 12.2, None, ''),
	('Flash Marriage-14.2', None, 14.2, None, ''),
	('Flash Marriage-17.2', None, 17.2, None, ''),
	('Flash Marriage-22.2', None, 22.2, None, ''),
	('Flash Marriage-26.1', None, 26.1, None, ''),
	('Flash News 4', None, 4.0, None, ''),
	('Flash News 5', None, 5.0, None, ''),
	('Flash News 6', None, 6.0, None, ''),
	('Flash News 7', None, 7.0, None, ''),
	('Flashback: Hellfire', None, None, None, ''),
	('Flashback: Watch “The Cranberries – Linger” on YouTube', None, None, None, ''),
	('Flashbank stronk. Rant even stronker.', None, None, None, ''),
	('Flight of the Code Monkey by Kid Wigger', None, None, None, ''),
	('Flight of the Dragon, Dance of the Phoenix – Chapter 20', None, 20.0, None, ''),
	('Flight of the Dragon, Dance of the Phoenix – Chapter 21', None, 21.0, None, ''),
	('Flight of the Dragon, Dance of the Phoenix – Chapter 22', None, 22.0, None, ''),
	('Flight of the Dragon, Dance of the Phoenix – Chapter 23', None, 23.0, None, ''),
	('Flower Garden Dungeon 2nd Level (Part I)', None, 2.0, None, ''),
	('Fluff descends. Kirito descends (?!).', None, None, None, ''),
	('Fluffy Fluff Commonsenseless Paradise!', None, None, None, ''),
	('Flying Off Tomorrow', None, None, None, ''),
	('Folder Icons – For the anime and LN', None, None, None, ''),
	('Food : Grand Duck King in Sun Plaza', None, None, None, ''),
	('Food : Having Lunch in Riceville', None, None, None, ''),
	('Food: My Disappointment and Mislead culinary information', None, None, None, ''),
	('For Love and Duty 0.5', None, 0.5, None, ''),
	('For OreDungeon fans', None, None, None, ''),
	('For a more comfortable living', None, None, None, ''),
	('For all GDN Fans', None, None, None, ''),
	('For future references: Half a chapter or Full chapter?', None, None, None, ''),
	('For here I am-Lol', None, None, None, ''),
	('For our HTK fans', None, None, None, ''),
	('For the Record – Fortress', None, None, None, ''),
	('For the Record – Gamble', None, None, None, ''),
	('For the Record – Hive', None, None, None, ''),
	('For the Record – Insider', None, None, None, ''),
	('For the Record – Pyrite', None, None, None, ''),
	('For the Record – Smiley', None, None, None, ''),
	('For the Record – Source', None, None, None, ''),
	('For the Record – Trespasser', None, None, None, ''),
	('For those that aren’t seeing updates', None, None, None, ''),
	('For those who are wondering about why there weren’t any updates up till now', None, None, None, ''),
	('For those who fear.', None, None, None, ''),
	('For those who wish to be an editor here', None, None, None, ''),
	('For what it’s worth…', None, None, None, ''),
	('For you Bu-ni-mi-dynamite people who kept throwing explosive questions at me. Also, League of Ladder.', None, None, None, ''),
	('Forced redirects', None, None, None, ''),
	('Forces of Earth', None, None, None, ''),
	('Forest of Funerals – Chapter 1', None, 1.0, None, ''),
	('Forest of Funerals – Chapter 2', None, 2.0, None, ''),
	('Forest of Funerals – Chapter 3', None, 3.0, None, ''),
	('Forest of Funerals – Chapter 4', None, 4.0, None, ''),
	('Forever Your Girl', None, None, None, ''),
	('Foreword and Preface', None, None, None, 'Foreword and Preface'),
	("Forgive me but you're mine", None, None, None, ''),
	('Forgot, but also Muimui-tan 1-6', None, 1.0, None, ''),
	('Former Fiancé Novem', None, None, None, ''),
	('Forsaken Hero — Story 4-10', None, 4.0, None, ''),
	('Forsaken Hero — Story 4-11', None, 4.0, None, ''),
	('Forsaken Hero — Story 4-12', None, 4.0, None, ''),
	('Forsaken Hero — Story 4-13', None, 4.0, None, ''),
	('Forsaken Hero — Story 4-14', None, 4.0, None, ''),
	('Forsaken Hero — Story 4-15', None, 4.0, None, ''),
	('Forsaken Hero — Story 4-9', None, 4.0, None, ''),
	('Fortunately, I Did Not (幸好不是我) by: Candy (糖果)', None, None, None, ''),
	('Forum promotion', None, None, None, ''),
	('Forums', None, None, None, ''),
	('Found a cute blog', None, None, None, ''),
	('Fourth Chapter Of The Week! Book 3 Chapter 12!', 3.0, 12.0, None, ''),
	('Fourth Contest!!', None, None, None, ''),
	('Fourth Interlude', None, None, None, 'Interlude'),
	('Fourth Regular Chapter Of The Week!', None, None, None, ''),
	('Fox Ears and A Different World Journey Prequel', None, None, None, ''),
	('Fox Village (1) – Blue 93', None, 1.0, None, ''),
	('Fox Village (10) – Blue 92', None, 10.0, None, ''),
	('Fox Village (2) – Blue 93', None, 2.0, None, ''),
	('Fox Village (3) – Blue 93', None, 3.0, None, ''),
	('Fox Village (4) – Blue 93', None, 4.0, None, ''),
	('Fox Village (5) – Blue 92', None, 5.0, None, ''),
	('Fox Village (6) part 1 – Blue 92', None, 6.0, 1.0, ''),
	('Fox Village (6) part 2 – Blue 92', None, 6.0, 2.0, ''),
	('Fox Village (7) – Blue 92', None, 7.0, None, ''),
	('Fox Village (8) – Blue 92', None, 8.0, None, ''),
	('Fox Village (9) – Blue 92', None, 9.0, None, ''),
	('Frack!!! GDW 299', None, 299.0, None, ''),
	('Fragility – 01', None, 1.0, None, ''),
	('Fragility – 02', None, 2.0, None, ''),
	('Fragility – 03', None, 3.0, None, ''),
	('Fragility – 04', None, 4.0, None, ''),
	('Fragility – 05', None, 5.0, None, ''),
	('Fragility – 06', None, 6.0, None, ''),
	('Fragility – 07', None, 7.0, None, ''),
	('Fragility – 08', None, 8.0, None, ''),
	('Fragment: An Apple, Flowers, and the Passed Stone Blade', None, None, None, ''),
	('Fragment: Napping in the Hospital Room', None, None, None, ''),
	('Fragment: The Real Monster', None, None, None, ''),
	('Free Bitcoins - Collecting Coins in the meantime', None, None, None, ''),
	('Free Recipe Pamphlets', None, None, None, ''),
	('Freebitcoin Auto Multiplying Tips', None, None, None, ''),
	('Freedom will come later', None, None, None, ''),
	('Frequently Kinky, Often Sad and Sometimes Funny - Random Memoirs', None, None, None, ''),
	('Fresh Hot SOTR, Chapter 55!', None, 55.0, None, ''),
	('Freshman: Part 1', None, None, 1.0, ''),
	('Freshman: Part II', None, None, None, ''),
	('Friday Night Fights', None, None, None, ''),
	('Friends!', None, None, None, ''),
	('Friiiiii Dey!', None, None, None, ''),
	('From Brothers to Siblings : Chapter 17', None, 17.0, None, ''),
	('From Brothers to Siblings: Chapter 10', None, 10.0, None, ''),
	('From Brothers to Siblings: Chapter 11', None, 11.0, None, ''),
	('From Brothers to Siblings: Chapter 12', None, 12.0, None, ''),
	('From Brothers to Siblings: Chapter 13', None, 13.0, None, ''),
	('From Brothers to Siblings: Chapter 14', None, 14.0, None, ''),
	('From Brothers to Siblings: Chapter 15', None, 15.0, None, ''),
	('From Brothers to Siblings: Chapter 16', None, 16.0, None, ''),
	('From Brothers to Siblings: Chapter 7', None, 7.0, None, ''),
	('From Brothers to Siblings: Chapter 8', None, 8.0, None, ''),
	('From Brothers to Siblings: Chapter 9', None, 9.0, None, ''),
	('From Meditation To Sex', None, None, None, ''),
	('From TOM: Did you know Grimgal has a spinoff?', None, None, None, ''),
	('From Terra', None, None, None, ''),
	('From the bottom to the top', None, None, None, ''),
	('From “Stone Burners” by Syphax', None, None, None, ''),
	('Fu Ziyu (part 1)', None, None, 1.0, ''),
	('Fu Ziyu (part 2)', None, None, 2.0, ''),
	('Fuck College! (update)', None, None, None, ''),
	('Fuckin’ Hell….', None, None, None, ''),
	('Fudge Yeah! I Finally Cleared the Queue!', None, None, None, ''),
	('Full Metal Panic!', None, None, None, ''),
	('Full Metal Panic! Another', None, None, None, ''),
	('Full Metal Panic! Light Novel EPUB and PDF Download', None, None, None, ''),
	('Full Of My Love To You Chapter 24', None, 24.0, None, ''),
	('Full Of My Love To You Chapter 25', None, 25.0, None, ''),
	('Full Of My Love To You Chapter 26', None, 26.0, None, ''),
	('Full Of My Love To You Chapter 27', None, 27.0, None, ''),
	('Full Of My Love To You Chapter 28', None, 28.0, None, ''),
	('Full Of My Love To You Chapter 29 [END]', None, 29.0, None, ''),
	('Full chapter 54', None, 54.0, None, ''),
	('Fun Idea (in my opinion)', None, None, None, ''),
	('Fun With Translation (part 5) – Between Laughter and Tears', None, None, 5, ''),
	('Fun With Translations – Bad Translations', None, None, None, ''),
	("Fun's over, here's the actual link.", None, None, None, ''),
	('Furry ocean is so loooooooooooooong', None, None, None, ''),
	('Further Guilt: Chapter 1 – A Present At the Door', None, 1.0, None, ''),
	('Futanari 4P Part 2 ★ (Futanari Sex)', None, 4, 2, ''),
	('Futanari 4p Part 1 ★ (Blowjob)', None, 4, 1, ''),
	('Futanari beast girl, Kiki Part 1 ★ (Futanari Caress)', None, None, 1.0, ''),
	('Futanari beast girl, Kiki Part 1 ★ (Virgin Sex)', None, None, 1.0, ''),
	('Future Demon Lord Chapter 3', None, 3.0, None, ''),
	('Future Demon Lord chapter 2', None, 2.0, None, ''),
	('Future Editors', None, None, None, ''),
	('Future Plans', None, None, None, ''),
	('Future Posting Schedule', None, None, None, ''),
	('Future Project', None, None, None, ''),
	('Future Project!', None, None, None, ''),
	('Future chapter poll', None, None, None, ''),
	('Future releases', None, None, None, ''),
	('Fuyuu Gakuen no Alice and Shirley (Indonesia)', None, None, None, ''),
	('Fuyuu Gakuen no Alice and Shirley (Indonesia):Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('finally travel arranged…', None, None, None, ''),
	('finishing chapter on sunday', None, None, None, ''),
	('fireworkfolklore:\n\nIn case you haven’t noticed the ONS tag is being spammed with a bunch of stupid...', None, None, None, ''),
	('floor is such a weird little word…', None, None, None, ''),
	('forever sunshine by talorshee', None, None, None, ''),
	('friend of mine (Flying Fox)', None, None, None, ''),
	("friend's dad made me squirt and scream", None, None, None, ''),
	('fucking family history', None, None, None, ''),
	('fukasenanairo:\n\nQ: Do vampires have any complex (Like short...', None, None, None, ''),
	('full metal jacket', None, None, None, ''),
]

