

data = [
	('Q&A: Taylor', None, None, None, ''),
	('Q. and A. Chapter 1', None, 1.0, None, ''),
	('Q. and A. Chapter 2', None, 2.0, None, ''),
	('Q. and A. Chapter 3', None, 3.0, None, ''),
	('Q1 : Prologue done', None, 1.0, None, 'Prologue done'),
	('QF 28', None, 28.0, None, ''),
	('QF chaptahz', None, None, None, ''),
	('QF chapter 29', None, 29.0, None, ''),
	('QF chapters', None, None, None, ''),
	('QF34', None, 34.0, None, ''),
	('QQing About Poor-People Problems', None, None, None, ''),
	('QZGS -> The King’s Avatar', None, None, None, ''),
	('QZGS Chapter 100, 101', None, 100.0, None, ''),
	('QZGS Chapter 102', None, 102.0, None, ''),
	('QZGS Chapter 103', None, 103.0, None, ''),
	('QZGS Chapter 104', None, 104.0, None, ''),
	('QZGS Chapter 105-106', None, 105, 106, ''),
	('QZGS Chapter 107', None, 107.0, None, ''),
	('QZGS Chapter 108', None, 108.0, None, ''),
	('QZGS Chapter 109', None, 109.0, None, ''),
	('QZGS Chapter 110,111', None, 110.0, None, ''),
	('QZGS Chapter 112,113', None, 112.0, None, ''),
	('QZGS Chapter 114,115', None, 114.0, None, ''),
	('QZGS Chapter 116, 117', None, 116.0, None, ''),
	('QZGS Chapter 118, 119', None, 118.0, None, ''),
	('QZGS Chapter 91', None, 91.0, None, ''),
	('QZGS Chapter 92', None, 92.0, None, ''),
	('QZGS Chapter 93', None, 93.0, None, ''),
	('QZGS Chapter 94', None, 94.0, None, ''),
	('QZGS Chapter 95', None, 95.0, None, ''),
	('QZGS Chapter 96-97', None, 96, 97, ''),
	('QZGS Chapter 98', None, 98.0, None, ''),
	('QZGS Chapter 99', None, 99.0, None, ''),
	('QZGS Chapters 67-68', None, 67, 68, ''),
	('QZGS Chapters 69-88', None, 69, 88, ''),
	('QZGS Chapters 89-90', None, 89, 90, ''),
	('Qidian 101 by CKtalon & etvolare', None, 101.0, None, ''),
	('Qidian 101 by CKtalon & etvolare [reposting]', None, 101.0, None, ''),
	('Qidian 101 by CKtalon and etvolare', None, 101.0, None, ''),
	('Qidian Charts', None, None, None, ''),
	('Qidian Charts, most popular of 2014', None, 2014.0, None, ''),
	('Qidian charts', None, None, None, ''),
	('Qidian charts – Most popular of 2015', None, 2015.0, None, ''),
	('Qin Bi Jin Jian (禽比金坚) – C.2', None, 2.0, None, ''),
	('Qin Bi Jin Jian (禽比金坚) – C.3', None, 3.0, None, ''),
	('Qin Bi Jin Jian (禽比金坚) – C.4', None, 4.0, None, ''),
	('Qin Bi Jin Jian (禽比金坚) – C.5', None, 5.0, None, ''),
	('Qing Er: Poll Results', None, None, None, ''),
	('Qiu Mo Chapter 0: Magic Order', None, 0.0, None, ''),
	('Qote from Jokser', None, None, None, ''),
	('Quadra Suruga ~Brazilian Portuguese~', None, None, None, ''),
	('Quadruple post?', None, None, None, ''),
	('Qualidea Code Anime Adaptation Announced', None, None, None, ''),
	('Quanzhi Fashi 57 58 59 60', None, 57.0, None, ''),
	('Quanzhi Fashi 72, 73', None, 72.0, None, ''),
	('Quanzhi Fashi 82 83', None, 82.0, None, ''),
	('Quanzhi Fashi Chapter 25,26,27', None, 25.0, None, ''),
	('Quanzhi Fashi Chapter 35', None, 35.0, None, ''),
	('Quanzhi Fashi Chapter 39 & 40', None, 39.0, None, ''),
	('Quanzhi Fashi ch 38', None, 38.0, None, ''),
	('Quanzhi Fashi ch 43 & 44', None, 43.0, None, ''),
	('Quanzhi Fashi ch 52', None, 52.0, None, ''),
	('Quanzhi Fashi ch 53', None, 53.0, None, ''),
	('Quanzhi Fashi ch 56', None, 56.0, None, ''),
	('Quanzhi Fashi ch 61 62 63', None, 61.0, None, ''),
	('Quanzhi Fashi ch 64', None, 64.0, None, ''),
	('Quanzhi Fashi ch 67', None, 67.0, None, ''),
	('Quanzhi Fashi ch 75', None, 75.0, None, ''),
	('Quanzhi Fashi ch20', None, 20.0, None, ''),
	('Quanzhi Fashi ch21', None, 21.0, None, ''),
	('Quanzhi Fashi ch22', None, 22.0, None, ''),
	('Quanzhi Fashi ch23', None, 23.0, None, ''),
	('Quanzhi Fashi ch24', None, 24.0, None, ''),
	('Quanzhi Fashi ch30', None, 30.0, None, ''),
	('Quanzhi Fashi ch31-33', None, 31.0, None, ''),
	('Quanzhi Fashi ch36,37', None, 36.0, None, ''),
	('Quanzhi Fashi ch41-Intermission & 42', None, 41, None, 'ch41-Intermission & 42'),
	('Quanzhi Fashi ch49', None, 49.0, None, ''),
	('Quanzhi Fashi chapter 41', None, 41.0, None, ''),
	('Quanzhi Fashi chapter 45 & 46', None, 45.0, None, ''),
	('Quanzhi Fashi chapter 47', None, 47.0, None, ''),
	('Quanzhi Fashi chapter 48', None, 48.0, None, ''),
	('Quanzhi Fashi chapter 50 & 51', None, 50.0, None, ''),
	('Quanzhi Fashi chapter 65 66', None, 65.0, None, ''),
	('Quanzhi Fashi chapter 74', None, 74.0, None, ''),
	('Quanzhi Fashi chapter 76', None, 76.0, None, ''),
	('Quarto Mayoi ~Brazilian Portuguese~', None, None, None, ''),
	('Queen Crape Myrtle Flower', None, None, None, ''),
	('Queen of Swords 7.1', None, 7.1, None, ''),
	('Queen of Swords 7.10', None, 7.1, None, ''),
	('Queen of Swords 7.11', None, 7.11, None, ''),
	('Queen of Swords 7.12', None, 7.12, None, ''),
	('Queen of Swords 7.13', None, 7.13, None, ''),
	('Queen of Swords 7.14', None, 7.14, None, ''),
	('Queen of Swords 7.15', None, 7.15, None, ''),
	('Queen of Swords 7.16', None, 7.16, None, ''),
	('Queen of Swords 7.17', None, 7.17, None, ''),
	('Queen of Swords 7.2', None, 7.2, None, ''),
	('Queen of Swords 7.3', None, 7.3, None, ''),
	('Queen of Swords 7.4', None, 7.4, None, ''),
	('Queen of Swords 7.5', None, 7.5, None, ''),
	('Queen of Swords 7.6', None, 7.6, None, ''),
	('Queen of Swords 7.7', None, 7.7, None, ''),
	('Queen of Swords 7.8', None, 7.8, None, ''),
	('Queen of Swords 7.9', None, 7.9, None, ''),
	('Queen – Somebody to Love', None, None, None, ''),
	('Queen’s Knight Kael – Prologue', None, None, None, 'Prologue'),
	('Queen’s Knight Kael – V1 | Chapter 1', 1.0, 1.0, None, ''),
	('Queen’s Knight Kael – V1 | Chapter 2', 1.0, 2.0, None, ''),
	('Queen’s Knight Kael – V1 | Chapter 3', 1.0, 3.0, None, ''),
	('Queen’s Knight Kael – V1 | Chapter 4', 1.0, 4.0, None, ''),
	('Queen’s Knight Kael – V1 | Chapter 5', 1.0, 5.0, None, ''),
	('Question', None, None, None, ''),
	('Question 01', None, 1.0, None, ''),
	('Question 02', None, 2.0, None, ''),
	('Question 03', None, 3.0, None, ''),
	('Question 04', None, 4.0, None, ''),
	('Question 05', None, 5.0, None, ''),
	('Question 06', None, 6.0, None, ''),
	('Question 07', None, 7.0, None, ''),
	('Question 08', None, 8.0, None, ''),
	('Question 09', None, 9.0, None, ''),
	('Question 10', None, 10.0, None, ''),
	('Question 11', None, 11.0, None, ''),
	('Question 12', None, 12.0, None, ''),
	('Question 13', None, 13.0, None, ''),
	('Question 15', None, 15.0, None, ''),
	('Question 16', None, 16.0, None, ''),
	('Question 17', None, 17.0, None, ''),
	('Question 18', None, 18.0, None, ''),
	('Question 19', None, 19.0, None, ''),
	('Question 20', None, 20.0, None, ''),
	('Question 21', None, 21.0, None, ''),
	('Question 22', None, 22.0, None, ''),
	('Question for the readers:', None, None, None, ''),
	('Question’s ?', None, None, None, ''),
	('Quick Break on ZL', None, None, None, ''),
	('Quick Clarification on the ‘gap’ between 229 and 230', None, 229.0, None, ''),
	('Quick Correction', None, None, None, ''),
	('Quick Gravity Server Upgrade!', None, None, None, ''),
	('Quick Notice', None, None, None, ''),
	('Quick Server Maintenance Today', None, None, None, ''),
	('Quick Site Update!', None, None, None, ''),
	('Quick Status Update', None, None, None, ''),
	('Quick Tease', None, None, None, ''),
	('Quick Thing', None, None, None, ''),
	('Quick Update', None, None, None, ''),
	('Quick Update by THB. – May 5th', None, 5.0, None, ''),
	('Quick Update on Ads', None, None, None, ''),
	('Quick Update on Captcha Issue', None, None, None, ''),
	('Quick Update! And Terror Paradise Chapter 17 teaser!~', None, 17.0, None, ''),
	('Quick announcement!', None, None, None, ''),
	('Quick note to those who are still having problems', None, None, None, ''),
	('Quick notice about donations!', None, None, None, ''),
	('Quick question', None, None, None, ''),
	('Quick update', None, None, None, ''),
	('Quick update for Sep 2015 KS and SM Anime', None, 2015.0, None, ''),
	('Quick update on recruiting & RTD ads.', None, None, None, ''),
	('Quick update on status', None, None, None, ''),
	('Quick update to wash out the nasty taste of the last update', None, None, None, ''),
	('Quietly sneaks in + Sovereign of the Three Realms Chapter 8', None, 8.0, None, ''),
	('Quiz time!!', None, None, None, ''),
]

