

data = [
	("YES I'm A SLUT.........", None, None, None, ''),
	('YGDA Ch 20 part A', None, 20.0, None, ''),
	('YGDA Ch 21', None, 21.0, None, ''),
	('YGDA Ch 22', None, 22.0, None, ''),
	('YGDA Ch 23', None, 23.0, None, ''),
	('YGDA Ch 24', None, 24.0, None, ''),
	('YGDA Ch 25', None, 25.0, None, ''),
	('YGDA Ch 25 Part A', None, 25.0, None, ''),
	('YGDA Ch 26', None, 26.0, None, ''),
	('YGDA Ch 26 Part A', None, 26.0, None, ''),
	('YGDA Ch 27', None, 27.0, None, ''),
	('YGDA Ch 28', None, 28.0, None, ''),
	('YGDA Ch 29', None, 29.0, None, ''),
	('YGDA Ch 29 Part A', None, 29.0, None, ''),
	('YGDA Ch 30', None, 30.0, None, ''),
	('YGDA Ch 31 – It Still Hasn’t Finished Yet (The Story In This Kingdom)', None, 31.0, None, ''),
	('YGDA Ch 32', None, 32.0, None, ''),
	('YGDA Ch 32 Part A', None, 32.0, None, ''),
	('YGDA Ch 33 - Even for God, Perseverance is a Must', None, 33.0, None, ''),
	('YGDA Ch 34 Update', None, 34.0, None, ''),
	('YGDA Ch 35 update!', None, 35.0, None, ''),
	('YGDA Ch 36 Update', None, 36.0, None, ''),
	('YGDA Ch 36 part A update!', None, 36.0, None, ''),
	('YGDA ch 18', None, 18.0, None, ''),
	('YGDA ch 19', None, 19.0, None, ''),
	('YGDA ch 19 Part A', None, 19.0, None, ''),
	('YGDA ch 20', None, 20.0, None, ''),
	('YLT Type: Kouhai', None, None, None, ''),
	('YLT: Imouto', None, None, None, ''),
	('YNBW (WSK) Chapter 74', None, 74.0, None, ''),
	('YNBW (WSK) Chapter 75', None, 75.0, None, ''),
	('YNBW (WSK) Chapter 76', None, 76.0, None, ''),
	('YNBW (WSK) Chapter 77', None, 77.0, None, ''),
	('YNBW (WSK) Chapter 78', None, 78.0, None, ''),
	('YNBW (WSK) Chapter 82', None, 82.0, None, ''),
	('YNBW Vote for your choice!', None, None, None, ''),
	('YOU KNOW WHAT I JUST REALIZED?', None, None, None, ''),
	('YR VS DWGMSFF', None, None, None, ''),
	('YUUSHA YORI SAIKYOUNA KURO KISHI  – CHAPTER 8', None, 8.0, None, ''),
	('YUUSHA YORI SAIKYOUNA KURO KISHI – CHAPTER 7', None, 7.0, None, ''),
	('Ya, Hallo! This is IamMakina’s first translation Project!', None, None, None, ''),
	('Yahallo! Alice here~', None, None, None, ''),
	('Yahari Light Novel Volume 11 Illustrations (Digital Scans)', 11.0, None, None, 'Illustrations (Digital Scans)'),
	('Yahari Light Novel Volume 11 – Chapter 1', 11.0, 1.0, None, ''),
	('Yahari Light Novel Volume 11 – Chapter 1 (Part 2 of 3)', 11.0, 1.0, 2.0, ''),
	('Yahari Light Novel Volume a – Prologue 2', None, 2.0, None, 'Prologue 2'),
	('Yahari Ore no Seishun Love Come wa Machigatteiru: Volumen 2 Ilustraciones', None, 2.0, None, ''),
	('Yahari Ore no Seishun Love Come wa Machigatterir Volumen 3', None, 3.0, None, ''),
	('Yahari Ore no Seishun Love Come wa Machigatterir Volumen 3 Ilustraciones', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigateiru Español', None, None, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 2 capítulo 4', None, 2.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 3 Capítulo 1', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 3 Capítulo 2', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 3 Capítulo 3', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 3 Capítulo 4', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 3 Capítulo 5', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 3 Capítulo 6', None, 3.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 4 Capítulo 1', None, 4.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 4 Capítulo 4', None, 4.0, None, ''),
	('Yahari Ore no Seishun Rabu Kome wa Machigatteiru: Volumen 4 Capítulo 5', None, 4.0, None, ''),
	('Yahhoo~ I mean, Gooogle~', None, None, None, ''),
	('Yakushoku Distpiari - Gesellschaft Blume - 4-6 - 4-6 Hand of Truth', None, 4.0, 6.0, ''),
	('Yakushoku Distpiari - Gesellschaft Blume - vol1a - Spin Off Vol 1', 1.0, None, None, ''),
	('Yakushoku Distpiari – Gesellschaft Blume 2-4 to 2-8', None, 2.0, None, ''),
	('Yalta! We did it!', None, None, None, ''),
	('Yamato Nadeshiko, Koibana no Gotoku Chapter 1: My love shows in the blush on my face', None, 1.0, None, ''),
	('Yamato Nadeshiko, Koibana no Gotoku Chapter 2: Flowers of love are dancing, fluttering in the wind', None, 2.0, None, ''),
	('Yamato Nadeshiko, Koibana no Gotoku Prologue : Even if it means going against the world.', None, None, None, 'Prologue : Even if it means going against the world.'),
	('Yamato Nadeshiko, Koibana no Gotoku\xa0Chapter 3: Words beckoning ruin', None, 3.0, None, ''),
	('YanOto Family-Hen Chapter 4', None, 4.0, None, ''),
	('YanOto Family-Hen Chapter 5', None, 5.0, None, ''),
	('YanOto – Family-hen Chapter 7 is up', None, 7.0, None, ''),
	('YanOto – Family-hen Chapter 8 is up', None, 8.0, None, ''),
	('YanOto – Family-hen Chapter 9 is up', None, 9.0, None, ''),
	('YanOto – Family-hen Extra is up', None, None, None, 'Extra is up'),
	('YanOto – School Hen Chapter 12', None, 12.0, None, ''),
	('YanOto – School Hen Chapter 13', None, 13.0, None, ''),
	('YanOto – School Hen Chapter 6 & 7', None, 6.0, None, ''),
	('YanOto – School-Hen Chapter 11', None, 11.0, None, ''),
	('YanOto – School-Hen Chapter 4 is up', None, 4.0, None, ''),
	('YanOto – School-Hen Chapter 5 is up', None, 5.0, None, ''),
	('YanOto – School-Hen Chapter 8 & 9', None, 8.0, None, ''),
	('YanOto – School-hen Chapter 2 is up', None, 2.0, None, ''),
	('YanOto – School-hen Chapter 3 is up', None, 3.0, None, ''),
	('YanOto – School-hen is up', None, None, None, ''),
	('Yandere Chapter 1', None, 1.0, None, ''),
	('Yandere Chapter 2', None, 2.0, None, ''),
	('Yandere Chapter 3', None, 3.0, None, ''),
	('Yandere Chapter 4', None, 4.0, None, ''),
	('Yandere Chapter 5', None, 5.0, None, ''),
	('Yandere Chapter 6', None, 6.0, None, ''),
	('Yandere Chapter 7', None, 7.0, None, ''),
	('Yandere Chapter 8', None, 8.0, None, ''),
	('Yandere Chapter 9', None, 9.0, None, ''),
	('Yandere Darkness, I’m serious It’s Really [Yandere Darkness]', None, None, None, ''),
	('Yandere Love Theatrics: Prologue+Character introduction', None, None, None, 'Prologue+Character introduction'),
	('Yao Nie Bing Wang (WSK) 105', None, 105.0, None, ''),
	('Yao Nie Bing Wang (WSK) Batch Release 83, 84, 85, 86!', None, 83.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 101', None, 101.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 102', None, 102.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 103', None, 103.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 104', None, 104.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 106', None, 106.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 107', None, 107.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 108', None, 108.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 109', None, 109.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 110', None, 110.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 112', None, 112.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 113', None, 113.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 114', None, 114.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 115', None, 115.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 116', None, 116.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 117', None, 117.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 118', None, 118.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 119', None, 119.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 120', None, 120.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 121', None, 121.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 122', None, 122.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 123', None, 123.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 126', None, 126.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 127', None, 127.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 128-129', None, 128, 129, ''),
	('Yao Nie Bing Wang (WSK) Chapter 130', None, 130.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 131', None, 131.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 132-133', None, 132, 133, ''),
	('Yao Nie Bing Wang (WSK) Chapter 134&5', None, 134.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 136', None, 136.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 137', None, 137.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 138-139', None, 138, 139, ''),
	('Yao Nie Bing Wang (WSK) Chapter 140-141', None, 140, 141, ''),
	('Yao Nie Bing Wang (WSK) Chapter 142', None, 142.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 143', None, 143.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 144', None, 144.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 145', None, 145.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 146', None, 146.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 147', None, 147.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 148-149', None, 148, 149, ''),
	('Yao Nie Bing Wang (WSK) Chapter 150-151', None, 150, 151, ''),
	('Yao Nie Bing Wang (WSK) Chapter 152-153', None, 152, 153, ''),
	('Yao Nie Bing Wang (WSK) Chapter 154-155', None, 154, 155, ''),
	('Yao Nie Bing Wang (WSK) Chapter 156-157', None, 156, 157, ''),
	('Yao Nie Bing Wang (WSK) Chapter 158', None, 158.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 79', None, 79.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 87', None, 87.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 88', None, 88.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 89', None, 89.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 90', None, 90.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 91', None, 91.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 92', None, 92.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 93', None, 93.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 94', None, 94.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 95', None, 95.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 96', None, 96.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter 99', None, 99.0, None, ''),
	('Yao Nie Bing Wang (WSK) Chapter HUNNURD', None, None, None, ''),
	('Yao Nie Bing Wang (WSK) Chapters 124-125', None, 124, 125, ''),
	('Yao Nie Bing Wang (WSK) Chapters 97 & 98', None, 97.0, None, ''),
	('Yao Nie Bing Wang Chapter 111', None, 111.0, None, ''),
	('YaoNie Bing Wang (WSK) Chapter 80', None, 80.0, None, ''),
	('YaoNie Bing Wang (WSK) Chapter 81', None, 81.0, None, ''),
	('Yari no Yuusha Ch 420', None, 420.0, None, ''),
	('Yari no Yuusha Ch 427', None, 427.0, None, ''),
	('Yaritsukai to Kuroneko Ch.1 (part 2/2)', None, 1.0, 2.0, ''),
	('Yaritsukai to Kuroneko ch.1 (part 1/2)', None, 1.0, 1.0, ''),
	('Yarukinashi Eiyuutan', None, None, None, ''),
	("Yasemin's first chance (one more time 3)", None, 3.0, None, ''),
	('Yay!', None, None, None, ''),
	("Yay! Felicia's On Amazon!", None, None, None, ''),
	('Yay! I passed the JLPT N2', None, 2.0, None, ''),
	('Yay, Combat. Yay, More Cute. Yay, Mikadzuchi is Also Cute.', None, None, None, ''),
	('Yay~ back up and ready to TL.', None, None, None, ''),
	('Yeah We got Cloud Host', None, None, None, ''),
	('Yeah so…', None, None, None, ''),
	('Yeah, a little earliar then promised', None, None, None, ''),
	('Year Zero: The Fall', None, None, None, ''),
	('Year Zero: The Lowest Ebb', None, None, None, ''),
	('Year Zero: The Rise', None, None, None, ''),
	('Yes Daddy', None, None, None, ''),
	('Yes Master', None, None, None, ''),
	('Yes, I plan on continuing.', None, None, None, ''),
	('Yes, This is Actually a Blog(This is Not a Chapter)', None, None, None, ''),
	('Yes, release. Yes, cute. Yes, swimsuits. Yes, geass... wait what.', None, None, None, ''),
	('Yes, slaves', None, None, None, ''),
	('Yes, this is another poll.', None, None, None, ''),
	('Yesterday’s poll result', None, None, None, ''),
	('Yggdrasill no Ki no Shita de', None, None, None, ''),
	('Yi Jian Fei Xian Chapter 1', None, 1.0, None, ''),
	('YnO10', None, 10.0, None, ''),
	('YnO11', None, 11.0, None, ''),
	('YnO12', None, 12.0, None, ''),
	('YnO13', None, 13.0, None, ''),
	('YnO14', None, 14.0, None, ''),
	('YnO15', None, 15.0, None, ''),
	('YnO6 – E', None, 6.0, None, ''),
	('YnO7', None, 7.0, None, ''),
	('YnO8', None, 8.0, None, ''),
	('YnO9', None, 9.0, None, ''),
	('Yomuin-san wa Yuusha ja Arimasen node – Prologue – 1', None, 1.0, None, 'Prologue – 1'),
	('Yomuin-san wa Yuusha ja Arimasen node – Prologue – 2', None, 2.0, None, 'Prologue – 2'),
	('You Are Softness', None, None, None, ''),
	('You Are Under Arrest (in the Red Army)', None, None, None, ''),
	('You Can Choose Your Friends 2', None, 2.0, None, ''),
	('You Can Choose Your Friends 3', None, 3.0, None, ''),
	('You Can Choose Your Friends 4', None, 4.0, None, ''),
	('You Can Choose Your Friends 5', None, 5.0, None, ''),
	('You Cum Too Much!', None, None, None, ''),
	('You DARE!', None, None, None, ''),
	('You Don’t Have To Read This Message', None, None, None, ''),
	('You Have Been Summoned!!', None, None, None, ''),
	('You Have Guts! (你有种) – Ch. 12', None, 12.0, None, ''),
	('You Have Guts! (你有种) – Ch. 13', None, 13.0, None, ''),
	('You Have Guts! (你有种) – Ch. 14', None, 14.0, None, ''),
	('You Should Read: 剣刻の銀乙女 (Kenkoku no Jungfrau)', None, None, None, ''),
	('You Should Read: 千の魔剣と盾の乙女 (Thousand and Aegis)', None, None, None, ''),
	('You Should Read: 黒鋼の魔紋修復士 (Kuro no Hiera Glaphicos)', None, None, None, ''),
	('You Stole My Darkest Fantasy...', None, None, None, ''),
	('You can find volume 1 of the Guren Light Novels in English on Amazon.', 1.0, None, None, ''),
	('You knew this was coming ;)', None, None, None, ''),
	('You think it’s fine to just summon me to another world? Chapter 1 – I’ll never forgive you all', None, 1.0, None, ''),
	('You think it’s fine to just summon me to another world? Huh?', None, None, None, ''),
	("You're Mine Now--Character Pics", None, None, None, ''),
	("You're drunk, go home", None, None, None, ''),
	('Youhei Monogatari ~Junsuinaru Hangyakusha (Rebellion) ~ Prologue 1 – Late Checkout', None, 1.0, None, 'Prologue 1 – Late Checkout'),
	('Youhei Monogatari ~Junsuinaru Hangyakusha (Rebellion) ~ Prologue 2 – The wolf’s liver and first remuneration', None, 2.0, None, 'Prologue 2 – The wolf’s liver and first remuneration'),
	('Youjo Senki', None, None, None, ''),
	('Youjo Senki (幼女戦記) gets anime.', None, None, None, ''),
	('Youjo Senki Volume 1 Chapter 1', 1.0, 1.0, None, ''),
	('Youjo Senki Volume 1 Chapter 2', 1.0, 2.0, None, ''),
	('Youjo Senki Volume 1 Chapter 3', 1.0, 3.0, None, ''),
	('Youjo Senki Volume 1 Chapter 3 Preview', 1.0, 3.0, None, ''),
	('Youjo Senki Volume 1 Prologue', 1.0, None, None, 'Prologue'),
	('Youjo Senki manga begins serialization at the end of April', None, None, None, ''),
	('Young God Divine Armaments ch 10 ♥', None, 10.0, None, ''),
	('Young God Divine Armaments ch 11', None, 11.0, None, ''),
	('Young God Divine Armaments ch 12', None, 12.0, None, ''),
	('Young God Divine Armaments ch 13', None, 13.0, None, ''),
	('Young God Divine Armaments ch 14', None, 14.0, None, ''),
	('Young God Divine Armaments ch 15', None, 15.0, None, ''),
	('Young God Divine Armaments ch 16', None, 16.0, None, ''),
	('Young God Divine Armaments ch 16 (incomplete)', None, 16.0, None, ''),
	('Young God Divine Armaments ch 17', None, 17.0, None, ''),
	('Young God Divine Armaments ch 18 (Part A)', None, 18, 1, ''),
	('Young God Divine Armaments ch 18 (Part B)', None, 18.0, None, ''),
	('Young God Divine Armaments ch 3', None, 3.0, None, ''),
	('Young God Divine Armaments ch 4', None, 4.0, None, ''),
	('Young God Divine Armaments ch 5', None, 5.0, None, ''),
	('Young God Divine Armaments ch 6', None, 6.0, None, ''),
	('Young God Divine Armaments ch 7', None, 7.0, None, ''),
	('Young God Divine Armaments ch 8', None, 8.0, None, ''),
	('Young God Divine Armaments ch 9', None, 9.0, None, ''),
	('Young White Teens Taken by Black Africans by JonathanT', None, None, None, ''),
	('Your Highness -I know my wrongs. -Chapter 28.', None, 28.0, None, ''),
	('Your Highness, I Know My Wrong – Chapter 1', None, 1.0, None, ''),
	('Your Highness, I Know My Wrong – Chapter 2', None, 2.0, None, ''),
	('Your Highness, I Know My Wrong – Chapter 3', None, 3.0, None, ''),
	('Your Highness, I Know My Wrong – Chapter 4', None, 4.0, None, ''),
	('Your Highness, I Know My Wrongs Glossaries', None, None, None, ''),
	('Your Highness, I Know My Wrongs – Chapter 5', None, 5.0, None, ''),
	('Your Highness, I Know My Wrongs – Chapter 6', None, 6.0, None, ''),
	('Your Highness, I know my Wrongs – Chapter 10', None, 10.0, None, ''),
	('Your Highness, I know my Wrongs – Chapter 11', None, 11.0, None, ''),
	('Your Highness, I know my Wrongs – Chapter 12', None, 12.0, None, ''),
	('Your Highness, I know my Wrongs – Chapter 7', None, 7.0, None, ''),
	('Your Highness, I know my Wrongs – Chapter 8', None, 8.0, None, ''),
	('Your Highness, I know my Wrongs – Chapter 9', None, 9.0, None, ''),
	('Your Highness, I know my wrongs -Chapter 24.', None, 24.0, None, ''),
	('Your Highness, I know my wrongs.', None, None, None, ''),
	('Your Highness, I know my wrongs. -Chapter 13.', None, 13.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 14.', None, 14.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 15.', None, 15.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 16.', None, 16.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 17.', None, 17.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 18.', None, 18.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 19.', None, 19.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 20.', None, 20.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 22.', None, 22.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 23.', None, 23.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 25.', None, 25.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 26.', None, 26.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 27.', None, 27.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 29.', None, 29.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 30.', None, 30.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 31.', None, 31.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 32.', None, 32.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 33.', None, 33.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 34.', None, 34.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 35.', None, 35.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 36.', None, 36.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 37.', None, 37.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 38.', None, 38.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 39.', None, 39.0, None, ''),
	('Your Highness, I know my wrongs. -Chapter 40.', None, 40.0, None, ''),
	('Your Highness. -I know my wrongs. -Chapter 21.', None, 21.0, None, ''),
	('Your Humble Servant is Guilty! (微臣有罪) – Chapter 7 (Final)', None, 7.0, None, ''),
	('Your Humble Servant is Guilty! – Chapter 2', None, 2.0, None, ''),
	('Your Humble Servant is Guilty! – Chapter 3', None, 3.0, None, ''),
	('Your Humble Servant is Guilty! – Chapter 4', None, 4.0, None, ''),
	('Your Humble Servant is Guilty! – Chapter 5', None, 5.0, None, ''),
	('Your Humble Servant is Guilty! – Chapter 6', None, 6.0, None, ''),
	('Your Humble Servant is Guilty! – Pilot Chapter', None, None, None, ''),
	('Your Majesty Please Calm Down Capter 2:Punish You As A Nightwatchman.', None, 2.0, None, ''),
	('Your Majesty Please Calm Down Chapter 1: The Third Mistress', None, 1.0, None, ''),
	('Your Majesty Please Calm Down Chapter 3: Emperor Trust', None, 3.0, None, ''),
	('Your Majesty Please Calm Down Chapter 4:Major Crisis', None, 4.0, None, ''),
	('Your favorite dead series – THE POLL.', None, None, None, ''),
	('Your feedback please', None, None, None, ''),
	('Youthful Lariat Volume 1 Prologue', 1.0, None, None, 'Prologue'),
	('Youtube Channel: Animal Wonders Montana', None, None, None, ''),
	('Youtube Channel: The Brain Scoop', None, None, None, ''),
	('Yu Ren Chapter 1 Inhuman life', None, 1.0, None, ''),
	('Yu Ren Chapter 10 Whose suporter is stronger', None, 10.0, None, ''),
	('Yu Ren Chapter 11 The flood reached the Dragon Emperor’s Temple', None, 11.0, None, ''),
	('Yu Ren Chapter 2 Rare beauty', None, 2.0, None, ''),
	('Yu Ren Chapter 3 Buying with force', None, 3.0, None, ''),
	('Yu Ren Chapter 4 Ben xiaojie is the law', None, 4.0, None, ''),
	('Yu Ren Chapter 5 The female overlord at the border of the city', None, 5.0, None, ''),
	('Yu Ren Chapter 6 Raised to become an ox and a horse', None, 6.0, None, ''),
	('Yu Ren Chapter 8 One Price', None, 8.0, None, ''),
	('Yu Ren Chapter 9 Magical hands bringing the dying back to life advertisements', None, 9.0, None, ''),
	('Yu Ren chapter 7 We need to be low key', None, 7.0, None, ''),
	('Yu Wo’s blog: How would you like to die?', None, None, None, ''),
	('Yume Nikki (German)', None, None, None, ''),
	('Yume Nikki – I’m not in your Dream – You', None, None, None, ''),
	('Yun puts zombies to shame.', None, None, None, ''),
	('Yuusha Onna 23', None, 23.0, None, ''),
	('Yuusha Onna 24', None, 24.0, None, ''),
	('Yuusha Onna 25', None, 25.0, None, ''),
	('Yuusha Onna 26', None, 26.0, None, ''),
	('Yuusha Onna 27', None, 27.0, None, ''),
	('Yuusha Onna 28', None, 28.0, None, ''),
	('Yuusha Onna 29', None, 29.0, None, ''),
	('Yuusha Onna 31', None, 31.0, None, ''),
	('Yuusha Onna 32', None, 32.0, None, ''),
	('Yuusha Onna Chapter 21', None, 21.0, None, ''),
	('Yuusha Onna Chapter 22', None, 22.0, None, ''),
	('Yuusha Party 1-3', None, 1.0, None, ''),
	('Yuusha Party 10 | OreDungeon 5-6 |Recruitment', None, 10.0, None, ''),
	('Yuusha Party 10-12', None, 10.0, None, ''),
	('Yuusha Party 11-12', None, 11.0, None, ''),
	('Yuusha Party 13-14', None, 13.0, None, ''),
	('Yuusha Party 13-14 | Moving iminent', None, 13.0, None, ''),
	('Yuusha Party 15-16+', None, 15.0, None, ''),
	('Yuusha Party 17-18', None, 17.0, None, ''),
	('Yuusha Party 19', None, 19.0, None, ''),
	('Yuusha Party 7-9', None, 7.0, None, ''),
	('Yuusha Party Chapter 4&5', None, 4.0, None, ''),
	('Yuusha Party Chapter 6', None, 6.0, None, ''),
	('Yuusha Party WN20-22/LN 8-9 | OreDungeon 1-4', None, 20.0, None, ''),
	('Yuusha Party lives!', None, None, None, ''),
	('Yuusha Party – Chapter 121 (p1)', None, 121.0, 1.0, ''),
	('Yuusha Party – Chapter 147', None, 147.0, None, ''),
	('Yuusha Party – Chapter 150', None, 150.0, None, ''),
	('Yuusha Party – Chapter 37', None, 37.0, None, ''),
	('Yuusha Party – Chapter 55', None, 55.0, None, ''),
	('Yuusha Yori Saikyouna Kuro Kishi – Chapter 9', None, 9.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 1', None, 1.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 10', None, 10.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 11', None, 11.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 12', None, 12.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 13', None, 13.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 14', None, 14.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 15', None, 15.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 16', None, 16.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 17', None, 17.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 18', None, 18.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 19', None, 19.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 2', None, 2.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 20', None, 20.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 3', None, 3.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 4', None, 4.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 5', None, 5.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 6', None, 6.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 7', None, 7.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 8', None, 8.0, None, ''),
	('Yuusha ga onna da to dame desu ka? Chapter 9', None, 9.0, None, ''),
	('Yuusha-sama no Oshishou-sama - Chapter 1 Part 1', None, 1.0, 1.0, ''),
	('Yuusha-sama no Oshishou-sama - Chapter 1 Part 2', None, 1.0, 2.0, ''),
	('yay rant. update???', None, None, None, ''),
	('yay there’s sum HTK', None, None, None, ''),
	('you should come by our base', None, None, None, ''),
]

