

data = [
	('“5.8 Interlude (Samael)” from “Anathema” by Chrysalis', None, 5.8, None, 'Interlude (Samael)” from “Anathema” by Chrysalis'),
	('“Bolna” English Translation and Lyrics', None, None, None, ''),
	('“Damned I” by Shaeor', None, None, None, ''),
	('“Death March” 1-2 and small changes', None, 1.0, None, ''),
	('“Death March” Volume 1 Chapter 1', 1.0, 1.0, None, ''),
	('“Fancy” PDFs', None, None, None, ''),
	('“Flannel” is actually “Nell”, huh.', None, None, None, ''),
	('“High spec highschool girl’s parallel world reincarnation – aiming for a more abundant livelihood!” -translation', None, None, None, ''),
	('“I am alive” – post', None, None, None, ''),
	('“I wrote it! Spread the news! Mika, Ferid, Crowley, the vampire...', None, None, None, ''),
	('“Kill Yourself Working” by Knifleman', None, None, None, ''),
	('“Liberation” by Psycho Gecko', None, None, None, ''),
	('“Mind Control: Cubs be Aware!” Chapter 1: Denny', None, 1.0, None, ''),
	('“Mind Control: Cubs be Aware!” Chapter 2: Jerry', None, 2.0, None, ''),
	('“Mind Control: Cubs be Aware!” Chapter 3: Bobby', None, 3.0, None, ''),
	('“Nandesho?” by Deco*27, English Lyrics', None, 27.0, None, ''),
	('“Once Giants, Volume I:  The Size Queen” by Team Contract', None, None, None, ''),
	('“Power Play” by Gregory Taylor', None, None, None, ''),
	('“Project Qualidea” Special Roundtable Discussion with Sagara Sou, Tachibana Koushi and Watari Wataru', None, None, None, ''),
	('“Sanctioned, Book One: Rejects” by ChrysKelly', 1, None, None, ''),
	('“Sin ~ Sin>\nAct 1: People are Pulpits\nPart 2: History', None, 1.0, None, ''),
	('“Sin ~ Sin> Act 1: People are Pulpits Part 1: Party', None, 1.0, 1.0, ''),
	('“Support a Webfiction” Event', None, None, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” :  Chapter 29 Love and Hate', None, 29.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 20 IDENTITY QUESTION', None, 20.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 21 WISHFUL THINKING', None, 21.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 22 Unexpected Invitation', None, 22.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 23 FEAR', None, 23.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 24 THE REUNION', None, 24.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 25 I’M NOT HER', None, 25.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 26 ESCAPE', None, 26.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 27 AT THE LAKE”', None, 27.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : CHAPTER 28 LIFE OR DEATH', None, 28.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : Chapter 16 THE RETURN OF CONCUBINE DAUGHTER', None, 16.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : Chapter 17 ENEMIES ON A NARROW ROAD', None, 17.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : Chapter 18 GESTURES', None, 18.0, None, ''),
	('“The Rebirth of Deceased Consort that Astounded the World” : Chapter 19 UNNATURAL', None, 19.0, None, ''),
	('“When I Returned” Chapter 1', None, 1, None, ''),
	('“Yeh Fitoor Mera” English Translation and Lyrics', None, None, None, ''),
	('“You bored?” or “Why OniAi hasn’t been edited yet.”', None, None, None, ''),
	('“before light” by keeno ft. Hatsune Miku Dark', None, None, None, ''),
]

