

data = [
	('...', None, None, None, ''),
	('..........err', None, None, None, ''),
	('....and it started so beautiful', None, None, None, ''),
	('./lazing_irl.exe', None, None, None, ''),
	('.Girl Corps – Chapter 2.', None, 2.0, None, ''),
	('.Girl Corps – Chapter 3.', None, 3.0, None, ''),
	('.I bought a girl – Chapter 1.', None, 1.0, None, ''),
	('.I bought a girl – Chapter 17.', None, 17.0, None, ''),
	('.I bought a girl – Chapter 2.', None, 2.0, None, ''),
	('.I bought a girl – Chapter 3.', None, 3.0, None, ''),
	('.I bought a girl – Chapter 4.', None, 4.0, None, ''),
	('.I bought a girl – Chapter 5.', None, 5.0, None, ''),
	('.I bought a girl – Chapter 6.', None, 6.0, None, ''),
	('.I bought a girl – Chapter(s) 12, 13, 14, 15.', None, 12.0, None, ''),
	('.I bought a girl – Chapter(s) 7 and 8.', None, 7.0, None, ''),
	('.I bought a girl – Chapter(s) 9, 10, 11.', None, 9.0, None, ''),
	('.I bought a girl – EXTRA 1.', None, 1.0, None, 'EXTRA 1.'),
	('.I can speak – Chapter 10.', None, 10.0, None, ''),
	('.I can speak – Chapter 12.', None, 12.0, None, ''),
	('.I can speak – Chapter 13.', None, 13.0, None, ''),
	('.Modern Weapons – Volume 2 Chapter 13.', 2.0, 13.0, None, ''),
	('.Modern Weapons – Volume 2 Chapter 14.', 2.0, 14.0, None, ''),
	('.Modern Weapons – Volume 2 Chapter 15.', 2.0, 15.0, None, ''),
	('.Modern Weapons – Volume 2 Chapter 16.', 2.0, 16.0, None, ''),
	('.Modern Weapons – Volume 3 Chapter 1 (Part 2).', 3.0, 1.0, 2.0, ''),
	('.Modern weapons – Volume 2 Chapter 17.', 2.0, 17.0, None, ''),
	('.Modern weapons – Volume 3 chapter 1 (Part 1).', 3.0, 1.0, 1.0, ''),
	('.Upper World – Chapter 12.', None, 12.0, None, ''),
	('.Upper world – Chapter 13.', None, 13.0, None, ''),
	('.Upper world – Chapter 14.', None, 14.0, None, ''),
]

