
RUNSTATE       = True
FEEDER_STARTED = False

RSS_DEBUG      = False

RULE_CACHE           = None
SPECIAL_CASE_CACHE   = None
RAW_MIRROR_CACHE     = None
TRIGGERED_URLS_CACHE = None

IS_FLASK = False