"""starting

Revision ID: fba1df4514fa
Revises: 
Create Date: 2016-01-10 18:27:20.101437

"""

# revision identifiers, used by Alembic.
revision = 'fba1df4514fa'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_page_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errno', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('file', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('is_text', sa.Boolean(), nullable=True),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('fetchtime', sa.DateTime(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('tsv_content', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.Column('root_rel', sa.Integer(), nullable=False),
    sa.Column('newer_rel', sa.Integer(), nullable=True),
    sa.Column('older_rel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['web_files.id'], ),
    sa.ForeignKeyConstraint(['newer_rel'], ['web_page_history.id'], ),
    sa.ForeignKeyConstraint(['older_rel'], ['web_page_history.id'], ),
    sa.ForeignKeyConstraint(['root_rel'], ['web_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_page_history_distance'), 'web_page_history', ['distance'], unique=False)
    op.create_index('ix_web_page_history_tsv_content', 'web_page_history', ['tsv_content'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_web_page_history_url'), 'web_page_history', ['url'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_page_history_url'), table_name='web_page_history')
    op.drop_index('ix_web_page_history_tsv_content', table_name='web_page_history')
    op.drop_index(op.f('ix_web_page_history_distance'), table_name='web_page_history')
    op.drop_table('web_page_history')
    ### end Alembic commands ###
