"""starting

Revision ID: a4cb7899f08f
Revises: fba1df4514fa
Create Date: 2016-01-10 18:55:20.339504

"""

# revision identifiers, used by Alembic.
revision = 'a4cb7899f08f'
down_revision = 'fba1df4514fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_page_history', sa.Column('contenthash', sa.Text(), nullable=True))
    op.add_column('web_page_history', sa.Column('is_diff', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_page_history', 'is_diff')
    op.drop_column('web_page_history', 'contenthash')
    ### end Alembic commands ###
