"""empty message

Revision ID: 52ecc22110c4
Revises: f6cfe0a6836c
Create Date: 2016-05-19 22:52:33.458073

"""

# revision identifiers, used by Alembic.
revision = '52ecc22110c4'
down_revision = 'f6cfe0a6836c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nu_outbound_wrappers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('container_page', sa.Text(), nullable=True),
        sa.Column('link_url', sa.Text(), nullable=True),
        sa.Column('target_url', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nu_outbound_wrappers_container_page'), 'nu_outbound_wrappers', ['container_page'], unique=False)
    op.create_index(op.f('ix_nu_outbound_wrappers_link_url'), 'nu_outbound_wrappers', ['link_url'], unique=False)
    op.drop_index('web_pages_state_netloc_idx', table_name='web_pages')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('web_pages_state_netloc_idx', 'web_pages', ['state', 'netloc'], unique=False)
    op.drop_index(op.f('ix_nu_outbound_wrappers_link_url'), table_name='nu_outbound_wrappers')
    op.drop_index(op.f('ix_nu_outbound_wrappers_container_page'), table_name='nu_outbound_wrappers')
    op.drop_table('nu_outbound_wrappers')
    ### end Alembic commands ###
