"""empty message

Revision ID: d50da91f4e86
Revises: 9abd467440df
Create Date: 2016-10-31 00:00:01.829105

"""

# revision identifiers, used by Alembic.
revision = 'd50da91f4e86'
down_revision = '9abd467440df'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_web_pages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger())
    op.alter_column('raw_web_pages_version', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_web_pages_version', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER())
    op.alter_column('raw_web_pages', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER())
    ### end Alembic commands ###
