"""empty message

Revision ID: 963e454edeee
Revises: 8ae5aae58f62
Create Date: 2016-10-31 06:04:39.039429

"""

# revision identifiers, used by Alembic.
revision = '963e454edeee'
down_revision = '8ae5aae58f62'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nu_release_item_seriesname_releaseinfo_groupinfo_outbound_w_key', 'nu_release_item', type_='unique')
    op.create_unique_constraint(None, 'nu_release_item', ['seriesname', 'releaseinfo', 'groupinfo', 'outbound_wrapper'])
    op.create_unique_constraint(None, 'nu_release_item', ['outbound_wrapper'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nu_release_item', type_='unique')
    op.drop_constraint(None, 'nu_release_item', type_='unique')
    op.create_unique_constraint('nu_release_item_seriesname_releaseinfo_groupinfo_outbound_w_key', 'nu_release_item', ['seriesname', 'releaseinfo', 'groupinfo', 'outbound_wrapper', 'actual_target'])
    ### end Alembic commands ###
