"""More validation

Revision ID: 1b4006c4f120
Revises: c03e35792e2a
Create Date: 2016-11-24 06:08:13.470594

"""

# revision identifiers, used by Alembic.
revision = '1b4006c4f120'
down_revision = 'c03e35792e2a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils
from sqlalchemy import literal

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nu_release_item', sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=literal(False)))
    op.create_index(op.f('ix_nu_release_item_reviewed'), 'nu_release_item', ['reviewed'], unique=False)
    op.create_index(op.f('ix_nu_release_item_validated'), 'nu_release_item', ['validated'], unique=False)
    op.create_index(op.f('ix_nu_release_item_validated_on'), 'nu_release_item', ['validated_on'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nu_release_item_validated_on'), table_name='nu_release_item')
    op.drop_index(op.f('ix_nu_release_item_validated'), table_name='nu_release_item')
    op.drop_index(op.f('ix_nu_release_item_reviewed'), table_name='nu_release_item')
    op.drop_column('nu_release_item', 'reviewed')
    ### end Alembic commands ###
