"""empty message

Revision ID: 6afc6cc95487
Revises: 963e454edeee
Create Date: 2016-11-03 01:49:34.974187

"""

# revision identifiers, used by Alembic.
revision = '6afc6cc95487'
down_revision = '963e454edeee'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nu_resolved_outbound', ['parent', 'client_id', 'client_key', 'actual_target'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nu_resolved_outbound', type_='unique')
    ### end Alembic commands ###
