"""Dropping unused columns now

Revision ID: d547cd837350
Revises: 1dc0fe0d793f
Create Date: 2017-02-28 07:29:45.214970

"""

# revision identifiers, used by Alembic.
revision = 'd547cd837350'
down_revision = '1dc0fe0d793f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # Make these columns nullable now.
    op.alter_column('feed_pages', 'srcname',
               nullable=True)
    op.alter_column('feed_pages', 'feedurl',
               nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
