"""Moarrrrrrrrrrr rss stuff

Revision ID: 9d03d8bba40e
Revises: c92e0c8632d7
Create Date: 2017-02-27 06:37:27.490654

"""

# revision identifiers, used by Alembic.
revision = '9d03d8bba40e'
down_revision = 'c92e0c8632d7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_pages', sa.Column('feed_id', sa.BigInteger()))
    op.create_index(op.f('ix_feed_pages_feed_id'), 'feed_pages', ['feed_id'], unique=False)
    op.create_foreign_key(None, 'feed_pages', 'rss_parser_funcs', ['feed_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feed_pages', type_='foreignkey')
    op.drop_index(op.f('ix_feed_pages_feed_id'), table_name='feed_pages')
    op.drop_column('feed_pages', 'feed_id')
    ### end Alembic commands ###
