"""empty message

Revision ID: 5272b11df6a8
Revises: 11dbcd6e5ee3
Create Date: 2017-09-28 04:23:24.283199

"""

# revision identifiers, used by Alembic.
revision = '5272b11df6a8'
down_revision = '11dbcd6e5ee3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE nu_release_item SET fetch_attempts = 3 WHERE validated is TRUE")
    op.execute("commit")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass

