"""empty message

Revision ID: 5aa994117f07
Revises: 85a1c0888f3d
Create Date: 2017-09-28 04:03:38.834496

"""

# revision identifiers, used by Alembic.
revision = '5aa994117f07'
down_revision = '85a1c0888f3d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nu_release_item', sa.Column('fetch_attempts', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nu_release_item', 'fetch_attempts')
    ### end Alembic commands ###
