"""empty message

Revision ID: 85a1c0888f3d
Revises: be0687950ece
Create Date: 2017-03-08 04:51:21.957091

"""

# revision identifiers, used by Alembic.
revision = '85a1c0888f3d'
down_revision = 'be0687950ece'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session as BaseSession, relationship


from sqlalchemy import Column
from sqlalchemy import BigInteger
from sqlalchemy import Integer
from sqlalchemy import Text
from sqlalchemy import Float
from sqlalchemy import Boolean
from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import PrimaryKeyConstraint
from sqlalchemy import UniqueConstraint
from sqlalchemy.orm import relationship
from sqlalchemy.schema import UniqueConstraint


Session = sessionmaker()

Base = declarative_base()

class RssFeedEntry(Base):
    __versioned__ = {}

    __tablename__     = 'rss_parser_funcs'
    name              = 'rss_parser_funcs'

    id                = Column(BigInteger, primary_key = True, index = True)

    last_changed      = Column(DateTime, nullable=False)



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_parser_funcs', sa.Column('last_changed', sa.DateTime(), nullable=True))
    op.add_column('rss_parser_funcs_version', sa.Column('last_changed', sa.DateTime(), autoincrement=False, nullable=True))


    bind = op.get_bind()
    sess = Session(bind=bind)

    print("Updating date/time stamps for functions.")
    sess.query(RssFeedEntry).update({'last_changed' : datetime.datetime.now()})
    sess.commit()
    print("Update done.")

    op.alter_column('rss_parser_funcs', 'last_changed', nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_parser_funcs_version', 'last_changed')
    op.drop_column('rss_parser_funcs', 'last_changed')
    ### end Alembic commands ###
