"""empty message

Revision ID: 11dbcd6e5ee3
Revises: 5aa994117f07
Create Date: 2017-09-28 04:06:18.968893

"""

# revision identifiers, used by Alembic.
revision = '11dbcd6e5ee3'
down_revision = '5aa994117f07'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.execute("UPDATE nu_release_item SET fetch_attempts = 0 WHERE fetch_attempts IS NULL")
    op.alter_column('nu_release_item', 'fetch_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nu_release_item', 'fetch_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
