"""add another enum type

Revision ID: 804a59c2c76c
Revises: 4c8331188a48
Create Date: 2020-12-06 08:47:45.967439

"""

# revision identifiers, used by Alembic.
revision = '804a59c2c76c'
down_revision = '4c8331188a48'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("COMMIT")
    op.execute("ALTER TYPE dlstate_enum ADD VALUE 'manually_deferred';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError("Cannot downgrade!")
    # ### end Alembic commands ###
