"""Add URL column (Derp!)

Revision ID: 2d10f39bfbfd
Revises: 669e9df34ea7
Create Date: 2020-01-20 05:40:48.520465

"""

# revision identifiers, used by Alembic.
revision = '2d10f39bfbfd'
down_revision = '669e9df34ea7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seen_netloc_tracker', sa.Column('example_url', citext.CIText(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_netloc_tracker_example_url'), table_name='seen_netloc_tracker')
    op.drop_column('seen_netloc_tracker', 'example_url')
    # ### end Alembic commands ###
