"""Add Skipped enum value

Revision ID: 1384202f8121
Revises: 8b536bc5d716
Create Date: 2020-04-27 12:29:07.037892

"""

# revision identifiers, used by Alembic.
revision = '1384202f8121'
down_revision = '8b536bc5d716'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feed_author_author'), 'feed_author', ['author'], unique=False)
    op.drop_index('feed_pages_published_idx', table_name='feed_pages')
    op.create_index(op.f('ix_feed_tags_tag'), 'feed_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_nu_release_item_seriesname'), 'nu_release_item', ['seriesname'], unique=False)
    op.create_index(op.f('ix_nu_resolved_outbound_parent'), 'nu_resolved_outbound', ['parent'], unique=False)
    op.drop_index('plugin_status_plugin_name_idx', table_name='plugin_status')
    op.create_index(op.f('ix_raw_web_pages_id'), 'raw_web_pages', ['id'], unique=False)
    op.create_index(op.f('ix_raw_web_pages_netloc'), 'raw_web_pages', ['netloc'], unique=False)
    op.drop_index('raw_web_pages_id_state_fetchtime_idx', table_name='raw_web_pages')
    op.drop_index('raw_web_pages_netloc_fetchtime_idx', table_name='raw_web_pages')
    op.create_index(op.f('ix_raw_web_pages_version_data_hash'), 'raw_web_pages_version', ['data_hash'], unique=True)
    op.create_index(op.f('ix_raw_web_pages_version_id'), 'raw_web_pages_version', ['id'], unique=False)
    op.create_index(op.f('ix_raw_web_pages_version_parent_hash'), 'raw_web_pages_version', ['parent_hash'], unique=False)
    op.drop_constraint('raw_web_pages_version_data_hash_key', 'raw_web_pages_version', type_='unique')
    op.create_index(op.f('ix_rss_parser_feed_name_lut_feed_netloc'), 'rss_parser_feed_name_lut', ['feed_netloc'], unique=False)
    op.create_index(op.f('ix_rss_parser_feed_name_lut_id'), 'rss_parser_feed_name_lut', ['id'], unique=False)
    op.create_index(op.f('ix_rss_parser_feed_name_lut_version_data_hash'), 'rss_parser_feed_name_lut_version', ['data_hash'], unique=True)
    op.create_index(op.f('ix_rss_parser_feed_name_lut_version_id'), 'rss_parser_feed_name_lut_version', ['id'], unique=False)
    op.create_index(op.f('ix_rss_parser_feed_name_lut_version_parent_hash'), 'rss_parser_feed_name_lut_version', ['parent_hash'], unique=False)
    op.drop_constraint('rss_parser_feed_name_lut_version_data_hash_key', 'rss_parser_feed_name_lut_version', type_='unique')
    op.create_index(op.f('ix_rss_parser_funcs_id'), 'rss_parser_funcs', ['id'], unique=False)
    op.create_index(op.f('ix_rss_parser_funcs_version_data_hash'), 'rss_parser_funcs_version', ['data_hash'], unique=True)
    op.create_index(op.f('ix_rss_parser_funcs_version_id'), 'rss_parser_funcs_version', ['id'], unique=False)
    op.create_index(op.f('ix_rss_parser_funcs_version_parent_hash'), 'rss_parser_funcs_version', ['parent_hash'], unique=False)
    op.drop_constraint('rss_parser_funcs_version_data_hash_key', 'rss_parser_funcs_version', type_='unique')
    op.create_index(op.f('ix_seen_netloc_tracker_example_url'), 'seen_netloc_tracker', ['example_url'], unique=True)
    op.create_index(op.f('ix_web_cookie_db_id'), 'web_cookie_db', ['id'], unique=False)
    op.drop_index('web_files_filename_idx', table_name='web_files')
    op.create_index(op.f('ix_web_pages_id'), 'web_pages', ['id'], unique=False)
    op.create_index(op.f('ix_web_pages_netloc'), 'web_pages', ['netloc'], unique=False)
    op.create_index(op.f('ix_web_pages_state'), 'web_pages', ['state'], unique=False)
    op.drop_index('ix_web_pages_id_state', table_name='web_pages')
    op.drop_index('ix_web_pages_state_id', table_name='web_pages')
    op.drop_index('web_pages_netloc_fetchtime_idx', table_name='web_pages')
    op.drop_index('web_pages_netloc_id_idx', table_name='web_pages')
    op.create_index(op.f('ix_web_pages_version_data_hash'), 'web_pages_version', ['data_hash'], unique=True)
    op.create_index(op.f('ix_web_pages_version_distance'), 'web_pages_version', ['distance'], unique=False)
    op.create_index(op.f('ix_web_pages_version_fetchtime'), 'web_pages_version', ['fetchtime'], unique=False)
    op.create_index(op.f('ix_web_pages_version_id'), 'web_pages_version', ['id'], unique=False)
    op.create_index(op.f('ix_web_pages_version_netloc'), 'web_pages_version', ['netloc'], unique=False)
    op.create_index(op.f('ix_web_pages_version_operation_type'), 'web_pages_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_web_pages_version_parent_hash'), 'web_pages_version', ['parent_hash'], unique=False)
    op.create_index(op.f('ix_web_pages_version_priority'), 'web_pages_version', ['priority'], unique=False)
    op.create_index(op.f('ix_web_pages_version_state'), 'web_pages_version', ['state'], unique=False)
    op.create_index(op.f('ix_web_pages_version_transaction_id'), 'web_pages_version', ['transaction_id'], unique=False)
    op.drop_constraint('web_pages_version_data_hash_key', 'web_pages_version', type_='unique')
    op.drop_index('web_pages_version_id_url_idx', table_name='web_pages_version')
    op.create_foreign_key(None, 'web_pages_version', 'web_pages_version', ['parent_hash'], ['data_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_pages_version', type_='foreignkey')
    op.create_index('web_pages_version_id_url_idx', 'web_pages_version', ['id', 'url'], unique=False)
    op.create_unique_constraint('web_pages_version_data_hash_key', 'web_pages_version', ['data_hash'])
    op.drop_index(op.f('ix_web_pages_version_transaction_id'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_state'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_priority'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_parent_hash'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_operation_type'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_netloc'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_id'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_fetchtime'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_distance'), table_name='web_pages_version')
    op.drop_index(op.f('ix_web_pages_version_data_hash'), table_name='web_pages_version')
    op.create_index('web_pages_netloc_id_idx', 'web_pages', ['netloc', 'id'], unique=False)
    op.create_index('web_pages_netloc_fetchtime_idx', 'web_pages', ['netloc', 'fetchtime'], unique=False)
    op.create_index('ix_web_pages_state_id', 'web_pages', ['state', 'id'], unique=False)
    op.create_index('ix_web_pages_id_state', 'web_pages', ['id', 'state'], unique=False)
    op.drop_index(op.f('ix_web_pages_state'), table_name='web_pages')
    op.drop_index(op.f('ix_web_pages_netloc'), table_name='web_pages')
    op.drop_index(op.f('ix_web_pages_id'), table_name='web_pages')
    op.create_index('web_files_filename_idx', 'web_files', ['filename'], unique=False)
    op.drop_index(op.f('ix_web_cookie_db_id'), table_name='web_cookie_db')
    op.drop_index(op.f('ix_seen_netloc_tracker_example_url'), table_name='seen_netloc_tracker')
    op.create_unique_constraint('rss_parser_funcs_version_data_hash_key', 'rss_parser_funcs_version', ['data_hash'])
    op.drop_index(op.f('ix_rss_parser_funcs_version_parent_hash'), table_name='rss_parser_funcs_version')
    op.drop_index(op.f('ix_rss_parser_funcs_version_id'), table_name='rss_parser_funcs_version')
    op.drop_index(op.f('ix_rss_parser_funcs_version_data_hash'), table_name='rss_parser_funcs_version')
    op.drop_index(op.f('ix_rss_parser_funcs_id'), table_name='rss_parser_funcs')
    op.create_unique_constraint('rss_parser_feed_name_lut_version_data_hash_key', 'rss_parser_feed_name_lut_version', ['data_hash'])
    op.drop_index(op.f('ix_rss_parser_feed_name_lut_version_parent_hash'), table_name='rss_parser_feed_name_lut_version')
    op.drop_index(op.f('ix_rss_parser_feed_name_lut_version_id'), table_name='rss_parser_feed_name_lut_version')
    op.drop_index(op.f('ix_rss_parser_feed_name_lut_version_data_hash'), table_name='rss_parser_feed_name_lut_version')
    op.drop_index(op.f('ix_rss_parser_feed_name_lut_id'), table_name='rss_parser_feed_name_lut')
    op.drop_index(op.f('ix_rss_parser_feed_name_lut_feed_netloc'), table_name='rss_parser_feed_name_lut')
    op.create_unique_constraint('raw_web_pages_version_data_hash_key', 'raw_web_pages_version', ['data_hash'])
    op.drop_index(op.f('ix_raw_web_pages_version_parent_hash'), table_name='raw_web_pages_version')
    op.drop_index(op.f('ix_raw_web_pages_version_id'), table_name='raw_web_pages_version')
    op.drop_index(op.f('ix_raw_web_pages_version_data_hash'), table_name='raw_web_pages_version')
    op.create_index('raw_web_pages_netloc_fetchtime_idx', 'raw_web_pages', ['netloc', 'fetchtime'], unique=False)
    op.create_index('raw_web_pages_id_state_fetchtime_idx', 'raw_web_pages', ['id', 'state', 'fetchtime'], unique=False)
    op.drop_index(op.f('ix_raw_web_pages_netloc'), table_name='raw_web_pages')
    op.drop_index(op.f('ix_raw_web_pages_id'), table_name='raw_web_pages')
    op.create_index('plugin_status_plugin_name_idx', 'plugin_status', ['plugin_name'], unique=False)
    op.drop_index(op.f('ix_nu_resolved_outbound_parent'), table_name='nu_resolved_outbound')
    op.drop_index(op.f('ix_nu_release_item_seriesname'), table_name='nu_release_item')
    op.drop_index(op.f('ix_feed_tags_tag'), table_name='feed_tags')
    op.create_index('feed_pages_published_idx', 'feed_pages', ['published'], unique=False)
    op.drop_index(op.f('ix_feed_author_author'), table_name='feed_author')
    # ### end Alembic commands ###
