"""add new netloc tracking table

Revision ID: 669e9df34ea7
Revises: 5552dfae2cb0
Create Date: 2020-01-20 01:36:51.862767

"""

# revision identifiers, used by Alembic.
revision = '669e9df34ea7'
down_revision = '5552dfae2cb0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_netloc_tracker',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('netloc', citext.CIText(), nullable=False),
    sa.Column('ignore', sa.Boolean(), nullable=True),
    sa.Column('have', sa.Boolean(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seen_netloc_tracker_netloc'), 'seen_netloc_tracker', ['netloc'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_netloc_tracker_netloc'), table_name='seen_netloc_tracker')
    op.drop_table('seen_netloc_tracker')
    # ### end Alembic commands ###
