"""Add epoch column for smarter refetch tracking

Revision ID: d5dba845418b
Revises: 2d10f39bfbfd
Create Date: 2020-04-26 09:51:40.312747

"""

# revision identifiers, used by Alembic.
revision = 'd5dba845418b'
down_revision = '2d10f39bfbfd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    op.execute("SET statement_timeout TO 144000000;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_web_pages', sa.Column('epoch', sa.Integer(), nullable=True))
    op.add_column('raw_web_pages_version', sa.Column('epoch', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('web_pages', sa.Column('epoch', sa.Integer(), nullable=True))
    op.add_column('web_pages_version', sa.Column('epoch', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_pages_version', 'epoch')
    op.drop_column('web_pages', 'epoch')
    op.drop_column('raw_web_pages_version', 'epoch')
    op.drop_column('raw_web_pages', 'epoch')
    # ### end Alembic commands ###
