"""and ANOTHER enum tupe

Revision ID: 2e06d866fea8
Revises: 804a59c2c76c
Create Date: 2021-08-08 07:04:46.300947

"""

# revision identifiers, used by Alembic.
revision = '2e06d866fea8'
down_revision = '804a59c2c76c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("COMMIT")
    op.execute("ALTER TYPE dlstate_enum ADD VALUE 'single_step_deferred';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise RuntimeError("Cannot downgrade!")
    # ### end Alembic commands ###
