"""Fiddling with uniqueness

Revision ID: 8af5f324577a
Revises: bb9d84530f05
Create Date: 2016-07-03 20:14:18.951859

"""

# revision identifiers, used by Alembic.
revision = '8af5f324577a'
down_revision = 'bb9d84530f05'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nu_outbound_wrappers_client_id_client_key_seriesname_releas_key', 'nu_outbound_wrappers', type_='unique')
    op.create_unique_constraint(None, 'nu_outbound_wrappers', ['client_id', 'client_key', 'seriesname', 'releaseinfo', 'groupinfo', 'actual_target'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nu_outbound_wrappers', type_='unique')
    op.create_unique_constraint('nu_outbound_wrappers_client_id_client_key_seriesname_releas_key', 'nu_outbound_wrappers', ['client_id', 'client_key', 'seriesname', 'releaseinfo', 'groupinfo'])
    ### end Alembic commands ###
