"""empty message

Revision ID: b88c4e0d8ed4
Revises: 3d053b0c817b
Create Date: 2017-02-14 22:52:16.158800

"""

# revision identifiers, used by Alembic.
revision = 'b88c4e0d8ed4'
down_revision = '3d053b0c817b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText

from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_pages_version', 'file',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('web_pages_version', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_pages_version', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER())
    op.alter_column('web_pages_version', 'file',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    ### end Alembic commands ###
