"""empty message

Revision ID: bb9d84530f05
Revises: cb674b790e4a
Create Date: 2016-07-03 06:06:40.090459

"""

# revision identifiers, used by Alembic.
revision = 'bb9d84530f05'
down_revision = 'cb674b790e4a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types import TSVectorType
from sqlalchemy_searchable import make_searchable
import sqlalchemy_utils

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nu_outbound_wrappers', ['client_id', 'client_key', 'seriesname', 'releaseinfo', 'groupinfo'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nu_outbound_wrappers', type_='unique')
    ### end Alembic commands ###
