
# This appears to be hosted by the same people as FictionPress.
# The website sure looks to be the same codebase, in any event.


FOLLOW_GOOGLE_LINKS: False
allImages: False

type: "western"

baseUrl: [
	"https://www.fanfiction.net/",
	"http://www.fanfiction.net/",
	]

send_raw_feed: False
trigger: False

badwords: [
			"/about/",
			"/join-us/",
			"/chat/",
			'&format=pdf',
			'?format=pdf',
			'?replytocom=',
			"/forum/",
			"/forum",
			"/forums/",
			"/forums",
			"/games/",
			"/betareaders/",
			"/poetry/", # Really?

			"/post.php?",
			"/author.php?",
			]

# Content Stripping needs to be determined.
decomposeBefore: [

]

decompose: [
	{'id' : "top"},
	{'id' : "p_footer"},
	{'id' : "profile_top"},
	{'id' : "review"},
	{'class' : "zmenu"},
	{'class' : "lc-wrapper"},
]

stripTitle: []


destyle : [
	["div",  {}],
	["span", {}],
]


preserveAttrs : [
	["button", 'id'],
	["button", 'onclick'],
	["button", 'type'],
	["button", 'btn'],
	["select", ''],
]

