
import urllib.parse


def getNiceName(srcurl):
	mapper = {

		"87percenttranslation.wordpress.com"        : "87 Percent Translation",
		"aquarilasscenario.blogspot.com"            : "Aquarilas' Scenario",
		"arzengi.blogspot.com"                      : "Towards the Sky~",
		"asherahbluenotebook.wordpress.com"         : "AsherahBlue's Notebook",
		"durasama.wordpress.com"                    : "Durasama",
		"ensjtrans.wordpress.com"                   : "Ensj Translations",
		"entruce.wordpress.com"                     : "EnTruce Translations",
		"erosworkshop.blogspot.com"                 : "Eros Workshop",
		"forgetfuldreamer.wordpress.com"            : "Forgetful Dreamer",
		"fudgetranslations.wordpress.com"           : "Fudge Translations",
		"izra709.com"                               : "izra709 | B Group no Shounen Translations",
		"koongkoongtranslations.wordpress.com"      : "Koong Koong Translations",
		"magelifeblog.wordpress.com"                : "Mage Life",
		"rebirthonlineworld.com"                    : "Rebirth Online World",
		"rejecthero.wordpress.com"                  : "Reject Hero",
		"shikkakutranslations.wordpress.com"        : "Shikkaku Translations",
		"sousetsuka.blogspot.com"                   : "Sousetsuka",
		"the-last-skull.blogspot.com"               : "The Last Skull",
		"thezombieknight.blogspot.com"              : "The Zombie Knight",
		"tototr.com"                                : "Totokk\'s Translations",
		"tototrans.wordpress.com"                   : "Totokk\'s Translations",
		"translationraven.wordpress.com"            : "Translation Raven",
		"unchainedtranslation.wordpress.com"        : "Unchained Translation",
		"xhawk77x.blogspot.com"                     : "Universes With Meaning",
		"zoengsaiwaa.wordpress.com"                 : "ZSW",
		'12superlatives.wordpress.com'              : '12 Superlatives',
		'77novel.com'                               : '77 Novel',
		'9ethtranslations.wordpress.com'            : 'TheLazy9',
		'a0132.blogspot.com'                        : 'A0132',
		'addnewtab.wordpress.com'                   : 'Lost in Translation',
		'aelyiyue.wordpress.com'                    : 'Yi Yue Translation',
		'aflappyteddybird.wordpress.com'            : 'AFlappyTeddyBird',
		'ahasintsoa.wordpress.com'                  : 'Pea\'s Kingdom',
		'ahoujicha.blogspot.com'                    : 'Roasted Tea',
		'alcsel.wordpress.com'                      : 'Alcsel Translations',
		'aldnoahextrathetranslation.wordpress.com'  : '(NanoDesu) - Aldnoah Zero',
		'alyschu.wordpress.com'                     : 'Alyschu & Co',
		'amaburithetranslation.wordpress.com'       : '(NanoDesu) - Amagi Brilliant Park ',
		'anathemaserial.wordpress.com'              : 'Anathema Serial',
		'anonempireblog.wordpress.com'              : 'Anon Empire',
		'aoritranslations.wordpress.com'            : 'Aori Translations',
		'apearlyview.wordpress.com'                 : 'A Pearly View',
		'aquascans.wordpress.com'                   : 'Aqua Scans',
		'archivitysite.wordpress.com'               : 'Archivity',
		'arkmachinetranslations.com'                : 'Ark Machine Translations',
		'avertranslation.com'                       : 'Avert Translations',
		'avertranslation.org'                       : 'Avert Translations',
		'azureskytls.blogspot.com'                  : 'Azure Sky Translation',
		'azurillturtle.blogspot.com'                : '輝く世界',
		'azurro4cielo.wordpress.com'                : 'Azurro 4 Cielo',
		'bakadogeza.blogspot.com'                   : 'Baka Dogeza Translation',
		'bcat00.wordpress.com'                      : 'Bcat00 Translation',
		'bearbeartranslations.wordpress.com'        : 'Bear Bear Translations',
		'bersekertranslations.blogspot.com'         : 'Berseker Translations',
		'berserksite.wordpress.com'                 : 'BeRsErk Translations',
		'bingnovels.wordpress.com'                  : 'Binggo&Corp',
		'binhjamin.wordpress.com'                   : 'Binhjamin',
		'blazingtranslations.com'                   : 'Blazing Translations',
		'www.blazingtranslations.com'               : 'Blazing Translations',
		'bltranslation.blogspot.com'                : 'Chinese BL Translations',
		'bluesilvertranslations.wordpress.com'      : 'Blue Silver Translations',
		'bubujingxinenglish.blogspot.com'           : 'Bu Bu Jing Xin Translation',
		'bureidanworks.wordpress.com'               : 'Burei Dan Works',
		'calicoxtabby.wordpress.com'                : 'Calico x Tabby',
		'canonrap.wordpress.com'                    : 'Quality ★ Mistranslations',
		'casteliacones.wordpress.com'               : 'Cheddar!',
		'cathdeary.wordpress.com'                   : 'Romantic Dreamer\'s Sanctuary',
		'ceruleonice.wordpress.com'                 : 'Ceruleonice Translations',
		'cetranslation.blogspot.com'                : 'C.E. Light Novel Translations',
		'chineseweabootranslations.wordpress.com'   : 'Chinese Weaboo Translations',
		'choukun.wordpress.com'                     : 'ELYSION Translation',
		'circleofshards.wordpress.com'              : 'Circle of Shards',
		'circustranslations.com'                    : 'Circus Translations',
		'clickyclicktranslation.blogspot.com'       : 'Clicky Click Translation',
		'cloudmanor.wordpress.com'                  : 'Cloud Manor',
		'clover7snook.wordpress.com'                : 'Clover\'s Nook',
		'cnovelproject.blogspot.com'                : 'The C-Novel Project',
		'cnovels.bookbychapters.com'                : 'Lil\' Bliss Novels',
		'cnovels2c.wordpress.com'                   : 'C Novels 2 C',
		'cookiepastatranslations.wordpress.com'     : 'CookiePasta Translations',
		'cosmictranslation.wordpress.com'           : 'Cosmic Translation',
		'crimsonkisato.blogspot.com'                : 'Kisato\'s MLTs',
		'ctrlalcala.wordpress.com'                  : 'CtrlAlcalá',
		'd3wynightunr0lls.wordpress.com'            : 'Dewey Night Unrolls',
		'dailehtranslations.wordpress.com'          : 'NOT Daily Translations',
		'daoseekerblog.wordpress.com'               : 'Dao Seeker Blog',
		'darkfishoftherevolution.wordpress.com'     : 'A fish once said this to me',
		'darktranslations.wordpress.com'            : 'Dark Translations',
		'dawninghowls.wordpress.com'                : 'Dawning Howls',
		'defan752.wordpress.com'                    : 'Defan\'s Translations',
		'defiring.wordpress.com'                    : 'Defiring',
		'demontranslations.com'                     : 'Demon Translations',
		'descentsubs.wordpress.com'                 : 'Descent Subs',
		'distractedtranslations.wordpress.com'      : 'Distracted Translations',
		'diwasteman.wordpress.com'                  : 'Diwasteman',
		'dlingson.wordpress.com'                    : 'Lingson\'s Translations',
		'dorayakiz.wordpress.com'                   : 'Dorayakiz',
		'dreadfuldecoding.blogspot.com'             : 'Dreadful Decoding',
		'dreamavenuee.wordpress.com'                : 'Dream Avenue',
		'dreamsleeper87.blogspot.com'               : 'Lunate',
		'durandaru.wordpress.com'                   : 'Duran Daru Translation',
		'dynamislightnovel.wordpress.com'           : 'Dynamis Gaul Light Novel',
		'ecwebnovel.blogspot.com'                   : 'EC Webnovel',
		'endkun.wordpress.com'                      : 'EndKun',
		'endonline.wordpress.com'                   : 'End Online Novel',
		'ente38.wordpress.com'                      : 'Ente38 translations',
		'epyontranslations.wordpress.com'           : 'Epyon Translations',
		'etheriatranslation.wordpress.com'          : 'Etheria Translations',
		'eugene-rain.com'                           : 'Eugene Rain',
		'eyeofadventure.wordpress.com'              : 'Eye of Adventure ',
		'eztranslations.wordpress.com'              : 'EZ Translations',
		'faildoor.wordpress.com'                    : 'Emergency Exit\'s Release Blog',
		'farmerbob1.wordpress.com'                  : 'Symbiote',
		'fateapocryphathetranslation.wordpress.com' : '(NanoDesu) - Fate/Apocrypha',
		'fightingdreamersscanlations.wordpress.com' : 'Fighting Dreamers Scanlations',
		'fivestarspecialists.wordpress.com'         : 'Five Star Specialists',
		'flickerhero.wordpress.com'                 : 'Flicker Hero',
		'flowerbridgetoo.com'                       : 'Flower Bridge Too',
		'flowerbridgetoo.wordpress.com'             : 'Flower Bridge Too',
		'forgottenconqueror.wordpress.com'          : 'Forgotten Conqueror',
		'forgottenconqueror.com'                    : 'Forgotten Conqueror',
		'fromwhencecamethenamed.wordpress.com'      : 'The Named',
		'fungshen.wordpress.com'                    : 'Fung Shen',
		'fuyuugakuenthetranslation.wordpress.com'   : '(NanoDesu) - Fuyuu Gakuen no Alice and Shirley',
		'fuzionlife.wordpress.com'                  : 'Fuzion Life',
		'gargoyleserial.wordpress.com'              : 'Gargoyle Web Serial',
		'gekkahimethetranslation.wordpress.com'     : '(NanoDesu) - Gekka no Utahime to Magi no Ou',
		'gilatranslationmonster.wordpress.com'      : 'Gila Translation Monster',
		'ginironochou.wordpress.com'                : 'Silver Butterfly',
		'giraffecorps.liamak.net'                   : 'Giraffe Corps',
		'gjbuthetranslation.wordpress.com'          : '(NanoDesu) - GJ-Bu',
		'goddessgrantmeagirlfriend.wordpress.com'   : 'Goddess! Grant Me a Girlfriend!!',
		'gravitytales.com'                          : 'Gravity Tales',
		'gravitytranslations.com'                   : 'Gravity Translation',
		'grimgalthetranslation.wordpress.com'       : '(NanoDesu) - Hai to Gensou no Grimgal',
		'guhehe.net'                                : 'guhehe.TRANSLATIONS',
		'gurotranslation.blogspot.com'              : 'Guro Translation',
		'hajiko.wordpress.com'                      : 'Hajiko translation',
		'hamster428.wordpress.com'                  : 'Hamster428',
		'heartcrusadescans.wordpress.com'           : 'Heart Crusade Scans',
		'hellotranslations.wordpress.com'           : 'Hello Translations',
		'hellping.org'                              : 'Hellping',
		'hendricksensama.wordpress.com'             : 'Hendricksen-sama',
		'hennekothetranslation.wordpress.com'       : '(NanoDesu) - Hentai Ouji to Warawanai Neko',
		'henoujikun.wordpress.com'                  : 'Henouji Translation',
		'hikuosan.blogspot.com'                     : 'ヾ(。￣□￣)ﾂ',   # I can haz UTF-8 source code?
		'hokagetranslations.wordpress.com'          : 'Hokage Translations',
		'hotcocoatranslations.wordpress.com'        : 'Hot Cocoa Translations',
		'hui3r.wordpress.com'                       : 'Fanatical',
		'ichigoichiebanzai.wordpress.com'           : '一期一会, 万歳!',
		'imoutoliciouslnt.blogspot.com'             : 'Imoutolicious Light Novel Translations',
		'imperialwinters.wordpress.com'             : 'Snow & Dust',
		'infinitenoveltranslations.wordpress.com'   : 'Infinite Novel Translations',
		'infinitetranslations.wordpress.com'        : 'Infinite Translations',
		'insigniapierce.wordpress.com'              : 'Insignia Pierce',
		'isekaicyborg.wordpress.com'                : 'Isekai Soul-Cyborg Translations',
		'isekailunatic.wordpress.com'               : 'Reigokai: Isekai Translations',
		'isekaimahou.wordpress.com'                 : 'Isekai Mahou Translations!',
		'isolarium.wordpress.com'                   : 'Isolarium',
		'istlovesu.blogspot.com'                    : 'Istian\'s Workshop',
		'itranslateln.wordpress.com'                : 'itranslateln',
		'itslovetranslation.blogspot.com'           : 'Korean Novel Translations',
		'izra709.wordpress.com'                     : 'izra709 | B Group no Shounen Translations',
		'japtem.com'                                : 'Japtem',
		'jawztranslations.blogspot.com'             : 'JawzTranslations',
		'jjagaimo.wordpress.com'                    : 'Jagaimo',
		'jntranslation.wordpress.com'               : 'Solitary Translation',
		'joeglens.com'                              : 'Joeglen\'s Translation Space',
		'kaezartranslations.blogspot.com'           : 'Kaezar Translations',
		'kahoim.wordpress.com'                      : 'Kahoim Translations',
		'kakemonoko.wordpress.com'                  : 'A Place Of Legends',
		'kamitranslation.wordpress.com'             : 'Kami Translation',
		'kedelu.wordpress.com'                      : 'Kedelu',
		'kerambitnosakki.wordpress.com'             : 'Kerambit\'s Incisions',
		'kingjaahn.wordpress.com'                   : 'King Jaahn\'s Subjects',
		'kirikotranslations.wordpress.com'          : 'Kiriko Translations',
		'kirileaves.wordpress.com'                  : 'Kiri Leaves',
		'knoktranslations.wordpress.com'            : 'Knokkro Translations',
		'kntranslation.wordpress.com'               : 'KN Translation',
		'kobatochandaisuki.wordpress.com'           : 'KobatoChanDaiSukiScan',
		'koreyorihachidori.wordpress.com'           : 'Kore Yori Hachidori',
		'korezombiethetranslation.wordpress.com'    : '(NanoDesu) - Kore wa Zombie Desu ka?',
		'krytykal.org'                              : 'Krytyk\'s Translations',
		'kumaotou.wordpress.com'                    : 'Kuma Otou',
		'kurenaithetranslation.wordpress.com'       : '(NanoDesu) - Kurenai',
		'kurotsuki-novel.blogspot.com'              : 'Kurotsuki Novel',
		'kyakka.wordpress.com'                      : 'Kyakka Translations',
		'larvyde.wordpress.com'                     : 'Larvyde',
		'lasolistia.com'                            : 'HaruPARTY',
		'lastexorcist.wordpress.com'                : 'The Sphere',
		'lastvoicetranslator.wordpress.com'         : 'Lastvoice Translator',
		'layzisheep.wordpress.com'                  : 'Layzisheep',
		'lazyneet.wordpress.com'                    : 'Lazy NEET Translations',
		'legendofgalacticheroes.blogspot.com'       : 'Legend of Galactic Heroes Translation Project',
		'linkedtl.wordpress.com'                    : 'Linked Translations',
		'liveandlearn88.wordpress.com'              : 'Grow with me',
		'lizardtranslations.wordpress.com'          : 'Lizard Translations',
		'lmsmachinetranslations.com'                : 'LMS Machine Translations',
		'lnaddiction.wordpress.com'                 : 'Ln Addiction',
		'loiterous.wordpress.com'                   : 'Loiterous',
		'loliquent.wordpress.com'                   : 'Loliquent',
		'lorcromwell.wordpress.com'                 : 'LorCromwell',
		'lordofscrubs.wordpress.com'                : 'LordofScrubs',
		'loveyouthetranslation.wordpress.com'       : '(NanoDesu) - Love★You',
		'lygartranslations.wordpress.com'           : 'LygarTranslations',
		'lylisasmodeus.wordpress.com'               : 'Lylis Translations',
		'madospicy.wordpress.com'                   : 'MadoSpicy TL',
		'mahoukoukoku.blogspot.com'                 : 'Mahou Koukoku',
		'mahoutsuki.wordpress.com'                  : 'Mahoutsuki Translation',
		'makinatranslations.wordpress.com'          : 'Makina Translations',
		'manatankmagus.wordpress.com'               : 'Mana Tank Magus',
		'manga0205.wordpress.com'                   : 'Manga0205 Translations',
		'maoyuuthetranslation.wordpress.com'        : '(NanoDesu) - Maoyuu Maou Yuusha',
		'martialgodtranslator.wordpress.com'        : 'Martial God Translator',
		'mayochikithetranslation.wordpress.com'     : '(NanoDesu) - Mayo Chiki',
		'mechamushroomtranslations.wordpress.com'   : 'Mecha Mushroom Translations',
		'metalhaguremt.wordpress.com'               : '1HP',
		'miaomix539.wordpress.com'                  : 'Yet Another Translation Site',
		'midnighttranslationblog.wordpress.com'     : 'Midnight Translation Blog',
		'mnemeaa.wordpress.com'                     : 'Mnemeaa',
		'mtlcorner.blogspot.com'                    : 'Andrew9495\'s MTL corner',
		'mystiquetranslations.wordpress.com'        : 'Mystique Translations',
		'nakulas.blogspot.com'                      : '[nakulas]',
		'nanodesutranslations.wordpress.com'        : 'NanoDesu Light Novel Translations',
		'nationalneet.wordpress.com'                : 'National NEET',
		'natsutl.wordpress.com'                     : 'Natsu TL',
		'neettranslations.wordpress.com'            : 'NEET Translations',
		'netblazer.wordpress.com'                   : 'Blazing Translations',
		'nightbreezetranslations.com'               : 'Nightbreeze Translations',
		'nightofthehuntingparty.wordpress.com'      : 'When The Hunting Party Came',
		'nightraccoon.wordpress.com'                : 'Konjiki no Wordmaster',
		'nohohontranslations.wordpress.com'         : 'Nohohon Translation',
		'noitl.blogspot.com'                        : 'Translation Treasure Box',
		'noone2246.wordpress.com'                   : 'Maou na Anoko to murabito a',
		'novelsnao.com'                             : 'Novels Nao',
		'novicetranslator.wordpress.com'            : 'NoviceTranslator',
		'nowhereandnothingwebserial.wordpress.com'  : 'Nowhere & Nothing',
		'nuttyisprocrasinating.wordpress.com'       : 'Nutty is Procrastinating',
		'ohanashimi.wordpress.com'                  : 'Ohanashimi',
		'ojamajothetranslation.wordpress.com'       : '(NanoDesu) - Ojamajo Doremi',
		'oktranslation.wordpress.com'               : 'OK Translation',
		'omatranslations.com'                       : 'One Man Army Translations (OMA)',
		'omegaharem.wordpress.com'                  : 'Omega Harem',
		'omgitsaray.wordpress.com'                  : 'Omgitsaray Translations',
		'onesecondspring.blogspot.com'              : 'One Second Spring',
		'oniichanyamete.wordpress.com'              : 'お兄ちゃん、やめてぇ！',
		'orangeblossomdreams.wordpress.com'         : 'Tsukigomori',
		'oregaheroineeng.wordpress.com'             : 'Ore ga Heroine in English',
		'oregairuthetranslation.wordpress.com'      : '(NanoDesu) - Yahari Ore no Seishun Love Come wa Machigatteiru',
		'oreimothetranslation.wordpress.com'        : '(NanoDesu) - Oreimo',
		'otakunoeiyaku.blogspot.com'                : 'Ducky\'s English Translations',
		'otomerevo.wordpress.com'                   : 'Otome Revolution',
		'otterspacetranslation.wordpress.com'       : 'otterspacetranslation',
		'outspanfoster.wordpress.com'               : 'Outspan Foster',
		'pactwebserial.wordpress.com'               : 'Pact Web Serial',
		'pandafuqtranslations.wordpress.com'        : 'pandafuqtranslations',
		'pandatranslations.net'                     : 'pandafuqtranslations',
		'panofitrans.blogspot.com'                  : 'Translations From Outer Space',
		'parahumans.wordpress.com'                  : 'Worm - A Complete Web Serial',
		'paztok.wordpress.com'                      : 'Paztok',
		'peatranslation.wordpress.com'              : 'Pea Translation',
		'pikatranslations.com'                      : 'Pika Translations',
		'pikatranslations.wordpress.com'            : 'Pika Translations',
		'pippisite.wordpress.com'                   : 'Pippi Site',
		'pirateyoshi.wordpress.com'                 : 'Ziru\'s Musings | Translations~',
		'plainlybored.wordpress.com'                : 'PlainlyBored',
		'polyphonicstory.wordpress.com'             : 'Polyphonic Story Translation Group',
		'popsiclete.blogspot.com'                   : 'Popsiclete',
		'project-accelerator.net'                   : 'Project Accelerator',
		'pummels.wordpress.com'                     : 'Pummels Translations',
		'pumpkintranslations.blogspot.com'          : 'Pumpkin Translations',
		'putttytranslations.wordpress.com'          : 'putttytranslations',
		'rainbowtranslationsblog.wordpress.com'     : 'Rainbow Translations',
		'rainingstardust.wordpress.com'             : 'Weaving stories and building castles in the clouds',
		'raisingthedead.ninja'                      : 'Raising the Dead',
		'raltzero.wordpress.com'                    : 'Currently TLing [Bu ni Mi]',
		'reantoanna.wordpress.com'                  : 'ℝeanとann@',
		'rebirthonlinelightnovel.wordpress.com'     : 'Rebirth Online',
		'reddragontranslations.wordpress.com'       : 'Red Dragon Translations',
		'reddycreations.com'                        : 'Reddy Creations',
		'requirecookie.com'                         : 'Require: Cookie',
		'rhinabolla.wordpress.com'                  : 'Rhinabolla',
		'rokkathetranslation.wordpress.com'         : '(NanoDesu) - Rokka no Yuusha',
		'rosyfantasy.wordpress.com'                 : 'Rosyfantasy - Always Dreaming',
		'rumanshi.com'                              : 'Rumanshi\'s Lair',
		'rumorblock.wordpress.com'                  : 'Rumor\'s Block',
		'ruzetranslations.wordpress.com'            : 'Ruze Translations',
		'sabertranslations.wordpress.com'           : 'Saber Translations',
		'saekanothetranslation.wordpress.com'       : '(NanoDesu) - Saenai Heroine no Sodatekata',
		'sakurahonyaku.wordpress.com'               : '桜翻訳! | Light novel translations',
		'sasamisanthetranslation.wordpress.com'     : '(NanoDesu) - Sasami-San@Ganbaranai',
		'saurimania.wordpress.com'                  : 'Sauri\'s TL Blog',
		'scryatranslations.wordpress.com'           : 'Scrya Translations',
		'seizonthetranslation.wordpress.com'        : '(NanoDesu) - Seitokai no Ichizon',
		'sekaigamethetranslation.wordpress.com'     : '(NanoDesu) - Kono Sekai ga Game Dato Ore Dake ga Shitteiru',
		'setsuna86blog.wordpress.com'               : 'SETSUNA86BLOG',
		'shermatranslations.wordpress.com'          : 'Sherma Translations',
		'shincodezeroblog.wordpress.com'            : 'Code-Zero\'s Blog',
		'shinsekai.cadet-nine.org'                  : 'Shin Sekai Yori – From the New World',
		'shinsoritranslations.wordpress.com'        : 'Shinsori Translations',
		'www.shintranslations.com'                  : 'Shin Translations',
		'shintranslations.com'                      : 'Shin Translations',
		'shintranslations.wordpress.com'            : 'Shin Translations',
		'shiroyukitranslations.com'                 : 'Shiroyukineko Translations',
		'shokyuutranslations.wordpress.com'         : 'Shokyuu Translations',
		'silvalau.wordpress.com'                    : 'Silva\'s Library',
		'skythewood.blogspot.com'                   : 'Skythewood translations',
		'skyworldthetranslation.wordpress.com'      : '(NanoDesu) - Sky World',
		'slimelv1.wordpress.com'                    : 'Slime Lv1',
		'slothtranslations.wordpress.com'           : '-Sloth-',
		'snowjadeflowers.wordpress.com'             : 'A Translator\'s Ramblings',
		'soaringtranslations.com'                   : 'Soaring Translations',
		'soratranslationsblog.wordpress.com'        : 'Sora Translationsblog',
		'sotranslations.wordpress.com'              : 'Supreme Origin Translations',
		'stcon.wordpress.com'                       : 'Stellar Transformation Con.',
		'stltranslations.wordpress.com'             : 'STL Translations',
		'stoneburners.wordpress.com'                : 'Stone Burners',
		'subudai11.com'                             : 'Subudai11',
		'summiesdummyworld.wordpress.com'           : 'World of Summie',
		'sunshowerfields.wordpress.com'             : 'Sun Shower Fields',
		'superpotatotrans.wordpress.com'            : 'Super Potato Translations',
		'swordandgame.blogspot.com'                 : 'Sword and Game',
		'sylver135.wordpress.com'                   : 'Sylver Translations',
		'tabikonotrans.blogspot.com'                : 'A traveler\'s translations.',
		'taffygirl13.wordpress.com'                 : '~Taffy Translations~',
		'taulsn.wordpress.com'                      : 'Raising Angels & Defection',
		'tensaitranslations.wordpress.com'          : 'Tensai Translations',
		'terminustranslations.wordpress.com'        : 'Terminus Translation',
		'thatguywhosthere.wordpress.com'            : 'ThatGuyOverThere',
		'the4everreader.wordpress.com'              : 'L2M',
		'theadamantinedragon.wordpress.com'         : 'Adamantine Dragon in the Crystal World',
		'thecatscans.wordpress.com'                 : 'Cat Scans',
		'thedefend.wordpress.com'                   : 'TheDefend Translations',
		'thelordofpie.blogspot.com'                 : 'Pielord Translations',
		'themustangtranslator.wordpress.com'        : 'The Mustang Translator',
		'thenakedsol.blogspot.com'                  : 'Iterations within a Thought-Eclipse',
		'theworsttranslation.wordpress.com'         : 'Bad Translation',
		'thundertranslations.com'                   : 'Thunder Translation',
		'thundertranslations.wordpress.com'         : 'Thunder Translation',
		'thyaeriatranslations.com'                  : 'Thyaeria Translations',
		'tieshaunn.wordpress.com'                   : 'Tieshaunn',
		'tmbrakta.wordpress.com'                    : 'All\'s Fair In Love & War',
		'tofubyu.wordpress.com'                     : 'Tofubyu',
		'tomorolls.wordpress.com'                   : 'Tomorolls',
		'tony-yon-ka.blogspot.com'                  : 'Tony Yon Ka',
		'tony-yon-ka.blogspot.com.au'               : 'Tony Yon Ka',
		'totallyinsanetranlation.com'               : 'Totally Insane Tranlation',
		'totobro.com'                               : 'Totokk\'s Translations',
		'tototrans.com'                             : 'Totokk\'s Translations',
		'translatedbyaclown.wordpress.com'          : 'Translated by a Clown',
		'trippingoverwn.wordpress.com'              : 'Tripp Translations',
		'trolllancer.com'                           : '[G.O] Chronicles',
		'trungtnguyen123.wordpress.com'             : 'Trungt Nguyen 123',
		'tsaltranslation.wordpress.com'             : 'Light Novel translations',
		'tsuigeki.wordpress.com'                    : 'Tsuigeki Translations',
		'tu-shu-guan.blogspot.com'                  : '中翻英圖書館 Translations',
		'tumbleintofantasy.wordpress.com'           : 'Tumble Into Fantasy',
		'turb0translation.blogspot.com'             : 'Turb0 Translation',
		'tusjecht.wordpress.com'                    : 'Tus-Trans',
		'twistedcogs.wordpress.com'                 : 'Twisted Cogs',
		'typemoondb.wordpress.com'                  : 'CapsUsingShift Tl',
		'udonatewetranslate.blogspot.com'           : 'U Donate We Translate',
		'ultimatearcane.wordpress.com'              : 'Ultimate Arcane',
		'unbreakablemachinedoll.wordpress.com'      : 'Unbreakable Machine Doll',
		'undecentlnt.wordpress.com'                 : 'Undecent Translations',
		'unlimitednovelfailures.mangamatters.com'   : 'Unlimited Novel Failures',
		'unlimitedstoryworks.wordpress.com'         : 'Unlimited Story Works',
		'untuned-strings.blogspot.com'              : 'Untuned Translation Blog',
		'uselessno4.wordpress.com'                  : 'Useless no 4',
		'villagetranslations.wordpress.com'         : 'Village Translations',
		'voidtranslations.wordpress.com'            : 'Void Translations',
		'walkthejianghu.com'                        : 'Walk the Jiang Hu',
		'wartdf.wordpress.com'                      : 'Raising the Dead',
		'watermelonhelmets.wordpress.com'           : 'Watermelon Helmets',
		'wcctranslation.wordpress.com'              : 'WCC Translation',
		'webnoveltranslations.blogspot.com'         : 'Neo Translations',
		'webnoveltranslations.blogspot.se'          : 'Neo Translations',
		'weletranslation.wordpress.com'             : 'Wele Translation',
		'whitetigertranslations.wordpress.com'      : 'White Tiger Translations',
		'wishuponahope.blogspot.com'                : 'Wish Upon A Hope',
		'wolfietranslation.wordpress.com'           : 'Wolfie Translation',
		'wordofcraft.wordpress.com'                 : 'Word of Craft',
		'worldofwatermelons.com'                    : 'World of Watermelons',
		'wuxiaheroes.com'                           : 'Wuxia Heroes',
		'wuxiasociety.com'                          : 'WuxiaSociety',
		'wuxiwish.wordpress.com'                    : 'Wuxiwish',
		'www.deadlylegends.com'                     : 'Deadly Forgotten Legends',
		'www.lingson.com'                           : 'Lingson\'s Translations',
		'www.lonahora.com'                          : 'Lonahora',
		'www.paultwister.com'                       : 'The Tales of Paul Twister',
		'www.princerevolution.org'                  : 'Prince Revolution!',
		'www.radianttranslations.com'               : 'Radiant Translations',
		'www.risingdragonstranslation.com'          : 'Rising Dragons Translation',
		'www.sousetsuka.com'                        : 'Sousetsuka',
		'www.talesofmu.com'                         : 'Tales of MU',
		'www.taptaptaptaptap.net'                   : 'tap-trans » tappity tappity tap.',
		'www.translationnations.com'                : 'Translation Nations',
		'www.whimsicalland.com'                     : 'Whimsical Land',
		'www.wuxiatranslations.com'                 : 'Wuxia Translations',
		'www.wuxiaworld.com'                        : 'Wuxiaworld',
		'wwyxhqc.wordpress.com'                     : 'Dreams of Jianghu',
		'xantandminions.wordpress.com'              : 'Xant & Minions',
		'xcrossj.blogspot.com'                      : 'XCrossJ',
		'xcrossj.wordpress.com'                     : 'XCrossJ',
		'yoraikun.wordpress.com'                    : 'Yoraikun Translation',
		'youjinsite.com'                            : 'Youjinsite Translations',
		'youshokutranslations.wordpress.com'        : 'Youshoku Translations',
		'youtsubasilver.wordpress.com'              : 'youtsubasilver\'s Blog',
		'yukkuri-literature-service.blogspot.com'   : 'Yukkuri Free Time Literature Service',
		'zentranslations.wordpress.com'             : 'Zen Translations',
		'zmunjali.wordpress.com'                    : 'Roxism HQ',

		'yellawtwl.com'                             : 'Wuxiaworld',
		'yellawlaw.wordpress.com'                   : 'Wuxiaworld',


		'beehugger.wordpress.com'                   : 'Beehugger',
		'rancerqz.wordpress.com'                    : 'RANCER',
		'moonbunnycafe.com'                         : 'Moon Bunny Cafe',

		"feedproxy.google.com"                      : "FeedProxy",

		"dragomircm.com"                            : "DragomirCM",
		'dragomircm.wordpress.com'                  : "DragomirCM",
		"mike777ac.wordpress.com"                   : "Mike777ac",


		'erolns.blogspot.com'                       : 'Ero Light Novel Translations',
		'machineslicedbread.wordpress.com'          : 'Machine Sliced Bread',
		'holdxandclick.wordpress.com'               : 'Hold \'X\' and Click',
		'watdameow.wordpress.com'                   : 'Wat Da Meow',


		'cavescans.com'                             : 'cavescans.com',

		# Wat
		# 'booksmoviesandbeyond.blogspot.com'         : 'booksmoviesandbeyond.blogspot.com',
		# 'xxjohnsmithxx.wordpress.com'               : 'Huh',


		# OEL bits and bobs:
		# "xantbos.wordpress.com"                     : "wat",

		# Invitation only.
		# "hereticlnt.blogspot.com"                   : "hereticlnt.blogspot.com",

		# Removed:
		# "solitarytranslation.wordpress.com"         : "wat",

		# Porn? How did that get in here?
		# "teamkoinaka.wordpress.com"                 : "wat",

		# Accidental manga blog:
		# "thecatscans.wordpress.com"                 : "wat",
	}

	srcnetloc = urllib.parse.urlparse(srcurl).netloc

	if srcnetloc in mapper:
		return mapper[srcnetloc]

	# print("Unknown netloc?", srcnetloc)
	# print("Src url?", srcurl)
	return False
