
import urllib.parse

mapper = {

	# Wordpress
	"87percenttranslation.wordpress.com"              : "87 Percent Translation",
	"asherahbluenotebook.wordpress.com"               : "AsherahBlue's Notebook",
	"durasama.wordpress.com"                          : "Durasama",
	"ensjtrans.wordpress.com"                         : "Ensj Translations",
	"entruce.wordpress.com"                           : "EnTruce Translations",
	"forgetfuldreamer.wordpress.com"                  : "Forgetful Dreamer",
	"fudgetranslations.wordpress.com"                 : "Fudge Translations",
	"koongkoongtranslations.wordpress.com"            : "Koong Koong Translations",
	"magelifeblog.wordpress.com"                      : "Mage Life",
	"mike777ac.wordpress.com"                         : "Mike777ac",
	"mike777ac.com"                                   : "Mike777ac",
	"rejecthero.wordpress.com"                        : "Reject Hero",
	"shikkakutranslations.wordpress.com"              : "Shikkaku Translations",
	"shikkakutranslations.com"                        : "Shikkaku Translations",
	"tototrans.wordpress.com"                         : "Totokk\'s Translations",
	"translationraven.wordpress.com"                  : "Translation Raven",
	"unchainedtranslation.wordpress.com"              : "Unchained Translation",
	"zoengsaiwaa.wordpress.com"                       : "ZSW",
	'12superlatives.wordpress.com'                    : '12 Superlatives',
	'9ethtranslations.wordpress.com'                  : 'TheLazy9',
	'addnewtab.wordpress.com'                         : 'Lost in Translation',
	'aelyiyue.wordpress.com'                          : 'Yi Yue Translation',
	'aflappyteddybird.wordpress.com'                  : 'AFlappyTeddyBird',
	'agreyworld.wordpress.com'                        : 'A Grey World',
	'ahasintsoa.wordpress.com'                        : 'Pea\'s Kingdom',
	'alcsel.wordpress.com'                            : 'Alcsel Translations',
	'aldnoahextrathetranslation.wordpress.com'        : '(NanoDesu) - Aldnoah Zero',
	'alicetranslations.wordpress.com'                 : 'Alice Translations',
	'alyschu.wordpress.com'                           : 'Alyschu & Co',
	'amaburithetranslation.wordpress.com'             : '(NanoDesu) - Amagi Brilliant Park ',
	'amber99y.wordpress.com'                          : 'C-Novel Tranlations…',
	'anathemaserial.wordpress.com'                    : 'Anathema Serial',
	'anonempireblog.wordpress.com'                    : 'Anon Empire',
	'aoritranslations.wordpress.com'                  : 'Aori Translations',
	'apearlyview.wordpress.com'                       : 'A Pearly View',
	'aquascans.wordpress.com'                         : 'Aqua Scans',
	'archivitysite.wordpress.com'                     : 'Archivity',
	'asiancult.wordpress.com'                         : 'The Asian Cult',
	'asiandramalife.wordpress.com'                    : 'Xiaowen206\'s Blog',
	'asylumtranslations.wordpress.com'                : 'Asylum Translations',
	'atentranslationswordpresscom.wordpress.com'      : 'Aten Translations',
	'azurro4cielo.wordpress.com'                      : 'Azurro 4 Cielo',
	'bakapervert.wordpress.com'                       : 'Baka Pervert',
	'bcat00.wordpress.com'                            : 'Bcat00 Translation',
	'bearbeartranslations.wordpress.com'              : 'Bear Bear Translations',
	'beehugger.wordpress.com'                         : 'Beehugger',
	'berserksite.wordpress.com'                       : 'BeRsErk Translations',
	'bingnovels.wordpress.com'                        : 'Binggo&Corp',
	'binhjamin.wordpress.com'                         : 'Binhjamin',
	'bluesilvertranslations.wordpress.com'            : 'Blue Silver Translations',
	'bureidanworks.wordpress.com'                     : 'Burei Dan Works',
	'calicoxtabby.wordpress.com'                      : 'Calico x Tabby',
	'canonrap.wordpress.com'                          : 'Quality ★ Mistranslations',
	'casprojectsite.wordpress.com'                    : 'Cas Project Site',
	'casteliacones.wordpress.com'                     : 'Cheddar!',
	'cathdeary.wordpress.com'                         : 'Romantic Dreamer\'s Sanctuary',
	'catinghampalace.wordpress.com'                   : 'Nekoyashiki',
	'ceruleonice.wordpress.com'                       : 'Ceruleonice Translations',
	'chineseweabootranslations.wordpress.com'         : 'Chinese Weaboo Translations',
	'choukun.wordpress.com'                           : 'ELYSION Translation',
	'chubbycheeksthoughts.wordpress.com'              : 'ChubbyCheeks',
	'chubbycheeksthoughts.com'                        : 'ChubbyCheeks',
	'circleofshards.wordpress.com'                    : 'Circle of Shards',
	'cloudmanor.wordpress.com'                        : 'Cloud Manor',
	'clover7snook.wordpress.com'                      : 'Clover\'s Nook',
	'cnovels2c.wordpress.com'                         : 'C Novels 2 C',
	'cookiepastatranslations.wordpress.com'           : 'CookiePasta',
	'cosmictranslation.wordpress.com'                 : 'Cosmic Translation',
	'crackofdawntranslations.wordpress.com'           : 'Crack of Dawn Translations',
	'crystalraindescends.wordpress.com'               : 'CrystalRainDescends',
	'ctrlalcala.wordpress.com'                        : 'CtrlAlcalá',
	'd3wynightunr0lls.wordpress.com'                  : 'Dewey Night Unrolls',
	'dailehtranslations.wordpress.com'                : 'NOT Daily Translations',
	'daoseekerblog.wordpress.com'                     : 'Dao Seeker Blog',
	'darkfishoftherevolution.wordpress.com'           : 'A fish once said this to me',
	'darktranslations.wordpress.com'                  : 'Dark Translations',
	'dawninghowls.wordpress.com'                      : 'Dawning Howls',
	'defan752.wordpress.com'                          : 'Defan\'s Translations',
	'defiring.wordpress.com'                          : 'Defiring',
	'demontranslations.wordpress.com'                 : 'Demon Translations',
	'descentsubs.wordpress.com'                       : 'Descent Subs',
	'distractedchinese.wordpress.com'                 : 'Distracted Chinese',
	'distractedtranslations.wordpress.com'            : 'Distracted Translations',
	'diwasteman.wordpress.com'                        : 'Diwasteman',
	'dlingson.wordpress.com'                          : 'Lingson\'s Translations',
	'dorayakiz.wordpress.com'                         : 'Dorayakiz',
	'dragomircm.wordpress.com'                        : "DragomirCM",
	'dramasbooksandtea.wordpress.com'                 : 'Dramas, Books & Tea',
	'dreamavenuee.wordpress.com'                      : 'Dream Avenue',
	'durandaru.wordpress.com'                         : 'Duran Daru Translation',
	'dynamislightnovel.wordpress.com'                 : 'Dynamis Gaul Light Novel',
	'ellionoratranslation.wordpress.com'              : 'Ellionora Translation',
	'endkun.wordpress.com'                            : 'EndKun',
	'endonline.wordpress.com'                         : 'End Online Novel',
	'ente38.wordpress.com'                            : 'Ente38 translations',
	'epyontranslations.wordpress.com'                 : 'Epyon Translations',
	'etheriatranslation.wordpress.com'                : 'Etheria Translations',
	'eyeofadventure.wordpress.com'                    : 'Eye of Adventure ',
	'eztranslations.wordpress.com'                    : 'EZ Translations',
	'faildoor.wordpress.com'                          : 'Emergency Exit\'s Release Blog',
	'farmerbob1.wordpress.com'                        : 'Symbiote',
	'fateapocryphathetranslation.wordpress.com'       : '(NanoDesu) - Fate/Apocrypha',
	'fightingdreamersscanlations.wordpress.com'       : 'Fighting Dreamers Scanlations',
	'firebirdsnest.wordpress.com'                     : 'Firebird\'s Nest',
	'firebirdsnest.org'                               : 'Firebird\'s Nest',
	'fivestarspecialists.wordpress.com'               : 'Five Star Specialists',
	'flickerhero.wordpress.com'                       : 'Flicker Hero',
	'flowerbridgetoo.wordpress.com'                   : 'Flower Bridge Too',
	'forgottenconqueror.wordpress.com'                : 'Forgotten Conqueror',
	'fromwhencecamethenamed.wordpress.com'            : 'The Named',
	'frostfire10.wordpress.com'                       : 'Frostfire 10',
	'fungshen.wordpress.com'                          : 'Fung Shen',
	'fuyuugakuenthetranslation.wordpress.com'         : '(NanoDesu) - Fuyuu Gakuen no Alice and Shirley',
	'fuzionlife.wordpress.com'                        : 'Fuzion Life',
	'gargoyleserial.wordpress.com'                    : 'Gargoyle Web Serial',
	'gekkahimethetranslation.wordpress.com'           : '(NanoDesu) - Gekka no Utahime to Magi no Ou',
	'gilatranslationmonster.wordpress.com'            : 'Gila Translation Monster',
	'ginironochou.wordpress.com'                      : 'Silver Butterfly',
	'gjbuthetranslation.wordpress.com'                : '(NanoDesu) - GJ-Bu',
	'goddessgrantmeagirlfriend.wordpress.com'         : 'Goddess! Grant Me a Girlfriend!!',
	'gravitytranslations.wordpress.com'               : 'Gravity Tales',
	'grimgalthetranslation.wordpress.com'             : '(NanoDesu) - Hai to Gensou no Grimgal',
	'hajiko.wordpress.com'                            : 'Hajiko translation',
	'hamster428.wordpress.com'                        : 'Hamster428',
	'hanagiku.wordpress.com'                          : 'My Purple World',
	'heartcrusadescans.wordpress.com'                 : 'Heart Crusade Scans',
	'heavenlystartranslations.wordpress.com'          : 'Heavenly Star Translations',
	'hellotranslations.wordpress.com'                 : 'Hello Translations',
	'hendricksensama.wordpress.com'                   : 'Hendricksen-sama',
	'hennekothetranslation.wordpress.com'             : '(NanoDesu) - Hentai Ouji to Warawanai Neko',
	'henoujikun.wordpress.com'                        : 'Henouji Translation',
	'hokagetranslations.wordpress.com'                : 'Hokage Translations',
	'holdxandclick.wordpress.com'                     : 'Hold \'X\' and Click',
	'hotcocoatranslations.wordpress.com'              : 'Hot Cocoa Translations',
	'hui3r.wordpress.com'                             : 'Fanatical',
	'ichigoichiebanzai.wordpress.com'                 : '一期一会, 万歳!',
	'imperialwinters.wordpress.com'                   : 'Snow & Dust',
	'infinitenoveltranslations.wordpress.com'         : 'Infinite Novel Translations',
	'infinitetranslations.wordpress.com'              : 'Infinite Translations',
	'insigniapierce.wordpress.com'                    : 'Insignia Pierce',
	'intensedessugar.wordpress.com'                   : 'IntenseDesSugar',
	'intensedessugar.com'                             : 'IntenseDesSugar',
	'isekaicyborg.wordpress.com'                      : 'Isekai Soul-Cyborg Translations',
	'isekailunatic.wordpress.com'                     : 'Reigokai: Isekai Translations',
	'isekaimahou.wordpress.com'                       : 'Isekai Mahou Translations!',
	'isolarium.wordpress.com'                         : 'Isolarium',
	'itranslateln.wordpress.com'                      : 'itranslateln',
	'izra709.wordpress.com'                           : 'izra709 | B Group no Shounen Translations',
	'jammerg55.wordpress.com'                         : '「　」',
	'jerutz.wordpress.com'                            : 'JeruTz\'s Blog',
	'jjagaimo.wordpress.com'                          : 'Jagaimo',
	'jntranslation.wordpress.com'                     : 'Solitary Translation',
	'joeglens.wordpress.com'                          : 'Joeglens\' Translation Space',
	'jtranslashions.wordpress.com'                    : 'Web Novel Japanese Translation',
	'kahoim.wordpress.com'                            : 'Kahoim Translations',
	'kakemonoko.wordpress.com'                        : 'A Place Of Legends',
	'kamitranslation.wordpress.com'                   : 'Kami Translation',
	'kedelu.wordpress.com'                            : 'Kedelu',
	'kerambitnosakki.wordpress.com'                   : 'Kerambit\'s Incisions',
	'kingjaahn.wordpress.com'                         : 'King Jaahn\'s Subjects',
	'kirikotranslations.wordpress.com'                : 'Kiriko Translations',
	'kirileaves.wordpress.com'                        : 'Kiri Leaves',
	'knoktranslations.wordpress.com'                  : 'Knokkro Translations',
	'kntranslation.wordpress.com'                     : 'KN Translation',
	'kobatochandaisuki.wordpress.com'                 : 'KobatoChanDaiSukiScan',
	'kongetsume.wordpress.com'                        : '天才創造すなわち百合',
	'konobuta.wordpress.com'                          : 'Konobuta',
	'koreyorihachidori.wordpress.com'                 : 'Kore Yori Hachidori',
	'korezombiethetranslation.wordpress.com'          : '(NanoDesu) - Kore wa Zombie Desu ka?',
	'kumaotou.wordpress.com'                          : 'Kuma Otou',
	'kurenaithetranslation.wordpress.com'             : '(NanoDesu) - Kurenai',
	'kurotranslations.wordpress.com'                  : 'Kuro Translations',
	'kyakka.wordpress.com'                            : 'Kyakka Translations',
	'lagnos.wordpress.com'                            : 'lagnos.wordpress.com',
	'larvyde.wordpress.com'                           : 'Larvyde',
	'lasciviousimouto.wordpress.com'                  : 'Lascivious Imouto',
	'lasciviousimouto.net'                            : 'Lascivious Imouto',
	'lastexorcist.wordpress.com'                      : 'The Sphere',
	'lastvoicetranslator.wordpress.com'               : 'Lastvoice Translator',
	'layzisheep.wordpress.com'                        : 'Layzisheep',
	'lazyneet.wordpress.com'                          : 'Lazy NEET Translations',
	'linkedtl.wordpress.com'                          : 'Linked Translations',
	'liveandlearn88.wordpress.com'                    : 'Grow with me',
	'lizardtranslations.wordpress.com'                : 'Lizard Translations',
	'lnaddiction.wordpress.com'                       : 'Ln Addiction',
	'loiterous.wordpress.com'                         : 'Loiterous',
	'loliquent.wordpress.com'                         : 'Loliquent',
	'lorcromwell.wordpress.com'                       : 'LorCromwell',
	'lordofscrubs.wordpress.com'                      : 'LordofScrubs',
	'loveyouthetranslation.wordpress.com'             : '(NanoDesu) - Love★You',
	'lsdell.com'                                      : 'Taint',
	'luentranslations.wordpress.com'                  : 'Luen Translations',
	'lunaris111.wordpress.com'                        : 'Lunaris',
	'lygartranslations.wordpress.com'                 : 'LygarTranslations',
	'lylisasmodeus.wordpress.com'                     : 'Lylis Translations',
	'machineslicedbread.wordpress.com'                : 'Machine Sliced Bread',
	'www.machineslicedbread.xyz'                      : 'Machine Sliced Bread',
	'madospicy.wordpress.com'                         : 'MadoSpicy TL',
	'mahoutsuki.wordpress.com'                        : 'Mahoutsuki Translation',
	'makinatranslations.wordpress.com'                : 'Makina Translations',
	'manatankmagus.wordpress.com'                     : 'Mana Tank Magus',
	'manga0205.wordpress.com'                         : 'Manga0205 Translations',
	'maoyuuthetranslation.wordpress.com'              : '(NanoDesu) - Maoyuu Maou Yuusha',
	'martialgodtranslator.wordpress.com'              : 'Martial God Translator',
	'mayochikithetranslation.wordpress.com'           : '(NanoDesu) - Mayo Chiki',
	'mechamushroomtranslations.wordpress.com'         : 'Mecha Mushroom Translations',
	'megacarp.wordpress.com'                          : 'Blublub',
	'metalhaguremt.wordpress.com'                     : '1HP',
	'miaomix539.wordpress.com'                        : 'Yet Another Translation Site',
	'midnighttranslationblog.wordpress.com'           : 'Midnight Translation Blog',
	'mnemeaa.wordpress.com'                           : 'Mnemeaa',
	'monktranslation.wordpress.com'                   : 'Monk Translation',
	'morrighansucks.wordpress.com'                    : 'Morrighan Sucks',
	'mystiquetranslations.wordpress.com'              : 'Mystique Translations',
	'mythicalpagoda.wordpress.com'                    : 'Mythical Pagoda',
	'n00btranslations.wordpress.com'                  : 'N00b Translations',
	'nanjamora.wordpress.com'                         : 'Nanjamora',
	'nanodesutranslations.wordpress.com'              : 'NanoDesu Light Novel Translations',
	'nationalneet.wordpress.com'                      : 'National NEET',
	'natsutl.wordpress.com'                           : 'Natsu TL',
	'neettranslations.wordpress.com'                  : 'NEET Translations',
	'netblazer.wordpress.com'                         : 'Blazing Translations',
	'nightofthehuntingparty.wordpress.com'            : 'When The Hunting Party Came',
	'nightraccoon.wordpress.com'                      : 'Konjiki no Wordmaster',
	'nohohontranslations.wordpress.com'               : 'Nohohon Translation',
	'noone2246.wordpress.com'                         : 'Maou na Anoko to murabito a',
	'novelaffairs.wordpress.com'                      : 'Novel Affairs',
	'noveltrans.wordpress.com'                        : 'Novel Trans',
	'novicetranslator.wordpress.com'                  : 'NoviceTranslator',
	'nowhereandnothingwebserial.wordpress.com'        : 'Nowhere & Nothing',
	'nuttyisprocrasinating.wordpress.com'             : 'Nutty is Procrastinating',
	'ohanashimi.wordpress.com'                        : 'Ohanashimi',
	'ojamajothetranslation.wordpress.com'             : '(NanoDesu) - Ojamajo Doremi',
	'oktranslation.wordpress.com'                     : 'OK Translation',
	'omatranslations.wordpress.com'                   : 'One Man Army Translations',
	'omegaharem.wordpress.com'                        : 'Omega Harem',
	'omgitsaray.wordpress.com'                        : 'Omgitsaray Translations',
	'oniichanyamete.wordpress.com'                    : 'お兄ちゃん、やめてぇ！',
	'orangeblossomdreams.wordpress.com'               : 'Tsukigomori',
	'oregaheroineeng.wordpress.com'                   : 'Ore ga Heroine in English',
	'oregairuthetranslation.wordpress.com'            : '(NanoDesu) - Yahari Ore no Seishun Love Come wa Machigatteiru',
	'oreimothetranslation.wordpress.com'              : '(NanoDesu) - Oreimo',
	'originnovels.wordpress.com'                      : 'Origin Novels',
	'otomerevo.wordpress.com'                         : 'Otome Revolution',
	'otterspacetranslation.wordpress.com'             : 'otterspacetranslation',
	'outspanfoster.wordpress.com'                     : 'Outspan Foster',
	'pactwebserial.wordpress.com'                     : 'Pact Web Serial',
	'pandafuqtranslations.wordpress.com'              : 'pandafuqtranslations',
	'parahumans.wordpress.com'                        : 'Worm - A Complete Web Serial',
	'patriarchreliance.wordpress.com'                 : 'Patriarch Reliance',
	'paztok.wordpress.com'                            : 'Paztok',
	'peatranslation.wordpress.com'                    : 'Pea Translation',
	'pikatranslations.wordpress.com'                  : 'Pika Translations',
	'pippisite.wordpress.com'                         : 'Pippi Site',
	'pirateyoshi.wordpress.com'                       : 'Ziru\'s Musings | Translations~',
	'zirusmusings.com'                                : 'Ziru\'s Musings | Translations~',
	'pizzasandcoke.wordpress.com'                     : 'Madao Translations',
	'plainlybored.wordpress.com'                      : 'PlainlyBored',
	'polyphonicstory.wordpress.com'                   : 'Polyphonic Story Translation Group',
	'priddles.wordpress.com'                          : 'Priddles Translations',
	'pummels.wordpress.com'                           : 'Pummels Translations',
	'putttytranslations.wordpress.com'                : 'putttytranslations',
	'qualideascumthetranslation.wordpress.com'        : 'Qualidea of Scum and a Gold Coin',
	'qualiteatranslations.wordpress.com'              : 'QualiTeaTranslations',
	'rainbowtranslationsblog.wordpress.com'           : 'Rainbow Translations',
	'rainingstardust.wordpress.com'                   : 'Weaving stories and building castles in the clouds',
	'raltzero.wordpress.com'                          : 'Currently TLing [Bu ni Mi]',
	'rancerqz.wordpress.com'                          : 'RANCER',
	'reantoanna.wordpress.com'                        : 'ℝeanとann@',
	'rebirthonlinelightnovel.wordpress.com'           : 'Rebirth Online',
	'reddragontranslations.wordpress.com'             : 'Red Dragon Translations',
	'rhinabolla.wordpress.com'                        : 'Rhinabolla',
	'risingdragons.wordpress.com'                     : 'Rising Dragons Translation',
	'rokkathetranslation.wordpress.com'               : '(NanoDesu) - Rokka no Yuusha',
	'rosyfantasy.wordpress.com'                       : 'Rosyfantasy - Always Dreaming',
	'rosyfantasy.net'                                 : 'Rosyfantasy - Always Dreaming',
	'rumorblock.wordpress.com'                        : 'Rumor\'s Block',
	'ruzetranslations.wordpress.com'                  : 'Ruze Translations',
	'sabertranslations.wordpress.com'                 : 'Saber Translations',
	'saekanothetranslation.wordpress.com'             : '(NanoDesu) - Saenai Heroine no Sodatekata',
	'saibaichiroku.wordpress.com'                     : 'Nooblate',
	'sakurahonyaku.wordpress.com'                     : '桜翻訳! | Light novel translations',
	'sasamisanthetranslation.wordpress.com'           : '(NanoDesu) - Sasami-San@Ganbaranai',
	'saurimania.wordpress.com'                        : 'Sauri\'s TL Blog',
	'scryatranslations.wordpress.com'                 : 'Scrya Translations',
	'seizonthetranslation.wordpress.com'              : '(NanoDesu) - Seitokai no Ichizon',
	'sekaigamethetranslation.wordpress.com'           : '(NanoDesu) - Kono Sekai ga Game Dato Ore Dake ga Shitteiru',
	'selkinnovel.wordpress.com'                       : 'Selkin Novel',
	'selkinnovel.com'                                 : 'Selkin Novel',
	'setsuna86blog.wordpress.com'                     : 'SETSUNA86BLOG',
	'shermatranslations.wordpress.com'                : 'Sherma Translations',
	'shincodezeroblog.wordpress.com'                  : 'Code-Zero\'s Blog',
	'shinsoritranslations.wordpress.com'              : 'Shinsori Translations',
	'shintranslations.wordpress.com'                  : 'Shin Translations',
	'shinynewjustice.wordpress.com'                   : 'Sins of the Fathers',
	'shokyuutranslations.wordpress.com'               : 'Shokyuu Translations',
	'silenttl.wordpress.com'                          : 'Silent Tl',
	'silvalau.wordpress.com'                          : 'Silva\'s Library',
	'skyworldthetranslation.wordpress.com'            : '(NanoDesu) - Sky World',
	'slimelv1.wordpress.com'                          : 'Slime Lv1',
	'slothtranslations.wordpress.com'                 : '-Sloth-',
	'snowjadeflowers.wordpress.com'                   : 'A Translator\'s Ramblings',
	'soaringtranslations.wordpress.com'               : 'Soaring Translations',
	'solitarytranslation.wordpress.com'               : 'Solitary Translation',
	'soojiki.wordpress.com'                           : 'Soojiki\'s Project',
	'soratranslationsblog.wordpress.com'              : 'Sora Translations',
	'sorotrans.wordpress.com'                         : 'sorotrans.wordpress.com',
	'sotranslations.wordpress.com'                    : 'Supreme Origin Translations',
	'stcon.wordpress.com'                             : 'Stellar Transformation Con.',
	'stltranslations.wordpress.com'                   : 'STL Translations',
	'stoneburners.wordpress.com'                      : 'Stone Burners',
	'summiesdummyworld.wordpress.com'                 : 'World of Summie',
	'sunshowerfields.wordpress.com'                   : 'Sun Shower Fields',
	'superpotatotrans.wordpress.com'                  : 'Super Potato Translations',
	'sut3kii.wordpress.com'                           : 'Suteki Da Ne',
	'sylver135.wordpress.com'                         : 'Sylver Translations',
	'taffygirl13.wordpress.com'                       : '~Taffy Translations~',
	'taulsn.wordpress.com'                            : 'Raising Angels & Defection',
	'tensaitranslations.wordpress.com'                : 'Tensai Translations',
	'terminustranslations.wordpress.com'              : 'Terminus Translation',
	'thatguywhosthere.wordpress.com'                  : 'ThatGuyOverThere',
	'the4everreader.wordpress.com'                    : 'L2M',
	'theadamantinedragon.wordpress.com'               : 'Adamantine Dragon in the Crystal World',
	'thecatscans.wordpress.com'                       : 'Cat Scans',
	'thedefend.wordpress.com'                         : 'TheDefend Translations',
	'themustangtranslator.wordpress.com'              : 'The Mustang Translator',
	'theworsttranslation.wordpress.com'               : 'Bad Translation',
	'thundertranslations.wordpress.com'               : 'Thunder Translation',
	'tieshaunn.wordpress.com'                         : 'Tieshaunn',
	'tmbrakta.wordpress.com'                          : 'All\'s Fair In Love & War',
	'tofubyu.wordpress.com'                           : 'Tofubyu',
	'tomorolls.wordpress.com'                         : 'Tomorolls',
	'translatedbyaclown.wordpress.com'                : 'Translated by a Clown',
	'trippingoverwn.wordpress.com'                    : 'Tripp Translations',
	'trueidentitynovel.wordpress.com'                 : 'Origin Novels',
	'trungtnguyen123.wordpress.com'                   : 'Trungt Nguyen 123',
	'trungtnguyen123.org'                             : 'Trungt Nguyen 123',
	'tsaltranslation.wordpress.com'                   : 'Light Novel translations',
	'tsuigeki.wordpress.com'                          : 'Tsuigeki Translations',
	'tthcs.wordpress.com'                             : 'Ten Thousand Heaven Controlling Sword',
	'tumbleintofantasy.wordpress.com'                 : 'Tumble Into Fantasy',
	'tusjecht.wordpress.com'                          : 'Tus-Trans',
	'twistedcogs.wordpress.com'                       : 'Twisted Cogs',
	'typemoondb.wordpress.com'                        : 'CapsUsingShift Tl',
	'ultimatearcane.wordpress.com'                    : 'Ultimate Arcane',
	'unbreakablemachinedoll.wordpress.com'            : 'Unbreakable Machine Doll',
	'undecentlnt.wordpress.com'                       : 'Undecent Translations',
	'unlimitedstoryworks.wordpress.com'               : 'Unlimited Story Works',
	'uselessno4.wordpress.com'                        : 'Useless no 4',
	'vaancruze.wordpress.com'                         : 'VaanCruze',
	'vaancruze.com'                                   : 'VaanCruze',
	'verathragna.wordpress.com'                       : 'Verathragana Stories',
	'verathragna.com'                                 : 'Verathragana Stories',
	'villagetranslations.wordpress.com'               : 'Village Translations',
	'voidtranslations.wordpress.com'                  : 'Void Translations',
	'walkingthestorm.wordpress.com'                   : 'Walking the Storm',
	'walkthejianghu.wordpress.com'                    : 'Walk the Jiang Hu',
	'wartdf.wordpress.com'                            : 'Raising the Dead',
	'watdameow.wordpress.com'                         : 'Wat Da Meow',
	'watermelonhelmets.wordpress.com'                 : 'Watermelon Helmets',
	'wcctranslation.wordpress.com'                    : 'WCC Translation',
	'weletranslation.wordpress.com'                   : 'Wele Translation',
	'whitetigertranslations.wordpress.com'            : 'White Tiger Translations',
	'willfulcasual.wordpress.com'                     : 'Willful Casual',
	'wolfietranslation.wordpress.com'                 : 'Wolfie Translation',
	'wordofcraft.wordpress.com'                       : 'Word of Craft',
	'wuwuwu555.wordpress.com'                         : 'Wuwuwu555',
	'wuxiaheroes.wordpress.com'                       : 'Wuxia Heroes',
	'wuxiwish.wordpress.com'                          : 'Wuxiwish',
	'www.shinsori.com'                                : 'Shinsori Translations',
	'wwyxhqc.wordpress.com'                           : 'Dreams of Jianghu',
	'xantandminions.wordpress.com'                    : 'Xant & Minions',
	'xantbos.wordpress.com'                           : 'Xant Does Stuff and Things',
	'xcrossj.wordpress.com'                           : 'XCrossJ',
	'xxjohnsmithxx.wordpress.com'                     : 'I\'ve reincarnated, but I\'m a Girl! Wait, am I not even Human?',
	'yellawlaw.wordpress.com'                         : 'Wuxiaworld',
	'yoraikun.wordpress.com'                          : 'Yoraikun Translation',
	'youjinsite.wordpress.com'                        : 'Youjinsite Translations',
	'youkoadvent.wordpress.com'                       : 'Youko Advent',
	'youshokutranslations.wordpress.com'              : 'Youshoku Translations',
	'youtsubasilver.wordpress.com'                    : 'youtsubasilver\'s Blog',
	'zentranslations.wordpress.com'                   : 'Zen Translations',
	'zetianjitranslation.wordpress.com'               : 'Translating Ze Tian Ji',
	'zmunjali.wordpress.com'                          : 'Roxism HQ',
	'sparklingdawnlights.blogspot.com'                : 'Little Translations',
	'tbatenovel.com'                                  : 'The Beginning After The End Novel',
	'thebeginningaftertheendblog.wordpress.com'       : 'The Beginning After The End Novel',
	'theundyingblog.wordpress.com'                    : 'The Undying Cultivator',

	# Blogspot
	'trungnguyenwriter.blogspot.com'                  : 'Trung Nguyen',
	'tlsyosetsu.blogspot.com'                         : 'TL Syosetsu',
	"aquarilasscenario.blogspot.com"                  : "Aquarilas' Scenario",
	"arzengi.blogspot.com"                            : "Towards the Sky~",
	"erosworkshop.blogspot.com"                       : "Eros Workshop",
	"the-last-skull.blogspot.com"                     : "The Last Skull",
	"thezombieknight.blogspot.com"                    : "The Zombie Knight",
	"xhawk77x.blogspot.com"                           : "Universes With Meaning",
	'a0132.blogspot.com'                               : 'My Translations',
	'a0132.blogspot.com'                              : 'A0132',
	'ahoujicha.blogspot.com'                           : 'Roasted Tea',
	'ahoujicha.blogspot.com'                          : 'Roasted Tea',
	'azureskytls.blogspot.com'                         : 'Azure Sky Translation',
	'azureskytls.blogspot.com'                        : 'Azure Sky Translation',
	'azureskytls.blogspot.com'                     : 'Azure Sky Translation',
	'azurillturtle.blogspot.com'                      : '輝く世界',
	'bakadogeza.blogspot.com'                         : 'Baka Dogeza Translation',
	'bersekertranslations.blogspot.com'               : 'Berseker Translations',
	'bersekertranslations.blogspot.com'            : 'Berseker Translations',
	'bltranslation.blogspot.com'                      : 'Chinese BL Translations',
	'booksmoviesandbeyond.blogspot.com'               : 'Books Movies and Beyond',
	'bubujingxinenglish.blogspot.com'               : 'Startling Surprises at Every Step',
	'bubujingxinenglish.blogspot.com'                 : 'Startling Surprises at Every Step',
	'bubujingxinenglish.blogspot.com'              : 'Startling Surprises at Every Step',
	'cetranslation.blogspot.com'                       : 'C.E. Light Novel Translations',
	'cetranslation.blogspot.com'                      : 'C.E. Light Novel Translations',
	'cetranslation.blogspot.com'                       : 'C.E. Light Novel Translations',
	'clickyclicktranslation.blogspot.com'           : 'Clicky Click Translation',
	'clickyclicktranslation.blogspot.com'             : 'Clicky Click Translation',
	'cnovelproject.blogspot.com'                      : 'The C-Novel Project',
	'crimsonkisato.blogspot.com'                      : 'Kisato\'s MLTs',
	'dreadfuldecoding.blogspot.com'                   : 'Dreadful Decoding',
	'dreamsleeper87.blogspot.com'                     : 'Lunate',
	'ecwebnovel.blogspot.com'                          : 'EC Webnovel',
	'ecwebnovel.blogspot.com'                         : 'EC Webnovel',
	'erolns.blogspot.com'                             : 'Ero Light Novel Translations',
	'godawfultranslator.blogspot.com'               : 'God Awful Machine Translator',
	'gurotranslation.blogspot.com'                    : 'Guro Translation',
	'hikuosan.blogspot.com'                           : 'ヾ(。￣□￣)ﾂ',   # I can haz UTF-8 source code?
	'imoutoliciouslnt.blogspot.com'                    : 'Imoutolicious Light Novel Translations',
	'imoutoliciouslnt.blogspot.com'                   : 'Imoutolicious Light Novel Translations',
	'imoutoliciouslnt.blogspot.com'                : 'Imoutolicious Light Novel Translations',
	'imperatorarcana.blogspot.com'                 : 'Imperator Arcana',
	'istlovesu.blogspot.com'                          : 'Istian\'s Workshop',
	'istlovesu.blogspot.com'                       : 'Istian\'s Workshop',
	'itslovetranslation.blogspot.com'                 : 'Korean Novel Translations',
	'jawztranslations.blogspot.com'                    : 'JawzTranslations',
	'jawztranslations.blogspot.com'                   : 'JawzTranslations',
	'kaezartranslations.blogspot.com'                 : 'Kaezar Translations',
	'kurotsuki-novel.blogspot.com'                     : 'Kurotsuki Novel',
	'kurotsuki-novel.blogspot.com'                    : 'Kurotsuki Novel',
	'legendofgalacticheroes.blogspot.com'             : 'Legend of Galactic Heroes Translation Project',
	'lmfyd.blogspot.com'                            : 'Love me if you dare',
	'lmfyd.blogspot.com'                              : 'Love me if you dare',
	'mahoukoukoku.blogspot.com'                       : 'Mahou Koukoku',
	'mahoukoukoku.blogspot.com'                    : 'Mahou Koukoku',
	'mtlcorner.blogspot.com'                          : 'Andrew9495\'s MTL corner',
	'nakulas.blogspot.com'                            : '[nakulas]',
	'noitl.blogspot.com'                              : 'Translation Treasure Box',
	'noitl.blogspot.com'                               : 'Translation Treasure Box',
	'onesecondspring.blogspot.com'                    : 'One Second Spring',
	'onesecondspring.blogspot.com'                     : 'One Second Spring',
	'otakunoeiyaku.blogspot.com'                      : 'Ducky\'s English Translations',
	'panofitrans.blogspot.com'                        : 'Translations From Outer Space',
	'popsiclete.blogspot.com'                         : 'Popsiclete',
	'pumpkintranslations.blogspot.com'                : 'Pumpkin Translations',
	'royalroadweed.blogspot.com'                    : 'Royal Road Weed',
	'skythewood.blogspot.com'                         : 'Skythewood translations',
	'skythewood.blogspot.com'                          : 'Skythewood translations',
	'skythewoodtl.com'                                : 'Skythewood translations',
	'sweetacollections.blogspot.com'                  : 'Sweet A Collections',
	'swordandgame.blogspot.com'                        : 'Sword and Game',
	'swordandgame.blogspot.com'                       : 'Sword and Game',
	'swordandgame.blogspot.com'                        : 'Sword and Game',
	'tabikonotrans.blogspot.com'                      : 'A traveler\'s translations.',
	'thebathrobeknight.blogspot.com'                  : 'The Bathrobe Knight',
	'thelordofpie.blogspot.com'                       : 'Pielord Translations',
	'thenakedsol.blogspot.com'                        : 'Iterations within a Thought-Eclipse',
	'thenakedsol.blogspot.com'                     : 'Iterations within a Thought-Eclipse',
	'thezombieknight.blogspot.com'                  : 'The Zombie Knight',
	'tony-yon-ka.blogspot.com'                        : 'Tony Yon Ka',
	'tony-yon-ka.blogspot.com'                     : 'Tony Yon Ka',
	'tu-shu-guan.blogspot.com'                        : '中翻英圖書館 Translations',
	'turb0translation.blogspot.com'                   : 'Turb0 Translation',
	'udonatewetranslate.blogspot.com'                 : 'U Donate We Translate',
	'unnamedtranslations.blogspot.com'                 : 'Unnamed Translations',
	'untuned-strings.blogspot.com'                     : 'Untuned Translation Blog',
	'untuned-strings.blogspot.com'                    : 'Untuned Translation Blog',
	'webnoveltranslations.blogspot.com'               : 'Neo Translations',
	'webnoveltranslations.blogspot.com'                : 'Neo Translations',
	'webnoveltranslations.blogspot.com'                : 'Neo Translations',
	'jigglypuffsdiary.com'                            : 'Neo Translations',
	'wishuponahope.blogspot.com'                    : 'Wish Upon A Hope',
	'wishuponahope.blogspot.com'                      : 'Wish Upon A Hope',
	'witchlifenovel.blogspot.com'                     : 'Witch Life Novel',
	'xcrossj.blogspot.com'                            : 'XCrossJ',
	'xcrossj.blogspot.com'                         : 'XCrossJ',
	'yorasutranslations.blogspot.com'                 : 'Yorasu Translations',
	'yukkuri-literature-service.blogspot.com'         : 'Yukkuri Free Time Literature Service',
	'sparklingdawnlights.blogspot.com'                 : 'Little Translations',
	'tseirptranslations.blogspot.com'                  : 'Tseirp Translations',
	'tseirptranslations.blogspot.com'                 : 'Tseirp Translations',

	'mineralwatertranslation.blogspot.com'          : 'Mineral Water Translation',
	'mineralwatertranslation.blogspot.com'            : 'Mineral Water Translation',
	'saiakutranslationsblog.wordpress.com'            : 'Saiaku Translations Blog',
	'mylittlehippokun.wordpress.com'                  : '/',
	'adorablexd.wordpress.com'                        : 'Joie de Vivre',
	'daike1234.wordpress.com'                         : 'Crappy Machine Translation',
	'dekinaidiary.wordpress.com'                      : 'Dekinai Diary',
	'v7silent.wordpress.com'                          : 'v7 Silent',


	"sousetsuka.blogspot.com"                         : "Sousetsuka",
	'sousetsuka.blogspot.com'                          : 'Sousetsuka',
	'www.sousetsuka.com'                              : 'Sousetsuka',

	# Other
	"dragomircm.com"                                  : "DragomirCM",
	"feedproxy.google.com"                            : "FeedProxy",
	"izra709.com"                                     : "izra709 | B Group no Shounen Translations",
	"rebirthonlineworld.com"                          : "Rebirth Online World",
	"tototr.com"                                      : "Totokk\'s Translations",
	"www.worldofwatermelons.com"                      : "World of Watermelons",
	'77novel.com'                                     : '77 Novel',
	'adarshan-novels.livejournal.com'                 : 'Adarshan no Hanayome',
	'anni-fiesta.livejournal.com'                     : 'The Verbose Playground',
	'applepling.tumblr.com'                           : 'Collection.',
	'aresnovels.com'                                  : 'Ares Novels',
	'arkmachinetranslations.com'                      : 'Ark Machine Translations',
	'avertranslation.com'                             : 'Avert Translations',
	'avertranslation.org'                             : 'Avert Translations',
	'black-freya.livejournal.com'                     : 'Mobile Suit Zeta Gundam Novels Translation',
	'blastron01.tumblr.com'                           : 'Blastron Does Some Things',
	'blazingtranslations.com'                         : 'Blazing Translations',
	'catingham-palace.com'                            : 'Nekoyashiki',
	'cavescans.com'                                   : 'CaveScans',
	'chinanovel.net'                                  : 'Chinanovel.net',
	'circustranslations.com'                          : 'Circus Translations',
	'closure-of-yellow.tumblr.com'                    : 'Clôture of Yellow',
	'cnovels.bookbychapters.com'                      : 'Lil\' Bliss Novels',
	'bookbychapters.com'                              : 'Lil\' Bliss Novels',
	'cocobees.tumblr.com'                             : 'Cocobees',
	'demontranslations.com'                           : 'Demon Translations',
	'eccentrictranslations.com'                       : 'EccentricTranslations',
	'eternalpath.net'                                 : 'Root of Evil',
	'eugene-rain.com'                                 : 'Eugene Rain',
	'flowerbridgetoo.com'                             : 'Flower Bridge Too',
	'forgottenconqueror.com'                          : 'Forgotten Conqueror',
	'giraffecorps.liamak.net'                         : 'Giraffe Corps',
	'gomigeemu.tumblr.com'                            : 'Gomigeemu',
	'goodwifetranslation.com'                         : 'Good Wife Translation',
	'gravitytales.com'                                : 'Gravity Tales',
	'gravitytranslations.com'                         : 'Gravity Translation',
	'grimdarkztranslations.com'                       : 'GrimdarkZ Translations',
	'guhehe.net'                                      : 'guhehe.TRANSLATIONS',
	'helidwarf.com'                                   : 'Helidwarf',
	'hellping.org'                                    : 'Hellping',
	'heroicnovels.com'                                : 'Heroic Novels',
	'honyakusha-eri.tumblr.com'                       : 'Translator Eri',
	'inchoate-oeuvre.livejournal.com'                 : 'Inchoate Oeuvre',
	'indoromance.com'                                 : 'Evida\'s Indo Romance',
	'inmydaydreams.com'                               : 'In My Daydreams',
	'japtem.com'                                      : 'Japtem',
	'joeglens.com'                                    : 'Joeglen\'s Translation Space',
	'keseranpasaran.livejournal.com'                  : 'BL Drama Diary',
	'kobatochandaisuki.com'                           : 'KobatoChanDaiSukiScan',
	'krytykal.org'                                    : 'Krytyk\'s Translations',
	'lasolistia.com'                                  : 'HaruPARTY',
	'laute.tumblr.com'                                : 'Laute, Laute!',
	'lightnovelstranslations.com'                     : 'Light Novels Translations',
	'lily-ros3.livejournal.com'                       : 'Lily Ros 3',
	'liveandlearn88.com'                              : 'Grow with Me',
	'lmsmachinetranslations.com'                      : 'LMS Machine Translations',
	'ln.m-chan.org'                                   : 'Baka-Tsuki e-pub Generator',
	'lunacy-of-venomania.tumblr.com'                  : 'The Lunacy of Duke Venomania',
	'luxiufer.livejournal.com'                        : 'Luxiufer',
	'mikagura-scans.tumblr.com'                       : 'Mikagura Scanlations Club',
	'mittens-220.livejournal.com'                     : 'Mittens 220',
	'moonbunnycafe.com'                               : 'Moon Bunny Cafe',
	'necromancyscans.tumblr.com'                      : 'Scanlating the Lodoss Novels',
	'nightbreezetranslations.com'                     : 'Nightbreeze Translations',
	'novelsnao.com'                                   : 'Novels Nao',
	'omatranslations.com'                             : 'One Man Army Translations (OMA)',
	'opinisaya.com'                                   : 'Opinisaya.com',
	'orenotokei.livejournal.com'                      : 'Japanese Light Novels: Prologues',
	'pandatranslations.net'                           : 'pandafuqtranslations',
	'panisal.livejournal.com'                         : 'panisal',
	'pikatranslations.com'                            : 'Pika Translations',
	'project-accelerator.net'                         : 'Project Accelerator',
	'raisingthedead.ninja'                            : 'Raising the Dead',
	'www.raisingthedead.ninja'                        : 'Raising the Dead',
	'rancerqz.com'                                    : 'Rancer',
	're-monster.wikia.com'                            : 'Re:Monster Wiki',
	'reddycreations.com'                              : 'Reddy Creations',
	'renna-translations.tumblr.com'                   : 'Renna\'s Translations',
	'requirecookie.com'                               : 'Require: Cookie',
	'risingdragons.co'                                : 'Rising Dragons Translation',
	'rumanshi.com'                                    : 'Rumanshi\'s Lair',
	'Rumanshi.com'                                    : 'Rumanshi\'s Lair',
	's3ri.livejournal.com'                            : 'S3ri',
	'shinsekai.cadet-nine.org'                        : 'Shin Sekai Yori – From the New World',
	'shintranslations.com'                            : 'Shin Translations',
	'shiroyukitranslations.com'                       : 'Shiroyukineko Translations',
	'sinmay.livejournal.com'                          : 'Spirits Abound',
	'sl-llian.livejournal.com'                        : 'Llian',
	'slavetranslations.com'                           : 'Slave Translations',
	'soaringtranslations.com'                         : 'Soaring Translations',
	'sookybabi.livejournal.com'                       : 'Sooky\'s Kitchen',
	'soratranslations.com'                            : 'Sora Translations',
	'soul-eater-novel.tumblr.com'                     : 'Suikoden I: Soul Eater Novel Translation',
	'subudai11.com'                                   : 'Subudai11',
	'thetaleofxero.net'                               : 'Mystic Tales',
	'thundertranslations.com'                         : 'Thunder Translation',
	'thyaeriatranslations.com'                        : 'Thyaeria Translations',
	'tiffybook.com'                                   : 'Crazy for HE Novels',
	'totallyinsanetranlation.com'                     : 'Totally Insane Translation',
	'totobro.com'                                     : 'Totokk\'s Translations',
	'tototrans.com'                                   : 'Totokk\'s Translations',
	'translatisms.tumblr.com'                         : '陽光的夏天',
	'trinityarchive.com'                              : 'Trinity Archive',
	'trolllancer.com'                                 : '[G.O] Chronicles',
	'tsukilining.livejournal.com'                     : 'Tsuki\'s Miscellaneous',
	'turtleme.me'                                     : 'The Beginning After The End',
	'unlimitednovelfailures.mangamatters.com'         : 'Unlimited Novel Failures',
	'vgperson.tumblr.com'                             : 'VgPerson',
	'volaretranslations.com'                          : 'Volare Translations',
	'walkthejianghu.com'                              : 'Walk the Jiang Hu',
	'weaboodesu.com'                                  : 'Weaboo Desu',
	'Weaboodesu.com'                                  : 'Weaboo Desu',
	'wiegenlied-of-green.tumblr.com'                  : 'Wiegenlied of Green',
	'worldofwatermelons.com'                          : 'World of Watermelons',
	'wuxiaheroes.com'                                 : 'Wuxia Heroes',
	'wuxiasociety.com'                                : 'WuxiaSociety',
	'wuxiaworld.com'                                  : 'Wuxia World',
	'www.arantranslations.com'                        : 'Aran Translations',
	'www.baka-tsuki.org'                              : 'Baka-Tsuki',
	'www.bladeofhearts.com'                           : 'Blade of Hearts',
	'www.blazingtranslations.com'                     : 'Blazing Translations',
	'www.bluephoenixnovel.com'                        : 'Blue Phoenix',
	'bluephoenixnovel.com'                            : 'Blue Phoenix',
	'www.deadlylegends.com'                           : 'Deadly Forgotten Legends',
	'www.heroicnovels.com'                            : 'Heroic Novels',
	'www.lingson.com'                                 : 'Lingson\'s Translations',
	'www.lonahora.com'                                : 'Lonahora',
	'www.novelsaga.com'                               : 'Novel Saga',
	'www.pandatranslations.net'                       : 'Panda Translations',
	'www.paultwister.com'                             : 'The Tales of Paul Twister',
	'www.pegasusfarts.com'                            : 'Pegasus Farts',
	'www.pridesfamiliarsmaidens.com'                  : 'Pride X ReVamp',
	'www.princerevolution.org'                        : 'Prince Revolution!',
	'www.radianttranslations.com'                     : 'Radiant Translations',
	'www.renegadesanctuary.com'                       : 'Renegade Sanctuary',
	'www.risingdragonstranslation.com'                : 'Rising Dragons Translation',
	'www.shintranslations.com'                        : 'Shin Translations',
	'www.soltarination.org'                           : 'Soltarination Scanlations',
	'www.suiminchuudoku.net'                          : '睡眠中毒',
	'www.talesofmu.com'                               : 'Tales of MU',
	'www.taptaptaptaptap.net'                         : 'tap-trans » tappity tappity tap.',
	'www.translationnations.com'                      : 'Translation Nations',
	'www.wattpad.com'                                 : 'Wattpad',
	'www.whimsicalland.com'                           : 'Whimsical Land',
	'www.wuxiaheroes.com'                             : 'Wuxia Heroes',
	'www.wuxiatranslations.com'                       : 'Wuxia Translations',
	'www.wuxiaworld.com'                              : 'Wuxiaworld',
	'www.youjinsite.com'                              : 'Youjinsite Translations',
	'www.zeonic-republic.net'                         : 'Zeonic',
	'yellawtwl.com'                                   : 'Wuxiaworld',
	'youjinsite.com'                                  : 'Youjinsite Translations',
	'yuujinchou.livejournal.com'                      : 'Yuujinchou',
	'zhuanji.livejournal.com'                         : '未完待续',
	'toriitranslations.animeholics.org'               : 'Torii Translations',

	'fgilantranslations.wordpress.com'                : 'fgiLaN translations',
	'fgilantranslations.com'                          : 'fgiLaN translations',

	'slothtranslationsblog.wordpress.com'             : 'Sloth Translations Blog',
	'dadishero.wordpress.com'                         : 'DadIsHero Fan Translations',
	'ezanifiction.wordpress.com'                      : 'E. Zani Fiction',


	'chronazero.blogspot.com'                         : 'Chrona Zero',
	'tlsyosetsu.blogspot.com'                          : 'TL Syosetsu',
	'trungnguyenwriter.blogspot.com'                   : 'Trung Nguyen',
	'royalroad.blogspot.com'                          : 'The Bountiful REM Exploits of Danziger Monking',
	'misarumi.tumblr.com'                             : '宿命の二人',
	'ichinichibl.tumblr.com'                          : 'Ichinichi BL',
	'www.zxzxzx.info'                                 : 'Zxzxzx\'s blog',
	'bunimithetranslation.wordpress.com'              : 'A Translation of the Bu Ni Mi Light Novel ',
	'psicern.wordpress.com'                           : 'Psicern.Translations',
	'ninjanuf.wordpress.com'                          : 'NinjaNUF',
	'anotherworldtranslations.wordpress.com'          : 'Another World Translations',
	'arctranslations.wordpress.com'                   : 'Arc\'s Translations',
	'arslansenki.wordpress.com'                       : 'Heroic Legend of Arslan Translations',
	'ayaxworld.wordpress.com'                         : 'Ayax World',
	'bbluefiree.wordpress.com'                        : 'Bluefire Translations',
	'bijinsans.wordpress.com'                         : 'Bijinsans',
	'blackpond.wordpress.com'                         : 'Pandora\'s Book',
	'chronontranslations.wordpress.com'               : 'Chronon Translations',
	'cloudtranslations.wordpress.com'                 : 'Cloud Translations',
	'dowstranslations.wordpress.com'                  : 'DOW\'s Translations',
	'emptyboundaries.wordpress.com'                   : 'Empty Boundaries',
	'faketypist.wordpress.com'                        : 'Fake typist',
	'falinmer.wordpress.com'                          : 'Falinmer',
	'gaochaotranslations.wordpress.com'               : 'Gaochao Translations',
	'halfelementmaster.wordpress.com'                 : 'HalfElementMaster Translation',
	'halfelementmaster.com'                           : 'HalfElementMaster Translation',
	'honyakusite.wordpress.com'                       : 'Hon\'yaku',
	'januketranslations.wordpress.com'                : 'Januke Translations',
	'japanesemafialady.wordpress.com'                 : 'Kakkokari',
	'karkiat.wordpress.com'                           : 'Disappointing Translations',
	'keyotranslations.wordpress.com'                  : 'Keyo Translations',
	'kokumatranslations.wordpress.com'                : 'Kokuma Translations',
	'lickymeetranslations.wordpress.com'              : 'Lickymee Translations',
	'loliquentblog.wordpress.com'                     : 'Lynfamily',
	'mojotranslations.wordpress.com'                  : 'Mojo Translations',
	'nakimushitl.wordpress.com'                       : 'Nakimushi',
	'nefasvenustus.wordpress.com'                     : 'This World Work',
	'nepustation.wordpress.com'                       : 'Nepustation',
	'nepustation.com'                                 : 'Nepustation',
	'pekaboblog.wordpress.com'                        : 'Pekabo Blog',
	'penguinoverlordblog.wordpress.com'               : 'Penguin Overlord Translations',
	'premiumredtea.wordpress.com'                     : 'Premium Red Tea',
	'razorace.wordpress.com'                          : 'Tentatively under construction',
	'riptranslations.wordpress.com'                   : 'Rip translations',
	'ruibelle.wordpress.com'                          : 'Rui\'s Translations',
	'shenyuanlangmtl.wordpress.com'                   : 'Shen Yuan Lang MTL',
	'solstar24.wordpress.com'                         : 'Solstar24',
	'springscents.wordpress.com'                      : 'Spring Scents',
	'starrydawntranslations.wordpress.com'            : 'Starrydawn Translations',
	'taidadonotranslations.wordpress.com'             : 'Taida-dono Translations',
	'trytranslations.wordpress.com'                   : 'Try Translations',
	'turtleandharetranslations.wordpress.com'         : 'Turtle and Hare Translations',
	'wizthief.wordpress.com'                          : 'WizThief\'s Novels',
	'wuxiatranslators.wordpress.com'                  : 'Wuxia Translators',
	'dailydallying.com'                               : 'Daily-Dallying',
	'cookiepasta.com'                                 : 'CookiePasta Translations',
	'chasingadreamtranslations.com'                   : 'Translating For Your Pleasure',
	'falamartranslation.wordpress.com'                : 'Falamar Translation',
	'cautrs.com'                                      : 'Cautr\'s',
	'machineslicedbread.xyz'                          : 'Machine Sliced Bread',
	'koongkoongtranslations.com'                      : 'Koong Koong Translations',
	'www.lightnovelstranslations.com'                 : 'Light Novels Translations !',
	'www.anotherparallel.space'                       : 'Another Parallel World',
	'talesoftheforgottenslayer.wordpress.com'         : 'Tales of The Forgottenslayer',
	'welcometotheunderdark.wordpress.com'             : 'Welcome To The Underdark',
	'snowy.pub'                                       : 'Snowy Publications',
	'twigserial.wordpress.com'                        : 'Twig',
	'silvalibrary.com'                                : 'Silva\'s Library',


	'sparkskey.livejournal.com'                       : '희노애락',
	'narumo.livejournal.com'                          : 'Creepy and Evil Translations',
	'forbidentry.livejournal.com'                     : 'Forbidentry',
	'redturtle95.livejournal.com'                     : 'Turtle\'s',
	'yonakayaku.tumblr.com'                           : 'HaruChika & Ghost Hunt Translations',
	'dragonmt.wordpress.com'                          : 'Dragon MT',
	'nanowave.wordpress.com'                          : 'Nanowave Translations',
	'altoroctranslations.wordpress.com'               : 'Altoroc Translations',
	'delicioustranslations.wordpress.com'             : 'Delicious Translations',
	'norvablog.wordpress.com'                         : 'Norva Blog',
	'tatakaushisho.wordpress.com'                     : 'Tatakau Shisho Light Novel Translation',
	'dreamlesswindow.wordpress.com'                   : 'Dreamless Window\'s translation',


	'pettankotranslations.wordpress.com'              : 'Pettanko Translations',
	'www.ironteethserial.com'                         : 'The Iron Teeth',
	'senjiqcreations.wordpress.com'                   : 'SenjiQ creations',


	'emruyshittranslations.blogspot.com'              : 'Emruyshit Translations',
	'negaraizu.wordpress.com'                         : 'Nega Translations',
	'nighttranslations.wordpress.com'                 : 'NightFall Translations',
	'oyasumireads.wordpress.com'                      : 'Oyasumi Reads',
	'spiritualtranscription.wordpress.com'            : 'Spiritual Transcription',


	'fantasybooksforever.blogspot.com'             : 'Fantasy novels',
	'fantasybooksforever.blogspot.com'                : 'Fantasy novels',
	'icarusbride.blogspot.com'                        : 'Icarus Bride Scanlation',
	'kyoptionslibrary.blogspot.com'                    : 'KyOption\'s Library',
	'dhh-workshop.blogspot.com'                       : 'DHH Translations',
	'mahoukoukoku.blogspot.com'                     : 'Mahou Koukoku',
	'asiaisaru.livejournal.com'                       : 'Death, taxes, and fandom.',
	'dandeliontrail.livejournal.com'                  : 'Dandelion Trail',
	'hugginglove.blogspot.com'                         : 'Hugs & Love',
	'hugginglove.blogspot.com'                        : 'Hugs & Love',

	'polaristranslations.tumblr.com'                  : 'Polaris Translations',
	'freezinglightnovels.wordpress.com'               : 'Freezing Light Novels',
	'tamakeribanchou.wordpress.com'                   : '\'Ball\'-Kicking Gang Boss',
	'arousingimouto.wordpress.com'                    : 'Arousing Imouto',
	'yamenaideoneesama.wordpress.com'                 : '止めないで、お姉さま…',
	'azuremysterioustofusect.wordpress.com'           : '青玄豆腐幇',
	'psychobarcodetranslations.wordpress.com'         : 'Psycho Barcode Translations',
	'fablewind.wordpress.com'                         : 'Fable Wind',
	'snowtranslations.wordpress.com'                  : 'Snow Translations',
	'rinotakublog.wordpress.com'                      : 'RinOtakuBlog',
	'kawaiidaikon.wordpress.com'                      : 'Kawaii Daikon',
	'anneandcindy.wordpress.com'                      : 'Anne And Cindy',
	'ntrholic.wordpress.com'                          : 'NTRHolic',
	'sleepytranslations.wordpress.com'                : 'Sleepy Translations',
	'shell2ly.wordpress.com'                          : 'Shell2ly C-Novel Site',
	'harezora.wordpress.com'                          : 'Ling Translates Sometimes',
	'noodletowntranslated.wordpress.com'              : 'Noodletown Translated',
	'noodletowntranslated.com'                        : 'Noodletown Translated',
	'mayy91.wordpress.com'                            : 'Twelve Months of May',
	'lypheonblog.wordpress.com'                       : 'Lypheon Machine Translation',
	'novelisation.wordpress.com'                      : 'Novelisation',
	'demerithtranslation.wordpress.com'               : 'Demerith Translation',
	'tinkerbellsan.wordpress.com'                     : 'Tinkerbell-san',
	'hellyeah524.wordpress.com'                       : 'Hell Yeah 524',
	'monktranslations.wordpress.com'                  : 'Monkoto\'s Translations',
	'bayabuscotranslation.wordpress.com'              : 'Bayabusco Translation',
	'lohithbbtls.wordpress.com'                       : 'Lohithbb TLs',
	'faktranslations.wordpress.com'                   : 'Fak Translations',
	'faktranslations.com'                             : 'Fak Translations',
	'epithetic.wordpress.com'                         : 'Epithetic',
	'mtlcrap.wordpress.com'                           : 'MTLCrap',
	'redlanternarchives.wordpress.com'                : 'Red Lantern Archives',
	'tarabletranslation.wordpress.com'                : 'Tarable Translations',
	'skullsquadorn.wordpress.com'                     : 'Skull Squadron',
	'wltrans.wordpress.com'                           : 'WL Translations',
	'bruintranslation.wordpress.com'                  : 'Bruin Translation',
	'comereadme.wordpress.com'                        : 'Read Me Translations',
	'junjuntianxia.wordpress.com'                     : 'Jun Juntianxia',
	'alicemtl.wordpress.com'                          : 'AliceMTL',
	'hikkinomori.wordpress.com'                       : 'Hikki no Mori Translations',
	'asd398.wordpress.com'                            : 'asd398',
	'ridwantrans.wordpress.com'                       : 'RidwanTrans',
	'ameryedge.com'                                   : 'Amery Edge',
	'www.novelsground.com'                            : 'Novels Ground',
	'tseirptranslations.com'                          : 'Tseirp Translations',
	'littleshanks.net'                                : 'LittleShanks Translations',
	'littlenovel.com'                                 : 'Little Novel Translation',
	'hyorinmaru.net'                                  : 'Hyorinmaru',
	'hyorinmarublog.wordpress.com'                    : 'Hyorinmaru',

	'realmofchaosblog.wordpress.com'                  : 'Realm of Chaos',
	'albertkenoreijou.wordpress.com'                  : 'Albert Kenoreijou',
	'piggybottle.wordpress.com'                       : 'PiggyBottle Translations',
	'projecthydrogen.wordpress.com'                   : 'Sandwich Kingdom',
	'tyrantseyetranslations.wordpress.com'            : 'Tyrant\'s Eye Translations',
	'kondeesite.wordpress.com'                        : 'KONDEE Translations',
	'ukel2x.wordpress.com'                            : 'Ukel2x',
	'ukel2x.blogspot.com'                             : 'Ukel2x',
	'procrastranslation.wordpress.com'                : 'ProcrasTranslation',
	'novelsjapan.wordpress.com'                       : 'Novels Japan',
	'novelsjapan.com'                                 : 'Novels Japan',
	'7daystrial.wordpress.com'                        : '7 Days Trial',
	'dokuhanatl.wordpress.com'                        : 'DokuHana Translations',
	'ensigblog.wordpress.com'                         : 'Ensig\'s Writings',

	'rinkagetranslation.com'                          : 'Rinkage Translation',
	'wltranslations.com'                              : 'WL Translations',

	'shikkakutranslations.org'                        : 'Shikkaku Translations',

	'polarbearcatcher.wordpress.com'                  : 'Polar Bear Catcher',
	'apollotrans.wordpress.com'                       : 'Apollo Translations',
	'vermillionthetranslation.wordpress.com'          : '(NanoDesu) - Vermillion',
	'leechervamparis.wordpress.com'                   : 'Leecher Vamparis Translations',
	'wumstranslations.wordpress.com'                  : 'Wums Translations',
	'poorqualitytl.wordpress.com'                     : 'Poor Quality Translations',
	'hiohbye.wordpress.com'                           : 'Hiohbye Translations',
	'daupao.wordpress.com'                            : 'Daupao',
	'soulpermutation.wordpress.com'                   : 'Soul Permutation',
	'wisnujr.wordpress.com'                           : 'Noob Mtl',
	'zerotranslations.wordpress.com'                  : 'Zero Translations',
	'elementalcobalt.wordpress.com'                   : 'Elemental Cobalt',
	'xianxiatales.wordpress.com'                      : 'Xianxia Tales',
	'ceiphiedknightandbanditsplight.wordpress.com'    : 'Chaos Words',
	'pathoftranslation.wordpress.com'                 : 'Path of Translation',
	'myoniyonitranslations.wordpress.com'             : 'Myoniyoni Translations',
	'alternativeprojects.wordpress.com'               : 'Alternative Projects',
	'yamettetranslations.wordpress.com'               : 'Yamette Translations',
	'euphmoria.wordpress.com'                         : 'No Name Translations',

	'godawfultranslator.blogspot.com'                 : 'God Awful Machine Translator',
	'imperatorarcana.blogspot.com'                    : 'Imperator',
	'zips-17.livejournal.com'                         : 'Zips_17',
	'penumbrale.livejournal.com'                      : 'Penumbrale',
	'2minutesofyourtime.tumblr.com'                   : 'Pleiades',
	'himegaminomiko.tumblr.com'                       : 'Himegami no Miko Translated',
	'mirroredtranslations.tumblr.com'                 : '鏡像翻訳',
	'novelsnchill.com'                                : 'Novels&Chill',
	'levitytales.com'                                 : 'Levity Tales',
	'www.mayyth.com'                                  : 'Twelve Months of May',
	'yamitranslations.com'                            : 'Yami Translations',
	'sakurane.sky-field.org'                          : 'Sakurane',
	'reincarnationtranslations.com'                   : 'Reincarnation Translations',
	'spiritgodshura35.wordpress.com'                  : 'Spirit God Shura',
	'lightsways.wordpress.com'                        : 'The Boy Who Couldn\'t Be A Hero',
	'landoflightnovels.wordpress.com'                 : 'Land of Light Novels',
	'reitransblog.wordpress.com'                      : 'Rei TransBlog',
	'whitenightsite.wordpress.com'                    : 'White Night Site',
	'extantvisions.com'                               : 'Extant Visions',



	'chillock-amt.blogspot.com'                       : 'Anime, Manga, Translations',
	'exploringtheroadoflife.blogspot.com'           : 'I swear I\'m not lost... I\'m just... exploring...',
	'hextidol.blogspot.com'                           : 'For Kalimdor!',
	# 'jolecole.blogspot.com'                           : 'jolecole.blogspot.com',
	'kfn-translations.blogspot.com'                   : 'Knight Fantastic Night Translations',
	'shinetranslation.blogspot.com'                   : 'Shine Translation',
	'shovatranslations.blogspot.com'                  : 'Shova Translations',
	'amethystcria.tumblr.com'                         : '✱||| Straying away…。',
	# 'chendaere.tumblr.com'                            : 'chendaere.tumblr.com',
	'doushinojikan.tumblr.com'                        : 'Doushi no Jikan scanlations',
	# 'hisokasasss.tumblr.com'                          : 'hisokasasss.tumblr.com',
	'izuminotwins.tumblr.com'                         : 'Prince of Stride Novel Translation',
	# 'kiyoitsukikage.tumblr.com'                       : 'kiyoitsukikage.tumblr.com',
	'revolutionpotato.tumblr.com'                     : 'Various Translated Work',
	# 'shou7.tumblr.com'                                : 'shou7.tumblr.com',
	'tang-wei.tumblr.com'                             : 'Welcome to the Malformed Box',
	'xia0yuer.tumblr.com'                             : 'Confessions of a Drama Addict',
	# 'yifanqini.tumblr.com'                            : 'yifanqini.tumblr.com',
	'ciaranhillock.tumblr.com'                        : 'Ciaran Hillock',
	'ankoutranslations.wordpress.com'                 : 'Ankou Translations',
	'bananachocolatecosmos.wordpress.com'             : 'ChocolateCosmos Translations',
	'chinalightnovel.wordpress.com'                   : 'China Light Novel',
	'chinesenoveltranslated.wordpress.com'            : 'Chinese Novel Translated',
	'datebayoblog.wordpress.com'                      : 'Datebayo Blog',
	'demonscorpion.wordpress.com'                     : 'Demon Scorpion Translations',
	'dreamylilies.wordpress.com'                      : 'Your Majesty Please Calm Down',
	'duwarufutranslations.wordpress.com'              : 'Dwrf TL',
	'elephantno5.wordpress.com'                       : 'World Turtle Translations',
	'expnull.wordpress.com'                           : 'ExpNull',
	'extralaki.wordpress.com'                         : 'Laki\'s Laboratory',
	'fakeftranslations.wordpress.com'                 : 'Fake Fruits Translations',
	'fluffysnowtime.wordpress.com'                    : 'SnowTime Translations',
	'forthemoneytranslations.wordpress.com'           : 'Forthemoney Translations',
	'girlynovelsblog.wordpress.com'                   : 'Girly Novels',
	'heavensjustice.wordpress.com'                    : 'Heavens Justice Translation',
	'honeyfulananas.wordpress.com'                    : 'Ananas Parfait',
	'iballisticbunnies.wordpress.com'                 : 'I Ballistic Bunnies',
	'idyllictranslations.wordpress.com'               : 'Idyllic Translations',
	'incarneous.wordpress.com'                        : 'Incarneous',
	'intentionsofxing.wordpress.com'                  : 'Bo~',
	'jenpresstranslation.wordpress.com'               : 'Jen Press Translation',
	'jujutranslation.wordpress.com'                   : 'JuJu Translation',
	'kagurojp.wordpress.com'                          : 'Kaguro Jp',
	'kai5404.wordpress.com'                           : 'Kai\'s Translations',
	'kiriharamaya.wordpress.com'                      : 'Kirihara Maya',
	'kudarajin.wordpress.com'                         : 'Kudarajin',
	'l3detal.wordpress.com'                           : 'L3D',
	'legendoftheevilgod.wordpress.com'                : 'Legend of the Evil God',
	'legionrealm.wordpress.com'                       : 'Legions Realm',
	'loathsometranslations.wordpress.com'             : 'Loathsome Translations',
	'luminstia.wordpress.com'                         : 'Luminstia',
	'magictrans.wordpress.com'                        : 'Magictrans',
	'mountainofpigeons.wordpress.com'                 : 'Mountain of Pigeons Translations',
	'mtlspot.wordpress.com'                           : 'Chimp\'s MTL Spot',
	'mtnovels.wordpress.com'                          : 'MT Novels',
	'myengtranslation.wordpress.com'                  : 'MyEngTranslation',
	'nadenadeshitai.wordpress.com'                    : 'Nadenadeshitai',
	'nexserus.wordpress.com'                          : 'Nex Serus',
	'novelstravel.wordpress.com'                      : 'Novels Travel',
	'pengutaichou.wordpress.com'                      : 'Pengu Taichou',
	'pumlated.wordpress.com'                          : 'Pumlated',
	'riestranslations.wordpress.com'                  : 'Ries Translations',
	'rinveltsou.wordpress.com'                        : 'Rinvelt House',
	'rogueapple.wordpress.com'                        : 'Rogue Apple',
	'rottentranslations.wordpress.com'                : 'Rotten Translations',
	'sabishidesu.wordpress.com'                       : 'Sabishi desu!!',
	'sekaikuroba.wordpress.com'                       : 'Sekai no Kuroba',
	'shalvationtranslations.wordpress.com'            : 'Shalvation Translations',
	'shamelessoniisan.wordpress.com'                  : 'Shameless Onii-san',
	'shenweilantian.wordpress.com'                    : 'Deep Azure Sky',
	'shouldntbehereblog.wordpress.com'                : 'Shouldnt be here blog',
	'shugui.wordpress.com'                            : '『書櫃』',
	'silkpantsentente.wordpress.com'                  : 'Silkpants Entente',
	'solitaryidler.wordpress.com'                     : '閒人 • O N L I N E',
	'sunnytranslations.wordpress.com'                 : 'SunnyTranslations',
	'tequilamockingbard.wordpress.com'                : 'Tequila Mockingbard',
	'tokyoespscans.wordpress.com'                     : 'Tokyo ESP Scans',
	'tranzgeek.wordpress.com'                         : 'T&Q',
	'uniquebooksblog.wordpress.com'                   : 'Unique Books',
	'yasashihonyaku.wordpress.com'                    : 'Yasashi Honyaku',
	'yeagdrasil.wordpress.com'                        : 'Yeagdrasil',
	'www.ameryedge.com'                               : 'Amery Edge',
	'warites.org'                                     : 'Warrior Writing',
	'wigglytranslation.com'                           : 'Wiggly Translation',
	'penofhope.com'                                   : 'World of Hope',
	'myoniyonitranslations.com'                       : 'Myoniyoni Translations',
	'antheor.eu'                                      : 'Antheor',
	'www.yamitranslations.com'                        : 'Yami Translations',
	'bayabuscotranslation.com'                        : 'Bayabusco Translation',
	'martialdao.com'                                  : 'Martial Dao',
	'www.readingattic.com'                            : 'Reading Attic',
	'mistycloudtranslations.com'                      : 'Misty Cloud Translations',
	'hachidoritranslations.com'                       : 'Hachidori Translations',
	'weletranslation.com'                             : 'Wele Translations',
	'asuratales.com'                                  : 'Asura Tales',
	'exmachina.asia'                                  : 'ExMachina.Asia',
	'lightnovels.world'                               : 'Light Novels World',
	'myotterspace.com'                                : 'Otterspace Translation',
	'zxzxzx.info'                                     : 'Zxzxzx\'s Blog',
	'www.endofdoom.com'                               : 'End of Doom MTL',
	'www.kencephalontranslations.com'                 : 'Kencephalon Translations',
	'www.lesyt.xyz'                                   : 'LESYT',
	'www.pathoftranslation.com'                       : 'Path of Translation',
	'www.rainbowturtletranslation.com'                : 'Rainbow Turtle Translations',
	'www.steadytranslation.com'                       : 'Steady Translation',
	'chillock.wordpress.com'                          : 'Anime, manga, translations',


	'alatpengeras.blogspot.com'                     : 'Toaaa~~~',
	'dreamygetaway.blogspot.com'                      : 'Shova Translations',
	'exploreandtry.blogspot.com'                       : 'Explore',
	'frozensama.blogspot.com'                         : 'Frozen\'s Lazy Blog',
	'jolecole.blogspot.com'                           : 'JoleCole\'s Station',
	'kuromin9.blogspot.com'                           : 'Kuromin',
	'novelstranslation.blogspot.com'                  : 'Novels Translation',
	'sabishiidesu.blogspot.com'                       : 'Sabishii desu!!',
	'timebun.blogspot.com'                            : 'Timebun Translations',
	'usawdemon.blogspot.com'                        : 'Fake USAW Translation',
	'amberos.livejournal.com'                         : 'Obsessive Dreamer',
	'hakureina.livejournal.com'                       : 'Hakureina',
	'hiirowing.livejournal.com'                       : 'Shirohane',
	'niiselin.livejournal.com'                        : 'Niiselin',
	'chendaere.tumblr.com'                            : 'Meteor Ranger T.',
	'happythexceed.tumblr.com'                        : 'Happythexceed の Corner',
	'hisokasasss.tumblr.com'                          : 'I only want Shinji.',
	'imayooshi.tumblr.com'                            : 'Chaotic Neutral',
	'kiyoitsukikage.tumblr.com'                       : 'Kiyoitsukikage',
	'marchen-v-friedhof.tumblr.com'                   : 'The Place Closest to Heaven',
	'shou7.tumblr.com'                                : 'Pajama Days',
	'x0401x.tumblr.com'                               : 'Open The Sky',
	'50centtranslations.wordpress.com'                : '50% Translations',
	'absurdtl.wordpress.com'                          : 'Absurd Translation',
	'alchyr.wordpress.com'                            : 'Alchyr does things',
	'apurpleblob.wordpress.com'                       : 'A Purple Blob',
	'arsl31.wordpress.com'                            : 'AeRoSoL31',
	'artegthebear.wordpress.com'                      : 'Arteg the Bear',
	'asthmaticspider.wordpress.com'                   : 'Asthmatic Spider Translations',
	'avaritiakuns.wordpress.com'                      : 'Avaritia-kun',
	'bionicarktranslations.wordpress.com'             : 'Bionicark Translations',
	'boyslovetranslations.wordpress.com'              : 'Wisteria Translations',
	'cagedbramblings.wordpress.com'                   : 'Caged Bramblings In A Pavilion',
	'chaoticswordoftl.wordpress.com'                  : 'Chaotic Sword Translations',
	'chaotictranslations.wordpress.com'               : 'Chaotic Translations',
	'circatrans.wordpress.com'                        : 'Circa Translations',
	'clesesia.wordpress.com'                          : 'Clesesia Blogspot~',
	'daikyuntl.wordpress.com'                         : 'Daikyun Translations',
	'deathknightnovel.wordpress.com'                  : 'Death Knight',
	'dysrysummaries.wordpress.com'                    : 'Dysry Summaries',
	'edltranslation.wordpress.com'                    : 'Eternal Dreamland Translation',
	'egsmarttranslation.wordpress.com'                : 'EG-Smart-Translation',
	'egsnblog.wordpress.com'                          : 'EGSN Blog',
	'failtranslations.wordpress.com'                  : 'FailTranslations',
	'fairlyaccuratetranslations.wordpress.com'        : 'Fairly Accurate Translations',
	'feelsbadtranslations.wordpress.com'              : 'Feels Bad Translations',
	'fuwafuwatales.wordpress.com'                     : 'Fuwa Fuwa Tales~',
	'hellsingfederation.wordpress.com'                : 'Hellsing Federation Translations',
	'jynkitl.wordpress.com'                           : 'Jynki\'s TLs',
	'kurossite.wordpress.com'                         : 'Kuros TL',
	'kusomtl.wordpress.com'                           : 'Kuso Machine Translation',
	'lionmaskrpt.wordpress.com'                       : 'Lion Mask\'s Really Professional Translations',
	'mightynovels.wordpress.com'                      : 'Almighty Athlete',
	'mofumofutranslation.wordpress.com'               : 'Mofumofu Translation',
	'moonlighttranslations.wordpress.com'             : 'Moonlight Translations',
	'paichuntranslations.wordpress.com'               : 'Paichun Translations',
	'planttranslation.wordpress.com'                  : 'Plant Translation',
	'professionalgamethrower.wordpress.com'           : 'ProfessionalGameThrower\'s Translations',
	'scumbagtranslations.wordpress.com'               : 'Scum Bag Translation',
	'segmeton.wordpress.com'                          : 'Segmeton Translation',
	'sereneandtranquil.wordpress.com'                 : 'Serene and Tranquil',
	'sinistertranslations.wordpress.com'              : 'Sinister Translations',
	'sodtranslations.wordpress.com'                   : 'Sod Translations',
	'starvecleric.wordpress.com'                      : 'StarveCleric',
	'tsubakitranslation.wordpress.com'                : 'Tsubaki Translation',
	'twkisanotaku.wordpress.com'                      : 'Twki-san Otaku',
	'veetranslation.wordpress.com'                    : 'Vee Translation',
	'vestigetranslations.wordpress.com'               : 'Vestige Translations',
	'whatevertranslations.wordpress.com'              : 'Whatever Translations MTL',
	'wuxialover.wordpress.com'                        : 'Wuxia Lovers',
	'xytranslations.wordpress.com'                    : 'Xiaoyuu\'s Translations',
	'yumeabyss.wordpress.com'                         : 'Yumeabyss',
	'sabishidesu.tk'                                  : 'Japanese Novel Translation',
	'www.scarletmadness.org'                          : 'Scarlet Madness',
	'trytranslations.com'                             : 'TryTranslations/The Busy One',
	'seonbinovels.com'                                : 'Seonbi Novels',
	'selftaughtjapanese.com'                          : 'Self Taught Japanese ',
	'scrya.org'                                       : 'Scrya Translations',
	'saiakutranslationsblog.com'                      : 'SaiakuTranslationsblog',
	'rebirth.online'                                  : 'Rebirth Online World',
	'noveltranslation.net'                            : 'Yasashi Honyaku',
	'kobatochan.com'                                  : 'KobatoChanDaiSukiScan',
	'infinitenoveltranslations.net'                   : 'Infinite Novel Translations',
	'hamster428.com'                                  : 'Hamster428',
	'grandlation.com'                                 : 'Grandlation',
	'ajrg.me'                                         : 'AJRG',
	'www.vikingstoryteller.com'                       : 'The Viking Story Teller',
	'fantasy-books.live'                              : 'Fantasy-Books',

	'bersekertranslations.blogspot.com'               : 'Berseker Translations',
	'bubujingxinenglish.blogspot.com'                 : 'Startling Surprises at Every Step',
	'fantasybooksforever.blogspot.com'                : 'Fantasy Novels',
	'istlovesu.blogspot.com'                          : 'Istian\'s Workshop',
	'mahoukoukoku.blogspot.com'                       : 'Mahou Koukoku',
	'thenakedsol.blogspot.com'                        : 'Iterations within a Thought-Eclipse',
	'xcrossj.blogspot.com'                            : 'XCrossJ',
	'guroslibrary.blogspot.com'                       : 'Guro\'s Library of Stories',
	'xiakeluojiao.blogspot.com'                       : 'Xiakeluojiao 侠客落脚',
	'imperatorarcana.blogspot.com'                    : 'Imperator',
	'www.xianxiaworld.net'                            : 'Xian Xia World',
	'www.lightnovelbastion.com'                       : 'Light Novel Bastion',
	'lightnovelbastion.com'                           : 'Light Novel Bastion',
	'www.ultimaguil.org'                              : 'Ultimaguil Base',
	'ultimaguil.org'                                  : 'Ultimaguil Base',
	'www.hasutsuki.com'                               : 'Hasutsuki',
	'chongmeitranslations.weebly.com'                 : 'Chongmei Translations',
	'hakushakutoyousei.weebly.com'                    : 'Hakushaku to Yousei',
	'fleetingphoenix.weebly.com'                      : 'Fleeting Phoenix Translations',
	'transtranstrans.hatenablog.com'                  : 'Ainushi Translations 愛主の翻訳',
	'www.avertranslation.org'                         : 'Avert Translations~',
	'novel.oddsquad.org'                              : 'Odd Squad Novels',
	'firegirlthetranslation.wordpress.com'            : '(NanoDesu) - The Fire Girl',
	'grimgarthetranslation.wordpress.com'             : '(NanoDesu) - Hai to Gensou no Grimgar',
	'sakaro44.wordpress.com'                          : 'Light Novels',
	'zeromahouthetranslation.wordpress.com'           : '(NanoDesu) - Zero Kara Hajimeru Mahou no Sho!',
	'www.subudai11.com'                               : 'Subudai11',
	'endofdoom.com'                                   : 'End of Doom MTL',
	'fakeftranslations.com'                           : 'Fake Fruit Translation',
	'lesyt.xyz'                                       : 'LESYT',
	'mojotranslations.com'                            : 'Mojo Translations',
	'nakimushitl.com'                                 : 'Nakimushi',
	'novelsground.com'                                : 'Novels Ground',
	'paichuntranslations.com'                         : 'Paichun Translations',
	'rainbowturtletranslation.com'                    : 'Rainbow Turtle Translations',
	'readingattic.com'                                : 'Reading Attic',
	'royalnovel.com'                                  : 'Royal Novel',
	'shinsori.com'                                    : 'Shinsori Translations',
	'slothtranslations.com'                           : 'Sloth Translations',
	'www.mtlhex.com'                                  : 'For Kalimdor!',
	'www.noodletowntranslated.com'                    : 'Noodletown Translated',



	# Redirect loop.
	'lightnovelcafe.com'                              : 'Light Novel Cafe',


	# Low quality
	'owari-owari.tumblr.com'                          : '♥ yenney ♥',
	'chilly-territory.tumblr.com'                     : 'Chilly Territory',
	'theyseemewhalin.tumblr.com'                      : 'The Captain\'s Log',

	# Currently empty?
	'evernightblog.wordpress.com'                     : 'Ever Night Blog',

	# Private
	'hereticlnt.blogspot.com'                          : 'hereticlnt.blogspot.com',
	'heartlapsed.wordpress.com'                       : 'heartlapsed.wordpress.com',
	'slothfulworks.wordpress.com'                     : 'slothfulworks.wordpress.com',

	# Gone
	'thepaperfictions.wordpress.com'                  : 'thepaperfictions.wordpress.com',
	'namelesstranslation.wordpress.com'               : 'namelesstranslation.wordpress.com',

	# Broken?
	'novelcow.com'                                    : 'NovelCow',

	# Removed:
	'ciaranhillock.blogspot.com'                      : 'ciaranhillock.blogspot.com',
	'mousou-haven.com'                                : 'Mousou Haven',

	# Now a scumware site?
	'ruzetranslations.org'                            : 'ruzetranslations.org',


	# Garbage or non-translation blogs:
	'cacatuasulphureacitrinocristata.tumblr.com'      : 'cacatuasulphureacitrinocristata.tumblr.com',  # 'A lil\' shipping never hurts',   # More naruto bs
	'raspomme.tumblr.com'                             : 'raspomme.tumblr.com',                         # 'Soup Fanclub',            # raspomme.tumblr.com/rss
	'shuuen-scans.tumblr.com'                         : 'shuuen-scans.tumblr.com',                     # 'Shuuen Scanlations',        # shuuen-scans.tumblr.com/rss



	# Fix things
	'Rosy Fantasy' : 'Rosyfantasy - Always Dreaming',


}

def getNiceName(srcurl, netloc=None, debug=False):
	if netloc:
		srcnetloc = netloc
	else:
		srcnetloc = urllib.parse.urlparse(srcurl).netloc

	orig = srcnetloc

	# Blogspot domains are coerced to ".com" since they seem to localize their TLD,
	# and somehow it all points to the same place in the end.
	if ".blogspot." in srcnetloc and not ".blogspot.com" in srcnetloc:
		prefix = srcnetloc.split(".blogspot.")[0]
		srcnetloc = prefix + ".blogspot.com"

	if debug:
		print("Netlocs: ", (orig, srcnetloc))

	if srcnetloc in mapper:
		return mapper[srcnetloc]

	return False
