
import urllib.parse


def getNiceName(srcurl):
	mapper = {

		"asherahbluenotebook.wordpress.com"         : "AsherahBlue's Notebook",
		"durasama.wordpress.com"                    : "Durasama",
		"ensjtrans.wordpress.com"                   : "Ensj Translations",
		"entruce.wordpress.com"                     : "EnTruce Translations",
		"erosworkshop.blogspot.com"                 : "Eros Workshop",
		"forgetfuldreamer.wordpress.com"            : "Forgetful Dreamer",
		"fudgetranslations.wordpress.com"           : "Fudge Translations",
		"izra709.com"                               : "izra709 | B Group no Shounen Translations",
		"koongkoongtranslations.wordpress.com"      : "Koong Koong Translations",
		"rebirthonlineworld.com"                    : "Rebirth Online World",
		"shikkakutranslations.wordpress.com"        : "Shikkaku Translations",
		"sousetsuka.blogspot.com"                   : "Sousetsuka",
		"tototr.com"                                : "Totokk\'s Translations",
		"tototrans.wordpress.com"                   : "Totokk\'s Translations",
		"translationraven.wordpress.com"            : "Translation Raven",
		"unchainedtranslation.wordpress.com"        : "Unchained Translation",
		"zoengsaiwaa.wordpress.com"                 : "ZSW",
		'9ethtranslations.wordpress.com'            : 'TheLazy9',
		'a0132.blogspot.com'                        : 'A0132',
		'aflappyteddybird.wordpress.com'            : 'AFlappyTeddyBird',
		'ahoujicha.blogspot.com'                    : 'Roasted Tea',
		'alcsel.wordpress.com'                      : 'Alcsel Translations',
		'aldnoahextrathetranslation.wordpress.com'  : '(NanoDesu) - Aldnoah Zero',
		'alyschu.wordpress.com'                     : 'Alyschu & Co',
		'amaburithetranslation.wordpress.com'       : '(NanoDesu) - Amagi Brilliant Park ',
		'archivitysite.wordpress.com'               : 'Archivity',
		'arkmachinetranslations.com'                : 'Ark Machine Translations',
		'avertranslation.com'                       : 'Avert Translations',
		'avertranslation.org'                       : 'Avert Translations',
		'azureskytls.blogspot.com'                  : 'Azure Sky Translation',
		'bakadogeza.blogspot.com'                   : 'Baka Dogeza Translation',
		'bingnovels.wordpress.com'                  : 'Binggo&Corp',
		'binhjamin.wordpress.com'                   : 'Binhjamin',
		'blazingtranslations.com'                   : 'Blazing Translations',
		'bluesilvertranslations.wordpress.com'      : 'Blue Silver Translations',
		'bureidanworks.wordpress.com'               : 'Burei Dan Works',
		'calicoxtabby.wordpress.com'                : 'Calico x Tabby',
		'cetranslation.blogspot.com'                : 'C.E. Light Novel Translations',
		'choukun.wordpress.com'                     : 'ELYSION Translation',
		'clickyclicktranslation.blogspot.com'       : 'Clicky Click Translation',
		'clover7snook.wordpress.com'                : 'Clover\'s Nook',
		'ctrlalcala.wordpress.com'                  : 'CtrlAlcalá',
		'darkfishoftherevolution.wordpress.com'     : 'A fish once said this to me',
		'darktranslations.wordpress.com'            : 'Dark Translations',
		'defiring.wordpress.com'                    : 'Defiring',
		'dlingson.wordpress.com'                    : 'Lingson\'s Translations',
		'dreadfuldecoding.blogspot.com'             : 'Dreadful Decoding',
		'durandaru.wordpress.com'                   : 'Duran Daru Translation',
		'eztranslations.wordpress.com'              : 'EZ Translations',
		'fateapocryphathetranslation.wordpress.com' : '(NanoDesu) - Fate/Apocrypha',
		'flowerbridgetoo.com'                       : 'Flower Bridge Too',
		'flowerbridgetoo.wordpress.com'             : 'Flower Bridge Too',
		'fuyuugakuenthetranslation.wordpress.com'   : '(NanoDesu) - Fuyuu Gakuen no Alice and Shirley',
		'gekkahimethetranslation.wordpress.com'     : '(NanoDesu) - Gekka no Utahime to Magi no Ou',
		'gilatranslationmonster.wordpress.com'      : 'Gila Translation Monster',
		'giraffecorps.liamak.net'                   : 'Giraffe Corps',
		'gjbuthetranslation.wordpress.com'          : '(NanoDesu) - GJ-Bu',
		'gravitytales.com'                          : 'Gravity Tales',
		'gravitytranslations.com'                   : 'Gravity Translation',
		'grimgalthetranslation.wordpress.com'       : '(NanoDesu) - Hai to Gensou no Grimgal',
		'guhehe.net'                                : 'guhehe.TRANSLATIONS',
		'gurotranslation.blogspot.com'              : 'Guro Translation',
		'hajiko.wordpress.com'                      : 'Hajiko translation',
		'heartcrusadescans.wordpress.com'           : 'Heart Crusade Scans',
		'hellotranslations.wordpress.com'           : 'Hello Translations',
		'hellping.org'                              : 'Hellping',
		'hendricksensama.wordpress.com'             : 'Hendricksen-sama',
		'hennekothetranslation.wordpress.com'       : '(NanoDesu) - Hentai Ouji to Warawanai Neko',
		'henoujikun.wordpress.com'                  : 'Henouji Translation',
		'hikuosan.blogspot.com'                     : 'ヾ(。￣□￣)ﾂ',   # I can haz UTF-8 source code?
		'hokagetranslations.wordpress.com'          : 'Hokage Translations',
		'hui3r.wordpress.com'                       : 'Fanatical',
		'imoutoliciouslnt.blogspot.com'             : 'Imoutolicious Light Novel Translations',
		'infinitenoveltranslations.wordpress.com'   : 'Infinite Novel Translations',
		'insigniapierce.wordpress.com'              : 'Insignia Pierce',
		'isekaicyborg.wordpress.com'                : 'Isekai Soul-Cyborg Translations',
		'isekaimahou.wordpress.com'                 : 'Isekai Mahou Translations!',
		'istlovesu.blogspot.com'                    : 'Istian\'s Workshop',
		'itranslateln.wordpress.com'                : 'itranslateln',
		'izra709.wordpress.com'                     : 'izra709 | B Group no Shounen Translations',
		'japtem.com'                                : 'Japtem',
		'jawztranslations.blogspot.com'             : 'JawzTranslations',
		'kaezartranslations.blogspot.com'           : 'Kaezar Translations',
		'kamitranslation.wordpress.com'             : 'Kami Translation',
		'kerambitnosakki.wordpress.com'             : 'Kerambit\'s Incisions',
		'kirikotranslations.wordpress.com'          : 'Kiriko Translations',
		'kirikotranslations.wordpress.com'          : 'Kiriko Translations',
		'kirileaves.wordpress.com'                  : 'Kiri Leaves',
		'kobatochandaisuki.wordpress.com'           : 'KobatoChanDaiSukiScan',
		'korezombiethetranslation.wordpress.com'    : '(NanoDesu) - Kore wa Zombie Desu ka?',
		'krytykal.org'                              : 'Krytyk\'s Translations',
		'kurenaithetranslation.wordpress.com'       : '(NanoDesu) - Kurenai',
		'kurotsuki-novel.blogspot.com'              : 'Kurotsuki Novel',
		'kyakka.wordpress.com'                      : 'Kyakka Translations',
		'kyakka.wordpress.com'                      : 'Kyakka',
		'larvyde.wordpress.com'                     : 'Larvyde',
		'lasolistia.com'                            : 'HaruPARTY',
		'lazyneet.wordpress.com'                    : 'Lazy NEET Translations',
		'lnaddiction.wordpress.com'                 : 'Ln Addiction',
		'loliquent.wordpress.com'                   : 'Loliquent',
		'lorcromwell.wordpress.com'                 : 'LorCromwell',
		'lordofscrubs.wordpress.com'                : 'LordofScrubs',
		'loveyouthetranslation.wordpress.com'       : '(NanoDesu) - Love★You',
		'lygartranslations.wordpress.com'           : 'LygarTranslations',
		'madospicy.wordpress.com'                   : 'MadoSpicy TL',
		'mahoukoukoku.blogspot.com'                 : 'Mahou Koukoku',
		'mahoutsuki.wordpress.com'                  : 'Mahoutsuki Translation',
		'manga0205.wordpress.com'                   : 'Manga0205 Translations',
		'maoyuuthetranslation.wordpress.com'        : '(NanoDesu) - Maoyuu Maou Yuusha',
		'mayochikithetranslation.wordpress.com'     : '(NanoDesu) - Mayo Chiki',
		'metalhaguremt.wordpress.com'               : '1HP',
		'nakulas.blogspot.com'                      : '[nakulas]',
		'nanodesutranslations.wordpress.com'        : 'NanoDesu Light Novel Translations',
		'natsutl.wordpress.com'                     : 'Natsu TL',
		'neettranslations.wordpress.com'            : 'NEET Translations',
		'netblazer.wordpress.com'                   : 'Blazing Translations',
		'nightbreezetranslations.com'               : 'Nightbreeze Translations',
		'nightraccoon.wordpress.com'                : 'Konjiki no Wordmaster',
		'nohohontranslations.wordpress.com'         : 'Nohohon Translation',
		'noitl.blogspot.com'                        : 'Translation Treasure Box',
		'ohanashimi.wordpress.com'                  : 'Ohanashimi',
		'ojamajothetranslation.wordpress.com'       : '(NanoDesu) - Ojamajo Doremi',
		'omegaharem.wordpress.com'                  : 'Omega Harem',
		'oniichanyamete.wordpress.com'              : 'お兄ちゃん、やめてぇ！',
		'oregairuthetranslation.wordpress.com'      : '(NanoDesu) - Yahari Ore no Seishun Love Come wa Machigatteiru',
		'oreimothetranslation.wordpress.com'        : '(NanoDesu) - Oreimo',
		'otterspacetranslation.wordpress.com'       : 'otterspacetranslation',
		'pandafuqtranslations.wordpress.com'        : 'pandafuqtranslations',
		'pandatranslations.net'                     : 'pandafuqtranslations',
		'panofitrans.blogspot.com'                  : 'Translations From Outer Space',
		'pikatranslations.com'                      : 'Pika Translations',
		'pikatranslations.wordpress.com'            : 'Pika Translations',
		'pirateyoshi.wordpress.com'                 : 'Ziru\'s Musings | Translations~',
		'pummels.wordpress.com'                     : 'Pummels Translations',
		'putttytranslations.wordpress.com'          : 'putttytranslations',
		'reantoanna.wordpress.com'                  : 'ℝeanとann@',
		'rebirthonlinelightnovel.wordpress.com'     : 'Rebirth Online',
		'reddragontranslations.wordpress.com'       : 'Red Dragon Translations',
		'rhinabolla.wordpress.com'                  : 'Rhinabolla',
		'rokkathetranslation.wordpress.com'         : '(NanoDesu) - Rokka no Yuusha',
		'ruzetranslations.wordpress.com'            : 'Ruze Translations',
		'saekanothetranslation.wordpress.com'       : '(NanoDesu) - Saenai Heroine no Sodatekata',
		'sakurahonyaku.wordpress.com'               : '桜翻訳! | Light novel translations',
		'sasamisanthetranslation.wordpress.com'     : '(NanoDesu) - Sasami-San@Ganbaranai',
		'scryatranslations.wordpress.com'           : 'Scrya Translations',
		'seizonthetranslation.wordpress.com'        : '(NanoDesu) - Seitokai no Ichizon',
		'sekaigamethetranslation.wordpress.com'     : '(NanoDesu) - Kono Sekai ga Game Dato Ore Dake ga Shitteiru',
		'setsuna86blog.wordpress.com'               : 'SETSUNA86BLOG',
		'shincodezeroblog.wordpress.com'            : 'Code-Zero\'s Blog',
		'shinsekai.cadet-nine.org'                  : 'Shin Sekai Yori – From the New World',
		'shintranslations.com'                      : 'Shin Translations',
		'shintranslations.wordpress.com'            : 'Shin Translations',
		'shiroyukitranslations.com'                 : 'Shiroyukineko Translations',
		'shokyuutranslations.wordpress.com'         : 'Shokyuu Translations',
		'skythewood.blogspot.com'                   : 'Skythewood translations',
		'skyworldthetranslation.wordpress.com'      : '(NanoDesu) - Sky World',
		'sotranslations.wordpress.com'              : 'Supreme Origin Translations',
		'stcon.wordpress.com'                       : 'Stellar Transformation Con.',
		'stltranslations.wordpress.com'             : 'STL Translations',
		'superpotatotrans.wordpress.com'            : 'Super Potato Translations',
		'swordandgame.blogspot.com'                 : 'Sword and Game',
		'sylver135.wordpress.com'                   : 'Sylver Translations',
		'tensaitranslations.wordpress.com'          : 'Tensai Translations',
		'thatguywhosthere.wordpress.com'            : 'ThatGuyOverThere',
		'thenakedsol.blogspot.com'                  : 'Iterations within a Thought-Eclipse',
		'theworsttranslation.wordpress.com'         : 'Bad Translation',
		'thundertranslations.com'                   : 'Thunder Translation',
		'thundertranslations.wordpress.com'         : 'Thunder Translation',
		'tomorolls.wordpress.com'                   : 'Tomorolls',
		'tony-yon-ka.blogspot.com'                  : 'Tony Yon Ka',
		'tony-yon-ka.blogspot.com.au'               : 'Tony Yon Ka',
		'totobro.com'                               : 'Totokk\'s Translations',
		'tototrans.com'                             : 'Totokk\'s Translations',
		'translatedbyaclown.wordpress.com'          : 'Translated by a Clown',
		'trippingoverwn.wordpress.com'              : 'Tripp Translations',
		'tsaltranslation.wordpress.com'             : 'Light Novel translations',
		'tsuigeki.wordpress.com'                    : 'Tsuigeki Translations',
		'tu-shu-guan.blogspot.com'                  : '中翻英圖書館 Translations',
		'turb0translation.blogspot.com'             : 'Turb0 Translation',
		'tusjecht.wordpress.com'                    : 'Tus-Trans',
		'typemoondb.wordpress.com'                  : 'CapsUsingShift Tl',
		'unbreakablemachinedoll.wordpress.com'      : 'Unbreakable Machine Doll',
		'undecentlnt.wordpress.com'                 : 'Undecent Translations',
		'unlimitednovelfailures.mangamatters.com'   : 'Unlimited Novel Failures',
		'untuned-strings.blogspot.com'              : 'Untuned Translation Blog',
		'vaancruze.wordpress.com'                   : 'VaanCruze',
		'voidtranslations.wordpress.com'            : 'Void Translations',
		'wartdf.wordpress.com'                      : 'Raising the Dead',
		'raisingthedead.ninja'                      : 'Raising the Dead',
		'wcctranslation.wordpress.com'              : 'WCC Translation',
		'webnoveltranslations.blogspot.com'         : 'Neo Translations',
		'webnoveltranslations.blogspot.se'          : 'Neo Translations',
		'worldofwatermelons.com'                    : 'World of Watermelons',
		'www.deadlylegends.com'                     : 'Deadly Forgotten Legends',
		'www.lingson.com'                           : 'Lingson\'s Translations',
		'www.princerevolution.org'                  : 'Prince Revolution!',
		'www.risingdragonstranslation.com'          : 'Rising Dragons Translation',
		'www.sousetsuka.com'                        : 'Sousetsuka',
		'www.taptaptaptaptap.net'                   : 'tap-trans » tappity tappity tap.',
		'www.translationnations.com'                : 'Translation Nations',
		'www.wuxiatranslations.com'                 : 'Wuxia Translations',
		'www.wuxiaworld.com'                        : 'Wuxiaworld',
		'xcrossj.blogspot.com'                      : 'XCrossJ',
		'yoraikun.wordpress.com'                    : 'Yoraikun Translation',
		'youtsubasilver.wordpress.com'              : 'youtsubasilver\'s Blog',
		'zmunjali.wordpress.com'                    : 'Roxism HQ',
		'novicetranslator.wordpress.com'            : 'NoviceTranslator',

		'yukkuri-literature-service.blogspot.com'   : 'Yukkuri Free Time Literature Service',
		'bersekertranslations.blogspot.com'         : 'Berseker Translations',
		'dreamsleeper87.blogspot.com'               : 'Lunate',
		'cnovelproject.blogspot.com'                : 'The C-Novel Project',

		'bubujingxinenglish.blogspot.com'           : 'Bu Bu Jing Xin Translation',

		'beehugger.wordpress.com'                   : 'Beehugger',
		'rancerqz.wordpress.com'                    : 'RANCER',
		'moonbunnycafe.com'                         : 'Moon Bunny Cafe',



		"feedproxy.google.com"                      : "FeedProxy",

		"dragomircm.com"                            : "DragomirCM",
		"mike777ac.wordpress.com"                   : "Mike777ac",

		"87percenttranslation.wordpress.com"        : "87 Percent Translation",
		'12superlatives.wordpress.com'              : '12 Superlatives',
		'77novel.com'                               : '77 Novel',
		'addnewtab.wordpress.com'                   : 'Lost in Translation',
		'aelyiyue.wordpress.com'                    : 'Yi Yue Translation',
		'ahasintsoa.wordpress.com'                  : 'Pea\'s Kingdom',
		'anonempireblog.wordpress.com'              : 'Anon Empire',
		'aoritranslations.wordpress.com'            : 'Aori Translations',
		'apearlyview.wordpress.com'                 : 'A Pearly View',
		'aquascans.wordpress.com'                   : 'Aqua Scans',
		'azurillturtle.blogspot.com'                : '輝く世界',
		'azurro4cielo.wordpress.com'                : 'Azurro 4 Cielo',
		'bcat00.wordpress.com'                      : 'Bcat00 Translation',
		'bearbeartranslations.wordpress.com'        : 'Bear Bear Translations',
		'berserksite.wordpress.com'                 : 'BeRsErk Translations',
		'bltranslation.blogspot.com'                : 'Chinese BL Translations',
		'canonrap.wordpress.com'                    : 'Quality ★ Mistranslations',
		'casteliacones.wordpress.com'               : 'Cheddar!',
		'cathdeary.wordpress.com'                   : 'Romantic Dreamer\'s Sanctuary',
		'ceruleonice.wordpress.com'                 : 'Ceruleonice Translations',
		'chineseweabootranslations.wordpress.com'   : 'Chinese Weaboo Translations',
		'circleofshards.wordpress.com'              : 'Circle of Shards',
		'circustranslations.com'                    : 'Circus Translations',
		'cloudmanor.wordpress.com'                  : 'Cloud Manor',
		'cnovels.bookbychapters.com'                : 'Lil\' Bliss Novels',
		'cnovels2c.wordpress.com'                   : 'C Novels 2 C',
		'cookiepastatranslations.wordpress.com'     : 'CookiePasta Translations',
		'cosmictranslation.wordpress.com'           : 'Cosmic Translation',
		'crimsonkisato.blogspot.com'                : 'Kisato\'s MLTs',
		'd3wynightunr0lls.wordpress.com'            : 'Dewey Night Unrolls',
		'dailehtranslations.wordpress.com'          : 'NOT Daily Translations',
		'daoseekerblog.wordpress.com'               : 'Dao Seeker Blog',
		'dawninghowls.wordpress.com'                : 'Dawning Howls',
		'defan752.wordpress.com'                    : 'Defan\'s Translations',
		'demontranslations.com'                     : 'Demon Translations',
		'descentsubs.wordpress.com'                 : 'Descent Subs',
		'distractedtranslations.wordpress.com'      : 'Distracted Translations',
		'diwasteman.wordpress.com'                  : 'Diwasteman',
		'dorayakiz.wordpress.com'                   : 'Dorayakiz',
		'dreamavenuee.wordpress.com'                : 'Dream Avenue',
		'ecwebnovel.blogspot.com'                   : 'EC Webnovel',

		'endkun.wordpress.com'                      : 'EndKun',
		'endonline.wordpress.com'                   : 'End Online Novel',
		'ente38.wordpress.com'                      : 'Ente38 translations',
		'epyontranslations.wordpress.com'           : 'Epyon Translations',
		'erolns.blogspot.com'                       : 'Ero Light Novel Translations',


		'etheriatranslation.wordpress.com'          : 'etheriatranslation.wordpress.com',
		'eugene-rain.com'                           : 'eugene-rain.com',
		'eyeofadventure.wordpress.com'              : 'eyeofadventure.wordpress.com',
		'faildoor.wordpress.com'                    : 'faildoor.wordpress.com',
		'farmerbob1.wordpress.com'                  : 'farmerbob1.wordpress.com',
		'fightingdreamersscanlations.wordpress.com' : 'fightingdreamersscanlations.wordpress.com',
		'fivestarspecialists.wordpress.com'         : 'fivestarspecialists.wordpress.com',
		'flickerhero.wordpress.com'                 : 'flickerhero.wordpress.com',
		'forgottenconqueror.wordpress.com'          : 'forgottenconqueror.wordpress.com',
		'fromwhencecamethenamed.wordpress.com'      : 'fromwhencecamethenamed.wordpress.com',
		'fungshen.wordpress.com'                    : 'fungshen.wordpress.com',
		'fuzionlife.wordpress.com'                  : 'fuzionlife.wordpress.com',
		'gargoyleserial.wordpress.com'              : 'gargoyleserial.wordpress.com',
		'ginironochou.wordpress.com'                : 'ginironochou.wordpress.com',
		'goddessgrantmeagirlfriend.wordpress.com'   : 'goddessgrantmeagirlfriend.wordpress.com',
		'hamster428.wordpress.com'                  : 'hamster428.wordpress.com',
		'holdxandclick.wordpress.com'               : 'holdxandclick.wordpress.com',
		'hotcocoatranslations.wordpress.com'        : 'hotcocoatranslations.wordpress.com',
		'ichigoichiebanzai.wordpress.com'           : 'ichigoichiebanzai.wordpress.com',
		'imperialwinters.wordpress.com'             : 'imperialwinters.wordpress.com',
		'infinitetranslations.wordpress.com'        : 'infinitetranslations.wordpress.com',
		'isekailunatic.wordpress.com'               : 'isekailunatic.wordpress.com',
		'isolarium.wordpress.com'                   : 'isolarium.wordpress.com',
		'itslovetranslation.blogspot.com'           : 'itslovetranslation.blogspot.com',
		'jjagaimo.wordpress.com'                    : 'jjagaimo.wordpress.com',
		'jntranslation.wordpress.com'               : 'jntranslation.wordpress.com',
		'joeglens.com'                              : 'joeglens.com',
		'kahoim.wordpress.com'                      : 'kahoim.wordpress.com',
		'kakemonoko.wordpress.com'                  : 'kakemonoko.wordpress.com',
		'kedelu.wordpress.com'                      : 'kedelu.wordpress.com',
		'kingjaahn.wordpress.com'                   : 'kingjaahn.wordpress.com',
		'knoktranslations.wordpress.com'            : 'knoktranslations.wordpress.com',
		'kntranslation.wordpress.com'               : 'kntranslation.wordpress.com',
		'koreyorihachidori.wordpress.com'           : 'koreyorihachidori.wordpress.com',
		'kumaotou.wordpress.com'                    : 'kumaotou.wordpress.com',
		'lastexorcist.wordpress.com'                : 'lastexorcist.wordpress.com',
		'lastvoicetranslator.wordpress.com'         : 'lastvoicetranslator.wordpress.com',
		'layzisheep.wordpress.com'                  : 'layzisheep.wordpress.com',
		'legendofgalacticheroes.blogspot.com'       : 'legendofgalacticheroes.blogspot.com',
		'linkedtl.wordpress.com'                    : 'linkedtl.wordpress.com',
		'liveandlearn88.wordpress.com'              : 'liveandlearn88.wordpress.com',
		'lizardtranslations.wordpress.com'          : 'lizardtranslations.wordpress.com',
		'lmsmachinetranslations.com'                : 'lmsmachinetranslations.com',
		'loiterous.wordpress.com'                   : 'loiterous.wordpress.com',
		'lylisasmodeus.wordpress.com'               : 'lylisasmodeus.wordpress.com',
		'machineslicedbread.wordpress.com'          : 'machineslicedbread.wordpress.com',
		'makinatranslations.wordpress.com'          : 'makinatranslations.wordpress.com',
		'manatankmagus.wordpress.com'               : 'manatankmagus.wordpress.com',
		'martialgodtranslator.wordpress.com'        : 'martialgodtranslator.wordpress.com',
		'mechamushroomtranslations.wordpress.com'   : 'mechamushroomtranslations.wordpress.com',
		'miaomix539.wordpress.com'                  : 'miaomix539.wordpress.com',
		'midnighttranslationblog.wordpress.com'     : 'midnighttranslationblog.wordpress.com',
		'mnemeaa.wordpress.com'                     : 'mnemeaa.wordpress.com',
		'mtlcorner.blogspot.com'                    : 'mtlcorner.blogspot.com',
		'mystiquetranslations.wordpress.com'        : 'mystiquetranslations.wordpress.com',
		'nationalneet.wordpress.com'                : 'nationalneet.wordpress.com',
		'nightofthehuntingparty.wordpress.com'      : 'nightofthehuntingparty.wordpress.com',
		'noone2246.wordpress.com'                   : 'noone2246.wordpress.com',
		'novelsnao.com'                             : 'novelsnao.com',
		'nowhereandnothingwebserial.wordpress.com'  : 'nowhereandnothingwebserial.wordpress.com',
		'nuttyisprocrasinating.wordpress.com'       : 'nuttyisprocrasinating.wordpress.com',
		'oktranslation.wordpress.com'               : 'oktranslation.wordpress.com',
		'omatranslations.com'                       : 'omatranslations.com',
		'omgitsaray.wordpress.com'                  : 'omgitsaray.wordpress.com',
		'onesecondspring.blogspot.com'              : 'onesecondspring.blogspot.com',
		'orangeblossomdreams.wordpress.com'         : 'orangeblossomdreams.wordpress.com',
		'oregaheroineeng.wordpress.com'             : 'oregaheroineeng.wordpress.com',
		'otakunoeiyaku.blogspot.com'                : 'otakunoeiyaku.blogspot.com',
		'otomerevo.wordpress.com'                   : 'otomerevo.wordpress.com',
		'outspanfoster.wordpress.com'               : 'outspanfoster.wordpress.com',
		'pactwebserial.wordpress.com'               : 'pactwebserial.wordpress.com',
		'parahumans.wordpress.com'                  : 'parahumans.wordpress.com',
		'paztok.wordpress.com'                      : 'paztok.wordpress.com',
		'peatranslation.wordpress.com'              : 'peatranslation.wordpress.com',
		'pippisite.wordpress.com'                   : 'pippisite.wordpress.com',
		'plainlybored.wordpress.com'                : 'plainlybored.wordpress.com',
		'polyphonicstory.wordpress.com'             : 'polyphonicstory.wordpress.com',
		'popsiclete.blogspot.com'                   : 'popsiclete.blogspot.com',
		'pumpkintranslations.blogspot.com'          : 'pumpkintranslations.blogspot.com',
		'rainbowtranslationsblog.wordpress.com'     : 'rainbowtranslationsblog.wordpress.com',
		'rainingstardust.wordpress.com'             : 'rainingstardust.wordpress.com',
		'raltzero.wordpress.com'                    : 'raltzero.wordpress.com',
		'reddycreations.com'                        : 'reddycreations.com',
		'requirecookie.com'                         : 'requirecookie.com',
		'rosyfantasy.wordpress.com'                 : 'rosyfantasy.wordpress.com',
		'rumorblock.wordpress.com'                  : 'rumorblock.wordpress.com',
		'sabertranslations.wordpress.com'           : 'sabertranslations.wordpress.com',
		'saurimania.wordpress.com'                  : 'saurimania.wordpress.com',
		'selkinnovel.com'                           : 'selkinnovel.com',
		'shermatranslations.wordpress.com'          : 'shermatranslations.wordpress.com',
		'shinsoritranslations.wordpress.com'        : 'shinsoritranslations.wordpress.com',
		'shinynewjustice.wordpress.com'             : 'shinynewjustice.wordpress.com',
		'silvalau.wordpress.com'                    : 'silvalau.wordpress.com',
		'slimelv1.wordpress.com'                    : 'slimelv1.wordpress.com',
		'slothtranslations.wordpress.com'           : 'slothtranslations.wordpress.com',
		'snowjadeflowers.wordpress.com'             : 'snowjadeflowers.wordpress.com',
		'soaringtranslations.com'                   : 'soaringtranslations.com',
		'soratranslationsblog.wordpress.com'        : 'soratranslationsblog.wordpress.com',
		'stoneburners.wordpress.com'                : 'stoneburners.wordpress.com',
		'subudai11.com'                             : 'subudai11.com',
		'summiesdummyworld.wordpress.com'           : 'summiesdummyworld.wordpress.com',
		'sunshowerfields.wordpress.com'             : 'sunshowerfields.wordpress.com',
		'tabikonotrans.blogspot.com'                : 'tabikonotrans.blogspot.com',
		'taffygirl13.wordpress.com'                 : 'taffygirl13.wordpress.com',
		'project-accelerator.net'                   : 'project-accelerator.net',
		'taulsn.wordpress.com'                      : 'taulsn.wordpress.com',
		'terminustranslations.wordpress.com'        : 'terminustranslations.wordpress.com',
		'the4everreader.wordpress.com'              : 'the4everreader.wordpress.com',
		'theadamantinedragon.wordpress.com'         : 'theadamantinedragon.wordpress.com',
		'thecatscans.wordpress.com'                 : 'thecatscans.wordpress.com',
		'thedefend.wordpress.com'                   : 'thedefend.wordpress.com',
		'thelordofpie.blogspot.com'                 : 'thelordofpie.blogspot.com',
		'themustangtranslator.wordpress.com'        : 'themustangtranslator.wordpress.com',
		'thyaeriatranslations.com'                  : 'thyaeriatranslations.com',
		'tieshaunn.wordpress.com'                   : 'tieshaunn.wordpress.com',
		'tmbrakta.wordpress.com'                    : 'tmbrakta.wordpress.com',
		'tofubyu.wordpress.com'                     : 'tofubyu.wordpress.com',
		'totallyinsanetranlation.com'               : 'totallyinsanetranlation.com',
		'trolllancer.com'                           : 'trolllancer.com',
		'trungtnguyen123.wordpress.com'             : 'trungtnguyen123.wordpress.com',
		'tumbleintofantasy.wordpress.com'           : 'tumbleintofantasy.wordpress.com',
		'twistedcogs.wordpress.com'                 : 'twistedcogs.wordpress.com',
		'udonatewetranslate.blogspot.com'           : 'udonatewetranslate.blogspot.com',
		'ultimatearcane.wordpress.com'              : 'ultimatearcane.wordpress.com',
		'unlimitedstoryworks.wordpress.com'         : 'unlimitedstoryworks.wordpress.com',
		'uselessno4.wordpress.com'                  : 'uselessno4.wordpress.com',
		'vaancruze.com'                             : 'vaancruze.com',
		'villagetranslations.wordpress.com'         : 'villagetranslations.wordpress.com',
		'walkthejianghu.com'                        : 'walkthejianghu.com',
		'watdameow.wordpress.com'                   : 'watdameow.wordpress.com',
		'watermelonhelmets.wordpress.com'           : 'watermelonhelmets.wordpress.com',
		'weletranslation.wordpress.com'             : 'weletranslation.wordpress.com',
		'whitetigertranslations.wordpress.com'      : 'whitetigertranslations.wordpress.com',
		'wishuponahope.blogspot.com'                : 'wishuponahope.blogspot.com',
		'wolfietranslation.wordpress.com'           : 'wolfietranslation.wordpress.com',
		'wordofcraft.wordpress.com'                 : 'wordofcraft.wordpress.com',
		'wuxiaheroes.com'                           : 'wuxiaheroes.com',
		'wuxiasociety.com'                          : 'wuxiasociety.com',
		'wuxiwish.wordpress.com'                    : 'wuxiwish.wordpress.com',
		'www.lonahora.com'                          : 'www.lonahora.com',
		'www.paultwister.com'                       : 'www.paultwister.com',
		'www.radianttranslations.com'               : 'www.radianttranslations.com',
		'www.talesofmu.com'                         : 'www.talesofmu.com',
		'www.whimsicalland.com'                     : 'www.whimsicalland.com',
		'wwyxhqc.wordpress.com'                     : 'wwyxhqc.wordpress.com',
		'xantandminions.wordpress.com'              : 'xantandminions.wordpress.com',
		'xcrossj.wordpress.com'                     : 'xcrossj.wordpress.com',
		'youjinsite.com'                            : 'youjinsite.com',
		'youshokutranslations.wordpress.com'        : 'youshokutranslations.wordpress.com',
		'zentranslations.wordpress.com'             : 'zentranslations.wordpress.com',



		'dynamislightnovel.wordpress.com'           : 'Dynamis Gaul Light Novel',
		'anathemaserial.wordpress.com'              : 'Anathema Serial',
		'agreyworld.wordpress.com'                  : 'A Grey World',

		'cavescans.com'                             : 'cavescans.com',

		# Wat
		# 'booksmoviesandbeyond.blogspot.com'         : 'booksmoviesandbeyond.blogspot.com',

		# 'xxjohnsmithxx.wordpress.com'               : 'Huh',

		# OEL bits and bobs:
		# "xhawk77x.blogspot.com"                     : "wat",
		# "tieshaunn.wordpress.com"                   : "wat",
		# "the-last-skull.blogspot.com"               : "wat",
		# "taulsn.wordpress.com"                      : "wat",
		# "selkinnovel.wordpress.com"                 : "wat",
		# "rumorblock.wordpress.com"                  : "wat",
		# "paztok.wordpress.com"                      : "wat",
		# "nightofthehuntingparty.wordpress.com"      : "wat",
		# "lastexorcist.wordpress.com"                : "wat",
		# "magelifeblog.wordpress.com"                : "wat",
		# "fuzionlife.wordpress.com"                  : "wat",
		# "gargoyleserial.wordpress.com"              : "wat",
		# "farmerbob1.wordpress.com"                  : "wat",
		# "endonline.wordpress.com"                   : "wat",
		# "ecwebnovel.blogspot.com"                   : "wat",
		# "fromwhencecamethenamed.wordpress.com"      : "wat",
		# "twistedcogs.wordpress.com"                 : "wat",
		# "tmbrakta.wordpress.com"                    : "wat",
		# "xantbos.wordpress.com"                     : "wat",
		# "thezombieknight.blogspot.com"              : "wat",
		# "stoneburners.wordpress.com"                : "wat",
		# "rejecthero.wordpress.com"                  : "wat",
		# "shinynewjustice.wordpress.com"             : "wat",
		# "pactwebserial.wordpress.com"               : "wat",
		# "parahumans.wordpress.com"                  : "wat",
		# "hereticlnt.blogspot.com"                   : "wat",
		# "arzengi.blogspot.com"                      : "wat",
		# "agreyworld.wordpress.com"                  : "wat",
		# "flickerhero.wordpress.com"                 : "wat",
		# "anathemaserial.wordpress.com"              : "wat",
		# "aquarilasscenario.blogspot.com"            : "wat",

		# Removed:
		# "solitarytranslation.wordpress.com"         : "wat",

		# Porn? How did that get in here?
		# "teamkoinaka.wordpress.com"                 : "wat",

		# Accidental manga blog:
		# "thecatscans.wordpress.com"                 : "wat",
	}

	srcnetloc = urllib.parse.urlparse(srcurl).netloc

	if srcnetloc in mapper:
		return mapper[srcnetloc]

	# print("Unknown netloc?", srcnetloc)
	# print("Src url?", srcurl)
	return False
